### ISSUE TITLE
I think it need more work when I delete a AS3 ConfigMap 

### ISSUE THREAD

**Issue by luruiqiang** [F5Networks/k8s-bigip-ctlr#1000]
#### Description
When I delete a AS3 ConfigMap, I have to deploy a blank configmap, then restart the controller. I think .it need more work, I worry about sometime we may forget some step or find some error when I execute it.

Can we simply the function ? I hope that the funciton is like to delete common configmap in k8s that it only need one delete command?

#### Kubernetes Version
1.13

#### Controller Version
1.9.1

#### BIG-IP Version
12.1

**Comment by mdditt2000** [comment]
You shouldnt need to restart the controller. Just apply a blank declaration. We are taking care this in the CIS 1.10 release coming this week. 

Jira CONTCNTR-940 PM tracking

**Comment by luruiqiang** [comment]
Is it possible that I don't apply a blank ConfigMap when I delete some objects created by AS3 ? I hope that I can use one command to delete it.

**Comment by luruiqiang** [comment]
ok, please give me the early build. Thanks

**Comment by luruiqiang** [comment]
I found that 1.11 had been released last week. Whether the issue is resolved?

**Comment by luruiqiang** [comment]
it works! Thanks.

**Comment by luruiqiang** [comment]
sorry, I made a mistake. it is still an issue.

**Comment by ssurenr** [comment]
@luruiqiang It is no longer required to restart the controller. However, still, you need to deploy a blank declaration on the configmap to clear the resources on BIG-IP. This is by design.
