### ISSUE TITLE
Ingress Resource: passthrough - https service access failed

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [F5Networks/k8s-bigip-ctlr#1013]
supported Ingress annotations have been added,
then access to the http service is normal,
but accessing the https service jumps to the f5 login screen.

do I need any other configuration?

traefik sets up self-signed certificates. 
If access the dashboard directly through traefik (not through f5), the dashboard access is normal

version: 
k8s --> v1.15.3
ingress --> traefik

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/64109790-ffbd9c80-cdb2-11e9-8f15-5056544da79c.png)

Is there a configuration like openshift to set tls passthrough

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/64139030-135c1800-ce32-11e9-9798-3944f1f2b868.png)

Dashboard cannot be accessed after replacing it with a signed certificate (the secrets are under kube-system namespace)

![image](https://user-images.githubusercontent.com/46734380/64139225-b2810f80-ce32-11e9-8818-7d1271d0e466.png)

**Comment by mdditt2000** [comment]
Are you looking for a passthrough option for K8S ingress? You can use a configmap with AS3.

**Comment by mdditt2000** [comment]
created CONTCNTR-1116 for internal PM tracking

**Comment by mdditt2000** [comment]
No plan to enhance the support of Ingress at this time. This feature is now supported in CIS 2.2 using a CRD for both TCP, HTTP passthrough. With a CRD you can do TCP for both performance and standard. Please look at CIS 2.2
