### ISSUE TITLE
Ingress resource - Performance problem with large number of ingresses

### ISSUE THREAD

**Issue by codertao** [F5Networks/k8s-bigip-ctlr#1014]
#### Description
We're having a performance issue with the k8s-bigip-ctlr ; we have ~30 ingresses with unique certs being served off a single virtual server. 

I *think*, due to: https://github.com/F5Networks/k8s-bigip-ctlr/blob/11f07d9dfa6957813ac88be8a4701da7744bce67/pkg/appmanager/resourceConfig.go#L1677 , each call to appManager.updateVirtualServer pulls down, as far as I can tell, every secret used (by the virtual server?), which is taking 200ms a call. Net result is ~4 seconds for a call to updateVirtualServer, and 2-5 minutes on average for a new pod in a service to be added to the related pool. Or 2-5 minutes of downtime for rolling deployments.

#### Kubernetes Version
1.12, Amazon EKS

#### Controller Version
1.9, built in house

#### BIG-IP Version
14.0.0.1

#### Diagnostic Information
Quite awful custom logging added to processNextVirtualServer:

2019/09/03 21:32:06 [INFO] Process next virtual server some-app, queue: 44
2019/09/03 21:32:06 [INFO] Start lookup service {Namespace:staging ServiceName:some-app As3Name: As3Data:} (1.882µs)
2019/09/03 21:32:06 [INFO] Get resources for Key {Namespace:staging ServiceName:some-app As3Name: As3Data:} (26.63µs)
2019/09/03 21:32:06 [INFO] sync configmap {Namespace:staging ServiceName:some-app As3Name: As3Data:} (36.167µs)
2019/09/03 21:32:06 [INFO] sync ingress {Namespace:staging ServiceName:some-app As3Name: As3Data:} (12.498163ms)
2019/09/03 21:32:06 [INFO] . . . . . Startinng ing rule handling 402ns - 11.248µs
2019/09/03 21:32:06 [INFO] . . . . . Finished dependency stuff 16.859µs - 27.708µs
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 103.711µs - 114.608µs
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 183.947µs - 194.845µs
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 222.576µs - 233.454µs
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 276.78µs - 287.698µs
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 299.005µs - 310.022µs
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 471.841µs - 482.736µs
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 186.909165ms - 186.920066ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 186.925483ms - 186.936339ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 186.930106ms - 186.940975ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 186.934558ms - 186.945409ms
2019/09/03 21:32:06 [INFO] . . . . . Startinng ing rule handling 371ns - 186.951192ms
2019/09/03 21:32:06 [INFO] . . . . . Finished dependency stuff 215.25µs - 187.166178ms
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 348.093µs - 187.298938ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 385.578µs - 187.33641ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 390.942µs - 187.341755ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 395.258µs - 187.346077ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 399.313µs - 187.350228ms
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 469.809µs - 187.420644ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 200.117778ms - 387.068677ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 200.137152ms - 387.087978ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 200.142285ms - 387.093089ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 200.146344ms - 387.097146ms
2019/09/03 21:32:06 [INFO] . . . . . Startinng ing rule handling 404ns - 387.103101ms
2019/09/03 21:32:06 [INFO] . . . . . Finished dependency stuff 18.278µs - 387.121024ms
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 87.726µs - 387.190421ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 100.002µs - 387.202693ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 103.388µs - 387.206081ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 107.185µs - 387.209879ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 110.658µs - 387.213378ms
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 153.474µs - 387.25621ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 199.4248ms - 586.527634ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 199.443473ms - 586.546219ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 199.448655ms - 586.551348ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 199.452568ms - 586.55526ms
2019/09/03 21:32:06 [INFO] . . . . . Startinng ing rule handling 540ns - 586.561499ms
2019/09/03 21:32:06 [INFO] . . . . . Finished dependency stuff 42.239µs - 586.603236ms
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 203.912µs - 586.764889ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled TLS 230.982µs - 586.791938ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Health 244.09µs - 586.805054ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something Fast 248.926µs - 586.809883ms
2019/09/03 21:32:06 [INFO] . . . . . . Handled Something dependency related 252.354µs - 586.813323ms
2019/09/03 21:32:06 [INFO] . . . . . . Created RSConfig 336.921µs - 586.897889ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 400.678697ms - 987.23972ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 400.697332ms - 987.258274ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 400.702766ms - 987.263698ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 400.706503ms - 987.267438ms
2019/09/03 21:32:07 [INFO] . . . . . Startinng ing rule handling 646ns - 987.273742ms
2019/09/03 21:32:07 [INFO] . . . . . Finished dependency stuff 153.211µs - 987.426355ms
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 311.367µs - 987.584517ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 422.134µs - 987.695302ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 495.897µs - 987.769062ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 542.32µs - 987.815503ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 593.19µs - 987.866343ms
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 733.104µs - 988.006295ms
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 200.273384ms - 1.187546553s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 200.348007ms - 1.187621141s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 200.364473ms - 1.187637593s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 200.379149ms - 1.18765227s
2019/09/03 21:32:07 [INFO] . . . . . Startinng ing rule handling 430ns - 1.187688129s
2019/09/03 21:32:07 [INFO] . . . . . Finished dependency stuff 27.686µs - 1.187715374s
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 144.067µs - 1.187831769s
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 195.001µs - 1.187882696s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 229.148µs - 1.187916852s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 243.486µs - 1.187931171s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 256.488µs - 1.187944176s
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 330.813µs - 1.188018509s
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 199.902969ms - 1.387590749s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 199.918625ms - 1.387606301s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 199.923887ms - 1.387611594s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 199.928809ms - 1.387616513s
2019/09/03 21:32:07 [INFO] . . . . . Startinng ing rule handling 403ns - 1.387622669s
2019/09/03 21:32:07 [INFO] . . . . . Finished dependency stuff 119.481µs - 1.387741833s
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 270.67µs - 1.387893329s
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 470.728µs - 1.388093066s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 482.137µs - 1.388104428s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 557.728µs - 1.388180086s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 565.203µs - 1.388187504s
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 743.999µs - 1.388366348s
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 201.158609ms - 1.588780939s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 201.176534ms - 1.58879882s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 201.181309ms - 1.588803588s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 201.1854ms - 1.58880768s
2019/09/03 21:32:07 [INFO] . . . . . Startinng ing rule handling 1.192µs - 1.58881435s
2019/09/03 21:32:07 [INFO] . . . . . Finished dependency stuff 45.184µs - 1.588858349s
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 139.437µs - 1.588952623s
2019/09/03 21:32:07 [INFO] . . . . . . Handled TLS 152.5µs - 1.588965656s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Health 156.181µs - 1.588969321s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something Fast 159.553µs - 1.588972686s
2019/09/03 21:32:07 [INFO] . . . . . . Handled Something dependency related 162.773µs - 1.588975904s
2019/09/03 21:32:07 [INFO] . . . . . . Created RSConfig 217.388µs - 1.589030567s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 198.888979ms - 1.787702212s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 198.907467ms - 1.787720634s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 198.912657ms - 1.787725829s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 198.917543ms - 1.787730696s
2019/09/03 21:32:08 [INFO] . . . . . Startinng ing rule handling 379ns - 1.787737216s
2019/09/03 21:32:08 [INFO] . . . . . Finished dependency stuff 17.455µs - 1.787754302s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 79.372µs - 1.787816214s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 97.243µs - 1.787834071s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 101.696µs - 1.787838603s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 105.686µs - 1.787842503s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 109.356µs - 1.787846184s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 149.425µs - 1.787886245s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 199.015111ms - 1.986751983s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 199.031169ms - 1.986768002s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 199.03619ms - 1.986773012s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 199.039761ms - 1.986776576s
2019/09/03 21:32:08 [INFO] . . . . . Startinng ing rule handling 583ns - 1.98678302s
2019/09/03 21:32:08 [INFO] . . . . . Finished dependency stuff 19.379µs - 1.986801791s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 84.958µs - 1.986867389s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 98.786µs - 1.986881211s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 102.822µs - 1.986885249s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 108.124µs - 1.986890526s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 111.848µs - 1.986894258s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 147.127µs - 1.98692956s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 207.688148ms - 2.194470723s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 207.707298ms - 2.19448972s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 207.712508ms - 2.194494924s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 207.716734ms - 2.194499171s
2019/09/03 21:32:08 [INFO] . . . . . Startinng ing rule handling 7.957µs - 2.19452239s
2019/09/03 21:32:08 [INFO] . . . . . Finished dependency stuff 25.469µs - 2.194539896s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 92.558µs - 2.194606967s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 105.987µs - 2.194620383s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 109.034µs - 2.194623439s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 113.31µs - 2.194627734s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 117.138µs - 2.194631547s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 155.346µs - 2.194669755s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 200.616619ms - 2.395131136s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 200.633778ms - 2.395148192s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 200.638974ms - 2.395153398s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 200.643848ms - 2.395158272s
2019/09/03 21:32:08 [INFO] . . . . . Startinng ing rule handling 481ns - 2.395165252s
2019/09/03 21:32:08 [INFO] . . . . . Finished dependency stuff 5.20949ms - 2.400374437s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 5.296917ms - 2.400461737s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 5.312377ms - 2.400477156s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 5.315568ms - 2.400480333s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 5.318836ms - 2.400483602s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 5.321853ms - 2.400486618s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 5.346321ms - 2.400511073s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 192.027588ms - 2.587192488s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 192.25776ms - 2.587422537s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 192.265182ms - 2.587429984s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 192.27009ms - 2.587434853s
2019/09/03 21:32:08 [INFO] . . . . . Startinng ing rule handling 443ns - 2.587441479s
2019/09/03 21:32:08 [INFO] . . . . . Finished dependency stuff 21.35µs - 2.587462396s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 129.912µs - 2.587570973s
2019/09/03 21:32:08 [INFO] . . . . . . Handled TLS 618.743µs - 2.588059891s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Health 731.066µs - 2.588172158s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something Fast 783.892µs - 2.58822497s
2019/09/03 21:32:08 [INFO] . . . . . . Handled Something dependency related 848.966µs - 2.588290048s
2019/09/03 21:32:08 [INFO] . . . . . . Created RSConfig 1.738975ms - 2.589180079s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 400.08497ms - 2.987526066s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 400.103584ms - 2.987544634s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 400.108523ms - 2.987549562s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 400.112489ms - 2.987553516s
2019/09/03 21:32:09 [INFO] . . . . . Startinng ing rule handling 1.125µs - 2.98757893s
2019/09/03 21:32:09 [INFO] . . . . . Finished dependency stuff 21.357µs - 2.987599123s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 790.203µs - 2.988368031s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 939.562µs - 2.988517431s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 1.091998ms - 2.988669849s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 1.110855ms - 2.988688664s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 1.124407ms - 2.988702201s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 1.225172ms - 2.988802966s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 199.815713ms - 3.187393555s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 199.834823ms - 3.187412597s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 199.839689ms - 3.18741746s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 199.843466ms - 3.187421237s
2019/09/03 21:32:09 [INFO] . . . . . Startinng ing rule handling 471ns - 3.187428603s
2019/09/03 21:32:09 [INFO] . . . . . Finished dependency stuff 37.851µs - 3.187465969s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 127.835µs - 3.187556314s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 142.624µs - 3.187570758s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 146.46µs - 3.187574586s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 150.208µs - 3.187578343s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 153.702µs - 3.18758183s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 191.89µs - 3.187620006s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 200.266267ms - 3.387694531s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 200.537775ms - 3.387966032s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 200.607126ms - 3.388035301s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 200.634945ms - 3.388063086s
2019/09/03 21:32:09 [INFO] . . . . . Startinng ing rule handling 394ns - 3.388079278s
2019/09/03 21:32:09 [INFO] . . . . . Finished dependency stuff 44.947µs - 3.388123867s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 7.346584ms - 3.395425606s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 10.444196ms - 3.398523216s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 10.455193ms - 3.398534105s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 10.460047ms - 3.398538953s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 10.464791ms - 3.39854369s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 10.51772ms - 3.39859666s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 199.362778ms - 3.587441742s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 199.417818ms - 3.587496786s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 199.440409ms - 3.587519316s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 199.4543ms - 3.587533187s
2019/09/03 21:32:09 [INFO] . . . . . Startinng ing rule handling 769ns - 3.588186274s
2019/09/03 21:32:09 [INFO] . . . . . Finished dependency stuff 57.477µs - 3.588242952s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 303.303µs - 3.588488988s
2019/09/03 21:32:09 [INFO] . . . . . . Handled TLS 340.965µs - 3.588526454s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Health 355.23µs - 3.588540723s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something Fast 368.993µs - 3.588554492s
2019/09/03 21:32:09 [INFO] . . . . . . Handled Something dependency related 382.542µs - 3.588568031s
2019/09/03 21:32:09 [INFO] . . . . . . Created RSConfig 478.938µs - 3.588664447s
2019/09/03 21:32:10 [INFO] . . . . . . Handled TLS 199.090527ms - 3.787276082s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Health 199.10746ms - 3.787292937s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Something Fast 199.112001ms - 3.787297472s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Something dependency related 199.115951ms - 3.787301419s
2019/09/03 21:32:10 [INFO] . . . . . Startinng ing rule handling 403ns - 3.787307191s
2019/09/03 21:32:10 [INFO] . . . . . Finished dependency stuff 18.769µs - 3.787325569s
2019/09/03 21:32:10 [INFO] . . . . . . Created RSConfig 139.764µs - 3.787446614s
2019/09/03 21:32:10 [INFO] . . . . . . Handled TLS 397.442µs - 3.787704336s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Health 589.374µs - 3.787896263s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Something Fast 2.168985ms - 3.789475883s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Something dependency related 2.338762ms - 3.789645666s
2019/09/03 21:32:10 [INFO] . . . . . . Created RSConfig 2.518927ms - 3.789825808s
2019/09/03 21:32:10 [INFO] . . . . . . Handled TLS 200.574703ms - 3.987881591s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Health 200.591864ms - 3.987898666s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Something Fast 200.596173ms - 3.987902974s
2019/09/03 21:32:10 [INFO] . . . . . . Handled Something dependency related 200.600378ms - 3.987907175s
2019/09/03 21:32:10 [INFO] sync DG {Namespace:staging ServiceName:some-app As3Name: As3Data:} (4.00054037s)
2019/09/03 21:32:10 [INFO] sync IRule {Namespace:staging ServiceName:some-app As3Name: As3Data:} (4.001198867s)
2019/09/03 21:32:10 [INFO] delete unused {Namespace:staging ServiceName:some-app As3Name: As3Data:} (4.001274426s)
2019/09/03 21:32:10 [INFO] delete profiles, but also Updated 0 of 0 virtual server configs, deleted 0
2019/09/03 21:32:12 [INFO] And now finished
2019/09/03 21:32:12 [INFO] Finished syncing virtual servers {Namespace:staging ServiceName:some-app As3Name: As3Data:} (6.199880517s)

**Comment by codertao** [comment]
And the other 2 seconds lost for 'delete profiles', is a call to deleteUnusedProfiles, which has a similar secrets call in checkProfile

**Comment by mdditt2000** [comment]
hello @codertao we are going into refactoring Ingress resources in CIS. Can you please reach out to me so i understand your configuration, scale sizing etc. Here is my email. m.dittmer@F5.com

**Comment by mdditt2000** [comment]
Jira for tracking this issue CONTCNTR-1122

**Comment by sennerholm** [comment]
I have simular performance issues in one of our installations. I haven't got all debug output yet, but I think it could be simular circumstances, we have around 70 ingresses, most of them with certificates. (the generated config is around 260k, most of it certificates)

**Comment by sennerholm** [comment]
> For the record, we've patched this locally (changed the secrets access in three spots to use a SharedIndexInformer), but there was another issue- appManager.setIngressStatus was also issuing an API call even if no changes to the ingress status were made. Fixing both of those got the time to update down in the acceptable levels.
> 
> Can look into putting together a PR, but not sure if the SharedIndexInformer on secrets is a 'good solution'- I have it setup with a field selector on secret.type=kubernetes.io/tls (as I didn't want it caching every single secret, just certs), but that could be compatibility breaking.

Is it possible to get a copy of the patch so I can try it on my environment?

**Comment by codertao** [comment]
@sennerholm The patch, used against v1.9.0 tag:
[diff.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/3709195/diff.txt)

Now... getting the build environment setup is an entirely different problem. 
(If getting it building is an issue, I can look into pushing a docker image somewhere)

**Comment by snatra** [comment]
We started looking into this issue, could reproduce the problem, we will provide a fix in the upcoming release.

**Comment by ssurenr** [comment]
The fix will be shipped after the next release.

**Comment by mdditt2000** [comment]
Closing this issue. CIS 1.13 improvements
