### ISSUE TITLE
INFO logging to STDERR

### ISSUE THREAD

**Issue by okunc** [F5Networks/k8s-bigip-ctlr#1016]
#### Description
bug: using f5networks/k8s-bigip-ctlr:latest I see the logs generated in INFO level but appearing as ERROR in DataDog.

e.g. it logs
```
2019/09/05 14:40:49 [INFO] Wrote 1 Virtual Server and 0 IApp configs
```

but shows in red color [tagged as ERROR] in DataDog. My wildshot is that it's logging to STDERR instead of STDOUT, can you please confirm and preferably fix this? thanks a lot!

#### Kubernetes Version
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

#### Controller Version
deployed by https://github.com/F5Networks/charts/blob/master/src/stable/f5-bigip-ctlr
`sha256:828e9be3db33acd98098b09b6d7b63f5951f5cf723a4af188e55e1a23f9ac85e`

#### BIG-IP Version
n/a

#### Diagnostic Information
n/a

**Comment by mdditt2000** [comment]
@ssurenr is the milestone 1.11?

**Comment by ssurenr** [comment]
> @ssurenr is the milestone 1.11?

Yes.
