### ISSUE TITLE
F5 Schema resources "The partition '' in the ConfigMap does not match"

### ISSUE THREAD

**Issue by Timoses** [F5Networks/k8s-bigip-ctlr#1023]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

k8s-bigip-ctlr logs:
```
2019/09/23 11:34:06 [ERROR] Error parsing ConfigMap default_coffee.vs
2019/09/23 11:34:06 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/09/23 11:34:06 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/09/23 11:34:06 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/09/23 11:34:06 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/09/23 11:34:06 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/09/23 11:34:06 [WARNING] Could not get config for ConfigMap: coffee.vs - The partition '' in the ConfigMap does not match 'env_ex-kubernetes' that the controller watches for
```

I'm uncertain what to try. I find it odd that it says `partition ''` and not `partition 'env_ex-kubernetes' (or any name that I enter into the configmap for the partition).

Any ideas?

#### Kubernetes Version
<Version of Kubernetes being used>
v1.14.1

#### Controller Version
<Version of k8s-bigip-ctlr being used>
1.10.0

#### BIG-IP Version
<Version of BIG-IP being used>
BIG-IP 14.0.0.1 Build 0.0.2 Point Release 1 

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.5
    heritage: Tiller
    release: f5-bigip-ctlr
  name: f5-bigip-ctlr-f5-bigip-ctlr
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: f5-bigip-ctlr
        release: f5-bigip-ctlr
    spec:
      containers:
      - args:
        - --credentials-directory
        - /tmp/creds
        - --insecure=true
        - --bigip-partition
        - env_ex-kubernetes
        - --bigip-url
        - <IP-XYZ>
        - --default-ingress-ip
        - <IP-ZYX>
        command:
        - /app/bin/k8s-bigip-ctlr
        image: f5networks/k8s-bigip-ctlr:1.10.0
        imagePullPolicy: IfNotPresent
        name: f5-bigip-ctlr
        volumeMounts:
        - mountPath: /tmp/creds
          name: bigip-creds
          readOnly: true
      serviceAccountName: f5-bigip-ctlr-serviceaccount
      volumes:
      - name: bigip-creds
        secret:
          secretName: f5-bigip-ctlr-login

```

```
apiVersion: v1
data:
  data: |
    {   
      "virtualServer": {
        "backend": {
          "ServiceName": "coffee-svc",
          "servicePort": 80
          }
        },
        "frontend": {
          "virtualAddress": {
            "port": 80, 
            "bindAddr": "<IP-ZYX>"
          },
          "partition": "env_svu-kubernetes",
          "mode": "http"
        }
      }   
  schema: f5schemadb://bigip-virtual-server_v0.1.7.json
kind: ConfigMap
metadata:
  creationTimestamp: "2019-09-18T08:53:28Z"
  labels:
    f5type: virtual-server
  name: coffee.vs
  namespace: default
  resourceVersion: "4075293"
  selfLink: /api/v1/namespaces/default/configmaps/coffee.vs
  uid: c89aa1be-d9f1-11e9-a56a-001a4a000d39
```

**Comment by Timoses** [comment]
The same issue was posted here: https://github.com/F5Networks/k8s-bigip-ctlr/issues/803#issuecomment-457084840

**Comment by trinaths** [comment]
@Timoses: The error mentions " [ERROR] Error parsing ConfigMap default_coffee.vs" can you share the YAML file of your configmap. 

In the AS3 declaration, you need the mention that partition. Please refer to
 https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3-use-1.html#iii-configure-the-big-ip-system

**Comment by Timoses** [comment]
@trinaths Thanks for the hint. I will try AS3 as well at a later time.

For now though, this is not an AS3 config. It's F5 schema resources:
* https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.10/#f5-resource-configmap-properties
* https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-f5-resource.html
* https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-create-service-vs.html#kctlr-per-svc-vs


The documentation of the k8s-bigip-ctlr is quite heavy to read. So far I've figured 3 ways to configure F5 BigIP:
* Kubernetes Ingress Resource Objects
* F5 Schema Resources
* AS3

The AS3 option looks the most promising (and most up to date?). It seems F5 Schema Resources are outdated (?) and superseded by AS3.

I hope to achieve TLS passthrough via F5 Schema Resources or AS3 as the Kubernetes Ingress Resource Object does not appear to support it (neither via the native API nor via [F5-specific Annotations](https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.10/#supported-ingress-annotations))

**Comment by mdditt2000** [comment]
@Timoses thank you for the feedback. We are going to be working on fixing the documentation as we move away from F5 Schema Resources CCCL to the AS3 declarative API. 

Over the next few weeks we starting to refactor Kubernetes Ingress Resource with AS3 backend. Can you please send me all your Kubernetes Ingress Resource requirements or do you just need TLS passthrough. BTW here is a example of TLS passthrough using configmap https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-10/as3%20declaration/https.yaml

**Comment by Timoses** [comment]
@mdditt2000 : Thanks for your response.

I did get to dive a little deeper into AS3 and succeeded in my task for TLS passthrough (also thanks to the examples [here](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/)).


It's just a pity that the documentation is outdated. In my opinion you should immediately insert some highlight banner on all the old F5 Schema Resources pointing towards AS3.

My user story is:
* First trying Kubernetes Ingress resource (it's the most K8s native approach, and admittedly the Ingress API is still in Beta... so not having all the use cases for Ingress controls at hand here is to be expected)
* Then I looked at F5 Schema Resources: **This is where I should be informed to NOT use that, but rather look at AS3**.. Wasted quite some time on this.
* -> Finally AS3: Achieved F5 BIG-IP configuration via Kubernetes ConfigMap in AS3

For me, this ticket can be closed as F5 Schema Resources seem outdated and I don't expect any fix (considering AS3 does the job).

**Comment by mdditt2000** [comment]
@Timoses thank you for the feedback. We are in the process of re-writing all the documentation since CIS has changed completely. You are correct we have moved away from the F5 Schema Resources to AS3. That will be the first section to be updated. Please do not hesitate to reach out to use via github issues or slack. f5cloudsolutions.slack.com  #cc-kubernetes
