### ISSUE TITLE
Prometheus Metric request for duplicate IP used in configmap that already exists in the F5

### ISSUE THREAD

**Issue by YacovNagose** [F5Networks/k8s-bigip-ctlr#1028]
#### Description

Prometheus Metric request for IP used in Config map that already exists in the F5.
We create a lot of VIPs using the bigip ctrl pod in K8s, we would like to have a Prometheus metric for duplicate IP that used in Config maps.

#### Kubernetes Version
v1.13.10
#### Controller Version
1.8.1
#### BIG-IP Versios

BIG-IP 13.1.1.5 Build 0.0.4 Point Release 5

#### Diagnostic Information

[INFO] Text: u'{"code":400,"message":"01070333:3: Virtual Server /static-ci-k8s/static-ci_lp-appmgmtsvc-app-vip-80 illegally shares destination address, source address, service port, ip-protocol, and vlan with Virtual Server /QA/qa_lp-appmgmtsvc-web-vip-80.","errorStack":[],"apiError":3}'

**Comment by mdditt2000** [comment]
Using SharedNodes in CIS 2.2 helps with using duplicate/Shared Nodes. CIS will now create the node in Common. The best way to achieve this information using using telemetry stream and pull the system stats/logs to monitor any BIG-IP IP node conflict. Another option would be to use telemetry streaming to pull BIG-IP node information. Not something CIS can provide. 

Closing issue out.
