### ISSUE TITLE
[RFE] HTTPS monitor in CRD 

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1034]
#### Description

Need HTTPS health check implemented in CRD. 
Would like this functionality built into the new CRD feature that is planned. 

#### Kubernetes Version
Let's target v1.16, as it has [apiextensions.k8s.io/v1](https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/)

####  Related Info

Internal SR: C3104289

**Comment by mdditt2000** [comment]
CONTCNTR-1796 closed. HTTPS/HTTP monitors added to CIS 2.1. Release image in July. Closing issue out.
