### ISSUE TITLE
CIS 1.11 generating many dozens of "INFO" log messages every 30 seconds

### ISSUE THREAD

**Issue by dgarrisonf5** [F5Networks/k8s-bigip-ctlr#1041]
#### Description

Using CIS v1.11 with OKD v3.11 and am getting many dozens of "INFO" level log messages every 30 seconds.

#### Kubernetes Version

OKD v3.11

#### Controller Version

CIS v1.11

#### BIG-IP Version

BIG-IP v13.1.0.4

#### Diagnostic Information

2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:37 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2019/10/10 20:46:38 [INFO] Wrote 0 Virtual Server and 0 IApp configs

**Comment by mdditt2000** [comment]
Jira for PM tracking CONTCNTR-1141

**Comment by mdditt2000** [comment]
@dgarrisonf5 we will be releasing a patch release shortly with this fix. CIS 1.11.1

**Comment by dgarrisonf5** [comment]
I deployed CIS 1.11.1, but am still getting dozens of "INFO" level log messages every 30 seconds.  Snippet of CIS logs:

2019/11/04 18:42:44 [INFO] Starting: Version: v1.11.1, BuildInfo: n1899-607057777
2019/11/04 18:42:44 [INFO] ConfigWriter started: 0xc000292d80
2019/11/04 18:42:44 [INFO] Started config driver sub-process at pid: 12
.
.
.
.

2019/11/04 18:54:45 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:54:45 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:54:45 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:54:45 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:54:52 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:54:57 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:07 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:12 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs
2019/11/04 18:55:15 [INFO] Wrote 3 Virtual Server and 0 IApp configs

**Comment by ssurenr** [comment]
Hi @dgarrisonf5 we had to move the config map logging fix for the next release. The log dump is fixed for Routes on AS3 in 1.11.1.

**Comment by dgarrisonf5** [comment]
Thanks @ssurenr.  Please remove the entry that references this issue from the "Bug Fixes" section of the 1.11.1 release notes.

Thanks

**Comment by ssurenr** [comment]
Addressed in 1.12.0

**Comment by dgarrison63** [comment]
I've deployed CIS 1.12, but the continuous INFO log messages persist.

Please re-open this issue.

Kubernetes Version
OKD v3.11

Controller Version
CIS v1.12

BIG-IP Version
BIG-IP v13.1.0.4

Diagnostic Information

2019/12/19 19:36:46 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:46 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:46 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:47 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:48 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:53 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:54 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:54 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:36:58 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:08 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:13 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/12/19 19:37:16 [INFO] Wrote 1 Virtual Server and 0 IApp configs

**Comment by ssurenr** [comment]
Can you share your controller deployment file?
