### ISSUE TITLE
Ingress Resource - Support clientssl and serverssl annotation in Ingress object

### ISSUE THREAD

**Issue by cjunwchen** [F5Networks/k8s-bigip-ctlr#1045]
#### Description
- The current version of CIS support  "virtual-server.f5.com/clientssl:", "virtual-server.f5.com/serverssl:" , "virtual-server.f5.com/waf" in route object
- The route object also support encryption type of "Edge Terminated", "Passthrough Terminated", "Re-encrypt Terminated"

Request same annotation above to be implemented for Ingress object

#### Openshift Version
3.11

#### Controller Version
1.10

#### BIG-IP Version
14.1

**Comment by mdditt2000** [comment]
CONTCNTR-1152 for PM tracking

**Comment by veeramalla-f5** [comment]
@cjunwchen if you want to setup both clientssl and serverssl for Ur ingress resource. You need to create a TLS secret with certificate and key(CIS will create a clientssl profile) and use our serverssl annotation to reference an existing bigip serverssl profile.

This will function similar to Openshift re-encrypt route.

Please use the below example

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingressTLS
  namespace: default
  annotations:
    # Provide an IP address for the BIG-IP pool you want to handle traffic.
    virtual-server.f5.com/ip: "1.2.3.4"
    # Specify the BIG-IP partition containing the virtual server.
    virtual-server.f5.com/partition: "k8s"
    virtual-server.f5.com/serverssl: "/Common/clientssl"
    ingress.kubernetes.io/ssl-redirect: "true"
    
spec:
  tls:
    # Specifies an already-configured SSL Profile on BIG-IP that should be
    # used for this Ingress.
    # Follows the format "/partition/profile_name".
    - secretName: /Common/clientssl
  backend:
    # The name of a single Kubernetes Service you want to expose to external
    # traffic using TLS
    serviceName: myService
    servicePort: 443

**Comment by mdditt2000** [comment]
Closing this out. Validated and documented. 

https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/slack/ingress/re-encrypt-tls.yaml
