### ISSUE TITLE
k8s-bigip-ctrl crashing

### ISSUE THREAD

**Issue by gsingh76** [F5Networks/k8s-bigip-ctlr#1056]
#### Description
<We are setting up F5 Connector on Kubernetes and while testing the workflow, the big controller  start to crash when we add load on it. We observed that the controller pods starts to crash after we create approx 10-15 VIP's. 

#### Kubernetes Version
v1.14.7

#### Controller Version
k8s-bigip-ctlr:1.11

#### BIG-IP Version
<Version of BIG-IP being used>

#### Diagnostic Information
Below is the error that we have observed frequently from the controller pod.

"2019/10/16 18:54:13 [DEBUG] ConfigWriter (0xc000139b00) received stop signal
E1016 18:54:13.391110       1 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x198d100), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x1aabfa0), missingMethod:""} (interface conversion: interface {} is nil, not appmanager.serviceQueueKey)

Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by mdditt2000** [comment]
@gsingh76 what K8S deployment  method are you using "cfgmap, Ingress"? Is this legacy CC or you using CIS with AS3 API?

**Comment by gsingh76** [comment]
We are using configmap. We are not using AS3 API.
I think the last time we had conversation with your team, we were told that we cannot have individual configmap for each tenant and a centralized configmap need to be maintained for all tenants and that defeats our purpose of DevOps where every customer can self service there application.

**Comment by ssurenr** [comment]
@gsingh76 The recommendation is to use an AS3 declaration via a config map, as this is a future-proof solution. If you go this way, you can allow your customers to create multiple AS3 Application classes to a version control system and consolidate them to form a single AS3 declaration as part of your CI/CD pipeline and send it to CIS. 
Another simple, better and future-proof approach would be to configure the controller to listen for Ingress resources.

**Comment by joelkeener** [comment]
I believe that @gsingh76 is hoping to segregate each Tenant so that running the configMap will not break other Tenants if there is an error. That concern already has an RFE < https://github.com/F5Networks/k8s-bigip-ctlr/issues/998 > but I believe they are willing to move to AS3, even with this limitation, in the interim so that they can get a fix for the error message / crash.

**Comment by mdditt2000** [comment]
@gsingh76 please can you try the CRDs with CIS. Still in Alpha but we adding more options on each release. https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/crd/CustomResource.md
