### ISSUE TITLE
K8s cluster unavailable after a day using big-ip-controller.

### ISSUE THREAD

**Issue by thiagoliri** [F5Networks/k8s-bigip-ctlr#1058]
Hello, folks! On my PRD envivonment I have 4 physical BigIP devices divided on 2 different datacenters. On each datacenter both boxes are configured with HA Settings, so any data created on the LTM config on one box is replicated on the other. No issues there. The problem is that there's no replication regarding the o datacenter. They have to be configured separately. This setup is due to some Internet link redundancies so avoid downtime as much as possible. With this in mind i wand to use Kubernetes CC as an Ingress controller. On the deployment object i can specify ONE BigIp bigip-url. I talked here about this situation and i got a suggestion that i could do another deployment, using the other DC configurations do I could achieve my needed configuration. This, at first, worked like a charm. I could see the virtual servers and policies being created on both DC's and the GTM rules were configured so that, in a case of some issue, the links could be switched with no downtime for the applications. And I was happy. Until the next day. When i came to work on the next day my UAT cluster was completely unavailable. I'm using rancher 2.2.8 with kubernetes 1.14.6 and I'm getting this message.
Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://10.70.5.161:6443/api/v1/namespaces/cattle-prometheus?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers); [certificates] Deploying kubernetes certificates to Cluster nodes
This makes my cluster completly unavailable, the api server is unresponsive and i could find any indication of how to solve it unless to delete the whole cluster. And i know that this is happening because of CC since for this last test I created two different clusters with the same configurations, nodes and sizes. The only difference is that one have this whole bigip / cc / gtm configuration and the other one doesn't. Have you guys faces this issue before? Any indications?

#### Kubernetes Version
kubernetes 1.14.6 

#### Controller Version
"version": "1.10.0", "build": "n1738-575267085"

#### BIG-IP Version
13.1.1.5 buid release 5

#### Diagnostic Information

LOG: [ERROR] ClusterController c-nxh2f [user-controllers-controller] failed with : failed to start user controllers for cluster c-4j6np: failed to contact server: Get https://10.10.1.1:6443/api/v1/namespaces/kube-system?timeout=30s: dial tcp 127.0.0.1:6443: connect: connection refused\n","stream":"stdout","time":"2019-09-24T00:01:02.110678662Z"}

**Comment by veeramalla-f5** [comment]
Hi @thiagoliri,

 Did u face this issue again? If yes, Please provide more log information and if possible share your deployment configuration.

Regards,
Abhishek.

**Comment by thiagoliri** [comment]
Hello ! veeramalla-f5

Yes, we face the issue again, we can only run the environment with the BigIP controller when we have only one etcd. If we use 3 etcd the cluster get down. When we look at the etcd, it get out of memory and the port it's down and the master could not connect.

The deployment is:

I upload the logs of the 2 Bigip controllers deployed. 
[bigip-ctlr.zip](https://github.com/F5Networks/k8s-bigip-ctlr/files/3821171/bigip-ctlr.zip)

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-13-novo
  template:
    metadata:
      name: k8s-bigip-ctlr-13-novo
      labels:
        app: k8s-bigip-ctlr-13-novo
    spec:
      serviceAccount: bigip-ctlr
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=10.40.80.99
        - --bigip-partition=k8shml
        - --pool-member-type=nodeport
        - --default-ingress-ip=10.40.10.70
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
              optional: false
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
              optional: false
        image: f5networks/k8s-bigip-ctlr
        name: k8s-bigip-ctlr
      serviceAccountName: bigip-ctlr

**Comment by veeramalla-f5** [comment]
Hi @thiagoliri ,

 We have stabilized CIS with respect to crashes and CPU load on BIG-IP. Please try our latest release 2.1 and let us know if u still see the issue.

**Comment by mdditt2000** [comment]
Closing this issue.
