### ISSUE TITLE
Warnings - "Error when setting Ingress status IP for virtual server"

### ISSUE THREAD

**Issue by wheestermans31** [F5Networks/k8s-bigip-ctlr#1069]
#### Description
Warnings - "Error when setting Ingress status IP for virtual server"

#### Kubernetes Version
v1.11.10-docker-1

#### Controller Version
1.10.0

#### Diagnostic Information

Any  information what the following WARNINGs means, we see these regularly inside our logs:
```
2019/10/31 11:50:44 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-hub-service-app-h8": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-hub-service-app-h8, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2d84190d-fb39-11e9-81fd-0242ac110005, UID in object meta: 
2019/10/31 11:50:45 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-hub-service-app-kl": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-hub-service-app-kl, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 3253f812-fb39-11e9-b3e2-0242ac110005, UID in object meta: 
2019/10/31 11:50:45 [WARNING] Overwriting existing entry for backend {ServiceName:tme-svc-jetty-vlps-hub-service-app-h1 ServicePort:8080 Namespace:tme-ns-jetty-dev}
2019/10/31 11:50:45 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-hub-service-app-se": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-hub-service-app-se, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2c45e8cc-fb39-11e9-b3e2-0242ac110005, UID in object meta: 
2019/10/31 11:50:45 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-hub-service-app-sg": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-hub-service-app-sg, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2ea7d416-fb39-11e9-81fd-0242ac110005, UID in object meta: 
2019/10/31 11:50:45 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-hub-service-app-thi": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-hub-service-app-thi, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 3439f7cb-fb39-11e9-b3e2-0242ac110005, UID in object meta: 
2019/10/31 11:50:46 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-hub-service-app-va": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-hub-service-app-va, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2dbf68eb-fb39-11e9-b3e2-0242ac110005, UID in object meta: 
2019/10/31 11:50:46 [WARNING] Overwriting existing entry for backend {ServiceName:tme-svc-jetty-vlps-hub-service-app-h1 ServicePort:8080 Namespace:tme-ns-jetty-dev}
2019/10/31 11:50:46 [WARNING] Error when setting Ingress status IP for virtual server ingress_10-100-4-110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-online-app": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-online-app, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 3383ee7b-fb39-11e9-81fd-0242ac110005, UID in object meta: 
```

**Comment by trinaths** [comment]
Can you share the ingress definition which is causing this error.

**Comment by wheestermans31** [comment]
Sample:

110_80: Operation cannot be fulfilled on ingresses.extensions "tme-ing-jetty-vlps-online-app": StorageError: invalid object, Code: 4, Key: /registry/ingress/tme-ns-jetty-dev/tme-ing-jetty-vlps-online-app, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 3383ee7b-fb39-11e9-81fd-0242ac110005, UID in object meta:

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kubernetes.io/change-cause":"kubectl apply --namespace=tme-ns-jetty-dev --filename=tme-k8s-service-vlps-online-app.yaml --record=true"},"name":"tme-svc-jetty-vlps-online-app","namespace":"tme-ns-jetty-dev"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"tme-app-jetty-vlps-online-app"},"type":"ClusterIP"}}
    kubernetes.io/change-cause: kubectl apply --namespace=tme-ns-jetty-dev --filename=tme-k8s-service-vlps-online-app.yaml
      --record=true
  creationTimestamp: null
  name: tme-svc-jetty-vlps-online-app
  selfLink: /api/v1/namespaces/tme-ns-jetty-dev/services/tme-svc-jetty-vlps-online-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tme-app-jetty-vlps-online-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

When we redeploy applications in development, we remove all resouces, deployment/ingress/service. Then everything is recreated/ This only happens inside the development envitonment. Can this cause the warnings that we see?

**Comment by trinaths** [comment]
@wheestermans31 : I think you are hitting this issue: https://github.com/kubernetes/kubernetes/issues/71139

**Comment by mdditt2000** [comment]
Closing issue out. No update since Dec.
