### ISSUE TITLE
Command to review generic secret is incorrect

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1083]
#### Description
In section https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-secrets.html#secret-bigip-login

the command provided to review the generic secret created above is incorrect and needs to be revised.

The correct command is:
kubectl describe secret/bigip-login -n (namespace)

**Comment by ssurenr** [comment]
The documented command works fine. I checked in 1.16 version of k8s and kubectl.

**Comment by grmarxer-1** [comment]
This command works fine?
kubectl describe secret bigip-login

**Comment by ssurenr** [comment]
Yes.
<img width="531" alt="Screenshot 2019-11-25 at 12 17 50 PM" src="https://user-images.githubusercontent.com/8192995/69518445-9bf3db80-0f7d-11ea-9c05-2cc7c36cb56c.png">

**Comment by grmarxer-1** [comment]
I am also running kube v1.16.2 and the command did not work.  I'm guessing you have additional tools loaded that simplify some commands.  The documentation should only include complete generic commands that work in all environments.

@kube5:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}


@kube5:~$ kubectl describe secret bigip-login
Error from server (NotFound): secrets "bigip-login" not found


@kube5:~$ kubectl describe secrets/bigip-login -n kube-system
Name:         bigip-login
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  5 bytes
username:  5 bytes

**Comment by vklohiya** [comment]
@grmarxer-1 , You are correct as it's creating the secret in namespace kube-system, hence the describe command should also include the namespace. It's a documentation issue. We will update the document soon.

**Comment by mdditt2000** [comment]
Created CONTCNTR-1474 for internal PM tracking

**Comment by mdditt2000** [comment]
Text is fixed on this page: 
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-secrets.html#verify-the-secret
