### ISSUE TITLE
Documentation needs to include Instructions for using Calico

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1085]
#### Description
F5 recommends calico be used with CIS.  Please provide explicit instructions for both installing calico as well as configuring BGP

**Comment by ssurenr** [comment]
@dgarrisonf5 If you have any inputs for this documentation, that would be helpful.

**Comment by grmarxer-1** [comment]
This is the procedure I created for installing and Configuring BGP with Calico using Ubuntu 16.04

[Calico Install and Configure Ubuntu 16-04.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/3842945/Calico.Install.and.Configure.Ubuntu.16-04.txt)

**Comment by ssurenr** [comment]
Thanks @grmarxer-1 This is good.

**Comment by ssurenr** [comment]
CONTCNTR-1296 is created to track this effort internally.

**Comment by ssurenr** [comment]
There is a blog post in dev central: https://devcentral.f5.com/s/articles/calico-kubernetes-and-big-ip-26850

**Comment by mdditt2000** [comment]
New documentation for calico. 

https://clouddocs.f5.com/containers/latest/userguide/controller/calico-config.html
