### ISSUE TITLE
Introduction to F5 Container Ingress Services Workflow

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1086]
#### Description
https://clouddocs.f5.com/containers/v2/

The document flow outlined above should be revised to follow a standard workflow a customer would use to install and work with CIS.  For example the BIG-IP and flannel VXLAN Integration section should not come before Install the BIG-IP Controller: Kubernetes.  Please revise the documentation into a work flow that a generic user can follow to successfully install and work with CIS.

**Comment by ssurenr** [comment]
We are not going to change this workflow now as we are in the process of rewriting the docs from scratch. It will be published as v3.
