### ISSUE TITLE
Incorrect documentation for deleting CIS AS3 configmaps

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/k8s-bigip-ctlr#1087]
#### Description
The clouddocs provided to delete the CIS configmap for AS3 is incorrect in the link below
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-as3-delete-configmap.html

<Version of Kubernetes being used>
1.16.2
#### Controller Version
latest

#### BIG-IP Version
14.1

#### Diagnostic Information
The steps provided in the clouddocs requires you to delete the CIS deployment in addition to deleting the configmap and applying the empty AS3 configmap. However there is no need to delete the deployment or the configmap. Upon simply applying the empty AS3 config yaml file to the running configmap deletes the AS3 configuration.

**Comment by ssurenr** [comment]
Correct steps 5 and 6 are not necessary for recent versions.

**Comment by ssurenr** [comment]
Internal story CONTCNTR-1297 is created to track this effort.

**Comment by mdditt2000** [comment]
Completed. Added to documentation 

https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-as3-delete-configmap.html
