### ISSUE TITLE
AS3 Action Parameter Clarification

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1090]
#### Description
I am trying to understand when to use the AS3 action parameter (remove).

The action deploy deploys the declaration onto the target device (this is the default and used if you didn’t specify an action). dry-run does everything deploy does, except attempt to change the configuration of the target device (useful for debugging declarations). redeploy redeploys one of the declarations stored in the target device’s declaration history without making you GET it then POST it. retrieve returns the latest declaration (same as using GET). remove deletes the configuration created by the declaration (same as using DELETE). For localhost we recommend using GET and DELETE rather than the retrieve or remove actions

However, the remove action does not remove an AS3 config map and the following procedure is required.

https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-as3-delete-configmap.html

I would like to understand when to use the AS3 Action parameter

**Comment by ssurenr** [comment]
CIS discards the action parameter and it is always set to "deploy". I will add this behavior in the docs.

**Comment by ssurenr** [comment]
CONTCNTR-1295 created for internal tracking.

**Comment by mdditt2000** [comment]
I've added a note in the CIS service discovery section. 
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html

Closing this issue as complete.
