### ISSUE TITLE
How do you determine what version of k8s-bigip-ctlr is installed?

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1096]
#### Description
I'm trying to determine what version of k8s-bigip-ctlr I have installed.  What is the command and can you please document it here?

https://clouddocs.f5.com/containers/v2/releases_and_versioning.html#f5-schema

**Comment by ssurenr** [comment]
The first line of the controller log will have the version info.

```bash
kubectl logs -n kube-system deployment/k8s-bigip-ctlr-deployment --limit-bytes=1000 | head -1
```

**Comment by grmarxer-1** [comment]
Thank you.  Will this be added to the documentation?

**Comment by ssurenr** [comment]
Maybe we can create a FAQ section and add this info.

**Comment by grmarxer-1** [comment]
Wouldn’t it make the most sense to add it here since this is where the information is required?
https://clouddocs.f5.com/containers/v2/releases_and_versioning.html#f5-schema

Gregg Marxer | Systems Engineer
O 949-317-0334 M 732.713.1361
f5.com | synthesis.f5.com

**Comment by ssurenr** [comment]
Sure we can add there.

**Comment by ssurenr** [comment]
CONTCNTR-1293 added for internal tracking

**Comment by mdditt2000** [comment]
adding userAgent for CIS 2.0

"controls": {
        "class": "Controls",
        "userAgent": "CIS/2.0 K8S/1.18",
    },

**Comment by mdditt2000** [comment]
when using CIS 2.0, CIS adds a userAgent": "CIS/2.0 K8S/1.18 to the declaration when sending to BIG-IP. You can send a GET request to BIG-IP to pull the version. 

Get https://10.192.75.92/mgmt/shared/appsvcs/declare

![image](https://user-images.githubusercontent.com/12733938/82937249-af8bf900-9f44-11ea-8c2d-4ded6ad644f1.png)

**Comment by mdditt2000** [comment]
closing issue as done.
