### ISSUE TITLE
 cannot unmarshal string into Go struct field configMapFrontend

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1125]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

#### Kubernetes Version
<Version of Kubernetes being used>

#### Controller Version
<Version of k8s-bigip-ctlr being used>

#### BIG-IP Version
<Version of BIG-IP being used>

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by ssurenr** [comment]
@liaotx Could you please provide the relevant logs from the controller, the version of controller that you are using and your controller deployment YAML?

**Comment by liaotx** [comment]
> @liaotx Could you please provide the relevant logs from the controller, the version of controller that you are using and your controller deployment YAML?
 can you link to this ?  
https://github.com/F5Networks/k8s-bigip-ctlr/issues/1127
