### ISSUE TITLE
how to edit the bigip-virtual-server_v0.1.7.json

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1127]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

#### Kubernetes Version
v1.9.0

#### Controller Version
 v1.11.1

#### BIG-IP Version
v13.1.1.5

#### Diagnostic Information
    i want to use irule in my configmap, i find this  https://github.com/F5Networks/k8s-bigip-ctlr/issues/787 ,but i don't know how edit this json  file.

anyone who can tell me  how to edit this file ?  thanks !!

**Comment by liaotx** [comment]
oh  , The above format, I wrote it wrong, there is no Diagnostic Information  ，

**Comment by liaotx** [comment]
and  when i  edit this file , how  to use it ?   i'm new in this ,thanks !!!

**Comment by ssurenr** [comment]
@liaotx Please use an AS3 Declaration to configure the virtuals. https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html

Here's an example of using an iRule in an AS3 declaration: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/examples.html#example-4-calling-resources-from-a-url-source
Here is the

**Comment by liaotx** [comment]
> @liaotx Please use an AS3 Declaration to configure the virtuals. https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html
> 
> Here's an example of using an iRule in an AS3 declaration: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/examples.html#example-4-calling-resources-from-a-url-source
> Here is the

thank you ,but in client environment, there  has someone problems and now we need to use configmap  rather AS3  , can you tell me how to use irule in configmap ?  like my title  , how to edit json file (bigip-virtual-server_v0.1.7.json) ?

**Comment by liaotx** [comment]
> @liaotx Please use an AS3 Declaration to configure the virtuals. https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html
> 
> Here's an example of using an iRule in an AS3 declaration: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/examples.html#example-4-calling-resources-from-a-url-source
> Here is the

or if I want to use irule, what other methods are there and how to use it? ?  i really new in this and need to help  , thank you!

**Comment by ssurenr** [comment]
@liaotx As of now, there are no plans to enhance Classic config maps. We will support the config maps for a short while. Please plan to move to AS3 Declaration for L4 services and Ingress/Routes for L7 services.
cc: @mdditt2000

**Comment by mdditt2000** [comment]
Closing this issue out.
