### ISSUE TITLE
can i upload certificate and  create a sslprofile and  enable sni  ?

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1131]
In my client environment where use configmap to config  the demand ,now i need to upload certificate  to a partition and create a  clientssl profile  and enable sni function, how to achieve this demand if i can do it ?  
ps : just configmap rather AS3 

Kubernetes Version
v1.9.0

Controller Version
v1.11.1

BIG-IP Version
v13.1.1.3

**Comment by ssurenr** [comment]
@liaotx As of now, there are no plans to enhance Classic config maps. We will support the config maps for a short while. Please plan to move to AS3 Declaration for L4 services and Ingress/Routes for L7 services.
cc: @mdditt2000

**Comment by liaotx** [comment]
> @liaotx As of now, there are no plans to enhance Classic config maps. We will support the config maps for a short while. Please plan to move to AS3 Declaration for L4 services and Ingress/Routes for L7 services.
> cc: @mdditt2000

ok ,thanks

**Comment by mdditt2000** [comment]
Closing this issue out.
