### ISSUE TITLE
k8s 1.15/1.16

### ISSUE THREAD

**Issue by fabriziofiorucci** [F5Networks/k8s-bigip-ctlr#1134]
When are k8s 1.15 and 1.16 going to be officially supported?

**Comment by mdditt2000** [comment]
Jira CONTCNTR-1384 for internal tracking. Sprint 30 and part of release 1.13 scheduled for early Jan 2020

**Comment by mdditt2000** [comment]
@fabriziofiorucci validation will begin soon. I have being testing with K8S 1.16.2. Please note their is a API change. Please find the deployment file at https://github.com/mdditt2000/kubernetes-1-16/blob/master/cis%201.12/big-ip-91/f5-cluster-deployment.yaml

This is different 

apiVersion: apps/v1 . --- Changes
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  selector:  --- Add
    matchLabels:
      app: k8s-bigip-ctlr

**Comment by mdditt2000** [comment]
@fabriziofiorucci validation is complete. Automation testing is taking place. What out for the CIS 1.13 release coming shortly. Support for 1.16.2

**Comment by mdditt2000** [comment]
Released https://github.com/F5Networks/k8s-bigip-ctlr/releases/tag/v1.13.0 which has validation for K8S 1.16.x thanks
