### ISSUE TITLE
why CC will try to delete my clientssl profile

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1135]
#### Description
i want to create a configmap and use a client SSL profile ,but i find CC always want to delete my clientssl profile ,and i want to know how to fix it ??
ps:just in configmap

Kubernetes Version
v1.9.0

Controller Version
v1.11.1

BIG-IP Version
v13.1.1.5

#### Diagnostic Information
2019/12/23 06:14:02 [ERROR] [2019-12-23 06:14:02,497 f5_cccl.utils.profile ERROR] Error deleting SSL profile: 400 Unexpected Error: Bad Request for uri: https://138.65.1.55:443/mgmt/tm/ltm/profile/client-ssl/~f5-vxlan-test~f5-vxlan-test_f5-vxlan-test-cfmap-https.app~f5-vxlan-test_f5-vxlan-test-cfmap-https_clientssl_1/
2019/12/23 06:14:02 [INFO] Text: u'{"code":400,"message":"01070265:3: The ClientSSL Profile (/f5-vxlan-test/f5-vxlan-test_f5-vxlan-test-cfmap-https.app/f5-vxlan-test_f5-vxlan-test-cfmap-https_clientssl_1) cannot be deleted because it is in use by a virtual server profile (/f5-vxlan-test/f5-vxlan-test_f5-vxlan-test-cfmap-https.app/f5-vxlan-test_f5-vxlan-test-cfmap-https_vs /f5-vxlan-test/f5-vxlan-test_f5-vxlan-test-cfmap-https.app/f5-vxlan-test_f5-vxlan-test-cfmap-https_clientssl_1).","errorStack":[],"apiError":3}'

here is my CC yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cc-k8s-to-bigip1
  namespace: f5-vxlan-test
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:latest" 
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=admin",
            "--bigip-password=admin",
            "--bigip-url=https://138.65.1.55",
            "--bigip-partition=f5-vxlan-test",
            "--pool-member-type=cluster",
            "--flannel-name=/Common/flannel_vxlan",
            "--namespace=f5-vxlan-test"
            ]
      imagePullSecrets:
        # Secret that gives access to a private docker registry
       # - name: my-secret
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login

here is my configmap:
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-vxlan-test-cfmap-https
  namespace: f5-vxlan-test
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
   {
     "virtualServer": {
       "backend": {
         "serviceName": "f5-vxlan-test-svc2",
         "servicePort": 80
       },
       "frontend": {
         "partition": "f5-vxlan-test",
         "iapp": "/f5-vxlan-test/a-test-iapp-irules-https2",
         "iappPoolMemberTable": {
           "name": "pool__members",
           "columns": [
               {"name": "addr", "kind": "IPAddress"},
               {"name": "port", "kind": "Port"},
               {"name": "connection_limit", "value": "0"}
           ]
         },
         "iappOptions": {
           "description": "a-test-iapp-irules-http"
         },
         "iappVariables": {
           "pool__addr": "138.65.1.70",
           "pool__pool_to_use": "/#create_new#",
           "pool__port": "443",
           "vs_name": "iapp_vs_https",
           "vs__ProfileHTTP": "/Common/http",
           "vs__ProfileClientSSLCert_1": "/Common/test5.f5.com.crt",
           "vs__ProfileClientSSLKey_1":"/Common/test5.f5.com.key",
           "vs__ProfileClientSSLChain_1":"/Common/test5.f5.com.crt",
           "vs__ProfileClientSSLAdvOptions_sni_default": "sni-default true",
           "pool__irules": " when CLIENT_ACCEPTED {  \r\n   if { [IP::addr [IP::client_addr] equals 138.65.1.57 ] } {   \r\n    pool  cfgmap_f5-vxlan-test_f5-vxlan-test-cfmap-sni_f5-vxlan-test-svc2  \r\n   }   else {   \r\n  pool  cfgmap_f5-vxlan-test_f5-vxlan-test-cfmap-sni_f5-vxlan-test-svc2  \r\n  } \r\n  }   "
         }
       }
     }
   }

**Comment by mdditt2000** [comment]
Closing this issue. Moving away from legacy iAPP in configmap to using AS3 user-defined configmaps. https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html
