### ISSUE TITLE
[Doc] misleading information on ingress annotation

### ISSUE THREAD

**Issue by nmenant** [F5Networks/k8s-bigip-ctlr#1136]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

On the following page: https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-as3-backend.html

It says: 

> Supported Annotations
kubernetes.io/ingress.class
virtual-server.f5.com/balance
virtual-server.f5.com/health
virtual-server.f5.com/ip
virtual-server.f5.com/serverssl
virtual-server.f5.com/http-port
virtual-server.f5.com/https-port

i believe it's an error to have https-port listed here. if a user want https based service, they should use http-port annotation and put a value of 443

**Comment by trinaths** [comment]
@nmenant - The Supported annotations are with respect to https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.12/#kubernetes-ingress-resources.
