### ISSUE TITLE
CC and AS3 monitor

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1145]
i has two namespace(f5-vxlan-test and f5-vxlan-test2 ) ,and one CC in namespace(f5-vxlan-test). when i config  AS3 in f5-vxlan-test2, CC will upload the config to F5 howeven my CC just monitor in namespace f5-vxlan-test,does CC  parameter "--namespace=f5-vxlan-test" dont take effect in AS3 ?  i want to know how to fix it?  thanks ！

#### Kubernetes Version
v1.9.0

#### Controller Version
v1.12

#### BIG-IP Version
v13.1.1.5

 # CC yaml
Name:                   cc-k8s-to-bigip1
Namespace:              f5-vxlan-test
CreationTimestamp:      Tue, 07 Jan 2020 10:23:25 +0800
Labels:                 app=k8s-bigip-ctlr
Annotations:            deployment.kubernetes.io/revision=3
Selector:               app=k8s-bigip-ctlr
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=k8s-bigip-ctlr
  Service Account:  bigip-ctlr
  Containers:
   k8s-bigip-ctlr:
    Image:  f5networks/k8s-bigip-ctlr:latest
    Port:   <none>
    Command:
      /app/bin/k8s-bigip-ctlr
    Args:
      --bigip-username=admin
      --bigip-password=admin
      --bigip-url=https://138.65.1.59
      --bigip-partition=partition1
      --pool-member-type=cluster
      --insecure=true
      --namespace=f5-vxlan-test
      --agent=as3
      --flannel-name=/partition1/flannel_vxlan
    Environment:
      BIGIP_USERNAME:  <set to the key 'username' in secret 'bigip-login'>  Optional: false
      BIGIP_PASSWORD:  <set to the key 'password' in secret 'bigip-login'>  Optional: false
    Mounts:            <none>
  Volumes:             <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   cc-k8s-to-bigip1-74d5b4b65c (1/1 replicas created)
Events:          <none>

**Comment by vincentmli** [comment]
> i has two namespace(f5-vxlan-test and f5-vxlan-test2 ) ,and one CC in namespace(f5-vxlan-test). when i config AS3 in f5-vxlan-test2, CC will upload the config to F5 howeven my CC just monitor in namespace f5-vxlan-test,does CC parameter "--namespace=f5-vxlan-test" dont take effect in AS3 ? i want to know how to fix it? thanks ！

How do you config AS3 in f5-vxlan-test2? you have two CC and each CC monitors f5-vxlan-test and f5-vxlan-test2 ?

**Comment by liaotx** [comment]
> > i has two namespace(f5-vxlan-test and f5-vxlan-test2 ) ,and one CC in namespace(f5-vxlan-test). when i config AS3 in f5-vxlan-test2, CC will upload the config to F5 howeven my CC just monitor in namespace f5-vxlan-test,does CC parameter "--namespace=f5-vxlan-test" dont take effect in AS3 ? i want to know how to fix it? thanks ！
> 
> How do you config AS3 in f5-vxlan-test2? you have two CC and each CC monitors f5-vxlan-test and f5-vxlan-test2 ?

i didn't has two CC ,i just had one CC in namespace  f5-vxlan-test,  f5-vxlan-test2  didn't had  any CC .  my CC just monitor in f5-vxlan-test ,my AS3 configmap config in namespace  f5-vxlan-test2 ,but CC will  find the AS3 configmap and upload the config to F5-LTM, however i  want to CC just monitor namespace f5-vxlan-test and don't monitor other namespaces.

how can i achieve this ?

**Comment by mdditt2000** [comment]
CONTCNTR-1693 - Internal Jira. Completed the regression. Resolved in CIS 2.0 coming next week.
