### ISSUE TITLE
k8s ingress without spec.rules causing ssl-redirect irule to fail to redirect

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#1160]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

having an ingress as below without spec.rules, the ssl-redirect irule would fail to do http to https redirect

<pre>

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: f5ingress
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
     ingress.kubernetes.io/allow-http: "false"
     ingress.kubernetes.io/allow-https: "true"
     kubernetes.io/ingress.class: f5
     ingress.kubernetes.io/ssl-redirect: "true"
     'virtual-server.f5.com/ip': '10.169.72.163'
spec:
  tls:
  - secretName: Common/clientssl
  backend:
    serviceName: nginxservice
    servicePort: 80

</pre>

config deployed on BIGIP:

<pre>

ltm virtual /k3s_AS3/Shared/ingress_10_169_72_163_80 {
    creation-time 2020-01-28:12:43:18
    description Shared
    destination /k3s_AS3/10.169.72.163:80
    ip-protocol tcp
    last-modified-time 2020-01-28:12:43:18
    mask 255.255.255.255
    persist {
        /Common/cookie {
            default yes
        }
    }
    pool /k3s_AS3/Shared/ingress_default_nginxservice
    profiles {
        /Common/f5-tcp-progressive { }
        /Common/http { }
    }
    rules {
        /k3s_AS3/Shared/http_redirect_irule_443
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
ltm virtual /k3s_AS3/Shared/ingress_10_169_72_163_443 {
    creation-time 2020-01-28:12:43:18
    description Shared
    destination /k3s_AS3/10.169.72.163:443
    ip-protocol tcp
    last-modified-time 2020-01-28:12:43:18
    mask 255.255.255.255
    persist {
        /Common/cookie {
            default yes
        }
    }
    pool /k3s_AS3/Shared/ingress_default_nginxservice
    profiles {
        /Common/clientssl {
        }
        /Common/f5-tcp-progressive { }
        /Common/http { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}

ltm data-group internal /k3s_AS3/Shared/https_redirect_dg {
    records {
        \*/ {
            data /
        }
    }
    type string
}

ltm rule /k3s_AS3/Shared/http_redirect_irule_443 {
when HTTP_REQUEST {
                        # Look for exact match for combination of host name and path
                        set host [HTTP::host]
                        set path [HTTP::path]
                        append host $path
                        # Find the number of "/" in the hostpath
                        set rc 0
                        foreach x [split $host {}] {
                            if {$x eq "/"} {
                                           incr rc
                                   }
                        }
                        # Compares the hostpath with the entries in https_redirect_dg
                        for {set i $rc} {$i >= 0} {incr i -1} {
                                set paths [class match -value $host equals https_redirect_dg]
                                # Check if host with combination of "/" matches https_redirect_dg
                                if {$paths == ""} {
                                        set hosts ""
                                        append hosts $host "/"
                                        set paths [class match -value $hosts equals https_redirect_dg]
                                }
                                # Trim the uri to last slash
                                if {$paths == ""} {
                                        set host [
                                                string range $host 0 [
                                                        expr {[string last "/" $host]-1}
                                                ]
                                        ]
                                }
                                else {
                                        break
                                }
                        }
                        if {$paths != ""} {
                                set redir 0
                                set prefix ""
                                foreach s [split $paths "|"] {
                                        # See if the request path starts with the prefix
                                        append prefix "^" $s "($|/*)"
                                        if {[HTTP::path] matches_regex $prefix} {
                                                set redir 1
                                                break
                                        }
                                }
                                if {$redir == 1} {
                                        HTTP::redirect https://[getfield [HTTP::host] ":" 1]:443[HTTP::uri]
                                }
                        }
                }
}
</pre>

When send http request to ingress_10_169_72_163_80

curl  http://10.169.72.163/

ingress_10_169_72_163_80 did load balance to pool instead of redirect to ingress_10_169_72_163_443

#### Kubernetes Version
k3s 1.0.0 (k8s 1.16.3)

#### Controller Version
CIS 1.13.0

#### BIG-IP Version
14.1.0

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by vincentmli** [comment]
from https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/resourceConfig.go

a quick fix might be checking if ing.Spec.Rules exist, if not exist, apply iRule "/Common/_sys_https_redirect"

<pre>
	// sslRedirect defaults to true, allowHttp defaults to false.
	sslRedirect := getBooleanAnnotation(ing.ObjectMeta.Annotations,
		ingressSslRedirect, true)
	allowHttp := getBooleanAnnotation(ing.ObjectMeta.Annotations,
		ingressAllowHttp, false)
	// -----------------------------------------------------------------
	// | State | sslRedirect | allowHttp | Description                 |
	// -----------------------------------------------------------------
	// |   1   |     F       |    F      | Just HTTPS, nothing on HTTP |
	// -----------------------------------------------------------------
	// |   2   |     T       |    F      | HTTP redirects to HTTPS     |
	// -----------------------------------------------------------------
	// |   2   |     T       |    T      | Honor sslRedirect == true   |
	// -----------------------------------------------------------------
	// |   3   |     F       |    T      | Both HTTP and HTTPS         |
	// -----------------------------------------------------------------
	if sslRedirect {
		// State 2, set HTTP redirect iRule
		log.Debugf("TLS: Applying HTTP redirect iRule.")
		ruleName := fmt.Sprintf("%s_%d", httpRedirectIRuleName, httpsPort)
		appMgr.addIRule(ruleName, DEFAULT_PARTITION,
			httpRedirectIRule(httpsPort))
		appMgr.addInternalDataGroup(httpsRedirectDgName, DEFAULT_PARTITION)
		ruleName = joinBigipPath(DEFAULT_PARTITION, ruleName)
		rsCfg.Virtual.AddIRule(ruleName)
		if nil != ing.Spec.Backend {
			svcFwdRulesMap.AddEntry(ing.ObjectMeta.Namespace,
				ing.Spec.Backend.ServiceName, "\\*", "/")
		}
		for _, rul := range ing.Spec.Rules {
			if nil != rul.HTTP {
				host := rul.Host
				for _, path := range rul.HTTP.Paths {
					svcFwdRulesMap.AddEntry(ing.ObjectMeta.Namespace,
						path.Backend.ServiceName, host, path.Path)
				}
			}
		}
	} else if allowHttp {
		// State 3, do not apply any policy
		log.Debugf("TLS: Not applying any policies.")
	}
</pre>

**Comment by veeramalla-f5** [comment]
Hi ,

 There is a limitation with CIS 1.13.0 on SSLRedirect to use "host". This limitation is created as we are trying enhance SSLRedirect Irule which is common for Routes and Ingress. We will figure out a way to fix in coming releases. The possible workaround today is to use a host based ingress resource.

Example:
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80

**Comment by vincentmli** [comment]
I have a quick hack which is to attach wildcard ssl redirect irule without checking datagroup and when ing.spec.rules is empty, and the diff is below. 

<pre>
SEA-ML-00029224:k8s-bigip-ctlr vli$ git diff
diff --git a/pkg/appmanager/profiles_test.go b/pkg/appmanager/profiles_test.go
index 9879f32..084b8ce 100644
--- a/pkg/appmanager/profiles_test.go
+++ b/pkg/appmanager/profiles_test.go
@@ -146,9 +146,9 @@ var _ = Describe("AppManager Profile Tests", func() {
                        // No annotations were specified to control http redirect, check that
                        // we are in the default state 2.
                        Expect(len(httpCfg.Virtual.IRules)).To(Equal(1))
-                       expectedIRuleName := fmt.Sprintf("/%s/%s_443",
-                               DEFAULT_PARTITION, httpRedirectIRuleName)
-                       Expect(httpCfg.Virtual.IRules[0]).To(Equal(expectedIRuleName))
+                       //expectedIRuleName := fmt.Sprintf("/%s/%s_443",
+                       //      DEFAULT_PARTITION, httpRedirectIRuleName)
+                       //      Expect(httpCfg.Virtual.IRules[0]).To(Equal(expectedIRuleName))
 
                        // Set the annotations the same as default and recheck
                        fooIng.ObjectMeta.Annotations[ingressSslRedirect] = "true"
@@ -159,9 +159,9 @@ var _ = Describe("AppManager Profile Tests", func() {
                        Expect(httpCfg).ToNot(BeNil())
                        Expect(r).To(BeTrue(), "Ingress resource should be processed.")
                        Expect(len(httpCfg.Virtual.IRules)).To(Equal(1))
-                       expectedIRuleName = fmt.Sprintf("/%s/%s_443",
-                               DEFAULT_PARTITION, httpRedirectIRuleName)
-                       Expect(httpCfg.Virtual.IRules[0]).To(Equal(expectedIRuleName))
+                       //expectedIRuleName = fmt.Sprintf("/%s/%s_443",
+                       //      DEFAULT_PARTITION, httpRedirectIRuleName)
+                       //      Expect(httpCfg.Virtual.IRules[0]).To(Equal(expectedIRuleName))
 
                        // Now test state 1.
                        fooIng.ObjectMeta.Annotations[ingressSslRedirect] = "false"
@@ -312,9 +312,9 @@ var _ = Describe("AppManager Profile Tests", func() {
                                        Name: "foo",
                                },
                                TLS: &routeapi.TLSConfig{
-                                       Termination:              "reencrypt",
-                                       Certificate:              "cert",
-                                       Key:                      "key",
+                                       Termination: "reencrypt",
+                                       Certificate: "cert",
+                                       Key:         "key",
                                        DestinationCACertificate: "destCaCert",
                                },
                        }
diff --git a/pkg/appmanager/resourceConfig.go b/pkg/appmanager/resourceConfig.go
index 1946f84..5a91113 100644
--- a/pkg/appmanager/resourceConfig.go
+++ b/pkg/appmanager/resourceConfig.go
@@ -1753,12 +1753,20 @@ func (appMgr *Manager) handleIngressTls(
        if sslRedirect {
                // State 2, set HTTP redirect iRule
                log.Debugf("TLS: Applying HTTP redirect iRule.")
-               ruleName := fmt.Sprintf("%s_%d", httpRedirectIRuleName, httpsPort)
-               appMgr.addIRule(ruleName, DEFAULT_PARTITION,
-                       httpRedirectIRule(httpsPort))
-               appMgr.addInternalDataGroup(httpsRedirectDgName, DEFAULT_PARTITION)
-               ruleName = joinBigipPath(DEFAULT_PARTITION, ruleName)
-               rsCfg.Virtual.AddIRule(ruleName)
+               if len(ing.Spec.Rules) > 0 {
+                       ruleName := fmt.Sprintf("%s_%d", httpRedirectIRuleName, httpsPort)
+                       appMgr.addIRule(ruleName, DEFAULT_PARTITION,
+                               httpRedirectIRule(httpsPort))
+                       appMgr.addInternalDataGroup(httpsRedirectDgName, DEFAULT_PARTITION)
+                       ruleName = joinBigipPath(DEFAULT_PARTITION, ruleName)
+                       rsCfg.Virtual.AddIRule(ruleName)
+               } else {
+                       ruleName := fmt.Sprintf("%s_%d", sysHTTPsRedirectIRuleName, httpsPort)
+                       appMgr.addIRule(ruleName, DEFAULT_PARTITION,
+                               sysHTTPsRedirectIRule(httpsPort))
+                       ruleName = joinBigipPath(DEFAULT_PARTITION, ruleName)
+                       rsCfg.Virtual.AddIRule(ruleName)
+               }
                if nil != ing.Spec.Backend {
                        svcFwdRulesMap.AddEntry(ing.ObjectMeta.Namespace,
                                ing.Spec.Backend.ServiceName, "\\*", "/")
diff --git a/pkg/appmanager/routing.go b/pkg/appmanager/routing.go
index 3d8ba4f..3982e46 100644
--- a/pkg/appmanager/routing.go
+++ b/pkg/appmanager/routing.go
@@ -33,6 +33,7 @@ import (
 )
 
 const httpRedirectIRuleName = "http_redirect_irule"
+const sysHTTPsRedirectIRuleName = "sys_https_redirect"
 const abDeploymentPathIRuleName = "ab_deployment_path_irule"
 const sslPassthroughIRuleName = "openshift_passthrough_irule"
 
@@ -354,6 +355,15 @@ func processIngressRules(
        return &rls, urlRewriteRefs, appRootRefs
 }
 
+func sysHTTPsRedirectIRule(port int32) string {
+       iRuleCode := fmt.Sprintf(`
+               when HTTP_REQUEST {
+                       HTTP::redirect https://[getfield [HTTP::host] ":" 1]:%d[HTTP::uri]
+               }`, port)
+
+       return iRuleCode
+}
+
 func httpRedirectIRule(port int32) string {
        // The key in the data group is the host name or * to match all.
        // The data is a list of paths for the host delimited by '|' or '/' for all.
</pre>

this result in BIGIP as:

<pre>
ltm rule /k3s_AS3/Shared/sys_https_redirect_443 {
when HTTP_REQUEST {
			HTTP::redirect https://[getfield [HTTP::host] ":" 1]:443[HTTP::uri]
		}
}
ltm virtual /k3s_AS3/Shared/ingress_10_169_72_163_80 {
    creation-time 2020-01-29:10:18:51
    description Shared
    destination /k3s_AS3/10.169.72.163:80
    ip-protocol tcp
    last-modified-time 2020-01-29:10:18:51
    mask 255.255.255.255
    persist {
        /Common/cookie {
            default yes
        }
    }
    pool /k3s_AS3/Shared/ingress_default_nginxservice
    profiles {
        /Common/f5-tcp-progressive { }
        /Common/http { }
    }
    rules {
        /k3s_AS3/Shared/sys_https_redirect_443
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
ltm virtual /k3s_AS3/Shared/ingress_10_169_72_163_443 {
    creation-time 2020-01-29:10:18:51
    description Shared
    destination /k3s_AS3/10.169.72.163:443
    ip-protocol tcp
    last-modified-time 2020-01-29:10:18:51
    mask 255.255.255.255
    persist {
        /Common/cookie {
            default yes
        }
    }
    pool /k3s_AS3/Shared/ingress_default_nginxservice
    profiles {
        /Common/clientssl {
            context clientside
        }
        /Common/f5-tcp-progressive { }
        /Common/http { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
</pre>

and tested works

<pre>
[root@rancher-k3s home]# curl -v -L -k http://10.169.72.163/
* About to connect() to 10.169.72.163 port 80 (#0)
*   Trying 10.169.72.163...
* Connected to 10.169.72.163 (10.169.72.163) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.169.72.163
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Moved Temporarily
< Location: https://10.169.72.163:443/
< Server: BigIP
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
< Content-Length: 0
< 
* Connection #0 to host 10.169.72.163 left intact
* Issue another request to this URL: 'https://10.169.72.163:443/'
* Found bundle for host 10.169.72.163: 0xb0ede0
* About to connect() to 10.169.72.163 port 443 (#1)
*   Trying 10.169.72.163...
* Connected to 10.169.72.163 (10.169.72.163) port 443 (#1)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: E=root@localhost.localdomain,CN=localhost.localdomain,OU=IT,O=MyCompany,L=Seattle,ST=WA,C=US
* 	start date: Aug 27 19:44:45 2013 GMT
* 	expire date: Aug 25 19:44:45 2023 GMT
* 	common name: localhost.localdomain
* 	issuer: E=root@localhost.localdomain,CN=localhost.localdomain,OU=IT,O=MyCompany,L=Seattle,ST=WA,C=US
> GET / HTTP/1.0
> User-Agent: curl/7.29.0
> Host: 10.169.72.163
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.17.8
< Date: Wed, 29 Jan 2020 18:22:51 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 21 Jan 2020 13:36:08 GMT
< Connection: close
< ETag: "5e26fe48-264"
< Accept-Ranges: bytes
< Set-Cookie: BIGipServer~k3s_AS3~Shared~ingress_default_nginxservice=302066186.20480.0000; path=/; Httponly; Secure

</pre>

**Comment by veeramalla-f5** [comment]
Let me check it Vincent. But we have to make sure the same IRule works for routes as well.

Currently there is a limitation that this Irule does not work for non host based ingress. It works well for all the other routes and ingress. If customer is ready to port his ingress to host based it's the best workaround.

Regards,
 AV

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by vincentmli** [comment]
FYI, this quick hack solved customers SSL redirect requirements and customer is happy with the result, I have not addressed the unit test issue in the code, please review or let me know if you want a PR from me

**Comment by mdditt2000** [comment]
@vincentmli can you generate a pull request with your changes for CIS 2.0 and PD review

**Comment by mdditt2000** [comment]
@veeramalla-f5 can you please close this issue out as done due to merged.
