### ISSUE TITLE
F5 Access Levels - least privileged access (not a bug)

### ISSUE THREAD

**Issue by rhysjtevans** [F5Networks/k8s-bigip-ctlr#1161]
Hi F5,
Is there more detailed RBAC documentation requirements? 

We're trying to go for least privileged access rather than providing full admin privileges to the controller.

If we provide "Manager" role to manage everything in a partition would that still work?

Cheers,

**Comment by mdditt2000** [comment]
Full BIGIP admin privileges to the controller are required. This is due to the API which CIS uses to communicate with BIGIP. CIS used the BIGIP creds from K8S secret.

**Comment by mdditt2000** [comment]
Closing issue out at this time. API requires CIS to use admin privileges
