### ISSUE TITLE
OpenShift route status not updating in OCP 4.3

### ISSUE THREAD

**Issue by strantalis** [F5Networks/k8s-bigip-ctlr#1162]
#### Description
Route Status not updating in ui and sits in pending. I would expect that this status would be updated as the route was created and working as expected. 

#### Kubernetes Version
Openshift 4.3/Kube 1.16

#### Controller Version
1.13.0

#### BIG-IP Version
BIG-IP 13.1.0.8

#### Diagnostic Information
Not seeing any error logs but I am noticing even in debug mode I never see this log.

https://github.com/F5Networks/k8s-bigip-ctlr/blob/1.13-stable/pkg/postmanager/handleRouteStatus.go#L82

##### Route
```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: argocd
  namespace: argocd
  selfLink: /apis/route.openshift.io/v1/namespaces/argocd/routes/argocd
  uid: 0ba46a22-1925-42de-9c7b-57f0514afcbc
  resourceVersion: '2694890'
  creationTimestamp: '2020-01-29T22:22:43Z'
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-1.6.5
spec:
  host: argocd.ingress.test.openshift.example.com
  to:
    kind: Service
    name: argo-cd-argocd-server
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
status:
  ingress: null

```
#### CIS Deployments
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-bigip-ctlr-01
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          # replace the version as needed
          image: "f5networks/k8s-bigip-ctlr:1.13.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url={{ .Values.f5.device1 }}",
            "--bigip-partition={{ .Values.f5.partition }}",
            "--pool-member-type=cluster",
            "--openshift-sdn-name={{ .Values.f5.sdnName }}",
            "--manage-routes=true",
            "--route-vserver-addr={{ .Values.f5.vip }}",
            '--insecure=true',
            '--agent=as3',
            '--log-level=DEBUG',
            '--namespace-label=f5=true',
            '--node-label-selector=node-role.kubernetes.io/worker'
            ]
      imagePullSecrets:
        # Secret that gives access to a private Docker registry
        - name: f5-docker-images
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login
```

**Comment by mdditt2000** [comment]
Are you using OCP 4.3? If so thanks for reporting. We just started the OCP 4.3 verification.

**Comment by mdditt2000** [comment]
Created CONTCNTR-1499 for PM tracking.

**Comment by gageorsburn** [comment]
It looks like the issue is that the CIS code is assuming that the default openshift routers are going to be watching every namespace. In the context of this issue, the default routers for openshift were using a namespace selector to watch only specific namespaces and the route was created in a namespace not being monitored by the default router.

In my opinion the status code should be rewritten without the dependency on the default openshift routers because they might not always be watching..

**Comment by veeramalla-f5** [comment]
@gageorsburn , F5 CIS does not take Openshift Default Router in to consideration for updating the route status. However, We are tracking the issue internally and will try to fix it in the next release.

Regards,
AV

**Comment by gageorsburn** [comment]
@veeramalla-f5 Yes there is an indirect dependency on the openshift router.

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/postmanager/handleRouteStatus.go#L64

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/postmanager/handleRouteStatus.go#L45

You guys are never handling the case where a route status is not set aka equal to 0. If the openshift router is not watching a namespace that a route is created in, it will not ever get a status.

**Comment by mdditt2000** [comment]
thanks for reporting this. We will look at this once the OCP 4.3 test environment is complete

**Comment by mdditt2000** [comment]
@subbuv26 just made the following improvements for route update

- It handles multiple namespaces
- It updates status irrespective of presence of other/default routers
- It updates status with no delay
 
Validation will be done on OCP 3.11 and 4.1. OCP 4.2 is coming soon

**Comment by subbuv26** [comment]
Issue is addressed in #1173. Validated on OCP 3.11.

**Comment by mdditt2000** [comment]
Fix Route Admit Status issue #1173. This issue can be closed out with CIS 1.14 shipping this week.

**Comment by strantalis** [comment]
I see 1.14 was released but I am not seeing the docker image yet. Any eta on when that will be published?

**Comment by trinaths** [comment]
@strantalis - We will be uploading the release image to DockerHub and RH Container registry. We are in final release steps.

**Comment by strantalis** [comment]
I can confirm route status is now updating correctly even on 4.3. Closing issue and thanks for fixing this.
