### ISSUE TITLE
CIS 1.13 SSL redirect fail when ingress 'virtual-server.f5.com/http-port': '8080'

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#1179]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>

This is same issue as https://github.com/F5Networks/k8s-bigip-ctlr/issues/802
CIS + AS3 does not resolve the ssl redirect when http-port is not standard http port 80

example ingress:
<pre>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: single-service
  annotations:
     ingress.kubernetes.io/ssl-redirect: "true"
     ingress.kubernetes.io/allow-http: "false"
     ingress.kubernetes.io/allow-https: "true"
     kubernetes.io/ingress.class: f5
     'virtual-server.f5.com/ip': '10.169.72.169'
     'virtual-server.f5.com/http-port': '8080' #=======HTTP port 8080
spec:
  tls:
  - hosts:
    - www.example.com
    secretName: Common/clientssl
  rules:
   - host: www.example.com
     http:
       paths:
       - path: /
         backend:
            serviceName: nginxservice
            servicePort: 80
   - host: www1.example.com
     http:
       paths:
       - path: /
         backend:
            serviceName: nginxservice1
            servicePort: 80
</pre>

#### Kubernetes Version
<Version of Kubernetes being used>
1.16
#### Controller Version
<Version of k8s-bigip-ctlr being used>
CIS 1.13
#### BIG-IP Version

15.1.0

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

<pre>

HTTP virtual

ltm virtual /k3s_AS3/Shared/ingress_10_169_72_169_8080 {
    creation-time 2020-02-13:10:41:38
    description Shared
    destination /k3s_AS3/10.169.72.169:8080
    ip-protocol tcp
    last-modified-time 2020-02-13:10:41:38
    mask 255.255.255.255
    persist {
        /Common/cookie {
            default yes
        }
    }
    policies {
        /k3s_AS3/Shared/Ingress_10_169_72_169_8080 { }
    }
    profiles {
        /Common/f5-tcp-progressive { }
        /Common/http { }
    }
    rules {
        /k3s_AS3/Shared/http_redirect_irule_443
    }
    serverssl-use-sni disabled
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}

[root@rancher-k3s home]# curl -v http://www.example.com:8080/
* About to connect() to www.example.com port 8080 (#0)
*   Trying 10.169.72.169...
* Connected to www.example.com (10.169.72.169) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.example.com:8080
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

ltm reset log:
Feb 13 10:46:32 vli-k8s-bigip err tmm7[12067]: 01230140:3: RST sent from 10.169.72.169:8080 to 10.169.72.189:40326, [0x298c0dc:5201] No server selected

</pre>

I suspect the HTTP request to HTTP virtual server is handled by policy Ingress_10_169_72_169_8080  for some reason fail to select pool and load balance, instead, when SSL redirect is true, I would recommend not to configure policy Ingress_10_169_72_169_8080  the HTTP virtual and let SSL redirect irule handle the request. but there is one thing I am not clear, when HTTP port is standard port 80, why the request is correctly handled by SSL redirect irule, not by the policy.

**Comment by vincentmli** [comment]
made a quick patch to remove policy Ingress_10_169_72_169_8080, still same error, so it looks the problem is not relate to the policy, probably the ssl redirect irule

**Comment by vincentmli** [comment]
I found the fix, the host variable need to take non standard http port into consideration, with port 8080, the host would be www.example.com:8080, but in datagroup, the host is www.example.com, so host does not match ssl redirect irule fail to redirect, following one line change fix the problem:

<pre>
diff --git a/pkg/appmanager/routing.go b/pkg/appmanager/routing.go
index 90c1b62..dac6368 100644
--- a/pkg/appmanager/routing.go
+++ b/pkg/appmanager/routing.go
@@ -360,7 +360,7 @@ func httpRedirectIRule(port int32) string {
        iRuleCode := fmt.Sprintf(`
                when HTTP_REQUEST {
                        # Look for exact match for combination of host name and path
-                       set host [HTTP::host]
+                       set host [getfield [HTTP::host] ":" 1]
                        set path [HTTP::path]
                        append host $path
                        # Find the number of "/" in the hostpath
</pre>

I will send a PR

**Comment by vincentmli** [comment]
created PR https://github.com/F5Networks/k8s-bigip-ctlr/pull/1181

**Comment by mdditt2000** [comment]
This issue has being resolved in CIS 1.14
