### ISSUE TITLE
Documentation issue for configmap

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/k8s-bigip-ctlr#1189]
On this page:
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-create-service-vs.html

There is an example

data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          }]
        },

Looks like there is an errant "]" that needs to be removed as that is not an array.

**Comment by mdditt2000** [comment]
@thomsonjames agree! Thanks for pointing this out. 
`"servicePort": 8080
},`

Created Jira for tech writer to fix this issue - CONTCNTR-1593

**Comment by mdditt2000** [comment]
CONTCNTR-1593 is done and closed. Closing this issue.
