### ISSUE TITLE
Remove BigIP's AS3 partition config if we change to CCCL agent.

### ISSUE THREAD

**Issue by velascoblasco** [F5Networks/k8s-bigip-ctlr#1191]
#### Description
When we have CIS+CCCL working  in an environment and then we decide to change to CIS+AS3 mode part of the process is:
- Removing BigIP's configuration in CCCL partition.
- Re-create configuration in AS3 partition (if configmaps are compatible).

This occurs and it is expected.
But if the path is the opposite and we have CIS+AS3 working  in an environment and then we decide to change to CIS+CCCL mode (something that it could be perfectly possible) CIS DO NOT remove configuration in BigIP's AS3 partition. 

This causes CIS stops to work since nothing is updated anymore in AS3 partition and nothing is updated either in CCCL partition since we cannot duplicate objects with the same value (for example a virtual server that already exists in another partition:

2020/02/27 11:02:39 [INFO] Text: u'{"code":400,"message":"01070333:3: Virtual Server /velasco/ingress_10-10-10-101_80 illegally shares destination address, source address, service port, ip-protocol, and vlan with Virtual Server /velasco_AS3/Shared/ingress_10_10_10_101_80.","errorStack":[],"apiError":3}'

#### Kubernetes Version
This is not depending on K8s version, although I have tested on v1.14

#### Controller Version
v1.13

#### BIG-IP Version
v15.1

**Comment by trinaths** [comment]
This is handled in release 2.0.
