### ISSUE TITLE
(pool-only-mode) AS3 support for pools-without-virtual-servers configmap

### ISSUE THREAD

**Issue by velascoblasco** [F5Networks/k8s-bigip-ctlr#1192]
#### Description
Currently AS3 supports two ways of configuration:

- Creating one AS3 declaration per tenant inside a configmap.
- Creating objects in K8s (Ingress Resources, Ingress Routes and Configmaps) and let CIS transform it to an AS3 declaration which then it sends to BigIP.

But whilst Ingress and Routes are supported totally Configmaps have some limitations. Currently when we create an SVC and a Configmap referring to this SVC a 'virtualAddress' is mandatory, otherwise you get errors in BigIP:

Fri, 28 Feb 2020 12:31:38 GMT - warning: [appsvcs] {"status":422,"message":"declaration is invalid","errors":["/velasco_AS3/Shared/default_velascoclusterip: should have required property 'virtualAddresses'"],"level":"warning"}

This error is sent back to CIS as response:

HTTP/1.1 422 Unprocessable Entity
Date: Fri, 28 Feb 2020 15:09:32 GMT
Content-Type: application/json; charset=UTF-8
Pragma: no-cache
Cache-Control: no-store
Cache-Control: no-cache
Cache-Control: must-revalidate
Expires: -1
Content-Length: 178
Server: Jetty(9.2.22.v20170606)

{"code":422,"errors":["/velasco_AS3/Shared/default_velascoclusterip: should have required property 'virtualAddresses'"],"declarationFullId":"","message":"declaration is invalid"}

And then we can read it in CIS logs:
2020/02/28 12:26:21 [ERROR] Invalid Virtual Server Destination IP address/Port.
2020/02/28 12:26:21 [WARNING] Unsupported resource type: configmap
2020/02/28 12:26:21 [DEBUG] AS3 Template is Validated Successfully

We get errors as well if we define only port:
            "virtualAddress": {  
              "port": 8080
            }

#### Kubernetes Version
v1.14.10

#### Controller Version
v1.13

#### BIG-IP Version
v14

#### Diagnostic Information

This happens because we are sending this part of the AS3 declaration to BigIP inside  "class": "Application":

            "default_velascoclusterip": {
               "layer4": "tcp",
               "source": "0.0.0.0/0",
               "translateServerAddress": true,
               "translateServerPort": true,
               "class": "Service_HTTP",
               "snat": "auto",
               "pool": "/velasco_AS3/Shared/cfgmap_default_velascoclusterip_velascoclusterip"
            },

In order to support 'pools-without-virtual-servers ':
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-manage-bigip-objects.html#pools-without-virtual-servers

We would need to omit above section in the declaration when we detect no virtualAddress:bindAddr.
I have tested it applying this declaration manually in BigIP and then it works:

root@(localhost)(cfg-sync Standalone)(Active)(/velasco_AS3/Shared)(tmos)# list ltm pool
ltm pool cfgmap_default_velascoclusterip_velascoclusterip {
    members {
        /velasco_AS3/192.168.235.155:http {
            address 192.168.235.155
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { cfgmap_default_velascoclusterip_velascoclusterip_0_http }
    partition velasco_AS3
}

**Comment by mdditt2000** [comment]
@velascoblasco what are you asking for here?

**Comment by veeramalla-f5** [comment]
@velascoblasco  we do not support for pool-only-mode in AS3. This is an enhancement request which we will look into.

**Comment by mdditt2000** [comment]
No plans to adopt pool-only-mode in AS3. This is out of the scope of AS3.

**Comment by mdditt2000** [comment]
Closing issue out. No plans to adopt adopt pool-only-mode in AS3
