### ISSUE TITLE
[DOC]: as3-override

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1209]
#### Description

I believe that the following could be improved in the documentation:

- When using the as3 agent the --vs-snat-pool-name parameter doesn't have effect (not even a warning).
- It is not documented how to apply the AS3 override to several features:
  + is it supported?
  + does it need several config maps?
  + does it need a single config map with several virtual server declarations? 
  --> an example would be greatly appreciated.

Many thanks

      Ulises

**Comment by trinaths** [comment]
AS3 Override is a feature in Beta to enable  configure certain BIG-IP objects that are not configurable with either ingress or routes. This will give the operator a free hand to configure advanced configurations in BIG-IP. AS3 override is not meant to be used with User defined AS3 configMap. We will improve the docs with the suggestions.

**Comment by mdditt2000** [comment]
Updated documentation 
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-as3-override.html
