### ISSUE TITLE
[RFE] make as3-override feature to have a declarative behevior

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1210]
#### Description

According to the documentation "CIS will not listen to any events on override config map", this breaks the declarative nature of k8s API. The behaviour of the config map depends if it is deployed before or after. And opens questions with respect on eliminating a config map which requires CIS restart. 

Could this be enhanced in the future by listening to the config map events?

Thanks

      Ulises

**Comment by trinaths** [comment]
We are enhancing this behaviour to be informer based. its a Work in progress now.

**Comment by mdditt2000** [comment]
Resolved in CIS 2.0. No CIS reboot required when making changes to the AS3 override feature.
