### ISSUE TITLE
Allow two bigip ctrl pods to update Same resource on F5

### ISSUE THREAD

**Issue by tocy1** [F5Networks/k8s-bigip-ctlr#1214]
Is it possible to have two bigip ctrl pods in two different but identical kubernetes cluster update the same pool in F5.
We have two identical clusters with the same apps in different zones. We want to allow the two bigip ctrl to update the same pool (app) with their respective cluster pods ip to allow failover.

**Comment by mdditt2000** [comment]
@tocy1 this is possible if you use different partitions and namespaces. Are you using a user-defined configmap, Ingress or routes? Mark

**Comment by tocy1** [comment]
@mdditt2000 Am confused about your reply. We are using user defined ingress.

**Comment by mdditt2000** [comment]
@tocy1 that answers my questions. In the controller configure use different BIGIP partitions example "--bigip-partition=controller-01", for controller one and say "--bigip-partition=controller-02", for controller two. Creating separate namespace is also good. Example namespace=prod and namespace=dev. Mark

**Comment by tocy1** [comment]
OK I get your point. But this approach will create different pools of the same app in the different partition but what i want is a single pool in one partition where both bigip ctlr pod of each cluster will  sync their respective pod ips for the same deployment as pool members.

**Comment by mdditt2000** [comment]
This is not a common use-case. BIG-IP has a issue with sharing objects accross partitions. To get this working you have to use the following:

Controller 1: --- namespace 1
Controller 2: --- namespace 2
Same service: 
configmap using sharedNodes = true so the nodes are created in common partition. Here is a example of sharedNodes 
```
"members": [
                            {
                                "servicePort": 443,
                                "serverAddresses": [],
                                **"shareNodes": true**
                            }
                        ]
                    },
```

**Comment by mdditt2000** [comment]
Closing this issue out
