### ISSUE TITLE
Allow setting HTTP Profile to "none" for simple TCP forwarding

### ISSUE THREAD

**Issue by tibers** [F5Networks/k8s-bigip-ctlr#1237]
#### Description
Enhancement: The controller defaults to HTTP Profile being HTTP, which only works for http/s services. If this is set to "none", I get simple TCP forwarding, which is what I'm after. This also makes it easier to setup HTTP forwarding if I choose not to terminate SSL on the F5.

#### Kubernetes Version
1.17.x

#### Controller Version
1.11.x?

#### BIG-IP Version
12

#### Diagnostic Information
None.

**Comment by mdditt2000** [comment]
@tibers Have you looked at  Service_TCP classes? Does this work for you?

**Comment by tibers** [comment]
I'm not following. Please provide me with a link?

**Comment by mdditt2000** [comment]
@tibers here is a example using a user-defined configmap with AS3 https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/user-defined-configmap/vzn/as3-tcp-config.yaml
