### ISSUE TITLE
OpenShift annotation virtual-server.f5.com/whitelist-source-range blocks CIS

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#1247]
#### Description
virtual-server.f5.com/whitelist-source-range does not work with CIS in AS3-mode.
When configured in one OpenShift-Route it blocks CIS and log shows "AS3 Template is not valid. see errors".
When removing whitelist, thie CIS does not recover automatically. Any other modifications to OS-Routes etc. are not accepted by CIS.
A reboot of CIS is required to make it functional again!
#### Kubernetes Version
v1.11.0+d4cacc0

#### OpenShift Master:
v3.11.82 

#### Controller Version
Version: 1.15.0-WIP, BuildInfo: tsomanchi-ee674b9-dirty-20200402164009

#### BIG-IP Version
14.1.2.3-0.129.5

#### Diagnostic Information
#01 The following annotations are used in the relevant OpenSift-Route:
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    virtual-server.f5.com/balance: round-robin
    virtual-server.f5.com/health: |
      [
        {
          "path":     "/",
          "send":     "GET / HTTP/1.1\\r\\nHost: httpd-example-f5test.telitcaas1.t-internal.com\\r\\nConnection: Close\\r\\n\\r\\n",
          "recv":     "200 OK",
          "interval": 5,
          "timeout":  16
        }
      ]
    virtual-server.f5.com/waf: /Common/RD_000_ASMPOLICY_BASIC_f5test_httpd-example
    virtual-server.f5.com/whitelist-source-range: '1.2.3.4/32,2.2.2.0/24'

#02 CIS-log:
2020/04/20 14:24:24 [ERROR] AS3 Template is not valid. see errors :
2020/04/20 14:24:24 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid
2020/04/20 14:24:24 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: Must validate "then" as "if" was valid
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: Must validate one and only one schema (oneOf)
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: path is required
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: Must validate all the schemas (allOf)
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: Must validate "then" as "if" was valid
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: Must validate one and only one schema (oneOf)
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: all is required
2020/04/20 14:24:24 [ERROR] - declaration.Shared.rules.36.conditions.1: name is required
[...]

#### expected target-configuration performed by CIS
CIS should add a rule in LTM policy openshift_secure_routes - see example below.

       osr_f5test_httpd_example {
            actions {
                0 {
                    forward
                    select
                    pool POOL_ASM_TEST
                }
                1 {
                    asm
                    enable
                    policy /Common/RD_000_WAF_BASIC_GENERIC
                }
            }
            conditions {
                0 {
                    http-header
                    name host
                    values { httpd-example-f5test.telitcaas2.t-internal.com }
                }
                1 {
                    tcp
                    client-accepted
                    address
                    matches
                    values { 10.10.10.0/24 22.22.22.22/32 10.10.11.0/24 }
                }
            }

**Comment by mdditt2000** [comment]
@dstokesf5 can we achieve the address match using the Enforcement_Rule_Flow_Filter conditions in AS3 to achieve the match values { 10.10.10.0/24 22.22.22.22/32 10.10.11.0/24 }? Do you have an AS3 example?

**Comment by dstokesf5** [comment]
The most reliable way to recreate that LTM policy would be with AS3's Endpoint Policies. However, the tcp condition is not yet exposed: https://github.com/F5Networks/f5-appsvcs-extension/issues/211

Resolving that GitHub issue is currently a high priority for us since it is a commonly requested feature.

**Comment by mdditt2000** [comment]
Internal Jira CONTCNTR-1828. Waiting for AS3-20 for support for F5Networks/f5-appsvcs-extension#211 

Planning for CIS 2.1

**Comment by mdditt2000** [comment]
Still awaiting AS3-20. Release June 4th

**Comment by mdditt2000** [comment]
Closing Github issue. Issue is resolved and will be available in CIS 2.1 

Status: | Review Done
-- | --
Done

Have a wonderful vacation. Working on getting the three issue for AB testing also resolved in CIS 2.1
