### ISSUE TITLE
CC monitor by Prometheus issue

### ISSUE THREAD

**Issue by liaotx** [F5Networks/k8s-bigip-ctlr#1264]
i know CC parameter “--http-listen-address” is use to pull data to Prometheus, but i want to know what data that Prometheus will get ,is customize by Prometheus ? what kind of data will be get by Prometheus  (all of kind ) ?

i just get some step that get node-export data but no pods ,are you has some configuration steps that how to monitor CC(pods) by Prometheus ?

#### Kubernetes Version
GitVersion:"v1.16.3",

#### Controller Version
V1.11.1

#### BIG-IP Version
v13.1.3.2

**Comment by mdditt2000** [comment]
Hello @liaotx Did you create a Target in Prometheus to pull get node-export data? I will try that later in the week. BTW i created the following document from Prometheus to pull BIGIP metrics. https://github.com/mdditt2000/prometheus

**Comment by mdditt2000** [comment]
You can pull data to Prometheus using the following command curl -s localhost:8080/metrics | grep bigip

```
[root@k8s-1-18-master prometheus]# curl -s 10.244.2.31:8080/metrics | grep bigip
# HELP bigip_monitored_nodes Total count of monitored nodes by the BigIP k8s CTLR
# TYPE bigip_monitored_nodes gauge
bigip_monitored_nodes{nodeselector=""} 4
# HELP bigip_monitored_services Total count of monitored services by the BigIP k8s CTLR
# TYPE bigip_monitored_services gauge
bigip_monitored_services{name="ingress_10-192-75-107_443",namespace="monitoring",status="port-not-found"} 0
bigip_monitored_services{name="ingress_10-192-75-107_443",namespace="monitoring",status="service-not-found"} 0
bigip_monitored_services{name="ingress_10-192-75-107_443",namespace="monitoring",status="success"} 1
bigip_monitored_services{name="ingress_10-192-75-107_80",namespace="monitoring",status="port-not-found"} 0
bigip_monitored_services{name="ingress_10-192-75-107_80",namespace="monitoring",status="service-not-found"} 0
bigip_monitored_services{name="ingress_10-192-75-107_80",namespace="monitoring",status="success"} 1
bigip_monitored_services{name="ingress_10-192-75-108_80",namespace="default",status="port-not-found"} 0
bigip_monitored_services{name="ingress_10-192-75-108_80",namespace="default",status="service-not-found"} 0
bigip_monitored_services{name="ingress_10-192-75-108_80",namespace="default",status="success"} 1
[root@k8s-1-18-master prometheus]#
```
I am going to try add this as a target however its rather silly that prometheus needs to know the target. Container can its address......

**Comment by liaotx** [comment]
> You can pull data to Prometheus using the following command curl -s localhost:8080/metrics | grep bigip
> 
> ```
> [root@k8s-1-18-master prometheus]# curl -s 10.244.2.31:8080/metrics | grep bigip
> # HELP bigip_monitored_nodes Total count of monitored nodes by the BigIP k8s CTLR
> # TYPE bigip_monitored_nodes gauge
> bigip_monitored_nodes{nodeselector=""} 4
> # HELP bigip_monitored_services Total count of monitored services by the BigIP k8s CTLR
> # TYPE bigip_monitored_services gauge
> bigip_monitored_services{name="ingress_10-192-75-107_443",namespace="monitoring",status="port-not-found"} 0
> bigip_monitored_services{name="ingress_10-192-75-107_443",namespace="monitoring",status="service-not-found"} 0
> bigip_monitored_services{name="ingress_10-192-75-107_443",namespace="monitoring",status="success"} 1
> bigip_monitored_services{name="ingress_10-192-75-107_80",namespace="monitoring",status="port-not-found"} 0
> bigip_monitored_services{name="ingress_10-192-75-107_80",namespace="monitoring",status="service-not-found"} 0
> bigip_monitored_services{name="ingress_10-192-75-107_80",namespace="monitoring",status="success"} 1
> bigip_monitored_services{name="ingress_10-192-75-108_80",namespace="default",status="port-not-found"} 0
> bigip_monitored_services{name="ingress_10-192-75-108_80",namespace="default",status="service-not-found"} 0
> bigip_monitored_services{name="ingress_10-192-75-108_80",namespace="default",status="success"} 1
> [root@k8s-1-18-master prometheus]#
> ```
> 
> I am going to try add this as a target however its rather silly that prometheus needs to know the target. Container can its address......

thanks and yes  i had try use prometheus in a node-export env ,and i can get some data. but i want to know what it can get in a CC pods . i heard that prometheus can monitor CC ,but i has no idea how to use in CC

**Comment by mdditt2000** [comment]
I updated the document. 
https://github.com/mdditt2000/prometheus

Please look at the job list to get CIS into the dashboard. 
https://github.com/mdditt2000/prometheus/blob/master/cis-job-name.yaml

**Comment by mdditt2000** [comment]
Closing issue out
