### ISSUE TITLE
Update F5 takes long time after creation/update Ingress resources

### ISSUE THREAD

**Issue by wheestermans31** [F5Networks/k8s-bigip-ctlr#1286]
I'm seeing the following behaviour many times. If we create new ingress resource or update, then it takes a very long time before we see the changes reflected inside the F5 console, sometimes even minutes!

We are using the BIGIP controller version 1.13.0, running inside Docker-EE , kubernetes v1.14.8-docker-1

These are the arguments of the controller

    spec:
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=https://<URL>
        - --bigip-partition=KuberNetes
        - --pool-member-type=cluster
        - --namespace=tme-ns-java-dev
        - --namespace=tme-ns-http-dev
        - --namespace=tme-ns-nodejs-dev
        - --namespace=tme-ns-jetty-dev
        - --namespace=tme-ns-python-dev
        - --namespace=tme-ns-kong-dev
        - --vs-snat-pool-name=KuberNat
        - --manage-configmaps=false
        - --log-level=WARNING
        - --verify-interval=30
        - --node-poll-interval=10
        - --node-poll-interval=10

Any reason why updates can take minutes after Ingress controller creation and/or update?

**Comment by mdditt2000** [comment]
@wheestermans31 please can you move to the new AS3 API. Here is a guide that provides what you need. 

https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%201.14/QuickStartGuideCluster.md

One slight change in the arguments. Please change true to ingress 

- "--manage-ingress=true"
- "--manage-routes=false"
- "--manage-configmaps=false"

Please monitor the AS3 logs using 
kubectl logs -f k8s-bigip-ctlr-deployment -n kube-system | grep --color=auto -i '\[as3'

**Comment by wheestermans31** [comment]
For the AS3 api, we need Kubernetes 1.8?

**Comment by trinaths** [comment]
@wheestermans31 - No. as @mdditt2000 updated, change your controller deployment config to

```
--manage-ingress=true
--manage-routes=false
--manage-configmaps=false
--agent=as3
```

**Comment by wheestermans31** [comment]
What about the required k8s level required?

**Comment by trinaths** [comment]
@wheestermans31  please refer to [supported version matrix for CIS](https://clouddocs.f5.com/containers/v2/releases_and_versioning.html).

**Comment by mdditt2000** [comment]
kubernetes v1.14.8 is fine

**Comment by mdditt2000** [comment]
This issue can be closed.
