### ISSUE TITLE
CIS with AS3 agent doesn't work with route domains

### ISSUE THREAD

**Issue by hunterx19** [F5Networks/k8s-bigip-ctlr#1287]
#### Description
When you want to use route domains with AS3 agent _AS3 partition created by the controller doesn't take route domain identifier from partition defined in controller deployment config, instead it creates _AS3 partition in route domain 0.

Consequences of that are that pool members in _AS3 partition don't have required route domain identifier and traffic flow is not working in route domain.

When using CCCL as agent route domains are working correctly.  

#### Kubernetes Version
OCP 3.11

#### Controller Version
1.14

#### BIG-IP Version
14.1.2.3

**Comment by mdditt2000** [comment]
Internal PM Jira CONTCNTR-1751. Would add option to the CIS controller that will allow for a route domain example defaultRouteDomain": 10,

Only one route domain will be support per CIS controller.

**Comment by trinaths** [comment]
For Route Domain support, can you try override AS3 ?

Example override AS3

```
apiVersion: v1
data:
  template: |
    {
        "declaration": {
            "test_AS3": {
                "defaultRouteDomain": 20              <== Refer Route domain ID existing in BIGIP
            }
        }
    }
kind: ConfigMap
metadata:
  labels:
    f5type: virtual-server
    overrideAS3: "true"
  name: override-as3-cm
  namespace: default
```

**Comment by hunterx19** [comment]
> For Route Domain support, can you try override AS3 ?
> 
> Example override AS3
> 
> ```
> apiVersion: v1
> data:
>   template: |
>     {
>         "declaration": {
>             "test_AS3": {
>                 "defaultRouteDomain": 20              <== Refer Route domain ID existing in BIGIP
>             }
>         }
>     }
> kind: ConfigMap
> metadata:
>   labels:
>     f5type: virtual-server
>     overrideAS3: "true"
>   name: override-as3-cm
>   namespace: default
> ```
> 
> You need to delete the existing CIS managed partitions before applying or updating the Route Domain.

I needed a quick fix so I configured new vCMP guests to avoid route domains. 
But if I will have need in the future I will try this AS3 workaround.

**Comment by pedrorouremalta** [comment]
Same problem here. But I'm using Openshift Routes. Is there any workaround that I can use in this scenario? Or the only option would be to use the CCCL agent until the option that allows to specify the default route domain to be used in the _AS3 partition be ​​released ? Thanks in advance.
