### ISSUE TITLE
Error parsing ConfigMap 

### ISSUE THREAD

**Issue by mariuszbugaj** [F5Networks/k8s-bigip-ctlr#1290]
#### Description
k8s-bigip-ctrl reports errors "Error parsing ConfigMap static-as3_f5-cm-apps". Data section of configmap is correct because was verified via Postman POST and f5 big-ip don't report any issues. 
Despite of the errors all configuration from configmap is correctly send and processed by f5-bigip.

#### Kubernetes Version
Openshift OCP 4.3.13

#### Controller Version
f5networks/k8s-bigip-ctlr:1.14.0

#### BIG-IP Version

BIG-IP | 15.1.0.2 | 0.0.9

#### Diagnostic Information

Logs from container f5-ctrl 
Configuration : config-map, service, k8s-bigip-ctrl deployment

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-cm-apps
  namespace: static-as3
  selfLink: /api/v1/namespaces/static-as3/configmaps/f5-cm-apps
  uid: 4875c28c-0cad-4942-b40b-2978745ba844
  resourceVersion: '5685102'
  creationTimestamp: '2020-05-06T13:10:02Z'
  labels:
    as3: 'true'
    f5type: virtual-server
data:
  template: |
    {
      "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "d492687a-bd1d-478d-987b-9590253c5099",
        "label": "Sample AS3",
        "remark": "Simple HTTPS Service",
        "T1aplikacje": {
          "class": "Tenant",
          "static-as3": {
            "class": "Application",
            "template": "generic",
            "V1apkaStaticAS3": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                "10.232.10.106"
              ],
              "enable": true,
              "persistenceMethods": ["source-address"],
              "virtualPort": 443,
              "profileTCP": "mobile",
              "pool": "webpool",
              "profileHTTP": { "use": "http_prof_mid_security" },
              "profileHTTPAcceleration": { "use": "my_caching" },
              "profileHTTPCompression": { "use":"my_compression" },
              "iRules": ["irule1"],
              "redirect80": true,
              "serverTLS": { "bigip": "/Common/myclientssl" }
            },
            "webpool": {
              "class": "Pool",
              "loadBalancingMode": "dynamic-ratio-member",
              "monitors": [
                "http"
              ],
              "reselectTries": 1,
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "irule1": {
                 "class": "iRule",
                 "iRule": "when CLIENT_ACCEPTED { }"
            },
            "http_prof_mid_security": {
              "class": "HTTP_Profile",
              "proxyType": "reverse",
              "requestChunking": "rechunk",
              "responseChunking": "rechunk",
              "allowedResponseHeaders": [
                "content-type",
                "set-cookie",
                "location",
                "date",
                "expires",
                "cache-control",
                "pragma",
                "vary",
                "content-encoding",
                "keep-alive",
                "connection" 
              ],
              "fallbackRedirect": "http://www.plus.pl",
              "xForwardedFor": true
            },
            "my_caching": {
              "class": "HTTP_Acceleration_Profile",
              "parentProfile": { "bigip": "/Common/webacceleration" },
              "maximumObjectSize": 200000,
              "maximumEntries": 5000,
              "maximumAge": 120
            },
            "my_compression": {
              "class": "HTTP_Compress",
              "minimumSize": 2000
            }
          }
        }
      }
    }
```

```
kind: Service
apiVersion: v1
metadata:
  name: static-as3-service
  namespace: static-as3
  selfLink: /api/v1/namespaces/static-as3/services/static-as3-service
  uid: 49d4f54c-2bcd-4aec-822d-0083170f6266
  resourceVersion: '5684143'
  creationTimestamp: '2020-05-06T13:07:40Z'
  labels:
    cis.f5.com/as3-app: static-as3
    cis.f5.com/as3-pool: webpool
    cis.f5.com/as3-tenant: T1aplikacje
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"cis.f5.com/as3-app":"static-as3","cis.f5.com/as3-pool":"webpool","cis.f5.com/as3-tenant":"T1aplikacje"},"name":"static-as3-service","namespace":"static-as3"},"spec":{"ports":[{"port":80,"protocol":"TCP"}],"selector":{"app":"static-as3"}}}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: static-as3
  clusterIP: 172.30.205.193
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
```
----- Logs -----
```

2020/05/06 08:11:19 [DEBUG] Updated 2 of 2 virtual server configs, deleted 0
2020/05/06 08:11:19 [DEBUG] AS3 Template is Validated Successfully 

2020/05/06 08:11:19 [DEBUG] [AS3] No Change in the Configuration
2020/05/06 08:11:19 [DEBUG] Finished syncing virtual servers {Namespace:static-route ServiceName:f5-demo-app-service-basic AS3Name: AS3Data:} (86.196573ms)

**2020/05/06 08:11:24 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:T1aplikacje --- message: no change
2020/05/06 08:11:24 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:sdn_AS3 --- message: success**
2020/05/06 08:11:24 [DEBUG] [AS3] Admitted Route -  f5-demo-app-route-basic
2020/05/06 08:11:25 [DEBUG] Configured rule: {openshift_route_static-route_f5-demo-app-route-basic demo.f5.ocp.lwm.plusnet/ 0 [0xc00032f2c0] [0xc00163a440]}
2020/05/06 08:11:25 [DEBUG] Found endpoints for backend {ServiceName:f5-demo-app-service-basic ServicePort:8080 Namespace:static-route}: [{10.128.3.47 8080 user-enabled} {10.128.3.48 8080 user-enabled} {10.128.3.49 8080 user-enabled} {10.131.0.201 8080 user-enabled} {10.131.0.202 8080 user-enabled} {10.131.0.203 8080 user-enabled}]
2020/05/06 08:11:25 [DEBUG] Configured rule: {openshift_route_static-route_f5-demo-app-
```

```
Looks like there is routes and configmap 

Admitted Route -  f5-demo-app-route-basic
Found AS3 ConfigMap
```

2020/05/06 08:11:42 [DEBUG] Finished syncing virtual servers {Namespace:openshift-controller-manager ServiceName:controller-manager AS3Name: AS3Data:} (9.154µs)
**2020/05/06 08:11:42 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps**
2020/05/06 08:11:42 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/06 08:11:42 [DEBUG] Finished syncing virtual servers {Namespace:static-as3 
2020/05/06 08:11:42 [DEBUG] [AS3] Found AS3 ConfigMap - f5-cm-apps.
2020/05/06 08:11:42 [DEBUG] [AS3] Active ConfigMap: (f5-cm-apps)

2020/05/06 08:11:42 [DEBUG] [AS3] Processing AS3 cfgMap (f5-cm-apps) with AS3 Manager.

2020/05/06 08:11:42 [DEBUG] [AS3] Started Parsing the AS3 Object
2020/05/06 08:11:42 [DEBUG] [AS3] Discovering endpoints for pool: [T1aplikacje -> static-as3 -> webpool]
2020/05/06 08:11:42 [DEBUG] [AS3] Discovered members for service static-as3-service is [{10.131.0.209 80 }]
2020/05/06 08:11:42 [DEBUG] Updating AS3 Template for tenant 'T1aplikacje' app 'static-as3' pool 'webpool', 
2020/05/06 08:11:42 [DEBUG] [AS3] AS3 Template is populated with the pool members
2020/05/06 08:11:42 [DEBUG] AS3 Template is Validated Successfully 

2020/05/06 08:11:42 [DEBUG] [AS3] No Change in the Configuration
2020/05/06 08:11:43 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
(9.757µs)
**2020/05/06 08:11:43 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps**
2020/05/06 08:11:43 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/06 08:11:43 [DEBUG] Finished syncing virtual servers {Namespace:static-as3 ServiceName:static-as3-service AS3Name: AS3Data:} (236.623µs)

----------------------------------------------------------

```
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/k8s-bigip-ctlr
  resourceVersion: '5605080'
  name: k8s-bigip-ctlr
  uid: 143d4225-8f8a-4c87-a2ff-6cda58539856
  creationTimestamp: '2020-04-30T11:47:04Z'
  generation: 10
  namespace: kube-system
  labels:
    app: k8s-bigip-ctlr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr
    spec:
      restartPolicy: Always
      serviceAccountName: bigip-ctlr
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: k8s-bigip-ctlr
          command:
            - /app/bin/k8s-bigip-ctlr
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'f5networks/k8s-bigip-ctlr:1.14.0'
          args:
            - '--bigip-username=$(BIGIP_USERNAME)'
            - '--bigip-password=$(BIGIP_PASSWORD)'
            - '--bigip-url=https://10.232.10.3'
            - '--insecure=true'
            - '--bigip-partition=sdn'
            - '--pool-member-type=cluster'
            - '--openshift-sdn-name=/Common/openshift_vxlan'
            - '--agent=as3'
            - '--as3-validation=false'
            - '--log-as3-response=true'
            - '--route-label=bigipa'
            - '--log-level=DEBUG'
            - '--manage-routes=true'
            - '--route-vserver-addr=10.232.10.102'
            - '--default-ingress-ip=10.232.10.103'
      serviceAccount: bigip-ctlr
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 2147483647
  progressDeadlineSeconds: 2147483647
status:
  observedGeneration: 10
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-04-30T11:47:04Z'
      lastTransitionTime: '2020-04-30T11:47:04Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
```

**Comment by mdditt2000** [comment]
afternoon @mariuszbugaj please can you upload, contribute your user-defined configmap to my repo so that i can use for testing.

https://github.com/mdditt2000/kubernetes-1-18/tree/master/cis%201.14/github-issue/%231290

**Comment by mdditt2000** [comment]
@mariuszbugaj it looks are using user-defined configmap and routes on the same controller. Am i correct?

**Comment by mariuszbugaj** [comment]
Hi,

Yes, but errors are related to configmap.

**Comment by trinaths** [comment]
@mariuszbugaj  - Can you share the configMap - `static-as3_f5-cm-apps` which is giving errors as shown in logs.

**Comment by mariuszbugaj** [comment]
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:lanwan ServiceName:ubi AS3Name: AS3Data:} (11.76µs)
2020/05/14 09:35:08 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:openshift-monitoring ServiceName:telemeter-client AS3Name: AS3Data:} (11.273µs)
2020/05/14 09:35:08 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:openshift-image-registry ServiceName:image-registry-operator AS3Name: AS3Data:} (10.555µs)
2020/05/14 09:35:08 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:openshift-machine-config-operator ServiceName:machine-config-daemon AS3Name: AS3Data:} (10.391µs)
2020/05/14 09:35:08 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:lanwan ServiceName:networktool AS3Name: AS3Data:} (10.211µs)
2020/05/14 09:35:08 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/14 09:35:08 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:static-as3 ServiceName:static-as3-service AS3Name: AS3Data:} (21.516µs)
2020/05/14 09:35:08 [DEBUG] Updated 0 of 0 virtual server configs, deleted 0
2020/05/14 09:35:08 [DEBUG] Finished syncing virtual servers {Namespace:lanwan ServiceName:dc-metro-map-webhook AS3Name: AS3Data:} (11.233µs)
2020/05/14 09:35:08 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps


kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-cm-apps
  namespace: static-as3
  selfLink: /api/v1/namespaces/static-as3/configmaps/f5-cm-apps
  uid: 4875c28c-0cad-4942-b40b-2978745ba844
  resourceVersion: '7636258'
  creationTimestamp: '2020-05-06T13:10:02Z'
  labels:
    as3: 'true'
    f5type: virtual-server
data:
  template: |
    {
      "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "d492687a-bd1d-478d-987b-9590253c5099",
        "label": "Sample AS3",
        "remark": "Simple HTTPS Service",
        "T1aplikacje": {
          "class": "Tenant",
          "static-as3": {
            "class": "Application",
            "template": "generic",
            "V1apkaStaticAS3": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                "10.232.10.106"
              ],
              "enable": true,
              "persistenceMethods": ["source-address"],
              "virtualPort": 443,
              "profileTCP": "mobile",
              "pool": "webpool",
              "profileHTTP": { "use": "http_prof_mid_security" },
              "profileHTTPAcceleration": { "use": "my_caching" },
              "profileHTTPCompression": { "use":"my_compression" },
              "iRules": ["irule1"],
              "redirect80": true,
              "serverTLS": { "bigip": "/Common/myclientssl" }
            },
            "webpool": {
              "class": "Pool",
              "loadBalancingMode": "dynamic-ratio-member",
              "monitors": [
                "http"
              ],
              "reselectTries": 1,
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "irule1": {
                 "class": "iRule",
                 "iRule": "when CLIENT_ACCEPTED { }"
            },
            "http_prof_mid_security": {
              "class": "HTTP_Profile",
              "proxyType": "reverse",
              "requestChunking": "rechunk",
              "responseChunking": "rechunk",
              "allowedResponseHeaders": [
                "content-type",
                "set-cookie",
                "location",
                "date",
                "expires",
                "cache-control",
                "pragma",
                "vary",
                "content-encoding",
                "keep-alive",
                "connection" 
              ],
              "fallbackRedirect": "http://www.plus.pl",
              "xForwardedFor": true
            },
            "my_caching": {
              "class": "HTTP_Acceleration_Profile",
              "parentProfile": { "bigip": "/Common/webacceleration" },
              "maximumObjectSize": 200000,
              "maximumEntries": 5000,
              "maximumAge": 120
            },
            "my_compression": {
              "class": "HTTP_Compress",
              "minimumSize": 2000
            }
          },
          "f5-demo-as3": {
            "class": "Application",
            "template": "generic",
            "V1apkaF5DEMOAS3": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                "10.232.10.108"
              ],
              "enable": true,
              "persistenceMethods": ["source-address"],
              "virtualPort": 443,
              "profileTCP": "mobile",
              "pool": "webpoolwebhook",
              "profileHTTP": { "use": "http_prof_mid_security" },
              "profileHTTPAcceleration": { "use": "my_caching" },
              "profileHTTPCompression": { "use":"my_compression" },
              "iRules": ["irule1"],
              "redirect80": true,
              "serverTLS": { "bigip": "/Common/myclientssl" }
            },
            "webpoolwebhook": {
              "class": "Pool",
              "loadBalancingMode": "dynamic-ratio-member",
              "monitors": [
                "http"
              ],
              "reselectTries": 1,
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "irule1": {
                 "class": "iRule",
                 "iRule": "when CLIENT_ACCEPTED { }"
            },
            "http_prof_mid_security": {
              "class": "HTTP_Profile",
              "proxyType": "reverse",
              "requestChunking": "rechunk",
              "responseChunking": "rechunk",
              "allowedResponseHeaders": [
                "content-type",
                "set-cookie",
                "location",
                "date",
                "expires",
                "cache-control",
                "pragma",
                "vary",
                "content-encoding",
                "keep-alive",
                "connection" 
              ],
              "fallbackRedirect": "http://www.plus.pl",
              "xForwardedFor": true
            },
            "my_caching": {
              "class": "HTTP_Acceleration_Profile",
              "parentProfile": { "bigip": "/Common/webacceleration" },
              "maximumObjectSize": 200000,
              "maximumEntries": 5000,
              "maximumAge": 120
            },
            "my_compression": {
              "class": "HTTP_Compress",
              "minimumSize": 2000
            }
          }
        }
      }
    }

**Comment by mdditt2000** [comment]
Correct AS3 user-defined cfgmap isnt valid. 

```
2020/05/15 17:00:04 [ERROR] [AS3] Template is not valid. see errors
2020/05/15 17:00:04 [ERROR] [AS3] Error validating AS3 template
2020/05/15 17:00:04 [ERROR] [AS3] Error while processing user defined AS3 cfgMap Name: f5-cm-apps
2020/05/15 17:00:22 [ERROR] [AS3] Template is not valid. see errors
2020/05/15 17:00:22 [ERROR] [AS3] Error validating AS3 template
2020/05/15 17:00:22 [ERROR] [AS3] Error while processing user defined AS3 cfgMap Name: f5-cm-apps
2020/05/15 17:00:22 [ERROR] [AS3] Template is not valid. see errors
2020/05/15 17:00:22 [ERROR] [AS3] Error validating AS3 template
2020/05/15 17:00:22 [ERROR] [AS3] Error while processing user defined AS3 cfgMap Name: f5-cm-apps
```
https://github.com/mdditt2000/kubernetes-1-18/tree/master/cis%201.14/github-issue/%231290

**Comment by mdditt2000** [comment]
@mariuszbugaj please make the following changes

https://github.com/mdditt2000/kubernetes-1-18/commit/5c75560e3d1cb4eafd7ce5d2ae4f7ea48b48bd45

You need to remove 
```
"$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
```
Please use the correct AS3 schema. You using AS3-19? I tested with AS3-18 using CIS 2.0 and successful able to deploy your CM

```
2020/05/15 17:30:19 [DEBUG] [AS3] Posting AS3 Declaration
2020/05/15 17:30:19 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/05/15 17:30:20 [ERROR] [AS3] Big-IP Responded with code: 422
2020/05/15 17:30:20 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: message:Unable to find /Common/myclientssl for /T1aplikacje/static-as3/V1apkaStaticAS3/serverTLS]
2020/05/15 17:30:20 [DEBUG] [AS3] Error handling for event statusCommonResponse
```
Used the following CM 

https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%201.14/github-issue/%231290/f5-cm-apps-static-as3-only.yaml

**Comment by mariuszbugaj** [comment]
Hi,

I removed AS3 schemat and put suggested CM but still controller reports errors.


2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:16 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:45 [INFO] Successfully Sent the FDB Records
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps
2020/05/18 20:58:47 [ERROR] Error parsing ConfigMap static-as3_f5-cm-apps


kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-cm-apps
  namespace: static-as3
  selfLink: /api/v1/namespaces/static-as3/configmaps/f5-cm-apps
  uid: 4875c28c-0cad-4942-b40b-2978745ba844
  resourceVersion: '10425696'
  creationTimestamp: '2020-05-06T13:10:02Z'
  labels:
    as3: 'true'
    f5type: virtual-server
data:
  template: |
    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "d492687a-bd1d-478d-987b-9590253c5099",
            "label": "Sample AS3",
            "remark": "Simple HTTPS Service",
            "T1aplikacje": {
                "class": "Tenant",
                "static-as3": {
                    "class": "Application",
                    "template": "generic",
                    "V1apkaStaticAS3": {
                        "class": "Service_HTTPS",
                        "virtualAddresses": [
                            "10.232.10.106"
                        ],
                        "enable": true,
                        "persistenceMethods": [
                            "source-address"
                        ],
                        "virtualPort": 443,
                        "profileTCP": "mobile",
                        "pool": "webpool",
                        "profileHTTP": {
                            "use": "http_prof_mid_security"
                        },
                        "profileHTTPAcceleration": {
                            "use": "my_caching"
                        },
                        "profileHTTPCompression": {
                            "use": "my_compression"
                        },
                        "iRules": [
                            "irule1"
                        ],
                        "redirect80": true,
                        "serverTLS": {
                            "bigip": "/Common/myclientssl"
                        }
                    },
                    "webpool": {
                        "class": "Pool",
                        "loadBalancingMode": "dynamic-ratio-member",
                        "monitors": [
                            "http"
                        ],
                        "reselectTries": 1,
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "irule1": {
                        "class": "iRule",
                        "iRule": "when CLIENT_ACCEPTED { }"
                    },
                    "http_prof_mid_security": {
                        "class": "HTTP_Profile",
                        "proxyType": "reverse",
                        "requestChunking": "rechunk",
                        "responseChunking": "rechunk",
                        "allowedResponseHeaders": [
                            "content-type",
                            "set-cookie",
                            "location",
                            "date",
                            "expires",
                            "cache-control",
                            "pragma",
                            "vary",
                            "content-encoding",
                            "keep-alive",
                            "connection"
                        ],
                        "fallbackRedirect": "http://www.plus.pl",
                        "xForwardedFor": true
                    },
                    "my_caching": {
                        "class": "HTTP_Acceleration_Profile",
                        "parentProfile": {
                            "bigip": "/Common/webacceleration"
                        },
                        "maximumObjectSize": 200000,
                        "maximumEntries": 5000,
                        "maximumAge": 120
                    },
                    "my_compression": {
                        "class": "HTTP_Compress",
                        "minimumSize": 4000
                    }
                }
            }
        }
    }

**Comment by mdditt2000** [comment]
@mariuszbugaj can you please email me at m.dittmer@f5.com. Tomorrow setup a zoom call to look at this issue and work on a resolution.

**Comment by mdditt2000** [comment]
SR filed for this issue C3274502
Internal Jira filed for this issue CONTCNTR-1846

**Comment by mariuszbugaj** [comment]
Hello,

I've changed name of configmap to the f5cmapps and still get errors. According name convention I see that underscore character is added automatically but it does not exist in ConfigMap definition. Where is the problem ?

[root@k8s-1-18-master 1-6279714721]# kubectl create -f static-as3_definition.yaml The ConfigMap "static-as3_definition" is invalid: metadata.name: Invalid value: "static-as3_definition": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')


2020/06/02 10:30:05 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps
2020/06/02 10:30:23 [ERROR] Error parsing ConfigMap static-as3_f5cmapps


New ConfigMap 

kind: ConfigMap
apiVersion: v1
metadata:
  name: f5cmapps
  namespace: static-as3
  selfLink: /api/v1/namespaces/static-as3/configmaps/f5cmapps
  uid: 690b6875-83a8-4f30-ad0e-f9c20580a77c
  resourceVersion: '16081603'
  creationTimestamp: '2020-06-02T10:22:23Z'
  labels:
    as3: 'true'
    f5type: virtual-server
data:
  template: |
    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "d492687a-bd1d-478d-987b-9590253c5099",
            "label": "Sample AS3",
            "remark": "Simple HTTPS Service",
            "T1aplikacje": {
                "class": "Tenant",
                "staticas3": {
                    "class": "Application",
                    "template": "generic",
                    "V1apkaStaticAS3": {
                        "class": "Service_HTTPS",
                        "virtualAddresses": [
                            "10.232.10.106"
                        ],
                        "enable": true,
                        "persistenceMethods": [
                            "source-address"
                        ],
                        "virtualPort": 443,
                        "profileTCP": "mobile",
                        "pool": "webpool",
                        "profileHTTP": {
                            "use": "http_prof_mid_security"
                        },
                        "profileHTTPAcceleration": {
                            "use": "my_caching"
                        },
                        "profileHTTPCompression": {
                            "use": "my_compression"
                        },
                        "iRules": [
                            "irule1"
                        ],
                        "redirect80": true,
                        "serverTLS": {
                            "bigip": "/Common/myclientssl"
                        }
                    },
                    "webpool": {
                        "class": "Pool",
                        "loadBalancingMode": "dynamic-ratio-member",
                        "monitors": [
                            "http"
                        ],
                        "reselectTries": 1,
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "irule1": {
                        "class": "iRule",
                        "iRule": "when CLIENT_ACCEPTED { }"
                    },
                    "http_prof_mid_security": {
                        "class": "HTTP_Profile",
                        "proxyType": "reverse",
                        "requestChunking": "rechunk",
                        "responseChunking": "rechunk",
                        "allowedResponseHeaders": [
                            "content-type",
                            "set-cookie",
                            "location",
                            "date",
                            "expires",
                            "cache-control",
                            "pragma",
                            "vary",
                            "content-encoding",
                            "keep-alive",
                            "connection"
                        ],
                        "fallbackRedirect": "http://www.plus.pl",
                        "xForwardedFor": true
                    },
                    "my_caching": {
                        "class": "HTTP_Acceleration_Profile",
                        "parentProfile": {
                            "bigip": "/Common/webacceleration"
                        },
                        "maximumObjectSize": 200000,
                        "maximumEntries": 5000,
                        "maximumAge": 120
                    },
                    "my_compression": {
                        "class": "HTTP_Compress",
                        "minimumSize": 4000
                    }
                }
            }
        }
    }



Regards,
Mariusz
