### ISSUE TITLE
The namespace parameter doesn't work as expected

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/k8s-bigip-ctlr#1295]
#### Description
Our understanding is that the namespace parameter when specified in the CIS deployment, it should only monitor for services/configmaps in that particular namespace.
However, initial tests shows that the configuration is pushed to BIGIP when configmap is created on any namespace regardless of which namespace is specified in the CIS for that BIGIP.
#### Kubernetes Version
OpenShift 4.3

#### Controller Version
1.14

#### BIG-IP Version
15.1

#### Diagnostic Information
Here is the parameters in CIS deployment file. As can be seen the namespace specified is "cnf"

"--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.75.71.153",
            "--namespace=cnf",
            "--bigip-partition=kubernetes",
            "--insecure=true",
            "--agent=as3",
            "--log-level=DEBUG",
            "--log-as3-response=true",
            "--pool-member-type=cluster",
            "--openshift-sdn-name=/Common/ocp-ingress-1"

And beloqw is the configmap which is deployed in namespace called nat46. So the expectation is that CIS should not be pushing this configuration to BIGIP. However the configuration is pushed and and the partition and VS, pools etc are created in BIGIP

kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-multitool
  namespace: nat46
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.17.0",
            "id": "multitool-deployment",
            "icni": {
                "class": "Tenant",
                "Shared": {
                  "class": "Application",
                  "template": "shared",
                  "ingress_snatpool": {
                  "class": "SNAT_Pool",
                  "snatAddresses": [
                    "10.120.27.135"
                  ] 
                 } 
                },
                "icni_app": {
                    "class": "Application",
                    "template": "generic",
                    "VS_Ingress_WSNIR": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                                "10.120.27.136"
                        ],
                        "virtualPort": 0,
                        "pool": "icni_app_pool",
                        "snat": {
                          "use": "/icni/Shared/ingress_snatpool"
                        }
                    },
                    "icni_app_pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                } 
        }
    }
    }

**Comment by mdditt2000** [comment]
CONTCNTR-1693 - Internal Jira. Completed the regression. Resolved in CIS 2.0 coming next week.

**Comment by mdditt2000** [comment]
Closing Issue.
