### ISSUE TITLE
Is there a way I can enable route advertisement?

### ISSUE THREAD

**Issue by chihaiaalex** [F5Networks/k8s-bigip-ctlr#1304]
Hi,
I'm using the F5 K8S operator to automatically provision virtual servers in the BigIP System.

Is there a way I can enable route advertisement on a virtual address?
My configuration is the following:

{

    "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "istio-ingressgateway",
          "healthMonitors": [
          {
            "protocol": "tcp",
            "interval": 5,
            "timeout": 16
          }
         ]
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "172.27.209.134"
          },
          "partition": "test",
          "balance": "ratio-member",
          "mode": "tcp"
        }
      }
    }

**Comment by mdditt2000** [comment]
@chihaiaalex would be possible to AS3 using a user-defined configmap. A user-defined configmap can expose any BIG-IP object using the AS3 API. 

Advertising a route for a Service Address
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#advertising-a-route-for-a-service-address

How do use user-defined configmap with AS3 API. 
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html

Let me know if you have any questions or concerns.

**Comment by diaconud007** [comment]
@mdditt2000  we currently don't have the AS3 extension configured in our F5BigIP instance, but will have it 'till next week.

we will come back with feedback after testing.
Thank you,

DD on behalf of @chihaiaalex

**Comment by mdditt2000** [comment]
awesome @chihaiaalex @diaconud007 let me know if you need additional help.

**Comment by mdditt2000** [comment]
Closing this issue out
