### ISSUE TITLE
Support source IP - Real client IP

### ISSUE THREAD

**Issue by YacovNagose** [F5Networks/k8s-bigip-ctlr#1306]
Description

We need to create VIPs on the F5 without Automap or SNAT, We have services that required to see the real client IP.
The only option with the bigip ctrl is AutomMap.

Actual Problem

We can't create VIP's that doesn't modify the Real client IP.

Solution Proposed
Add an argument on the Config Map to configure the Source Address Translation values on the F5 to the available options: None/AutoMap/SNAT.

Controller Version
1.8.1

BIG-IP Version
BIG-IP 13.1.1.5 Build 0.0.4 Point Release 5

We tried the AS3 but it doesn't fit our environment.
We build automation around this solution on deployments, we need you to support Source IP args in the Config map.

**Comment by mdditt2000** [comment]
afternoon @YacovNagose Sounds like you are using the legacy API called CCCL. Please note in CIS 2.0 shipping this week CCCL is not longer default. You will need to apply "agent=cccl" in the deployment manifest. We are moving to use AS3 API by default. Also not that CCCL wont receive any new features in CIS.

You have a few options

1) user-defined AS3 configmap where you can apply the 

```
"snat": "none",
```
2) Use CRD in CIS 2.0. Using a CRD were you can configure no snat
3) Use a ingress with AS3 override. Apply the same as item number 1.

**Comment by YacovNagose** [comment]
Hi Mark,

Thank you for the quick response.
Can you please share with me the document of the CIS 2.0? I would like to
read about it.

Best Regards,
Yacov.

**Comment by mdditt2000** [comment]
@YacovNagose here are the CIS 2.0 release-notes https://github.com/F5Networks/k8s-bigip-ctlr/blob/2.0-stable/docs/RELEASE-NOTES.rst
The new documentation will be published in the next few days. However during the meantime you can read about use-define configmap https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html

**Comment by YacovNagose** [comment]
Thank you! I will check it out.

**Comment by mdditt2000** [comment]
Closing issue out
