### ISSUE TITLE
[AS3 Agent] Remove additional <partition_name>_AS3 partition

### ISSUE THREAD

**Issue by nmenant** [F5Networks/k8s-bigip-ctlr#1312]
#### Title
Remove additional <partition_name>_AS3 partition

#### Description
With CIS 1.X and CCL, you specify a partition in the controller config and it will use this partition on the targeted BIG-IP. 

With CIS1.X and AS3 Agent, you have a new behavior where CIS will use the defined partition AND create another partition called <partition_name>_AS3. The first partition is used for FDB entries and the other partition is used for AS3 config

#### Actual Problem
Using two different partitions is confusing and there is no real value on relying on two different partitions for this

#### Solution Proposed
Go back to the previous behavior and use a single partition for AS3 config and FDB entries

**Comment by mdditt2000** [comment]
Internal Jira for PM tracking CONTCNTR-1678. Change is scheduled for CIS 2.1 as stated in the release-notes https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/RELEASE-NOTES.rst

**Comment by mdditt2000** [comment]
Internal Jira CONTCNTR-1678 for PM tracking

**Comment by mdditt2000** [comment]
Problem: When CIS configured as AS3 Agent, CIS will use the defined partition AND create another partition called <partition_name>_AS3. The first partition is used for FDB entries and the other partition is used for AS3 config, Using two different partitions is confusing and there is no real value on relying on two different partitions.

Solution: CIS should only support a single partition and <partition_name>_AS3 must be removed.

You can view, comment on, or merge this pull request online at:

  https://github.com/F5Networks/k8s-bigip-ctlr/pull/1324

Commit Summary

Single partion for CIS when configured in AS3 agent
File Changes

M cmd/k8s-bigip-ctlr/main.go (17)
Patch Links:

https://github.com/F5Networks/k8s-bigip-ctlr/pull/1324.patch
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1324.diff

**Comment by trinaths** [comment]
Fix submitted. Closing this FR.
