### ISSUE TITLE
Support for X-Forwarded-Proto Header

### ISSUE THREAD

**Issue by strantalis** [F5Networks/k8s-bigip-ctlr#1316]
#### Title
Support for X-Forwarded-Proto Header

#### Description
Looking for the ability to support adding the X-Forwarded-Proto header on Openshift routes that are using edge termination for tls or tls in general. 

#### Actual Problem
We ran into a issue where an application was creating Openshift routes with edge termination and because it didn’t receive the X-Forwarded-Proto https header it ended up in a endless redirect loop as the service was returning http while the Virtual Server was redirecting the request back to https.

#### Solution Proposed
Have the Big-Ip insert the the X-Forwarded-Proto header for tls routes by default.

**Comment by mdditt2000** [comment]
@strantalis this can do this very easily. Here are the steps to get this accomplished:

1) continue to create your OpenShift routes. 
2) Add a AS3 override configmap to add the netopps configuration to the route. This will simply reference a HTTP custom profile where you enable your XFF header etc. 

Here is the AS3 override configmap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-route-vs-override
  namespace: default
data:
  template: |
    {
        "declaration": {
            "https_ose_vserver": {
                "Shared": {
                    "ingress_10_192_75_108_80": {
                        "profileHTTP": {
                            "bigip": "/Common/http-custom"
                        }
                    }
                }
            }
        }
    }
```
Here is a bigger example with alot more items you can add to the override like irule, logging, snat etc https://github.com/mdditt2000/openshift-3-11/blob/master/examples/as3-override/example.json

Please add the AS3 override statement to your CIS deployment
```
"--override-as3-declaration=namesoace/f5-route-vs-override"
```
Let me know if you have any questions. Mark

**Comment by mdditt2000** [comment]
@strantalis quick correct. If you are going to use CIS 2.0 with the AS3 override please add the labels as shown below. 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
labels:
      f5type: virtual-server
      overrideAS3: "true"
data:
  template: |
    {
        "declaration": {
            "https_ose_vserver": {
                "Shared": {
                    "ingress_10_192_75_108_80": {
                        "profileHTTP": {
                            "bigip": "/Common/http-custom"
                        }
                    }
                }
            }
        }
    }
```

**Comment by strantalis** [comment]
I tried the override configmap but it doesn't seem to be working. 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: kube-system
  labels:
    f5type: virtual-server
    overrideAS3: 'true'
data:
  template: |
    {
        "declaration": {
            "example_AS3": {
                "Shared": {
                    "https_ose_vserver": {
                        "profileHTTP": {
                            "bigip": "/Common/openshift_https"
                        }
                    }
                }
            }
        }
    }
```
```- '--override-as3-declaration=kube-system/f5-as3-declaration'```

**Comment by mdditt2000** [comment]
@strantalis are you using CIS 1.14 or CIS 2.0? In CIS 1.14 after creating the configmap "AS3 override the controller will need to be re-started". This is not required if you are using CIS 2.0.

**Comment by strantalis** [comment]
I was trying both. It finally worked but not really sure what got it to update. I updated virtualPort and then removed it to see if that would update and it did but then I noticed the http profile was updated as well. 

But its working now 👍 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: kube-system
  labels:
    f5type: virtual-server
    overrideAS3: 'true'
data:
  template: |
    {
        "declaration": {
            "gp_1_poc_cis_AS3": {
                "Shared": {
                    "https_ose_vserver": {
                        "profileHTTP": {
                            "bigip": "/Common/openshift_https"
                        },
                        "virtualPort": 8443
                    }
                }
            }
        }
    }
```

**Comment by mdditt2000** [comment]
@strantalis with CIS 2.0 it should take effect right away. 

- Create the AS3 override configmap
- Create the route. You should notice the change XFF in the BIG-IP UI. 

Any other system level configuration you want to apply?

**Comment by mdditt2000** [comment]
@strantalis question as to why you are using namespace kube-system? Is that your default namespace.

**Comment by strantalis** [comment]
No reason just followed these [docs](https://clouddocs.f5.com/containers/v2/openshift/kctlr-openshift-bigip-ha.html) originally.

**Comment by mdditt2000** [comment]
@strantalis can i close this issue out?

**Comment by walterk82** [comment]
This issue was opened dealing with X-Forwarded-Proto (XFP) but then it transition to X-Forwarded-For (XFF).  @strantalis What header were you looking to have addressed?
