### ISSUE TITLE
Support for shared nodes for CIS deployment

### ISSUE THREAD

**Issue by rlombardi12** [F5Networks/k8s-bigip-ctlr#1319]
#### Title
Add Support for shared nodes

#### Description
Customer wants to use different controllers per different namespaces and partitions. While trying to use this scenario CIS logs error saying there is a conflict with IP address already in use in another partition. This is blocking the customer from achieving this kind of segregation.

#### Actual Problem
Not possible to use different controllers per different namespaces and partition when the backend is the same. Need controller option for sharedNodes=true so the same member could be shared by different partitions.

#### Solution Proposed
Need controller option for sharedNodes=true
[cis-log-sharednodes.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/4685515/cis-log-sharednodes.txt)

**Comment by mdditt2000** [comment]
@rlombardi12 thanks for opening this issue. @nandakishorepeddi is looking into when CIS applies/does not apply SharedNodes to the pool.

**Comment by mdditt2000** [comment]
@nandakishorepeddi confirmed sharedNodes is not supported currently by our CIS. Internal PM tracking Jira CONTCNTR-1850. Update Github after next weeks sprint planning.

**Comment by mdditt2000** [comment]
Currently no milestone.

**Comment by mdditt2000** [comment]
Adding support for SharedNodes in CRDs. SharedNodes is required if you re-using or sharing nodes across clusters. CIS creates the nodes in common

**Comment by mdditt2000** [comment]
@rlombardi12 feature coming in CIS 2.2

**Comment by mdditt2000** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1534 Resolved in CIS 2.2
