### ISSUE TITLE
Removing ingress with AS3 configmap override break CIS

### ISSUE THREAD

**Issue by rlombardi12** [F5Networks/k8s-bigip-ctlr#1320]
#### Title
Removing ingress with AS3 configmap override break CIS

#### Description
If AS3 Configmap override cannot find the ingress it should ignore

#### Actual Problem
Today if we remove an ingress that is being referenced by AS3 Configmap override, it simply break the controller. Every update done after this is not reflected in BigIP.

#### Solution Proposed
If AS3 Configmap override cannot find the ingress it should ignore it and do nothing.

#### Alternatives
We need to take care and first delete any reference in AS3 Configmap override to this ingress and after that delete de ingress.
[logcontroller-apos-remocao.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/4685597/logcontroller-apos-remocao.txt)

**Comment by mdditt2000** [comment]
Closing this out as this issue requires no development effort at this time. AS3 Configmap needs to be modified before the Ingress is removed or modified.
