### ISSUE TITLE
Self-signed BIG-IP certificate resulted in as3 agent internal error

### ISSUE THREAD

**Issue by penghon** [F5Networks/k8s-bigip-ctlr#1327]
#### Setup Details
 CIS Version : 2.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.0.3
 AS3 Version: 3.19.1      
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version: 1.18.2       
 Pool Mode: Cluster      
 Additional Setup details: bare metal / flannel 

#### Description  
BIG-IP has self signed certificate. Unable to get the controller pod up and running. 
#### Steps To Reproduce
Just deploy CIS version 2.0 and see the controller pod fails. Ensure that BIG-IP device certificate is self-signed. 

#### Expected Result 
Controller pod up and running regardless of whether BIG-IP device certificate is self-signed or not.

#### Actual Result  
Logs are as follows:
[root@km143 ~]# kn logs k8s-bigip-ctlr-5cb6f6f7b9-8lqgd
2020/05/29 08:20:48 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.0.0, BuildInfo: cloud-user-efcab9e-20200522033624
2020/05/29 08:20:48 [INFO] ConfigWriter started: 0xc00031e570
2020/05/29 08:20:48 [INFO] Started config driver sub-process at pid: 17
2020/05/29 08:20:48 [INFO] [INIT] Creating Agent for as3
2020/05/29 08:20:48 [INFO] [AS3] Initializing AS3 Agent
2020/05/29 08:20:48 [ERROR] [AS3] REST call error: Get https://172.28.22.148/mgmt/shared/appsvcs/info: x509: certificate signed by unknown authority
2020/05/29 08:20:48 [ERROR] [AS3] Internal Error
2020/05/29 08:20:48 [CRITICAL] [INIT] Failed to initialize as3 agent, Internal Error

[root@km143 ~]# kn get pods
NAME                                       READY   STATUS             RESTARTS   AGE
<snip>
k8s-bigip-ctlr-5cb6f6f7b9-8lqgd            0/1     CrashLoopBackOff   1          8s
<snip>

In an act of desperation, I downgraded to CIS to version 1.14:
[root@km143 ~]# kn logs k8s-bigip-ctlr-669559c7d7-ph2bh
2020/05/29 08:52:04 [INFO] Starting: Version: 1.14.0, BuildInfo: n2285-661543171
2020/05/29 08:52:04 [INFO] ConfigWriter started: 0xc0003401b0
2020/05/29 08:52:04 [INFO] Started config driver sub-process at pid: 13
2020/05/29 08:52:06 [INFO] [2020-05-29 08:52:06,181 __main__ INFO] entering inotify loop to watch /tmp/k8s-bigip-ctlr.config589230808/config.json
2020/05/29 08:52:07 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2020/05/29 08:52:07 [INFO] NodePoller (0xc0009bf680) registering new listener: 0x11c3400
2020/05/29 08:52:07 [INFO] NodePoller (0xc0009bf680) registering new listener: 0x11c3470
2020/05/29 08:52:07 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:52:07 [INFO] ProcessNodeUpdate: Change in Node state detected
2020/05/29 08:52:07 [INFO] NodePoller started: (0xc0009bf680)
2020/05/29 08:52:07 [INFO] Watching Ingress resources.
2020/05/29 08:52:07 [INFO] Watching ConfigMap resources.
2020/05/29 08:52:07 [INFO] Handling ConfigMap resource events.
2020/05/29 08:52:07 [INFO] Handling Ingress resource events.
2020/05/29 08:52:07 [INFO] Registered BigIP Metrics
2020/05/29 08:52:10 [INFO] [2020-05-29 08:52:10,996 f5_cccl.resource.resource INFO] Updating ApiFDBTunnel: /Common/flannel_ingress
2020/05/29 08:52:38 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:53:08 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:53:38 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:54:08 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:54:38 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:55:08 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:55:38 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:56:08 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:56:38 [ERROR] [AS3] REST call error: Post https://172.28.22.148/mgmt/shared/appsvcs/declare/: x509: certificate signed by unknown authority
2020/05/29 08:57:08 [ERROR] [AS3] REST call error: Post 

[root@km143 ~]# kn get pods
NAME                                       READY   STATUS    RESTARTS   AGE
<snip>
k8s-bigip-ctlr-669559c7d7-ph2bh            1/1     Running   0          10m
<snip>

#### Observations (if any)

**Comment by mdditt2000** [comment]
@penghon if you are using a self-signed cert on BIG-IP you need to add a argument to CIS. Please add **"--insecure=true",** as shown in the example below.

```
args: [
    "--bigip-username=$(BIGIP_USERNAME)",
    "--bigip-password=$(BIGIP_PASSWORD)",
    "--bigip-url=192.168.200.98",
    "--bigip-partition=AS3",
    "--namespace=default",
    "--pool-member-type=cluster",
    "--flannel-name=fl-vxlan",
    "--log-level=INFO",
    "--insecure=true",
```

More information from my repo. 

https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-14/howto.md#installing-as3-and-handling-ssl-certificate-verification

**Comment by mdditt2000** [comment]
Created Jira CONTCNTR-1849 to add [Doc] Provide a page to list all CIS Config parameters

**Comment by penghon** [comment]
Thank you so much, I couldnt find the insecure option anywhere and the controller is now happy:

  Normal  Scheduled  <unknown>  default-scheduler       Successfully assigned kube-system/k8s-bigip-ctlr-9568877dc-lvv4k to kw71.ph.local
  Normal  Pulling    2m49s      kubelet, kw71.ph.local  Pulling image "f5networks/k8s-bigip-ctlr:latest"
  Normal  Pulled     2m46s      kubelet, kw71.ph.local  Successfully pulled image "f5networks/k8s-bigip-ctlr:latest"
  Normal  Created    2m46s      kubelet, kw71.ph.local  Created container k8s-bigip-ctlr
  Normal  Started    2m46s      kubelet, kw71.ph.local  Started container k8s-bigip-ctlr
