### ISSUE TITLE
Compatiblity with bigip 12.1.5 ?

### ISSUE THREAD

**Issue by somejfn** [F5Networks/k8s-bigip-ctlr#1328]
#### Setup Details
 CIS Version : 2.X   
 Build: /k8s-bigip-ctlr:1.14.0
 BIGIP Version: Big IP 12.1.5   
 AS3 Version: NONE INSTALLED    
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster
 Additional Setup details: K8s 1.14.4

#### Description  

In CCCL mode,  this configmap produces the expected results on an LVM VE 15.1.0.3 but trying the same on our 12.1.5 bigip produces 400 API errors.

#### Steps To Reproduce
1) config map:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress.vs
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.2.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "a1-nginx-ingress",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /nginx-health HTTP/1.0 \n",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "10.x.x.x"
          },
          "partition": "K8S_testcluster",
          "balance": "least-connections-member",
          "mode": "http"
        }
      }
    }
```

#### Expected Result 

No errors in CIS controller logs and pool/monitor created

#### Actual Result  

vserver created but not operational erroring on pool/monitor creation

#### Diagnostic Information
```
2020/05/29 20:40:13 [INFO] [2020-05-29 20:40:13,132 f5_cccl.resource.resource INFO] Creating ApiHTTPMonitor: /K8S_testcluster/cfgmap_core-services_a1-nginx-ingress.vs_a1-nginx-ingress_0_http
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,147 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiHTTPMonitor) /K8S_testcluster/cfgmap_core-services_a1-nginx-ingress.vs_a1-nginx-ingress_0_http.
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,147 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.65.17.151:443/mgmt/tm/ltm/monitor/http/
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,147 f5_cccl.service.manager ERROR] Resource /K8S_testcluster/cfgmap_core-services_a1-nginx-ingress.vs_a1-nginx-ingress_0_http creation error, requeuing task...
2020/05/29 20:40:13 [INFO] Text: '{"code":400,"message":"\\"http\\" unexpected argument","errorStack":[],"apiError":26214401}'
2020/05/29 20:40:13 [INFO] [2020-05-29 20:40:13,147 f5_cccl.resource.resource INFO] Creating ApiPool: /K8S_testcluster/cfgmap_core-services_a1-nginx-ingress.vs_a1-nginx-ingress
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,184 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiPool) /K8S_testcluster/cfgmap_core-services_a1-nginx-ingress.vs_a1-nginx-ingress.
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,184 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.65.17.151:443/mgmt/tm/ltm/pool/
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,184 f5_cccl.service.manager ERROR] Resource /K8S_testcluster/cfgmap_core-services_a1-nginx-ingress.vs_a1-nginx-ingress creation error, requeuing task...
2020/05/29 20:40:13 [INFO] Text: '{"code":400,"message":"\\"pool\\" unexpected argument","errorStack":[],"apiError":26214401}'
2020/05/29 20:40:13 [INFO] [2020-05-29 20:40:13,184 f5_cccl.resource.resource INFO] Creating ApiVirtualServer: /K8S_testcluster/core-services_a1-nginx-ingress.vs
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,222 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiVirtualServer) /K8S_testcluster/core-services_a1-nginx-ingress.vs.
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,222 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.65.17.151:443/mgmt/tm/ltm/virtual/
2020/05/29 20:40:13 [ERROR] [2020-05-29 20:40:13,222 f5_cccl.service.manager ERROR] Resource /K8S_testcluster/core-services_a1-nginx-ingress.vs creation error, requeuing task...
2020/05/29 20:40:13 [INFO] Text: '{"code":400,"message":"\\"virtual\\" unexpected argument","errorStack":[],"apiError":26214401}'
2020/05/29 20:40:20 [ERROR] [2020-05-29 20:40:20,371 __main__ ERROR] Error applying config, will try again in 128 seconds

```

**Comment by somejfn** [comment]
Also Im curious why the controller logs:  [ERROR] [AS3] Big-IP Responded with code: 401
with the controller started with agent=cccl

**Comment by mdditt2000** [comment]
@somejfn thanks for opening this issue. cisbot assigned this @vklohiya. 

From a PM perspective is there a reason why you want to stay on CCCL and not move to AS3?

**Comment by somejfn** [comment]
Hi Mark,  

The team managing the F5 had serious concerns about the level of privileges required for CIS to work in AS3 mode.   We defaulted to CCCL because of that using an admin created partition and only operator level access for CIS in that partition.    AS3 would be welcomed is non-admin privileges were possible for the CIS API user.

**Comment by mdditt2000** [comment]
@somejfn As PM for BIG-IP on the automation side can we chat with the team managing the the F5. CIS requires Admin creds to interact with BIG-IP. The reason for admin creds is due to API call that need to communicate with the user-interface. Even CCCL requires admin creds after release CC 1.7 when the user-agent was added. Those 401 codes errors are due changes in the API. are The advantage of AS3 is the schema is contracted and therefore cannot be changed unless adding additional features. So regardless of the version of BIG-IP AS3 will work.

**Comment by mdditt2000** [comment]
@vklohiya can you review the logs and determine if you believe the APIs have changed on BIG-IP in 15.1.0.3 using the above CCCL configmap. Thanks Mark

**Comment by somejfn** [comment]
Also I want to re-iterate I did not need admin level with CCCL on 15.1.0.3 :

![image](https://user-images.githubusercontent.com/15197608/83412227-bb196d00-a3e7-11ea-8f09-c17ee7cf7d49.png)

**Comment by mdditt2000** [comment]
@somejfn not sure i am clear on the issue you experiencing. You aren't getting any errors 400 Unexpected Error: Bad Request for uri: https://10.65.17.151:443/mgmt/tm/ltm/pool/ using LVM VE 15.1.0.3? Only get the error using 12.1.5 ?

**Comment by somejfn** [comment]
Hi @mdditt2000 ,

The 400s errors goes away when using a CIS user with resource admin privileges.  I can't explain how I got that to work with operator level in 15.1.0.3 although I did started with admin privileges on my first try then lowered to operator afterward... 

We'll discuss internally if that is acceptable to run CIS as resource admin or find a different solution.   thank you !

**Comment by mdditt2000** [comment]
Thanks @somejfn That would make sense. CIS is forced to use ADMIN creds. Closing issue out.
