### ISSUE TITLE
F5 Role  for k8s-bigip-ctrl 

### ISSUE THREAD

**Issue by tomaszmzyk** [F5Networks/k8s-bigip-ctlr#1335]
Hi
Build: f5networks/k8s-bigip-ctlr:2.0.0
BIGIP Version: Big IP 15.1
AS3 Version: 3.19
Agent Mode: AS3
Orchestration: Openshift
Orchestration Version:3.11

Hi
On F5 only user with Administrator role have access and k8s-bigip-ctrl works fine.
When user is Resource Administrator pod from controller have errors:

2020/06/03 12:41:34 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.0.0, BuildInfo: cloud-user-efcab9e-20200522033624
2020/06/03 12:41:34 [INFO] ConfigWriter started: 0xc0003a5410
2020/06/03 12:41:34 [DEBUG] [CCCL] ConfigWriter (0xc0003a5410) writing section name global
2020/06/03 12:41:34 [DEBUG] [CCCL] ConfigWriter (0xc0003a5410) successfully wrote section (global)
2020/06/03 12:41:34 [DEBUG] [CCCL] ConfigWriter (0xc0003a5410) writing section name bigip
2020/06/03 12:41:34 [DEBUG] [CCCL] ConfigWriter (0xc0003a5410) successfully wrote section (bigip)
2020/06/03 12:41:34 [INFO] Started config driver sub-process at pid: 18
2020/06/03 12:41:34 [INFO] [INIT] Creating Agent for as3
2020/06/03 12:41:34 [DEBUG] [INIT] Invalid trusted-certs-cfgmap option provided.
2020/06/03 12:41:34 [DEBUG] [CORE] Agent Response Worker started and blocked on channel  0xc0001be060
2020/06/03 12:41:34 [INFO] [AS3] Initializing AS3 Agent
2020/06/03 12:41:34 [DEBUG] [AS3] No certs appended, using only system certs
2020/06/03 12:41:34 [DEBUG] [AS3] Validating AS3 schema with  as3-schema-3.18.0-4-cis.json
2020/06/03 12:41:34 [DEBUG] [AS3] posting GET BIGIP AS3 Version request on https://<f5.mgmt.info/mgmt/shared/appsvcs/info
2020/06/03 12:41:34 [ERROR] [AS3] Error response from BIGIP with status code 401
2020/06/03 12:41:34 [CRITICAL] [INIT] Failed to initialize as3 agent, Error response from BIGIP with status code 401

From documentation should work not only on Administrator Role.
Could you please check
Regards
Tomasz

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by trinaths** [comment]
@tomaszmzyk Can you share where in documentation it's mentioned ` From documentation should work not only on Administrator Role.`. Since CIS 2.0 starts with AS3 as default agent, you need AS3 3.18 and above for the same installed in BIG-IP.

**Comment by tomaszmzyk** [comment]
Hi

I have installed the latest version of AS3 3.19.
When I looked to documentation today indeed there is only Administrator role :), in earlier version have been Resource Administrator too.

Regards

P.S. We can close issue.

**Comment by tomaszmzyk** [comment]
Hi
Now I'm reading following documentation:
https://clouddocs.f5.com/containers/latest/userguide/openshift/

And there is wrote:
OCP 3.11 - one master and two worker nodes
CIS 2.0
AS3: 3.18+
BIG-IP 14.1.2.2
You will need to have the role of Administrator or Resource Administrator on the BIG-IP system.

As you see there is a information that Resource Administrator can be :)
Regards

**Comment by trinaths** [comment]
@tomaszmzyk - Thanks for sharing the info. With Admin role is the issue resolved ?

**Comment by mdditt2000** [comment]
Documentation bug. Need to remove **or Resource Administrator**

![image](https://user-images.githubusercontent.com/12733938/83897425-71dc5c80-a70a-11ea-9221-3227e304a9c1.png)

**Comment by mdditt2000** [comment]
Created internal Jira CONTCNTR-1876 for PM tracking. Assigned to technical writer to remove the "Resource Administrator"

**Comment by tomaszmzyk** [comment]
> @tomaszmzyk - Thanks for sharing the info. With Admin role is the issue resolved ?

Hi
Yes with Administrator role works fine.
Regards

**Comment by mdditt2000** [comment]
Issue and documentation resolved. Thanks @vtrippel
