### ISSUE TITLE
F5 document look like a shit!

### ISSUE THREAD

**Issue by sober-wang** [F5Networks/k8s-bigip-ctlr#1336]
#### Setup Details
 CIS Version : 2.0.0      
 Build: f5networks/k8s-bigip-ctlr:2.0.0     
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:  1.16     
 Pool Mode: Cluster/Nodeport      

#### Description  
  
![image](https://user-images.githubusercontent.com/35804630/83705164-c0c0be00-a646-11ea-8726-4ab55f5941ba.png)

Fuck the F5 as3 doc. 
k8s configmaps `metadata.name` can't used fuckF5 . the doc author is stupid!

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by snatra** [comment]
Hi Sober,

This is an example depicted in the callflow. The highlighted cfgMap name  "myCfgMap" should be changed by the user accordingly.

refer to the previous example user-defined AS3 ConfigMap.

**Comment by mdditt2000** [comment]
Sorry but these comments aren't helpful. We are making active improvements to CIS documentation. Please advise how we can better the documentation. But the use of bad language wont be tolerated. Closing issue out, reported user and blocked user.
