### ISSUE TITLE
Enable high-speed logging for F5-Bigip LTM VS created for Ingress

### ISSUE THREAD

**Issue by holymam** [F5Networks/k8s-bigip-ctlr#1342]
#### Title
Enable high-speed logging for F5-Bigip LTM VS created for Ingress

#### Description
F5-bigip LTM VS high speed logging enabled is not available on the official website

#### Actual Problem
Enable high-speed logging for F5-Bigip LTM VS created for Ingress

#### Solution Proposed
Define vs high-speed logging in Ingress by means of key-value pairs

#### Alternatives
none

#### Additional context
Enable high-speed logging for F5-Bigip LTM VS created for Ingress
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        name: name-virtual-host-ingress
      spec:
        rules:
        - host: foo.bar.com
          http:
            paths:
            - backend:
                serviceName: service1
                servicePort: 80
        - host: bar.foo.com
          http:
            paths:
            - backend:
                serviceName: service2
                servicePort: 80

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Good morning @holymam. There are multiple ways to accomplish this. What high-speed logging endpoint or consumer are you logging to? Also how do you plan to enable HSL on big-ip?

**Comment by f5minions** [comment]
One of my customers also wants to use "traffic logging" with cis ingress virtual server. I found the below link and we can support traffic policy using AS3 but there are no ingress annotations yet. 

Do you have any recommend a way to support these customer's requirements without AS3?

**Comment by mdditt2000** [comment]
PleaseF5 telemetry streaming to enable traffic logging. profileTrafficLog can be enabled via AS3 override configmap

```
"profileTrafficLog": {
     "use": "/Common/Shared/telemetry_traffic_log_profile"
},
```
Please see the following example https://github.com/mdditt2000/telemetry-streaming/blob/master/sumo-logic/sumo-logic-as3.json

You can also enable profileTrafficLog via TMSH

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html#configuretmsh

**Comment by mdditt2000** [comment]
This issue can be closed out.
