### ISSUE TITLE
Redirect Support on Openshift Routes Passthrough/Re-Encrypt 

### ISSUE THREAD

**Issue by strantalis** [F5Networks/k8s-bigip-ctlr#1343]
#### Title
Redirect Support on Openshift Routes Passthrough/Re-Encrypt 

#### Description
Looking for additional support of ```insecureEdgeTerminationPolicy: Redirect``` on Openshift passthrough and re-encrypt routes.

#### Actual Problem
It seems when setting ```insecureEdgeTerminationPolicy``` to Redirect on passthrough or re-encrypt routes the f5 doesn't redirect initial requests on http to https. 

[Supported Openshift Route Features](https://clouddocs.f5.com/containers/v2/openshift/kctlr-use-as3-backend.html#supported-openshift-route-features)

##### Current Result
```
➜ curl http://registry.example.com -v
* Rebuilt URL to: http://registry.example.com/
*   Trying X.X.X.X...
* TCP_NODELAY set
* Connected to registry.example.com (X.X.X.X) port 80 (#0)
> GET / HTTP/1.1
> Host: registry.example.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

##### Expected redirect result
```
➜ curl http://registry.example.com -v
* Rebuilt URL to: http://registry.example.com/
*   Trying X.X.X.X...
* TCP_NODELAY set
* Connected to registry.example.com (X.X.X.X) port 80 (#0)
> GET / HTTP/1.1
> Host: registry.example.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Moved Temporarily
< Location: https://registry.example.com/
< Server: BigIP
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
< Content-Length: 0
<
* Connection #0 to host registry.example.com left intact
```

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
After @strantalis Redirect only works with TLS Edge termination. 

Without having to write/add additional code to CIS you achieve a redirect "redirect80": true for passthrough or re-encrypt routes with using the override feature

CIS will merge the JSON with "redirect80": true, to the route and send to BIG-IP. The prerequisite are AS3 - https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-as3-override.html

```
{
    "declaration": {
        "your-tenant_AS3": {
            "Shared": {
                "https_ose_vserver": {
                    "redirect80": true
                }
            }
        }
    }
}
```
https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/github-sr-issues/%231343/as3-override.yaml

**Comment by mdditt2000** [comment]
@strantalis discuss with the CIS team

**Comment by mdditt2000** [comment]
Review this Github this week when new OCP blueprint is complete.

**Comment by mdditt2000** [comment]
Closing issue from 2020. Redirect is working on Routes
