### ISSUE TITLE
Add support to CRD for adding monitors

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/k8s-bigip-ctlr#1345]
#### Title
Add support to CRD for adding monitors

#### Description
I know CRD's are early access, but one missing feature is definitely monitors.

#### Actual Problem
TCP and HTTP would be critical

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@thomsonjames thank you for opening this.

**Comment by mdditt2000** [comment]
No milestone

**Comment by mdditt2000** [comment]
Merged https://github.com/F5Networks/k8s-bigip-ctlr/pull/1369

**Comment by mdditt2000** [comment]
Status: | Review Done
Done

Jira is closed. HTTP/HTTPS health monitors added in CIS 2.1 released in a few weeks. Closing this issue
