### ISSUE TITLE
bigip-username with non Administrator role

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/k8s-bigip-ctlr#1346]
#### Title
CIS with bigip-username with non Administrator role

#### Actual Problem
According to the documentation:
For cluster type pool members, the role must be Administrator for the bigip-username
We need to have a specific CIS only be able to configure certain partition. 
With the Administrator role, CIS can modify all partition
#### Solution Proposed
CIS with cluster type for pool, a bigip-username role to be manager

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@prabhatkarki role must be Administrator for the bigip-username. This is requirement coming from both AS3 and BIG-IP. Unfortunately this wont be changes on BIG-IP.

**Comment by prabhatkarki** [comment]
@mdditt2000 Thanks!

**Comment by baurmatt** [comment]
Hey @mdditt2000, is your answer still valid by now? :) Asking because I've just stumble over the iControl Rest API changes in 13.1.x that allow non-administrator users access.
