### ISSUE TITLE
--namespace not work as expect

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1348]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  
`--namespace` be used in namespace isolation, which can used to define kubernetes namespaces to watch. Also from document [1], 

**Kubernetes namespace(s) to watch** 

* may be a comma-separated list
* watches all namespaces by default
~~~

But it never work, eg the following config

~~~
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=197.14.0.9",
            "--insecure=true",
            "--bigip-partition=k8s",
            "--pool-member-type=cluster",
            "--namespace=test01,test02,test03,test04,test05",
            "--vs-snat-pool-name=SNAT_Pool_MP",
            ]
~~~

The above args setting doesn't work, note that `test0*` are namespace in k8s, the controller doesn't watch any of the configured namespace. 

[1] https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.11/

#### Steps To Reproduce
1)
2)
3)

#### Expected Result 


#### Actual Result  


#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by agupta49** [comment]
@kylinsoong The correct way to provide multiple namespaces arg is:
~~~
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=197.14.0.9",
            "--insecure=true",
            "--bigip-partition=k8s",
            "--pool-member-type=cluster",
            "--namespace=test01,
            "--namespace=test02,
            "--namespace=test03,
            "--vs-snat-pool-name=SNAT_Pool_MP",
            ]
~~~
Please use this way.

**Comment by mdditt2000** [comment]
Escalation SR 1-6382539511
Internal PM Jira filed for Sprint 43 - CONTCNTR-1948

https://github.com/F5Networks/k8s-bigip-ctlr/issues/1311 

Allow for CIS 2.0 to support multiple user-defined configmaps like 1.14. This will resolved this issue.

**Comment by mdditt2000** [comment]
Related. https://github.com/F5Networks/k8s-bigip-ctlr/issues/1311

**Comment by mdditt2000** [comment]
@prabhatkarki @kylinsoong CIS 2.1 will resolve this issue. Allow for CIS 2.x to support multiple configmaps

**Comment by mdditt2000** [comment]
Multiple namespace support:

- cis supports multiple namespace 

To specify multiple namespace, use multiple --namespace flags

eg:

--namespace=default,
--namespace=foo

Scenario: configmap in namepace1  and service in namespace2 wont work!! We have no plans to support this! 

Behavior on CIS 2.x: CIS processes service endpoint if they are in same namespace as ConfigMap

**Note: ConfigMap and service should be in same namespace**
**Note: Same behavior is also verified in CIS 1.14**

--- Closing issue out ---

**Comment by rgarcia89** [comment]
@mdditt2000 
> Scenario: configmap in namepace1 and service in namespace2 wont work!! We have no plans to support this!

This is from my perspective a very bad decision in matter of security.
With 1.14 it was possible to deploy all AS3 related configmaps into a specific namespace where the service, for which they were build did not need to be placed. This was nice because only a limited amount of users were able to modify these files.

In my case for example I don't want users that are not part of the network team to be able to make changes to AS3 files or even worse to deploy there own AS3 files that will be applied to the F5, as the ctrl listens to there namespace.

As configmaps are used by a lot of teams on my clusters, there is also no possibility to get around this, by removing the access to them in general...

**Comment by mdditt2000** [comment]
@rgarcia89 i think there is some confusion here. In CIS 1.14 CIS seems to be doing service discovery without checking the namespace. 

For example i have a configmap in namespace default

https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.2/github/1348/as3-configmap/default/f5-as3-configmap.yaml

And a deployment and service in namespace n1

https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.2/github/1348/pod-deployment/f5-hello-world-service-n1.yaml

In CIS 1.14 service discovery will detect the pool members. That broken if you ask me. In CIS 2.0 the pool members will not be detected. This prevents misconfigurations in configmaps from detecting the incorrect services. 

Questions: Do you want CIS to ignore the namespace in the configmap and only look for matching labels?

**Comment by mdditt2000** [comment]
Reopening issue as user not happy with ConfigMaps.

**Comment by rgarcia89** [comment]
@mdditt2000 thanks for clarifing the difference between the pool member discovery in CIS 1.14 and CIS 2.0. 
What I do not understand in case of CIS 2.0 is how services are discovered than?

I also was already looking into CRD which would have been fine for me as I can remove access for users to this resources. So there would be no issue with placing them in the same namespace as the service resides. However, there are still to many options missing when it comes to CRD. I for example cannot set the serviceAddress options and also not the allowedVlan. 
Therefore, I have to use AS3 declarations. 

For me it would be totally fine, if CIS would only work by labels when it comes to AS3. I mean I can totally understand about the performance issue. But what options would we have in matter of that? Would it be possible to mention the namespace somewhere in the declaration for which the related configmap is to be used for? In that case CIS would know in which namespace to look for the related labels.

**Comment by rgarcia89** [comment]
@mdditt2000 can you please give me an update on that?
What do you think about my issue?

**Comment by mdditt2000** [comment]
@rgarcia89 afternoon Raul. Sorry for the delay, was out of the office due to ThanksGiving. CIS 2.0 was refactored with improvements in performance etc. CIS 2.2.1 coming this week has more performance improvements. Mostly to CRDs but a few to ConfigMap. One enhancement to ConfigMap is CIS will now detect the correct port configured in the service. Before CIS would pick the first port. 

In CIS 2.0 services discovered takes the namespace into count if specified in the ConfigMap. That namespace needs to map the associated service. 

We can add allowedVlan in the next sprint. CRD is an abstracted AS3 declaration and would be pretty easy to add. We would like you to start using CRDs as its a better solution than ConfigMaps. 

Please can you submit a Github issue for adding "allowedVlan" and any other enhancements needed for CRDs

**Comment by rgarcia89** [comment]
@mdditt2000 I have raised a ticket with what I need to switch from AS3 configmaps to CRD.
Please let me know in case you should have any further questions.

Thanks

**Comment by mdditt2000** [comment]
Completed in CIS 2.5 with configmap hub mode. Review documentation example https://github.com/mdditt2000/k8s-bigip-ctlr/blob/main/user_guides/hubmode/README.md

Closing issue
