### ISSUE TITLE
Endless Warnings About "Overwriting existing entry for backend"

### ISSUE THREAD

**Issue by AMoghrabi** [F5Networks/k8s-bigip-ctlr#1354]
#### Setup Details
CIS Version : 2.0.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 15.1.0.1
AS3 Version: 3.19.1
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.15.11
Pool Mode: NodePort
Additional Setup details: Flannel (host-gw)

#### Description  
Our F5 CIS is continuously overwriting entries on the F5 for no apparent reason. I don't understand what is causing the warning. This is causing sync issues between our active/passive F5 setup because it happens every few seconds. 

Here is a copy of the logs:

```
2020/06/12 20:59:25 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:XXX ServicePort:80 Namespace:ZZZ} and resource ingress_10-xxx-xxx-xxx_443
2020/06/12 20:59:26 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:YYY ServicePort:80 Namespace:ZZZ} and resource ingress_10-xxx-xxx-xxx_443
2020/06/12 20:59:30 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:XXX ServicePort:80 Namespace:ZZZ} and resource ingress_10-xxx-xxx-xxx_443
2020/06/12 20:59:34 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:YYY ServicePort:80 Namespace:ZZZ} and resource ingress_10-xxx-xxx-xxx_443
```

Here is what our CIS deployment looks like:
```
ame:                   bigip-ctlr
Namespace:              XXX
CreationTimestamp:      Fri, 12 Jun 2020 08:17:18 -0700
Labels:                 app=bigip-ctlr

Annotations:            deployment.kubernetes.io/revision: 6
                        fluxcd.io/sync-checksum: a3fbbc7910037692411a03e41b1451784ec03231
Selector:               app=bigip-ctlr
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=bigip-ctlr
  Service Account:  bigip-ctlr
  Containers:
   bigip-ctlr:
    Image:      f5networks/k8s-bigip-ctlr:2.0.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /app/bin/k8s-bigip-ctlr
    Args:
      --credentials-directory=/var/run/secrets/credentials
      --bigip-url=XXXXX
      --pool-member-type=nodeport
      --bigip-partition=$(BIGIP_PARTITION)
      --default-ingress-ip=$(BIGIP_DEFAULT_INGRESS_IP)
      --insecure=true
    Limits:
      cpu:     100m
      memory:  256Mi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment Variables from:
      bigip-ctlr-cluster-config  ConfigMap  Optional: false

      ...
```

#### Steps To Reproduce
1) Unknown.

#### Expected Result 
Fewer rewrites unless something changes, unless I'm misconfiguring or misunderstanding how the controller works.

#### Actual Result  
Endless warnings and rewrites.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by AMoghrabi** [comment]
Actually this seems to be happening every 25 to 30 seconds which I think matches with the poll interval for CIS to check if anything has changed on the Kubernetes side.

But if nothing has changed, why is it overwriting? If something has changed, how can I check what is changing and prevent it? Overwrites every 30 seconds is excessive, right?

**Comment by mdditt2000** [comment]
@nandakishorepeddi is this related to docs | CIS floods "[WARNING] [CORE] Overwriting existing entry for backend {ServiceName:svc-99 ServicePort:443 Namespace:default} and resource ose-vserver" (#408)

**Comment by nandakishorepeddi** [comment]
No I believe Mark, I tried using CIS in Cluster mode when configuring edge routes and the messages are not flooded every 30 seconds in my case, but this issue is reported in NodePort Mode. I will give a try.
@AMoghrabi which type of routes are you using i.e. edge/reencrypt/passthrough etc. If possible could you post your route configuration here to understand the issue further.

**Comment by AMoghrabi** [comment]
Thanks @nandakishorepeddi and Mark. 

@nandakishorepeddi , sorry I'm a new to the F5. Where can I find my route configuration?

**Comment by nandakishorepeddi** [comment]
If you have access to kubectl or oc client, please try the below command:
"oc get routes -n <namespace_where_routes_exist> -oyaml"

**Comment by AMoghrabi** [comment]
Hey @nandakishorepeddi , we aren't using OpenShift so I used `kubectl`. I get an error from the API server because a resource type of `routes` doesn't exist:

```
alim$ kubectl get routes -n cluster-admin -o yaml
error: the server doesn't have a resource type "routes"
```

 Did you mean you'd like me to fetch my ingresses and/or services?

**Comment by nandakishorepeddi** [comment]
Extremely sorry. I thought you were using Openshift. Could you please post the ingress resources which CIS is listening.

**Comment by AMoghrabi** [comment]
Not a problem! Sorry I should have clarified that.

First. here is the warning in the CIS controller that relates to our test-service (named `david-cats`) ingress:

`2020/06/16 17:05:43 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:david-cats ServicePort:80 Namespace:default} and resource ingress_10-230-0-22_443`

Ingress:

```
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"f5","virtual-server.f5.com/balance":"round-robin","virtual-server.f5.com/ip":"controller-default"},"name":"david-cats","namespace":"default"},"spec":{"rules":[{"host":"david-cats.xxxx.net","http":{"paths":[{"backend":{"serviceName":"david-cats","servicePort":80}}]}}],"tls":[{"hosts":["david-cats.xxxx.net"]}]}}
    kubernetes.io/ingress.class: f5
    virtual-server.f5.com/balance: round-robin
    virtual-server.f5.com/ip: controller-default
  creationTimestamp: "2020-06-14T07:38:22Z"
  generation: 8
  name: david-cats
  namespace: default
  resourceVersion: "11074222"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/david-cats
  uid: 177380c5-dc47-4a9f-9933-2b3d4ab66ba2
spec:
  rules:
  - host: david-cats.xxxx.net
    http:
      paths:
      - backend:
          serviceName: david-cats
          servicePort: 80
  tls:
  - hosts:
    - david-cats.xxxx.net
status:
  loadBalancer:
    ingress:
    - ip: 10.230.0.22
```

**Comment by AMoghrabi** [comment]
I'm not sure if this is helpful information or if this is a symptom of the above errors, but I noticed when I try to hit the site via incognito mode in my web browser, it'll hang for maybe 5-10 seconds and then I get a "Connection Reset", finally the page auto-refreshes and I get a 200 OK. 

This doesn't happen all the time. If I open and close incognito mode 2-3 times I can usually replicate the issue.

I'm wondering if this is caused by the overwrites.

**Comment by nandakishorepeddi** [comment]
I would see secrets are not referenced in the above ingress resource. Could you please create the secret try to reference the same under "tls" section. Please refer this example : https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/ingress/single-service-tls-ingress.yaml

**Comment by AMoghrabi** [comment]
Hey @nandakishorepeddi, 

So we have two certificates. One is default certificate that we manually placed on the F5. We can reference this certificate just fine in our ingress.

Second certificate is generated by Let's Encrypt. This secret appears on the F5 but not in the "Selected" column of the virtual server. This is in reference to my second ticket I opened: https://github.com/F5Networks/k8s-bigip-ctlr/issues/1353

If I move the Let's Encrypt certificate to the `Selected` column (doing this manually), then all is well. SSL works for both domains. But I still see the overwrite warnings.

**Comment by AMoghrabi** [comment]
One last thing I want to mention is we moved away from using this tool as our ingress-controller. Instead we are using it to populate the F5 with our nodes and sending traffic to an nginx-ingress, which was our ultimate goal in the first place.

**Comment by mdditt2000** [comment]
@AMoghrabi using CIS to automate nginx-ingress is a very smart options. Please read more about that solution documented at https://devcentral.f5.com/s/articles/Better-together-F5-Container-Ingress-Services-and-Nginx-Ingress-Controller-Integration

Is this issue still a concern or can i close this issue?

**Comment by mdditt2000** [comment]
Jira CONTCNTR-1923 filed for this BUG for PM tracking

**Comment by AMoghrabi** [comment]
Hi Mark. I actually have commented on that page to receive help, thank you.

Yep issue may be closed.
