### ISSUE TITLE
k8s-bigip-ctl and F5 more than one pool in configuration (automatically change IP addresses)

### ISSUE THREAD

**Issue by tomaszmzyk** [F5Networks/k8s-bigip-ctlr#1355]
CIS Version : 2.0.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 15.1.0.2
AS3 Version: 3.19.1
Agent Mode: AS3
Orchestration: Openshift
Orchestration Version: 3.11
Pool Mode: ClusterIP

Hi
I read some github about more than one pool in AS3 configuration.
I prepared a AS3 config with two pools according to this document. 
Below is section with this pools:
"HELLOWORLD1": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": [
                                    "172.130.4.16",
                                    "172.128.6.16"
                                ]
                            }
                        ]
                    },
                    "HELLOWORLD2": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": [
                                    "172.130.2.18",
                                    "172.129.2.19",
                                    "172.130.4.17"
                                ]
                            }
                        ]
                    },

For this pools is prepared LTM policy with rules. This work but only for the first time when we redeploy pods.
After redeploy pods IP addressess changed and we must change configmap.

Is there a solution that we can automatically canged this address like for configuration with one pool ?
When we have one pool, there is acording to AS3 documentation for example:
                   "HELLOWORLD1": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }

Regards

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by vklohiya** [comment]
@tomaszmzyk ,you don't need to put any IP address in pool definition as it's dynamically learned by CIS by reading service endpoint. You can create pool without any endpoints in configmap as follows:

"HELLOWORLD1": {
"class": "Pool",
"monitors": [
"http"
],
"members": [
{
"servicePort": 8080,
"serverAddresses": []
}
]
},
"HELLOWORLD2": {
"class": "Pool",
"monitors": [
"http"
],
"members": [
{
"servicePort": 8080,
"serverAddresses": []
}
]
},

**Comment by tomaszmzyk** [comment]
Hi
Indeed. Thanks for information. I tested and works as expected.

Regards
