### ISSUE TITLE
Pod lifecycle and F5 bigip controller

### ISSUE THREAD

**Issue by anjkl** [F5Networks/k8s-bigip-ctlr#1359]
#### Title
ReadinessGates and F5 bigip controller

#### Description
Implement ReadinessGates feature to F5 bigip controller.

#### Actual Problem
We use f5-bigip-ctrl in cluster mode (`--pool-member-type=cluster`). In some cases it leads to entire application downtime as it was described in https://github.com/F5Networks/k8s-bigip-ctlr/issues/1009.

#### Solution Proposed
I want to have a guarantee that any issues with f5 big ip controller or F5 API do not affect application deployment process in a k8s cluster.

The first solution that I see is ReadinessGates feature that was marked as stable in Kubernetes 1.14.
Using ReadinessGates feature, k8s deployment controller can automatically stop deployments when something goes wrong with f5 controller.

Description of ReadinessGates can be found [here](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate) and [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0007-pod-ready%2B%2B.md)

#### Alternatives
I haven't tested nodeport mode, but I think it can help. My opinion is nodeport mode isn't the best solution.

#### Additional context
As a workaround, we created a simple custom ReadinessGate controller as a separate application in addition to f5-bigip-ctrl.

This controller works in the following way:
* We add additional readinessGate condition to k8s Deployment.
* ReadinessGate controller subscribes to pod's events with type `ADDED`
* It checks if pod IP exists in F5 pool.
* Then controller sets readinessGate condition as True if pod IP is in F5 pool.

It leads to the following situation:
By default k8s endpoint controller adds IP of pod to Endpoins when all Readiness Probes are `True` including ReadinessGates.
For this reason Service parameter `svc.spec.publishNotReadyAddresses` has to be set to `true`.
Otherwise, pod IP will never be added to Endpoints because of readinessGate condition which in turn can not be satisfied since f5-bigip-ctrl adds only ready IPs to F5.

Now it means that we add non-ready pods to F5. In this case, we have to rely on F5 health check for pool members.
But it introduces another issue. f5-bigip-ctrl registers pods in state Unknown(enabled) and allows to send traffic to them before the first health check happens. So in case, the pod turns out unhealthy, we end up sending traffic to unoperational pod for up to 5 seconds (health check period) basically meaning application downtime.

Adding ReadinessGate feature to f5-bigip-ctrl will allow us to add Pod IPs right after successful Readiness Probe (regardless of ReadinessGate status) directly to F5 without having to deal with Endpoints.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Discussing this request with the CIS team

**Comment by mdditt2000** [comment]
Team needs to explore Github #1009 issue as CIS shouldn't affect or cause any application downtime as CIS is only automation. More investigation is needed
