### ISSUE TITLE
Documentation: Typo in https://clouddocs.f5.com/containers/latest/userguide/controller/config-options.html

### ISSUE THREAD

**Issue by pdp2shirts** [F5Networks/k8s-bigip-ctlr#1363]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 
#### Description  
In the ClusterIP section of https://clouddocs.f5.com/containers/latest/userguide/controller/config-options.html the third bullet point has this text: 

"Alternately Pod rotatable through network, for example:"

should be:

"Alternately Pod routable through network, for example:"

I'll submit a PR for this if you can point me to the correct repo and location for this doc.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@vtrippel can we please make a modification to the document that @pdp2shirts pointed out. 

"Alternately Pod **rotatable** through network, for example:"

should be:

"Alternately Pod **routable** through network, for example:"

@vtrippel do you need me to open a JIRA?

**Comment by vtrippel** [comment]
This is fixed now: https://clouddocs.f5.com/containers/latest/userguide/controller/config-options.html#clusterip

Thank you!
