### ISSUE TITLE
Migration from iApps to AS3

### ISSUE THREAD

**Issue by anjkl** [F5Networks/k8s-bigip-ctlr#1366]
#### Setup Details
All tests was checked with the following setup:
Build: f5networks/k8s-bigip-ctlr:1.14.0 (Version: 1.14.0, BuildInfo: n2285-661543171) and 2.0.0 (Version: 2.0.0, BuildInfo: cloud-user-efcab9e-20200522033624). Details are bellow.
BIGIP Version: BIG-IP 14.1.2.3 Build 0.0.5 Point Release 3
Agent Mode: Both AS3 and CCCL. Details are below.
Orchestration: K8S
Orchestration Version: 1.16
Pool Mode: Cluster
Additional Setup details: CNI: calico

#### Description  
I've described the issue that we have with iApps and k8s-bigip-ctrl [here](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1240)
So now I'm trying to prepare a plan of migration to AS3.

I tested out AS3 implementation in f5-bigip-ctrl and found a few issues that are blockers for migration to AS3 declaration.

f5-bigip-ctrl 1.14.0 doesn't work with AS3 well.

Configuration of f5-bigip-ctrl:
```
k8s-bigip-ctrl run args:
Pod Template:
  Labels:           app=k8s-bigip-ctlr
  Service Account:  bigip-ctlr
  Containers:
    Args:
      --credentials-directory=/credentials-directory
      --bigip-partition=AS3_TEST
      --pool-member-type=cluster
      --namespace-label=bigip
      --log-level=INFO
      --insecure=true
```

When I was trying to create configMap with AS3 declaration I got the following error:
```
2020/06/19 12:37:29 [ERROR] Error parsing ConfigMap external-dns_f5-as3-external-dns
```

The similar issue is described #1290
Here are some points to add to the discussion:
* Despite the above error, everything that was described in AS3 declaration was successfully created in F5 by f5-bigip-ctrl
* But when I tried to scale up/down application pods nothing was changed in F5 and the same error message was displayed. So the controller didn't push anything to F5.

After that I tried to update f5-bigip-ctrl to 2.0.0 and faced another issue:
* --agent=as3 is default in 2.0.0 version.
* f5-bigip-ctrl-2.0.0 doesn't work with iApp configuration when agent is as3. So this configuration isn't suitable for us.
* When I'm trying to change --agent to cccl I get another situation: the controller deploys iapps but not as3.

So the question is how can I migrate configuration from iApps to AS3?
Sorry for mixing different cases and configurations in the issue report.

iApp ConfigMap was presented in https://github.com/F5Networks/k8s-bigip-ctlr/issues/1240
AS3 configuration is:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-external-dns
  namespace: external-dns
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "f70f24b8-1c4a-4b46-9c35-19d79fc94a9e",
            "PARTITION_DNS": {
                "class": "Tenant",
                "external_dns": {
                    "class": "Application",
                    "template": "generic",
                    "external_dns_tcp": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                            {"use": "external_dns_vip"}
                        ],
                        "virtualPort": 53,
                        "pool": "external_dns_pool",
                        "allowVlans": [
                            "/Common/INTERNAL"
                        ]
                    },
                    "external_dns_udp": {
                        "class": "Service_UDP",
                        "virtualAddresses": [
                            {"use": "external_dns_vip"}
                        ],
                        "virtualPort": 53,
                        "pool": "external_dns_pool",
                        "allowVlans": [
                            "/Common/INTERNAL"
                        ]
                    },
                    "external_dns_pool": {
                        "class": "Pool",
                        "monitors": [
                                { "use": "external_dns_monitor" }
                        ],
                        "members": [
                            {
                                "servicePort": 53,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "external_dns_monitor": {
                        "class": "Monitor",
                        "monitorType": "dns",
                        "queryName": "kubernetes.default.svc.kubespray-sandbox.dub",
                        "queryType": "a",
                        "interval": 5,
                        "receive": "172.22.0.1"
                    },
                    "external_dns_vip": {
                        "class": "Service_Address",
                        "virtualAddress": "10.108.3.11",
                        "routeAdvertisement": "selective",
                        "icmpEcho": "enable"
                    }
                }
            }
        }
    }
```

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by nmenant** [comment]
Hi,

i've tested the following configuration without issue: 

> kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-external-dns
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "f70f24b8-1c4a-4b46-9c35-19d79fc94a9e",
            "PARTITION_DNS": {
                "class": "Tenant",
                "external_dns": {
                    "class": "Application",
                    "template": "generic",
                    "external_dns_tcp": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                            {"use": "external_dns_vip"}
                        ],
                        "virtualPort": 53,
                        "pool": "external_dns_pool"
                    },
                    "external_dns_udp": {
                        "class": "Service_UDP",
                        "virtualAddresses": [
                            {"use": "external_dns_vip"}
                        ],
                        "virtualPort": 53,
                        "pool": "external_dns_pool"
                    },
                    "external_dns_pool": {
                        "class": "Pool",
                        "monitors": [
                                { "use": "external_dns_monitor" }
                        ],
                        "members": [
                            {
                                "servicePort": 53,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "external_dns_monitor": {
                        "class": "Monitor",
                        "monitorType": "dns",
                        "queryName": "kubernetes.default.svc.kubespray-sandbox.dub",
                        "queryType": "a",
                        "interval": 5,
                        "receive": "172.22.0.1"
                    },
                    "external_dns_vip": {
                        "class": "Service_Address",
                        "virtualAddress": "10.108.3.11",
                        "routeAdvertisement": "selective",
                        "icmpEcho": "enable"
                    }
                }
            }
        }
    }

Have you installed AS3 on your BIG-IP? i've tested with AS3.20 without issue
CIS version: f5networks/k8s-bigip-ctlr:2.0.0

**Comment by anjkl** [comment]
`f5-appsvcs` has been updated to version `3.20.0-3` (3.19 used before) and I see the same issue.

`f5networks/k8s-bigip-ctlr:2.0.0` works with AS3 but not with iApp (it just deletes all objects that were created using iApps) as I described above.

It means we cannot upgrade the controller to 2.0.0 version because we use iApps in production.

**Comment by mdditt2000** [comment]
good morning @anjkl 

what iApp btw are you using?

**Comment by mdditt2000** [comment]
Please note that CIS 2.0 uses the AS3-18 schema. Updating to version 3.20.0-3 wont make much difference. Please can we open a F5 support ticket so we can have support look at the why the iApp with legacy configmap isnt not working in CIS 2.0

**Comment by mdditt2000** [comment]
SR opened C3309528 - Please use the SR to continue to work this issue. This Github can be closed so we do not duplicate work.

**Comment by mdditt2000** [comment]
Closing issue as support is working the SR. Duplicate item
