### ISSUE TITLE
AS3 logs show up in bigip controller even when AS3 isn't enabled

### ISSUE THREAD

**Issue by anfernee** [F5Networks/k8s-bigip-ctlr#1367]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 1.14.0
 AS3 Version: 3.20      
 Agent Mode: CCCL       
 Orchestration: K8S     
 Orchestration Version: 1.16.8
 Pool Mode:Nodeport      

#### Description  
We didn't enable as3 mode, but the controller still prints the error messages: 
```
  2020/06/19 19:06:34 [ERROR] [AS3] REST call error: Post https://xxx/mgmt/shared/appsvcs/declare/: x509: certificate is valid for localhost.localdomain, not xxx
```

#### Expected Result 
It shouldn't complain because we are running cccl mode.

#### Actual Result  
```
  2020/06/19 19:06:34 [ERROR] [AS3] REST call error: Post https://xxx/mgmt/shared/appsvcs/declare/: x509: certificate is valid for localhost.localdomain, not xxx
```

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@anfernee please can i see your CIS deployment arguments. I can see you are wanting to use the legacy Container Connector API **Agent Mode: CCCL**. This was the default API in CIS 1.x. When moving to CIS 2.0 we switched the default API to **Agent Mode: AS3**

Without specifying agent=cccl in the CIS deployment arguments running CIS 2.0, CIS will be used. Therefore what you are seeing is correct. Please add the argument

**Comment by anfernee** [comment]
I am using CIS 1.14, and it's using cccl mode. 

The arguments: 
```      
- args:
        - --credentials-directory=/etc/bigip-login
        - --bigip-partition=$(BIGIP_PARTITION)
        - --log-level=DEBUG
        - --pool-member-type=nodeport
```

**Comment by mdditt2000** [comment]
Thanks @anfernee in CIS 1.14 you wont see 
```
[ERROR] [AS3] REST call error: Post https://xxx/mgmt/shared/appsvcs/declare/: x509: certificate is valid for localhost.localdomain, not xxx
```
Please make sure your image is pointing to f5networks/k8s-bigip-ctlr:1.14.0 and not the latest image. If you think you still seeing [ERROR] [AS3] REST call error, i need to see the K8S logs after the controller is restarted 

Thanks Mark

**Comment by anfernee** [comment]
I was running CIS 1.14 (It also applied to previous releases like 1.13) and I saw that error message. I think the error I war running into was from postmanager, which is not gaurded by mode=as3: https://github.com/F5Networks/k8s-bigip-ctlr/blob/v1.14.0/cmd/k8s-bigip-ctlr/main.go#L777-L788

**Comment by mdditt2000** [comment]
@anfernee are you using user-defined configmap, ingress or routes? I am going to try reproduce this

**Comment by mdditt2000** [comment]
I see the same error

```
[kube@k8s-1-18-master root]$ kubectl logs -f deploy/k8s-bigip-ctlr-deployment  -n kube-system | grep --color=auto -i '\[as3'
2020/06/25 20:48:21 [DEBUG] [AS3] Invalid trusted-certs-cfgmap option provided.
2020/06/25 20:48:21 [DEBUG] [AS3] No certs appended, using only system certs
2020/06/25 20:48:24 [DEBUG] [AS3] PostManager Accepted the configuration
2020/06/25 20:48:24 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/06/25 20:48:24 [DEBUG] [AS3] Stated creating AS3 Informers
2020/06/25 20:48:24 [ERROR] [AS3] REST call error: Post https://192.168.200.92/mgmt/shared/appsvcs/declare/: x509: cannot validate certificate for 192.168.200.92 because it doesn't contain any IP SANs
2020/06/25 20:48:54 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/06/25 20:48:54 [ERROR] [AS3] REST call error: Post https://192.168.200.92/mgmt/shared/appsvcs/declare/: x509: cannot validate certificate for 192.168.200.92 because it doesn't contain any IP SANs
2020/06/25 20:49:24 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/06/25 20:49:24 [ERROR] [AS3] REST call error: Post https://192.168.200.92/mgmt/shared/appsvcs/declare/: x509: cannot validate certificate for 192.168.200.92 because it doesn't contain any IP SANs
2020/06/25 20:49:54 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/06/25 20:49:54 [ERROR] [AS3] REST call error: Post https://192.168.200.92/mgmt/shared/appsvcs/declare/: x509: cannot validate certificate for 192.168.200.92 because it doesn't contain any IP SANs
2020/06/25 20:50:24 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/06/25 20:50:24 [ERROR] [AS3] REST call error: Post https://192.168.200.92/mgmt/shared/appsvcs/declare/: x509: cannot validate certificate for 192.168.200.92 because it doesn't contain any IP SANs
^C
[kube@k8s-1-18-master root]$
```
@agupta49 why in CIS 1.14 is CIS trying to declare to BIG-IP when using CCCL agent "default"?

Follow-up on standby

**Comment by agupta49** [comment]
@mdditt2000 As we can switch between CCCL and AS3 mode. CIS doesn't know the previous agent state information. To clear the AS3 partition data in CCCL mode CIS is posting an empty AS3 declaration. CIS upcoming release with single partition support will fix this.

**Comment by mdditt2000** [comment]
Resolving in CIS 2.1

**Comment by mdditt2000** [comment]
Closing this issue out. CIS 2.1 released in a few weeks.

**Comment by achontzo** [comment]
Please re-open this ticket. I also have the same issue, As far as I know 1.X version is still maintained/supported and people are still using it (and cannot just upgrade from ingress to ASM)
