### ISSUE TITLE
Add support to customize the virtual server name with Ingress resources

### ISSUE THREAD

**Issue by pedrorouremalta** [F5Networks/k8s-bigip-ctlr#1378]
#### Title
Add support to customize the virtual server name with Ingress resources

#### Description
Currently, when using CIS with Ingress resources, a virtual server is created with a name following the pattern: "ingress_<IP with dots replaced by underscore>_port". 

#### Actual Problem
The default name pattern used by Ingress resources when naming virtual servers is not meaningful which makes difficult  to known only by the virtual server name to which application the virtual server is related to (mainly in an environment with a huge number of applications). It will be particularly helpful if the virtual server name could be customized to any name like "vs_myapp1", "vs_myapp2" and so on.  
#### Solution Proposed
Create an annotation that could be placed inside a Ingress declaration and give control over the name of virtual server that will be created. 

#### Alternatives
Currently, to control the virtual server name I'm using the ConfigMap resource which provides more control over the AS3 declaration. But it will be very helpful if the Ingress resource supported the customization of the virtual server name.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Discussed with team to add a Label to the Ingress for allowing a custom name on the ingress. CIS 2.2 is target 

PM to create to for CIS 2.2 planning

**Comment by trinaths** [comment]
@pedrorouremalta - Agree with adding custom names to ingress resources. But this give a free hand to create duplicate name and is not better manageable sometimes. CIS provided names are unique with IP, Port and Namespace combination. This helps in identifying the same named Virtual in different namespace.

**Comment by trinaths** [comment]
Closing this issue.
