### ISSUE TITLE
TLS_Server class - unable to add parameters

### ISSUE THREAD

**Issue by tomaszmzyk** [F5Networks/k8s-bigip-ctlr#1383]
#### Setup Details
 CIS Version : 1.14      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.0.2
 AS3 Version: 3.13      
 Agent Mode: AS3/CCCL       
 Orchestration: OSCP      
 Orchestration Version: 3.11
 Pool Mode: Cluster

#### Description  
Hi
I try add some parametres to TLS_Server class.
My configuration looks like below:

                 "TLS_CERT_VS": {
                        "class": "Certificate",
                        "certificate": {"bigip":"/Common/CERT_VS"},
                        "privateKey": {"bigip":"/Common/CERT_VS"},
                        "chainCA": {"bigip":"/Common/CERT_ROOT_CA.crt"}
                    },
                    "SSL_VS": {
                        "class": "TLS_Server",
                        "certificates": [
                            {
                                "certificate": "TLS_CERT_VS"
                            }
                        ]
                    },  

When I want add some of the following parameters, for example:
cipherGroup
                   "cipherGroup": {
                            "bigip": "/Common/CIPHERS_VS"
                        }
or one from:
                   "insertEmptyFragmentsEnabled": true,
                    "singleUseDhEnabled": true,
                    "tls1_3Enabled": false,
                    "tls1_2Enabled": false,
                    "tls1_1Enabled": true,
                    "tls1_0Enabled": false,

Configuration after add look like:

                "TLS_CERT_VS": {
                        "class": "Certificate",
                        "certificate": {"bigip":"/Common/CERT_VS"},
                        "privateKey": {"bigip":"/Common/CERT_VS"},
                        "chainCA": {"bigip":"/Common/CERT_ROOT_CA.crt"}
                    },
                    "SSL_VS": {
                        "class": "TLS_Server",
                        "certificates": [
                            {
                                "certificate": "TLS_CERT_VS"
                            }
                        ],
                        "tls1_3Enabled": false
                    },  

I have error in controller log:

2020/07/03 11:20:10 [ERROR] AS3 Template is not valid. see errors :
2020/07/03 11:20:10 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/07/03 11:20:10 [ERROR] - declaration: Additional property tls1_3Enabled is not allowed
2020/07/03 11:20:10 [ERROR] - declaration: Must validate all the schemas (allOf)
2020/07/03 11:20:10 [ERROR] [AS3] Error validating template

#### Steps To Reproduce
1) Create AS3 schema for F5
2) Prepare configuartion with TLS_Server class
3) Add parameters to class

#### Expected Result 

Properly validated schema witch parameters

#### Actual Result  

Error during validation

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)

Regards

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@tomaszmzyk most likely your CIS doesn't have the updated AS3 schema to support the configuration. Cipher groups and TLS shipped between AS3-18 and AS3-20. Please can you update the AS3 rpm on your BIG-IP and try again. 

If still fails please can you send me your resource defintion. I believe you are using a AS3 configmap. If you cannot paste your AS3 configmap on GIT please open a support ticket.

**Comment by mdditt2000** [comment]
TLS options added to AS3 in CIS 3-19
https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.19.0
Added support for additional TLS options, GitHub Issue 233

**Comment by tomaszmzyk** [comment]
Hi
This is my config:
apiVersion: v1
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "ocp-f5-app",
            "X_OCP_APP": {
                "class": "Tenant",
                "APP_APP": {
                    "class": "Application",
                    "template": "generic",
                    "VS_APP_443": {
                        "class": "Service_HTTPS",
                        "virtualAddresses": [
                            "10.115.129.54"
                        ],
                        "virtualPort": 443,
                        "redirect80": true,
                        "pool": "TEST",
                        "profileHTTP": {"bigip": "/Common/DEFAULT_HTTP"},
                        "persistenceMethods" : [{"bigip": "/Common/DEFAULT_STICKY"}],
                        "iRules": [
                            {"bigip": "/Common/RULE_DEFAULT_01"},
                            {"bigip": "/Common/RULE_DEFAULT_02"}
                        ],
                        "allowVlans": [{"bigip":"/Common/VLAN_EX"}],
                        "profileTCP" : {"bigip":"/Common/TCP_PROFILE"},
                        "serverTLS": {"bigip": "/Common/SSL_CLIENT_VS"}
                    },
                    "TLS_CERT_VS": {
                        "class": "Certificate",
                        "certificate": {"bigip":"/Common/X_OCP_CERT_VS"},
                        "privateKey": {"bigip":"/Common/X_OCP_CERT_VS"},
                        "chainCA": {"bigip":"/Common/CERT_ROOT_CA.crt"}
                    },
                    "SSL_CLIENT_VS": {
                        "class": "TLS_Server",
                        "certificates": [
                            {
                                "certificate": "TLS_CERT_VS"
                            }
                        ]
                    },

                }
            }
        }
    }

We use the version 3.19
f5-appsvcs | 3.19.1 | 1 | f5-appsvcs-3.19.1-1.noarch | PLUGIN

But in config I can use only version prior to 3.13.0

2020/07/08 08:49:09 [ERROR] - declaration.schemaVersion: declaration.schemaVersion must be one of the following: "3.13.0", "3.12.0", "3.11.0", "3.10.0", "3.9.0", "3.8.0", "3.7.0", "3.6.0", "3.5.0", "3.4.0", "3.3.0", "3.2.0", "3.1.0", "3.0.0"

Regards

**Comment by mdditt2000** [comment]
@tomaszmzyk please change the schema version in the declaration to "**schemaVersion": "3.19.0".**

**Comment by tomaszmzyk** [comment]
Hi
I wrote  in my previous comment.
When I change schema to version higher than 3.13.0 I have error:
2020/07/09 04:53:24 [ERROR] AS3 Template is not valid. see errors :

2020/07/09 04:53:24 [ERROR] - declaration.schemaVersion: declaration.schemaVersion must be one of the following: "3.13.0", "3.12.0", "3.11.0", "3.10.0", "3.9.0", "3.8.0", "3.7.0", "3.6.0", "3.5.0", "3.4.0", "3.3.0", "3.2.0", "3.1.0", "3.0.0"

2020/07/09 04:53:24 [ERROR] [AS3] Error validating template

I use k8s-bigip-ctrl version 1.14, and at this moment I can't use version 2.0, because we use configmap per project (for security and owners reasons)

Regards

**Comment by andrijaperovic** [comment]
Am seeing a similar issue with latest RPM installation (f5-appsvcs-3.22.1-1.noarch.rpm) and using schema version 3.19.0 with `declaration: Must validate "then" as "if" was valid` errors:

```
kubectl logs k8s-bigip-ctlr-deployment-69f765c45f-spwxm -n kube-system | egrep -i "error|excep|warn|fail"
2020/09/20 20:54:34 [ERROR] [AS3] Template is not valid. see errors
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serviceMain is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serviceMain is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serviceMain is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serviceMain is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serviceMain is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serviceMain is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate all the schemas (allOf)
2020/09/20 20:54:34 [ERROR] - declaration: Must validate "then" as "if" was valid
2020/09/20 20:54:34 [ERROR] - declaration: serverTLS is required
2020/09/20 20:54:34 [ERROR] - declaration: Must validate all the schemas (allOf)
2020/09/20 20:54:34 [ERROR] [AS3] Error validating AS3 template
2020/09/20 20:54:34 [ERROR] [AS3] Error in processing the ConfigMap: istio-system/example-vs
```

Here is my configuration:
```
kind: ConfigMap
apiVersion: v1
metadata:
 name: example-vs
 namespace: istio-system
 labels:
   f5type: virtual-server
   as3: "true"
data:
 template: |
    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.19.0",
            "id": "Idle_Timeout_Policy",
            "smf_user_engg_005": {
                "class": "Tenant",
                "Tenant_1": {
                    "class": "Application",
                    "istio_system_istio_ingressgateway_443_tcp_2": {
                        "class": "Service_HTTPS",
                        "virtualPort": 443,
                        "virtualAddresses": [
                            "10.29.28.40"
                        ],
                        "profileMultiplex": {
                          "use": "tcp_anthos"
                        }
                    },
                    "tcp_anthos": {
                        "class": "Multiplex_Profile",
                        "remark": "tcp_anthos timeout 443",
                        "maxConnections": 5000,
                        "maxConnectionAge": 3600,
                        "maxConnectionReuse": 20000,
                        "idleTimeoutOverride": 1800,
                        "connectionLimitEnforcement": "idle",
                        "sharePools": true
                    }
                }
            }
        }
    }
```

**Comment by vklohiya** [comment]
@andrijaperovic , AS3 version 3.22 is not supported with CIS 2.1.1 release. You can disable AS3 validation in CIS deployment as work around for now(--as3-validation=false). This will fixed in next release.

**Comment by andrijaperovic** [comment]
Thank you @vklohiya !

**Comment by trinaths** [comment]
Disable AS3 validation with `--as3-validation=false` flag. Closing this issue. No issues found in 2.4.1
