### ISSUE TITLE
[CIS2.0+AS3] No more CRUD available when one AS3 validation issue happen

### ISSUE THREAD

**Issue by f5minions** [F5Networks/k8s-bigip-ctlr#1392]
#### Setup Details
 CIS Version : 2.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.0      
 AS3 Version: 3.20     
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version: 1.18     
 Pool Mode: Cluster     
 Additional Setup details: CALICO

#### Description  
There is no more CRUD available when one AS3 validation was failed with below messages,

2020/07/07 16:11:36 [ERROR] [AS3] Template is not valid. see errors
2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:36 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:36 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:37 [ERROR] [AS3] Template is not valid. see errors
2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:37 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:37 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

Is this process expected behavior? or there is another way to continue CRUD works even though that one AS3 has some issues? 

#### Steps To Reproduce
1) apply below YAML to make AS3 validation fail,
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/ip: "1.113.150.10"
    virtual-server.f5.com/partition: "k8s-service"
    virtual-server.f5.com/serverssl: /Common/serverssl
    virtual-server.f5.com/health: |
      [
        {
          "path":     "keycloak.skb-doj-dev01.btvpaas.com/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        }
      ]
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/allow-http: "true"
  name: keycloak
  namespace: default
spec:
  rules:
  - host: keycloak.skb-doj-dev01.btvpaas.com
    http:
      paths:
      - backend:
          serviceName: httpbin1
          servicePort: 8000
        path: /* <-- will be failed by this "*" 
  tls:
    - secretName: /Common/clientssl
In that status we can apply another ingress like a below YAML,
----------------------2nd ingress ------
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/ip: 175.113.150.30
    virtual-server.f5.com/partition: k8s-service
  name: jenkins
  namespace: default
spec:
  rules:
  - host: jenkins.skb-doj-dev01.btvpaas.com
    http:
      paths:
      - backend:
          serviceName: f5-hello-world
          servicePort: 8080
        path: /
3)

CIS controller may not update anything.... if we find and remove some of AS3 validation issue than it works again.

#### Expected Result 
Want to know that is expected behavior or need to something to avoid this issue?

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

kubectl logs -f k8s-bigip1-ctlr-deployment-85c8575d6d-wrzjm -n kube-system
2020/07/07 16:09:51 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.0.0, BuildInfo: cloud-user-efcab9e-20200522033624
2020/07/07 16:09:51 [INFO] ConfigWriter started: 0xc00031c360
2020/07/07 16:09:52 [INFO] Started config driver sub-process at pid: 15
2020/07/07 16:09:52 [INFO] [INIT] Creating Agent for as3
2020/07/07 16:09:52 [INFO] [AS3] Initializing AS3 Agent
2020/07/07 16:09:52 [INFO] [CCCL] Initializing CCCL Agent
2020/07/07 16:09:52 [INFO] [CORE] NodePoller (0xc00003c240) registering new listener: 0x130d7c0
2020/07/07 16:09:52 [INFO] [CORE] NodePoller started: (0xc00003c240)
2020/07/07 16:09:52 [INFO] [CORE] Watching Ingress resources.
2020/07/07 16:09:52 [INFO] [CORE] Watching ConfigMap resources.
2020/07/07 16:09:52 [INFO] [CORE] Handling ConfigMap resource events.
2020/07/07 16:09:52 [INFO] [CORE] Handling Ingress resource events.
2020/07/07 16:09:52 [INFO] [CORE] Registered BigIP Metrics
2020/07/07 16:09:52 [INFO] [CCCL] Successfully Sent the FDB Records
2020/07/07 16:09:58 [INFO] [2020-07-07 16:09:58,746 __main__ INFO] entering inotify loop to watch /tmp/k8s-bigip-ctlr.config826231538/config.json
2020/07/07 16:10:23 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:23 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:23 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:23 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:httpbin1 ServicePort:8000 Namespace:default} and resource ingress_1-113-150-10_80
2020/07/07 16:10:23 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:23 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:httpbin1 ServicePort:8000 Namespace:default} and resource ingress_1-113-150-10_443
2020/07/07 16:10:23 [ERROR] [AS3] Template is not valid. see errors
2020/07/07 16:10:23 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:10:23 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:10:23 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:10:23 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:10:23 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:10:23 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:10:23 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:10:24 [ERROR] [AS3] Template is not valid. see errors
2020/07/07 16:10:24 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:10:24 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:10:24 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:10:24 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:10:24 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:10:24 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:10:24 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:10:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:22 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:36 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:36 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:36 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:36 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:36 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:f5-hello-world ServicePort:8080 Namespace:default} and resource ingress_175-113-150-30_80
2020/07/07 16:11:36 [ERROR] [AS3] Template is not valid. see errors
2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:36 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:36 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:36 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:37 [ERROR] [AS3] Template is not valid. see errors
2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:37 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/07 16:11:37 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/07/07 16:11:37 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:11:52 [WARNING] [CORE] Rule not found for Health Monitor path 'keycloak.skb-doj-dev01.btvpaas.com/'
2020/07/07 16:12:01 [INFO] [CCCL] Successfully Sent the FDB Records
2020/07/07 16:12:35 [INFO] [CCCL] Successfully Sent the FDB Records

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Good afternoon @f5minions I see a few issues.

1. Please use the correct Ingress Api. Api changed after K8S 1.16. Correct Api is 

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
```
Example - https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/ingress/big-ip-92-cluster/ingress-examples/f5-k8s-ingress-https.yaml

2. Remove unsupported annotation

```
virtual-server.f5.com/serverssl: /Common/serverssl - this is a annotation for OpenShift Route. Not support by Ingress
```

Are you trying todo Edge TLS or re-encrypt? 

Here is a example of Edge TLS referencing BIG-IP clientssl profile. 
https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/ingress/big-ip-92-cluster/ingress-examples/f5-k8s-ingress-https.yaml

**Comment by f5minions** [comment]
Hi mdditt,
I want to use end to end tls encryption, means that below
client>>>> TLS >>>>F5 >>>> TLS >>>> backend server. In this case, how we can support it without "virtual-server.f5.com/serverssl: /Common/serverssl "? and that also works well on my k8s environmemt...

let me know how to use re-encrypt on k8s ingress? In your f5-k8s-ingress-https.yaml is for EDGE tls use case.

Thanks.

**Comment by mdditt2000** [comment]
@f5minions thank you for providing clarity. @vklohiya provide the following example. Please follow these examples todo what you need

**Example 1**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    virtual-server.f5.com/ip: 172.16.3.11
    virtual-server.f5.com/serverssl: /Common/serverssl
  name: k8s13
  namespace: default
spec:
  backend:
    serviceName: svc
    servicePort: 80
  tls:
  - secretName: /Common/clientssl
 ```
**Example 2**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: f5
    virtual-server.f5.com/balance: least-connections-node
    virtual-server.f5.com/health: '[                 {"path": "/",                  "send":
      "HTTP GET /",                  "interval": 2,                  "timeout": 5                     }                 ]'
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/https-port: "443"
    virtual-server.f5.com/ip: 172.16.3.11
    virtual-server.f5.com/partition: test
    virtual-server.f5.com/serverssl: /Common/pytest-foo-serverssl
  name: svc-1
  namespace: default
spec:
  backend:
    serviceName: svc-1
    servicePort: 443
  tls:
  - secretName: /Common/pytest-foo-clientssl
```

This should resolve your issue. Please keep in mind that these TLS profiles have to be created. CIS using AS3 doesn't created the profiles. AS3 is used under CIS and references these profiles.

**Comment by f5minions** [comment]
Thanks for your update so you mean that we can use below on k8s environment also,
virtual-server.f5.com/serverssl: /Common/serverssl 

Is it correct? 

And if CIS controller met some of the invalid ingress, the controller may not work any other creation or deletion and update until that invalid ingress was resolved. --> actually i want to know this. is it by design?

please check this once again.

**Comment by mdditt2000** [comment]
@f5minions yes this is used in nightly regression. /Common/serverssl is used for re-encrypt.

**Comment by mdditt2000** [comment]
@f5minions please change your path to "path": "keycloak.skb-doj-dev01.btvpaas.com",

Remove the /. This character is invalid.

**Comment by mdditt2000** [comment]
@f5minions have we resolved your issue? There are multiple in the github.

**Comment by f5minions** [comment]
Hi mddit,
Is below link works well?
https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/slack/ingress/re-encrypt-tls.yaml

I tried to apply it on my lab environment but that looks didn't working with below error messages,

2020/07/11 07:41:37 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:f5-hello-world ServicePort:8080 Namespace:default} and resource ingress_10-192-75-108_443


2020/07/11 07:41:37 [ERROR] [AS3] Template is not valid. see errors
2020/07/11 07:41:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/11 07:41:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/11 07:41:37 [ERROR] - declaration.Shared: serverTLS is required

2020/07/11 07:41:37 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)


2020/07/11 07:41:37 [ERROR] [AS3] Template is not valid. see errors
2020/07/11 07:41:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/11 07:41:37 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/07/11 07:41:37 [ERROR] - declaration.Shared: serverTLS is required

2020/07/11 07:41:37 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)


Maybe below didn't recognize by AS3
    servicePort: 8080
  tls:
  - secretName: test-secret <----- this point.

And i used below than it works well,
    servicePort: 8080
  tls:
  - secretName: /Common/clientssl

**Comment by mdditt2000** [comment]
@f5minions glad it works well!

```
And i used below than it works well,
servicePort: 8080
tls:

secretName: /Common/clientssl
```

I will close this issue as done.
