### ISSUE TITLE
AS3 configmap and blank declaration safeguards

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1415]
#### Setup Details
 CIS Version : 1.14
 Build: f5networks/k8s-bigip-ctlr:1.14       
 BIGIP Version: Big IP 14.1.2
 AS3 Version: 3.13      
 Agent Mode: AS3   
 Orchestration: K8S      
 Orchestration Version: 1.16
 Pool Mode: Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
We should provide some safeguard when k8s user mistakenly deploys both a blank configmap and a normal configmap (with config objects) simultaneously. This causes CIS to continuously create and delete config objects on BIG-IP and eventually use up all resources on BIG-IP

#### Steps To Reproduce
1)Deploy blank configmap with a certain configmap name like "delete-cm", specifying tenant1
2)Deploy another configmap specifying the same tenant1, but with the configuration objects simultaneously, named "create-cm"
3) Note that CIS will attempt to create then delete the objects continuously

#### Expected Result 
Should not be able to send two configmaps simultaneously to the same tenant. 

#### Actual Result  
CIS will create and then delete AS3 objects continuously. 

#### Diagnostic Information

configmap could be any configuration. 

/var/log/ltm shows that the AS3 objects are continuously created at whatever as3 POST interval you set (default 30s)
```
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01070727:5: Pool /Tenant1/app1/nginx_pool member /Common/2004:c030:111:40f1::1d:32129 monitor status up. [ /Common/http: up ]  [ was unchecked for 0hr:0min:1sec ]
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01070727:5: Pool /Tenant1/app1/nginx_pool member /Common/2004:c030:111:40f1::1f:32129 monitor status up. [ /Common/http: up ]  [ was unchecked for 0hr:0min:1sec ]
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01070727:5: Pool /Tenant1/app1/nginx_pool member /Common/2004:c030:111:40f1::5:32129 monitor status up. [ /Common/http: up ]  [ was unchecked for 0hr:0min:1sec ]
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01070727:5: Pool /Tenant1/app1/nginx_pool2 member /Common/2004:c030:111:40f1::1d:31283 monitor status up. [ /Common/http: up ]  [ was unchecked for 0hr:0min:1sec ]
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01070727:5: Pool /Tenant1/app1/nginx_pool2 member /Common/2004:c030:111:40f1::1f:31283 monitor status up. [ /Common/http: up ]  [ was unchecked for 0hr:0min:1sec ]
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01070727:5: Pool /Tenant1/app1/nginx_pool2 member /Common/2004:c030:111:40f1::5:31283 monitor status up. [ /Common/http: up ]  [ was unchecked for 0hr:0min:1sec ]
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01071681:5: SNMP_TRAP: Virtual /Tenant1/app1/service1 has become available
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 01071681:5: SNMP_TRAP: Virtual /Tenant1/app1/service2 has become available
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 0107168c:5: Incremental sync complete: This system is updating the configuration on device group /Common/devicegroup1 device %cmi-mcpd-peer-/Common/bigip2.local from commit id { 19228 6850840440047175001 /Common/bigip1.local } to commit id { 19231 6850840443946674692 /Common/bigip1.local }.
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 0107168c:5: Incremental sync complete: This system is updating the configuration on device group /Common/devicegroup1 device %cmi-mcpd-peer-/Common/bigip2.local from commit id { 19231 6850840443946674692 /Common/bigip1.local } to commit id { 19232 6850840444041180438 /Common/bigip1.local }.
Jul 19 00:19:50 bigip1.local notice mcpd[6452]: 0107168c:5: Incremental sync complete: This system is updating the configuration on device group /Common/devicegroup1 device %cmi-mcpd-peer-/Common/bigip2.local from commit id { 19232 6850840444041180438 /Common/bigip1.local } to commit id { 19233 6850840444090268776 /Common/bigip1.local }.
Jul 19 00:19:53 bigip1.local notice mcpd[6452]: 010719e7:5: Virtual Address /Tenant1/cdn_svcaddr1 general status changed from BLUE to GREEN.
Jul 19 00:19:53 bigip1.local notice mcpd[6452]: 010719e8:5: Virtual Address /Tenant1/cdn_svcaddr1 monitor status changed from UNCHECKED to UP.
Jul 19 00:19:53 bigip1.local notice mcpd[6452]: 010719e7:5: Virtual Address /Tenant1/cdn_svcaddr2 general status changed from BLUE to GREEN.
Jul 19 00:19:53 bigip1.local notice mcpd[6452]: 010719e8:5: Virtual Address /Tenant1/cdn_svcaddr2 monitor status changed from UNCHECKED to UP.
```  

#### Observations (if any)

other services like tomcat also eventually affected:
```
# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError="/usr/bin/restart_tomcat"
#   Executing /bin/sh -c "/usr/bin/restart_tomcat"...
Sun Jul 19 15:49:13 JST 2020: START... [Ljava.lang.String;@5f07e8
Sun Jul 19 15:49:13 JST 2020: Calling command 1 with args: " restart tomcat"
Sun Jul 19 15:49:17 JST 2020: DONE: com.f5.util.ContainerManager$Result@b6881e
```

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by veeramalla-f5** [comment]
@tkam8 You cannot use two different AS3 Configmaps with same tenants. You could rather combine the declarations or use "kubectl delete cm <>" to incase u want to delete a specific configmap.

If you have a list of tenants in a configmap and want to delete a specific tenant, Please use kubectl edit option to remove the tenant configuration. 

Note: from CIS 2.1(available) we also support deletion of configmap by switching the label to false

**Comment by mdditt2000** [comment]
AS3 expected behavior. @tkam8 please reach out to me

**Comment by mdditt2000** [comment]
@tkam8 please dont deploy a blank configmap. Please use the new feature in CIS 2.1 where you change the f5 label from true to false. 

Example below. 

**Add configmap**
```
labels:
    f5type: virtual-server
    as3: "true"
```
[AS3] Response from BIG-IP: code: 200 --- tenant:TCP --- message: success

![image](https://user-images.githubusercontent.com/12733938/89341586-60ee8f80-d656-11ea-8085-6ae896873641.png)

**Remove configmap** 
```
labels:
    f5type: virtual-server
    as3: "false"
```

[root@k8s-1-18-master vzn]# **kubectl apply -f as3-tcp-config.yaml**
[AS3] Response from BIG-IP: code: 200 --- tenant:TCP --- message: **success**

![image](https://user-images.githubusercontent.com/12733938/89341848-c5a9ea00-d656-11ea-93bf-815dce6da322.png)

AS3 configmap is removed. You can now delete the configmap. 
[root@k8s-1-18-master vzn]# **kubectl delete -f as3-tcp-config.yaml**

Update clouddocs coming this week.

**Comment by mdditt2000** [comment]
https://clouddocs.f5.com/containers/latest/userguide/config-map.html#delete-as3-configmap resolved. Closing issue
