### ISSUE TITLE
[Note] Template is not valid. When using CIS 2.1 with AS3 version: 3.21.0

### ISSUE THREAD

**Issue by mdditt2000** [F5Networks/k8s-bigip-ctlr#1433]
#### Setup Details
 CIS Version : 2.1     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.21     
 Agent Mode: AS3    
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      

#### Description  

CIS 2.1 doesn’t have the AS3-21 schema and therefore cannot validate the JSON 
 
**[AS3] Validating AS3 schema with  as3-schema-3.20.0-3-cis.json**
[AS3] posting GET BIGIP AS3 Version request on https://192.168.200.92/mgmt/shared/appsvcs/info
**[AS3] BIGIP is serving with AS3 version: 3.21.0**
 
We are seeing the following error
 
[ERROR] [AS3] Template is not valid. see errors
ERROR] [AS3] Template is not valid. see errors

CIS cannot validate schema and therefore get Template is not valid. We should rather say

#### Workaround
 
Please use AS3 version: as3-schema-3.20.0-3-cis.json or set validation to  - "--as3-validation=false"

#### Observations (if any)

CIS development can we print a message advising to use AS3 version: as3-schema-3.20.0-3-cis.json or set validation to  - "--as3-validation=false" and or allow a lower schema validation

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Internal PM Jira file CONTCNTR-2049

**Comment by mdditt2000** [comment]
**Hotfix**Please note this will resolved in CIS 2.1 but here is Hotfix for now. 

Please use below image to support AS3 v3.21.
docker pull f5networksdevel/k8s-bigip-ctlr:as3_21Support
 
**Updated CIS with latest AS3 v3.21.0-4 schema validation**.
Fix included for “[ERROR] [AS3] Template is not valid” if using higher AS3 version installed on BIG-IP.

**Comment by veeramalla-f5** [comment]
Will be fixed as part of 3.21

Intermediate image for use:
f5networksdevel/k8s-bigip-ctlr:as3_21Support
