### ISSUE TITLE
multiple configmap in single namespaces will cause online VS in F5 offline

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1434]
#### Setup Details
 CIS Version : 2.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.1    
 AS3 Version: 3.x      
 Agent Mode: AS3      
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
 
multiple configmap in single namespaces will cause online virtual server in F5 offline, even the service  label are different in configmap

#### Steps To Reproduce

Assuming the CIS 2.1 are installed and worker correctly.

0) get code

~~~
git clone https://github.com/kylinsoong/container-ingress.git
ls container-ingress/f5-cis/issue/1434/
cis.yaml        cm1.yaml        cm2.yaml        cm3.yaml        deploy.yaml
~~~

note that there are 5 yaml files exists.

1) deploy 3 apps in cistet namespace

~~~
kubectl create ns cistest
kubectl apply -f deploy.yaml
~~~

2) create 1st configmap

~~~
kubectl apply -f cm1.yaml
~~~

then check from F5 that the VS with path cistest/cistest_app-svc-1 go online

3) create 2nd configmap

~~~
kubectl apply -f cm2.yaml
~~~

then check from F5 that the previous cistest/cistest_app-svc-1 vs has gone, the new VS with path cistest/cistest_app-svc-2 overwrited the VS with cistest/cistest_app-svc-1.

4) create 3rd configmap

~~~
kubectl apply -f cm3.yaml
~~~

then check from F5 that the previous cistest/cistest_app-svc-2 vs has gone, the new VS with path cistest/cistest_app-svc-3 overwrited the VS with cistest/cistest_app-svc-2.

5) check the total configmap from cistest

~~~
kubectl get cm -n cistest
NAME         DATA   AGE
cistest100   1      8m57s
cistest101   1      6m58s
cistest102   1      70s
~~~

note that 3 configmaps existes in cistest.

#### The Biggest concern from customer

The customer thought this is a some kind of security issue, which CIS 2.1 has backdoor security risk, which the attacker create a configmap with offline online production service.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@kylinsoong testing this afternoon. Will update later today.

**Comment by mdditt2000** [comment]
Since your second and third configmap are not incremental you override the declaration. This is how AS3 works. You need to increment cm1 + cm2 + cm3 in one AS3 declaration. Look at the recreate. 

![image](https://user-images.githubusercontent.com/12733938/89474186-bb145100-d739-11ea-882a-c674fb923139.png)

https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/github/1434/cm-all.yaml

I created the JSON file for you at 

https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/github/1434/cm-all.json

**CIS is functioning as designed**

**Comment by mdditt2000** [comment]
Only one configmap
```
[root@k8s-1-18-master 1434]# kubectl get cm -n cistest
NAME         DATA   AGE
cistest100   1      4m10s
```

**Comment by mdditt2000** [comment]
Please review the label as3 = false to remove the configmap. No more blank

labels:
    f5type: virtual-server
    as3: "false"

**Comment by mdditt2000** [comment]
This can be closed out.
