### ISSUE TITLE
Support non-HTTP Virtual Servers with CRD

### ISSUE THREAD

**Issue by sbarre-esit** [F5Networks/k8s-bigip-ctlr#1443]
#### Title
Support non-HTTP Virtual Servers with CRD

#### Description
CIS automation powered by CRDs should support non-http traffic such as a more simple TCP forwarding.

#### Actual Problem
Currently CRD definitions only support HTTP traffic as the BIG-IP is configured to check the `Host` header and redirect based on that. We would like to be able to expose non-http traffic such as databases via CIS automation using CRDs. This is due to CRDs being easier to control with RBAC in K8S/OpenShift.

#### Solution Proposed
Add parameters for a tcp mode and specifying he port to use other than 80.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Created Jira CONTCNTR-2056 for PM tracking and planning. Need to support LTMprofile:

This will allow for support of TCP profile and allow none-http CRD support.

**Comment by mdditt2000** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1454

**Comment by mdditt2000** [comment]
Feature in test

**Comment by mdditt2000** [comment]
Code completed and merged. Awaiting integrated build for CIS release on Oct 21. Currently no delays. Closing issue out
