### ISSUE TITLE
CISv2.1.0 does not delete LTM-Policy reset-rule when OpenShift-annotation for whitelist-source-range will be removed

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#1458]
#### Setup Details
 CIS Version : 2.1.0   
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.0.3  
 AS3 Version: 3.20.0-build3 
 Agent Mode: AS3       
 Orchestration: K8S/OSCP      v1.17.1, OS v4.2
 Orchestration Version:       
 Pool Mode: Cluster 
 Additional Setup details: OpenShift-Routes using virtual-server.f5.com/whitelist-source-range: 

#### Description  
When I remove the annotation "virtual-server.f5.com/whitelist-source-range:" from my OpenShift-Route, the CIS does NOT update the matching rule in the BIG-IPs LTM-Policy (openshift_secure_routes, openshift_insecure_routes) correctly.
It does NOT delete the following reset-rule (example):
osr_f5test_httpd_b_example_reset {
            actions {
                0 {
                    shutdown
                    connection
                }
                1 {
                    asm
                    disable
                }
            }
            conditions {
                0 {
                    http-header
                    name host
                    values { <hostname> }
                }
            }
            ordinal 4
        }

#### Steps To Reproduce
1) add annotation "virtual-server.f5.com/whitelist-source-range: ..." to the relevant OpenShift-Route
2) remove annotation "virtual-server.f5.com/whitelist-source-range: ..." to the relevant OpenShift-Route
3) check LTM-policy on BIG-IP

#### Expected Result 
remove reset-rule in LTM-Policy (openshift_secure_routes, openshift_insecure_routes)

#### Actual Result  
Does NOT remove reset-rule in LTM-Policy (openshift_secure_routes, openshift_insecure_routes)

#### Diagnostic Information

Excerpt CIS-config
      image: 'registry.connect.redhat.com/f5networks/cntr-ingress-svcs:2.1.0-rhel7'
      args:
        - '--bigip-username=$(BIGIP_USERNAME)'
        - '--bigip-password=$(BIGIP_PASSWORD)'
        - '--bigip-url=A.B.C.D'
        - '--bigip-partition=XXX'
        - '--pool-member-type=cluster'
        - '--openshift-sdn-name=/Common/RD_000_TUN_VXL_0001'
        - '--log-level=INFO'
        - '--log-as3-response=true'
        - '--manage-routes=true'
        - '--manage-ingress=false'
        - '--route-label=XXX'
        - '--route-http-vserver=RD_000_VS_RED_XXX_80'
        - '--route-https-vserver=RD_000_VS_STD_XXX_443'
        - '--route-vserver-addr=A.B.C.D'
        - '--agent=as3'
        - '--insecure=true'
        - '--tls-version=1.3'
        - '--cipher-group=/Common/CIPHER_GROUP_AES-GCM_ECDHE_DHE_TLSV12_TLSV13'

#### Observations (if any)
It happens for each OpenShift-Route, once annotation "virtual-server.f5.com/whitelist-source-range:" was removed!

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by joebride** [comment]
I did some more testing. Let me share my results:
1.
Once annotation for whitelist-source-range was in use one time only, the CIS always configure reset-rule.
So if you remove whitelisting the CIS still configure the reset-rule in LTM-Policy, although is is not required anymore!

2.
The specific reset-rule per host is not required at all, because per default the CIS configure the reset-all-rule "openshift_route_waf_disable". This rule ensures blocking of all requests which are not explicitely allowed !!!

**Comment by joebride** [comment]
to 1.
To make it more clearer.
I manually removed the reset-rule in both LTM-policies via BIG-IP WebGUI. After some change in OpenShift the CIS added again the unnecessary reset-rule.

**Comment by vklohiya** [comment]
@joebride , reset rule is required if WAF Policy is not attached. I think we need to conditionally attach this reset rule.

**Comment by mdditt2000** [comment]
Scheduled for CIS 2.3

**Comment by trinaths** [comment]
This issue is fixed with CIS v2.3
