### ISSUE TITLE
Cannot create F5 resources using K8s Ingress Objects

### ISSUE THREAD

**Issue by eduardoriveror** [F5Networks/k8s-bigip-ctlr#1461]
Using CIS 2.1 and AS3 3.20, with BIG IP System 12.1.4.1 I can create F5 objects using AS3 configmaps and services, but not when using Kubernetes ingress objects. 

This is the configuration used so far:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress-class: f5
    nginx.ingress.kubernetes.io/rewrite-target: /
    virtual-server.f5.com/balance: round-robin
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/ip: controller-default
    virtual-server.f5.com/partition: PARTITION_DIFFERENT_THAN_CONTROLLER
  name: myingress-1
  namespace: NAMESPACE
spec:
  rules:
  - host: www.hello-k8s-1.com
    http:
      paths:
      - backend:
          serviceName: hello-k8s
          servicePort: 80
        path: /
apiVersion: apps/v1
```kind: Deployment
metadata:
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: f5-ingress
  name: f5-ingress-f5-bigip-ctlr
  namespace: F5-NAMESPACE
spec:
  selector:
    matchLabels:
      app: f5-bigip-ctlr
  template:
    metadata:
      labels:
        app: f5-bigip-ctlr
        release: f5-ingress
    spec:
      containers:
      - args:
        - --bigip-username
        - $(BIGIP_USERNAME)
        - --bigip-password
        - $(BIGIP_PASSWORD)
        - --bigip-partition
        - ACC_KUBERNETES
        - --bigip-url
        - https://IP_ADDRESS
        - --insecure
        - "true"
        - --log-as3-response
        - "true"
        - --log-level
        - DEBUG
        - --pool-member-type
        - cluster
        - --agent
        - as3
        - --default-ingress-ip
        - IP-ADDRESS
        - --namespace
        - NAMESPACE
        - --manage-ingress
        - "true"
        - --manage-configmaps
        - "true"
        - --as3-validation
        - "false"
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: f5-bigip-ctlr-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: f5-bigip-ctlr-login
        image: PRIVATE-REPO/f5networks/k8s-bigip-ctlr:2.1.0
        imagePullPolicy: Always
        name: f5-bigip-ctlr
        ...
      volumes:
      - name: bigip-creds
        secret:
          defaultMode: 420
          secretName: f5-bigip-ctlr-login```

This are the only logs we can get from the CIS container

```51
2020/08/13 15:50:38 [DEBUG] [RESOURCE] Configured policy: {ingress_10-128-173-4_80 TENANT  [forwarding]  true [http] [0xc000345080] /Common/first-match}
2020/08/13 15:50:38 [DEBUG] [CORE] Found endpoints for backend {ServiceName:hello-k8s ServicePort:80 Namespace:cd-acc}: [{10.233.115.232 8080 user-enabled} {10.233.86.106 8080 user-enabled} {10.233.88.38 8080 user-enabled}]```

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
I believe this is the issue "virtual-server.f5.com/partition: PARTITION_DIFFERENT_THAN_CONTROLLER". - Checking if CIS will use PARTITION_DIFFERENT_THAN_CONTROLLER for Ingress. I do not believe so

**Comment by eduardoriveror** [comment]
With config maps it is stated in the docs, so i tried like that with ingress. Even though I have updated the ingress and it shows the same behaviour. 

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress-class: f5
    nginx.ingress.kubernetes.io/rewrite-target: /
    virtual-server.f5.com/balance: round-robin
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/ip: controller-default
    virtual-server.f5.com/partition: ACC_KUBERNETES
  name: myingress-1
  namespace: NAMESPACE
spec:
  rules:
  - host: www.hello-k8s-1.com
    http:
      paths:
      - backend:
          serviceName: nginx-test-f5
          servicePort: 80
        path: /```

**Comment by veeramalla-f5** [comment]
@eduardoriveror trying this now, I will get back to you shortly.

**Comment by veeramalla-f5** [comment]
@eduardoriveror I have tested the exact configuration in my cluster and it works well. 

Note: I haven't tried in combination with AS3 configmap. I think Ingress alone(without AS3 configmap) is also not working at your end.

**Comment by eduardoriveror** [comment]
Yes, if we apply an AS3 configmap with a service it works. Even though with ingress the F5 resources are not being created, on purpose i pointed the ingress to the same service linked to the AS3 configmap and the controlller recognize it and throws an error stating that the ip of the node in the pool exist in another virtual server

**Comment by veeramalla-f5** [comment]
In case of ingress , The controller default partition should be same as virtual-server.f5.com/partition: ACC_KUBERNETES.

Lets dig into the issue step by step by, 

For now, Please share all the error logs that you see when you deploy controller only with ingress resource... with No configmap resource in the cluster.

Please share the output of below command

kubectl log deploy/<controller-pod> -n kube-system | grep -i error

**Comment by eduardoriveror** [comment]
Yes of course. Basically is this, repeated a lot

```2020/08/14 17:01:50 [ERROR] [AS3] Response from BIG-IP: code: 200 --- tenant:Common --- message: no change
2020/08/14 17:01:50 [ERROR] [AS3] Response from BIG-IP: code: ERR_REQUEST_FAILED --- tenant:ACC_KUBERNETES --- message: declaration failed
2020/08/14 17:01:50 [ERROR] [AS3] Response from BIG-IP: code: 200 --- tenant:CD_ACC --- message: no change
2020/08/14 17:01:50 [ERROR] [AS3] Response from BIG-IP: code: 200 --- tenant:Common --- message: no change
2020/08/14 17:01:50 [ERROR] [AS3] Raw response from Big-IP: map[code:207 declaration:map[CD_ACC:map[class:Tenant defaultRouteDomain:463 nginx-test:map[class:Application serviceMain:map[class:Service_HTTP pool:web_pool virtualAddresses:[10.10.10.1]] template:http web_pool:map[class:Pool members:[map[serverAddresses:[10.233.110.184 10.233.86.155 10.233.89.53 10.233.98.250 10.233.99.125] servicePort:80]] monitors:[http]]]] class:ADC controls:map[archiveTimestamp:2020-08-14T17:01:50.605Z class:Controls userAgent:CIS/v2.1.0 K8S/v1.16.9] id:urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d label:CIS Declaration remark:Auto-generated by CIS schemaVersion:3.20.0 updateMode:selective] results:[map[code:200 host:localhost message:no change runTime:915 tenant:Common] map[code:ERR_REQUEST_FAILED host:localhost message:declaration failed response:POST http://admin:XXXXXX@localhost:8100/mgmt/tm/sys/config merge cli script response=400 body={"code":400,"message":"Loading configuration process failed.","errorStack":[],"apiError":26214401} runTime:678 tenant:ACC_KUBERNETES] map[code:200 host:localhost message:no change runTime:549 tenant:CD_ACC] map[code:200 host:localhost message:no change runTime:645 tenant:Common]]]
2020/08/14 17:01:50 [DEBUG] [AS3] Error handling for event statusCommonResponse
2020/08/14 17:02:16 [DEBUG] [AS3] Error handling for event
2020/08/14 17:02:16 [DEBUG] [AS3] Error handling for event
2020/08/14 17:02:17 [DEBUG] [AS3] Error handling for event```

**Comment by mdditt2000** [comment]
afternoon @eduardoriveror i finished recreating your issue and it works perfectly

```
[root@k8s-1-18-master 1461]# kubectl apply -f as3-configmap.yaml
configmap/as3-configmap configured
[root@k8s-1-18-master 1461]#

[root@k8s-1-18-master 1461]# kubectl create -f ingress-http.yaml
ingress.networking.k8s.io/f5-hello-world created
```

```
2020/08/20 19:49:32 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/08/20 19:49:35 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:Github-1461 --- message: success
2020/08/20 19:49:35 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s --- message: no change
2020/08/20 19:49:35 [DEBUG] [AS3] Preparing response message to response handler
2020/08/20 19:49:35 [DEBUG] [AS3] AppManager wrote endpoints to VxlanMgr
2020/08/20 19:49:35 [DEBUG] [AS3] Sent response message to response handler
2020/08/20 19:51:17 [DEBUG] [AS3] Posting AS3 Declaration
2020/08/20 19:51:17 [DEBUG] [AS3] posting request to https://192.168.200.92/mgmt/shared/appsvcs/declare/
2020/08/20 19:51:20 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:Github-1461 --- message: no change
2020/08/20 19:51:20 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s --- message: success
2020/08/20 19:51:20 [DEBUG] [AS3] Preparing response message to response handler
2020/08/20 19:51:20 [DEBUG] [AS3] AppManager wrote endpoints to VxlanMgr
2020/08/20 19:51:20 [DEBUG] [AS3] Sent response message to response handler
```

Please review the files i used

https://github.com/mdditt2000/kubernetes-1-18/tree/master/cis%202.1/github/1461

**Comment by eduardoriveror** [comment]
HI @mdditt2000 Sorry for the late response, short leave. 

I am checking the files in the repo and i spotted the only difference of you using flannel vxlan. We use calico and we set up BGP peering between all the nodes and the BIG-IP system itself. Is it possible for you to add the service file in your repo?

**Comment by eduardoriveror** [comment]
Is there a way to set the default route domain via ingress annotation or in the controller itself as a flag? What I see is that the ingress declaration fails with error 400 and is because a merge conflict with the default template as i see in this two errors:

```map[code:ERR_REQUEST_FAILED host:localhost message:declaration failed response:POST http://admin:XXXXXX@localhost:8100/mgmt/tm/sys/config merge cli script response=400 body={"code":400,"message":"Loading configuration process failed.","errorStack":[],"apiError":26214401} runTime:1473 tenant:ACC_KUBERNETES]```

```2020/08/24 09:37:40 [ERROR] [AS3] Response from BIG-IP: code: ERR_REQUEST_FAILED --- tenant:ACC_KUBERNETES --- message: declaration failed```

**Comment by mdditt2000** [comment]
@eduardoriveror so you aren't using the route domain of 0?

**Comment by mdditt2000** [comment]
@eduardoriveror please look at https://github.com/F5Networks/k8s-bigip-ctlr/issues/1287

You can add a system level configuration that will merge with the Ingress before sending to BIG-IP

```
For Route Domain support, can you try override AS3 ?

Example override AS3

apiVersion: v1
data:
  template: |
    {
        "declaration": {
            "test_AS3": {
                "defaultRouteDomain": 20              <== Refer Route domain ID existing in BIGIP
            }
        }
    }
kind: ConfigMap
metadata:
  labels:
    f5type: virtual-server
    overrideAS3: "true"
  name: override-as3-cm
  namespace: default
You need to delete the existing CIS managed partitions before applying or updating the Route Domain.
```

**Comment by eduardoriveror** [comment]
Hi @mdditt2000 For a working demo purpose, i solved it for now using cccl agent. Now I am able to create virtual servers with ingress, with a lot of things that i need to configure manually though. I will be testing the override config but if needed for now you can close this issue

Thanks a lot for the help

**Comment by iam-veeramalla** [comment]
@trinaths this was assigned to me .. please close this as I don't have permissions for the same :)
