### ISSUE TITLE
CIS AS3 does not support k8s services has multiple port

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1464]
#### Setup Details
 CIS Version : 2.1    
 Build: f5networks/k8s-bigip-ctlr:2.1       
 BIGIP Version: Big IP 14.1.0.5   
 AS3 Version: 3.19.1     
 Agent Mode: AS3    
 Orchestration: K8S 
 Orchestration Version:  v1.15.5      
 Pool Mode: Cluster

#### Description  

CIS AS3 does not support k8s services has multiple port.

The K8S service looks like

~~~
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cis.f5.com/as3-tenant: "cistest"
    cis.f5.com/as3-app: "cistest"
    cis.f5.com/as3-pool: "cistest_app_svc_pool"
  name: app-svc
  namespace: cistest
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  - port: 8081
    name: management
    protocol: TCP
    targetPort: 8081
  selector:
    app: app
  type: ClusterIP
~~~

The requirement is that expose 8080 via F5 CIS + AS3, but only 8081 can be expose.
  
#### Steps To Reproduce

1) Get the Code
~~~
git clone https://github.com/kylinsoong/container-ingress.git
cd container-ingress/f5-cis/as3/multiports
~~~

2) Deploy ap
~~~
kubectl apply -f backend.1464.yaml
~~~

this will deploy a app with 2 replicas, and 1 services expose 2 ports 8080 and 8081.

3) Deploy configmap(Assume CIS are set up correctly)
~~~
kubectl apply -f cm1464.yaml
~~~

4) check the pool member from F5, the pool member port always are 8081

Note that, though the servicePort in configmap is 8080
~~~
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
~~~

the pool member port is 8081, which is not expected, the expected is 8080

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@kylinsoong you will need to create two services exposing one port. Currently CIS only exposes one port per service. There are plans to resolve this in an upcoming release.

**Comment by mdditt2000** [comment]
Similar to https://github.com/F5Networks/k8s-bigip-ctlr/issues/1155

Internal PM Jira for tracking item in the backlog CONTCNTR-1651, CONTCNTR-539

**Comment by mdditt2000** [comment]
Created a new jira CONTCNTR-2079 for tracking. Target CRD enhancement

**Comment by mdditt2000** [comment]
SR C3361209 filed with Support

**Comment by kylinsoong** [comment]
@mdditt2000 Thanks mark.

**Comment by mdditt2000** [comment]
@kylinsoong please note the CRD work is complete for CIS to handle multiple ports on a service. Here is an example https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/_static/config_examples/crd/MultiPortServices

Something to consider

**Comment by mdditt2000** [comment]
New Jira for CONTCNTR-2181 - Configmap to support multiple service ports

**Comment by mdditt2000** [comment]
Added to Sprint 51. @agupta49 coding the feature.

**Comment by mdditt2000** [comment]
Please note: current design only supports one ConfigMap with one service because of labels used for service discovery on service. However with multiport support CIS will pick up the serviceport defined in configmap and will add the same as pool members. Same service cannot be used for multiple ConfigMaps according to CIS design. CRD don't have this issue as labels are not used for service discovery.  This will be documented in clouddocs as a limitation.

**Comment by mdditt2000** [comment]
Closing issue - Only documentation task is required. New Jire is opened for that.

**Comment by kylinsoong** [comment]
Hey Guys

It's quite a long time since we talk this issue last time, hoping you doing well.

After some investigating of this enhance, I have found that the enhance not resolve multi-port service ingress via 1 svc and 1 as3 template simultaneous, 2 template is necessary. Also this bring backwards compatible issue, In Previous version, the `servicePort ` is optional, but in later version `servicePort `is mandatory, which cause upgrade issue.

**Could you help to re-investigate, that made the `servicePort ` is optional? so the basic logic is：if the `servicePort ` match the `targetPort` then use the current logic, or else, keep the previous logic?**

Many Thanks

Kylin

**Comment by kylinsoong** [comment]
@mdditt2000 I have just reviewed your notes in Nov 12, 2020, I will forward the documented limitation to customer, at the moment ,could you have a look at for **Backwards incompatible issue**, may thanks.

**Comment by trinaths** [comment]
PR https://github.com/F5Networks/k8s-bigip-ctlr/pull/1564/files
