### ISSUE TITLE
Two instance of kubernetes application/service share the same F5 appliance

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1465]
#### Setup Details
CIS Version : 2.1.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 2.1.0
AS3 Version: 3.x
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.16.0
Pool Mode: Nodeport
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  

I have the below scenario. However I don't know if it is going to work or not.

1) there has only one kubernetes cluster
2) the same application was deployed in different kubernetes namespace and the services were using the different nodeport
   i.e. namespace1, nodeport1 & namespace2, nodeport2
3) Plan to create two kubernetes partitions for CIS on F5 UI, i.e. env1_partition & env2_partition
4) Plan to deploy two F5 Ingress Controllers in kubernetes cluster using NodePort member type
   The only difference for these two controllers are partitions, i.e. env1_partition & env2_partition
5) Deploy Ingress resource in two kubernetes namespaces with different virtual server IP in F5 appliance to manage its own backend service
   i.e.  namespace1, vip1  &  namespace2, vip2

For the above step 4), I am wondering that it may not work for the second deployment cause it may complain the duplication IP address from F5 to kubernetes host IPs.

Could anyone see if above approach is feasible or any suggestions if F5 appliance to be reused?  

Or from above steps 3) and 4), we change them to
3') Plan to create one kubernetes partition for CIS on F5 UI, i.e. env_shared_partition
4') Plan to deploy one F5 Ingress Controller in kubernetes cluster using NodePort member type and above shared partition
That sounds more promising to me.

Thanks

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Good morning @zhu20200720 

You above scenario will work fine. Please note the following:

- Use CIS 2.1 and specify the corresponding namespace env1_partition in the CIS arguments. Each CIS will monitor a unique namespace. 
- You cannot share services across both namespaces env1_partition, env2_partition. Create unique services. 
- Please make sure the base partition in the CIS arguments are unique. The partition could match the namespace name
- Recommend you use unique pool members and Virtual IP. If not please let me know so i can provide some guidance on how to achieve re-using pools, pool members across  env1_partition, env2_partition
- For better performance please configure postdelay. Postdelay will help scale the API between CIS and BIG-IP as you declaring updates 2X. Maybe configure postdelay=120 https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html#as3-parameters
- Please increase the mgmt memory on BIG-IP to 1000 https://github.com/mdditt2000/openshift-3-11/blob/master/openshift-faq.md#restjavad-memory-recommendation-using-cis-and-as3

**Comment by zhu20200720** [comment]
Thank you @mdditt2000 , I didn't know we could specify --namespace in CIS arguments before. We will create env1_namespace and env2_namespace for applications. For partitions, we will ask F5 team to create env1_partition, env2_partition. If my understanding is correct, if I specify **--namespace**, **--bigip-partition** separately, the two ingress controllers are able to use/share the same **--bigip-url**. 

We did have two Virtual IPs in each Ingress resource for two namespaces.

For the unique services part, I didn't really get it.  I thought the service was in different namespace, if we used different nodeport between two namespace, F5 should be able to route traffic to hostip:nodeport if we used Pool Mode: Nodeport.

**Comment by mdditt2000** [comment]
@zhu20200720 specify the --namespace in CIS arguments that you want CIS to monitor. This would be the same namespace defined in the service/pods that CIS is providing Ingress. 

Correct. As the BIG-IP team to create the two partition
1) env1_partition
2) env2_partition

You CIS configuration will look something like this for CIS 1
```
args: 
            - "--bigip-username=$(BIGIP_USERNAME)"
            - "--bigip-password=$(BIGIP_PASSWORD)"
            - "--bigip-url=192.168.200.92"
            - "--bigip-partition= env1_partition"
            - "--namespace=default" ------------------- Your service/pods namespace that CIS is monitoring. It could be the same as the tenant on BIG-IP env1_partition"
            - "--flannel-name=fl-vxlan"
            - "--insecure=true"
            - "--manage-ingress=true"
            - "--as3-validation=true"
```
CIS 2

```
args: 
            - "--bigip-username=$(BIGIP_USERNAME)"
            - "--bigip-password=$(BIGIP_PASSWORD)"
            - "--bigip-url=192.168.200.92"
            - "--bigip-partition= env2_partition"
            - "--namespace=default" ------------------- Your service/pods namespace that CIS is monitoring. It could be the same as the tenant on BIG-IP env2_partition"
            - "--pool-member-type=nodeport"
            - "--insecure=true"
            - "--manage-ingress=true"
            - "--as3-validation=true"
```

**Comment by mdditt2000** [comment]
Closing out
