### ISSUE TITLE
docs only mention OCP 3.11

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#1485]
#### Description  
  
Docs only mention OCP 3.11 and can only find mention of 4.x in release notes.

https://clouddocs.f5.com/containers/latest/userguide/openshift/

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@chen23 I will get this resolved. The support matrix is updated. https://clouddocs.f5.com/containers/latest/userguide/what-is.html#releases-and-versioning

TY for filing this!

**Comment by mdditt2000** [comment]
Internal PM Jira CONTCNTR-2154 for tracking

**Comment by mdditt2000** [comment]
thanks @vtrippel - Issue updated 
See the Releases and Versioning matrix for supported versions of CIS, OCP, AS3, and BIG-IP.
