### ISSUE TITLE
VIP name not same as configured in CRD

### ISSUE THREAD

**Issue by YacovNagose** [F5Networks/k8s-bigip-ctlr#1496]
#### Setup Details
 CIS Version : 2.0   
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP1.13.1.5      
 AS3 Version: 3.19.1     
 Agent Mode: AS3       
 Orchestration: K8S 
 Orchestration Version: 1.17      
 Pool Mode: Nodeport      
 Additional Setup details: Calico

#### Description  

The VIP name isn't the same as configured in the CRD, it creates a name that starts with 
crd_Ip address

#### Steps To Reproduce

Create a VIP using CRD and the VIP name will be "crd" and the Ip address of the VIP instead of the name configured in the CRD.

e.g:
crd_10_82_45_241_80
crd_10_82_45_241_81

#### Expected Result 
 VIP with the name configured in the CRD

#### Actual Result  

crd_10_82_45_241_80

**Comment by mdditt2000** [comment]
Added to the next development sprint as CONTCNTR-2128

**Comment by YacovNagose** [comment]
Thank you.
בברכה,
יעקב.

**Comment by mdditt2000** [comment]
Enhancement is completed. I will provide you with a intergrated build in a few days.

**Comment by YacovNagose** [comment]
Thank you, Mark!
