### ISSUE TITLE
Node Selector for CIS

### ISSUE THREAD

**Issue by renatonader** [F5Networks/k8s-bigip-ctlr#1499]
#### Title
nodeSelector for CIS

#### Description
It would be great if it was possible to choose the node where the CIS would run using nodeSelector to assign CIS to a specific node.

#### Actual Problem
We can't select on which node will CIS run.

#### Solution Proposed
Use something like nodeSelector to assign a specific node to CIS.
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by trinaths** [comment]
In the CIS deployment spec add `nodeSelector` to the pod template. @renatonader  No update for CIS is required. 

closing this issue.
