### ISSUE TITLE
openshift docs user guide (do not need to setup RBAC when using operator)

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#1503]
## Description  

The user guide describes setting up RBAC, but when using the operator you do not need to setup RBAC.

**Comment by nmenant** [comment]
Hi Eric,

https://clouddocs.f5.com/containers/latest/userguide/openshift/#how-to-deploy-cis-using-openshift
We don't expand on setting up RBAC when using operator. 

@mdditt2000 - could you close the case ?

**Comment by mdditt2000** [comment]
@nmenant @chen23 need to double check with @vklohiya if we need to make any modification based on his latest updates coming in CONTCNTR-2091

**Comment by chen23** [comment]
I'm still seeing RBAC on the following page: https://clouddocs.f5.com/containers/latest/userguide/openshift/#configuring-and-deploying-cis, maybe there needs to be a warning to say "If you are using OpenShift 4 skip to the operator section" ?

**Comment by trinaths** [comment]
Operator document updated. Please see - https://clouddocs.f5.com/containers/latest/userguide/openshift/#installing-cis-using-operators-on-openshift-cluster 
closing this issue.
