### ISSUE TITLE
How to set "Action On Service Down" for service

### ISSUE THREAD

**Issue by liuyuan10** [F5Networks/k8s-bigip-ctlr#1504]
#### Title
How to set "Action On Service Down" for service

#### Description
Some service requires "Action On Service Down" set to "reject". Is there a way to set it through the k8s bigip controller. AFAIK, it doesn't.

#### Actual Problem
We are fine if we can simply set it through F5 management UI manually. But we notice that during k8s cluster upgrade, where all pods and nodes are reloaded, the "Action On Service Down" get reverted back to "none". Does anyone have an explanation? During other time, seems like k8s bigip controller is able to preserve the option.

#### Solution Proposed
Either have k8s bigip controlle to support setting this option or providing a workaround to set it manually without being overwritten.

#### Alternatives
n/a

#### Additional context
We are using v1.14.0

**Comment by anfernee** [comment]
cc @memes

**Comment by mdditt2000** [comment]
Please look at Github https://github.com/F5Networks/k8s-bigip-ctlr/issues/1510

I provided the following AS3 override for Action On Service Down" set to "drop"

An AS3 override can be applied to either an Ingress or OpenShift Route. 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-override
  namespace: default
  labels:
    f5type: virtual-server
    overrideAS3: "true"  # set to true to process this configMap. For staging set to false.
data:
  template: |
    {
        "declaration": {
            "k8s": {
                "Shared": {
                    "ingress_10_192_75_108_80": {
                        "profileTrafficLog": {
                            "bigip": "/Common/Shared/telemetry_traffic_log_profile"
                        },
                        "persistenceMethods": [],
                        "serviceDownImmediateAction": "drop"
                    }
                }
            }
        }
    }
```
example can be located on my repo at https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/github/1510/as3-override.yaml

You can remove the persistence and logging from the Json. You only need "serviceDownImmediateAction": "drop".

AS3 override is very well documented at https://clouddocs.f5.com/containers/latest/userguide/config-map.html#create-override-as3-configmap

**Comment by liuyuan10** [comment]
Thanks for the reply. We are not using the AS3 schema but the old "bigip-virtual-server_v0.1.7.json". I know AS3 support it. But with old schema, is there a possible way to workaround? I notice that the bigip controller will remove all the virtual servers  if restarts and it can't connect to api server. Is there a way to tell it to wait for a successful connection to api server before flushing the configs?

**Comment by mdditt2000** [comment]
We have no plans to expand the old bigip-virtual-server_v0.1.7.json schema. CCCL shouldn't be flushing the configurations. Are you using the HTTP iApp?

**Comment by liuyuan10** [comment]
No, we are not using HTTP iapp. I can reproduce it by cutting off connection to api server and restart the pod.

**Comment by mdditt2000** [comment]
@liuyuan10 can you please start looking at CIS 2.2 using CRDs. We have no plans expanding support around iApp.
