### ISSUE TITLE
[Log] 400 Unexpected Error: Bad Request for uri

### ISSUE THREAD

**Issue by vtog** [F5Networks/k8s-bigip-ctlr#1508]
#### Setup Details
 CIS Version : 2.1.1  
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.20      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
Seeing yucky error in logs not affecting deployment.

#### Steps To Reproduce
1) Setup clusterip mode w/ flannel vxlan
2)
3)

#### Diagnostic Information
2020/09/16 16:28:21 [ERROR] [2020-09-16 16:28:21,838 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.1.1.4:8443/mgmt/tm/net/fdb/tunnel/~Common~k8s-tunnel/?ver=11.5.0
2020/09/16 16:28:21 [INFO] Text: '{"code":400,"message":"enter a valid option","errorStack":[],"apiError":26214401}'
2020/09/16 16:28:21 [ERROR] [2020-09-16 16:28:21,838 f5_cccl.service.manager ERROR] Resource /Common/k8s-tunnel delete error, requeuing task...
2020/09/16 16:28:21 [ERROR] [2020-09-16 16:28:21,838 __main__ ERROR] Error applying config, will try again in 16 seconds
2020/09/16 16:28:31 [INFO] [2020-09-16 16:28:31,990 f5_cccl.resource.resource INFO] Updating ApiFDBTunnel: /Common/k8s-tunnel
2020/09/16 16:28:32 [INFO] [2020-09-16 16:28:32,041 f5_cccl.resource.resource INFO] Deleting IcrFDBTunnel: /Common/k8s-tunnel
2020/09/16 16:28:32 [ERROR] [2020-09-16 16:28:32,062 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrFDBTunnel) /Common/k8s-tunnel.

**Comment by mdditt2000** [comment]
Internal Jira issue CONTCNTR-2146 for PM tracking

**Comment by mdditt2000** [comment]
@vtog what was the version of BIG-IP?

**Comment by vtog** [comment]
> @vtog what was the version of BIG-IP?

15.0.1-0.0.11

**Comment by srivastavnitin24** [comment]
Hi @vtog, can you please share the steps to reproduce the mentioned logs where are you encountering 400 Unexpected Error: Bad Request for URI.

**Comment by vtog** [comment]
> Hi @vtog, can you please share the steps to reproduce the mentioned logs where are you encountering 400 Unexpected Error: Bad Request for URI.

We see this in our Agility lab, you can find the lab/steps here:
https://clouddocs.f5.com/training/community/containers/html/class1/module2/lab1.html

As you can see at the bottom we let the student know by calling out the error.

**Comment by mdditt2000** [comment]
hello @vtog 

Please can you change the CIS argument

The vxlan config created in the common partition should mention the complete flannel-name including the partition.

--flannel-name=/Common/k8s-tunnel

**Comment by vtog** [comment]
The full path made no difference, same yucky log messages.

[yuck.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/5403067/yuck.txt)

**Comment by mdditt2000** [comment]
@srivastavnitin24 we are still seeing the error when using the full path

0/10/19 15:39:03 [ERROR] [2020-10-19 15:39:03,378 f5_cccl.service.manager ERROR] Resource /Common/k8s-tunnel delete error, requeuing task...
2020/10/19 15:39:03 [ERROR] [2020-10-19 15:39:03,378 __main__ ERROR] Error applying config, will try again in 4 seconds
2020/10/19 15:39:10 [INFO] [2020-10-19 15:39:10,952 f5_cccl.resource.resource INFO] Deleting IcrFDBTunnel: /Common/k8s-tunnel
2020/10/19 15:39:11 [ERROR] [2020-10-19 15:39:11,462 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrFDBTunnel) /Common/k8s-tunnel.
2020/10/19 15:39:11 [ERROR] [2020-10-19 15:39:11,462 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.1.1.4:8443/mgmt/tm/net/fdb/tunnel/~Common~k8s-tunnel/?ver=11.5.0

**Comment by mdditt2000** [comment]
@trinaths can we re-visit this issue in CIS 2.4.1?

**Comment by trinaths** [comment]
Is this issue with https://support.f5.com/csp/article/K45708931 ? @vtog can you check as per the support suggestions.

**Comment by vtog** [comment]
> Is this issue with https://support.f5.com/csp/article/K45708931 ? @vtog can you check as per the support suggestions.

This is not the issue. "bigstart restart restjavad" has no affect on the bad log messages.  Keep in mind we see these log messages with a clean install, and no config.  Simply starting CIS with BIGIP and we see this. The issue can be seen/duped by running the Agility Container Lab in UDF. Every 2m the ERROR logs.

**Comment by trinaths** [comment]
created CONTCNTR-2508 for internal tracking.

**Comment by trinaths** [comment]
VXLAN tunnel name starting with prefix "k8s" is not supported.CIS uses prefix "k8s" to differentiate managed and user created resources. Please rename the vxlan tunnel name and the issue will be resolved. closing this issue.

**Comment by vtog** [comment]
Thanks, I'll test this out in our lab.  Is this documented anywhere?

**Comment by trinaths** [comment]
https://clouddocs.f5.com/containers/latest/reference/faq.html check 4 question 3rd point.

**Comment by vtog** [comment]
> https://clouddocs.f5.com/containers/latest/reference/faq.html check 4 question 3rd point.

Thanks... I did confirm on the Agility lab by removing the "k8s" prefix in my naming did indeed resolve the issue.
