### ISSUE TITLE
Mapping arguments in CIS or Ingress for virtual server configurations 

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1510]
#### Setup Details
CIS Version : 2.1.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 2.1.0
AS3 Version: 3.x
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.18.8
Pool Mode: Nodeport
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  

We want to change a few setting for virtual server, the following screenshots captured what we want to change:
1) Default Persistence Profile
2) Request Logging Profile
3) Immediate Action on Service Down

We don't want or can't change above items from management UI because those will be overridden on the fly by Ingress Controller which monitors the Ingress resource. So are there corresponding settings available in either Ingress Controller or Ingress Resource to set above configurations beforehand?

Or if NOT, are there any corresponding global settings in F5 management UI which could propagate the required changes to the virtual servers not to be overridden?

![image](https://user-images.githubusercontent.com/68562586/93525246-ba0f3b80-f903-11ea-84ca-94885c596f06.png)
![image](https://user-images.githubusercontent.com/68562586/93525338-df9c4500-f903-11ea-80fa-0e80dfa2e743.png)

Thanks,
Mr Zhu

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by mdditt2000** [comment]
@zhu20200720 good afternoon. By using AS3 ConfigMap Override you can change a few setting for the virtual server

Here are the documentation https://clouddocs.f5.com/containers/latest/userguide/config-map.html#override-as3-configmap
Here are some example https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/_static/config_examples/configmap/override-configmap

---
For non-persistence please use
```
"persistenceMethods": [],
```
---
 For 
```
"profileTrafficLog": {
    "use": "/Common/Shared/telemetry_traffic_log_profile"
},
```
I am looking into the last option. "Immediate Action on Service"

**Comment by mdditt2000** [comment]
@zhu20200720 Regarding the last option

**serviceDownImmediateAction** (string) | “none” | “none”, “drop”, “reset” | 

Specifies the immediate action the BIG-IP system should respond with upon the receipt of the initial client’s SYN packet if the availability status of the virtual server is Offline or Unavailable. This is supported for the virtual server of Standard type and TCP protocol. **The default value is none**

What value to you want to change?

**Comment by zhu20200720** [comment]
@mdditt2000 , we want to set to 'drop'

**Comment by mdditt2000** [comment]
@zhu20200720 here is the as3 override that you need. 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-override
  namespace: default
  labels:
    f5type: virtual-server
    overrideAS3: "true"  # set to true to process this configMap. For staging set to false.
data:
  template: |
    {
        "declaration": {
            "k8s": {
                "Shared": {
                    "ingress_10_192_75_108_80": {
                        "profileTrafficLog": {
                            "bigip": "/Common/Shared/telemetry_traffic_log_profile"
                        },
                        "persistenceMethods": [],
                        "serviceDownImmediateAction": "drop"
                    }
                }
            }
        }
    }
```
You can copy the files from https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/github/1510/as3-override.yaml

Controller argument https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/github/1510/f5-cluster-deployment.yaml

Please note i used Telemetry streaming to configure the logging. Here you can find the TS json https://github.com/mdditt2000/telemetry-streaming/blob/master/sumo-logic/sumo-logic-as3.json

Picture from BIG-IP

![image](https://user-images.githubusercontent.com/12733938/93948593-b6a8f500-fcf3-11ea-8294-94e9866fc4ad.png)

**Comment by mdditt2000** [comment]
Example provided for AS3 override. Github issue can be closed.
