### ISSUE TITLE
Ingress controller pod log with Responded with code: 422 and complained the service not found 

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1517]
#### Setup Details
 CIS Version : 2.1.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 2.1.0
AS3 Version: 3.x
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.16.0
Pool Mode: Nodeport
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
1) We deployed a service in **kube-system** namespce to expose kube state metrics like below
![image](https://user-images.githubusercontent.com/68562586/94210392-97010080-fe9c-11ea-89bb-1a73966645bd.png)

2) The service exposing is good, we are able to use curl to retrieve the kube state metrics

3) We deployed the Ingress Controller to monitor the **kube-system** namespace
![image](https://user-images.githubusercontent.com/68562586/94210828-d3812c00-fe9d-11ea-85c8-1072dc85a141.png)

4) We deployed the Ingress resource in **kube-system** namespace for backend service already exposed for accessing kube state metrics from outside
![image](https://user-images.githubusercontent.com/68562586/94211178-ba2caf80-fe9e-11ea-973c-e89d32a32b8b.png)

5) However we got error log from Ingress controller pod which complained Responded with code: 422 and complained the service not found like below
![image](https://user-images.githubusercontent.com/68562586/94211734-52776400-fea0-11ea-8d7a-ad4a352c3c9e.png)

We are stuck and cannot figure out what the problem is. Could anyone know if we are missing something to get F5 CIS working properly?

Thanks,
Mr Zhu 

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by mdditt2000** [comment]
@zhu20200720 please can you upload the yaml files. I cannot pictures

**Comment by zhu20200720** [comment]
@mdditt2000, seemed only one Ingress controller is working per one f5 host, otherwise multiple controllers lead to confusion for f5 as the cluster nodes IPs are the same. I submitted an issue before https://github.com/F5Networks/k8s-bigip-ctlr/issues/1465, unfortunately it was not working as expected. We changed the design to use only one Ingress controller, so you can close this issue.

**Comment by mdditt2000** [comment]
@zhu20200720 you can use multiple ingress controller per host but we need to follow some best practices. Each CIS  ingress controller needs to subscribe to a unique namespace so there is no nodes IPs conflicts. But AS3 can share common objects. Using one CIS is per F5 scales the best! I will close issue #1465

**Comment by zhu20200720** [comment]
@mdditt2000 , we did split the namespace in k8s cluster as well as in Ingress controller, however the issue was that we used the same k8s cluster to deploy multiple Ingress controllers to same f5 host. You can close this ticket as we already updated design to use only one Ingress controller in k8s cluster per f5 host.

**Comment by mdditt2000** [comment]
Closing this Github issue. Issue has been resolved.
