### ISSUE TITLE
The Pool cannot be deleted because it is in use by a policy action

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1520]
#### Setup Details
CIS Version : 2.1.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 2.1.0
AS3 Version: 3.x
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.18.8
Pool Mode: Nodeport
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  

In summary, we used F5 cis to monitor multiple Ingress resource.
For the application ingress alone, it is working properly; After we applied the second ingress, the expected output will be a new vip to be created by the ingress in partition my-cluster, but we see nothing in F5 UI.
We observed some errors in pod log of the k8s cis controller.
![image](https://user-images.githubusercontent.com/68562586/94860754-80aaf580-0404-11eb-97f3-73b073044ff1.png)

Actually we have multiple envs to have above implemented, only got issues in one environment. There has no difference from CIS side between working env and non-working env. They used different partition and different vip. The only thing seemed weird to us is we observed the working one has "/Shared" appended in the path for the published policy. 

![image](https://user-images.githubusercontent.com/68562586/94861283-40984280-0405-11eb-8cad-d716b6acdba9.png)

 
![image](https://user-images.githubusercontent.com/68562586/94861068-f020e500-0404-11eb-95f2-6680769a2fcb.png)
 
We did some research and found this https://support.f5.com/csp/article/K15335. I am wondering if that is causing the issue.

Thanks,
Mr Zhu

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by mdditt2000** [comment]
@zhu20200720 Thank you for creating SR C3394545. Ene will help you via the SR

**Comment by mdditt2000** [comment]
@zhu20200720 "/Shared" is correct. Maybe something with the fanout. I request support to provide me the Ingress resources so that i can reproduce this issue.

**Comment by zhu20200720** [comment]
@mdditt2000 , the non-working one doesn't have /Shared in the path for the published policy. And yes, you can get all the files related to #C3394545 from the support.

**Comment by mdditt2000** [comment]
@zhu20200720 requested from Support. Awaiting a response. Thanks!

**Comment by mdditt2000** [comment]
Objects on BIG-IP needed to be removed and recreated with AS3. Objects were not originally created via AS3. Once we removed the virtual and recreated the ingress everything was resolved. Closing issue out.
