### ISSUE TITLE
generic template and serviceMain

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1522]
#### Setup Details
 CIS Version : 2.1.1
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 14.1.0.1.0.0.7
AS3 Version: 3.22.1
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: v1.18.6
Pool Mode: Nodeport

#### Description  

 When deploying a configmap with generic template and using Service_TCP, as3 validation fails with:
```
2020/10/02 07:33:11 [ERROR] [AS3] Template is not valid. see errors
2020/10/02 07:33:11 [ERROR] - declaration: Must validate "then" as "if" was valid

2020/10/02 07:33:11 [ERROR] - declaration.serviceMain.class: declaration.serviceMain.class does not match: "Service_Generic"

2020/10/02 07:33:11 [ERROR] - declaration: Must validate all the schemas (allOf)

2020/10/02 07:33:11 [ERROR] [AS3] Error validating AS3 template
2020/10/02 07:33:11 [ERROR] [AS3] Error in processing the ConfigMap: kube-system/as3-declaration
```

#### Steps To Reproduce
1) Deploy configmap
2) Check logs
3) Confirm error

#### Expected Result 

TCP virtual server is deployed

#### Actual Result  

AS3 validation error

#### Diagnostic Information

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html
FAQ says "The generic template does not have or enforce any content requirements, so there is no requirement for naming the virtual service serviceMain."

Which means to me that it could potentially take "serviceMain", but in actuality, it doesn't. 
Need document to be more explicit by saying "serviceMain" cannot be used as a name when using generic template.  

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    as3: "true"
    f5type: virtual-server
  name: as3-declaration
  namespace: kube-system
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.21.0",
        "id": "app1",
        "label": "f5",
        "remark": "An HTTP application",
        "sandbox1": {
          "class": "Tenant",
          "sandbox1_app": {
            "class": "Application",
            "template": "generic",
            "serviceMain": {
              "class": "Service_TCP",
              "virtualAddresses": [
               {
                "use": "sandbox1_addr"
               }
               ],
               "virtualPort": 25,
              "pool": "sandbox1_pool1"
            },                                            
            "sandbox1_addr": {
                "class": "Service_Address",
                "virtualAddress": "240b:a:b:c:d::1",
                "trafficGroup": "/Common/traffic-group-1"
            },
            "sandbox1_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [{
                "servicePort": 80,
                "serverAddresses": [],
                "shareNodes": true
              }]
            }
            }
          }
        }
      }

```

**Comment by mdditt2000** [comment]
@tkam8 please look at the following example https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.1/as3-configmap/vzn/as3-tcp-config.yaml

Don't need servicemain with template generic. AS3 will fail.

**Comment by tkam8** [comment]
@mdditt2000 yes, that part is clearly documented. What I am raising is that there is a requirement that serviceMain cannot be used when using template generic, which is in a way a requirement. 
Consider the case that the user is copying and pasting declarations/manifest files where they change just the template type, but leave serviceMain as the name. This will fail, and may not be immediately clear to the user. 

This request is just to add a short statement that when template generic is used, serviceMain **cannot** be used.

**Comment by mdditt2000** [comment]
CIS doesn't use servicemain for its template. CIS cannot, nor prevent a user defined configmap from using servicemain. As servicemain is a correct AS3 deployment options
