### ISSUE TITLE
[Doc][CRD] fix examples for TLSProfile

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1524]
#### Setup Details
CIS Version : 2.1.1
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 14.1.0.1.0.0.7
AS3 Version: 3.22.1
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: v1.18.6
Pool Mode: Nodeport

#### Description  

Example for TLSProfile is misleadingly using the /common partition. Should be capital "C"   /Common. 

Please fix docs. 

#### Steps To Reproduce
1) Deploy with /common
2) note error in as3 logs
3)

#### Expected Result 

Doc should have correct examples to prevent user confusion

#### Actual Result  

Error
```
2020/10/04 14:37:59 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: message:Unable to find /common/clientssl for /k8s/Shared/crd_10_10_20_100_443/serverTLS]
2020/10/04 14:38:30 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: message:Unable to find /common/clientssl for /k8s/Shared/crd_10_10_20_100_443/serverTLS]
```

#### Diagnostic Information
```buildoutcfg
 apiVersion: cis.f5.com/v1
 kind: TLSProfile
 metadata:
   name: reencrypt-tls
   labels:
     f5cr: "true"
 spec:
   tls:
     termination: reencrypt
     clientSSL: /common/clientssl
     serverSSL: /common/serverssl
     reference: bigip             # --> reference profiles created in BIG-IP by User
   hosts:
   - coffee.example.com
```

**Comment by mdditt2000** [comment]
Added to the documentation list of items to address for CIS 2.2 release

**Comment by mdditt2000** [comment]
Example is correct

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/tls/reencrypt-bigip-reference/reencrypt-tls.yml

Closing issue out

**Comment by jmcalalang** [comment]
Add to this, the documentation is broken, but if you go back to the same TLSProfile and update it, the update is ignored. you have to delete the resource and then re-create it to get it to fix.

**Comment by tkam8** [comment]
@mdditt2000  Please re-open this. Clouddocs documentation is not fixed. The link showing the issue is clouddocs, not the yaml file in repo, thanks!:

https://clouddocs.f5.com/containers/latest/userguide/crd.html#tlsprofile
