### ISSUE TITLE
[Doc][CRD] Clarify TLSProfile reference parameter

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1525]
#### Setup Details
CIS Version : 2.1.1
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 14.1.0.1.0.0.7
AS3 Version: 3.22.1
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: v1.18.6
Pool Mode: Nodeport

#### Description  
 
Documentation for the TLSProfile "reference" parameter is insufficient. 
Need to include the valid strings accepted for this parameter to avoid user confusion. Examples show correct definition, but need it in the document table too:
https://clouddocs.f5.com/containers/latest/userguide/crd.html#id2

Suggesting to add below sentence to the description for the "reference" parameter:

"Use the string  `bigip` to indicate the SSL profiles exists on BIG-IP"

**Comment by mdditt2000** [comment]
Multiple meaningful logs were removed in 2.0 due to a possible performance issue. Over time we are  adding them back logs back. In this case i like to see when a service is discovered. 

- PO action "create a Jira for 2.2.1 release to add meaningful log back and validate to make sure no performance impact is created"

**Comment by mdditt2000** [comment]
Added to documentation Sync Up for 2.2.0. Documentation update is required as we now have support for secrets.

**Comment by mdditt2000** [comment]
thank you @vtrippel. closing issue Live here: https://clouddocs.f5.com/containers/latest/userguide/crd.html#tlsprofile-components

**Comment by tkam8** [comment]
Please confirm what was changed, I still don't see a reference showing valid strings accepted for the reference parameter. Thank you. 
here's what I see:
`Describes the location of profile, BIG-IP, or k8s Secrets. CIS currently supports BIG-IP and secret references.`

**Comment by mdditt2000** [comment]
@tkam8 the only two options are reference: bigip and secret. You either using cert from bigip or secrets. Those are the only combinations.

**Comment by vtrippel** [comment]
Thank you for the feedback @tkam8 I will reword it so it's clearer what the two options are.
