### ISSUE TITLE
Calico VXLAN for Cluster Mode

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#1533]
#### Title
Calico VXLAN for Cluster Mode

#### Description
Today we run our clusters using Calico in VXLAN mode. Looking at the documentation it only shows flannel is supported for cluster mode using VXLAN.

#### Actual Problem
Is calico VXLAN mode supported. If so can documentation be added on how to set it up and if not can support be added so we can use cluster mode using calico VXLAN?

#### Solution Proposed
Documentation or actual enhancement to support calico VXLAN

**Comment by mdditt2000** [comment]
@mitchellmaler at this time we have no documentation on calico VXLAN. Our focus for the next few months is OVN K8S using VXLAN to support the changes in OpenShift 4.5/4.6. 

Honestly i think this should work fine. Have you tried to configure the function?
