### ISSUE TITLE
CIS/AS3 is unable to redirect traffic to different pool associated with different service

### ISSUE THREAD

**Issue by auto2mate** [F5Networks/k8s-bigip-ctlr#1544]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:2.1.1    
 BIGIP Version: 14.1.2.7 Build 0.0.5    
 AS3 Version: 3.18.0            
 Pool Mode: Cluster    

#### Description  

I am running this CIS/configmap in GCP GKE environment

I am trying to configure single virtual server with multiple pool (each gke service will have one pool) and redirect the traffic based on URI.

For example if the user types abc.comL/test --> send traffic to pool A and if use types abc.com/ --> send traffic to pool B

I am getting error when I try to refer to other pool from the irule, 

Error - unable to find the pool

Rule [/testdev/service2/irule1] error: Unable to find pool ('service1pool') referenced at line 5: [pool 'service1pool'] runTime:1520 tenant:testdev] map[code:200 host:localhost message:no change runTime:990 tenant:kubernetes]]] 
  
#### Steps To Reproduce

---------config map------

kind: ConfigMap
apiVersion: v1
metadata:
  name: uriredirect
  namespace: testdev
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "https",
            "remark": "Configmap Template",
            "testdev": {
                "class": "Tenant",
                "service1": {
                    "class": "Application",
                    "template": "generic",
                    "service1pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 8000,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "service2": {
                    "class": "Application",
                    "template": "generic",
                    "service2-vs": {
                        "class": "Service_HTTPS",
                        "virtualAddresses": [
                            "10.10.10.1"
                        ],
                        "serverTLS": {
                        "bigip": "/Common/service2cert"
                        },
                        "iRules": [ 
                            "irule1" 
                        ],
                        "redirect80": false,
                        "pool": "service2pool"
                    },
                    "irule1": {
                      "class": "iRule",
                      "iRule": "when HTTP_REQUEST {\n set uri [string tolower [HTTP::path]] \nswitch -glob $uri {\n '/test' {\npool 'service1pool'\n} \ndefault {\npool 'service2pool'\n} \n} \n}"
                    },
                    "service2pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 8000,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }

#### Expected Result 

Traffic should be redirected to different pool based on URI

#### Actual Result  

Unable to find pool 'service1pool'

#### Diagnostic Information

Rule [/testdev/service1/irule1] error: Unable to find pool ('service1pool') referenced at line 5: [pool 'service1pool'] runTime:1520 tenant:testdev] map[code:200 host:localhost message:no change runTime:990 tenant:kubernetes]]] 

#### Observations (if any)

If I remove the irule, it can create the two pool but I am unable to redirect the traffic to different pool due unavailability of rule

**Comment by mdditt2000** [comment]
Recommend to use CRD with https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/tls/reencrypt-bigip-reference/virtualserver.yml

Product Owner Action Item

- Need to validate CRD on GCP for CIS 2.2

**Comment by mdditt2000** [comment]
Please make sure you follow the recreate on GKE https://github.com/mdditt2000/gke/tree/master/cis%202.2/crd/big-ip-cluster

**Comment by mdditt2000** [comment]
Recommend using fanout with CRD. Provided working example for GKE. https://github.com/mdditt2000/gke/tree/master/cis%202.2/crd/big-ip-cluster/crd-examples
