### ISSUE TITLE
[Doc] AS3 CM to CRD migration plan

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1552]
#### Title
AS3 configmaps to CRD migration tips/best practices

#### Description
Need documentation that guides how to migrate from AS3 configmaps to CRD in a production environment. 

#### Actual Problem
Currently, AS3 configmaps and CRDs cannot coexist. 
Need to ensure smooth migration to CRDs for some basic configmaps. 
Want to avoid downtime for the application.

#### Solution Proposed

Documentation on migration plan

#### Alternatives
n/a

#### Additional context

Existing documentation: https://clouddocs.f5.com/containers/latest/userguide/crd.html

**Comment by mdditt2000** [comment]
Jira CONTCNTR-2207 for PM tracking

**Comment by mdditt2000** [comment]
Out for review. @tkam8 sending you a email with the link for this item to review.

**Comment by mdditt2000** [comment]
PO needs to review the document and feedback.

**Comment by trinaths** [comment]
The document is review and changes in progress.

**Comment by mdditt2000** [comment]
Finalize the doc to be updated and published.

**Comment by trinaths** [comment]
Document published - Please see https://clouddocs.f5.com/containers/latest/userguide/crd/as3cm-to-crd.html 
Closing this issue.
