### ISSUE TITLE
Is serviceDownImmediateAction support available in the AS3 LTS release 3.19.1?

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1554]
#### Setup Details
 CIS Version : 2.1.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.18.0      
 Agent Mode: AS3       
 Orchestration: K8S
 Orchestration Version:18.8       
 Pool Mode: Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  

Service Request #C3409761

The issue we found was that serviceDownImmediateAction was not a valid property to be used in configure map.

The error log from cis:
2020/10/19 20:26:33 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: serviceDownImmediateAction]
2020/10/19 20:27:03 [ERROR] [AS3] Big-IP Responded with code: 422
2020/10/19 20:27:03 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: serviceDownImmediateAction]

We did some research and found that as of AS3 3.21.0 release, it introduced the following change, but it will end of support as of 21-Oct-2020 due to 3 months feature releases support. 
Added support for Immediate Action on Service Down (see serviceDownImmediateAction)

So if we use AS 3.19.1 LTS release, could you please let us know if serviceDownImmediateAction support is available in the LTS release given the LTS version number less than 3.21.0?

Thanks,
Mr Zhu

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by mdditt2000** [comment]
@zhu20200720 CIS does not require LTS. Since CIS and the container environment are moving fast it might not make sense to use LTS. Yesterday we released CIS 2.2 which has support for AS3-23. 

Support for serviceDownImmediateAction is available in AS3 v3.21 and later. 
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#configuring-servicedownimmediateaction-on-a-virtual

Therefore you need to use AS3 v3.21 to get this feature. I would recommend using CIS 2.2

**Comment by mdditt2000** [comment]
@zhu20200720 we are looking at AS3-24 for the next possible LTS. This would pair with CIS 2.2.1. Will provide a update later to the time.

**Comment by zhu20200720** [comment]
@mdditt2000 , we used AS3 3.21.0 per suggest from Service Request #C3409761.

**Comment by mdditt2000** [comment]
@zhu20200720 AS3-21 is fine. Watch out for the next LTS release. Most likely be AS3-24 which would be paired nicely with CIS 2.2.1 coming in early december.
