### ISSUE TITLE
iRule openshift_passthrough_irule logs various TCL errors

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#1557]
#### Setup Details
 CIS Version : 2.2.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.1.2.5 - build 0.101.3      
 AS3 Version: 3.20.0-build3
 Agent Mode: AS3
 Orchestration: K8S/OSCP v1.11.0, OS v3.11
 Pool Mode: Cluster
 Additional Setup details: openshift_passthrough_irule is active

#### Description  
My setup uses OS-Routes (mixture of host- and path-based) to expose services to Internet.
The mandatory iRule "openshift_passthrough_irule" "creates" TCL-error messages in /var/log/ltm.

#### Steps To Reproduce
A non-conform TLS-frame must be used, which cannot properly handled by this iRule.

#### Expected Result 
iRule "creates" no TCL-error

#### Actual Result  
iRule "creates" TCL-error

#### Diagnostic Information
1.
Oct 28 03:51:03 BIG-IP err tmm3[16191]: 01220001:3: TCL error: /appaotel1/Shared/openshift_passthrough_irule <CLIENT_DATA> - can't read "tls_payload_len": no such variable     while executing "string is integer -strict $tls_payload_len"

2.
Oct 28 04:34:41  BIG-IP err tmm2[16191]: 01220001:3: TCL error: /appaotel1/Shared/openshift_passthrough_irule <CLIENT_DATA> - bad option "-21660": must be -exact, -glob, -regexp, or --     while executing "switch -exact $tls_version {                            "769" -                                 "770" -                                 "771" {                                         # Content type of 22 indicates the TLS payload contains a handshake.                                        if { $..."

**Comment by trinaths** [comment]
JIRA- CONTCNTR-2277 for PM tracking

**Comment by trinaths** [comment]
issue resolved in v2.2.2. Closing this issue.
