### ISSUE TITLE
How to override multiple virtual server setting in one partition

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1558]
#### Setup Details
 CIS Version : 2.1.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.21.0      
 Agent Mode: AS3
 Orchestration: K8S/OSCP      
 Orchestration Version:   1.18.8    
 Pool Mode: Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  
We have two ingress created two virtual servers in one f5 partition. The two Ingress, two custom ConfigMap were deployed in two separate k8s namespaces.

We want to override the as3 configmap settings for both virtual servers.
 "--override-as3-declaration=kube-system/customconfig",
//"--override-as3-declaration=kube-system/customconfig1" 

However only the last argument above works in Ingress controller.

Is there a way in Ingress controller or in ConfigMap to achieve overridden both virtual server settings?

![image](https://user-images.githubusercontent.com/68562586/97495838-83830280-193e-11eb-8307-3a46c8c6f282.png)

![image](https://user-images.githubusercontent.com/68562586/97495926-9e557700-193e-11eb-81d3-d7852c48ca6f.png)

Thanks,
Mr zhu

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by mdditt2000** [comment]
@zhu20200720 CIS only **support one AS3 override**. Can you please merge ingress_x_y_z_vip_80 and ingress_x_y_z_vip1_80 into one ConfigMap. I can help if you share the YAML file.

**Comment by zhu20200720** [comment]
Thank you @mdditt2000 , I attached two configMap, they are very similar. It would be great if they can be merged as we tried ourselves but getting issues.
[customconfig.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/5454883/customconfig.txt)
[customconfig1.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/5454884/customconfig1.txt)

**Comment by mdditt2000** [comment]
here you go

ConfigMap - https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.2/github/1558/configmap.yaml
AS3 Json - https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.2/github/1558/configmap.json

This will resolve your issue

**Comment by zhu20200720** [comment]
Thanks, we will test and report it back

**Comment by mdditt2000** [comment]
i changed you file. It looks the " was incorrect and not valid. Let me know how the testing goes. That override should work for you.

**Comment by zhu20200720** [comment]
@mdditt2000 thanks, it works. As we use cis 2.1.0, as3 3.21.0, we have to add the line ""schemaVersion": "3.0.0","

**Comment by mdditt2000** [comment]
@zhu20200720 glad that resolved your issue!! Thank you..
