### ISSUE TITLE
[2.x] Logs should distinguish configmap and Ingress errors

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1565]
#### Title
Controller logs should distinguish configmap and Ingress errors to save time troubleshooting

#### Description
In logs such as below, there should be another indicator that tells user whether the errors are from an Ingress or configmap declaration. 

2020/11/21 15:13:32 [ERROR] [AS3] Template is not valid. see errors
2020/11/21 15:13:32 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/11/21 15:13:32 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2020/11/21 15:13:32 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2020/11/21 15:13:32 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)

2020/11/21 15:13:32 [ERROR] [AS3] Template is not valid. see errors

#### Actual Problem
In a large environment, both Ingress and configmap objects could be deployed and watched by CIS. 
If one user is trying to troubleshoot configmap deployment/syntax issues, unrelated Ingress errors may cause confusion. 

Personally spent few hours trying to troubleshoot configmap AS3 syntax and deployment issues when in fact an Ingress object deployed in another namespace was blocking all configmap processing regardless of whether AS3 validation of the configmap passed or not. 

#### Solution Proposed
Add additional indicators (configmap and Ingress) like below 

2020/11/21 15:13:32 [ERROR] [AS3] [**Ingress**] Template is not valid. see errors
2020/11/21 15:13:32 [ERROR] [**Ingress**] - declaration.Shared: Must validate "then" as "if" was valid
----snip----
2020/11/21 15:13:32 [ERROR] [AS3] [**configmap**] Template is not valid. see errors
2020/11/21 15:13:32 [ERROR] [**configmap**] - declaration: Must validate "then" as "if" was valid
 
2020/11/21 15:13:32 [ERROR] [**configmap**] - declaration.members.0: Must validate "then" as "if" was valid
 
2020/11/21 15:13:32 [ERROR] [**configmap**] - declaration.members.0: Must validate one and only one schema (oneOf)
 
2020/11/21 15:13:32 [ERROR] [**configmap**] - declaration.members.0: bigip is required

#### Alternatives
n/a

#### Additional context
This is improving usability, time to resolution

**Comment by mdditt2000** [comment]
@tkam8 most likely this wont make 2.2.1. Therefore tagged as 2.2.2

**Comment by mdditt2000** [comment]
Internal PM Jira  created for tracking CONTCNTR-2249

**Comment by trinaths** [comment]
This issue is fixed with CIS v2.3
