### ISSUE TITLE
Password includes'+-', f5 Authentication failed

### ISSUE THREAD

**Issue by jamesDeng** [F5Networks/k8s-bigip-ctlr#1567]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:1.12.0
 BIGIP Version: Big IP x.x.x      
 AS3 Version: N/A   
 Agent Mode: AS3/CCCL       
 Orchestration: K8S
 Orchestration Version: 1.15.7       
 Pool Mode: Cluster     
 Additional Setup details: helm chart

#### Description  
Password includes'+-', f5 Authentication failed

![image](https://user-images.githubusercontent.com/4443650/98780336-9235e300-242f-11eb-92d4-57d6c7df72d0.png)

f5 ctrl pod describe:
![image](https://user-images.githubusercontent.com/4443650/98780421-b0034800-242f-11eb-9e6a-b57e25640b66.png)

secret f5-bigip-ctrl-login yaml:
![image](https://user-images.githubusercontent.com/4443650/98780628-0d979480-2430-11eb-8709-607939f00efb.png)

#### Steps To Reproduce
1).  Test password,Login BIG-IP dashboard 
2). Update secret'f5-bigip-ctrl-login'
Get the base64 encrypted string of f5 password
``` base
echo 'QWERTYW239WuvgK+V%--+mYYKCEk9x' |base64 
```
Run Update
``` base
kubectl patch secret f5-bigip-ctlr-login -p='{"data":{"password": "XXXXXXXX"}}' -v=1 -n kube-system
```
3) Restart k8s-bigip-ctlr POD
``` base
kubectl rollout restart deployment f5-f5-bigip-ctlr-ha-active -n kube-system
```

#### Expected Result 
k8s-bigip-ctlr works normally

#### Actual Result  

 f5 Authentication failed

**Comment by mdditt2000** [comment]
@jamesDeng thank you for opening this issue. Having the API support a password with special characters is something outside of the scope of AS3/iControl REST API. CIS is a consumer the API and therefore have to following iControl RST password guidelines which don't support these type of characters. 

Test and i see the same error

HTTP Auth FAILURE: 401 - Authentication failed.

**Recommendation:** Please remove the +- from the password used for CIS.

**Comment by jamesDeng** [comment]
@mdditt2000 Noted and Thanks.

**Comment by jamesDeng** [comment]
@mdditt2000 Can you provide guidance on iControl RST password Fomats?

**Comment by VariableDeclared** [comment]
Can the prerequisites of CIS documentation state this please?
