### ISSUE TITLE
udp in Transportserver crd

### ISSUE THREAD

**Issue by mw-0** [F5Networks/k8s-bigip-ctlr#1573]
#### Title
Support UDP in Transportserver

#### Description
Add support for UDP to match TCP in transport server.  I use backend DNS Servers for instance on tcp and udp

#### Actual Problem
Currently tcp is only supported so I cannot move to crd design.

#### Solution Proposed
Allowed udp same as tcp

**Comment by mdditt2000** [comment]
@mw-0 thank you for opening this issue. Filed Jira CONTCNTR-2255 for PM tracking. Did you test TCP CRDs? Any feedback? We will add UDP support as fast as possible so you can move to CRD design. What are you time frame?

**Comment by mw-0** [comment]
I was evaluating since we use f5 elsewhere what I could do with the kube additions. I currently run using different tools here.  I have pout in virtual server and basic tcp crd.

**Comment by mdditt2000** [comment]
@mw-0 UDP has been added and will be released in CIS 2.4. I can provide a early test build if you want to test. We have added support for UDP monitors. Thanks
