### ISSUE TITLE
Support CRDs and Ingress at the same time

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#1580]
#### Title
Support processing CRDs and Ingress resources at the same time

#### Description
Currently we make use of the high level ingress resources provided out of the box by kubernetes but also want to make use of the more advanced CRDs at the same time.

#### Actual Problem
Want to make use of the advanced capabilities of CRDs and still be able to use Ingress at the same time. We use Ingress for simple web services but as we have other advanced use cases the custom resources will be used.

#### Solution Proposed
Be able to start the cis controller and have it process both ingress and crds. 

#### Alternatives
Deploy CIS controller twice with one set for CRDs and the other set just for Ingress. While this will allow for the requested use case it will double the required management and support since we will have two deployed instead of just one instance per big-ip.

**Comment by iam-veeramalla** [comment]
Hi @mitchellmaler, CRD controller is designed to be light weight and eliminate the processing issues with routes and ingress. The primary goal during the design was not to process ingress/routes and cfgmap along with CR's but to provide all the features of ingress and routes using CRDs. 

Can you please elaborate more on what is the exact reason why you want use both ingress and CRD at the same time?

**Comment by mitchellmaler** [comment]
Okay that makes sense. After more thought and planning we should be able to deploy the cis controller twice.

**Comment by mitchellmaler** [comment]
The main reason is we have tenants using Ingress that won’t want to migrate to CRD. This keeps backwards compatibility while newer deployments can start to use the CRDs.
