### ISSUE TITLE
Status and Events for Processed Custom Resources

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#1582]
#### Title
Status and Events for Processed Custom Resources

#### Description
Able to view the CR status using kubernetes api and see events for processing errors.

#### Actual Problem
If there is an issue processing the custom resource you won't know until either you can't get to your application or view the CIS logs. 

#### Solution Proposed
Create and update status(es) on the CustomResource to know when it has been processed fully and the Big-IP successful applied the configuration. This status can be used to show an error state if the Big-IP is not updated with the configuration for some reason. 

Create kubernetes events on the custom resource with a log of what has happened such as Applied or Error along with the reason for the error. This will allow tenants to troubleshoot their VirtualServer resources and understand why it isn't applied. 

#### Alternatives
Allow tenants to view the CIS logs which is not as easy since it is not running in their namespaces. Would have to give them access to the logs in an aggregator. Following the proposed solution is more kubernetes native.

**Comment by sterburg** [comment]
+1 This kind of feedback is really mandatory.
I like the solution proposed, as it is the kubernetes native way of doing so.

Alternatives:
Use Telemetry + syslog module on the F5 Big-IP to export metrics and logs into Prometheus of OpenShift, associating it with the corresponding kubernetes resource name.

**Comment by mikeoleary** [comment]
+1
Typically when I am troubleshooting with customers we are forced to view CIS pod logs which is difficult. This proposed solution would be easy for me to explain to a customer.

**Comment by trinaths** [comment]
Created CONTCNTR-2771 for internal PM tracking.

**Comment by trinaths** [comment]
@mitchellmaler - Is the requirement still valid ? Its been a long time this RFE is proposed.

**Comment by trinaths** [comment]
Closing this issue since its not longer planned for CIS.
