### ISSUE TITLE
Support services with multiple ports and use Firewall policies

### ISSUE THREAD

**Issue by ehlomarcus** [F5Networks/k8s-bigip-ctlr#1591]
#### Title
Support multiple ports on kind/Service
Support usage of Firewall policies on L4 and L7 services virtualServers

#### Description
I would like to be able to expose either kind/Service or kind/Ingress with multiple ports and also be able to attach a firewall policy.

All or most objects that can be attached to an "Virtual Server" or "Pool" should be possible to create by request from a user.

As a user I should be able to create a Deployment, Service and Ingress. Along with either lables or annotations to create needed objects in F5. Mush like how AWS behaves with the use of aws-alb-controller.

or 

Possibility to do the same with the use of CRDs. 

#### Actual Problem
The use-case I'm working with right now is to utilize both BIGIP and Nginx, where Nginx will be used for standard Ingress/L7 and BIGIP for L4 services that requires other ports than 443 or 80. An example could be a CockroachDB deployment where the CockroachDB pods are fronted with a L4 virtual server, which serves the gRPC port used by CockroachDB that is used by clients connecting to the database.

#### Solution Proposed
Expand the usage of CRDs to allow for more types. Possibly allow ingress objects with annotations to define a firewall policy, and allow Service objects to use multiple ports and expose those.

#### Alternatives
Alternatively (or currently partly solved): Use kind/Service with NodePort and use Config Map with AS3 declaration to create serviceMain with L4 template and a single port and pool. Virtual Server is also connected to a firewall policy defined in declaration.

#### Additional context
Documentation that exist is ok, but it is often sending me in a loop between documents.
Docs should also describe more end-to-end examples, and also show what combinations of controller configuration and resource configuration that work or does not work. Much like the crd-mode states today that ingress, service and config map is not supported at the same time.

**Comment by mdditt2000** [comment]
Responding to issue via **Slack**
-----

Yes user-defined AS3 configmap is currently the only way to add Network Firewall policies. The Network Firewall policie objects needs to be added to CRDs. This is not hard todo. Please file a Github enhancement for this

Regarding the AS3 ConfigMap. Each configmap will have a unique service. You can create multiple services to match a Application in the AS3 declaration. Here is a good example App A1 to App A4 https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%201.14/user-defined-configmap/A4/f5-as3-configmap.yaml and the service for this configmap https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%201.14/user-defined-configmap/deployment/f5-hello-world-service.yaml - Note the labels used for service discovery

**Request**

Can setup multiple tenants or a single tenant using AS3 configmap. Maybe next week we could setup a ZOOM call and discuss this morning. Please Direct Message me todo this.

CRDs support for Network Firewall policies makes perfect sense to be supported in TransportServer CRDs which are TCP based. Look at TransportServer CRDs https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/_static/config_examples/crd/TransportServer
-----

**Comment by mdditt2000** [comment]
New enhancement for CRD https://github.com/F5Networks/k8s-bigip-ctlr/issues/1600

**Comment by mdditt2000** [comment]
This issue can be closed **This issue can be closed! Policy CRD supports AFM**
