### ISSUE TITLE
CRD enhancements

### ISSUE THREAD

**Issue by rgarcia89** [F5Networks/k8s-bigip-ctlr#1592]
As discussed with @mdditt2000 below some snippets of what I do with AS3 so far and therefore, what I would need as CRD.

```json
#using shared objects
    "Shared": {
        "class": "Application",
        "template": "shared",
        "ftp_crm_prod_serviceAddress_v4": {
            "class": "Service_Address",
            "virtualAddress": "1.2.3.4",
            "arpEnabled": true,
            "icmpEcho": "enable",
            "routeAdvertisement": "all",
            "trafficGroup":"/Common/traffic-group-external-1"
        },
        "ftp_prod_pool": {
            "class": "Pool",
            "loadBalancingMode": "round-robin",
            "monitors": [
                "tcp"
            ],
            "members": [
                {
                    "servicePort": 9999,
                    "serverAddresses": [],
                    "shareNodes": true
                }
            ]
        },
    }
    
    "ftp_prod_app_v4": {
        "class": "Application",
        "template": "generic",
        "ftp_prod_v4": {
            "class": "Service_TCP",
            "remark": "",
            "virtualAddresses": [
                {
                    "use": "/anycast_tenant/Shared/ftp_crm_prod_serviceAddress_v4"
                }
            ],
            "virtualPort" : 22,
            "allowVlans": [
                "/Common/VL-e-rt-lb"
            ],
            "snat": "none",
            "pool": "/anycast_tenant/Shared/ftp_prod_pool"
        }
    },
    "http_prod_app_v4": {
        "class": "Application",
        "template": "generic",
        "http_prod_v4": {
            "class": "Service_HTTPS",
            "remark": "",
            "redirect80": true,
            "virtualAddresses": [
                {
                    "use": "/anycast_tenant/Shared/ftp_crm_prod_serviceAddress_v4"
                }
            ],
            "virtualPort" : 443,
            "allowVlans": [
                "/Common/VL-e-rt-lb"
            ],
            "serverTLS": { "bigip": "/Common/ssl_wildcard" },
            "snat": "none",
            "pool": "/anycast_tenant/Shared/http_prod_pool"
        }
    }

# not using shared objects
    "chat_app": {
        "class": "Application",
        "template": "generic",
        "chat_prod": {
            "class": "Service_HTTPS",
            "remark": "",
            "redirect80": true,
            "virtualAddresses": [
                {
                "use": "chat_serviceAddress"
                }
            ],
            "virtualPort" : 443,
            "allowVlans": [
                "/Common/VL-e-rt-lb"
            ],
            "serverTLS": { "bigip": "/Common/ssl_wildcard" },
            "clientTLS": { "bigip": "/Common/serverssl" },
            "snat": "none",
            "pool": "chat_pool"
        },
        "chat_pool": {
            "class": "Pool",
            "loadBalancingMode": "round-robin",
            "monitors": [
                "http"
            ],
            "members": [
                {
                    "servicePort": 9999,
                    "serverAddresses": [],
                    "shareNodes": true
                }
            ]
        },
        "chat_serviceAddress": {
            "class": "Service_Address",
            "virtualAddress": "1.2.3.4",
            "arpEnabled": true,
            "icmpEcho": "enable",
            "routeAdvertisement": "all",
            "trafficGroup":"/Common/traffic-group-external-1"
        }
    }

#other objects that we use
    "app1_monitor": {
        "class": "Monitor",
        "monitorType": "http",
        "send": "GET /health HTTP/1.1\r\nHost:app1\r\nConnection: Close\r\n\r\n",
        "receive": "app1 up and running",
        "adaptive": false
    }

    "app_irule": {
        "class": "iRule",
        "remark": "Limit each IP address to 5 connection within 60 seconds",
        "iRule": "..."
    }
```

**Comment by mdditt2000** [comment]
@rgarcia89 for  "class": "Service_TCP", i recommend look at TransportServer. TransportServer is a CRD for non HTTP applications. You would require "allowVlans" as its missing. I need to check but i believe we also missing 

```
"arpEnabled": true,
"icmpEcho": "enable",
"routeAdvertisement": "all",
```

**Comment by rgarcia89** [comment]
As far as I know the whole serviceAddress section is missing.
So also the `trafficGroup`-Section.

Also how can I declare shared pools or serviceAddresses in CRD?

**Comment by rgarcia89** [comment]
@mdditt2000 is there any update on the request?

**Comment by mdditt2000** [comment]
@rgarcia89 where are you vlans defined? Would the following be ok for the CRD schema?

"allowVlans": [
            { "bigip":"/Common/internal-sales" },
            { "bigip":"/Common/internal-marketing" }
          ]

**Comment by mdditt2000** [comment]
Jira item in the backlog for "Allowvlan" CONTCNTR-2357. PM requesting for for CIS 2.3

**Comment by mdditt2000** [comment]
Jira item in the backlog for Add arpEnabled, icmpEcho, routeAdvertisement, trafficGroup objects to CRD. CONTCNTR-2358

**Comment by mdditt2000** [comment]
@rgarcia89 support for Shared Nodes globally
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1534

https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html#as3-parameters

share-nodes=true

**Comment by rgarcia89** [comment]
> @rgarcia89 where are you vlans defined? Would the following be ok for the CRD schema?
> 
> "allowVlans": [
> { "bigip":"/Common/internal-sales" },
> { "bigip":"/Common/internal-marketing" }
> ]

looks good to me yes I think so

**Comment by rgarcia89** [comment]
> @rgarcia89 support for Shared Nodes globally
> #1534
> 
> https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html#as3-parameters
> 
> share-nodes=true

and in CRD? :thinking:

**Comment by mdditt2000** [comment]
@rgarcia89 yes for CRD etc

review my quick recreate example https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.2/github/1592/cis-deployment/f5-cluster-deployment.yaml

Pool member created in common as shared objects

![image](https://user-images.githubusercontent.com/12733938/104073028-895c5600-51c1-11eb-83e9-8f0bc38ef856.png)

Looking at the AS3 created by CIS you get 

`
"default_f5_hello_world_8080": {
                "class": "Pool",
                "members": [
                    {
                        "addressDiscovery": "static",
                        "serverAddresses": [
                            "10.244.2.11"
                        ],
                        "servicePort": 8080,
                        "shareNodes": true
                    },
                    {
                        "addressDiscovery": "static",
                        "serverAddresses": [
                            "10.244.3.12"
                        ],
                        "servicePort": 8080,
                        "shareNodes": true
                    }
                ]
,
`

**Comment by rgarcia89** [comment]
@mdditt2000 oh I see so by adding it to the CIS pod parameters it will be set per default on all AS3 that are passed by it.
I can definitely live with that.

**Comment by mdditt2000** [comment]
@rgarcia89 yes. Just add - "--share-nodes=true" to the CIS arguments and you done.

**Comment by trinaths** [comment]
This issue is fixed with CIS v2.3

**Comment by rgarcia89** [comment]
@trinaths do you have somewhere examples for this new implementations?

**Comment by trinaths** [comment]
@rgarcia89  -please see  https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/TransportServer/transport-server.yaml#L14

**Comment by rgarcia89** [comment]
> @rgarcia89 -please see https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/TransportServer/transport-server.yaml#L14

Is there also somewhere a documentation to see what other options are available?
I am missing for example things like shown here:
```
        "chat_serviceAddress": {
            "class": "Service_Address",
            "virtualAddress": "1.2.3.4",
            "arpEnabled": true,
            "icmpEcho": "enable",
            "routeAdvertisement": "all",
            "trafficGroup":"/Common/traffic-group-external-1"
```

**Comment by rgarcia89** [comment]
@agupta49 awesome this looks way better now.
Thanks
