### ISSUE TITLE
Support Priority Group Activation on pool using F5 BigIP Ingress controller

### ISSUE THREAD

**Issue by wheestermans31** [F5Networks/k8s-bigip-ctlr#1613]
Now we always create a pool with two members using the round-robbin method. Load is then balanced over the two members.

What I like to have is that we have two members and one is active and second is standby. Our F5 support team indicates to use the 'Priority Group Activation' on the pool. Set for example to 1. And then one of the members should have 1.

How can I handle this with Ingress annotations?

**Comment by mdditt2000** [comment]
@wheestermans31 plan can you provide me with the ltm pool configuration. I am checking if 'Priority Group Activation' is available in AS3. If not it will need to be added to AS3 first. I can help with that process.

**Comment by wheestermans31** [comment]
I don't have BIG-IP detailed logic, I'm a user of it for integration k8s. The real BIG-IP work is done by our network team. What you mean with 'ltm pool configuration from BIG-IP'? is uppose this is some dump of the BIG-IP config itself and not the k8s ingress controller part?

**Comment by mdditt2000** [comment]
@dstokesf5 have you seen any AS3 requests for Priority Group Activation' for the pool members?

**Comment by dstokesf5** [comment]
AS3 exposes the priority-group property of ltm pool member objects through the priorityGroup property of an AS3 pool member: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pool-member

**Comment by mdditt2000** [comment]
@wheestermans31 can we setup a meeting with yourself and network team to get this issue resolved using a AS3 configmap?

**Comment by wheestermans31** [comment]
I will come back with proposal date. This is something to be done on the the BIGIP itself or can be done via kubernetes ingress controller?

**Comment by trinaths** [comment]
Closing this issue since not activity.
