### ISSUE TITLE
Request to Fix 2 Key Bug to CIS 2.0, or future release to support 2.0 feature

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1636]
With CIS 2.0 Configmap can monitor services from same namespace that configmap resided, or services from different namespaces; 

however, in CIS  2.1 configmap can only monitor services from same namespace that configmap resided.

The customer current use V2.0 in production, hit 2 key BUG, and failed to upgrade CIS version, so request either failed the following 2 bugs in 2.0, or future release support 2.0 features

* https://github.com/F5Networks/k8s-bigip-ctlr/issues/1387
* https://github.com/F5Networks/k8s-bigip-ctlr/issues/1464

**Comment by mdditt2000** [comment]
New design/feature for controller hub/configmap label that can be associated to a configmap and maps to multiple services. CIS 2.5 bigroom planning for this feature.

**Comment by trinaths** [comment]
Hubmode is delivered in 2.5. Closing this issue.
