### ISSUE TITLE
Certificate-check added in CISv2.2.2 logs too often

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#1645]
#### Setup Details
 CIS Version : 2.2.2      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.0.3      
 AS3 Version: 3.25.0      
 Agent Mode: AS3
 Orchestration: K8S/OSCP v1.17.1, OS v4.2
 Orchestration Version:
 Pool Mode: Cluster
 Additional Setup details: OpenShift-Routes

#### Description  
As the release-notes states, CIS now verifies whether the BIG-IP clientssl/serverssl is valid or not valid.  
I really appreciate this feature, but the related error-messages are logged too often.

#### Steps To Reproduce
1) Use cert, which does not match hostname of OS-Route.

#### Expected Result 
Log error every 30mins.

#### Actual Result  
Errors are logged every 30secs.

#### Diagnostic Information
2021/01/20 10:11:17 [ERROR] [CORE] Hostname in route does not match with certificate hostname: x509: certificate is valid for XXX, not YYY
2021/01/20 10:11:17 [ERROR] [CORE] Hostname in route does not match with certificate hostname: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

**Comment by trinaths** [comment]
Tracking this issue with CONTCNTR-2413

**Comment by subbuv26** [comment]
@joebride Please let me know, why it is expected to be logged for every 30 minutes.

**Comment by joebride** [comment]
@subbuv26: It is about the messages regarding certificate check. The messages are fine, but they fill the CIS-log, when they reoccur every 30secs. This interval must be increased , e.g. to 30mins.

**Comment by subbuv26** [comment]
@joebride Got it. currently this interval is constant 30 sec, and not configurable. Will let you know, if this parameter is going to configurable.

**Comment by trinaths** [comment]
@joebride  - Can we log this error only for the first time and ignore for BIGIP ADMITTED routes ?

**Comment by joebride** [comment]
@trinaths: Sorry, but I do not understand, what you mean.

**Comment by trinaths** [comment]
@joebride - you are seeing this log for every 30 secs and want to have it for 30 mins. For each route processed by CIS, Route status is updated with "ADMITTED" flag so that in OCP GUI you can see whether or not route is processed/admitted by CIS. So, to minimize this log, would logging this error for an non admitted route solve the issue ?

**Comment by trinaths** [comment]
from https://github.com/F5Networks/k8s-bigip-ctlr/blob/f42c1494eaf6f355b8d9cc2805981a0a8c89d6fd/pkg/appmanager/validateResources.go#L284  a route with cert errors is not processed.so we need a configurable timer ?
