### ISSUE TITLE
Virtual Server is demoted from CMP when updating to CISv2.2.2

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#1646]
#### Setup Details
 CIS Version : 2.2.2     
 Build: f5networks/k8s-bigip-ctlr:latest       
BIGIP Version: Big IP 15.1.0.3
AS3 Version: 3.24.0
Agent Mode: AS3
Orchestration: K8S/OSCP v1.17.1, OS v4.2
Orchestration Version:
Pool Mode: Cluster
Additional Setup details: OpenShift-Routes

#### Description  
 When updating to new CISv2.2.2 the BIG-IP demotes the virtual-server from CMP.
 It seems to be caused by modification of iRule "openshift_passthrough_irule" via issue #1557 or #1584.
Using Virtual-server without CMP reduces the performance dramatically!

#### Steps To Reproduce
1) Update CIS to v2.2.2
2) iRule "openshift_passthrough_irule" must be used (OS-Routes)
3) observe BIG-IP LTM log
 

#### Expected Result 
iRule must be compatible to CMP mode supporting all CPUs (=default).

#### Actual Result  
iRule forces CMP mode to single CPUs, which dramatically decreases performance!

#### Diagnostic Information
```
LTM-log
Jan 20 10:57:15 BIG-IP warning mcpd[5070]: 01071700:4: The current configuration forces the Virtual (/partition/Shared/VS_TEST) to be demoted from CMP. 
```
```
$ show ltm virtual /partition/Shared/VS_TEST
 
 Ltm::Virtual Server: /partition/Shared/VS_TEST
 Status
   Availability     : unknown
   State            : enabled
   Reason           : The children pool member(s) either don't have service checking enabled, or service check results are  not available yet
   CMP              : enabled
   CMP Mode         : single-cpu       <<<< falls down to single-cpu
 [..]
```
#### Observations (if any)
When removing iRule "/partition/Shared/openshift_passthrough_irule" VS_TEST use the correct CMP-Mode

```
$ show ltm virtual /partition/Shared/VS_TEST
------------------------------------------------------------------------
Ltm::Virtual Server: /partition/Shared/VS_TEST
------------------------------------------------------------------------
Status
  Availability     : unknown
  State            : enabled
  Reason           : The children pool member(s) either don't have service checking enabled, or service check results are not available yet
  CMP              : enabled
  CMP Mode         : all-cpus       <<<< default-mode
[..]
```

**Comment by trinaths** [comment]
Investigating the issue.  I will update.

**Comment by trinaths** [comment]
Added CONTCNTR-2407 for PM tracking.

**Comment by mdditt2000** [comment]
2.2.3¶
Bug Fix¶
Issue 1646: Virtual Server demoted from CMP when updating to CIS v2.2.2.
https://clouddocs.f5.com/containers/latest/reference/release-notes.html
