### ISSUE TITLE
Report "status" of TransportServer CRD

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#1659]
#### Title
Report "status" of TransportServer CRD
#### Description

Currently an end-user cannot tell whether the controller has pushed an update to the BIG-IP device.  Ideally the status should report a timestamp that matches the last pushed update.  Otherwise it is unclear whether a change has been applied or not.

#### Actual Problem
From an end-user it is not possible to tell whether a TransportServer has been pushed to a BIG-IP (or whether any errors).  This would provide feedback if there is an issue (controller not running and/or BIG-IP unresponsive).

#### Solution Proposed
Add a Status that can be outputted when running "kubectl get ts -o wide" i.e.
```
NAME              VIRTUALSERVERADDRESS   VIRTUALSERVERPORT   POOL          POOLPORT   AGE  STATUS LASTUPDATE
my-frontend-crd   10.1.10.82             8080                my-frontend   80         10h  OK     3M
```

#### Alternatives
Currently you have to have privileges to look at the logs of the controller to check on status

#### Additional context
It is not possible to tell the state of a change whether successful or not.

**Comment by mdditt2000** [comment]
Only the STATUS is still required. @trinaths @mdditt2000 please file JIRA for upcoming sprint.

**Comment by trinaths** [comment]
Created CONTCNTR-2537 for internal tracking.

**Comment by mdditt2000** [comment]
Currently targeted at 2.7
