### ISSUE TITLE
Kubernetes/OpenShift Requirement version for CRD

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/k8s-bigip-ctlr#1661]
#### Documentation Update Request

On the CIS landing page we say that CIS works with a large range of K8 versions, however for CRD deployments its much less (1.16+)
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

Documentation to be updated:
https://clouddocs.f5.com/containers/latest/userguide/what-is.html#container-ingress-service-compatibility

**Comment by mdditt2000** [comment]
@jmcalalang will request we put a NOTE: under the CRD page https://clouddocs.f5.com/containers/latest/userguide/crd/ mentioning 1.16+. Will that work?

**Comment by jmcalalang** [comment]
Yeah that’ll work, hopefully it’s caught there!

Cheers,

Jon Calalang
425.971.8991
________________________________

**Comment by trinaths** [comment]
created CONTCNTR-2536 for PM tracking

**Comment by sravyap135** [comment]
Documentation change is live https://clouddocs.f5.com/containers/latest/userguide/crd/ 

Thanks @jmcalalang for raising this.
