### ISSUE TITLE
[Doc] CIS v2.x upgrade steps for ConfigMap

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1665]
#### Title
Guide to assist in upgrading CIS from 1.x to 2.x in production to avoid downtime. 

#### Description
When upgrading to CIS v2.x you need to make sure that all your configmaps are in the same namespace as the service/app workload. I am trying to figure out the best way to do the upgrade without downtime in a situation where all the CMs are in kube-system.

----example------

1. Ensure that you have backups of all configmaps in yaml format stored in a central repository of some sort. Ideally github for version control and RBAC. 
2. Confirm that the target CIS version (e.g. v2.2.2) is uploaded to your local repo if no access to Internet. The local repo location needs to be accessible from any of the worker nodes to pull down. 
3. For every configmap that is deployed in kube-system, delete the existing configmap (This should not impact any existing config on F5)
4. In each configmap, if the namespace is defined, modify only the namespace parameter to be the namespace of the corresponding app/service. Redeploy configmap (should not impact existing config on F5 because AS3 is idempotent)
5. Modify the CIS (k8s-bigip-ctlr) manifest file so that the image version points to the target CIS version. 
6. Redeploy CIS (ctlr) with the updated CIS image (e.g. v2.2.2)

#### Actual Problem
There is no documentation that guides a user wanting to upgrade to v2.x

#### Solution Proposed
Create documentation on clouddocs like example above

#### Alternatives
Making my own document, but would like confirmation from experts

#### Additional context
Include details about other behavioral changes from 1.x on one page (versus in each section of a new release note) would be helpful. For example,

-	Node Label Selector (CIS deployment manifest): Tells CIS to watch only nodes with this label
-	"--node-label-selector=node-role.kubernetes.io/f5role=worker"
-	Configmap Delete: No longer need “blank configmap” to remove configuration on BIG-IP. Use as3: ”false”
-	 labels:     f5type: virtual-server     as3: "false” !!!
-	Namespace: You can watch all namespaces by removing the ”--namespace” argument in the ctlr manifest file. Alternatively you can use “namespace-label” parameter so CIS watches the namespaces with specific label(s). e.g. NAME              STATUS   AGE     LABELS         default           Active   6d6h    externallb=f5   <--configure in CIS deployment   ”--namespace-label=externallb=f5”
-	CRD early access available
-	AS3 call optimisations:
    AS3 will only update BIG-IP if there is changes detected by the K8S API (AS3 must be source of truth)
    Multiple requests bundled into single call sent at a specified interval to prevent overload of restjavad
-	CIS will not create _AS3 partition anymore

**Comment by tkam8** [comment]
Any update on this request for doc please? This will be used for production environment where CIS is running. Thanks

**Comment by mdditt2000** [comment]
Created PM Jira for tracking CONTCNTR-2437

**Comment by tkam8** [comment]
Hello, any potential timeline for this to be completed? Thanks!

**Comment by trinaths** [comment]
The document update is in under development. It will be available with CIS v2.3 release.

**Comment by mdditt2000** [comment]
@tkam8 documentation is now published to clouddocs

https://clouddocs.f5.com/containers/latest/userguide/cis-upgrade.html

Thanks Mark
