### ISSUE TITLE
[Docs] OpenShift Deployment Example Typo

### ISSUE THREAD

**Issue by codygreen** [F5Networks/k8s-bigip-ctlr#1667]
The problem was a command error on the documentation: https://clouddocs.f5.com/containers/latest/userguide/openshift/
 
step 2 has the wrong service account name: **k8s-bigip-ctlr** should be **bigip-ctlr**

If you follow the docs are written you will have a failed deployment due to rbac issues.

**Comment by mdditt2000** [comment]
Issue is resolved in CIS 2.3 Thanks @vtrippel
