### ISSUE TITLE
Adjusting pod eviction time in Kubernetes/Openshift

### ISSUE THREAD

**Issue by grmarxer** [F5Networks/k8s-bigip-ctlr#1672]
#### Setup Details  
 OCP Version : 4.6     
 Build: f5networks/k8s-bigip-ctlr:latest       

#### Description  
 When a k8/OCP node goes offline, all pods on that node are terminated and new ones spun up on a healthy node.  The time that it takes from a node being reported as not-ready to the pods being moved is 5 minutes -- which is the default eviction timeout.  

If the k8s-bigip-ctlr pod is running on that failed node this means it will take a minimum of 5 minutes for the k8s-bigip-ctlr
pod to be moved to a healthy worker node.  During this time no configuration changes will be made to the BIG-IP that the particular k8s-bigip-ctlr is servicing.  

#### Observations  

You can greatly reduce this time using [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) in your k8s-bigip-ctlr deployment without changing the clusters eviction timeout.   

When adding a Toleration of __5 seconds__ to my k8s-bigip-ctlr deployment after the node went "not-ready" my k8s-bigip-ctlr pod moved to a new healthy worker node in 11 seconds.    

When adding a Toleration of __10 seconds__ to my k8s-bigip-ctlr deployment after the node went "not-ready" my k8s-bigip-ctlr pod moved to a new healthy worker node in 17 seconds.    
   
```
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10  
```   

#### k8s-bigip-ctlr_tolerations_deployment_example  

```  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl-bigip01
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ctrl-bigip01
  # DO NOT INCREASE REPLICA COUNT Please
  replicas: 1
  template:
    metadata:
      name: ctrl-bigip01
      labels:
        app: ctrl-bigip01
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "docker.io/f5networks/k8s-bigip-ctlr:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.1.1.12",
            "--bigip-partition=kubernetes",
            "--insecure=true",
            "--as3-validation=true",
            "--manage-ingress=false",
            "--manage-routes=false",
            "--custom-resource-mode=false",
            "--manage-configmaps=true",
            "--log-level=DEBUG",
            "--log-as3-response=true",
            "--pool-member-type=cluster"
            ]
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
```

**Comment by trinaths** [comment]
@grmarxer - This can handled as per CIS user requirements and upto the user to configure CIS deployment. This is no issue with CIS. Closing this issue.
