### ISSUE TITLE
External DNS CRD: CIS tries to remove non-existing monitor from GTM pool

### ISSUE THREAD

**Issue by pdiliberto** [F5Networks/k8s-bigip-ctlr#1684]
#### Setup Details
 CIS Version : 2.2.3    
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.0.4     
 AS3 Version: 3.24
 Agent Mode: AS3       
 Orchestration: K8S     
 Orchestration Version: 1.19       
 Pool Mode: Cluster      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
Deploying externalDNS CRD without specifying monitor. When I delete it, CIS tries to remove an inexistent monitor from the pool, so it fails.

#### Steps To Reproduce
1) Deploy an externalDNS without a monitor
2) Delete it

#### Expected Result 
The GTM configuration (WideIP and Pool) are removed

#### Actual Result  
They are not. The WideIP becomes unavailable (RED) because the pool member is removed from the pool 

#### Diagnostic Information
```
apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  namespace: e-commerce
  labels:
    f5cr: "true"
spec:
  domainName: hackazon.f5-udf.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: hackazon.pool
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/GSLB

```
```
2021/02/05 08:58:14 [DEBUG] [2021-02-05 08:58:14,124 icontrol.session DEBUG] RESPONSE::STATUS: 404 Content-Type: application/json; charset=UTF-8 Content-Encoding: None
2021/02/05 08:58:14 [INFO] Text: '{"code":404,"message":"Object not found - /Common/GSLB:/k8s/Shared/crd_10_1_10_101_80","errorStack":[],"apiError":1}'
2021/02/05 08:58:14 [ERROR] [2021-02-05 08:58:14,125 __main__ ERROR] Could not remove pool member: 404 Unexpected Error: Not Found for uri: https://10.1.1.5:443/mgmt/tm/gtm/pool/a/~Common~hackazon.pool/members/~Common~GSLB:~k8s~Shared~crd_10_1_10_101_80                   
2021/02/05 08:58:14 [INFO] Text: '{"code":404,"message":"Object not found - /Common/GSLB:/k8s/Shared/crd_10_1_10_101_80","errorStack":[],"apiError":1}'
2021/02/05 08:58:14 [ERROR] [2021-02-05 08:58:14,125 __main__ ERROR] Could not delete pool: 'monitor' 
```

**Comment by trinaths** [comment]
Created CONTCNTR-2915 for internal PM tracking.

**Comment by mdditt2000** [comment]
[CIS 2.6.1 SP2] ended 03/Nov/21
[CIS 2.7 SP1] ended 16/Nov/21

Resolved
