### ISSUE TITLE
Revisit the build process ??

### ISSUE THREAD

**Issue by iam-veeramalla** [F5Networks/k8s-bigip-ctlr#1685]
#### Title
Revisit the build process ??

#### Description
The current build process is overwhelming and obsolete. I think there is a lot of scope to remove and improve.

#### Solution Proposed
1. Move to multi stage docker build process. 
   - Why ? 
   1. Currently the build process is using shell scripts to copy the source code and artifacts from one container to another(Build to Runtime) using volume mounts. This is no longer required, Docker introduced multi stage builds to copy the artifacts from one stage to another. 
   2.  This will provide a very good chance of getting rid of rhel related files in the build process. According to me, the best way to stage the build process is:   
   ```
        Stage 1:  Do all the go build related  activities in a debian Image,  
        Stage 2: Copy the artifacts from  stage 1 to a UBI Image
    ```
2. There are go security patches and debian vulnerabilities which we tried fix(patch) as part of build process. I think most of them are not required as we moved to go 1.15 and UBI as runtime Image. 

#### Alternatives
NA

**Comment by trinaths** [comment]
@iam-veeramalla  - A new Build process is being discussed and implementation in progress. we will moving away from Travis CI and Docker hub. Closing this issue. More info will be available with v2.3
