### ISSUE TITLE
Move away from Docker Images to fix the rate limit issue

### ISSUE THREAD

**Issue by iam-veeramalla** [F5Networks/k8s-bigip-ctlr#1688]
#### Setup Details
Travis CI, Local Build

#### Description  
Currently k8s-bigip-ctlr is using public docker images for the build process(both local and travis CI). This is causing the rate limiting issue due to the latest Docker rate limit that is introduced for the free accounts.  Below is the error that I encountered in the Travis CI build process for library/golang image.

```
 library/golang
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
The command "docker pull golang:1.11.1" failed and exited with 1 during .
```
  

#### Steps To Reproduce
1) There are no standard steps to reproduce this issue.  You will encounter this issue when the docker rate limit is reached for the free or anonymous account.

#### Expected Result 
Build Process is Successful.

#### Actual Result  
```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

#### Diagnostic Information
NA

#### Observations (if any)
NA

**Comment by trinaths** [comment]
@iam-veeramalla - A new Build process is being discussed and implementation in progress. we will moving away from Travis CI and Docker hub. Closing this issue. More info will be available with v2.3
