### ISSUE TITLE
Low performance while processing hundreds of services

### ISSUE THREAD

**Issue by liaojianxiong** [F5Networks/k8s-bigip-ctlr#1690]
#### Setup Details
 CIS Version : 2.2.1     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 13.1.1.3     
 AS3 Version: 
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version:   1.17.4    
 Pool Mode: Cluster      
 Additional Setup details: flannel

#### Description  
 In my customer's environment, we find cis low performance while processing hundreds of services. They deploy one cis to monitor all k8s namespace in a k8s cluster, and use cccl and configmap+iApp to update the 3G VE. By now, 378 services deployed and more than 2 minutes delay updated to VE after any service was changed in k8s. It is a long time delay. Even worse, the number of service will increase to 1000 in three months, and the update time delay may increase to 5 minutes or more.  It is difficult for customer to accept this delay.

As I know, AS3 is the recommended agent in CIS, but my Customer plans change CCCL to AS3 next year.  We need find ways to improve the cis performance with cccl. Any help will be appreciated.

#### Steps To Reproduce
1) create 300 services in a k8s cluster
2) expose the 300 services by Configmap + iApp,  300  VS deployed in the LTM
3) add or delete a service/configmap，and find the delay time.

#### Expected Result 
In a 300 service k8s environment, delay time  less than 30 seconds.

#### Actual Result  
delay time more than 2 minutes.

#### Diagnostic Information
Test 1：
At 2021-02-03 06:56:30 we delete a configmap : ccms-dev-web_ccms-web-ve
06:58:45, cis delete the vs, more than 2 minutes delay.
2021-02-03T06:58:45.858874080Z 2021/02/03 06:58:45 [INFO] [2021-02-03 06:58:45,858 f5_cccl.resource.resource INFO] Deleting IcrApplicationService: /partition1/ccms-dev-web_ccms-web-ve

Test 2：
At 2021-02-03 07:42:40 we create a configmap : ccms-dev-web_ccms-web-ve123
07:44:50, cis create the vs, more than 2 minutes delay.
2021-02-03T07:44:50.262931388Z 2021/02/03 07:44:50 [INFO] [2021-02-03 07:44:50,262 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /partition1/ccms-dev-web_ccms-web-ve123
2021-02-03T07:46:42.434483334Z 2021/02/03 07:46:42 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:ccms-web ServicePort:8090 Namespace:ccms-dev-web} and resource ccms-dev-web_ccms-web-ve123

###CIS deployment yaml：
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
  creationTimestamp: "2020-06-23T08:12:12Z"
  generation: 13
  labels:
    app: k8s-bigip-ctlr1
  name: cc-k8s-to-bigip1
  namespace: kube-system
  resourceVersion: "170931100"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/cc-k8s-to-bigip1
  uid: c10227f3-fa10-4102-81b6-c1befa6f13d1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-bigip-ctlr1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-01-23T06:32:28Z"
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr1
      name: k8s-bigip-ctlr1
    spec:
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --manage-ingress=false
        - --bigip-partition=partition1
        - --bigip-url=https://21.97.147.252
        - --pool-member-type=cluster
        - --flannel-name=/Common/flannel_vxlan
        - --insecure=true
        - --agent=cccl
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login1
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login1
        image: f5networks/k8s-bigip-ctlr:2.2.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: k8s-bigip-ctlr1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-12-30T01:13:46Z"
    lastUpdateTime: "2021-01-23T06:32:49Z"
    message: ReplicaSet "cc-k8s-to-bigip1-64988b5955" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-02-03T07:26:37Z"
    lastUpdateTime: "2021-02-03T07:26:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

#####  configmap.yaml

kind: ConfigMap
apiVersion: v1
metadata:
  name: svc91
  namespace: default
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
   {
     "virtualServer": {
       "backend": {
         "serviceName": "nginx91",
         "servicePort": 80
       },
       "frontend": {
         "partition": "CIS",
         "iapp": "/Common/iapp_http_hsl",
         "iappPoolMemberTable": {
           "name": "pool__members",
           "columns": [
               {"name": "addr", "kind": "IPAddress"},
               {"name": "port", "kind": "Port"},
               {"name": "connection_limit", "value": "0"}
           ]
         },
         "iappOptions": {
           "description": "iapp_http_hsl"
         },
         "iappVariables": {
           "pool__pool_to_use": "/#create_new#",
           "pool__addr": "10.0.10.91",
           "pool__port": "80",
           "vs__SNATConfig": "automap",
           "vs__ProfileTCP": "tcp idle-timeout 300",
           "vs__ProfileHTTP": "insert-xforwarded-for enabled",
           "vs__ProfileDefaultPersist": "cookie expiration 30:00",
           "pool_lb": "least-connections-member",
           "monitor__Monitors": "tcp_default",
           "pool__irules": "none",
           "vs__ProfileRequestlog": "none",
           "vs__ProfileAnalytics": "none"
          }
       }
     }
   }

--------
#### iApp tmpl
cli admin-partitions {
    update-partition Common
}
sys application template /Common/iapp_http_hsl {
    actions {
        definition {
            html-help {
            }
            implementation {
                set app $tmsh::app_name

#create  pool
set poolmembers ""

foreach row $::pool__members {
    array set columns [lindex $row 0]
    set ip $columns(addr)
    set port $columns(port)
    append poolmembers "$ip:$port" " "
}

#monitor
if { $::monitor__Monitors eq "tcp_default" } {
   set monitorname  tcp
} elseif {$::monitor__Monitors contains "tcp_new"} {
   set monitorname  ${app}_monitor
   set monitordata [ string replace $::monitor__Monitors 0 6 ]
   tmsh::create ltm monitor tcp ${monitorname} ${monitordata}
}  elseif { $::monitor__Monitors eq "http_default" } {
   set monitorname  http
} elseif { $::monitor__Monitors contains "http_new" } {
   set monitorname  ${app}_monitor
   set monitordata [ string replace $::monitor__Monitors 0 7 ]
   tmsh::create ltm monitor http ${monitorname} ${monitordata}
}

set poolname ${app}_pool
if { ${poolmembers} eq "" } {
tmsh::create ltm pool ${poolname} monitor ${monitorname}  load-balancing-mode $::pool_lb
} else {
tmsh::create ltm pool ${poolname} members add \{ ${poolmembers} \} monitor ${monitorname}  load-balancing-mode $::pool_lb
}

#snat
if { $::vs__SNATConfig  eq "automap" } {
   set snatact $::vs__SNATConfig
} else { 
   set snatact "snat pool $::vs__SNATConfig"
}

#tcp profile
if { $::vs__ProfileTCP eq "tcp"  } {
   set tcpprofile tcp
} elseif { $::vs__ProfileTCP contains "idle-timeout" } {
  set idletimeout [ string replace $::vs__ProfileTCP 0 3 ]
  set tcpprofile ${app}_tcpprofile
  tmsh::create ltm profile tcp ${tcpprofile} ${idletimeout}
}

#http profile
if { $::vs__ProfileHTTP  eq "http" } {
   set httprofile_funtion $::vs__ProfileHTTP
} else { 
   set httprofile_funtion ${app}_httprofile
   tmsh::create ltm profile http ${httprofile_funtion} $::vs__ProfileHTTP
}

#irule
if { $::pool__irules eq "none" } {
   set ruleact $::pool__irules
} else { 
  set irulesname ${app}_irule
  tmsh::create ltm rule ${irulesname} $::pool__irules
  set ruleact "{${irulesname}}"
}

#persis
if {  $::vs__ProfileDefaultPersist eq "none"  }  {
     set persisact $::vs__ProfileDefaultPersist
} elseif {  $::vs__ProfileDefaultPersist eq "cookie"  }  {
     set persisname $::vs__ProfileDefaultPersist
     set persisact "replace-all-with { ${persisname} }"
} elseif {  $::vs__ProfileDefaultPersist contains  "cookie" and $::vs__ProfileDefaultPersist contains "expiration"  }  {
     set expiration [ string replace $::vs__ProfileDefaultPersist 0 5 ]
     set persisname ${app}_persis
     tmsh::create ltm persistence cookie ${persisname}  ${expiration}
     set persisact "replace-all-with { ${persisname} }"
} elseif {  $::vs__ProfileDefaultPersist eq "source_addr"  } {
     set persisname $::vs__ProfileDefaultPersist
     set persisact "replace-all-with { ${persisname} }"
} elseif {  $::vs__ProfileDefaultPersist contains  "source_addr" and $::vs__ProfileDefaultPersist contains "timeout" } {
     set timeout [ string replace $::vs__ProfileDefaultPersist 0 11 ]
     set persisname ${app}_persis
     tmsh::create ltm persistence source-addr ${persisname}  ${timeout}
     set persisact "replace-all-with { ${persisname} }"
}

#create  VS
set vsname ${app}_vs
tmsh::create ltm virtual ${vsname} destination $::pool__addr:$pool__port pool ${poolname} profiles add \{ ${tcpprofile} ${httprofile_funtion}\} rules ${ruleact} source-address-translation \{ type ${snatact} \}  persist  ${persisact} 
            }
            macro {
            }
            presentation {
            }
            role-acl none
            run-as none
        }
    }
    description none
    ignore-verification false
    requires-bigip-version-max none
    requires-bigip-version-min none
    requires-modules { ltm }
    signing-key none
    tmpl-checksum none
    tmpl-signature none
}

-------------------

#### Observations (if any)
CIS's CPU reaches almost 1000mCPU，which means one vCPU.  But the Node has 16 vCPU.

**Comment by trinaths** [comment]
@liaojianxiong - Can you move to mode AS3 ?

**Comment by trinaths** [comment]
Issue is fixed and will be available with v2.4
