### ISSUE TITLE
CIS Version : 2.2.1 - ERROR "Big-IP Responded with code: 401" from time to time. 

### ISSUE THREAD

**Issue by daniloroger** [F5Networks/k8s-bigip-ctlr#1702]
#### Setup Details
 CIS Version : 2.2.1      
 Build: f5networks/k8s-bigip-ctlr:2.2.1       
 BIGIP Version: Big IP  15.1.2.1 build 0.0.10 Point Release 1     
 AS3 Version: 3.24.0, build 5      
 Agent Mode: AS3       
 Orchestration: K8S (OpenShift)      
 Orchestration Version: 4.3.33       
 Pool Mode: Cluster      
 Additional Setup details: Network with NSX-T3 + NCP

#### Description  

We use several CIS controllers (about 6 in total) each one manages a separate namespace on OpenShift and partition on BIG-IP.

In only one of those controllers we are observing an authentication "flaping" in AS3. When we starting the CIS controller everything works normally, but from time to time (a few hours) it presents the error below:

```
  2021/02/12 12:56:13 [DEBUG] [AS3] posting request to https://172.x.x.x/mgmt/shared/appsvcs/declare/
  2021/02/12 12:56:13 [ERROR] [AS3] Big-IP Responded with code: 401
  2021/02/12 12:56:13 [ERROR] [AS3] Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare/ Referrer:10.253.86.5 Sender:10.253.86.5 referer:10.253.86.5 restOperationId:1.0017299e+07] 
```

Notice that instants ago the same controller successfully authenticated on BIG-IP:

 ```
 2021/02/12 12:56:12 [DEBUG] [CORE] Found endpoints for backend {ServiceName:dict ServicePort:80 Namespace:dict-h-2q}: [{10.253.66.4 8080 user-enabled} {10.253.66.7 8080 user-enabled}]
  2021/02/12 12:56:12 [DEBUG] [CORE] Updated 2 of 22 virtual server configs, deleted 0
  2021/02/12 12:56:12 [DEBUG] [CORE] Finished syncing virtual servers  dict-h-2q (7.163738ms)
  2021/02/12 12:56:13 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:dict-h --- message: success
  2021/02/12 12:56:13 [DEBUG] [AS3] Preparing response message to response handler
  2021/02/12 12:56:13 [DEBUG] [AS3] Sent response message to response handler
  2021/02/12 12:56:13 [DEBUG] [CORE] Updating Route Admit Status
  2021/02/12 12:56:13 [DEBUG] [AS3] Posting AS3 Declaration
  2021/02/12 12:56:13 [DEBUG] [AS3] posting request to https://172.x.x.x/mgmt/shared/appsvcs/declare/
  2021/02/12 12:56:13 [ERROR] [AS3] Big-IP Responded with code: 401
  2021/02/12 12:56:13 [ERROR] [AS3] Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare/ Referrer:10.253.86.5 Sender:10.253.86.5 referer:10.253.86.5 restOperationId:1.0017299e+07] 
  2021/02/12 12:56:13 [DEBUG] [AS3] Error handling for event statusCommonResponse
  2021/02/12 12:56:15 [DEBUG] [RESOURCE] Configured rule: {openshift_route_dict-h-2q_actuator-bcdict bcdict-h.cloud-2q.x.y.z/actuator 0 [0xc000b24b40] [0xc0009c1800 0xc0009c1840]}
  2021/02/12 12:56:15 [DEBUG] [CORE] Found endpoints for backend {ServiceName:dict ServicePort:80 Namespace:dict-h-2q}: [{10.253.66.4 8080 user-enabled}]
```

The others "CIS" controllers doesn't show the same error and they run at the same OpenShift cluster. Looking at the BIG-IP LOGs (/var/log/restjavad-audit.0.log) we notice that when it logs the error "401" the user is in the format "local/null" and not "local/admin" as when we had successful. The two examples are listed below:

```
  [I][7212][12 Feb 2021 15:56:31 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/shared/appsvcs/declare/","status":200,"from":"10.253.86.5"}
  
  [I][7219][12 Feb 2021 15:56:31 UTC][ForwarderPassThroughWorker] {"user":"local/null","method":"POST","uri":"http://localhost:8100/mgmt/shared/appsvcs/declare/","status":401,"from":"10.253.86.5"}
```

Our "Deployment" configuration is as follows:

    spec:
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=172.x.x.x
        - --bigip-partition=dict-h
        - --pool-member-type=cluster
        - --manage-routes=true
        - --manage-configmaps=true
        - --namespace=dict-h-2q
        - --namespace=dict-t-2q
        - --namespace=f5-2q
        - --route-vserver-addr=192.168.x.x
        - --route-label=app-f5-dict
        - --log-as3-response=true
        - --log-level=DEBUG
        - --override-as3-declaration=f5-2q/as3-override-site2-ocp-2q-dict
        - --as3-validation=false
        - --insecure=true
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
        image: docker.x.y.z/f5networks/k8s-bigip-ctlr:2.2.1

The "f5-2q" namespace is common in the declaration of all "CIS" controllers, in this namespace we run all the six controllers together, so they all look for the same "Secret". So we are sure that it is not a credential error.

The same settings do not generate errors in CIS v2.1 + AS3 3.21.0 + BIG-IP 15.1.0.4 build 0.0.6. 

We updated the components and faced this behavior.

Is there any known cause for this behavior?

Thank you!

**Comment by oakh1** [comment]
We've also seen this after upgrading to BIG-IP 15.1.2.1. Our pipelines started to fail intermittently with the same error so I had to "code around it". It's most likely a bug in the bigip version 15.1.2.1 (I can also confirm that there's nothing wrong with your credentials/requests).

**Comment by daniloroger** [comment]
@oakh1 Thanks for your response. In the last few days we have done several tests combining versions (F5, CIS and AS3). And in fact the error only occurs with the BIG-IP version "15.1.2.1 build 0.0.10 Point Release 1".

For now we are getting around the problem using the "15.1.2 build 0.0.9 Final" version.

**Comment by trinaths** [comment]
@daniloroger  with upgrade to BIGIP "15.1.2 build 0.0.9 Final" version, is this issue resolved.

**Comment by daniloroger** [comment]
@trinaths Hi! The "15.1.2 build 0.0.9 Final" version is lower than the "15.1.2.1 build 0.0.10 Point Release 1" version. So it was not actually a correction of the issue. In the previous version the same error does not occur.

I believe that this will be corrected in a new version (something like "15.1.2.1 build 0.0.11" or "15.1.2.2"). But it's just my imagination, we have to wait for the response from someone who is part of the development team.

**Comment by trinaths** [comment]
@daniloroger - Are the other CIS controllers running in the same OpenShift Cluster are working fine? from the issue description above, 

> In only one of those controllers we are observing an authentication "flaping" in AS3.

**Comment by trinaths** [comment]
@daniloroger based on the discussion above, I think there is no issue with CIS. Please update your findings if any from CIS.

**Comment by daniloroger** [comment]
@trinaths 

Hello! In fact (when I did the first tests and I opened that "issue"), I hadn’t validated all the possibilities.

What happens with the other controllers is that they do not make frequent interactions with BIG-IP. So, we can't see the error on these controllers because there are few changes in the namespaces (sometimes after days one POD is replaced).

The controller that presented problems is due to the fact that it is in development and the namespaces monitored by it have many changes (PODs creation and deletion every hour).

When we did a laboratory test (other installations of BIP-IP, OpenShift and CIS, but same versions) the error was repeated. It doesn't really seem to be a problem in CIS. It only occurs when we have the "15.1.2.1" version of BIG-IP present.

We are treating the case with the F5 official support, thats because we have the definitive license of the equipments. Soon I will close that "ISSUE" with their response. The response can help other people.

Thanks!

**Comment by y-myk** [comment]
> We've also seen this after upgrading to BIG-IP 15.1.2.1. Our pipelines started to fail intermittently with the same error so I had to "code around it". It's most likely a bug in the bigip version 15.1.2.1 (I can also confirm that there's nothing wrong with your credentials/requests).

Please advise if you also see the issue in OpenShift 4.x environment?

**Comment by trinaths** [comment]
Thank you for the update. No issue with CIS. Closing this issue.
