### ISSUE TITLE
F5 CIS doesnot append default http port to host in the policy which causes other application access URL failed

### ISSUE THREAD

**Issue by zhu20200720** [F5Networks/k8s-bigip-ctlr#1707]
#### Setup Details
CIS Version : 2.1.0
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP x.x.x
AS3 Version: 3.21.0
Agent Mode: AS3
Orchestration: K8S/OSCP
Orchestration Version: 1.18.8
Pool Mode: Nodeport
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  

When setting the service port for kube-state-metrics in Ingress to 80, while we were able to successfully curl the metrics from the Prometheus server, but Prometheus could not fetch the metrics and we saw the EOF error. 

We found out that when curl invoked the endpoint with port 80, it removed the port (only standard ports - 80 and 443) in the HTTP header (Host: xxx.f5cismetrics.mydomain). F5 received this and validated this with the policy (created by the F5 Ingress controller as per the ingress resource definition) which did not have the port information in the policy for the host property. 

When Prometheus invoked the URL, the header contained the port information in the host property (Host: xxx.f5cismetrics.mydomain:80) and since this did not match the policy in F5, the request was terminated by F5.

We looked into F5 and observed that F5 CIS did not append the default http port to host in the policy which caused other application access URL failed. For non-standard port, it did append port number to host in the policy.

It looks like the http spec supports host headers without a port and host headers with a port. Therefore, it sounds like the F5 is not conforming to the spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

The below are two screenshots of generated F5 policy with/without standard HTTP port. You can see clearly that there has no port "80" in F5 policy if using standard HTTP port which will lead other application URL access failed.

Standard HTTP port is not included in F5 policy
![image](https://user-images.githubusercontent.com/68562586/108116974-559b0880-706a-11eb-9bba-6169a127d239.png)

Non-Standard HTTP port is included in F5 policy  
![image](https://user-images.githubusercontent.com/68562586/108117756-584a2d80-706b-11eb-94a5-015fb379e5d2.png)

#### Steps To Reproduce
1)
2)
3)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by zhu20200720** [comment]
Does anyone can confirm it is indeed an issue and any timeline to address it?

**Comment by trinaths** [comment]
@zhu20200720 - please refer to https://github.com/mdditt2000/prometheus for working examples.

**Comment by trinaths** [comment]
Closing this issue. Share Prometheus examples with the user that can fix the issues.
