### ISSUE TITLE
CIS installation to support Pod Security Policy mechanism 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1719]
#### Title

CIS installation to support Pod Security Policy mechanism 

#### Description

Pod Security Mechanism is a Kubernetes security feature which is enabled by default in Tanzu Kubernetes Grid and supported at least in Openshift and Rancher

See https://kubernetes.io/docs/concepts/policy/pod-security-policy/

#### Actual Problem

In clusters/namespaces with this feature enabled the installation of CIS fails

#### Solution Proposed

Provide PSP policies in the documentation

**Comment by mitchellmaler** [comment]
Just to be aware PodSecurityPolicies are being deprecated in Kubernetes 1.21 and removed in 1.25.
https://github.com/kubernetes/enhancements/issues/5#issuecomment-776043765
https://github.com/kubernetes/kubernetes/pull/97171

**Comment by trinaths** [comment]
Closing this issue since PSP will be deprecated soon.

**Comment by pierluigilenoci** [comment]
FYI https://github.com/kubernetes/enhancements/pull/2582

**Comment by trinaths** [comment]
Reopening this issue since there is another approach to support PSP in active discussion. However, this RFE will considered when kubernetes/enhancements#2582 is available.

**Comment by trinaths** [comment]
Created CONTCNTR-2681 for PM tracking

**Comment by alonsocamaro** [comment]
Found that when using Helm charts, at installing in CIS in the kube-system it is deployed just fine, without PSPs:
```
tanzu$ kubectl -n kube-system get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
bigip1-f5-bigip-ctlr-64ff8ffc95-7zxtf                 1/1     Running   0          109s
```
This is not the case when deploying in other namespaces (tried with NGINXplus).

**Comment by trinaths** [comment]
PodSecurityPolicy was [deprecated](https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation) in Kubernetes v1.21, and removed from Kubernetes in v1.25.

Closing this issue.

**Comment by pierluigilenoci** [comment]
@trinaths Pod Security Policies have only been superseded by Pod Security Standards. 
The request still makes sense.
https://kubernetes.io/docs/concepts/security/pod-security-standards/

**Comment by trinaths** [comment]
@pierluigilenoci  please raise a new RFE.

**Comment by pierluigilenoci** [comment]
@trinaths done
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2756
