### ISSUE TITLE
Wrong Certificate is selected when cert is ECDSA-signed - Bug ID 912945

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#1723]
**Setup Details**
CIS Version : 2.2.3
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 15.1.0.3
AS3 Version: 3.25.0
Agent Mode: AS3
Orchestration: K8S/OSCP v1.17.1, OS v4.2
Orchestration Version:
Pool Mode: Cluster
Additional Setup details: OpenShift-Routes using ECDSA-signed certificate

**Description**
When I add ECDSA-signed certificate/key in an OS-Route, the BIG-IP selects the wrong certificate.
This is caused by "Bug ID 912945: A virtual server with multiple client SSL profiles, the profile with CN or SAN of the cert matching the SNI is not selected if cert is ECDSA-signed".

**Expected Result**
When I add ECDSA-signed certificate/key in an OS-Route, the BIG-IP must select the ECDSA-certificate, assigned to the specific OS-route.
Workaround is to Configure the 'Server Name' option in the client SSL profile as described in: https://cdn.f5.com/product/bugtracker/ID912945.html.
This must be performed by CIS, because it cannot be set by configmap for as3-override!

**Actual Result**
When I add ECDSA-signed certificate/key in an OS-Route, the BIG-IP selects wrong certificate and present it to the client.
The BIG-IP selects the certificate which is marked as sni-default=true in specific client-ssl profile option.

**Excerpt CIS-config**
```
image: 'registry.connect.redhat.com/f5networks/cntr-ingress-svcs:2.2.3-rhel7'
args:
- '--bigip-username=$(BIGIP_USERNAME)'
- '--bigip-password=$(BIGIP_PASSWORD)'
- '--bigip-url=A.B.C.D'
- '--bigip-partition=XXX'
- '--pool-member-type=cluster'
- '--openshift-sdn-name=/Common/RD_000_TUN_VXL_0001'
- '--log-level=INFO'
- '--log-as3-response=true'
- '--manage-routes=true'
- '--manage-ingress=false'
- '--route-label=XXX'
- '--route-http-vserver=RD_000_VS_RED_XXX_80'
- '--route-https-vserver=RD_000_VS_STD_XXX_443'
- '--route-vserver-addr=A.B.C.D'
- '--agent=as3'
- '--insecure=true'
- '--tls-version=1.3'
- '--cipher-group=/Common/CIPHER_GROUP_TLSV12_TLSV13_ECDHE_ECDSA_AESGCM

```

**Comment by trinaths** [comment]
created CONTCNTR-2495 for internal tracking.

**Comment by lavanya-f5** [comment]
@joebride Could you please share the route config used ? Is the usecase with multiple clientssl profiles on virtual or multiple certs in a single clientssl profile attached to virtual

**Comment by joebride** [comment]
@lavanya-f5 Find route config below. Use-case = multiple clientssl profiles on single virtual-server

```
<Example OS-Route using EC-DSA>

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
    virtual-server.f5.com/balance: round-robin
    virtual-server.f5.com/health: |
      [
        {
          "path":     "/",
          "send":     "GET /index.html HTTP/1.1\\r\\nHost: <host-name>\\r\\nConnection: Close\\r\\n\\r\\n",
          "recv":     "200",
          "interval": 5,
          "timeout":  16
        }
      ]
    virtual-server.f5.com/waf: /Common/RD_000_WAF_BASIC_GENERIC
  namespace: f5test
  labels:
    app: nginx-sample
    app.kubernetes.io/component: nginx-sample
    app.kubernetes.io/instance: nginx-sample
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-version: latest
    f5type: <f5type-label>
spec:
  host: <host-name>
  to:
    kind: Service
    name: nginx-sample
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
	  <removed>
      -----END CERTIFICATE-----
    cacertificate: |-
      -----BEGIN CERTIFICATE-----
	  <removed>
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN EC PRIVATE KEY-----
	  <removed>
      -----END EC PRIVATE KEY-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
