### ISSUE TITLE
Documentation: sentence on support for VXLAN and clusters is confusing

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#1725]
#### Setup Details
 CIS Version : na    
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP na 
 AS3 Version: na
 Agent Mode: AS3     
 Orchestration: K8S    
 Orchestration Version:       
 Pool Mode: Cluster
 Additional Setup details: customer plans VXLAN integration with A/S cluster of BIG-IP

#### Description  
Customer has reached out because they are confused by this sentence: 
````
VXLAN and Kubernetes are not supported today when using a BIG-IP cluster, but it works with standalone. OpenShift and VXLAN are supported, see the OpenShift section for more information.
````
This sentence can be found on this page:
https://clouddocs.f5.com/containers/latest/userguide/config-options.html#config-options

#### Observations (if any)

This sentence led the customer to believe that we do not support a VXLAN overlay if they are have a Active/Standby cluster. However, in the same documentation we go on to explain how to set up a VXLAN tunnel with a Kubernetes cluster: https://clouddocs.f5.com/containers/latest/userguide/kubernetes/#creating-vxlan-tunnels-on-kubernetes-cluster

Could we update this sentence to explain how to run multiple CIS instances in the cluster to update multiple devices when using VLXAN, and/or clarify the statement on it's support? And, ideally, what to expect when you have 2 clustered devices and multiple CIS instances?

Many thanks.

**Comment by walterk82** [comment]
I've a related conversation about using CIS with HA and support https://f5cloudsolutions.slack.com/archives/C7NJD8LGH/p1613956848000100?thread_ts=1611933417.007800&cid=C7NJD8LGH

> Has any consideration been given to allowing multiple BIG-IP devices per CIS instance for (HA) and then only updating the FDB entries on standby devices while pushing AS3 with the active device?

**Comment by trinaths** [comment]
created - CONTCNTR-2535 for PM tracking

**Comment by walterk82** [comment]
This is related to https://github.com/F5Networks/k8s-bigip-ctlr/issues/452 and https://github.com/F5Networks/f5-ci-docs/issues/750

**Comment by trinaths** [comment]
Issue is fixed. Closing this issue.
