### ISSUE TITLE
Antrea CNI support with NodePortLocal

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1727]
#### Title
Support for Antrea CNI using Geneve encapsulation

#### Description
Antrea with Geneve is the new default CNI used by VMware Tanzu. This can use different encapsulations but uses Geneve by default which BIG-IP supports.

https://github.com/vmware-tanzu/antrea

#### Actual Problem
Customer's prefer F5's single Tier Load Balancing solution.

#### Solution Proposed
Support this CNI in CIS.

**Comment by trinaths** [comment]
@alonsocamaro - Please setup a meeting with PM team to discuss this feature-request.

**Comment by trinaths** [comment]
created CONTCNTR-2248 for internal PM tracking

**Comment by mdditt2000** [comment]
Resolved in CIS 2.8
