### ISSUE TITLE
Need detailed logs passed back from pod to kubectl logs

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/k8s-bigip-ctlr#1733]
#### Title
Need detailed logs passed back from pod to kubectl logs

#### Description
User would like to run "kubectl logs" and point to pod to retrieve CIS logs. When certain errors occur like AS3 declaration POST errors, there needs to be more info in the pod logs so to avoid the need of logging into the F5 directly to see the restnoded.log file.

#### Actual Problem
Simple repro, setup an as3.json file with ASM stuff. But...provision your F5 with only LTM. When you complete the CIS setup and config map and then check kubectl logs, this is what you see on the failed declaration.

```
kubectl logs -f $cisPod -n kube-system | grep --color=auto -i '\[as3'2021/03/03 21:32:14 [INFO] [AS3] Initializing AS3 Agent
2021/03/03 21:32:14 [DEBUG] [AS3] No certs appended, using only system certs
2021/03/03 21:32:14 [DEBUG] [AS3] Validating AS3 schema with  as3-schema-3.25.0-3-cis.json
2021/03/03 21:32:14 [DEBUG] [AS3] posting GET BIGIP AS3 Version request on https://10.1.20.220/mgmt/shared/appsvcs/info
2021/03/03 21:32:15 [DEBUG] [AS3] BIGIP is serving with AS3 version: 3.26
2021/03/03 21:32:15 [DEBUG] [AS3] Removing Partition k8s_AS3 
2021/03/03 21:32:15 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:32:16 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s_AS3 --- message: no change
2021/03/03 21:32:16 [DEBUG] [AS3] Posting AS3 Declaration
2021/03/03 21:32:16 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:32:16 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:32:16 [DEBUG] [AS3] Error handling for event statusCommonResponse
2021/03/03 21:32:21 [DEBUG] [AS3] Posting AS3 Declaration
2021/03/03 21:32:21 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:32:22 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:32:22 [DEBUG] [AS3] Error handling for event statusCommonResponse
2021/03/03 21:32:52 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:32:53 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:32:53 [DEBUG] [AS3] Error handling for event statusCommonResponse
2021/03/03 21:33:23 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:33:23 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:33:23 [DEBUG] [AS3] Error handling for event statusCommonResponse
2021/03/03 21:33:53 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:33:54 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:33:54 [DEBUG] [AS3] Error handling for event statusCommonResponse
2021/03/03 21:34:24 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:34:25 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:34:25 [DEBUG] [AS3] Error handling for event statusCommonResponse
```

When you login directly to BIG-IP and check the /var/log/restnoded/restnoded.log file, this is what I see...

```
Wed, 03 Mar 2021 21:32:53 GMT - warning: [appsvcs] {"status":422,"message":"declaration is invalid","errors":["/AS3/owasp-juiceshop/OWASPAutoTune: One of these F5 modules needs to be provisioned: asm"],"level":"warning"}
```

#### Solution Proposed
Pass some of the details back from restnode.log into the CIS controller. This way, some high level logs will exist when checking kubectl logs. Like this...

```
```
kubectl logs -f $cisPod -n kube-system | grep --color=auto -i '\[as3'2021/03/03 21:32:14 [INFO] [AS3] Initializing AS3 Agent
2021/03/03 21:32:14 [DEBUG] [AS3] No certs appended, using only system certs
2021/03/03 21:32:14 [DEBUG] [AS3] Validating AS3 schema with  as3-schema-3.25.0-3-cis.json
2021/03/03 21:32:14 [DEBUG] [AS3] posting GET BIGIP AS3 Version request on https://10.1.20.220/mgmt/shared/appsvcs/info
2021/03/03 21:32:15 [DEBUG] [AS3] BIGIP is serving with AS3 version: 3.26
2021/03/03 21:32:15 [DEBUG] [AS3] Removing Partition k8s_AS3 
2021/03/03 21:32:15 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:32:16 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s_AS3 --- message: no change
2021/03/03 21:32:16 [DEBUG] [AS3] Posting AS3 Declaration
2021/03/03 21:32:16 [DEBUG] [AS3] posting request to https://10.1.20.220/mgmt/shared/appsvcs/declare/
2021/03/03 21:32:16 [ERROR] [AS3] Big-IP Responded with code: 422
2021/03/03 21:32:16 [DEBUG] [AS3] Error handling for event statusCommonResponse
----->>>>> new log here 2021/03/03 21:32:17 [DEBUG] [AS3] Missing resource provisioning for module ASM. Please enable ASM
```

#### Alternatives
Alternatively, if you want more details then you have to login to the BIG-IP directly.

#### Additional context
Add any other context or screenshots about the feature request here.

**Comment by mdditt2000** [comment]
afternoon @JeffGiroux 

please add the following to your CIS arguments

- "--log-as3-response=true"

**Comment by JeffGiroux** [comment]
OK, I see this option now.

https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html?highlight=log#as3-parameters

It was buried in the documentation. Can you please add a "Troubleshooting" or "Logging" section to the docs or something in a FAQ within clouddocs for CIS. Something like "How to enable detailed logging".

**Comment by mdditt2000** [comment]
@mdditt2000 to review docs with @vtrippel 

@mdditt2000 task for the troubleshooting document

**Comment by trinaths** [comment]
Created CONTCNTR-2908 for internal tracking

**Comment by mdditt2000** [comment]
Resolved
