### ISSUE TITLE
CIS fails validating as3 ConfigMap when monitor's default port doesn't match 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1745]
#### Setup Details
 CIS Version : 2.3      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP NA      
 AS3 Version: 3.26.0-5
 Agent Mode: AS3     
 Orchestration Version: OCP 4.5
 Pool Mode: Nodeport      

#### Description  
  
When using the following pool definition

```
	"Hello_World_app_pool ": {
		"class": "Pool",
		"monitors": [
			"http"
		],
		"members": [{
			"servicePort": 8080,
			"serverAddresses": []
		}]
	}
```

Please note that the pool members use port 8080 and http's default port is 80.

CIS fails validating it with the following error message

```
2021/03/10 18:38:28 [ERROR] [AS3] Template is not valid. see errors
```
This is solved by changing the service definition to use port 80, then modifying the configmap to use "servicePort": 80

#### Steps To Reproduce
1) Configure a service using port 8080
2) Configure a config map using that service, i have attached the original file that triggered the problem.

#### Expected Result 

it shouldn't be needed to create a custom http monitor or changing the port of the service

#### Observations

I find very important that CIS should provide some diagnostics. It didn't provide any and given that Visual Studio validation is fine this results in bad usability.

**Comment by mdditt2000** [comment]
@dstokesf5 would it be possible in AS3 to have the monitor http use the servicePort": 8080 is specified? That way their is no need to create a custom TCP monitor. 

Reason for this is due to the AS3 ConfigMap not match the service. Having to request the app dev change the service port to 80 isn't really a good option

Recreate - https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.3/github/1745/configmap

@trinaths we should look at improving the error log  [ERROR] [AS3] Template is not valid. see errors. Maybe explain why the template is not valid.

**Comment by dstokesf5** [comment]
@mdditt2000 It is unclear what you are asking from AS3 here. I setup a simple http node on port 8080 and use the following declaration (with IP addresses modified):
```json
{
    "class": "ADC",
    "schemaVersion": "3.0.0",
    "tenant": {
        "class": "Tenant",
        "application": {
            "class": "Application",
            "service": {
                "class": "Service_HTTP",
                "virtualAddresses": [
                    "192.0.2.0"
                ],
                "pool": "web_pool"
            },
            "web_pool": {
                "class": "Pool",
                "monitors": [
                    "http"
                ],
                "members": [
                    {
                        "servicePort": 8080,
                        "serverAddresses": [
                            "192.0.2.1"
                        ]
                    }
                ]
            }
        }
    }
}
```

The default HTTP health monitor is having no problems reporting the node as up, and I can see my HTTP server being pinged by GET requests.

**Comment by alonsocamaro** [comment]
@dstokesf5 why are you specifying the serverAddresses? are you using it with a matching service? I'm reproducing it all the time.

Actually I tried as workaround using a custom monitor and validation fails too

                    "Hello_World_app_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http_8080"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "http_8080": {
                      "class": "Monitor",
                      "monitorType": "http",
                      "targetPort": 8080
                }

**Comment by dstokesf5** [comment]
@alonsocamaro I am just trying to understand what @mdditt2000 was asking from AS3. I do not currently have CIS setup for testing.

**Comment by mdditt2000** [comment]
@dstokesf5 i will be doing more testing today on this Github issue. @dstokesf5 will follup-up thanks. Sorry for the delay.

**Comment by mdditt2000** [comment]
@dstokesf5 validated http monitor uses port specified in "servicePort": 8080, on  both CIS 2.0 and 2.3

**CIS 2.0**
https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.3/github/1745/cis/2.0/f5-cluster-deployment.yaml
Note: Namespace is required. 

**CIS 2.3**
https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.3/github/1745/cis/2.3/f5-cluster-deployment.yaml

Both deployments of AS3 Configmap work perfect
https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.3/github/1745/configmap/f5-as3-configmap-hello-world-http.yaml

```
"Hello_World_app": {
            "Hello_World_app_pool": {
                "class": "Pool",
                "members": [
                    {
                        "serverAddresses": [
                            "10.244.1.67",
                            "10.244.2.38"
                        ],
                        "servicePort": 8080
                    }
                ],
                "monitors": [
                    "http"
                ]
            },
```

![image](https://user-images.githubusercontent.com/12733938/111378874-ac8f0000-865f-11eb-9577-7e30caa0ab2e.png)

![image](https://user-images.githubusercontent.com/12733938/111378978-d3e5cd00-865f-11eb-8140-bc77a1ae81a4.png)

----
Validate port 8080 on POD. Only port 8080 is listening. 

[kube@k8s-1-19-master 2.0]$ curl http://10.244.2.41
curl: (7) Failed connect to 10.244.2.41:80; Connection refused
[kube@k8s-1-19-master 2.0]$ curl http://10.244.2.41:8080


<!DOCTYPE html>
<html lang="en">

**Comment by mdditt2000** [comment]
No issue with CIS. Issue can be closed.

**Comment by alonsocamaro** [comment]
Yes, it was just a configuration issue on my side.
