### ISSUE TITLE
Documentation add to describe what happens CIS container crashes

### ISSUE THREAD

**Issue by pdp2shirts** [F5Networks/k8s-bigip-ctlr#1748]
Documentation add to describe what happens CIS container crashes

#### Description
As part of the IBM Cloud Paks validation a section in the documentation is required to describe the backup and restore or failover functionality of the container. In our case, if the container fails Kubernetes takes care of creating a replica and the state info is pulled in via the Kubernetes API. A simple 2-3 sentence FAQ/ Q&A/troubleshooting section describing this would suffice.

#### Actual Problem
Can not pass IBM certification if this documentation section does not exist.

#### Solution Proposed
A simple 2-3 sentence FAQ/ Q&A/troubleshooting section describing this would suffice. possibly a statement that CIS is a control plane element and no data or data plane traffic will be impacted during an outage. and once new replica is online, then the CIS will gather the state and apply that to the BIG-IP it is associate with.

**Comment by trinaths** [comment]
Created CONTCNTR-2679 for PM tracking

**Comment by trinaths** [comment]
Document updated https://clouddocs.f5.com/containers/latest/reference/faq.html 
Closing this issue.
