### ISSUE TITLE
Add documentation on how to deploy CIS in an "air gapped" environment.

### ISSUE THREAD

**Issue by pdp2shirts** [F5Networks/k8s-bigip-ctlr#1749]
#### Title
Add documentation on how to deploy CIS in an "air gapped" environment.
#### Description
There are several users of CIS that are deploying CIS in an Air Gapped environment. a short section on how to accomplish this is required to pass IBM Cloud Pay certification of the CIS.

#### Solution Proposed
add a short FAQ/Q&A/troubleshooting section in the documentation that details the procedure to retrieve the container image and Operator from a public registry and how to edit the files such that the deployment is done from an internal "air gapped" repository.

**Comment by iam-veeramalla** [comment]
One good reference that I came across recently :
https://www.openshift.com/blog/how-to-deploy-operators-on-disconnected-environments

**Comment by vincentmli** [comment]
slightly related, I can import CIS image into k3s as local image and without any public/private registry setup https://github.com/k3s-io/k3s/issues/2760

**Comment by iam-veeramalla** [comment]
**Step 1:** Locate the mirror registry and its credentials
**Step 2:** Push the desired app image to mirror registry

mirror can be an insecure registry, you can use podman which allows the flag to bypass TLS verification. You can also use docker by adding mirror to insecure registry(if at all it is insecure). 

Pull the Image to local
docker pull docker.io/F5Networks/k8s-bigip-ctlr:latest

Tagging the image: 
podman tag docker.io/nginxinc/nginx-unprivileged <mirror-registry-url>/k8s-bigip-ctlr

Logging in to the mirror registry:
podman login <mirror-registry-url>/k8s-bigip-ctlr --tls-verify=false
<use the credentials you found in Step 1>

Pushing the image to the mirror registry: podman push <mirror-registry-url>/k8s-bigip-ctlr --tls-verify=false

Once these steps are done, You can simply go to the deployment resource created by CIS and update the Image to <mirror-registry-url>/k8s-bigip-ctlr

@pdp2shirts @vincentmli

**Comment by trinaths** [comment]
Created CONTCNTR-2680 for PM tracking.

**Comment by trinaths** [comment]
Document updated https://clouddocs.f5.com/containers/latest/reference/faq.html
Closing this issue.
