### ISSUE TITLE
How to integrate with Openshift4 and Kubernetes-OVN as SDN.

### ISSUE THREAD

**Issue by MartijnStraatman** [F5Networks/k8s-bigip-ctlr#1754]
#### Title
How to integrate with Openshift4 and Kubernetes-OVN as SDN.

#### Description
We are using Kubernetes OVN als default SDN for Openshift 4.x. How can we integrate with f5 while using OVN.
I cannot find documentation on it. 

I tried the documented `HostSubnet`. But in `OVN` this api seems not to be implemented

**Comment by trinaths** [comment]
Thanks for this feature-request. OVN support is in CIS future roadmap. when the support is ready, we will update the docs.
