### ISSUE TITLE
HTTPs redirect Data Group entry not cleaned up

### ISSUE THREAD

**Issue by dfs5** [F5Networks/k8s-bigip-ctlr#1767]
#### Setup Details
 CIS Version : 2.3      
 Build: f5networks/k8s-bigip-ctlr:2.3.0       
 BIGIP Version: Big IP 16.0.1.1      
 AS3 Version: 3.25      
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:1.19       
 Pool Mode: Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  Data Group entry for HTTPs redirect don't get cleaned up after VirtualServer deletion or modification.

#### Steps To Reproduce
1) deploy Kind:VirtualServer with httpTraffic: redirect
e.g.
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: securework-virtual
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.24.1.23"
  virtualServerHTTPSPort: 443
  httpTraffic: redirect
  tlsProfileName: terminate-tls
  host: cafe.example.com
  pools:
  - path: /tea
    service: nginx-ingress
    servicePort: 80
    
2) delete the deployment
3) In Data Group section in BIGIP UI you will still find the DG entry, e.g.: crd_10_24_1_23_80_https_redirect_dg
Same if you modify the deployment to a different IP address the old redirect entry still exists.
--

#### Expected Result 
Data Group configuration should get cleaned up accordingly.

#### Observations (if any)
Not sure what implications it may have if over time the amount of entries grow higher and higher.

**Comment by mitchellmaler** [comment]
This might fix the issue https://github.com/F5Networks/k8s-bigip-ctlr/pull/1753
I observed similar behavior and logged this issue https://github.com/F5Networks/k8s-bigip-ctlr/issues/1739

**Comment by mdditt2000** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1753

@dfs5 awaiting integrated build. I will test this on Tuesday with the latest build. Thanks Mark

**Comment by subbuv26** [comment]
Fixed in https://github.com/F5Networks/k8s-bigip-ctlr/pull/1753
