### ISSUE TITLE
Turn on/off persistence profile of TransportServer 

### ISSUE THREAD

**Issue by quynhlab** [F5Networks/k8s-bigip-ctlr#1768]
#### Title
Turn on/off persistence profile of TransportServer 

#### Description
persistence profile auto set source-address on virtualserver of bigip when deploy kind TransportServer  

#### Solution Proposed
allow turn on/off persistence profile on TransportServer  
look like : 

apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: svc1-tcp-transport-server
  namespace: default
spec:
  virtualServerAddress: "172.16.3.9"
  virtualServerPort: 8544
  virtualServerName: svc1-tcp-ts
  mode: standard
  snat: auto
  **persistenceprofile : none**

**Comment by quynhlab** [comment]
anyone can help?

**Comment by mdditt2000** [comment]
@quynhlab i have a action item to take a enhancement to modify the persistence methods in TransportServer. Will create the enhancement over the next few days.

**Comment by quynhlab** [comment]
@mdditt2000  great! 👍

**Comment by quynhlab** [comment]
hi @mdditt2000 , I'm still waiting for update from you

**Comment by quynhlab** [comment]
hi @mdditt2000 , I'm still waiting for update from you

**Comment by mdditt2000** [comment]
@quynhlab working on a design for this. We are looking at adding an ConfigMap Override to CRDs. That way can modify any object under the virtual. Will share more details once planning is complete.

**Comment by quynhlab** [comment]
@mdditt2000 thank for your response. It's really useful for my case study. I have plan use transportserver for load balancing for proxy mysql :)

**Comment by mikeoleary** [comment]
@mdditt2000 thanks for the insight into this. I came across another customer who is looking to use a custom persistence type and would like to use TransportServer CRD, and potentially with VirtualServer CRD too. For the immediate term we'll use ConfigMap and not CRD but we'll switch them to CRD as soon as this is supported.

**Comment by rmuermann** [comment]
@mdditt2000 I'll pile on here, too.  Another company wants to be able to disable persistence in a TransportServer or VirtualServer CRD.

**Comment by quynhlab** [comment]
@mdditt2000  could you please support for this case?

**Comment by mikeoleary** [comment]
@quynhlab and @rmuermann I thought to provide an update after speaking with @mdditt2000 today. This is being worked on and specifying persistence type is planned to be solved, along with other things. For now, I have a use case that I've solved with a AS3 declaration in a configMap that uses dest-address persistence. You can reach out if you want an example.

**Comment by quynhlab** [comment]
Hi @mikeoleary 
Thank you for reply. I know that AS3 in ConfigMap will help me resolve this case. I though that ConfigMap will not working when use CRD.
Please share to me with example

Many thanks!

**Comment by mikeoleary** [comment]
Hi @quynhlab , you are correct, I have stopped using CRD and set custom-resource-mode=false, and then set manage-configmaps=true. Then I used a configMap instead of a CRD. My example is here: https://github.com/mikeoleary/dest-addr-cis-example/blob/main/as3-configmap.yaml#L28

**Comment by andreasjacobi** [comment]
I have the same requirement to be able to turn off persistence for a TransportServer. But it should be possible with all CRDs where applicable.
I came across a use-case where persistence caused connection to get stuck during POD IP changes so this is valuable to be able to control.

**Comment by mdditt2000** [comment]
@trinaths we need to add this options to PolicyCRDs

```
// code placeholder
"persistenceMethods": [
    "options".  ----------------------- Support all persistence methods including none. 
],
```

Jira story CONTCNTR-2557

**Comment by quynhlab** [comment]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/80056481/154706821-0eebd94f-008e-4f4f-9712-4b70f212a3cb.png">
it's not including **none** in persistenceProfile

**Comment by mdditt2000** [comment]
@quynhlab look at this today.

**Comment by quynhlab** [comment]
thanks @mdditt2000 for mention. I'm still waiting for this features.

**Comment by mdditt2000** [comment]
@quynhlab i have a test image. Would you like a test build "non-production"? CIS 2.8 will be available in mid March

**Comment by quynhlab** [comment]
> @quynhlab i have a test image. Would you like a test build "non-production"? CIS 2.8 will be available in mid March

That's great, please send to me the image so i can use it on test environment. 
Thank you so much.

**Comment by mdditt2000** [comment]
@quynhlab Here you go. **Non-Production test build**

Test image: https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.8/crd-enhancements/cis-deployment/f5-bigip-ctlr-deployment.yaml

Examples for VS,TS

https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.8/crd-enhancements/crd

You can also add persistence to the policy CRD. Then add the policy CRD to the VS, TS CRD. Policy CRD will take precedence

Note: You need the updated CIS schema from https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.8/crd-enhancements/crd/schema

Please let me know if you have questions.

**Comment by mdditt2000** [comment]
created the following guide and video. https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.8/crd-enhancements

**Comment by mdditt2000** [comment]
Released. Closing
