### ISSUE TITLE
Endpoints could not be fetched for service 

### ISSUE THREAD

**Issue by dlhace** [F5Networks/k8s-bigip-ctlr#1774]
#### Setup Details
 CIS Version : 2.3 (assuming from helm deploy "latest")      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: BIG-IP 15.1.0.4 Build 0.0.6 Point Release 4      
 AS3 Version: 3.26.0     
 Agent Mode: AS3/CCCL    ?   
 Orchestration: K8S/OSCP      ?
 Orchestration Version:      ? 
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: RKE (Rancher) 
kubernetes version: v1.20.4
Docker version: 20.10.5

#### Description  
I am trying out f5-lb-f5-bigip-ctlr for a simple echo program.  The virtual server and the node pool are being created, but the pool is not being populated with members.  The log of f5-lb-f5-bigip-ctlr shows:
2021/03/30 18:49:09 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/30 18:49:09 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
But the describe of the service shows an endpoint:
-----
kubectl describe service echoserver2 -n echoserver2
Name:                     echoserver2
Namespace:                echoserver2
Labels:                   <none>
Annotations:              field.cattle.io/publicEndpoints:
                            [{"addresses":["10.109.19.226"],"port":30241,"protocol":"TCP","serviceName":"echoserver2:echoserver2","allNodes":true}]
Selector:                 app=echoserver2
Type:                     NodePort
IP Families:              <none>
IP:                       172.17.138.88
IPs:                      172.17.138.88
Port:                     http  80/TCP
TargetPort:               8080/TCP
NodePort:                 http  30241/TCP
Endpoints:                172.16.2.16:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>  
----
and using the node port works fine.
---
curl http://10.109.19.226:30241
Hostname: echoserver2-5cc95bf484-7cvdc
Pod Information:
        -no pod information available-
Server values:
        server_version=nginx: 1.13.3 - lua: 10008
Request Information:
        client_address=10.109.19.226
        method=GET
        real path=/
        query=
        request_version=1.1
        request_uri=http://10.109.19.226:8080/
Request Headers:
        accept=*/*
        host=10.109.19.226:30241
        user-agent=curl/7.68.0
Request Body:
        -no body in request-
------
#### Steps To Reproduce
1) setup new rancher cluster using vsphere with vsphere provider capabilities
2) kubectl create secret generic bigip-login -n kube-system --from-literal=username=xxx --from-literal=password='xxxx'
3) helm install f5-lb f5-stable/f5-bigip-ctlr -f values.yaml
4) kubectl apply -f f5-echo.yaml

#### Expected Result 
create a virtual server connected to a virtual pool with members pointing at the kubernetes configuration

#### Actual Result  
created a virtual server with a policy pointing at the pool with no members,

#### Diagnostic Information
```buildoutcfg
Error message:
2021/03/31 21:04:39 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:04:39 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:04:39 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/31 21:05:09 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/31 21:05:09 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:05:09 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:05:09 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/31 21:05:39 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/31 21:05:39 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:05:39 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:05:39 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/31 21:06:09 [INFO] [CORE] Port '8080' for service 'echoserver2' was not found.
2021/03/31 21:06:09 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'
2021/03/31 21:06:09 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey.ServiceName}' with port '#{svcKey.ServicePort}'

values.yaml
------
 bigip_login_secret: bigip-login
 rbac:
   create: true
 serviceAccount:
   create: true
   name: k8s-bigip-ctlr
 namespace: kube-system
 args:
   bigip_url: lb.example.com
   bigip_partition: k8s
   pool_member_type: nodeport
   insecure: true
 image:
   user: f5networks
   repo: k8s-bigip-ctlr
   pullPolicy: Always
 resources: {}
 version: latest
-----
f5-echo.yaml
----
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver2
  namespace: echoserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver2
  template:
    metadata:
      labels:
        app: echoserver2
    spec:
      containers:
        - name: echoserver2
          image: gcr.io/google_containers/echoserver:1.8
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver2
  namespace: echoserver2
spec:
  selector:
    app: echoserver2
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: echoserver2
  annotations:
    virtual-server.f5.com/ip: "10.118.252.66"
    virtual-server.f5.com/partition: "k8s"
    virtual-server.f5.com/balance: "round-robin"
    virtual-server.f5.com/http-port: "80"
spec:
  rules:
    - host: echo2.churchofjesuschrist.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echoserver2
                port:
                  number: 8080
---
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by dlhace** [comment]
A note on the rancher cluster build.  The default ngix ingress is set to "none" in order to allow f5-lb-f5-bigip-ctlr to be the default ingress.

**Comment by mdditt2000** [comment]
@dlhace that should be fine. I was working with another rancher deployment today. Give me a min while i consume your configuration into my K8S cluster

**Comment by mdditt2000** [comment]
@dlhace created a quick working example

https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.3/github/1774

Now let me dig into your issue

**Comment by mdditt2000** [comment]
@dlhace 

Created nicely

```
2021/03/31 22:16:27 [DEBUG] [AS3] Posting AS3 Declaration
2021/03/31 22:16:27 [DEBUG] [AS3] posting request to https://192.168.200.60/mgmt/shared/appsvcs/declare/
2021/03/31 22:16:30 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s --- message: success
2021/03/31 22:16:30 [DEBUG] [AS3] Preparing response message to response handler
2021/03/31 22:16:30 [DEBUG] [AS3] Sent response message to response handler
```

I think you are so close. 

Please copy the files

**CIS deployment manifest**

https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.3/github/1774/cis-deployment/f5-cluster-deployment.yaml

Note: you can removed namespace default. 

**Service and deployment**

https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.3/github/1774/reported-issue/pod-deployment/echoserver2-service.yaml

Change the port to 8080 which is the same as your deployment

Still working on the ingress. Page not coming up but it might be the host header. Need to create a host in DNS.

**Comment by mdditt2000** [comment]
@dlhace works great. no changes needed in your ingress. Just the above changes. Also make sure you using the AS3 extension. 

![image](https://user-images.githubusercontent.com/12733938/113220070-6d53d800-9237-11eb-8d9f-753b7fd696f3.png)

If you need more help, tomorrow we could setup a quick zoom session. Thanks Mark

**Comment by dlhace** [comment]
So switching the 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

to
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

fixed the problem with the deploy.  I tried it both with the helm install as well as the manual cis deploy install.
