### ISSUE TITLE
Openshift compatibility

### ISSUE THREAD

**Issue by renatonader** [F5Networks/k8s-bigip-ctlr#1775]
Hi Guys.

I was searching for some compatibility matrix or similar to know which CIS versions are compatible with the available Openshift versions.

I've found CIS release notes below but we don't have compatibility information for all of CIS versions.
https://clouddocs.f5.com/containers/latest/reference/release-notes.html#release-notes

Is there any other documentation that shows the compatibility for all CIS versions?

Thanks.

**Comment by mdditt2000** [comment]
@renatonader here you go

https://clouddocs.f5.com/containers/latest/userguide/what-is.html#container-ingress-service-compatibility

Let me know if you have questions

**Comment by mdditt2000** [comment]
Closing issue
