### ISSUE TITLE
DOC: document default value of  --as3-post-delay

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1797]
#### Setup Details
 CIS Version : 2.3.0      

#### Description  
 
This parameter doesn't have specified the default value used:

```
      --as3-post-delay int                Optional, time (in seconds) that CIS waits to post the available AS3 declaration.
```

**Comment by trinaths** [comment]
@alonsocamaro  can you share docs page you are looking into ?

**Comment by alonsocamaro** [comment]
It is the command line --help

**Comment by trinaths** [comment]
its 0, which mean we post AS3 immediately.
