### ISSUE TITLE
openshift install CIS with ingresslink issue(unknow flag: ingress-link-mode

### ISSUE THREAD

**Issue by x599123** [F5Networks/k8s-bigip-ctlr#1807]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 13.1.1.5 VE  
 AS3 Version:  3.25.0
 Agent Mode: AS3/CCCL       
 Orchestration: Openshift    
 Orchestration Version: 4.5.6       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>
![圖片](https://user-images.githubusercontent.com/39082455/116220225-0ca8b400-a77f-11eb-84ea-0d57348904ad.png)
![圖片](https://user-images.githubusercontent.com/39082455/116220234-0f0b0e00-a77f-11eb-8a8a-f8a8461d3e86.png)

#### Description  
I want to achieve LAB 4.1 in openshift but there is some problem.
https://clouddocs.f5.com/training/community/containers/html/class1/module4/lab1.html

#### Steps To Reproduce
1)
![圖片](https://user-images.githubusercontent.com/39082455/116219796-999f3d80-a77e-11eb-9305-0d6b386b56d6.png)
2)
![圖片](https://user-images.githubusercontent.com/39082455/116220140-f864b700-a77e-11eb-806a-e23bdec056ac.png)
3)
![圖片](https://user-images.githubusercontent.com/39082455/116220159-fc90d480-a77e-11eb-81ec-2b82b2cd5388.png)

**Comment by trinaths** [comment]
What is the CIS version you are using? can you share operator YAML file

**Comment by trinaths** [comment]
This issue is fixed in 2.3. Use CIS > 2.3 and verify. Closing this issue.
