### ISSUE TITLE
K8S BIG-IP Controller upload old certificate to BIG-IP

### ISSUE THREAD

**Issue by janault** [F5Networks/k8s-bigip-ctlr#1808]
#### Setup Details
 CIS Version : 2.4.0      
 Build: f5networks/k8s-bigip-ctlr:2.4.0
 BIGIP Version: BIG-IP 14.1.4.1 Build 0.0.4 Point Release 1
 AS3 Version: 3.25.0 Build: 3
 Agent Mode: AS3
 Orchestration: K8S      
 Orchestration Version: 1.18.10      
 Pool Mode: Cluster      
 Additional Setup details: CRD mode

#### Description  
Re-creation of certificate secret under the same name (e.g. certificate renewal) in k8s causes controller uploading of previous version of the certificate when creating a virtualServer with tlsProfile. Even if I after that delete everything from kubernetes (which efectively cleans up the BIGIP partition) and then create a new VirtualServer with completely different certificate the controller uploads both new and previous certificate. After restarting the controller and re-creating virtualServer with tlsProfile everything it is working again as expected - i.e. it seems that certificates are stored in some kind of cache inside controller and this cache is not renewed during operation.

#### Steps To Reproduce
1) Create ClusterIssuer selfsigned-issuer (kubectl apply -f selfsigned-issuer.yaml)
2) Create Certificate issued by selfsigned-issuer (kubectl apply -f https-vs-monitor-certificate.yaml)
3) Create testing deployment with virtualServer and TLSProfile (kubectl apply -f https-vs-monitor.yaml)
4) Check certificate expiration in Certificate Management and compare it with certificate in k8s (kubectl describe certificate hello-kubernetes-tls -n test-https-vs-monitor). They are both same.
5) Delete everything - certificate, testing deployment (kubectl delete -f https-vs-monitor-certificate.yaml; (kubectl apply -f https-vs-monitor.yaml) and check whether certificate has been deleted from BIG-IP.
6) Recreate certificate and testing deployment (kubectl apply -f https-vs-monitor-certificate.yaml; kubectl apply -f https-vs-monitor.yaml)
6.b) Create certificate with new name, TLSProfile with this name and testing deployment (kubectl apply -f https-vs-monitor-certificate2.yaml; kubectl apply -f https-vs-monitor2.yaml)
7) Check certificate expiration in Certificate Management and compare it with certificate in k8s (kubectl describe certificate hello-kubernetes-tls -n test-https-vs-monitor). Does not match - uploaded cert is the previous one.
7.b) Check certificates in BIG-IP - there are two certificates (hello-kubernetes-tls, hello-kubernetes-tls2), first is the previous one, which doesn't even exist in k8s.

#### Expected Result 
Controller uploads new (newly issued) certificate.

#### Actual Result  
Controller uploads old (cached) certificates.

#### Diagnostic Information
[https-vs-monitor.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6383543/https-vs-monitor.yaml.txt)
[https-vs-monitor2.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6383544/https-vs-monitor2.yaml.txt)
[selfsigned-issuer.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6383545/selfsigned-issuer.yaml.txt)
[https-vs-monitor-certificate.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6383536/https-vs-monitor-certificate.yaml.txt)
[https-vs-monitor-certificate2.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6383541/https-vs-monitor-certificate2.yaml.txt)

**Comment by trinaths** [comment]
@janault - Can you create the certificate with another name and try the above scenario. CIS doesn't listen on Certificate changes. However Changes to TLS profile are processed by CIS. Please share your findings. Update the TLS with new k8s secret and check whether new certificate is updated and old certificate is removed.

**Comment by janault** [comment]
@trinaths Yes, i try create certificate with new name, then create TLSProfile and virtualServer with this new certificate - steps 6b - 7b. After creating virtualServer, controller upload both certificates on F5 (old - which doesn't exist in K8S, new - which is OK and with new name). I assumed that CIS doesn't listen on Certificate changes, so I deleted certificate, TLSProfile, virtualServer firstly and then I re-create it, but controller upload old certificate, which no longer exist in K8S.

**Comment by trinaths** [comment]
@janault- Thank you for sharing your findings. We will resolve this issue in upcoming releases. Created JIRA CONTCNTR-2600 for internal PM tracking.

**Comment by trinaths** [comment]
Fix in v2.4.1. Closing this issue.
