### ISSUE TITLE
CIS' AS3 config map should not create shared objects 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1809]
#### Setup Details
 CIS Version : 2.3      
 BIGIP Version: Big IP 15.1
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: OSCP      
 Orchestration Version:       
 Pool Mode: Cluster
 Additional Setup details: vxlan

#### Description  

As per conversation with @mdditt2000 CIS's AS3 config maps should not contain declarations of shared objects such as:

```
  template: |
    {   
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "service-tcp",
            "remark": "Ingress to trigger FDB Push",
            "Common": {
                "class": "Tenant",
                "Shared": {
                    "class": "Application",
                    "template": "shared",
                    "sharedWildCardVirtualAddress": {
                      "class": "Service_Address",
                      "icmpEcho": "disable",
                      "virtualAddress": "0.0.0.0/0"
                    },

```

At present CIS doesn't either:

- inhibit posting this type of problematic sections and write a warning about it. For this AS3 (in BIG-IP) could ignore such a configuration and warn about it when the client is CIS (ie:by checking the User-Agent header).
-  documents this fact. In https://clouddocs.f5.com/containers/latest/userguide/config-map.html doesn't make any mention about this.

**Comment by alonsocamaro** [comment]
Doing some tests I triggered the following error:

```
2021/04/28 09:10:03 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/Egress_Common/Egress_Common_SVC/NAT46_ocp-egress-1/virtualAddresses/0/use: must contain path pointing into same Application (or /same-Tenant/Shared or /Common/Shared)] message:declaration is invalid]
```

**Comment by trinaths** [comment]
@alonsocamaro - Can you check posting the same AS3 declaration via a ReSTful Client and see any AS3 errors?

**Comment by trinaths** [comment]
> Doing some tests I triggered the following error:
> 
> ```
> 2021/04/28 09:10:03 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/Egress_Common/Egress_Common_SVC/NAT46_ocp-egress-1/virtualAddresses/0/use: must contain path pointing into same Application (or /same-Tenant/Shared or /Common/Shared)] message:declaration is invalid]
> ```
> 
> Which suggests that /Common/Shared is allowed. So this doesn't seem to be an issue actually.

Can we close this issue then ?

**Comment by trinaths** [comment]
> Doing some tests I triggered the following error:
> 
> ```
> 2021/04/28 09:10:03 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/Egress_Common/Egress_Common_SVC/NAT46_ocp-egress-1/virtualAddresses/0/use: must contain path pointing into same Application (or /same-Tenant/Shared or /Common/Shared)] message:declaration is invalid]
> ```
> 
> Which suggests that /Common/Shared is allowed. So this doesn't seem to be an issue actually.

Closing this issue.
