### ISSUE TITLE
2x broken links in docs to CRD examples

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#1815]
#### Description  
 On [this page](https://clouddocs.f5.com/containers/latest/userguide/crd/#examples-repository) in the documentation there is a link to "View more examples on GitHub"

It links to this location which gives me a 404: https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/_static/config_examples/crd

It should link to this location: https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/crd

I.e. it looks like "_static" needs to be removed from that URL.

#### Steps To Reproduce
1) Follow link to CRD examples from [this page in documentation](https://clouddocs.f5.com/containers/latest/userguide/crd/#examples-repository)

**Comment by mikeoleary** [comment]
I just noticed another broken link on the [same page](https://clouddocs.f5.com/containers/latest/userguide/crd/#examples-repository) in docs. The link to the customresourcefinitions file is broken, and again just "_static/" needs to be removed. Thanks!
Current link: https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/_static/config_examples/crd/Install/customresourcedefinitions.yml
Correct link: https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/crd/Install/customresourcedefinitions.yml

**Comment by mikeoleary** [comment]
As I go through the documentation, every link I've come across to the examples on github has been broken in the same, with "_static/" needing to be removed from the URL. So it's more than just those 2 broken links, but I'll leave it to you guys to find the links and update them, thanks!

**Comment by mdditt2000** [comment]
@mikeoleary a change was make last week to the example director. This is broken the doc examples on clouddocs. Getting this resolved ASAP.

**Comment by mdditt2000** [comment]
Issue is resolved with the latest merge request. Closing issue
