### ISSUE TITLE
Unable to create big-ip node in the cloud with bigip-node.yaml

### ISSUE THREAD

**Issue by laul7klau** [F5Networks/k8s-bigip-ctlr#1817]
The following procedure 
https://clouddocs.f5.com/containers/latest/userguide/cis-helm.html#id7
step 6 requires us to create a BIG-IP node using the config in bigip-node.yaml.
This is possible on-prem, but in the cloud (tested on AWS), creating a node effectively creates a Cloud instance. 
So the command:
kubectl create -f bigip-node.yaml
completes, but after running kubectl get nodes 
the node disappears after 3-4 secs. This i think is expected as AWS doesn't know know which ami image to launch.
Without running this step, the arp and fdb entries are successfully populated on the BIG-IP for me. Monitoring packets reaches the pods, but without bigip-node.yaml, the big-ip is not part of the k8 flannel network and packets are not returned to the bigipp. How do we implement bigip-node.yaml in the cloud, e.g. AWS?
My pod subnet is different from my node subnet

**Comment by mdditt2000** [comment]
@laul7klau are you using EKS?

**Comment by laul7klau** [comment]
In an eksctl created cluster, AWS uses its own CNI plugin instead of flannel vxlan and one has to manually install flannel. This involves setting up our own etcd database which is not what i want. 
So i'm trying kops. kops installs for us flannel vxlan in AWS however, kops enforcement requires that the node subnet not overlap the pod subnet. So i'm trying flannel vxlan with udp encapsulation, and met the problem.

**Comment by laul7klau** [comment]
i guess I'm trying to confirm if "bigip-node.yaml" is essential in getting BIG-IP CIS to work with flannel vxlan. And if it is, I can't see how we can apply it in the cloud to create  a node. 
This may not be a bug. I couldn't find the 'documentation' label when creating the issue.

**Comment by laul7klau** [comment]
Thanks for your response. I decided not to use flannel with a vxlan backend as the setup just/simply works with direct routing. The vxlan backend slows down the performance with CNI.0 and flannel.1.  Despite setting host-gw, performance still lags behind direct networking.
https://www.nginx.com/blog/testing-performance-nginx-ingress-controller-kubernetes/
https://storyboard.openstack.org/#!/story/1518605
