### ISSUE TITLE
LoadBalancer Service Type: healthCheckNodePort to be supported

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/k8s-bigip-ctlr#1822]
#### Title
LoadBalancer Service Type: healthCheckNodePort to be supported

#### Description
CIS 2.4 LB Service Type does not seem to support healthCheckNodePort when used along with externalTrafficPolicy when set to "local"
When activating LB Service type with CIS, all k8s nodeports nodes are targeted which causes unwated traffic forwarding (tromboning) within the cluster to reach actual pods.

#### Actual Problem
Load Balancer Service type feature needs to be algined with k8S spec aka supporting service.spec.externalTrafficPolicy and service.spec.healthCheckNodePort
See here : https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

#### Solution Proposed
CIS to support healthCheckNodePort as part of LB service type implementation

**Comment by mdditt2000** [comment]
Jira added for PM tracking CONTCNTR-2571. @tewfikm enhancement is CIS 2.5

**Comment by mdditt2000** [comment]
@tewfikm Health monitor support for service Type LB is complete. 

**Service Type LB Enhancements:**

- Added support for Multiport service
- Added support for HealthMonitor

However this is a-little different than adding healthCheckNodePort when used along with externalTrafficPolicy. Health monitor support is a higher priority

**Comment by mdditt2000** [comment]
Added health monitors to Service type LB

```
annotations:
    cis.f5.com/ipamLabel: Test
    cis.f5.com/policyName: type-lb
    cis.f5.com/health: '{"interval": 10, "timeout": 31}'
```
Example https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.9/servicetypelb_nginx_firewall/nginx-config/nginx-service.yaml

Closing this issue out
