### ISSUE TITLE
Enhancement request : CIS to support Efficient IP IPAM on the Roadmap

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/k8s-bigip-ctlr#1823]
#### Title
Enhancement request : CIS to support Efficient IP IPAM

#### Description
Prospect who is testing CIS 2.4 and FIC 0.12 is asking for any plan to support Efficient IP IPAM

https://www.efficientip.com/products/solidserver/

#### Actual Problem
Several major customers in France are using Efficient IP DDI (DNS, DHCP, IPAM) as global solution for their IT system (instead of the other well known IPAM vendor). 
This existing BIG-IP customer is having mulitple OCP clusters and dozens of BIG-IP and is interested in deploying CIS with OCP.

Customer received CIS/FIC demo but he is asking to leverage his deployed IPAM solution rather than deploying another one.

#### Solution Proposed
Evaluate effort to support Efficient IP DDI as IPAM that CIS can use. 
Efficient IP DDI is having plugins and REST API and propose already some cloud integrations.

https://www.efficientip.com/solidserver-api-for-it-automation/

#### Alternatives
To be investigated : 
- FIC to act as a IPAM proxy against Efficient IP DDI ?
- CIS to webhook Efficient IP DDI ?

#### Additional context
Reach out in unicast for customer details.

**Comment by trinaths** [comment]
Created CONTCNTR-2669 for PM tracking

**Comment by mdditt2000** [comment]
Keep the JIRA story open for tracking. Currently CIS to support Efficient IP IPAM is out of scope. Closing issue
