### ISSUE TITLE
Documentation Bug: Ingress Link: Docs do not mention required namespace and labels.

### ISSUE THREAD

**Issue by dstrohl** [F5Networks/k8s-bigip-ctlr#1826]
From: https://clouddocs.f5.com/containers/latest/userguide/ingresslink/

The documentation indicates that "The name of the app label selector in IngressLink resource should match the labels of the nginx-ingress service (nginx-service.yaml file)." however, this is incorrect (or at the least misleading and incomplete).

Expected:

    Note: The name of the app label selector in IngressLink resource must be set to "nginx-ingress".

There should also be notes on the earlier configuration steps to insure that the namespace is correctly set to the required setting ("kube-system" and that the app-label set in the NGINX config is also set to "nginx-ingress".

**Comment by trinaths** [comment]
Created CONTCNTR-2672 for PM tracking

**Comment by trinaths** [comment]
Document is updated. Closing this issue.
