### ISSUE TITLE
Documentation: Ingress Link, docs are currently only an example.

### ISSUE THREAD

**Issue by dstrohl** [F5Networks/k8s-bigip-ctlr#1827]
Currently the docs for ingress link are only an example, there is no explanation about what the various steps do or what different paths could be taken, or how this could be deployed in a customers environment.

#### Expected
An example is great in docs, but simply providing an example does not help a customer understand how a product actually needs to be configured in various environments.  

The documentation should describe the configuration files, it should note any required settings (ex. namespace and app label) but it should also explain the options that can be changed and what they mean.   Of the items in the instructions, what is simply an example and what is required by the system?

The documentation should also explain how this works (right now the explanation is more of a marketing elevator pitch than an explanation about what the product does).  great, it is an elegant solution and unifies the technologies... how?  what does it do?  Can I configure NGINX from a BIG-IP?  can I set the BIG-IP certificate within NGINX?

The documentation does not cover anything about any requirements around KIC/NGINX.  if I followed the example in the docs, nothing would actually work.

**Comment by trinaths** [comment]
Created CONTCNTR-2672 for PM tracking

**Comment by trinaths** [comment]
@dstrohl  - Customer environment varies as per their requirements. The Document is more generic and captures more info on how to use IngressLink. Please refer to the [Prerequisites](https://clouddocs.f5.com/containers/latest/userguide/ingresslink/#prerequisites) for required environment setup. 

Please refer to https://clouddocs.f5.com/training/community/containers/html/class1/module4/lab1.html or https://devcentral.f5.com/s/articles/My-first-deployment-of-IngressLink for more info. 

Closing this issue.
