### ISSUE TITLE
Ability to assign ingress IP from specific CIDR block

### ISSUE THREAD

**Issue by ofen** [F5Networks/k8s-bigip-ctlr#1835]
#### Description
Current implementation provide two ways to assign IP to ingress:
1. Using 1 shared IP for all ingresses in app group
2. Assign IP manually via ingress annotation

#### Actual Problem
We got usercase when users wants to have something similarity to alb ingress controller when user just creates ingress and loadbalancer IP automagically assigns to it.

#### Additional context
The idea is to add functionality to provide CIDR block to ingress controller and let it select/allocated/free IP during ingress spec creating/deletion.

**Comment by trinaths** [comment]
@ofen  - Suggest use CRDs. With 2.3+ we have IPAM support enabled with CRDs.

**Comment by trinaths** [comment]
Closing this issue.
