### ISSUE TITLE
BIGIP admin password in CIS logs

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/k8s-bigip-ctlr#1839]
Hello,
As we understand, CIS uses the REST API to login to BIGIP to push config changes. The question is does it log the BIGIP admin password in the CIS pod logs? We raise this question in terms of security that if someone has access to CIS pod logs if the password is in clear format and can be readable.

Thanks
Prabhat

**Comment by trinaths** [comment]
@prabhatkarki  - CIS will not log sensitive info. Can you share logs via teams, just to review the info.

**Comment by prabhatkarki** [comment]
Thnaks Trinath.
I don’t have any logs to show that it included password. It was just a question whether or not CIS will log the BIGIP password.

Regards,

Prabhat Karki | Solution Engineer
M +1 (469)-236-3954

[f5-logo-rgb-30x30.jpg]<https://f5.com/>



From: Trinath Somanchi ***@***.***>
Reply-To: F5Networks/k8s-bigip-ctlr ***@***.***>
Date: Wednesday, June 2, 2021 at 10:06 AM
To: F5Networks/k8s-bigip-ctlr ***@***.***>
Cc: Prabhat Karki <P.Karki@F5.com>, Mention ***@***.***>
Subject: Re: [F5Networks/k8s-bigip-ctlr] BIGIP admin password in CIS logs (#1839)


EXTERNAL MAIL: ***@***.***

@prabhatkarki<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprabhatkarki&data=04%7C01%7CP.Karki%40F5.com%7Cb800ed21f9654a24462808d925d7ffeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637582431907504066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JDTVyKA5j0EI3oDx7pDUHcAz4MwYg8A%2FmJcU4ogQu%2F4%3D&reserved=0> - CIS will not log sensitive info. Can you share logs via teams, just to review the info.

**Comment by trinaths** [comment]
Closing this issue. No workaround required.
