### ISSUE TITLE
CIS fails to complete AS3 declaration that worked with previous version

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#1846]
#### Setup Details
 CIS Version : 2.2.3 
 Build: f5networks/k8s-bigip-ctlr:2.2.3       
 BIGIP Version: Big IP 15.1.0.5     
 AS3 Version: 3.22.1      
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:  1.18     
 Pool Mode: Nodeport      
 Additional Setup details: Calico

#### Description  
Similar to https://github.com/F5Networks/k8s-bigip-ctlr/issues/1602  but using a version that is supposed to have fixed this, hence this issue.   

#### Steps To Reproduce
1) Confirm existing configmap that works with CIS v1.14
2) Upgrade CIS to v2.2.3 by modifying the image version in deployment manifest
3) Confirm errors in logs of controller when it boots without modifying anything like cm

#### Expected Result 
CIS will poll and discover known working configmaps without error. 
 
Also, if 2.2.2 supports AS3 3.25, I expect 2.2.3 supports AS3 3.22.1
Also it says Issue #1602 is fixed in 2.2.2

#### Actual Result  
Error with schema

#### Diagnostic Information
```logs
2021/05/31 13:41:12 [INFO] [AS3] Initializing AS3 Agent
2021/05/31 13:41:23 [ERROR] [AS3] Big-IP Responded with code: 422
2021/05/31 13:41:23 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/schemaVersion: should be equal to one of the allowed values ["3.0.0","3.1.0","3.2.0","3.3.0","3.4.0","3.5.0","3.6.0","3.7.0","3.8.0","3.9.0","3.10.0","3.11.0","3.12.0","3.13.0","3.14.0","3.15.0","3.16.0","3.17.0","3.18.0","3.19.0","3.20.0","3.21.0","3.22.0"]] message:declaration is invalid]
2021/05/31 13:41:23 [INFO] [CORE] NodePoller (0xc000654090) registering new listener: 0x14a4aa0
2021/05/31 13:41:23 [INFO] [CORE] NodePoller started: (0xc000654090)
2021/05/31 13:41:23 [INFO] [CORE] Watching Ingress resources.
2021/05/31 13:41:23 [INFO] [CORE] Watching ConfigMap resources.
2021/05/31 13:41:23 [INFO] [CORE] Handling ConfigMap resource events.
2021/05/31 13:41:23 [INFO] [CORE] Handling Ingress resource events.
2021/05/31 13:41:23 [INFO] [CORE] Registered BigIP Metrics
2021/05/31 13:41:33 [ERROR] [AS3] Template is not valid. see errors
2021/05/31 13:41:33 [ERROR] - declaration: Must validate "then" as "if" was valid

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)

2021/05/31 13:41:33 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/05/31 13:41:33 [ERROR] - declaration: Must validate all the schemas (allOf)

2021/05/31 13:41:33 [ERROR] - declaration: Must validate "then" as "if" was valid

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)

2021/05/31 13:41:33 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/05/31 13:41:33 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/05/31 13:41:33 [ERROR] - declaration: Must validate all the schemas (allOf)
```  

Corresponding configmap snippet:
```
{
    "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.13.0",
        "id": "kibaapp",
        "label": "f5-istio",
        "remark": "An HTTP application",
        "app1": {
          "class": "Tenant",
          "app_core": {
            "class": "Application",
            "template": "generic",
            "serviceUDP1": {
              "class": "Service_UDP",
              "virtualPort": 6000,
              "virtualAddresses": [
              {
                "use": "app_addr_core"
              }
              ],
              "pool": "app_pool_core1"
            },
```

**Comment by tkam8** [comment]
I want to update that I have seen this yet again in another cluster deploying CIS v2.2.3 for the first time, but using a known working configmap. 
The workaround to move past the "declaration.members.0.serverAddresses: Invalid type" error was to change the servicePort so that it matched the port that the service was actually mapping to for the app. I thought this was fixed and not applicable for 2.2.3, but it seems it is. Please reconfirm.

**Comment by tkam8** [comment]
AS3 Version: 3.22.1 @mdditt2000

**Comment by trinaths** [comment]
@tkam8 

`declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null`

The above error is observed when service endpoints cannot be fetched with the `servicePort` value defined. 

Please check if _servicePort_ value is matching with that in service definition.
  
Only for CIS release 2.2.1, AS3 configmap expects the `servicePort` value to be equal to nodeport of service definition. However, this issue was fixed and from later releases, AS3 configmap expects **service exposed _port_** instead of nodeport value.

**Comment by tkam8** [comment]
I understand now the problem I am having, thanks to @trinaths 

Basically, in v2.x, the servicePort must match the port (not the nodeport one) exposed in the service definition. 
In v1.14, I think this was ignored so we need to make sure this is one area to pay attention to when upgrading. 

Suggestion: Can we add this to documentation below (in "Behavioral Changes" section) to help everyone out? I could not find any mention of this on clouddocs other than the github issue mentioned earlier. Happy to be proven wrong. 
Suggested doc addition: 
```
In v2.x, the servicePort must match the port (not the nodeport one) exposed in the service definition. 
```
https://clouddocs.f5.com/containers/latest/userguide/cis-upgrade.html
