### ISSUE TITLE
Documentation: VXLAN Local Address must be Mgmt or SelfIP

### ISSUE THREAD

**Issue by fpieressa** [F5Networks/k8s-bigip-ctlr#1847]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  
We have found some examples where the VXLAN Local Address used was the Mgmt interface, and some others where a SelfIP is used.  In https://clouddocs.f5.com/containers/latest/userguide/openshift/#creating-vxlan-tunnels-on-openshift-cluster Step 3 is not clear which Local Address must be used.  Also is not clear (at least for me) which printscreen correspond to which Step, and I think is wrong the prinstcreen with the command (is the IP 192.168.200.60 or 192.168.200.91?) on Step 2 and Step 4

#### Steps To Reproduce
Check in the documentation https://clouddocs.f5.com/containers/latest/userguide/openshift/#creating-vxlan-tunnels-on-openshift-cluster Step 2, Step 3 and Step 4

#### Expected Result 

We expect the confirmation which Local Address is excpected (Mgmt, SelfIP or any), a consistence with IPs used, and be more clear which printscreen correspond with which step.

#### Actual Result  

I think is a little confused the VXLAN Configuration

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment]
Created CONTCNTR-2731 for internal PM tracking

**Comment by trinaths** [comment]
Document updated. Closing the issue.
