### ISSUE TITLE
Large Deployment file doesn't assign the correct pool

### ISSUE THREAD

**Issue by wturnage** [F5Networks/k8s-bigip-ctlr#1849]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.1.4      
 AS3 Version: 3.28
 Agent Mode: AS3     
 Orchestration: K8S     
 Orchestration Version:  1.20.4
 Pool Mode: Nodeport      
 Additional Setup details: Rancher supported K8S cluster, nodes are running RHEL 7.9 with  docker-ce-20.10.6-3.el7
F5 support case: C3559209

#### Description  
 Deployments that create multiple Virtual Servers with the same IP address but different port numbers deploys incorrectly. It will create some Virtual Servers correctly, but other will have the wrong port in the Virtual Servers  traffic policy.

If I then go to delete the VS using kubectl the virtual servers will not get delete on the LTM, but will cause high CPU usage.
I will then have to delete the f5-bigip-ctlr pod so it'll stop causing the high load on the LTM.

#### Steps To Reproduce
1) deploy file below
2) confirm some VS have wrong pool in traffic policy assigned
3) delete all the VS using kubectl
4) observe the high load. 

This issue will happen whether I include the virtualServerName field or not.

#### Expected Result 
The correct pool gets assigned to the correct VS traffic policy. I don't see any issues with VS creation with a single port and IP address.

#### Actual Result  

some Virtual Servers deploy correctly, but other will have the wrong port in the Virtual Servers  traffic policy

#### Diagnostic Information
```deployment-file.yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: ns-name-uat
  name: app-service-name-8080
  labels:
    f5cr: "true"
spec:
  virtualServerName: app-name-uat
  virtualServerAddress: "10.155.155.19"
  virtualServerHTTPSPort: 8080
  tlsProfileName: app-wildcard
  httpTraffic: none
  allowVlans:
  - "/Common/Ent-Prod-DMZ-LTM-Private"
  pools:
  - service: app-service-name
    servicePort: 8080
    monitor:
     type: https
     send: GET /\r\n 
     interval: 5
---

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: ns-name-uat
  name: app-service-name-8081
  labels:
    f5cr: "true"
spec:
  virtualServerName: app-name-uat
  virtualServerAddress: "10.155.155.19"
  virtualServerHTTPSPort: 8081
  tlsProfileName: app-wildcard
  httpTraffic: none
  allowVlans:
  - "/Common/Ent-Prod-DMZ-LTM-Private"
  pools:
  - service: app-service-name
    servicePort: 8081
    monitor:
     type: https
     send: GET /\r\n 
     interval: 5

---

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: ns-name-uat
  name: app-service-name-8082
  labels:
    f5cr: "true"
spec:
  virtualServerName: app-name-uat
  virtualServerAddress: "10.155.155.19"
  virtualServerHTTPSPort: 8082
  tlsProfileName: app-wildcard
  httpTraffic: none
  allowVlans:
  - "/Common/Ent-Prod-DMZ-LTM-Private"
  pools:
  - service: app-service-name
    servicePort: 8082
    monitor:
     type: https
     send: GET /\r\n 
     interval: 5
---

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: ns-name-uat
  name: app-service-name-8083
  labels:
    f5cr: "true"
spec:
  virtualServerName: app-name-uat
  virtualServerAddress: "10.155.155.19"
  virtualServerHTTPSPort: 8083
  tlsProfileName: app-wildcard
  httpTraffic: none
  allowVlans:
  - "/Common/Ent-Prod-DMZ-LTM-Private"
  pools:
  - service: app-service-name
    servicePort: 8083
    monitor:
     type: https
     send: GET /\r\n 
     interval: 5
---

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: ns-name-uat
  name: app-service-name-8084
  labels:
    f5cr: "true"
spec:
  virtualServerName: app-name-uat
  virtualServerAddress: "10.155.155.19"
  virtualServerHTTPSPort: 8084
  tlsProfileName: app-wildcard
  httpTraffic: none
  allowVlans:
  - "/Common/Ent-Prod-DMZ-LTM-Private"
  pools:
  - service: app-service-name
    servicePort: 8084
    monitor:
     type: https
     send: GET /\r\n 
     interval: 5

```  
File continues through servicePort 8099. I've chopped off the file as not to submit a wall a text.

**Comment by trinaths** [comment]
Created CONTCNTR-2653 for internal PM tracking.

**Comment by trinaths** [comment]
Fixed with https://github.com/F5Networks/k8s-bigip-ctlr/pull/1930
