### ISSUE TITLE
Documentation: Add httpTraffic setting in clouddocs

### ISSUE THREAD

**Issue by de1chk1nd** [F5Networks/k8s-bigip-ctlr#1852]
#### Title
Add info about ssl-redirect in virtualserver crd documentation (httpTraffic: xyz)

#### Description
missing info on http-redirect traffic as described here:
https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/crd/tls/tls-with-httpredirect

in our cloud docs documentaion here:
https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html#

#### Actual Problem
incomplete documentation about possible features in CRD declaration

#### Solution Proposed
Add "httpTraffic" into VirtualServer Components section
https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html#

#### Alternatives
n/a

#### Additional context
n/a

**Comment by trinaths** [comment]
Created CONTCNTR-2728 for internal PM tracking.

**Comment by trinaths** [comment]
Document updated. Closing this issue.
