### ISSUE TITLE
Service Type LoadBalancer with multiple CIS and multiple namespaces

### ISSUE THREAD

**Issue by renatonader** [F5Networks/k8s-bigip-ctlr#1862]
We are trying to use multiple CIS to deploy Service types LoadBalancer in different namespaces, but it's not working.

We have used the following article to configure one single CIS together with one F5 IPAM and it works fine.
https://clouddocs.f5.com/containers/latest/userguide/loadbalancer/

When trying to use multiple CIS to deploy objects in different namespaces, F5 IPAM seems to share the same IP addresses with the two CIS and then it doesn't work generating an IP address conflict at the moment of the deploy for a new service.

We have an ingress environment running multiple CIS and multiple namespaces and it works fine, but we'd like to know if its possible to do that in this new environment for Service Type LoadBalancer.

**Comment by trinaths** [comment]
@renatonader  Please share sample YAML file for this issue. that helps better understand the resources and CIS deployment args.

**Comment by renatonader** [comment]
> @renatonader Please share sample YAML file for this issue. that helps better understand the resources and CIS deployment args.

Hi Trinath.

Thanks for the response.

I'm attaching CIS and IPAM deployment files for both namespaces together with clusterrole files for also both of them.

The issue happens when all of them are deployed and only the first F5-IPAM's IP range is used for both namespaces.
The expected behaviour is that each CIS should use its own namespace F5-IPAM range, but both of them are using only one.
When we try to deploy a service using the second CIS, it returns a 422 error saying that the IP address is already in use.

[yaml.zip](https://github.com/F5Networks/k8s-bigip-ctlr/files/6664667/yaml.zip)

**Comment by trinaths** [comment]
@renatonader  - There are two IPAM deployments each for a CIS. you can deploy 1 IPAM for both CIS. Is that a setup requirement ?

**Comment by trinaths** [comment]
@renatonader - Suggest use 1 IPAM for all CIS deployment. Please assign appropriate labels to resources that the configured in IPAM so that different CIS resources use configured labels. Hope this helps.

**Comment by renatonader** [comment]
it worked. this way. Thanks Trinath
