### ISSUE TITLE
Health Monitors on Service Type LoadBalancer

### ISSUE THREAD

**Issue by renatonader** [F5Networks/k8s-bigip-ctlr#1863]
Hi all.

We are using CIS to deploy Services type LoadBalancer but couldn't find how to config health monitors in this case.
Have already tried to use Ingress health monitors annotations as shown on the follwing article but didn't work.
https://clouddocs.f5.com/containers/latest/userguide/ingress.html#ingress-health-monitors

Searching at the following article, can't find any annotation to configure it.
https://clouddocs.f5.com/containers/latest/userguide/loadbalancer/

Is it even possible to use health monitors for Service Type LoadBalancer?

**Comment by trinaths** [comment]
@renatonader  CIS 2.5 (next upcoming release) support HM for ServiceType LB. Closing this issue.
