### ISSUE TITLE
Doc - add detailed documentation for how to setup CRD

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1864]
Current document has very limited documentation about how to setup CRD, does CRD mode only works with CIS POD install on kube-system?

**Comment by trinaths** [comment]
@kylinsoong  - No. CRD can be either namespaced or cluster-scoped, as specified in the CRD's `scope` field. CustomResourceDefinitions themselves are non-namespaced and are available to all namespaces. They are dependent on CIS namespace.

Hope this helps. 

Please see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ for more info on CRDs. 

Closing this issue.
