### ISSUE TITLE
CIS will ignore service/configmap events change while F5 is offline or during reboot

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1866]
#### CIS will ignore service/configmap events change while F5 is offline or during reboot
The following is a real scenario from customer env:
- CIS works fine with it's peer F5  VE，configmap's config be push to VE
- VE offline due to VMware's breakdown
- configmap has changed, *one more service* be added during VMware's breakdown
- VMware recover, and VE get online again
- The *new added service*  during VMware's breakdown never be push to VE

After some investigation, only service/configmap change events can trigger CIS push operation,  seems this is default behavior.

Can we add an events change compensate mechanism , that CIS can store the service/configmap change events while VE is unavailable, then while VE available again, the stored events will be push to VE? 

#### CIS restart can trigger a full synch

CIS restart will trigger a full configmap synch with VE, this also can solve the above problem.

Also If deploy CIS before start VE, the CIS will re-start regularly, till VE is ready, however, if CIS's deploy is later than VE , then while VE unavaliable the CIS will not restart 

#### Workaround

Force CIS reboot can avoid this issue, so use a livenessProbe can work around

~~~
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
              - curl
              - -k
              - -s
              - -o
              - /dev/null
              - https://192.168.200.208
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
~~~

This need curl commands, but the debain base image don't support curl.

**Comment by trinaths** [comment]
@kylinsoong  I'm not clear of `debian base image`. Since we are using UBI as CIS base image using cURL is not an issue. Please verify with any latest CIS build. LivenessProbe should solve this issue.

**Comment by trinaths** [comment]
Closing this issue. Please reopen with further findings.
