### ISSUE TITLE
Service Type LoadBalancer Protocol UDP

### ISSUE THREAD

**Issue by renatonader** [F5Networks/k8s-bigip-ctlr#1872]
Trying to deploy a Service Type LoadBalancer using UDP protocol.

Tried to use the same manifest from the link below and changing TCP to UDP but the service keep being deployed as TCP.
https://clouddocs.f5.com/containers/latest/userguide/loadbalancer/

**Comment by trinaths** [comment]
Created JIRA CONTCNTR-2770 for internal PM tracking.
