### ISSUE TITLE
Support equivalent of nginx.ingress.kubernetes.io/rewrite-target in CiS

### ISSUE THREAD

**Issue by Spitfire1900** [F5Networks/k8s-bigip-ctlr#1882]
#### Title
Support equivalent of `nginx.ingress.kubernetes.io/rewrite-target` in CiS

#### Description
Support `nginx.ingress.kubernetes.io/rewrite-target` or an annotation with feature parity to `nginx.ingress.kubernetes.io/rewrite-target`.

#### Actual Problem
The annotation `nginx.ingress.kubernetes.io/rewrite-target: /$2` according to [Kubernetes nginx ingress docs](https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target) will take a request like `/api/v1/users` and rewrite it to `/v1/users`. I've not found a way in CiS using annotations to do the same.

#### Solution Proposed
Support `nginx.ingress.kubernetes.io/rewrite-target` or `ingress.kubernetes.io/rewrite-target`.

#### Alternatives
If this usecase can already be accomplished without any annotation changes improve parameter documentation at https://clouddocs.f5.com/containers/latest/userguide/ingress.html#ingress-resources.

**Comment by Spitfire1900** [comment]
The examples for rewrite-app-root look like they're prepending "/home" to the requested resource. In my case I want to strip the leading "/api" from a requested resource.

**Comment by Spitfire1900** [comment]
This looks to be related to #835.

**Comment by trinaths** [comment]
Yes. @Spitfire1900  This issue is similar to https://github.com/F5Networks/k8s-bigip-ctlr/issues/835 and we are unable to support this in ingress. Suggest to try CRDs in CIS.

Closing this issue.
