### ISSUE TITLE
docker hub image for 2.4 and 2.4.1 have same digest

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#1885]
#### Setup Details
 CIS Version : 2.4 and 2.4.1
 Build: f5networks/k8s-bigip-ctlr:2.4  
 BIGIP Version: n/a
 AS3 Version: n/a  

#### Description  
This is not a show-stopper for me but it looks like CIS v 2.4 was incorrectly overwritten in Docker Hub with 2.4.1? Please tell me if I am wrong but CIS images 2.4 and 2.4.1 both have identical digest of sha256:03f1beedfde479dfa3306fc8a9e32a5dcfcb9d2f38952d49d0ce0574bef9bfc9

If I pull image with tag 2.4 and check container logs at startup I can see 
````
2021/07/02 01:40:04 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.4.1
````

#### Steps To Reproduce
1) deploy CIS v 2.4 and read startup logs indicating you are running 2.4.1

#### Expected Result 
Expect that version 2.4 and 2.4.1 are different, which I believe they are, I just suspect the image is tagged incorrectly.

**Comment by trinaths** [comment]
Thanks for reporting this issue. It's updated now.
