### ISSUE TITLE
CIS errors if Ingress Rule contains Host with wildcard

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#1897]
#### Setup Details
 CIS Version : 2.4.1    
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.0.1      
 AS3 Version: 3.29
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster      

#### Description  
Please tell me if this is expected but I think this behavior is a problem. I have CIS 2.4.1 running.

It appears CIS logs errors when the "host" element of a rule includes a wildcard. However, this should be an allowed form of the hostname, according to [k8s docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#hostname-wildcards). 

Here is my Ingress resource, notice line 17:

````yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nginx-ingress
  name: nginx-ingress
  annotations:
    virtual-server.f5.com/ip: "10.1.10.10"
    virtual-server.f5.com/partition: "kubernetes"
spec:
  ingressClassName: f5
  defaultBackend:
    service:
      name: nginx-ingress
      port:
        number: 80
  rules:
  - host: "*.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-ingress
            port:
              number: 80

````

With the above ingress resource, CIS will show errors:
````
2021/07/13 17:55:31 [DEBUG] [RESOURCE] Configured policy: {ingress_10-1-10-10_80 kubernetes  [forwarding]  true [http] [0xc00007df20] /Common/first-match}
2021/07/13 17:55:31 [DEBUG] [CORE] Configured rule: {ingress_*.com__ingress_nginx-ingress_nginx-ingress *.com/ 0 [0xc0003bc060] [0xc000b8f200]}
2021/07/13 17:55:31 [DEBUG] [RESOURCE] Configured policy: {ingress_10-1-10-10_80 kubernetes  [forwarding]  true [http] [0xc0003bc0c0] /Common/first-match}
2021/07/13 17:55:31 [DEBUG] [CORE] Found endpoints for backend {ServiceName:nginx-ingress ServicePort:80 Namespace:nginx-ingress}: [{172.17.0.10 80 80 user-enabled} {172.17.0.8 80 80 user-enabled} {172.17.0.9 80 80 user-enabled}]
2021/07/13 17:55:31 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:nginx-ingress ServicePort:80 Namespace:nginx-ingress} and resource ingress_10-1-10-10_80
W0713 17:55:31.126570       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/07/13 17:55:31 [DEBUG] [CORE] Updated 1 of 1 virtual server configs, deleted 0
2021/07/13 17:55:31 [DEBUG] [CORE] Finished syncing virtual servers nginx-ingress in namespace nginx-ingress (19.422687ms)
2021/07/13 17:55:31 [ERROR] [AS3] Template is not valid. see errors
2021/07/13 17:55:31 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2021/07/13 17:55:31 [ERROR] - declaration.Shared: Must validate "then" as "if" was valid

2021/07/13 17:55:31 [ERROR] - declaration.Shared.rules.0.name: Does not match pattern '^[a-zA-Z0-9_\-.:%]+$'

2021/07/13 17:55:31 [ERROR] - declaration.Shared: Must validate all the schemas (allOf)


````

However when I edit the line 
````  - host: "*.com```` 
to 
````  - host: "example.com"````
then CIS works fine and populates the BIG-IP with virtual server and pool members as expected. It appears to not handle "*" in the host field.

#### Steps To Reproduce
1) Deploy CIS
2) Deploy Ingress resource as above
3) See errors in CIS logs
4) Edit resource to remove wildcard host, and CIS should then work as expected.

#### Expected Result 
I'd expect CIS to handle wildcards in the host field, or, provide an error message in logs that advised me of the problem with them.

#### Actual Result  
Error messages as above.

**Comment by trinaths** [comment]
@mikeoleary we don't currently support this. Do you have any requirement for this ? We have plans to support wildcard hostnames in TLS profile CRD.

**Comment by mikeoleary** [comment]
@trinaths thanks, I don't currently have a requirement for this. I came across this when manually editing Ingress resources and updating them from networking.k8s.io/v1beta1 to networking.k8s.io/v1. In my case I am working on a demo/user guide for a customer.

If this is not supported it would be helpful to see in logs and/or documentation because I suspect this is an easy issue to run into for others and it can consume a couple hrs of troubleshooting. Helpful log messages would be enough for me, in this case.

**Comment by trinaths** [comment]
@mikeoleary - Sure we will update the docs. Created CONTCNTR-2786 for internal tracking.

**Comment by mikeoleary** [comment]
@trinaths  - is it possible to also get some more helpful logs when this is encountered?

As you can see from the log messages above, it's difficult to know that the wildcard host is causing this issue.

**Comment by trinaths** [comment]
@mikeoleary  Since we don't process hostname wildcards, we cannot log it in a more descriptive way. We will document it.

**Comment by trinaths** [comment]
Created CONTCNTR-2850 for internal tracking.

**Comment by vincentmli** [comment]
this same error also applies to ingress with path like 

```
apiVersion: [networking.k8s.io/v1](https://networking.k8s.io/v1)

kind: Ingress

metadata:

 name: ing1-svc1-ns1

 namespace: ns1

 annotations:

   '[virtual-server.f5.com/ip](https://virtual-server.f5.com/ip)': "10.169.20.95"

   '[virtual-server.f5.com/partition](https://virtual-server.f5.com/partition)': "ns1"

spec:

 ingressClassName: f5

 rules:

 - http:

   paths:

   - path: /api/* <=======

    pathType: Prefix

    backend:

     service:

      name: svc1-ns1

      port:

       number: 80

```
