### ISSUE TITLE
Multiple type LB services with same IP address, different ports

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#1902]
#### Title
Multiple type LB services with same IP address, different ports

#### Description
We interested in using service type LB with Infoblox IPAM configuration. They will have many services, each in their own namespace. However, they would like to pull the same IP address and specify a unique port for each of these services. Can we support this?

#### Actual Problem
Today customer uses TransportServer so no problem today, but they have stated they would like type LB.

#### Solution Proposed
I am not sure how we could support this. Perhaps if there was a consistent label and unique port on each service that wanted to pull the same IP address, the IPAM controller could know to use the same IP address for different typeLB services. CIS could then handle the AS3 calls to create multiple VS's with same IP/unique ports.

#### Alternatives
Perhaps the alternative is challenging the current practice. If you have many services but intend to pull the same IP address for each of them, what is IPAM integration really getting you? There may be a good answer but I don't know. Perhaps if you have many services, but have groups of services that should get the same IP.

#### Additional context
Mark D asked me to submit this as a github issue. I can share details on use case privately.

**Comment by trinaths** [comment]
Created CONTCNTR-2787 for internal PM tracking

**Comment by mdditt2000** [comment]
@mikeoleary since there is no transport service to define a unique name per service its not possible to get this working. Customer must use a transport server with a unique name "fixed in CIS 2.9" - Issue https://github.com/F5Networks/k8s-bigip-ctlr/issues/2367 - DNS using udp or tcp 53 is a good example. Closing issue out
