### ISSUE TITLE
CIS cluster mode supported by Cilium Tunnel 

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#1906]
### With following two Cilium issues resolved, CIS cluster mode is supported by Cilium

1. https://github.com/cilium/cilium/issues/16517 
2. https://github.com/cilium/cilium/issues/16890

### if issue 1 is upstreamed in Cilium

to support CIS cluster mode, the BIG-IP vxlan setup is below:

Create a VXLAN tunnel profile 
<pre>
tmsh create net tunnels vxlan fl-vxlan port 8472 flooding-type none
</pre>

 Create Cilium VXLAN tunnel, note VNI key 68, Note key 1,2,3,4,5,6
 is reserved by Cilium, do not use them, see cilium bpf/node_config.h
<pre>
tmsh create net tunnels tunnel flannel_vxlan key 68 profile fl-vxlan local-address 10.169.72.15
</pre>

 Create the VXLAN tunnel self-IP, allow default service, allow none stops self ip ping.
  also make sure selfip subnet is /16, if /24, it may lead to unresolved pod ARP
<pre>
tmsh create net self 10.0.88.15 address 10.0.88.15/255.255.0.0 allow-service default vlan flannel_vxlan
</pre>

CIS needs to be patched with https://github.com/vincentmli/docs/blob/master/cilium-bigip/cis-cilium.diff.txt

### if both issue 1 and 2 is upstreamed in Cilium, CIS patch is not needed, BIG-IP will send ARP broadcast for pod,Cilium will do ARP reply for pod

Create a VXLAN tunnel profile with flooding-type set to multipoint
<pre>
tmsh create net tunnels vxlan fl-vxlan port 8472 flooding-type multipoint
</pre>

 Create Cilium VXLAN tunnel, note VNI key 68, Note key 1,2,3,4,5,6
 is reserved by Cilium, do not use them, see cilium bpf/node_config.h
<pre>
tmsh create net tunnels tunnel flannel_vxlan key 68 profile fl-vxlan local-address 10.169.72.15
</pre>

 Create the VXLAN tunnel self-IP, allow default service, allow none stops self ip ping.
  also make sure selfip subnet is /16, if /24, it may lead to unresolved pod ARP
<pre>
tmsh create net self 10.0.88.15 address 10.0.88.15/255.255.0.0 allow-service default vlan flannel_vxlan
</pre>

**Comment by trinaths** [comment]
Created CONTCNTR-2788 for internal PM tracking

**Comment by trinaths** [comment]
See https://github.com/mdditt2000/kubernetes-1-26/tree/main/cni/cilium 

Closed as done.
