### ISSUE TITLE
CIS CRD. Create a virtual server in a specific route domain.  

### ISSUE THREAD

**Issue by AlexanderSlinkov** [F5Networks/k8s-bigip-ctlr#1908]
#### Title
Creating a VS in a specific RD.

#### Description
Hi,

The CRDs work amazing, but I have a question below.
How I can create a VS in a specific RD (different from 0) using CIS CRD?
For example, without the CRD, I can do this with an appropriate ConfigMap, which will configure a specific RD number.
But in the CRD I can find option/possibility I want.

Thanks!

**Comment by de1chk1nd** [comment]
are you looking for adding All CRD VS in a specific route domain - or each VS in a different RD?

If first, try adding: "--default-route-domain=n", into the args section of your CIS controller deployment/manifest file (where n is route domain ID). This requires CIS v2.4 later

If second is what you are looking for, I do not know the answer :(

**Comment by AlexanderSlinkov** [comment]
Hi,

Yes, the first option worked for me.
I have not found a description for the "--default-route-domain' parameter on clouddocs.f5.com.

Thank you a lot!
 
P.S. but it would be great, if I could specify the appropriate RD number for VS via CRD.
