### ISSUE TITLE
ExternalDNS adds both VSs to a Wide IP pool.

### ISSUE THREAD

**Issue by AlexanderSlinkov** [F5Networks/k8s-bigip-ctlr#1918]
#### Title
ExternalDNS adds both VSs to a Wide IP pool.

#### Description
Hi,

The ExternalDNS CRD adds both VSs (HTTP and HTTPS) to a WideIP pool, if in the VirtualServer CRD was added the parameter «httptraffic: redirect».
Why this happens?
The HTTP VS only redirects traffic from HTTP to HTTPS and this VS does not needed to be in the WideIP pool. 
Is it possible to configure this behavior in the ExternalDNS CRD?

Thanks!

#### Actual Problem
The externalDNS CRD adds both VS to a Wide IP pool.

**Comment by trinaths** [comment]
Created CONTCNTR-2835 for internal PM tracking
