### ISSUE TITLE
VirtualServer pool service from different namespace

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#1933]
#### Title
We would like the ability to point a VS to a service in a different namespace. We are using Istio and are using an IngressGateway in the istio-system namespace.

#### Actual Problem
Cannot point a VirtualService pool to a service in a different namespace such as istio-system

#### Solution Proposed
Add a namespace field to the pool

**Comment by trinaths** [comment]
@mitchellmaler - Can you try with a virtual in istio-system namespace ? Not clear on why a `namespace` field is required for a pool.

**Comment by mitchellmaler** [comment]
Hi @trinaths,
Our use case is to create the VirtualService in the tenant/teams namespace which will include the IP assigned for them but since we are using Istio we are using the shared IngressGateway in the istio-system namespace. This would allow the team to be self service to know what their namespaces IP is without the need to setup their pool since it would be istio.

**Comment by trinaths** [comment]
Created CONTCNTR-2845 for internal PM tracking
