### ISSUE TITLE
latest version CIS pod is not working 

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/k8s-bigip-ctlr#1935]
#### Setup Details
 CIS Version : latest      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.0      
 AS3 Version: 3.29.3    
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:  AWS EKS     
 Pool Mode: Cluster/Nodeport      (both) 
 Additional Setup details: AWS EKS 1.20, CoreDNS Version v1.8.3-eksbuild.1, Kube-Proxy Version v1.20.4-eksbuild.2, VPC-CNI Version v1.7.5-eksbuild.2

#### Description  
 
CIS pod sometime will stuck in crash loop, sometime will come up, but it is not function as expected with following error message in the log. As soon as I changed to CIS 2.4.1 and everything works. Changed back to latest and stop working. 

E0730 15:19:50.645921       1 reflector.go:138] github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:878: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:bigip-ctlr" cannot list resource "secrets" in API group "" in the namespace "default"

#### Steps To Reproduce

I have the setup in AWS SP account, it is in US-East-1 Region with cluster name ekstest. 

Haitao

**Comment by trinaths** [comment]
```
E0730 15:19:50.645921 1 reflector.go:138] github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:878: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:bigip-ctlr" cannot list resource "secrets" in API group "" in the namespace "default"
```

From 2.5, CIS monitors all secrets. So you need to update ClusterRole bound to bigip-ctlr serviceAccount. Please refer [Release notes](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/RELEASE-NOTES.rst#before-upgrade-to-25) for details. 

Closing this issue.
