### ISSUE TITLE
Controller Logs. [AS3] Template is not valid. see errors.

### ISSUE THREAD

**Issue by tomaszmzyk** [F5Networks/k8s-bigip-ctlr#1938]
#### Setup Details
 CIS Version : 2.5.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.3
 AS3 Version: 3.x      
 Agent Mode: AS3
 Orchestration: OSCP      
 Orchestration Version:  3.11, 4.6.31
 Pool Mode: Cluster
 Additional Setup details: OpenshiftSDN

#### Description  
 Hi
We observed that after update controller container from version 2.1.1 to 2.5.0, we see in controller lot of errors, like follwing:
2021/07/28 12:24:37 [ERROR] [AS3] Template is not valid. see errors
2021/07/28 12:24:37 [ERROR] - (root): Must validate one and only one schema (oneOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)

2021/07/28 12:24:37 [ERROR] - declaration: Must validate all the schemas (allOf)

We have a lot of declaration, and from this logs there is a very hard find for which declaration we have errors.

#### Steps To Reproduce
1) Installed version 2.1.1 on Openshift
2) Deployed applications with AS3 declaration
3) Update controller to version 2.5.0
4) Errors in controller log

#### Expected Result 
Information for what declaration (id or configmap name) errors generated

#### Actual Result  
No information for what declaration we have errors in logs

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment]
@tomaszmzyk  - What is the AS3 version ? What resources are monitored by CIS ?

**Comment by tomaszmzyk** [comment]
Hi
At this moment we have installed version 3.29 on F5
f5-appsvcs	3.29.0	3	f5-appsvcs-3.29.0-3.noarch

In declaration AS# in config maybe a different version wrote. This is depend which developer created them.

**Comment by trinaths** [comment]
Can you share the sample as3 configMap causing this issue ? @tomaszmzyk

**Comment by tomaszmzyk** [comment]
Hi
This will be difficult, because I have about 50 declaration and realy don't know which from them is corrupted.
I will try prepare some validation for the configmap that check which one have errors.

**Comment by trinaths** [comment]
@tomaszmzyk - Thanks for the update. Closing this issue. CIS does schema validation and not data validation. the above errors are with invalid AS3 Schema in the ConfigMap.

**Comment by tomaszmzyk** [comment]
Something don't understand. In version 2.1.1 of CIS all configmap works well. After update to 2.5.0 we have errors like in case, so from which log I can read in which declaration is error. You close case without any investigation, this is hard to add to log name of configmap from which declaration are errors ?
Regards
