### ISSUE TITLE
The description of 'servicePort' in VirtualServer CRD is confusing

### ISSUE THREAD

**Issue by gazhuchao** [F5Networks/k8s-bigip-ctlr#1946]
Setup Details
 CIS Version : 2.5   
 Build: f5networks/k8s-bigip-ctlr:2.5.0     
 BIGIP Version: Big IP 15.1.2.1-0.0.10      
 AS3 Version: 3.28.0
 Agent Mode: CRD       
 Orchestration: K8S/OSCP      
 Orchestration Version: 1.20
 Pool Mode: Cluster
 Additional Setup details: CNI - KubeOVN

Description  
In the configuration of VirtualServer CRD,   'servicePort' which is the parameter of Pools, can work properly only after it is configured as the targetPort of Service.

If the targetPort of Service is different with Port of Service, and I set the 'servicePort' as the Port of Service, BIGIP cannot add pool member normally.

But in the guide, the description of 'servicePort' as below:

Parameter   | Type   | Required | Default | Description
servicePort | String | Required | N/A       | Port to access service.

Expected Result 
The 'servicePort' should be changed to 'targetPort' to avoid user's confusion. Or change the description of 'servicePort' in the guide.

**Comment by trinaths** [comment]
Thanks for raising this issue. Created CONTCNTR-2899 for internal tracking

**Comment by trinaths** [comment]
Document updated. Closing this issue.
