### ISSUE TITLE
[AS3] REST call error and Failed to initialize as3 agent (Internal Error) Failed. 

### ISSUE THREAD

**Issue by geekcu** [F5Networks/k8s-bigip-ctlr#1947]
Start the the k8s-bigip-ctlr container failed as below logs:

2021/08/13 01:01:55 [INFO] [AS3] Initializing AS3 Agent
2021/08/13 01:01:55 [ERROR] [AS3] REST call error: Get "https://10.66.88.88:443/mgmt/shared/appsvcs/info": dial tcp 10.66.88.88:443: connect: connection refused
2021/08/13 01:01:55 [ERROR] [AS3] Internal Error
2021/08/13 01:01:55 [CRITICAL] [INIT] Failed to initialize as3 agent, Internal Error

But I can use curl -u username:password to access the URL and get the output results. The firewall rule is opened. 
**Output:** {"version":"3.29.0","release":"3","schemaCurrent":"3.29.0","schemaMinimum":"3.0.0"}

Is there any other network port that need to open between Kubernetes cluster and F5-VE AS3 agent? 

`~` Thanks ~~~

**Comment by trinaths** [comment]
@geekcu - Its an issue with your setup and not related to CIS. CIS is checking to get AS3 info installed in BIGIP. Suggest check your firewall rules and other BIGIP reachability issues. Closing this issue.
