### ISSUE TITLE
Route Advertisement support for Ingress

### ISSUE THREAD

**Issue by andreasjacobi** [F5Networks/k8s-bigip-ctlr#1968]
#### Title
Route Advertisement support for Ingress

#### Description
When using CIS in CRD mode we can set Route Advertisement to selective when creating a VirtualServer object. But not when using CIS in default mode and creating an Ingress object. There doesn't seems to be an annotation for it.

#### Actual Problem
We only advertise host routes that are in use from the BigIP using BGP. An ingress object will be useless to us if we cannot advertise the route into the environment when it is available.

#### Solution Proposed
Add an annotation for route advertisement

**Comment by trinaths** [comment]
Suggest use CRDs with Route advertisement. Closing this issue.

**Comment by trinaths** [comment]
Route Advertisement using CRD

https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html?highlight=routeadvertisement#service-address-components

https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html?highlight=routeadvertisement
VirtualServer
