### ISSUE TITLE
F5 operator fails to create FDB record in non-default route domain on Openshift SDN

### ISSUE THREAD

**Issue by bukovjanmic** [F5Networks/k8s-bigip-ctlr#1977]
#### Setup Details
 CIS Version : 2.5.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.2      
 AS3 Version: 3.27.0      
 Agent Mode: AS3       
 Orchestration: OSCP      
 Orchestration Version: 4.6.42       
 Pool Mode: Cluster
 Additional Setup details: x86/openshift-sdn/ cluster nodes/ etc>

#### Description  

F5 operator fails to create FDB record in non-default route domain on Openshift SDN  

#### Steps To Reproduce
1) Define F5 controller

apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  annotations:
    operator-sdk/primary-resource: kube-system/f5-server-f5-bigip-ctlr
    operator-sdk/primary-resource-type: Deployment.apps
  name: f5-server
  namespace: openshift-operators
  finalizers:
    - helm.sdk.operatorframework.io/uninstall-release
spec:
  args:
    manage_routes: true
    agent: as3
    custom-resource-mode: false
    log_level: info
    route-vserver-addr: 172.31.8.220
    openshift-sdn-name: occ01/occ01-tunnel
    bigip_partition: occ01
    ipam: true
    default-route-domain: 14
    disable-teems: true
    bigip_url: 172.31.8.4
    log_as3_response: true
    insecure: true
    pool-member-type: cluster
  bigip_login_secret: bigip
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
  version: latest

2) Once the operator tries to establish FDB record, we get this error>

2021/08/27 08:58:58 [INFO] [2021-08-27 08:58:58,024 f5_cccl.resource.resource INFO] Updating ApiFDBTunnel: /occ01/occ01-tunnel
2021/08/27 08:58:58 [INFO] Text: '{"code":400,"message":"01070734:3: **Configuration error: The IP address (172.31.8.114%0)** of the tunnel FDB record (/occ01/occ01-tunnel 0a:0a:ac:1f:08:72) and the tunnel local address (172.31.8.4%14) cannot be in different route domain.","errorStack":[],"apiError":3}'
2021/08/27 08:58:58 [ERROR] [2021-08-27 08:58:58,108 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiFDBTunnel) /occ01/occ01-tunnel.
2021/08/27 08:58:58 [ERROR] [2021-08-27 08:58:58,109 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://172.31.8.4:443/mgmt/tm/net/fdb/tunnel/~occ01~occ01-tunnel/
2021/08/27 08:58:58 [ERROR] [2021-08-27 08:58:58,109 f5_cccl.service.manager ERROR] Resource /occ01/occ01-tunnel update error, requeuing task...
2021/08/27 08:58:58 [ERROR] [2021-08-27 08:58:58,109 __main__ ERROR] Error applying config, will try again in 32 seconds

#### Expected Result 

FDB record is created in route domain 14.

#### Actual Result  

The above error message is produced and AS3 declaration fails,.

#### Observations (if any)

Subsequently, virtual server for routes is created in default routing domain (0) too, which may or may not be related to this issue.

**Comment by trinaths** [comment]
@bukovjanmic - the actual error 

```
Configuration error: The IP address (172.31.8.114%0) of the tunnel FDB record (/occ01/occ01-tunnel 0a:0a:ac:1f:08:72) and the tunnel local address (172.31.8.4%14) cannot be in different route domain.```

We support `default-route-domain` when `custom-resource-mode` is true. Closing this issue.
