### ISSUE TITLE
An error occurred , when I deploy YAML with some specific spec.pools.path vlaue  How to correct it ?

### ISSUE THREAD

**Issue by linhy-cn** [F5Networks/k8s-bigip-ctlr#1980]
#### Setup Details
CIS Version : 2.5
Build: f5networks/k8s-bigip-ctlr:2.5.0
BIGIP Version: Big IP 15.1.2.1-0.0.10
AS3 Version: 3.28.0-3
Agent Mode: AS3
Orchestration: K8S
Orchestration Version:1.20
Pool Mode: Cluster

#### Description  

An error occurred , when I deploy YAML with some specific spec.pools.path vlaue ，the value is "/db-rr"

The content of the YAML：
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-solid-nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.1.123"
  host: solid.myoas.com
  virtualServerName: f5-soild-nginx-k8s
  snat: auto
  httpTraffic: allow
  pools:
  - path: /db-rr
    service: nginx-svc
    servicePort: 80

The content of the error：
[root@abc test]# kubectl apply -f vs.yaml
The VirtualServer "f5-solid-nginx" is invalid: spec.pools.path: Invalid value: "/db-rr": spec.pools.path in body should match '^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$'

####
How to correct this error ?

**Comment by myf5** [comment]
Check the original schema, 
`                      path:
                        type: string
                        pattern: '^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$'
`

UPdate your crd schema to 
`                      path:
                        type: string
                        pattern: '^\/([A-z0-9-_+]+\/)*([A-z0-9_]+\/?)*$'
`
then it will support - in path

**Comment by linhy-cn** [comment]
@myf5 Thank you for your reply
 I've tried what you offered and the same error still appears .
But I follow your thoughts and change my crd schema like this ，the error has been corrected

                      path:
                        type: string
                        pattern: '^\/([A-z0-9-_+]+\/)*([A-z0-9-]+\/?)*$'

this issues can be closed

**Comment by myf5** [comment]
yes  you are right, as your need "-", not "_"
