### ISSUE TITLE
type LoadBalancer not finding endpoint using TargetPort

### ISSUE THREAD

**Issue by andreasjacobi** [F5Networks/k8s-bigip-ctlr#1981]
#### Setup Details
 CIS Version : 2.5.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.0.1.4      
 AS3 Version: 3.28      
 Agent Mode: AS3       
 Orchestration: K8S
 Orchestration Version:   1.21.1    
 Pool Mode: Cluster     
 Additional Setup details: flannel vxlan

#### Description  
When creating a type LoadBalancer pointing to a ClusterIP service and specifying the POD TargetPort it doesn't find the endpoint. But when specifying the service port it finds the endpoint but the port is then wrong in the BigIP pool member object (as the POD is not listening on that port). A TransportServer will successfully find the endpoint with the correct POD TargetPort.

#### Steps To Reproduce
ClusterIP SVC with different Port and TargetPort:

`Name:              prometheus-server
Namespace:         default
Labels:            app=prometheus
                   app.kubernetes.io/managed-by=Helm
                   chart=prometheus-14.6.0
                   component=server
                   heritage=Helm
                   release=prometheus
Annotations:       meta.helm.sh/release-name: prometheus
                   meta.helm.sh/release-namespace: default
Selector:          app=prometheus,component=server,release=prometheus
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.105.46.135
IPs:               10.105.46.135
Port:              http  80/TCP
TargetPort:        9090/TCP
Endpoints:         10.244.1.156:9090
Session Affinity:  None
Events:            <none>`

Unsuccessful type LB (target port 9090):

`Name:                     prometheus-server-lb
Namespace:                default
Labels:                   app=prometheus-server-lb
Annotations:              cis.f5.com/ipamLabel: Test
Selector:                 app=prometheus,component=server,release=prometheus
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.96.175.60
IPs:                      10.96.175.60
LoadBalancer Ingress:     10.100.100.204
Port:                     prometheus-server-80  80/TCP
TargetPort:               9090/TCP
NodePort:                 prometheus-server-80  30640/TCP
Endpoints:                10.244.1.156:9090
Session Affinity:         None
External Traffic Policy:  Cluster
`

Results in this log entry and an empty BigIP pool:
2021/09/03 13:44:00 [DEBUG] Found endpoints for backend default/prometheus-server-lb: []

Type LB changed to the SVC port instead (targetport 80):

`Name:                     prometheus-server-lb
Namespace:                default
Labels:                   app=prometheus-server-lb
Annotations:              cis.f5.com/ipamLabel: Test
Selector:                 app=prometheus,component=server,release=prometheus
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.96.175.60
IPs:                      10.96.175.60
LoadBalancer Ingress:     10.100.100.204
Port:                     prometheus-server-80  80/TCP
TargetPort:               80/TCP
NodePort:                 prometheus-server-80  30640/TCP
Endpoints:                10.244.1.156:80
Session Affinity:         None
External Traffic Policy:  Cluster
`

Give this log entry and a BigIP pool member is created as expected, but the pool member will use the wrong POD port in this case and traffic won't work:
2021/09/03 14:49:53 [DEBUG] Found endpoints for backend default/prometheus-server-lb: [{10.244.1.156 80 0 user-enabled}]

Using a TransportServer works as expected using the correct POD port:

`apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
   name: prometheus-server-transportserver
   labels:
     f5cr: "true"
spec:
  virtualServerAddress: "10.100.100.99"
  virtualServerPort: 80
  mode: standard
  snat: auto
  pool:
    service: prometheus-server
    servicePort: 9090
    monitor:
      type: tcp
      interval: 10
      timeout: 10
  serviceAddress:
  icmpEcho: "enable"
    arpEnabled: true
    routeAdvertisement: "all"
    spanningEnabled: false`

#### Expected Result 
Be able to set the POD TargetPort in the type LoadBalancer config and have it find the endpoint

#### Actual Result  
Endpoint is not found and BigIP Pool is empty

**Comment by trinaths** [comment]
@andreasjacobi - Can you verify with SVC port same as target-port ? I think that works.

**Comment by andreasjacobi** [comment]
Yes, same Port and TargetPort works. Is that intended?

**Comment by trinaths** [comment]
yes. Thank you for the update. Closing this issue.
