### ISSUE TITLE
Use "Type: LoadBalancer" even without "ipamLabel:" annotation

### ISSUE THREAD

**Issue by yamashin55** [F5Networks/k8s-bigip-ctlr#1983]
#### Title
Use "Type: LoadBalancer" even without "ipamLabel:" annotation.

#### Description
In "type: LoadBalancer", the ipam label is usually a required field. It is intended to be used as the default Type: LoadBalancer even without the ipam label.

#### Actual Problem
The situation where you can manually add annotations to a service resource is fine.
Usually, you can just add them.
Some services, such as those installed from Helm, may not be F5-CIS aware (i.e., they may not be annotated).

#### Solution Proposed
Optionally, use the cluster's default Type: LoadBalancer even if it is not annotated as such.

**Comment by trinaths** [comment]
@yamashin55  - Can you please give more details about your use-case with Type-LB

**Comment by trinaths** [comment]
@yamashin55 - any update ?

**Comment by frbjo3** [comment]
I would also like to see this feature!
To optionally have the ipam controller watch objects also without the ipamLabel annotation. 
And be able to specify what iprange to assign from as Default.

**Comment by andreasjacobi** [comment]
This would simplify it for our customers as well so that they wouldn't have to care about the correct annotation and value but can instead just rely on the default settings.

**Comment by yamashin55** [comment]
> @yamashin55 - Can you please give more details about your use-case with Type-LB

The use cases are described below.

The ultimate goal of using a container environment is to have no human intervention. (I believe it is to automate the process).

For example, if you install Portworx from Helm chart, it does not come with F5-CIS annotations.
https://docs.portworx.com/portworx-install-with-kubernetes/install-px-helm/

As a result, EXTERNAL-IP will be <pending>.

`# kubectl -n px-backup get svc
NAME                            TYPE                 CLUSTER-IP          EXTERNAL-IP    PORT(S)                          AGE
px-backup                      ClusterIP           10.111.167.132     <none>           10002/TCP,10001/TCP   11m
px-backup-ui                  LoadBalancer   10.106.234.154     <pending>      80:31983/TCP                11m
px-central-ui                   LoadBalancer   10.106.182.119     <pending>      80:30460/TCP                11m`

The operator has to add the F5-CIS annotations manually.

`# kubectl annotate service px-backup-ui -n px-backup cis.f5.com/ipamLabel='LABELNAME'`


By not specifying an annotation label and having the IPAM controller monitor the
I want the Default IP range to be assigned without labels.

**Comment by trinaths** [comment]
No plans to add this requirement to CIS. Closing this issue. Please raise a new RFE/Issue with new requirements.
