### ISSUE TITLE
[DOC] IPAM dodcs should include IngressLink in compatibility matrix

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#1985]
#### Description  

IngressLink does support IPAM yet the documentation doesn't reflect this.

See https://clouddocs.f5.com/containers/latest/userguide/ipam/

Thanks

**Comment by mdditt2000** [comment]
Coming in CIS 2.6. Assigning to @vtrippel

**Comment by nandakishorepeddi** [comment]
Updated. Thanks for reporting.
