### ISSUE TITLE
Cannot create multiple domain names to point to the same virtual server in CRD Mode

### ISSUE THREAD

**Issue by 0oblanko0** [F5Networks/k8s-bigip-ctlr#1995]
#### Setup Details
 CIS Version : 2.5      
 Build: f5networks/k8s-bigip-ctlr:2.5.0       
 BIGIP Version: Big IP 15.1.2.1-0.0.10     
 AS3 Version:       
 Agent Mode: Custom Resource Definitions      
 Orchestration: K8S      
 Orchestration Version:  1.20     
 Pool Mode: Cluster      

### Description  

There is an application that needs to point two domain names to the same vs, such as a.test.com and b.test.com. I did three tests and found that the host field in CRDs mode can only define one domain name.

#### first tests(Separate domain names with comma)
***  the content of the YAML ***
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: crd-virtualserver
  namespace: sino-k8s-ns
  labels:
    f5cr: "true"
spec:
  virtualServerName: vs_web_crd_virtualserver
  virtualServerAddress: "172.16.1.80"
  virtualServerHTTPPort: 80
  host: a.test.com,b.test.com
  snat: auto
  pools:
  \- path: /
    service: sino-crd-svc
    servicePort: 80
*** The content of the error ***
[root@sino-k8s-master ~]# kubectl create -f crd-virtualserver.yaml 
The VirtualServer "crd-virtualserver" is invalid: spec.host: Invalid value: "": spec.host in body should match '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'

#### second tests (Separate domain names with spaces) 
***  the content of the YAML ***
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: crd-virtualserver
  namespace: sino-k8s-ns
  labels:
    f5cr: "true"
spec:
  virtualServerName: vs_web_crd_virtualserver
  virtualServerAddress: "172.16.1.80"
  virtualServerHTTPPort: 80
  host: a.test.com b.test.com
  snat: auto
  pools:
  \- path: /
    service: sino-crd-svc
    servicePort: 80

*** The content of the error ***
[root@sino-k8s-master ~]# kubectl create -f crd-virtualserver.yaml 
The VirtualServer "crd-virtualserver" is invalid: spec.host: Invalid value: "": spec.host in body should match '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'

#### third tests (Define two host fields) 
***  the content of the YAML ***
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: crd-virtualserver
  namespace: sino-k8s-ns
  labels:
    f5cr: "true"
spec:
  virtualServerName: vs_web_crd_virtualserver
  virtualServerAddress: "172.16.1.80"
  virtualServerHTTPPort: 80
  host: a.test.com
  host: b.test.com
  snat: auto
  pools:
  \- path: /
    service: sino-crd-svc
    servicePort: 80

*** The content of the error ***
LTM Policy only have b.test.com, cannot found a.test.com:

ltm policy vs_web_crd_virtualserver_80_b.test.com_policy {
    controls { forwarding }
    last-modified 2021-07-18:15:23:14
    partition sino-k8s-crd
    requires { http }
    rules {
        vs_b_test_com_sino_k8s_ns_sino_crd_svc_80 {
            actions {
                0 {
                    forward
                    select
                    pool sino_k8s_ns_sino_crd_svc_80
                }
            }
            conditions {
                0 {
                    http-header
                    name host
                    values { b.test.com }
                }
            }
        }
    }
    status legacy
    strategy /Common/first-match
}

Question: How to create multiple domain names to point to the same virtual server in CRD Mode?

**Comment by trinaths** [comment]
We have this issue reported https://github.com/F5Networks/k8s-bigip-ctlr/issues/1666. We are tracking this with CONTCNTR-2545

**Comment by trinaths** [comment]
Recommend use CIS latest release. Mutli host CRD support completed.
