### ISSUE TITLE
Source IP restriction support for type LoadBalancer

### ISSUE THREAD

**Issue by andreasjacobi** [F5Networks/k8s-bigip-ctlr#2001]
#### Title
Add support for source IP restrictions when using type LoadBalancer

#### Description
To give users the ability to restrict access to the type LoadBalancer similar as virtual-server.f5.com/allow-source-range does for ingress.

#### Actual Problem
In an environment where the F5 BigIP is fronting k8s services and SNAT is enabled (as in most environments) it is not possible to restrict access to the type LoadBalancer without involving external firewalls.
This also goes for TransportServer and VirtualServer as well.

#### Solution Proposed
Add an annotation like cis.f5.com/allow-source-range for type Loadbalancer and a CRD for TransportServer and VirtualServer (probably don't want an annotation in the last two cases)

**Comment by andreasjacobi** [comment]
Any update on this request?

**Comment by trinaths** [comment]
@andreasjacobi - We are reviewing this RFE and update the status here.

**Comment by mdditt2000** [comment]
@andreasjacobi are you still interested in this feature? My plan it to add allow-source-range to policy CRD. PolicyCRD is now attached to type LoadBalancer or TransportServer and VirtualServer. Please can you reach out at automation_toolchain_pm@f5.com so i can prioritize.

**Comment by mdditt2000** [comment]
Jira CONTCNTR-3437 for PM tracking. Once received contact i can prioritize enhancement to policyCRD. In CIS 2.9 using AFM this can already be achieved. https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.9/servicetypelb_nginx_firewall#readme

**Comment by trinaths** [comment]
Feature available from CIS 2.10.
