### ISSUE TITLE
In CRD mode, add a parameter that can be associated with profiles 

### ISSUE THREAD

**Issue by 0oblanko0** [F5Networks/k8s-bigip-ctlr#2007]
#### Title
In CRD mode, add a parameter that can be associated with profiles 

#### Description
I am now testing to release a gRPC load balancer in CRD mode. Although the BIG-IP version is v16.1.0, there are no parameters to associate with the HTTP/2 Profile when creating a Virtual Server in CRD mode, which makes it impossible to define gRPC load balancing. ( such as the need to associate oneconnect profile, stream profile, etc. Profiles other than HTTP or TLS are also unable to be associated because there are no parameters in CRD mode)

K61517014: gRPC Support on BIG-IP :  https://support.f5.com/csp/article/K61517014

#### Actual Problem
When I tried to configure gRPC load balancing, I was frustrated when I found that there are no parameters that can be associated with profiles other than HTTP and TLS Profile in CRD mode.

#### Solution Proposed
In CRD mode, add a parameter that can be associated with profiles other than HTTP and TLS Profile, such as oneconnection profile, HTTP/2 profile, etc.

**Comment by trinaths** [comment]
We are working on a new CRD - Policy CRD - to support VS profiles. Created CONTCNTR-2933 for internal tracking.

**Comment by trinaths** [comment]
Policy CRD available from CIS 2.7. See docs - https://clouddocs.f5.com/containers/latest/userguide/crd/policy.html

Closing this issue.
