### ISSUE TITLE
Documentation on External DNS error

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/k8s-bigip-ctlr#2018]
On this page:
https://clouddocs.f5.com/containers/latest/userguide/crd/externaldns.html  
Towards the bottom, there are 2 YAML configs.  The first titled: External DNS Example , then the next is titled VS-CRD Example , but the yaml files are the same. I believe the second yaml file is incorrect.

**Comment by trinaths** [comment]
Docuement updated. Closing this issue.
