### ISSUE TITLE
[Doc] Incorrect yaml file on EDNS Clouddocs. Needs to be correct

### ISSUE THREAD

**Issue by mdditt2000** [F5Networks/k8s-bigip-ctlr#2019]
#### Description  
  
EDNS documentation has the incorrect CRD. Currently showing a EDNS CRD and this needs to be a VS CRD. @vtrippel please can we correct this. 

https://clouddocs.f5.com/containers/latest/userguide/crd/externaldns.html

#### Issue 

This is not correct. Needs to VS CRD

![image](https://user-images.githubusercontent.com/12733938/135666013-b6460f7e-9ce5-40a0-9b3d-04138abfc55e.png)

**Comment by mdditt2000** [comment]
@trinaths filed based on feedback from @thomsonjames

**Comment by trinaths** [comment]
@mdditt2000 - Duplicate to https://github.com/F5Networks/k8s-bigip-ctlr/issues/2018 

Created CONTCNTR-2951 for internal tracking

**Comment by trinaths** [comment]
Document corrected. Closing this issue.
