### ISSUE TITLE
CIS and Nginx Controller is available as a preview feature

### ISSUE THREAD

**Issue by s-mangalath** [F5Networks/k8s-bigip-ctlr#2027]
#### Title
CIS and Nginx Controller is available as a preview feature
#### Description
Is this still a preview feature? and will it support type LoadBalancer created in BIG-IP to be attached to an NGINX Ingress resource?
#### Actual Problem
Customer is looking for type LoadBalancer in an on-prem k8s installation and wants to consume NGINX ingress along with type LoadBalancer created via CIS? Is this possible? And is the feature still a preview feature? Thanks
#### Solution Proposed
Using MetalLB along with Nginx Ingress Controller for type load balancer service

**Comment by trinaths** [comment]
IngressLink is available with CIS. Closing this issue.
