### ISSUE TITLE
ENDS will not work if both Virtual Server CRD and EDNS CRD are applied at the same time

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2032]
#### Setup Details
 CIS Version : 2.6.0
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.1      
 AS3 Version: 3.30     
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:1.20       
 Pool Mode: Cluster      
 Additional Setup details: Flannel

#### Description  

If EDNS CRD is applied before the VirtualServerCRD is configured and discovered by the GTM as a VirtualServer then the pool will have no members and be shown as down. Even after 20 minutes the pool doesn't have any members. 
if the  EDNS is applied after the VirtualServerCRD is configured and discovered by the GTM, then the pool will have the member configured and will show as green. 

#### Steps To Reproduce
1) Apply EDNS CRD before or at the same time as the Virtual CRD.

#### Expected Result 
The order on which the CRDs are applied (EDNS CRD first and VS CRD second) shouldn't affect the deployment of the EDNS services.

**Comment by trinaths** [comment]
Created CONTCNTR-2948 for internal tracking
