### ISSUE TITLE
Install CIS using Helm fails on K8s 1.18

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2050]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.30      
 Agent Mode: AS3
 Orchestration: K8S/
 Orchestration Version: 1.18       
 Pool Mode: Cluster      
 Additional Setup details: Flannel

#### Description  
Installing CIS Using Helm Charts fails when you rung K8s 1.18 or below. The error msg is the following:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "IngressClass" in version "networking.k8s.io/v1"

#### Steps To Reproduce
1) Install CIS using Helm on a v1.18 K8s

**Comment by trinaths** [comment]
Document updated.
