### ISSUE TITLE
Issue #1723 produces 422 error-code and blocks CIS for further AS3-updates

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#2053]
#### Setup Details
 CIS Version : 2.4.0     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.3.0.148.11     
 AS3 Version: 3.25      
 Agent Mode: AS3       
 Orchestration: K8S/OSCP v1.17.1, OS v4.2      
 Orchestration Version:       
 Pool Mode: Cluster
 Additional Setup details: Path-based OS-Routes sharing the same ECDSA-cert/key

#### Description  
The workaround for BIG-IP Bug ID 912945 introduced with #1723 produces a severe failure!!!
If multiple path-based OpenShift-Routes are used sharing the same ECDSA-cert/key, the AS3 declaration will be denied by BIG-IP with status-code 422.
Reason: The CIS sends an invalid configuration, because the workaround can only be used in one client-ssl profile referenced by one virtual-server. If multiple client-ssl profiles using the same server-name (=workaround) which are referenced by the same Virtual-Server, the BIG-IP denies such setup!

#### Steps To Reproduce
1) configure multiple path-based OpenShift-Routes sharing the same ECDSA-certificate/key.

#### Expected Result 
Workaround for BIG-IP Bug ID 912945 must be optional (e.g. per CIS parameter) or must be removed!

#### Actual Result  
CIS configure workaround - no choice.

**Comment by trinaths** [comment]
Created CONTCNTR-2986 for internal PM tracking. ETA 2.7

**Comment by sravyap135** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/pull/2140
