### ISSUE TITLE
HubMode not working

### ISSUE THREAD

**Issue by rgarcia89** [F5Networks/k8s-bigip-ctlr#2086]
#### Setup Details
 CIS Version : 2.6.1
 Build: f5networks/k8s-bigip-ctlr:2.6.1   
 BIGIP Version: BIG-IP v16.1.1 (Build 0.0.16)
 AS3 Version: 3.28
 Agent Mode: AS3
 Orchestration: K8S      
 Orchestration Version: 1.20.11
 Pool Mode: Nodeport      

#### Description  
HubMode is not working properly.
When I enable the hubmode in a controller argument I get the following errors in the log.

```
2021/11/11 09:54:22 [ERROR] - declaration: Must validate all the schemas (allOf)
2021/11/11 09:54:22 [ERROR] - declaration: Must validate "then" as "if" was valid
2021/11/11 09:54:22 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2021/11/11 09:54:22 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2021/11/11 09:54:22 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2021/11/11 09:54:22 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2021/11/11 09:54:22 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2021/11/11 09:54:22 [ERROR] - declaration: Must validate all the schemas (allOf)
```

AS3 declarations that are being used work fine using CIS 1.14.
We do have the AS3 configmaps for all other namespaces stored in one specific namespace, as we do not want to give k8s users access to the declarations.

Controller arguments
```
command: ["/app/bin/k8s-bigip-ctlr"]
args: [
    # See the k8s-bigip-ctlr documentation for information about
    # all config options
    # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
    "--bigip-username=$(BIGIP_USERNAME)",
    "--bigip-password=$(BIGIP_PASSWORD)",
    "--bigip-url=1.2.3.4",
    "--bigip-partition=k8s",
    "--pool-member-type=nodeport",
    "--manage-ingress=false",
    "--manage-configmaps=true",
    "--namespace=f5lab",
    "--insecure=true",
    "--log-level=debug",
    "--log-as3-response=true",
    "--node-label-selector=f5role=worker",
    "--agent=as3",
    "--hubmode"
```

**Comment by trinaths** [comment]
Created CONTCNTR-3012 for internal PM tracking.

**Comment by trinaths** [comment]
@rgarcia89 - Please try this multiple configMaps example using hubmode https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.5/hubMode 
this works

**Comment by trinaths** [comment]
@rgarcia89 Can we close this issue? good to know 1.14 to 2.6.1 upgrade is complete.

**Comment by rgarcia89** [comment]
closed as we found that the issue resides somewhere else in CIS
