### ISSUE TITLE
nodeMemberLabel regex does not allow for common node labels

### ISSUE THREAD

**Issue by bmayfi3ld** [F5Networks/k8s-bigip-ctlr#2087]
#### Setup Details
 CIS Version : 2.6.1

#### Description  
 The regex in the virtual server CRD does not allow for node labels with a slash in them. This is very common for node labels

#### Steps To Reproduce
try to add nodeMemberLabel field with a label that has a slash in it. 

#### Expected Result 
The virtualserver resrouce to be saved

#### Actual Result  
Regex error

#### Observations (if any)
Fixed by something like https://github.com/F5Networks/k8s-bigip-ctlr/pull/2083   . I just added a slash there, but there may be other characters.

**Comment by trinaths** [comment]
Created CONTCNTR-3015 for internal tracking.

**Comment by sravyap135** [comment]
This fix will be part of CIS 2.7 release. https://github.com/F5Networks/k8s-bigip-ctlr/pull/2100
