### ISSUE TITLE
Least privileges access per partition

### ISSUE THREAD

**Issue by Timoses** [F5Networks/k8s-bigip-ctlr#2104]
#### Title
Least privileges access per partition

#### Description
Currently the k8s-bigip-ctlr requires Administrative access on the complete BigIP device. This contradicts the documentation which states "You need a user with administrative access to this partition." (https://clouddocs.f5.com/containers/latest/userguide/kubernetes/#prerequisites)

#### Actual Problem
We are very hesitant to grant full administrative privileges to the controller as we have other productive workloads managed on the BigIP device. The impact surface of an unknown bug in k8s-bigip-ctlr is unnecessarily huge. This means we do not use the k8s-bigip-ctlr in sensitive environments (which resemble the much bigger part of our operations) but only in small development stages as we can not risk negative impacts due to automated overarching access privileges.

This is a huge loss for us, already hindering us with our advancement in Kubernetes and will impact our performance in the future.

#### Solution Proposed
As the k8s-bigip-ctlr manages a partition it should only require a user with access rights limited to that partition.

#### Alternatives
So far we have not come up with alternative solutions other than simply not to use k8s-bigip-ctlr leading to increased manual work.

#### Additional context
Issue #1161 already stated that complete administrative access is required.

Please reconsider.

**Comment by trinaths** [comment]
@Timoses - we need admin access since CIS uses AS3 to configure BIG_IP. We will update the docs to reflect this. No issue with CIS.
