### ISSUE TITLE
Can Single F5 BIGIP Controller in K8S cluster support simultaneously both Service Type LB and Ingress Mode.

### ISSUE THREAD

**Issue by RamanVaskevich1984** [F5Networks/k8s-bigip-ctlr#2123]
#### Title
Can Single F5 BIGIP Controller in K8S cluster support simultaneously both Service Type LB and Ingress Mode.

#### Description
We need to be able to process service types Load Balancer and NodePort with the same F5 BIGIP Controller.
For now it looks like it support either Service Type LB or Ingress, but not both simultaneously.

#### Solution Proposed
Probably Ingress Link is the solution which provides an option with F5 BIGIP Controller and Nginx Ingress Controller.

**Comment by mdditt2000** [comment]
@RamanVaskevich1984 Service Type LB uses CRD. Currently you cannot combine CRDs and Ingress on the same CIS. Would it be possible to migrate from Ingress to using CRDs?

**Comment by RamanVaskevich1984** [comment]
@mdditt2000 Thank you for response, Mark.
As for now project requirements is to have both Ingress and Service Type LB options within the same Controller.
I see that something similar is designed with IngressLink solution discussed here https://github.com/F5Networks/k8s-bigip-ctlr/issues/2027.
But not clear enough how to get IPAM allocating IPs https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/IngressLink/ingressLink-with-ipamLabel/ingresslink-with-ipamLabel.yaml#L7 from this example https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/customResource/IngressLink.

**Comment by RamanVaskevich1984** [comment]
@mdditt2000 actually there is a need to:
- process Services Type LB with External IPs allocation to them;
- process Ingresses.
Could you confirm whether IngressLink https://clouddocs.f5.com/containers/latest/userguide/ingresslink/ can be an appropriate option?
If yes, when it is going to be available not in Preview Mode?

**Comment by mdditt2000** [comment]
@RamanVaskevich1984 please review the following architecture and document https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.9/servicetypelb_nginx_firewall#readme

This will solve your issue.
