### ISSUE TITLE
Add CIS-option to blacklist particular OpenShift namespaces

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#2125]
#### Title
Add CIS-option to blacklist particular OpenShift namespaces

#### Description
The CIS miss the option to blacklist particular OpenShift namespaces.
The CIS only provides the option to allow all namespaces or a whitelisting.
Whitelisting is not scalable if you have hundreds of namespaces!

#### Actual Problem
This is especially important, when a particular namespace uses couple of OS-Routes, which for any reason are not supported by CIS.
E.g. "overlapping" OS-routes in scenarios where different services are exposed on same hostname with and without Forwarding Slash (host-based and path-based OS-Route)!
The CIS starts an AS3-loop, send every 20sec an AS3-declaration to BIG-IP, BIG-IP CPU load rises sharply to 80%! Connections are affected!

#### Solution Proposed
1. highest-priority solution:
Add CIS-option to blacklist particular OpenShift namespaces

2. next-highest-priority solution:
CIS must support such "overlapping" OS-routes 
In BIG-IPs LTM-Policy the CIS only creates the match criteria http uri - path SEGMENT. This cannot be used! 

Replace it by HTTP URI PATH "/" at request time.
The ordering is also important.
Nb.1 path-based OS-route for host and path "/"
Nb.2 host-based OS-route for the same host
![LTM-Policy](https://user-images.githubusercontent.com/44204107/144213176-1e678943-d6b8-489c-9295-41a36e555ed9.png)

**Comment by trinaths** [comment]
@joebride - there are two features in 1 RFE

For 1, one simple solution would be to label the namespaces and use that label in `--namespace-label` CIS deployment option. This way, any namespace without that label will not be monitored by CIS.

**Comment by joebride** [comment]
@trinaths: Unfortunately not helpful, because once the label is communicated to the consumer, I cannot control its usage anymore. I require a solution which has higher priority as such label.

**Comment by trinaths** [comment]
@joebride we can create multiple labels for a namespace.  We can have one label CIS bound and other to external users.

**Comment by joebride** [comment]
@trinaths: I do not have rights to set labels in the various namespaces. How should this work?

**Comment by trinaths** [comment]
@joebride - okay. that is a limitation. let me get back to you on this.

**Comment by mikeoleary** [comment]
@trinaths - wondering if there is an update on this?

I also have a customer that uses Rancher (so not Openshift) but their ask is the same. They want the ability to ignore a given namespace with a CIS deployment argument. This would allow them to just ignore the resource that is causing their issue in #2284

**Comment by trinaths** [comment]
@mikeoleary This can be achieved with ns-labels. Add the configured ns-label to namespaces which CIS need to monitor. CIS is not validated compatible with Rancher at this time also, calico CNI.

**Comment by trinaths** [comment]
@mikeoleary  Is this issue still valid and required ?

**Comment by mikeoleary** [comment]
@trinaths  - To answer your qu, it's still valid. It could be useful to have CIS ignore a namespace instead of labeling every other namespace. But still required? I have not followed up on whether this is still required. It's been about a year and I have not heard any updates from customer or PM.

**Comment by trinaths** [comment]
Closing this issue as not planned for CIS.
