### ISSUE TITLE
SIGSEGV in getSecretServiceQueueKeyForIngress CIS 2.5.1

### ISSUE THREAD

**Issue by jhennf5** [F5Networks/k8s-bigip-ctlr#2136]
#### Setup Details

        - args:
            - --bigip-username=$(BIGIP_USERNAME)
            - --bigip-password=$(BIGIP_PASSWORD)
            - --bigip-url=<SANITIZED>
            - --bigip-partition=<SANITIZED>
            - --pool-member-type=nodeport
            - --insecure=true
            - --agent=as3
            - --log-level=debug
            - --manage-configmaps=true
            - --log-as3-response=true
            - --as3-validation=true
            - --disable-teems=true
            - --manage-ingress=false
            - --as3-post-delay=60
            - --verify-interval=120
	    - --hubmode=true
          command:
            - /app/bin/k8s-bigip-ctlr
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: bigip-login
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: bigip-login
          image: <SANITIZED>k8s-bigip-ctlr:2.5.1

#### Steps To Reproduce

Attempt to deploy

#### Expected Result 

Deployment successful

#### Actual Result  

SIGSEGV

[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x16d9735]

goroutine 193 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x193d240, 0x28a98f0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).getSecretServiceQueueKeyForIngress(0xc0002f62c0, 0xc001f01680, 0x1b6182f, 0x7, 0xc000cb8508)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:192 +0x75
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).checkValidSecrets(0xc0002f62c0, 0x1b3f1a0, 0xc001f01680, 0xc000674df0, 0xc000674d40, 0x3, 0x0)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:277 +0xe5
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).enqueueSecrets(0xc0002f62c0, 0x1b3f1a0, 0xc001f01680, 0x1b60c62, 0x6)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:827 +0x46
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).newAppInformer.func14(0x1b3f1a0, 0xc001f01680)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:752 +0x53
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005d1760)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005ddf60, 0x1d507e0, 0xc000217e90, 0x18fd101, 0xc00066e000)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005d1760, 0x3b9aca00, 0x0, 0x1, 0xc00066e000)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000031700)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00035d800, 0xc00066c000)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start

Similar issues:
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2062
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2102

**Comment by jhennf5** [comment]
if we comment out --disable-teems=true it works

**Comment by jhennf5** [comment]
only problem is box has no internet connectivity, so kind of want disable-teems true...

**Comment by trinaths** [comment]
@jhennf5 Thanks for the update. Closing this issue.

**Comment by jhennf5** [comment]
I think it is pre-mature to close.  All I'm saying is disable-teems and hubmode are necessary for the core.  But those features are also necessary for customer.  So commenting them out is not an option.  They need those features and they need it not to core.

**Comment by trinaths** [comment]
@jhennf5 please try this image http://quay.io/f5networks/k8s-bigip-ctlr-devel:43dfd52c7ac76bec48b8e269eeaf365f34393f89 and share your findings

**Comment by trinaths** [comment]
make sure to enable teems and hubmode as per your requirement.

**Comment by jhennf5** [comment]
thanks!

**Comment by myf5** [comment]
> 

hi @jhennf5  did you find any clue with the image that @trinaths provided before?

**Comment by jhennf5** [comment]
The image fixes the issue in lab test.
