### ISSUE TITLE
Should project module changed from github.com/F5Networks/k8s-bigip-ctlr to github.com/F5Networks/k8s-bigip-ctlr/v2 in tag v2.x.x?

### ISSUE THREAD

**Issue by nuczzz** [F5Networks/k8s-bigip-ctlr#2153]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:v2.6.1     
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
 I want to create vs/ts with my go program(based on github.com/F2Networks/k8s-bigip-ctlr@v2.6.1), and I wrote go.mod like this:
```
module test

go 1.16

require github.com/F5Networks/k8s-bigip-ctlr v2.6.1
```
But when I ran go mod vendor, it told me:
```
$ go mod vendor
go: finding github.com/F5Networks/k8s-bigip-ctlr v2.6.1
go: errors parsing go.mod:
/root/gopath/src/test/go.mod:5: require github.com/F5Networks/k8s-bigip-ctlr: reading https://goproxy.io/github.com/%21f5%21networks/k8s-bigip-ctlr/@v/v2.6.1.info: 404 Not Found
```
Run go get with version will get the same error:
```
$ go get github.com/F5Networks/k8s-bigip-ctlr@v2.6.1
go: finding github.com/F5Networks v2.6.1
go: finding github.com/F5Networks/k8s-bigip-ctlr v2.6.1
go: finding github.com v2.6.1
go get github.com/F5Networks/k8s-bigip-ctlr@v2.6.1: github.com/F5Networks/k8s-bigip-ctlr@v2.6.1: reading https://goproxy.io/github.com/F5Networks/k8s-bigip-ctlr/@v/v2.6.1.info: 404 Not Found
```

#### Steps To Reproduce
1) Run
```
go get github.com/F5Networks/k8s-bigip-ctlr@v2.6.1
```

#### Expected Result 
Download github.com/F5Networks/k8s-bigip-ctlr@v2.6.1 successful

#### Actual Result  
Got error: 404 Not Found

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)
Should project module (in go.mod) changed from 
```
github.com/F5Networks/k8s-bigip-ctlr
``` 
to 
```
github.com/F5Networks/k8s-bigip-ctlr/v2
``` 
in tag v2.x.x？

**Comment by sravyap135** [comment]
Thanks @nuczzz for raising this issue. This is already part of dev backlog CONTCNTR-2931

**Comment by mikejoh** [comment]
@sravyap135 I have the same problem with the same use-case, i want to import the API types but can't since the major version bump from `v1` to `v2` requires a `/v2` module path:
```
go get github.com/F5Networks/k8s-bigip-ctlr@v2.10.1
go: github.com/F5Networks/k8s-bigip-ctlr@v2.10.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/F5Networks/k8s-bigip-ctlr/v2")
```

The issue you linked to: https://github.com/kubernetes/code-generator/issues/139 is closed due to inactivity.

**Comment by mikejoh** [comment]
@sravyap135 Hi, any news on this issue?

**Comment by sravyap135** [comment]
Hi @mikejoh, I am not working on this project
 @chandrajr  @trinaths  @vklohiya can help

**Comment by mikejoh** [comment]
@chandrajr @trinaths @vklohiya :wave:, i just want to know if it's possible to make changes in this repository to be able to import (atleast) the API types using Go modules regardless of the fact that the project has moved from `v1` to `v2`. If adding a `v2/` isn't possible what's the next best thing to do? Is it to move the API types to it's own module?

As a workaround i have basically copy-pasted the API types to the places where i want to use them (other modules).

Thanks.

**Comment by mikejoh** [comment]
Ping @chandrajr @trinaths @vklohiya! Sorry for the mass ping, but do you have any news on this issue? I just wanted to know if this is something that can be fixed or not. Thanks!

**Comment by trinaths** [comment]
@mikejoh we will review LoE during 2.11.1 sprints. Code freeze for 2.11 release.
