### ISSUE TITLE
CIS - Send logs to file from container

### ISSUE THREAD

**Issue by ghost** [F5Networks/k8s-bigip-ctlr#2158]
#### Title
CIS - Save logs to file in container

#### Description
Hi
Currently controller when run in container send logs to stdout/stderr.

#### Actual Problem
I want send logs from container to external syslog, and I prepared a sidecar for this, but all sollution base on read logs from file, not from stdout.
For example fluentbit, filebeat don't have option to read from stdout/stderr

#### Solution Proposed
Additional configuration for CIS that allows to create log file inside container, like for example for nginx.

Regards

**Comment by trinaths** [comment]
Created [CONTCNTR-3162] for internal tracking.
