### ISSUE TITLE
Setting into DEBUG level, configmap does not get configured onto bigip, setting to INFO level seems to be working although a little slow.

### ISSUE THREAD

**Issue by Niklaus-xie** [F5Networks/k8s-bigip-ctlr#2164]
#### Setup Details
 CIS Version : 2.7     
 Build: f5networks/k8s-bigip-ctlr:2.7.0     
 BIGIP Version: Big IP 14.1.2      
      
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  - args:
- --bigip-username=$(BIGIP_USERNAME)
- --bigip-password=$(BIGIP_PASSWORD)
- --bigip-url=https://XXXXX:8443
- --insecure=true
- --bigip-partition=kubernetes
- --pool-member-type=cluster
- --flannel-name=/Common/fl-tunnel
- --agent=cccl
- --namespace=default
- --verify-interval=45
- --node-poll-interval=120
- --http-listen-address=0.0.0.0:9113
- --periodic-sync-interval=180
- --log-level=DEBUG
- --cccl-log-level=DEBUG

#### Steps To Reproduce
- have already got ~200 iapps 
- create a new configmap for iapp , it is not configured onto bigip
(is not signaling bigip,  config handler is not woken for reset) although the new iapp is written into config.json .

#### Expected Result 
configurations gets set onto bigip.

#### Actual Result  
it is not configured onto bigip. setting log to INFO level seems to be ok, though slow.

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)
(is not signaling bigip,  config handler is not woken for reset) although the new iapp is already written into config.json .

**Comment by Niklaus-xie** [comment]
after some initial debug and analysis . find out that : the new iapp is written into config.json,  normally it would:  woken the config handler for reset  when the config.json changed,
however, in this case, it does not signal.

**Comment by Niklaus-xie** [comment]
noticed new cccl-log-level parameter from https://github.com/F5Networks/k8s-bigip-ctlr/pull/1999
also put it into the args.   seems the same behavior.

**Comment by Niklaus-xie** [comment]
one more observation : find a strange thing from the following log 26972c79e225f16743ccbcdc3ef52c3e59b175c45ad2d86b50bfab87433c5d60-json.log
 (set to DEBUG level):
in which , you can find   'Retrieving iApps from XXXX', but after that, there is no more retrieving anymore.(normally, it should retrieving nodes, etc)
this seems to be stopping here instead.

---
{"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,491 f5_cccl.bigip DEBUG] Retrieving gateway icmp_monitors from BIG-IP /kubernetes...\n","stream":"stderr","time":"2022-01-18T13:08:08.492142799Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,492 icontrol.session DEBUG] get WITH uri: https://10.250.15.179:8443/mgmt/tm/ltm/monitor/gateway-icmp/ AND suffix:  AND kwargs: {'params': '$filter=partition+eq+kubernetes'}\n","stream":"stderr","time":"2022-01-18T13:08:08.492517725Z"}
{"log":"2022/01/18 13:08:08 [INFO] Text: '{\"kind\":\"tm:ltm:monitor:gateway-icmp:gateway-icmpcollectionstate\",\"selfLink\":\"https://localhost/mgmt/tm/ltm/monitor/gateway-icmp?$filter=partition+eq+kubernetes\u0026ver=14.1.2.1\",\"items\":[]}'\n","stream":"stdout","time":"2022-01-18T13:08:08.506342094Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,505 urllib3.connectionpool DEBUG] https://10.250.15.179:8443 \"GET /mgmt/tm/ltm/monitor/gateway-icmp/?$filter=partition+eq+kubernetes HTTP/1.1\" 200 186\n","stream":"stderr","time":"2022-01-18T13:08:08.506349528Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,505 icontrol.session DEBUG] RESPONSE::STATUS: 200 Content-Type: application/json; charset=UTF-8 Content-Encoding: None\n","stream":"stderr","time":"2022-01-18T13:08:08.506387915Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,505 f5_cccl.bigip DEBUG] Retrieving iApps from BIG-IP /kubernetes...\n","stream":"stderr","time":"2022-01-18T13:08:08.506392322Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,506 icontrol.session DEBUG] get WITH uri: https://10.250.15.179:8443/mgmt/tm/sys/application/service/ AND suffix:  AND kwargs: {'params': '$filter=partition+eq+kubernetes'}\n","stream":"stderr","time":"2022-01-18T13:08:08.506789542Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [CORE] Updated 0 of 1 virtual server configs, deleted 0\n","stream":"stderr","time":"2022-01-18T13:08:08.507591896Z"}
{"log":"2022/01/18 13:08:08 [DEBUG] [CORE] Finished syncing virtual servers f5-test-svc-s400 in namespace k8s (623.702629ms), 1206/1206\n","stream":"stderr","time":"2022-01-18T13:08:08.5076095Z"}
{"log":"2022/01/18 13:08:10 [DEBUG] [2022-01-18 13:08:10,000 urllib3.connectionpool DEBUG] https://10.250.15.179:8443 \"GET /mgmt/tm/sys/application/service/?$filter=partition+eq+kubernetes HTTP/1.1\" 200 955208\n","stream":"stderr","time":"2022-01-18T13:08:10.000638515Z"}
{"log":"2022/01/18 13:08:10 [DEBUG] [2022-01-18 13:08:10,013 icontrol.session DEBUG] RESPONSE::STATUS: 200 Content-Type: application/json; charset=UTF-8 Content-Encoding: None\n","stream":"stderr","time":"2022-01-18T13:08:10.015409866Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) ready to poll, last wait: 5m0s\n","stream":"stderr","time":"2022-01-18T13:11:53.923920529Z"}
{"log":"\n","stream":"stderr","time":"2022-01-18T13:11:53.924041255Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) notifying listener: {l:0xc0003de300 s:0xc0003de360}\n","stream":"stderr","time":"2022-01-18T13:11:53.929880602Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) notifying listener: {l:0xc00059d6e0 s:0xc00059d740}\n","stream":"stderr","time":"2022-01-18T13:11:53.929916599Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) listener callback - num items: 5 err: \u003cnil\u003e\n","stream":"stderr","time":"2022-01-18T13:11:53.929921767Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CCCL] ConfigWriter (0xc00026b830) writing section name vxlan-fdb\n","stream":"stderr","time":"2022-01-18T13:11:53.930023029Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) listener callback - num items: 5 err: \u003cnil\u003e\n","stream":"stderr","time":"2022-01-18T13:11:53.930155
553Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [CCCL] ConfigWriter (0xc00026b830) successfully wrote section (vxlan-fdb)\n","stream":"stderr","time":"2022-01-18T13:11:53.945986395Z"}
{"log":"2022/01/18 13:11:53 [DEBUG] [VxLAN] Vxlan manager (fl-tunnel) wrote config section: [{52:6e:50:78:05:db 10.250.15.191} {46:f2:82:78:28:8d 10.250.15.164} {6e:7b:81:1c:5d:6
7 10.250.15.153} {76:e8:6e:57:7b:f3 10.250.15.117}]\n","stream":"stderr","time":"2022-01-18T13:11:53.946047473Z"}

**Comment by Niklaus-xie** [comment]
any ideas??? thanks

**Comment by Niklaus-xie** [comment]
any idea/comments/root cause about this issue  so that we can provide more info to the customer. thanks very much. 

because when I tried to look at some related git history, e.g.  https://github.com/f5devcentral/f5-ctlr-agent/pull/44
seems related to this issue as well.  thanks


> That is the actual issue this PR must resolve Trinath Somanchi.
> […](#)
> ________________________________ From: Niklaus-xie ***@***.***> Sent: Tuesday, January 18, 2022 7:58:38 PM To: F5Networks/k8s-bigip-ctlr ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [F5Networks/k8s-bigip-ctlr] Setting into DEBUG level, configmap does not get configured onto bigip, setting to INFO level seems to be working although a little slow (Issue #2164) EXTERNAL MAIL: ***@***.*** one more observation : find a strange thing from the following log 26972c79e225f16743ccbcdc3ef52c3e59b175c45ad2d86b50bfab87433c5d60-json.log (set to DEBUG level): in which , you can find 'Retrieving iApps from XXXX', but after that, there is no more retrieving anymore.(normally, it should retrieving nodes, etc) this seems to be stopping here instead.
> ________________________________ {"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,491 f5_cccl.bigip DEBUG] Retrieving gateway icmp_monitors from BIG-IP /kubernetes...\n","stream":"stderr","time":"2022-01-18T13:08:08.492142799Z"} {"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,492 icontrol.session DEBUG] get WITH uri: https://10.250.15.179:8443/mgmt/tm/ltm/monitor/gateway-icmp/<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2F10.250.15.179%3A8443%2Fmgmt%2Ftm%2Fltm%2Fmonitor%2Fgateway-icmp%2F&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NeU4UHqX5Y2Iy0oNsaNZkkaq4K2Q49%2BF1kDlNtdy1YY%3D&reserved=0> AND suffix: AND kwargs: {'params': '$filter=partition+eq+kubernetes'}\n","stream":"stderr","time":"2022-01-18T13:08:08.492517725Z"} {"log":"2022/01/18 13:08:08 [INFO] Text: '{"kind":"tm:ltm:monitor:gateway-icmp:gateway-icmpcollectionstate","selfLink":"https://localhost/mgmt/tm/ltm/monitor/gateway-icmp?$filter=partition+eq+kubernetes\u0026ver=14.1.2.1\",\"items\":[]}'\n","stream":"stdout","time":"2022-01-18T13:08:08.506342094Z"}<https://localhost/mgmt/tm/ltm/monitor/gateway-icmp?$filter=partition+eq+kubernetes%5Cu0026ver=14.1.2.1%5C%22,%5C%22items%5C%22:%5B%5D%7D'%5Cn%22,%22stream%22:%22stdout%22,%22time%22:%222022-01-18T13:08:08.506342094Z%22%7D> {"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,505 urllib3.connectionpool DEBUG] https://10.250.15.179:8443<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2F10.250.15.179%3A8443%2F&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K9cIW5C8NO3D39I%2BB0v8K3OdfrSTDndoBm4QPkI66UY%3D&reserved=0> "GET /mgmt/tm/ltm/monitor/gateway-icmp/?$filter=partition+eq+kubernetes HTTP/1.1" 200 186\n","stream":"stderr","time":"2022-01-18T13:08:08.506349528Z"} {"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,505 icontrol.session DEBUG] RESPONSE::STATUS: 200 Content-Type: application/json; charset=UTF-8 Content-Encoding: None\n","stream":"stderr","time":"2022-01-18T13:08:08.506387915Z"} {"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,505 f5_cccl.bigip DEBUG] Retrieving iApps from BIG-IP /kubernetes...\n","stream":"stderr","time":"2022-01-18T13:08:08.506392322Z"} {"log":"2022/01/18 13:08:08 [DEBUG] [2022-01-18 13:08:08,506 icontrol.session DEBUG] get WITH uri: https://10.250.15.179:8443/mgmt/tm/sys/application/service/<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2F10.250.15.179%3A8443%2Fmgmt%2Ftm%2Fsys%2Fapplication%2Fservice%2F&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aBZisMk2H0hT6uA56BL19pUAjpw3BE5tidt5gu0MA6I%3D&reserved=0> AND suffix: AND kwargs: {'params': '$filter=partition+eq+kubernetes'}\n","stream":"stderr","time":"2022-01-18T13:08:08.506789542Z"} {"log":"2022/01/18 13:08:08 [DEBUG] [CORE] Updated 0 of 1 virtual server configs, deleted 0\n","stream":"stderr","time":"2022-01-18T13:08:08.507591896Z"} {"log":"2022/01/18 13:08:08 [DEBUG] [CORE] Finished syncing virtual servers f5-test-svc-s400 in namespace k8s (623.702629ms), 1206/1206\n","stream":"stderr","time":"2022-01-18T13:08:08.5076095Z"} {"log":"2022/01/18 13:08:10 [DEBUG] [2022-01-18 13:08:10,000 urllib3.connectionpool DEBUG] https://10.250.15.179:8443<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2F10.250.15.179%3A8443%2F&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K9cIW5C8NO3D39I%2BB0v8K3OdfrSTDndoBm4QPkI66UY%3D&reserved=0> "GET /mgmt/tm/sys/application/service/?$filter=partition+eq+kubernetes HTTP/1.1" 200 955208\n","stream":"stderr","time":"2022-01-18T13:08:10.000638515Z"} {"log":"2022/01/18 13:08:10 [DEBUG] [2022-01-18 13:08:10,013 icontrol.session DEBUG] RESPONSE::STATUS: 200 Content-Type: application/json; charset=UTF-8 Content-Encoding: None\n","stream":"stderr","time":"2022-01-18T13:08:10.015409866Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) ready to poll, last wait: 5m0s\n","stream":"stderr","time":"2022-01-18T13:11:53.923920529Z"} {"log":"\n","stream":"stderr","time":"2022-01-18T13:11:53.924041255Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) notifying listener: {l:0xc0003de300 s:0xc0003de360}\n","stream":"stderr","time":"2022-01-18T13:11:53.929880602Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) notifying listener: {l:0xc00059d6e0 s:0xc00059d740}\n","stream":"stderr","time":"2022-01-18T13:11:53.929916599Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) listener callback - num items: 5 err: \u003cnil\u003e\n","stream":"stderr","time":"2022-01-18T13:11:53.929921767Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CCCL] ConfigWriter (0xc00026b830) writing section name vxlan-fdb\n","stream":"stderr","time":"2022-01-18T13:11:53.930023029Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CORE] NodePoller (0xc00016e120) listener callback - num items: 5 err: \u003cnil\u003e\n","stream":"stderr","time":"2022-01-18T13:11:53.930155 553Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [CCCL] ConfigWriter (0xc00026b830) successfully wrote section (vxlan-fdb)\n","stream":"stderr","time":"2022-01-18T13:11:53.945986395Z"} {"log":"2022/01/18 13:11:53 [DEBUG] [VxLAN] Vxlan manager (fl-tunnel) wrote config section: [{52:6e:50:78:05:db 10.250.15.191} {46:f2:82:78:28:8d 10.250.15.164} {6e:7b:81:1c:5d:6 7 10.250.15.153} {76:e8:6e:57:7b:f3 10.250.15.117}]\n","stream":"stderr","time":"2022-01-18T13:11:53.946047473Z"} — Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FF5Networks%2Fk8s-bigip-ctlr%2Fissues%2F2164%23issuecomment-1015464159&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AYam6XnrQsgMow5gckMiVCt1e1Nn7BvpINI9Rd8qplw%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAYX2XWHTNJSOO3FEGFCBOLUWV2JNANCNFSM5LA4FQYQ&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Feq0Tyh4UsKAkhnJSW0f7yf1fBfEGOo5sIp%2FTbRpuuo%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g8Vft75pYpNEG7wrbE%2BBEVC%2BDNATzXhYKZI21IsGbIg%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ct.somanchi%40f5.com%7C0a1d8b6a1959416582a708d9da8edeeb%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637781129434738436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=19LsallLJbv%2FNDBYar2oAhV8e9%2BM5m6GsQCa6ldDTu4%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by trinaths** [comment]
@Niklaus-xie - Somehow i'm not clear on the ask. please details clearly.

> any idea/comments/root cause about this issue so that we can provide more info to the customer. thanks very much.

> because when I tried to look at some related git history, e.g. f5devcentral/f5-ctlr-agent#44
> seems related to this issue as well. thanks

**Comment by Niklaus-xie** [comment]
to be more clear, 
1) [from](https://github.com/f5devcentral/f5-ctlr-agent/pull/44)  what is the specific reason behind this? because this also seems to be related the DEBUG issue.  any related conclusions/RCA(root cause analysis) from that.
2) for  2164   because it is ' impacting CIS from posting the data to BIGIP ',  customers are asking if any root cause analysis / plans.
thanks

**Comment by trinaths** [comment]
@Niklaus-xie 

> what is the specific reason behind this https://github.com/f5devcentral/f5-ctlr-agent/pull/44/files ? because this also seems to be related the DEBUG issue. any related conclusions/RCA(root cause analysis) from that.

This is disabled because f5-ctrl-agent is crashing while dumping more than 500 ARPs. This was fixed for ingress performance. This fix should not catch with this issue. they are not related.

> for 2164 because it is ' impacting CIS from posting the data to BIGIP ', customers are asking if any root cause analysis / plans.

We fixed this with --cccl-debug-level config with CIS. is that not solving this issue ?

**Comment by trinaths** [comment]
Created CONTCNTR-3138 for internal tracking.

**Comment by zongzw** [comment]
After some finding on this issue, it's because the debug log entry is too big.
The size of log entry is over `MaxScanTokenSize`(65536 bytes) mentioned from "https://cs.opensource.google/go/go/+/refs/tags/go1.17.8:src/bufio/scan.go;l=81", then it reports `ErrTooLong` error.
To fix it, the pull request https://github.com/F5Networks/k8s-bigip-ctlr/pull/2273 may help. Verified.

**Comment by trinaths** [comment]
Perfect! @zongzw. we will review the PR and update you.

**Comment by trinaths** [comment]
@zongzw From the PR, IMO double the buffer size will fix this issue temporarily, since the more the resources being monitored - more the debug log.

**Comment by zongzw** [comment]
Doubling the buffer size doesn't happen only once. It happens every time when `ErrTooLong`.
So, the buffer size doubles if needed when the resources grows.
Splitting the log may be not a good idea. 
It may break the integrity unexpectedly. Sometimes, we may want to parse some info from the log.

**Comment by zongzw** [comment]
Tested with 600 resource groups(vs+pool+member+..).
The `bufsize` was doubled 5 times, from 6536 to 2097152, 2MB. at ~400+th group.
The biggest log entry generates from here https://github.com/f5devcentral/f5-cccl/blob/master/f5_cccl/bigip.py#L277
