### ISSUE TITLE
F5 Ingress controller operator 1.7.0 installs wrong version of CRDs on Openshift

### ISSUE THREAD

**Issue by bukovjanmic** [F5Networks/k8s-bigip-ctlr#2171]
The current version of operator in OLM (1.7.0) seems to install old versions of CRDs. Specifically, the F5 controller logs these messages with version 2.7.0:

E0107 09:38:46.396620       1 reflector.go:138] github.com/F5Networks/k8s-bigip-ctlr/pkg/crmanager/informers.go:82: Failed to watch *v1.ExternalDNS: failed to list *v1.ExternalDNS: the server could not find the requested resource (get externaldnses.cis.f5.com)

Looking at installed CRDs, there is the old externaldnss.cis.f5.com from previous version.

Also, the new CRD Policy is missing,altogether leading to similar error for the Policy object.

Last but not least, the Github URL in operator description is also obsolete, leading to 404 errors.

**Comment by trinaths** [comment]
@bukovjanmic - please reinstall edns crd manually, CRD definition at https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml#L370. See https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/RELEASE-NOTES.rst#note

**Comment by bukovjanmic** [comment]
I tried this, it worked for the Policy object, which is new, but ExternalDNS could not be instantiated, as it conflicts with CRD from operator.
I tried removing the operator-installed CRD, then the new CRD was accepted, but operator keeps installing the old CRD back which in our case leads to inability to create an instance (ExternalDNS) - cluster reports an error on such attempt.

Plus, all instances of ExternalDNS are removed along the way - luckily, this is a test environment.

**Comment by trinaths** [comment]
@bukovjanmic - thanks for the update. We will be much more cautious when we deliver such updates. Where you able to re-install EDNS crd, we change the kind naming.

**Comment by trinaths** [comment]
@bukovjanmic - any update you can share to continue the investigation ?

**Comment by bukovjanmic** [comment]
Hi, I think it is not possible to update ExternalDNS by hand, as it conflicts with the one operator tries to (re-)install.
I think you should release a new operator (1.7.1) with correct CRDs, this should hopefully fix the problem.

**Comment by trinaths** [comment]
@bukovjanmic - From CIS 2.5 release, CIS operator will not auto install IngressClass and CRD definitions. Please install the updated CRD definitions and create instance of the operator.

see https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/RELEASE-NOTES.rst#before-upgrade-to-25

**Comment by bukovjanmic** [comment]
I am not sure I understand - current version of the operator (1.7.0) does install the CRDs; if I remove the existing CRD, it is re-installed within a minute  by the operator:

Do you mean to uninstall the entire operator and try again?

This is what gets autocreated back once I delete the ExternalDNS CRD:

kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: externaldnss.cis.f5.com
  labels:
    app.kubernetes.io/instance: f5-bigip-ctlr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
spec:
  group: cis.f5.com
  names:
    plural: externaldnss
    singular: externaldns
    shortNames:
      - edns
    kind: ExternalDNS
    listKind: ExternalDNSList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - domainName
              properties:
                dnsRecordType:
                  type: string
                  pattern: A
                domainName:
                  type: string
                  pattern: >-
                    ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
                loadBalanceMethod:
                  type: string
                pools:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - dataServerName
                    properties:
                      dataServerName:
                        type: string
                      dnsRecordType:
                        type: string
                        pattern: A
                      loadBalanceMethod:
                        type: string
                      monitor:
                        type: object
                        required:
                          - type
                          - send
                          - interval
                        properties:
                          interval:
                            type: integer
                          recv:
                            type: string
                          send:
                            type: string
                          timeout:
                            type: integer
                          type:
                            type: string
                            enum:
                              - http
                              - https
                      name:
                        type: string
                        pattern: >-
                          ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
      additionalPrinterColumns:
        - name: domainName
          type: string
          description: Domain name of virtual server resource
          jsonPath: .spec.domainName
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
status:
  conditions:
    - type: NamesAccepted
      status: 'True'
      lastTransitionTime: '2022-01-17T13:01:56Z'
      reason: NoConflicts
      message: no conflicts found
    - type: Established
      status: 'True'
      lastTransitionTime: '2022-01-17T13:01:56Z'
      reason: InitialNamesAccepted
      message: the initial names have been accepted
  acceptedNames:
    plural: externaldnss
    singular: externaldns
    shortNames:
      - edns
    kind: ExternalDNS
    listKind: ExternalDNSList
  storedVersions:
    - v1

**Comment by trinaths** [comment]
@bukovjanmic - 2.7 operator has changed a lot. Suggest reinstall operator and then manually create CR definitions and then recreate the operator instance and verify. Please share your findings.

**Comment by vklohiya** [comment]
@bukovjanmic, which version of openshift you are using ? Our latest version in OLM is 1.9.0, which does not install any CRDs.

**Comment by bukovjanmic** [comment]
We are on Openshift 4.8.17 at the moment, and have version 1.7.0. We are subscribed to beta channel (only  beta and alpha channel is available in OLM).

**Comment by vklohiya** [comment]
@bukovjanmic , Can you try upgrading  to version 1.9.0, it does not install any custom resource definitions.

**Comment by vklohiya** [comment]
@bukovjanmic  Can you update are you facing this issue with latest operator release 1.10.0 as well?

**Comment by bukovjanmic** [comment]
I would like to, but in OLM I still offers 1.7.0 as the latest version.

Although in the subscription channel, I see CSV 1.10.0 but no update is initiated.

Seems like a problem with OLM, I will try to reinstall entire operator.

**Comment by bukovjanmic** [comment]
I manually removed the operator and reinstalled from OLM, this time 1.10.0 version got installed.

When uninstalling the operartor, its CRDs were uninstalled too, which resulted in removal of all CR instances (TransportServer, VirtualServer) from the cluster. I am glad this is not a production'

However, the F5BigCtrl instance still did not get created, the operator was failing with:

{"level":"error","ts":1644400103.0625403,"logger":"helm.controller","msg":"Failed to sync release","namespace":"openshift-operators","name":"f5-server","apiVersion":"cis.f5.com/v1","kind":"F5BigIpCtlr","release":"f5-server","error":"failed to get candidate release: rendered manifests contain a resource that already exists. Unable to continue with update: could not get information about the resource: ingressclasses.networking.k8s.io \"f5\" is forbidden: User \"system:serviceaccount:openshift-operators:f5-bigip-ctlr-operator-controller-manager\" cannot get resource \"ingressclasses\" in API group \"networking.k8s.io\" at the cluster scope","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\toperator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\toperator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller....

And no deployment was created in kube-system. To circumvent this, I granted the cluster-admin role to the operator service account.

Also of note, IPAM controller operator does not work at all, it is being OOMKilled by Openshift and the deployment, which is created despite this, is failing to write to the PVC because of incompatible fsGroup with our CSI storage driver (why the fsGroup, runAsUser, etc. are in the securityContext?). 

I will create a separate ticket for this, I mention it because we have to remove some test cases because of this.

We will test ExternalDNS in coming days.

**Comment by vklohiya** [comment]
@bukovjanmic , Did you deleted the "F5BigCtrl" instance before uninstalling the operator? As it looks like the older instance of F5BigCtrl is still running which is trying to access the ingressclasses resources, but as new operator cluster role doesn't have this permission it's showing this  error. I would recommend you to delete the older instance and then install the operator again.

We will include this breaking change in our upgrade guide as well.

**Comment by trinaths** [comment]
@bukovjanmic - Is your issue resolved ?

**Comment by mdditt2000** [comment]
Closing this issue out. Please open a new Github issue using the latest version of CIS + Operator. Thanks!
