### ISSUE TITLE
CIS 2.7.0 HubMode issue

### ISSUE THREAD

**Issue by jinjia812** [F5Networks/k8s-bigip-ctlr#2178]
#### Setup Details
 CIS Version : 2.7.0      
 Build: f5networks/k8s-bigip-ctlr:2.7.0    
 BIGIP Version: Big IP 15.1.3.1     
 AS3 Version: 3.25     
 Agent Mode: AS3       
 Orchestration: K8S  
 Orchestration Version:      1.20.,13
 Pool Mode: Cluster  
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  
when I follow the link about HubMode "https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.5/hubMode".
the configuration of VS is OK, the pool name is OK. but the pool member is missing in the pool.
So i change the namespace of the configmap to "n1", which is the same NS as the depolyment and the SVC.
the configuration in F5 is OK.
So, it seems like the issue of  Hub mode 

#### Steps To Reproduce
1) follow the deploy and SVC ,and configmap in the repo of "https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.5/hubMode"
2) watch the config of the corresponding VS and Pool
3) change the NS of the configmap to "n1", so not using Hubmode
4)watch the config of the corresponding VS and Pool

#### Diagnostic Information

```  -------it seems nothing wrong in the debug log of cis------------


2022/01/11 13:53:50 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:control-hub-1 --- message: success
2022/01/11 13:53:50 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:k8s --- message: no change
2022/01/11 13:53:50 [DEBUG] [AS3] Preparing response message to response handler for arp and fdb config
2022/01/11 13:53:50 [DEBUG] [AS3] Sent response message to response handler for arp and fdb config
2022/01/11 13:53:50 [DEBUG] [CORE] Finished syncing namespace control-hub-2 (6.73µs)
2022/01/11 13:53:50 [DEBUG] [CORE] Finished syncing namespace control-hub-1 (79.656µs)
2022/01/11 13:53:50 [DEBUG] [CORE] Periodic enqueue of Service from Namespace: n1
2022/01/11 13:53:50 [DEBUG] [CORE] Finished syncing namespace n1 (19.109µs)
2022/01/11 13:53:50 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/01/11 13:53:50 [DEBUG] [CORE] Finished syncing virtual servers f5-hello-world-n1 in namespace n1 (32.684463ms), 2/2
2022/01/11 13:53:50 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/01/11 13:53:50 [DEBUG] [CORE] Finished syncing virtual servers f5-hello-world-n1 in namespace n1 (11.589546ms), 2/2
2022/01/11 13:53:50 [DEBUG] [CORE] NodePoller (0xc000128ab0) ready to poll, last wait: 30s

2022/01/11 13:53:50 [DEBUG] [CORE] NodePoller (0xc000128ab0) notifying listener: {l:0xc0005aef60 s:0xc0005aefc0}
2022/01/11 13:53:50 [DEBUG] [CORE] NodePoller (0xc000128ab0) listener callback - num items: 1 err: <nil>
2022/01/11 13:53:50 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/01/11 13:53:50 [DEBUG] [CORE] Finished syncing virtual servers f5-hello-world-n1 in namespace n1 (12.530562ms), 2/2
2022/01/11 13:53:50 [DEBUG] [2022-01-11 13:53:50,943 __main__ DEBUG] config handler woken for reset
2022/01/11 13:53:50 [DEBUG] [2022-01-11 13:53:50,943 __main__ DEBUG] loaded configuration file successfully
2022/01/11 13:53:50 [DEBUG] [2022-01-11 13:53:50,943 __main__ DEBUG] NET Config: {}
2022/01/11 13:53:50 [DEBUG] [2022-01-11 13:53:50,943 __main__ DEBUG] loaded configuration file successfully
2022/01/11 13:53:50 [DEBUG] [2022-01-11 13:53:50,946 __main__ DEBUG] updating tasks finished, took 0.003291606903076172 seconds

#### Observations (if any)

**Comment by zongzw** [comment]
@jinjia812  From my observation, it's not an issue actually. 
I verified this function in https://gitee.com/zongzw/devel-cis/tree/master/hubmode-test
You need to add `--hubmode=true` to k8s-bigip-ctlr parameter list.

Seen from the code, the hubmode function was added 8 months ago.

The document from https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.5/hubMode/README.md should be updated to add `--hubmode=true` to the `args`, so that it can avoid some misleading.

**Comment by jinjia812** [comment]
ok thanks




    


On 02/22/2022 21:35, f5zong wrote: 
@jinjia812  From my observation, it's not an issue actually.
I verified this function in https://gitee.com/zongzw/devel-cis/tree/master/hubmode-test
You need to add --hubmode=true to k8s-bigip-ctlr parameter list.
Seen from the code, the hubmode function was added 8 months ago.
The document from https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.5/hubMode/README.md should be updated to add --hubmode=true to the args, so that it can avoid some misleading.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/F5Networks/k8s-bigip-ctlr/issues/2178#issuecomment-1047803316",
"url": "https://github.com/F5Networks/k8s-bigip-ctlr/issues/2178#issuecomment-1047803316",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by trinaths** [comment]
Based on above discussion, the issues is resolved with correction in CIS configuration. Closing this issue.
