### ISSUE TITLE
Helm Chart ClusterRole Does Not Have Correct Permissions

### ISSUE THREAD

**Issue by bmayfi3ld** [F5Networks/k8s-bigip-ctlr#2184]
#### Setup Details
 CIS Version : 2.7.0
 Build: f5networks/k8s-bigip-ctlr:2.7.0
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.33
 Agent Mode: AS3
 Orchestration: K8S 
 Orchestration Version:  v1.21.6
 Pool Mode: Nodeport  

#### Description 
The file 
https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml

Seems to have the wrong resources listed.

```
    resources:
      - virtualservers
      - tlsprofiles
      - transportservers
      - externaldnss
      - ingresslinks
      - virtualservers/status
      - ingresslinks/status
```

Should probably be

```
  resources:
  - virtualservers
  - tlsprofiles
  - transportservers
  - externaldnses
  - ingresslinks
  - virtualservers/status
  - ingresslinks/status
  - policies
```

With policies added, and externaldnses spelled correctly.

if you don't you get the error 

```
E0113 21:03:27.829917 1 reflector.go:138] github.com/F5Networks/k8s-bigip-ctlr/pkg/crmanager/informers.go:94: Failed to watch *v1.Policy: failed to list *v1.Policy: policies.cis.f5.com is forbidden: User "system:serviceaccount:f5-cis:k8s-bigip-ctlr" cannot list resource "policies" in API group "cis.f5.com" at the cluster scope
--
Thu, Jan 13 2022 3:03:32 pm | E0113 21:03:32.129216 1 reflector.go:138] github.com/F5Networks/k8s-bigip-ctlr/pkg/crmanager/informers.go:82: Failed to watch *v1.ExternalDNS: failed to list *v1.ExternalDNS: externaldnses.cis.f5.com is forbidden: User "system:serviceaccount:f5-cis:k8s-bigip-ctlr" cannot list resource "externaldnses" in API group "cis.f5.com" at the cluster scope
```

  

#### Steps To Reproduce
1) Install CIS with the helm chart
2) Note the errors in the log after the pod starts.
3)

#### Expected Result 
No permissions errors

#### Actual Result  
Permissions errors as listed above.

**Comment by mleklund** [comment]
I am also seeing this.

**Comment by trinaths** [comment]
created CONTCNTR-3093 for internal tracking.
