### ISSUE TITLE
copyResourceData function did not handle iapps, expected to copy over iapps as well.

### ISSUE THREAD

**Issue by Niklaus-xie** [F5Networks/k8s-bigip-ctlr#2191]
#### Setup Details
 CIS Version : 2.7   
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x           
 Agent Mode: AS3/CCCL       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster     
 
#### Description  
 just turn on DEBUG level. and create an iapp using configmap and you can find out that it does not copy over iapps.

Description
args:
--bigip-username=$(BIGIP_USERNAME)
--bigip-password=$(BIGIP_PASSWORD)
--bigip-url=https://XXXXX:8443
--insecure=true
--bigip-partition=kubernetes
--pool-member-type=cluster
--flannel-name=/Common/fl-tunnel
--agent=cccl
--namespace=default
--verify-interval=45
--node-poll-interval=120
--http-listen-address=0.0.0.0:9113
--periodic-sync-interval=180
--log-level=DEBUG

#### Steps To Reproduce
1) create a configmap for iapp 
2)  this function copyResourceData() forgets about iapps.
3) this can also be seen in the logs  as “[CCCL] LTM Resources: {}”,  which does not include iapps content.

#### Expected Result 
copy over iapps.

#### Actual Result  
the function forgets about this part.

**Comment by trinaths** [comment]
@Niklaus-xie - What is the impact when the iapps are not copied over ? Please share the how this issue impacts CIS from posting the data to BIGIP ?

**Comment by Niklaus-xie** [comment]
@trinaths  let's not complicate this problem. From your point of view,  should it be copied over or not?  thanks

**Comment by trinaths** [comment]
@Niklaus-xie - Is iapp processing working well with out this fix ? Just want to understand the issue this fix is really solving.

**Comment by trinaths** [comment]
Created CONTCNTR-3138 for internal tracking.

**Comment by vklohiya** [comment]
@Niklaus-xie , Can you confirm that iapp processing is working well without this fix? PR #2165 only fix the logging, it does not fix any functionality.
