### ISSUE TITLE
Error: ipams.fic.f5.com "f5-server-f5-bigip-ctlr.ocpnew.ipam" not found 

### ISSUE THREAD

**Issue by melakutena** [F5Networks/k8s-bigip-ctlr#2193]
Hi All.
I installed cis 2.7.0 and Ipam controller 0.16. 

but I see the below ipam pod error  when trying to allocate ip for service type LB

[ERROR] Unable to Update IPAM: kube-system/f5-server-f5-bigip-ctlr.ocpnew.ipam Error: ipams.fic.f5.com "f5-server-f5-bigip-ctlr.ocpnew.ipam" not found 

I need your support.

Regards,
Melaku

**Comment by trinaths** [comment]
@melakutena - Suggest follow the steps from https://github.com/F5Networks/f5-ipam-controller/issues/92#issuecomment-1017647682. This should resolve the issue. Please share your findings.

**Comment by melakutena** [comment]
Thanks. i followed the steps from    F5Networks/f5-ipam-controller#92 (comment) and it did solve the issue.


Many thanks.

**Comment by trinaths** [comment]
@melakutena  - Thank you for sharing your feedback. We will add this to our troubleshooting document. Closing this issue.
