### ISSUE TITLE
IngressLink - Allow Sync of BIG-IP configuration

### ISSUE THREAD

**Issue by BarryHaines** [F5Networks/k8s-bigip-ctlr#2197]
#### Title
IngressLink - Allow Sync of BIG-IP configuration

#### Description
Allow for sync parameter to be pass the BIG-IP sync-group in ingresslink configuration file that would enable the sync of the configuration after the ingresslink virtual server is created or updated.

#### Actual Problem
When the ingresslink deploys the virtual server the configuration is not synced when big-ips are configurated to sync manually.

#### Solution Proposed
The IngressLink configuration should allow additional parameters for properties that are available for AS3 declarations and this would include passing the syncToGroup property that is available in the AS3 class.

#### Alternatives
Allow for the modification of the AS3 schema used by the IngressLink configuration.

**Comment by mdditt2000** [comment]
Good afternoon @BarryHaines We recommend using manual sync on BIG-IP when using CIS. Recommendation is to create a second CIS for the standby BIG-IP.
