### ISSUE TITLE
Feature request: link an existing health monitor to a VirtualServer custom resource

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2201]
#### Title
Link an existing health monitor on BIG-IP to a VirtualServer custom resource.

#### Description
Currently it appears a customer cannot reference an existing health monitor when creating a VirtualServer custom resource.

#### Solution Proposed
CRD extended to allow for referencing existing health monitor on BIG-IP.

#### Alternatives
The alternative is to define the health monitor required in the CRD. This is workable, but would be nice if we could reference an existing monitor that was created in the GUI.

**Comment by trinaths** [comment]
Created [CONTCNTR-3161] for internal tracking.
