### ISSUE TITLE
Feature request: define loadBalanceMethod property for VirtualServers or TransportServer CRDs. 

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2202]
#### Title
Define a loadBalanceMethod property for VirtualServers or TransportServer CRDs. There is one for ExternalDNS, but that is all.

#### Actual Problem
It appears that the VirtualServer and TransportServer CRD's do not allow us to define load balance method. I assume they therefore use the default AS3 value?

#### Solution Proposed
I would imagine this could be an optional value, with the default matching the [AS3 default of round robin](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pool). 

#### Alternatives
I'm unsure of an alternative today, apart from AS3 declaration via configMap.

#### Additional context
This is not urgent but was noticed and questioned by a customer for future use.

**Comment by trinaths** [comment]
Created [CONTCNTR-3146] for internal tracking.

**Comment by mdditt2000** [comment]
Demo/preview of this feature request: https://youtu.be/As9FTzW1BoA

Example Repo: https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.9/loadbalancingmethod#readme

**Comment by trinaths** [comment]
Dev PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2368

Closing this issue.
