### ISSUE TITLE
documentation error: broken link

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2203]
#### Description  
 Currently this page overviews the VirtualServer CRD: https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html

There is a broken link that takes me here (currently I get a 404 at this URL): https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/customResource/basic/vs-customresourcedefinition.yml

#### Steps To Reproduce
1) click on first link
2) read on and look for the link titled "Open API Schema Validation for VirtualServer"

#### Expected Result 
see Spec of VS CRD

#### Actual Result  
get 404

**Comment by trinaths** [comment]
Created CONTCNTR-3114 for internal tracking.

**Comment by trinaths** [comment]
Documentation updated. Closing this issue.
