### ISSUE TITLE
Bulk eDNS deletion fails due to Index error in CIS

### ISSUE THREAD

**Issue by walkingtub** [F5Networks/k8s-bigip-ctlr#2205]
#### Setup Details
 CIS Version : 2.7.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.3     
 AS3 Version: 3.27      
 Agent Mode: AS3  
 Orchestration: K8S      
 Orchestration Version: 1.20.4
 Pool Mode: Cluster     

#### Description  
Trying to create/delete more than 1 eDNS entry with a single yaml file. (each entry separated with end of directives marker "---")  Deletion is failing due to an Index error in CIS logs. "IndexError: list index out of range"

#### Steps To Reproduce
1) Create vserver file with more than 1 virtual server separated by "---"
2) Create eDNS file with more than 1 URL separated by "---"
3) Delete vserver file and eDNS file.

#### Expected Result 
All of the vservers and eDNS Wide IP's and Pools should be deleted.

#### Actual Result  
All vservers are deleted, only 2 pools are deleted, all of the wide ip's remain. Error in CIS log mentions "IndexError: list index out of range"

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)
![image](https://user-images.githubusercontent.com/61437966/151253248-3f1ab014-c49c-4b26-8e4d-d394411a46e2.png)

**Comment by trinaths** [comment]
@walkingtub - Please share the YAML files to investigate this issue.

**Comment by walkingtub** [comment]
[f5_2.7.1_manifests.zip](https://github.com/F5Networks/k8s-bigip-ctlr/files/7946012/f5_2.7.1_manifests.zip)

**Comment by trinaths** [comment]
Created CONTCNTR-3136 for internal tracking
