### ISSUE TITLE
CIS 2.7.1 Error serverAddresses: Invalid type. Expected: array, given: null

### ISSUE THREAD

**Issue by tomaszmzyk** [F5Networks/k8s-bigip-ctlr#2209]
#### Setup Details
 CIS Version : 2.7.1    
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.4
 AS3 Version: 3.20   
 Agent Mode: AS3     
 Orchestration: OSCP      
 Orchestration Version: 4.8.18
 Pool Mode: Cluster      
 Additional Setup details: OpenshiftSDN CNI

#### Description  
Hi after migrate from version 2.1.1 to 2.7.1  I observed errors in CIS logs:
2022/01/28 09:52:48 [ERROR] [AS3] Template is not valid. see errors
2022/01/28 09:52:48 [ERROR] - (root): Must validate one and only one schema (oneOf)
2022/01/28 09:52:48 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/01/28 09:52:48 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/01/28 09:52:48 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/01/28 09:52:48 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/01/28 09:52:48 [ERROR] - declaration: Must validate all the schemas (allOf)

In version 2.1.1 this errors don't exists.
This is in situation, when in ConfigMap exists configuration for not existent Service object on Openshift and CIS can't find proper pods assigned to Service

Error leads to not sync configuration between F5 and OCSP.

#### Steps To Reproduce
1) Create config map with AS3 declaration with Service that not exists on OCSP
2) Look at the logs
3) Error should occur

#### Expected Result
CIS should sync configuration between F5 and OCSP

#### Actual Result  
Errors in CIS logs and not sync between F5 and OCSP

#### Observations (if any)

This is easly to reproduce.
In one of namespace I run scale replicas from 4 to 2 pods
Results:
When use version 2.7.1 -> on F5 pods are market as DOWN but not deleted from pool
When use version 2.1.1 -> on F5 pods are market as DOWN and after some time deleted from pool as expected.

Regards

**Comment by trinaths** [comment]
@tomaszmzyk  - I think you are hitting https://github.com/F5Networks/k8s-bigip-ctlr/issues/1602#issuecomment-803802170

Suggest to update as per the suggestions in the comment.

**Comment by tomaszmzyk** [comment]
Hi
I read this comment. When I look at the our configuration, as I wrote before, in ConfigMap devs have configuration related to non existent Services, so create in that style is forrbiden ?
I'm courious why all sync not work, I migrate to version 2.7.1 for options: filter-tenants of CIS, that should prevent to syn only corrupted ConfigMap not all ?
Maybe I misunderstood how this options works ?
Regards

**Comment by trinaths** [comment]
>  configuration related to non existent Services, so create in that style is forrbiden ?

Yes. Without proper services created, EndPoints will not be created and CIS cannot generate correct AS3 with pool members. So you will see these errors. 

>2022/01/28 09:52:48 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null

**Comment by trinaths** [comment]
@tomaszmzyk - Does this resolve your issue ?

**Comment by tomaszmzyk** [comment]
Hi
Thanks for explanation, but one things is strange.
I have enabled option: filter-tenants
From the behavior of this options, all proper AS3 declaration should be synced between F5 and OCSP.
From my checks is not.
I run a litlle check, I change only replicaset for one of deployments with correct configuration (this is scale down from 4 to 2 pods).
I look at the F5 and see that F5 correctry set deleted pod to DOWN status, but did't delete them and I wait a lot of time (more than 10 minutes). After that I again change replicas from 2 to 4, and to my surprise on F5 new pods are added.
Regards

**Comment by trinaths** [comment]
@tomaszmzyk - Please share your CIS config and any examples file set to try at our end

**Comment by trinaths** [comment]
We will validate this issue. Created CONTCNTR-3081 for internal tracking. 

@tomaszmzyk - Please share your CIS config and any examples file set to try at our end

**Comment by tomaszmzyk** [comment]
Hi
Sorry for the late answer. I will prepare examples tommorow our CET time and attach to case.
Regards

**Comment by tomaszmzyk** [comment]
Hi
Below my configuration:

CIS ConfigMap:
`     containers:
        - name: k8s-bigip-ctrl
          image: "registry.example.com/f5networks/k8s-bigip-ctlr:2.7.1"
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # Credential for F5
            "--credentials-directory=/tmp/kredki",
            # Replace with the IP address or hostname of your BIG-IP device
            "--bigip-url=10.10.10.10",
            # Replace with the name of the BIG-IP partition you want to manage
            "--bigip-partition=OCSP",
            "--pool-member-type=cluster",
            # Replace tunnel for OpenShift vxlan
            "--openshift-sdn-name=/OCSP/vxlan_tunnel",
            # Set manage-configmaps TRUE to manage config maps
            "--manage-configmaps=true",
            # Login level
            "--log-level=DEBUG",
            # When set to true, adds the body of AS3 API response in Controller logs.
            "--log-as3-response=true",
            # Self-signed cert
            "--insecure=true",
            # The interval at which the CIS verifies that the BIG-IP configuration matches the state of the orchestration system
            "--verify-interval=60",
            # Specify to use tenant filtering API for AS3 declaration. This allows CIS to process each AS3 Tenant separately. Compatible with ConfigMap only
            "--filter-tenants=true",
            # If true, analytics data is not sent to F5.
            "--disable-teems",
            # Specifies the time, in seconds, that CIS waits to post the available AS3 declaration.
            "--as3-post-delay=30",
            # Tells the k8s-bigip-ctlr to watch any namespace with this label
            "--namespace-label=loadbalancer=f5",
            # Choose Agent for deployment
            "--agent=as3"
            ]
          volumeMounts:
          - name: creds
            mountPath: "/tmp/creds"
            readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: f5-secret
`
I scale my example application from to to 6 pods:
`openshift-example-php-5cb954f45-4trk7   1/1     Running   0          12m     172.132.4.47 
openshift-example-php-5cb954f45-6btsl   1/1     Running   1          4d12h   172.133.4.41 
openshift-example-php-5cb954f45-74mkz   1/1     Running   1          4d12h   172.133.4.40 
openshift-example-php-5cb954f45-hpp52   1/1     Running   0          12m     172.132.4.45 
openshift-example-php-5cb954f45-l9wzl   1/1     Running   0          12m     172.132.4.46 
openshift-example-php-5cb954f45-zjhd4   1/1     Running   0          12m     172.132.3.254`

And on F5 I see that also replicas changed:
`ltm pool /Y_OCP_OPENSHIFT/APP_OPENSHIFT/POOL_EXAMPLE {
    members {
        /Y_OCP_OPENSHIFT/172.132.3.254:8080 {
            address 172.132.3.254
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.132.4.45:8080 {
            address 172.132.4.45
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.132.4.46:8080 {
            address 172.132.4.46
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.132.4.47:8080 {
            address 172.132.4.47
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.133.4.40:8080 {
            address 172.133.4.40
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.133.4.41:8080 {
            address 172.133.4.41
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
    partition Y_OCP_OPENSHIFT
}
`

Next step is replicas down to 2 pods:
`$ date;oc scale deployment openshift-example-php --replicas=2 -n bsk-openshift
Tue Feb  1 08:50:41 CET 2022
deployment.apps/openshift-example-php scaled
$ oc get po -n bsk-openshift -o wide
NAME                                    READY   STATUS        RESTARTS   AGE     IP              NODE                  NOMINATED NODE   READINESS GATES
openshift-example-php-5cb954f45-4trk7   1/1     Terminating   0          37m     172.132.4.47   
openshift-example-php-5cb954f45-6btsl   1/1     Terminating   1          4d12h   172.133.4.41    
openshift-example-php-5cb954f45-74mkz   1/1     Running       1          4d12h   172.133.4.40 
openshift-example-php-5cb954f45-hpp52   1/1     Terminating   0          37m     172.132.4.45   
openshift-example-php-5cb954f45-l9wzl   1/1     Terminating   0          37m     172.132.4.46    
openshift-example-php-5cb954f45-zjhd4   1/1     Running       0          37m     172.132.3.254 
`

On F5 I see:
`# date
Tue Feb  1 08:51:48 CET 2022
# tmsh list ltm pool /Y_OCP_OPENSHIFT/APP_OPENSHIFT/POOL_EXAMPLE
ltm pool /Y_OCP_OPENSHIFT/APP_OPENSHIFT/POOL_EXAMPLE {
    members {
        /Y_OCP_OPENSHIFT/172.132.3.254:8080 {
            address 172.132.3.254
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.132.4.45:8080 {
            address 172.132.4.45
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.132.4.46:8080 {
            address 172.132.4.46
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.132.4.47:8080 {
            address 172.132.4.47
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.133.4.40:8080 {
            address 172.133.4.40
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.133.4.41:8080 {
            address 172.133.4.41
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
    partition Y_OCP_OPENSHIFT
}
`
Some pods have status down as expected and after some of time this down pods have been deleted:
` date
Tue Feb  1 09:02:23 CET 2022
# tmsh list ltm pool /Y_OCP_OPENSHIFT/APP_OPENSHIFT/POOL_EXAMPLE
ltm pool /Y_OCP_OPENSHIFT/APP_OPENSHIFT/POOL_EXAMPLE {
    members {
        /Y_OCP_OPENSHIFT/172.132.3.254:8080 {
            address 172.132.3.254
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /Y_OCP_OPENSHIFT/172.133.4.40:8080 {
            address 172.133.4.40
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
    partition Y_OCP_OPENSHIFT
}
`
But last time I wait a couple hour and nothing happens, I only see pool members in state down

**Comment by tomaszmzyk** [comment]
Hi
What I observed. In errors I see:
Error processing configmap cm-f5-app in namespace: example with err: invalid character ',' looking for beginning of value

After that in second namespace where new deployment are installed there is no sync between f5 and Openshift:

$ oc get po -o wide -n example2
NAME                                   READY   STATUS    RESTARTS   AGE    IP           
example2a-6d54847c75-npktk   2/2     Running   2          6d3h   172.132.2.138
example2b-645c57dd79-x6hsk     2/2     Running   1          88m    172.132.2.11 

On F5 there is a following pools:

```
pool /EXAMPLE2/APP_EXAMPLE2/1 {
    members {
        /EXAMPLE2/172.132.2.138:15000 {
            address 172.132.2.138
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { https }
    partition EXAMPLE2
}
ltm pool /EXAMPLE2/APP_EXAMPLE2/2 {
    members {
        /EXAMPLE2/172.132.2.138:15444 {
            address 172.132.2.138
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { https }
    partition EXAMPLE2
}
ltm pool /EXAMPLE2/APP_EXAMPLE2/3 {
    members {
        /EXAMPLE2/172.132.3.110:8430 {
            address 172.132.3.110
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { https }
    partition EXAMPLE2
}
ltm pool /EXAMPLE2/APP_EXAMPLE2/4 {
    members {
        /EXAMPLE2/172.132.3.110:15443 {
            address 172.132.3.110
            session monitor-enabled
            state down
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { https }
    partition EXAMPLE2
}
```

So as you see eve if I have enabled "--filter-tenants=true" there are missconfiguration between F5 and OCSP, but this could be related to another openned issue : #2210
Regards

**Comment by trinaths** [comment]
@tomaszmzyk - I see that this issue is resolved. Can you confirm the same ?

**Comment by tomaszmzyk** [comment]
Hi
For last 2 days I tested configuration, deletes, creates and for me CIS running unstable for sync.
One time sync goes quickly and without any issues, one time not.
I only testing scale up and down in one tenatnt, and sometimes sync not working.

Second confiusing thing is log from error, when you look at the logs you don't have information about in which tenant erorr exist, if you have a lot of them, this is very hard troubleshooting.

Regards

**Comment by trinaths** [comment]
@tomaszmzyk With filter-tenants and in debug log level, CIS logs will be more clearer. Please refer to BIGIP logs on how the CIS posted config is processed. Also from CIS log timestamp we can get more info on the same. Please share the error logs when Sync is not working so that we can investigate more.

**Comment by tomaszmzyk** [comment]
Hi
In logs I have:
2022/02/04 10:18:16 [DEBUG] [CORE] Finished syncing virtual servers example01-svc in namespace example01 (799.887443ms), 113/113
2022/02/04 10:18:16 [ERROR] [AS3] Template is not valid. see errors
2022/02/04 10:18:16 [ERROR] - (root): Must validate one and only one schema (oneOf)
2022/02/04 10:18:16 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/02/04 10:18:16 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/02/04 10:18:16 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/02/04 10:18:16 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/02/04 10:18:16 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/02/04 10:18:16 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/02/04 10:18:16 [ERROR] - declaration: Must validate all the schemas (allOf)
2022/02/04 10:18:49 [DEBUG] [CORE] Finished syncing virtual servers example02-svc in namespace example02 (793.883237ms), 113/113
2022/02/04 10:18:52 [ERROR] [AS3] Template is not valid. see errors
2022/02/04 10:18:52 [ERROR] - (root): Must validate one and only one schema (oneOf)
2022/02/04 10:18:52 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/02/04 10:18:52 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/02/04 10:18:52 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/02/04 10:18:52 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/02/04 10:18:52 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/02/04 10:18:52 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/02/04 10:18:52 [ERROR] - declaration: Must validate all the schemas (allOf)
2022/02/04 10:22:41 [DEBUG] [CORE] Finished syncing virtual servers example03 in namespace example03 (154.242µs), 113/113
2022/02/04 10:22:42 [ERROR] [AS3] Template is not valid. see errors
2022/02/04 10:22:42 [ERROR] - (root): Must validate one and only one schema (oneOf)
2022/02/04 10:22:42 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/02/04 10:22:42 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/02/04 10:22:42 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/02/04 10:22:42 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/02/04 10:22:42 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/02/04 10:22:42 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/02/04 10:22:42 [ERROR] - declaration: Must validate all the schemas (allOf)

For which one tenant this ERRORS belongs ?
I see also in log:
2022/02/04 10:22:11 [DEBUG] [CORE] Discovered members for service b... is []
2022/02/04 10:22:11 [DEBUG] [CORE] Discovered members for service ... is []

But there is proper assigment but from some reasons pods not working for this service.

Regards

**Comment by trinaths** [comment]
@tomaszmzyk 
This must issue service discovery issue. Please check https://github.com/F5Networks/k8s-bigip-ctlr/issues/1602#issuecomment-803802170

**Comment by tomaszmzyk** [comment]
Hi
I know that is related to issue #1602, but if you have a lot of tenants and configmap, find in which one this occurs is difficult without information in log, you must check one by one and spend about this a lot of time.
Nicely will be for eexample the logs looks like:

2022/02/04 10:22:42 [ERROR] [AS3] Template is not valid. see errors (tenant: <name of namespace or configmap>)

Regards

**Comment by tomaszmzyk** [comment]
Thanks in advance :)

**Comment by trinaths** [comment]
Created [CONTCNTR-3150]for tracking log improvements.

**Comment by vklohiya** [comment]
@tomaszmzyk , Can you share your config-map which you are using with CIS?

**Comment by ibmbwolfe** [comment]
We are having this same issue.  We have 200+ VIP's being created/managed under a single Tennent/Partition to host http/https traffic with configmaps reserved for creating multi-tenant hosting non-http/https traffic.  

Reproducible issue
If an ingress yaml gets pushed up that is accepted by the cluster but fails the at the CIS level.  The CIS logging is not descriptive enough to log the actual issue and the namespace/project.   The CIS continues to log items like {Configured Rule} which actually failed/never updated as the CIS stopped.

This is a problem with the CIS controller logging.  All versions 2.1 through 2.11 experience the same failures that are not logged appropriately.


This needs added as a BugFix

**Comment by trinaths** [comment]
@ibmbwolfe - Suggest create a new Bug with all required info.
