### ISSUE TITLE
[2.7.0] filter-tenants only covers syntax errors

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2210]
#### Setup Details
 CIS Version : 2.7.0    
 Build: f5networks/k8s-bigip-ctlr:latest       
BIGIP Version: Big IP 15.1.0.5
AS3 Version: 3.22.1
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.21.5
Pool Mode: Nodeport
Additional Setup details: Calico

#### Description  
  
Need to be able to allow configmaps to be pushed to BIG-IP even in the case where a bad configmap has bad configuration, not just syntax.

#### Steps To Reproduce
1) Deploy configmap with a template type that does not exist to simulate a bad configmap (see example below)
2) Confirm error in controller logs
3) Attempt to deploy another working configmap without any errors, and see that it does not get deployed (blocked)

#### Expected Result 

configmaps with errors should not block other working configmaps when using filter-tenants=true

#### Actual Result  

configmaps are blocked when there is a semantic error

#### Diagnostic Information

bad configmap (contains a template that does not exist..    ` "template": "http3"` )
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration5
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.20.0",
            "id": "urn:uuid:5",
            "label": "HTTPS VS with WAF",
            "remark": "CICD example",
            "Tenant5": {
                "class": "Tenant",
                "Test1": {
                    "class": "Application",
                    "template": "http3"
                    "san_test_svcaddr": {
                        "class": "Service_Address",
                        "trafficGroup": "/Common/traffic-group-1",
                        "virtualAddress": "200a:b:c:d:e::5006"
                    },
                    "serviceMain": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [{ "use": "san_test_svcaddr"}],
                        "pool": "f5_pool"
                    },
                    "f5_pool": {
                        "class": "Pool",
                         "monitors": [ {
                           "use": "http_mon"
                         }],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": [],
                                "shareNodes": true
                            }
                        ]
                    },
                    "http_mon" : {
                      "class": "Monitor",
                      "monitorType": "http",
                      "send": "GET /apim HTTP/1.1\r\nHost: mytest.co.jp\r\nConnection: Close",
                      "receive": "404",
                      "targetPort": 8080
                  }
                }
            }
        }
    }
```

Confirm the errors

```
2022/01/31 06:29:18 [DEBUG] [AS3] posting request to https://172.8.1.147/mgmt/shared/appsvcs/declare/Tenant5
2022/01/31 06:29:18 [ERROR] [AS3] Big-IP Responded with code: 422
2022/01/31 06:29:18 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: http3]
2022/01/31 06:29:18 [DEBUG] [AS3] posting request to https://172.8.1.147/mgmt/shared/appsvcs/declare/k8s
2022/01/31 06:29:18 [ERROR] [AS3] Big-IP Responded with code: 422
2022/01/31 06:29:18 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: http3]
2022/01/31 06:29:18 [DEBUG] [AS3] posting request to https://172.28.15.147/mgmt/shared/appsvcs/declare/i'm_a_good_tenant
2022/01/31 06:29:18 [ERROR] [AS3] Big-IP Responded with code: 422
2022/01/31 06:29:18 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: http3]
2022/01/31 06:29:18 [DEBUG] [AS3] Preparing response message to response handler for arp and fdb config
2022/01/31 06:29:18 [DEBUG] [AS3] Sent response message to response handler for arp and fdb config
2022/01/31 06:29:18 [DEBUG] [AS3] Error handling for event statusCommonResponse

```
CIS arguments

```
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=https://172.8.1.147",
            "--bigip-partition=k8s",
            "--insecure=true",
            "--pool-member-type=nodeport",
            "--log-as3-response=true",
            "--manage-ingress=false",
            "--log-level=debug",
            "--manage-configmaps=true",
            "--as3-validation=true",
            #"--hubmode=true",
            "--agent=as3",
            "--filter-tenants=true",
            #"--disable-teems=true",
            "--as3-post-delay=30",
            "--verify-interval=60"
            ]
```

#### Observations (if any)

Additional query: To what length does --as3-validation=true actually validate a configmap? Is it only json syntax? schema validation?

**Comment by trinaths** [comment]
We will validate this issue. Created CONTCNTR-3081 for internal tracking.

**Comment by tkam8** [comment]
Ideas:

1. fallback mechanism to recover from a 422 error from BIG-IP
2. incorporate "dry-run" capability from AS3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/as3-api.html#post-actions
3. Do actual as3 semantic validation

**Comment by trinaths** [comment]
@tkam8 CIS does only schema validation for filter-tenants or as3-validations. Data validation is taken care at AS3.
IMO, this issue is not valid based on the CIS current behaviour. 

As the feature `filter-tenants`, we are not sending 1 single AS3 declaration for all tenants, but individual declarations.

See the logs, 
Tenant: Tenant5
> 2022/01/31 06:29:18 [DEBUG] [AS3] posting request to https://172.8.1.147/mgmt/shared/appsvcs/declare/Tenant5
> 2022/01/31 06:29:18 [ERROR] [AS3] Big-IP Responded with code: 422
> 2022/01/31 06:29:18 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: http3]

another AS3 post, Tenant: k8s

> 2022/01/31 06:29:18 [DEBUG] [AS3] posting request to https://172.8.1.147/mgmt/shared/appsvcs/declare/k8s
> 2022/01/31 06:29:18 [ERROR] [AS3] Big-IP Responded with code: 422
> 2022/01/31 06:29:18 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: http3]

another AS3 post, Tenant:i'm_a_good_tenant

> 2022/01/31 06:29:18 [DEBUG] [AS3] posting request to https://172.28.15.147/mgmt/shared/appsvcs/declare/i'm_a_good_tenant
> 2022/01/31 06:29:18 [ERROR] [AS3] Big-IP Responded with code: 422
> 2022/01/31 06:29:18 [ERROR] [AS3] Raw response from Big-IP: map[code:422 message:Invalid data property: http3]

From all the above, CIS schema validation is passed for all the configuration and failed in data validation at AS3.

**Comment by tkam8** [comment]
Hi Trinath, thanks for the analysis. 

Since CIS is not designed to do AS3 data validation, there needs to be a way to recover from a configmap that fails. 
If BIG-IP sends back an error like 422, CIS should stop trying to send the invalid configmap. 

Any other ideas welcome.
