### ISSUE TITLE
Web socket timeout issue,  how to use an alternate connection profile (CCCL)

### ISSUE THREAD

**Issue by somejfn** [F5Networks/k8s-bigip-ctlr#2211]
#### Setup Details
 CIS Version : 1.14
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP v12.1.5.3 
 AS3 Version: n/a
 Agent Mode: CCCL       
 Orchestration: K8s/Kubeadm 
 Orchestration Version:    1.19
 Pool Mode: Cluster
 Additional Setup details:  F5 vserver is fronting nginx ingress controllers

#### Description  

Our k8s nginx ingress controllers are fronted by an F5 virtual server managed via bigip-ctrl.  An application is using websockets with long processing times and we found some timeout issues that we can mitigate at the nginx ingress controller level but we still have a timeout issue at the F5 vserver level because of the default tcp connection profile.   

The issue is likely the idle time between the client sending the request and the pod producing a response which can be >5 minutes.

In the CCCL schema,  I presume the connection profile is defined by the "mode":

```
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "10.X.X.X"
          },
          "partition": "k8s_clustername",
          "balance": "least-connections-member",
          "mode": "tcp"
        }
```

Seems the schema only allows these values:  tcp|udp|http.

Q. Is there anyway to use an alternate connection profile here and get a longer timeout than the default ?  

#### Steps To Reproduce
1) Try to use a non default mode in the frontend CCCL configuration

#### Expected Result 

Custom connection profile is being used

#### Actual Result  

This produce a controller error reading the vserver configmap.

**Comment by trinaths** [comment]
@somejfn - Try updating to CIS 2.x and using agent AS3. This would help with ingressLink for nginx usecase.

**Comment by kxs-jnadeau** [comment]
HI @trinaths,   Im affraid Ingresslink is not yet an option to me as our BigIP is on a 12.x release.   But since I need to have the discussion with the team managing the F5 devices,  can we confirm this can only be done under AS3 ?   Would using a service type loadbalancer  a) require AS3 and b) have a configurable tcp profile ?  thank you !

**Comment by mdditt2000** [comment]
@kxs-jnadeau you can use AS3.26 with CIS

Which TMOS versions does AS3 support?

AS3 supports TMOS versions 13.x and later (AS3 3.26 was the last version to support 12.1.x).

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html

Please can you invite me to that discussion with the team managing the F5 devices. I want to talk to them about upgrading to 16.1 and using AS3. 

- Currently we cannot add a policy to service type load balancer. This enhancement is coming

**Comment by kxs-jnadeau** [comment]
We're good to close this one.   We'll setup AS3 once the upgrade to a new TMOS is done.  Thanks for the help !

**Comment by mdditt2000** [comment]
@kxs-jnadeau good choice to update TMOS. I will close this issue.
