### ISSUE TITLE
CIS 2.7.1 Error Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected

### ISSUE THREAD

**Issue by tomaszmzyk** [F5Networks/k8s-bigip-ctlr#2216]
CIS Version : 2.7.1

BIGIP Version: Big IP 15.1.5
AS3 Version: 3.32
Agent Mode: AS3
Orchestration: Openshift
Orchestration Version: 4.8.18
Pool Mode: Cluster
Additional Setup details: OpenshiftSDN

Hi
When we run new version of CIS 2.7.1 we are observing in log following errors:

2022/02/02 12:48:33 [ERROR] [AS3] Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare/EXAMPLE1 Referrer:192.168.0.32 Sender:192.168.0.32 referer:192.168.0.32 restOperationId:2.50609612e+08]
2022/02/02 12:50:53 [ERROR] [AS3] Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare/EXAMPLE2 Referrer:192.168.0.32 Sender:192.168.0.32 referer:192.168.0.32 restOperationId:2.50620675e+08]
2022/02/02 12:52:22 [ERROR] [AS3] Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare/EXAMPLE3 Referrer:192.168.0.32 Sender:192.168.0.32 referer:192.168.0.32 restOperationId:2.5062603e+08]

What that means and how this error impact to sync data between F5 and OCSP ?
Thanks for information in advance.

Regards

**Comment by mdditt2000** [comment]
@tomaszmzyk where you upgrading CIS? CIS is having authentication issues connecting to the AS3 endpoint on BIG-IP

**Comment by tomaszmzyk** [comment]
Hi
I little don't understand a question thta you wrote. 
Could you please ask more clarify ?

I dodn't see this error on earlier version that we use. Tommotow morning I will check credentials for user that we create for CIS.
Regards

**Comment by mdditt2000** [comment]
@tomaszmzyk AS3 requires user with administrator role

Use the administrator role
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/best-practices.html

CIS uses the AS3 API to configure BIG-IP

**Comment by tomaszmzyk** [comment]
Hi
We have configured, without this nothing work.
In logs I have:
2022/02/03 05:55:06 [INFO] Text: '{"kind":"tm:auth:partition:partitionstate","name":"EXAMPLE","fullPath":"EXAMPLE","generation":1,"selfLink":"https://localhost/mgmt/tm/auth/partition/EXAMPLE?ver=15.1.4","defaultRouteDomain":0,"description":"Updated by AS3 at Fri, 24 Sep 2021 12:46:04 GMT"}'
2022/02/03 05:56:06 [DEBUG] [2022-02-03 05:56:06,887 icontrol.session DEBUG] RESPONSE::STATUS: 200 Content-Type: application/json; charset=UTF-8 Content-Encoding: None

Occasionally I see error as described above, in version CIS 2.1.1 this log I never find.
Regards

**Comment by tomaszmzyk** [comment]
Hi
I checked when this happen.
I prepare some test, and on my testing deployment I scale up pods from 2 to for:
$ date;oc scale deployment openshift-example-php --replicas=4 -n bsk-openshift
Thu Feb  3 07:46:03 CET 2022
deployment.apps/openshift-example-php scaled

Pods nicely runing:
```
NAME                                    READY   STATUS    RESTARTS   AGE
openshift-example-php-5cb954f45-2wlmn   1/1     Running   0          8s
openshift-example-php-5cb954f45-2xjqs   1/1     Running   0          8s
openshift-example-php-5cb954f45-74mkz   1/1     Running   3          6d11h
openshift-example-php-5cb954f45-nrg8m   1/1     Running   2          22h
```

In CIS log:
`2022/02/03 06:47:34 [ERROR] [AS3] Raw response from Big-IP: map[code:401 kind::resterrorresponse message:Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare/EXAMPLE-PHP Referrer:192.168.0.32 Sender:192.168.0.32 referer:192.168.0.32 restOperationId:2.51896334e+08]`


From restjavad log:
`Feb  3 07:47:25 f5-o66-dev-01.pl.ing-ad notice mcpd[4351]: 01070417:5: AUDIT - client tmsh, tmsh-pid-26489, user OCSP_ADMIN - transaction #389297100-3 - object 0 - create { class_value_item { class_value_item_name "/Common/____appsvcs_declaration-1643870844838" class_value_item_value 0 class_value_item_data "date^2022-02-03T06:47:24.838Z|id^urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d|tenants^...EXAMPLE-PHP...|blocks^1" } } [Status=Command OK]`

And there is a lot of logs that every have status [Status=Command OK]

But pool not synchronized:
```
ltm pool /EXAMPLE_PHP/APP_EXAMPLE_PHP/POOL_EXAMPLE {
    members {
        /EXAMPLE_PHP/172.133.4.40:8080 {
            address 172.133.4.40
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
        /EXAMPLE-PHP/172.134.2.12:8080 {
            address 172.134.2.12
            session monitor-enabled
            state up
            metadata {
                source {
                    value declaration
                }
            }
        }
    }
    min-active-members 1
    monitor min 1 of { http }
    partition EXAMPLE_PHP
}
```
Regards

**Comment by trinaths** [comment]
@tomaszmzyk - Please configure CIS with valid BIGIP Admin credentials.
