### ISSUE TITLE
VirtualServer Status not reported correctly when using hostGroup

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2220]
#### Setup Details
 CIS Version : 2.7.1
 Build: f5networks/k8s-bigip-ctlr:2.7.1       
 BIGIP Version: Big IP 15.1    
 AS3 Version: 3.33   
 Agent Mode: AS3/      
 Orchestration: K8S/     
 Orchestration Version: 1.20
 Pool Mode: Cluster/     
 Additional Setup details: Calico

#### Description  
When deploying multiple virtualServers with the same HostGroup only one will have the Status OK and IPAMVSADDRESS set to None.

If you deploy the same configuration but one by one, then it works fine

#### Steps To Reproduce
1) Create 3 VS CRDS on the same manifest and apply it.
![image](https://user-images.githubusercontent.com/11005568/152472502-090a4d32-2efc-493a-ac1d-99048803f6f5.png)
Please deploy the uploaded file no-working.yml to reproduce the problem

2)if you create 3 manifests and apply them few seconds apart, then the result is as expected.
![image](https://user-images.githubusercontent.com/11005568/152472656-71225fe5-4674-43d5-a6e2-7ee8def1d1e0.png)
Please deploy the uploaded files vs-1.yml, vs-2.yml and vs-3.yml (few seconds apart) to verify it is working 

[vs-2.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/8000111/vs-2.yml.txt)
[vs-1.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/8000112/vs-1.yml.txt)
[vs-3.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/8000146/vs-3.yml.txt)
[not-working.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/8000151/not-working.yml.txt)

**Comment by trinaths** [comment]
Created [CONTCNTR-3147] for internal tracking.
