### ISSUE TITLE
ERROR on CIS logs when deleting multiple VS CRD

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2221]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
 When deleting multiple VS you get the following ERROR on the CIS logs 
([ERROR] VirtualServer Not Found: default/xxxxxxx, failed to update VS status)

#### Steps To Reproduce
1)Create multiple VS and then delete them all "kubectl delete vs --all"

![image](https://user-images.githubusercontent.com/11005568/152474130-3ab6d71d-8282-4eb8-b5c3-d30f4936baeb.png)

2022/02/04 04:51:53 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:cis --- message: success
2022/02/04 04:51:53 [ERROR] VirtualServer Not Found: default/tea-virtual-server, failed to update VS status
2022/02/04 04:51:53 [ERROR] VirtualServer Not Found: default/test-virtual-server, failed to update VS status

**Comment by trinaths** [comment]
Created [CONTCNTR-3148] for internal tracking.
