### ISSUE TITLE
feature request: define persistence profile using Policy CRD

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2223]
#### Title
Define persistence profile for a virtual server on BIG-IP via the Policy CRD

#### Description
This is a real-world customer request.

Request to extend the VS or TS CRD to include a persistence profile. This could be in a Policy CRD, rather than a VS or TS CRD directly.

#### Actual Problem
By default a VS CRD will create a VIP on BIG-IP with "cookie" persistence. In some cases we want NO persistence or something else, like SrcIP.

#### Solution Proposed
Allow for defining persistence profile via CRD's.

#### Alternatives
The alternative today is configmap with AS3 as a workaround.

**Comment by skenderidis** [comment]
I have the same request from multiple customers

**Comment by quynhlab** [comment]
This feature was requested at #1768

**Comment by trinaths** [comment]
closing this issue. Duplicate of https://github.com/F5Networks/k8s-bigip-ctlr/issues/1768
