### ISSUE TITLE
Expose metrics of the time which CIS finish configuration of BIGIP to Prometheus 

### ISSUE THREAD

**Issue by kkfinkkfin** [F5Networks/k8s-bigip-ctlr#2256]
#### Title
Expose metrics of the time which CIS finish configuration of BIGIP to Prometheus 

#### Description
We want to know the time difference when CIS monitors the change of resource object to the BIGIP generation configuration, and expect to be able to pull this metrics data through prometheus. 

#### Actual Problem
When the scale of cluster resource data is relatively large, CIS sometimes takes a long time to update the BIGIP.

#### Solution Proposed
It is expected to be able to pull in precise configuration times via prometheus for alerting.

#### Alternatives
It is possible to calculate the update time of every VS config and every POD related objects in the program and output each updated cost time. Then we can use PromSQL to calculate the average time, output the top 10 maximum time consumption, etc

**Comment by trinaths** [comment]
Created [CONTCNTR-3177] for internal tracking.

**Comment by olvandeng** [comment]
PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2265/files is to address the the requirement, talking more for details, and working with HYD team to review the code. Thanks.

**Comment by trinaths** [comment]
@olvandeng please link this github ID and fill the details for the PR summary.

**Comment by trinaths** [comment]
Closing as no further discussion.
