### ISSUE TITLE
Out of date config examples

### ISSUE THREAD

**Issue by bab5470** [F5Networks/k8s-bigip-ctlr#2268]
This page
https://clouddocs.f5.com/containers/latest/userguide/kubernetes/

Has a link at the bottom to:
Examples Repository¶
View more examples on GitHub.

When you click on the link it takes you here: 
https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/

When you look at the examples in this directory. For example (https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/ingress/single-service-ingress.yaml)

ou'll see that they reference:
`apiVersion: extensions/v1beta1`

Which is no longer valid. But beyond that there are some other issues with the examples which make them not functional.

**Comment by trinaths** [comment]
Created [CONTCNTR-3791] for internal tracking.

**Comment by Th0masL** [comment]
I can also confirm that the official/latest version of the Helm Chart for the `f5-bigip-ingress`.

The Helm Chart version is 0.0.4 and as last updated on July 2021, and is not compatible with EKS 1.22+.

The breaking changes are mostly around the depreciation of the `extensions/v1beta1` and `networking.k8s.io/v1beta1` API versions of the Ingress.

Some part of the documentation on the website are up-to-date and are using the right examples, but some other example files on the website are still using the old syntax, or are using a mix of both the old syntax and new syntax.

In term of the Helm Chart in this repository, he following files/lines are not up-to-date and would need to be updated to be become compatible with EKS 1.22+ :
- The apiVersion `extensions/v1beta1` is now deprecated:
  - [templates/f5-bigip-ingress.yaml](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ingress/templates/f5-bigip-ingress.yaml#L1)
- The backend definition syntax in the following files:
  - [templates/_helpers.tpl](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ingress/templates/_helpers.tpl#L32-L36)
  - [values.yaml](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ingress/values.yaml#L34-L36)
  
More details [here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)

**Comment by trinaths** [comment]
Closing as completed.
