### ISSUE TITLE
Endpoint without an associated service causes CIS to log every second

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2284]
#### Setup Details
 CIS Version : 2.7.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1     
 AS3 Version: 3.34      
 Agent Mode: AS3       
 Orchestration: K8S, deployed by Rancher    
 Pool Mode: Nodeport      
 Additional Setup details: Rancher, CNI is Calico, cust using NodePort

#### Description  
We have an endpoint on its own without an associated service. This results in the following log message repeating **once every second** as the CIS tries repeatedly to process the endpoint.

````
Enqueuing Endpoints: &Endpoints{ObjectMeta:{cloud-controller-manager kube-system ….}}
Processing Key: &{kube-system Endpoints cloud-controller-manager 0x…. false}
  ConfigWriter (0x0…) writing section name gtm
Service kube-system/cloud-controller-manager does not exist
  ConfigWriter (0x0…) successfully wrote section (gtm)
Wrote gtm config section: map[]
[AS3] No Change in the Configuration
````

#### Steps To Reproduce
1) Create an endpoint without a service. In our case, this was created by vSphere cloud controller
2) Install CIS watching all namespaces with Debug loggin
3) Look at CIS pod logs.

#### Expected Result 
Clean logs

#### Actual Result  
Logs are too filled with the above message to make finding anything else practical.

#### Observations (if any)
It would be nice if we had a way to ignore a namespace, instead of only including a specific namespace.

**Comment by trinaths** [comment]
This must be an RFE. Since CIS is processing all the native resources in k8s. CIS processing an endpoint without a service is a new usecase. @mikeoleary please share the manifests to try at our end. EP, Deployment and CIS config.

**Comment by mikeoleary** [comment]
@trinaths  - thanks. To be clear this is a bug report from a customer, not a feature request. It actually seems to prevent the controller from further configuration as it gets stuck trying to process the endpoint.

Reproduction:
1.	Create an Endpoint without a spec. 
apiVersion: v1
kind: Endpoints
metadata:
  name: example
  namespace: example

2.	Notice the constant logs and then create a couple TransportServers. In my case it won’t process them all while this endpoint exists

I can’t control this endpoint unfortunately. It is created for leader election in vSphere.

**Comment by mdditt2000** [comment]
This could be related to https://github.com/F5Networks/k8s-bigip-ctlr/issues/2293
Creating Jira CONTCNTR-3215 for PM tracking and planning

**Comment by mikeoleary** [comment]
@arzzon thanks. I will ask customer to share his environment details so we can reproduce

**Comment by mikeoleary** [comment]
@arzzon sorry but we can close this. Customer reports that they are now unable to reproduce also, and they are running the latest version. Previously they were unable to get around it. If it comes up again in any other scenario/customer I’ll reopen the issue.

**Comment by arzzon** [comment]
Thanks @mikeoleary for the update.
