### ISSUE TITLE
same-ip:80 and same-ip:443 via CRDs - deployment not working (FQDN gets overwritten)

### ISSUE THREAD

**Issue by de1chk1nd** [F5Networks/k8s-bigip-ctlr#2297]
#### Setup Details
 CIS Version : 2.7.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.2.1      
 AS3 Version: 3.30.0 build 5      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster
 Additional Setup details: amazon eks

#### Description  
I want to create one virtual service via bigip on same-ip:80 and another on same-ip:443. both need different fqdns to be routed.

I had some struggle to get it working on the first stage (httpTraffic: allow was required; although my expectation was to have it disabled).

Posting the declaration below results in two VS:

crd_10_1_10_202_80
crd_10_1_10_202_443

Unfortunately the LTM policies get mixed up - beginning on the "rules" layer. Please see below:

crd_10_1_10_202_80
policy	: /kubernetes/Shared/crd_10_1_10_202_80_nginx_dashboard_https_k8s_lab_bigip_policy
rules	: vs_nginx_dashboard_https_k8s_lab_bigip_echo_app_80_default
fqdn	: nginx-dashboard-https.k8s.lab.bigip

crd_10_1_10_202_443
policy	: /kubernetes/Shared/crd_10_1_10_202_443_nginx_dashboard_https_k8s_lab_bigip_policy
rules	: vs_nginx_dashboard_https_k8s_lab_bigip_echo_app_80_default
FQDN	: nginx-dashboard-https.k8s.lab.bigip

# # # # #

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx-dashboard
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.202"
  host: nginx-dashboard-http.k8s.lab.bigip
  #hostGroup: "test"
  pools:
  - path: /
    service: echo-app
    servicePort: 80
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx-dashboard-ssl
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.202"
  host: nginx-dashboard-https.k8s.lab.bigip
  #hostGroup: "test"
  httpTraffic: allow
  tlsProfileName: edge-tls
  pools:
  - path: /
    service: echo-app
    servicePort: 443
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10

#### Steps To Reproduce
post declarations as above

#### Expected Result 
crd_10_1_10_202_80
Routing for http FQDN

crd_10_1_10_202_443
Routing for https FQDN

#### Actual Result  
crd_10_1_10_202_80
policy	: /kubernetes/Shared/crd_10_1_10_202_80_nginx_dashboard_https_k8s_lab_bigip_policy
rules	: vs_nginx_dashboard_https_k8s_lab_bigip_echo_app_80_default
fqdn	: nginx-dashboard-https.k8s.lab.bigip

crd_10_1_10_202_443
policy	: /kubernetes/Shared/crd_10_1_10_202_443_nginx_dashboard_https_k8s_lab_bigip_policy
rules	: vs_nginx_dashboard_https_k8s_lab_bigip_echo_app_80_default
FQDN	: nginx-dashboard-https.k8s.lab.bigip

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by mdditt2000** [comment]
When using **#hostGroup:** CIS adds only **one VirtualServer on BIG-IP** as shown in the link https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.8/github/2251#readme

CIS uses http routing policies for the backend. 

Please add **httpTraffic: redirect** to your **name: nginx-dashboard-ssl** VS. Example link https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.8/github/2286/split/working/k8s-dashboard.yaml

**Comment by trinaths** [comment]
@de1chk1nd Please share your findings based on above suggestion.

**Comment by trinaths** [comment]
Suggested to add httpTraffic: redirect to your name: nginx-dashboard-ssl VS. Example link https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.8/github/2286/split/working/k8s-dashboard.yaml

Closing this issue.
