### ISSUE TITLE
persistenceProfile doesn't work

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2305]
Seems current Virtual has a option for set persistenceProfile, however it doesn't work, The cookie persistence be hard coded, the VirtualServer can not use source_addr or other BIG-IP's persistenceProfile.

The following setting in VirtualServer CRD doesn't work

~~~
persistenceProfile: "source-addr"
~~~

**Comment by mdditt2000** [comment]
@kylinsoong please review https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.8/crd-enhancements

Video: https://youtu.be/brlNGGJ0sw0

Please use the following pre-view CIS 2.8 image from https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.8/multi-deployment-nginx/k8s/cis/cis-deployment/f5-bigip-ctlr-deployment.yaml

CIS 2.8 released next week.

**Comment by mdditt2000** [comment]
@kylinsoong please subscribe to https://www.youtube.com/c/MarkDittmer/videos

**Comment by kylinsoong** [comment]
Thanks @mdditt2000, I am not find the 2.8.0 in my test.
