### ISSUE TITLE
CRD can not define the RUlE, but only can reference a exist RULE in BIG-IP

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2306]
Current CIS CRD can only reference a exist RULE in BIG-IP, like the below setting in VirtualServer worked

~~~
iRules: ["/Common/RULE01", "/Common/RULE02"]
~~~

however, the Developer should add the RULE01 and RULE02 to BIG-IP, before create CRD VirtualServer, cloud CIS support either define Rule directly, or add another CRD for RULE?

Seems CRD do similar work with AS3, in AS3 the iRule definition syntax like:

~~~
"test001_app-v1-svc_irules": {
              "class": "iRule",
              "iRule": "when HTTP_REQUEST {\n  if {[HTTP::cookie exists \"Canary\"] and [HTTP::cookie value \"Canary\"] equals \"true\"} {\n    pool /test001/test001_app-v2-svc_svc/test001_app-v2-svc_80_pool \n  } else {\n    pool /test001/test001_app-v1-svc_svc/test001_app-v1-svc_80_pool \n  }\n}"
            }
~~~

**Comment by mdditt2000** [comment]
@kylinsoong I believe iRule are created and owned by the "infrastructure providers"  personas who manages BIG-IP. Application developers who creates the CRDs should just reference a CRD policy which contains the referenced iRule "/Common/RULE01"

CIS does CRD schema validation but not iRule Validation. My biggest concern is invalid iRules causing the CRD to fail, where BIG-IP has a iRule validation tool etc built in. 

Please can we chat about this RFE at the next Interlock meeting

**Comment by mdditt2000** [comment]
Please use the iRule validation tool on BIG-IP to validate iRule before adding on CIS. CIS validating iRule is out of scope at this time.
