### ISSUE TITLE
Only resources are deleted with ARPs left until next C(create) or U(update).

### ISSUE THREAD

**Issue by zongzw** [F5Networks/k8s-bigip-ctlr#2308]
#### Setup Details
 CIS Version : master      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: any
 AS3 Version: any      
 Agent Mode: AS3       
 Orchestration: K8S    
 Orchestration Version:       
 Pool Mode: Cluster      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
 
When user trigger the resource deletion, the deletion succeeds within function `processTenantDeletion`, but
`am.as3ActiveConfig.updateConfig(tempAS3Config)` will not be executed because the following condition is false:

```
	for partition, tenant := range tempAS3Config.tenantMap {
		if !reflect.DeepEqual(am.as3ActiveConfig.tenantMap[partition], tenant)
```
Thus, in `am.updateNetworkingConfig()`, the `SendARPEntries` will not get the latest updated `allPoolMembers`.
The ARPs on BIG-IP will be left there with no deletion.

This issue is introduced by #2170 

#### Steps To Reproduce
1) Create 10 groups of resources(configmap/service/deployment)
2) Delete 2 of them.
3) Observe on BIG-IP the ARP are left there.

**Comment by mdditt2000** [comment]
@zongzw AS3 cannot delete an ARP request when removing a Node. CIS will clean up after a update. Are you seeing issues when observing on BIG-IP the ARP are left there?

**Comment by zongzw** [comment]
That's not the case I mentioned in this issue.

Are you talking about this issue?
#2168 `[ERROR] [VxLAN] Vxlan manager could not get VtepMac for 10.42.1.10's node.`

**Comment by mdditt2000** [comment]
Dev looked into this issue

**Analysis**

https://github.com/F5Networks/k8s-bigip-ctlr/issues/2308 **is still an issue** and **needs to be resolved**. 

With **filter-tenants**, ARP recreation is still going on. 

JFYI, without filter-tenants, As3-configMap (and other combinations) will **work fine with 2.8.0**. 

@zongzw is your issue specific to filter-tenants?

**Comment by zongzw** [comment]
@mdditt2000 thanks for proceeding it.

without filter-tenants case, there should be no such problem from my perspective by analyzing the code call stack(because the issue happens in `processFilterTenants` only). 

What's more, without filter-tenants case, there is performance issue, I didn't use it any more, suppose users will not, neither.

**Comment by walterk82** [comment]
I would like to add that we are looking to use CIS with only with filter-tenants option as we have 1,000s of pods that need to be pushed to BIG-IP.  This mode is the only way that AS3 will be performant.

**Comment by trinaths** [comment]
Created [CONTCNTR-3245] for internal tracking.

**Comment by vklohiya** [comment]
Closing the issue as already fixed.
