### ISSUE TITLE
F5 CIS not update endpoint to pool member of F5 BIGIP when use endpoint outside k8s

### ISSUE THREAD

**Issue by quynhlab** [F5Networks/k8s-bigip-ctlr#2320]
#### Setup Details
 CIS Version : 2.8      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.2      
 AS3 Version: 3.30.0     
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version: v1.19       
 Pool Mode: Cluster      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  

F5 CIS not update endpoint to pool member of F5 BIGIP when use endpoint outside k8s

#### Steps To Reproduce
1) Create custom endpoint outside k8s

![image](https://user-images.githubusercontent.com/80056481/159758975-722228a1-ffe2-4953-bed3-b54c6511a5cb.png)

2) Create service for endpoint

![image](https://user-images.githubusercontent.com/80056481/159759165-d268fb86-cab9-4dbf-888b-2677ad382745.png)

3) Create Transport Server 

![image](https://user-images.githubusercontent.com/80056481/159759269-03bc9f12-0f9d-4dfc-a0bf-f1bcc8ab3e77.png)

#### Expected Result 

F5 CIS update endpoint to F5 BIGIP

#### Actual Result  
Log F5 CIS post AS3 success

![image](https://user-images.githubusercontent.com/80056481/159760813-6b74610e-4f26-4b13-8bff-a44dcb71d164.png)

Virtual Server setting is correct

![image](https://user-images.githubusercontent.com/80056481/159760515-ef966e91-cb47-4a93-8916-09ca57ce64a0.png)

Health check setting is correct

But F5 CIS not update endpoint to pool member of F5 BIGIP

![image](https://user-images.githubusercontent.com/80056481/159759519-0726f369-d29d-4f18-bebe-27b0a369ab50.png)

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by ThoanNV** [comment]
I have this problem too, Pls help me

**Comment by trinaths** [comment]
@quynhlab - This issue working in cis 2.7 and below versions ? Since you are manually creating the endpoints. Is your usecase tied to k8s headless services ?

**Comment by quynhlab** [comment]
> 

@trinaths Thank for your reply.
This issue working in cis 2.7 and below versions ? seem it's not working
Is your usecase tied to k8s headless services ? No
My usecase is use f5 cis crd to automation declare config VS and TS to F5 BIGIP and pool member of F5 BIGIP located outside k8s (monolithic architecture)
This will make it possible for us to apply both monolithic architecture and microservices architecture.

**Comment by trinaths** [comment]
@quynhlab - Since this usecase is to update the endpoint outside of k8s, IMO this must be an RFE rather than a BUG.

**Comment by quynhlab** [comment]
> @quynhlab - Since this usecase is to update the endpoint outside of k8s, IMO this must be an RFE rather than a BUG.

You're right, but nginx ingress controller can update endpoint outside of k8s.

**Comment by trinaths** [comment]
Created [CONTCNTR-3248] for internal tracking.

**Comment by trinaths** [comment]
@quynhlab - Can you try set CIS config param `--use-node-internal=false`

**Comment by quynhlab** [comment]
Let’s me try. I’ll update result to you later.
Thank you for your suggest.

**Comment by quynhlab** [comment]
> 

Hi @trinaths 
Sorry for reply late.
I have tried with args --use-node-internal=false in CIS deployment.
CIS running well but issues still happening. No member in pool on F5 BIGIP.

**Comment by quynhlab** [comment]
> > 
> 
> Hi @trinaths Sorry for reply late. I have tried with args --use-node-internal=false in CIS deployment. CIS running well but issues still happening. No member in pool on F5 BIGIP.

hi @trinaths 
So does your team have a plan to do this?

Best and regards,

**Comment by quynhlab** [comment]
@mdditt2000  thank for your reply. 
Yes, AS3 declaration based on a specific tenant is working when call via REST API.
I think CIS will be more powerful if it can manage configuration, update configuration to many BIGIP devices with endpoint outside K8s.
Because kind VirtualServer and TransportServer format is clearly and simple for configuration. We can provide customer self-service.

**Comment by mdditt2000** [comment]
Hi @quynhlab 
 
Thanks for reaching out, from our side we haven’t done any testing or validation with endpoints outside of K8S.  Adding to that, our PE team resources are completely tied down with current projects. We would not have the bandwidth to provide support for endpoints outside of K8S.
 
Sorry we are not able to provide the support you are requesting at this moment. At this time i would recommend using AS3 to create the configured required to a unique tenant. 

Closing this issue. Thanks Mark
