### ISSUE TITLE
Supporting Prometheus service in CRDs (similar to 2280)

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2325]
Similar to the Bug 2280, Prometheus services cannot be published through CRDs. They are part of the core services and CIS (CRD mode) doesn't discover any services. 
Please remove Prometheus-k8s as part of the core services as done with Grafana (see the code below). With CIS Ingress services it works fine.

![image](https://user-images.githubusercontent.com/11005568/160329603-8e1de3fd-88cc-4e22-8fa3-1234bf27f3aa.png)

**Comment by trinaths** [comment]
Created [CONTCNTR-3236] for internal tracking.

**Comment by mdditt2000** [comment]
Here is the fix for Grafana https://github.com/F5Networks/k8s-bigip-ctlr/pull/2280 - Same needs to be done for Prometheus services

**Comment by mdditt2000** [comment]
Currently in CIS 2.9.1 SP2.
