### ISSUE TITLE
cis2.7.1 config delete issue

### ISSUE THREAD

**Issue by jinjia812** [F5Networks/k8s-bigip-ctlr#2332]
#### Setup Details
CIS Version : 2.7.1
Build: f5networks/k8s-bigip-ctlr:2.7.1
BIGIP Version: Big IP 15.1.3.1
AS3 Version: 3.28
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.18.20
Pool Mode: Cluster
Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
when using the wrong configmap (means the schema is not ok )
cis delete all configuration in bigip  

#### Steps To Reproduce
1) using the configmap which the schema is error, note than missing "[] in  "members" "
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3-1
  namespace: f5-test003
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.28.0",
        "remark": "HTTP application",
        "test003": {
          "class": "Tenant",
          "test003": {
            "class": "Application",
            "template": "generic",
            "pool3": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": 
              {
                "servicePort": 8080,
                "serverAddresses": [ ],
                "shareNodes": true
              }
            },
            "tcp-611": {
              "class": "TCP_Profile",
              "idleTimeout": 611
            },
            "tcp-888": {
              "class": "TCP_Profile",
              "idleTimeout": 888
            },            
            "app_svc_vip": {
              "class": "Service_Address",
              "virtualAddress": "172.16.142.114",
              "arpEnabled": false
            },        
            "vs-L4": {
              "class": "Service_L4",
              "virtualAddresses": [{ "use": "app_svc_vip" }],
              "virtualPort": 83,
              "pool": "pool3"
            }
          }
        }
      }
    }
~~~
2)
cis logs
2022/04/01 01:12:47 [ERROR] [AS3] Template is not valid. see errors
2022/04/01 01:12:47 [ERROR] - (root): Must validate one and only one schema (oneOf)

2022/04/01 01:12:47 [ERROR] - declaration: Must validate "then" as "if" was valid

2022/04/01 01:12:47 [ERROR] - declaration.members: Invalid type. Expected: array, given: object

2022/04/01 01:12:47 [ERROR] - declaration: Must validate all the schemas (allOf)

2022/04/01 01:12:47 [ERROR] [AS3][Configmap] Error validating AS3 template
2022/04/01 01:12:47 [ERROR] [AS3][Configmap] Error in processing the ConfigMap: f5-test003/app-as3-1

~~~~~~
bigip audit logs 
pr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207613-2 - object 0 - modify { value_list { value_list_name "/Common/__appsvcs_update" value_list_config_source 0 } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207613-3 - object 0 - obj_delete { class_string_item { class_string_item_name "/Common/__appsvcs_update" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-3 - object 0 - modify { auth_partition { auth_partition_name "test003" auth_partition_description "Updated by AS3 at Fri, 01 Apr 2022 02:21:44 GMT" auth_partition_config_source 0 } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-5 - object 0 - obj_delete { pool { pool_name "/test003/test003/pool3" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-7 - object 0 - obj_delete { profile_tcp { profile_tcp_name "/test003/test003/tcp-611" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-9 - object 0 - obj_delete { profile_tcp { profile_tcp_name "/test003/test003/tcp-888" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-11 - object 0 - obj_delete { virtual_server { virtual_server_name "/test003/test003/vs-L4" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-13 - object 0 - obj_delete { virtual_address { virtual_address_name "/test003/app_svc_vip" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-15 - object 0 - obj_delete { node_address { node_address_name "/Common/10.42.8.137" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-17 - object 0 - modify { auth_partition { auth_partition_name "Common" auth_partition_description "Updated by AS3 at Fri, 01 Apr 2022 02:21:44 GMT" auth_partition_config_source 0 } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207614-19 - object 0 - obj_delete { node_address { node_address_name "/Common/10.42.8.138" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207620-2 - object 0 - obj_delete { folder { folder_name "/test003/test003" } } [Status=Command OK]
Apr  1 10:21:44 v15-b.f5.com notice mcpd[6661]: 01070417:5: AUDIT - client tmsh, tmsh-pid-17384, user admin - transaction #1207625-2 - object 0 - obj_delete { folder { folder_name "/test003" } } [Status=Command OK]

3) all the configuration declared in configmaps , in bigip is missing.

#### Expected Result 
cis can produce the error log, but the configuration in bigip will exist

#### Actual Result  
bigip configuration is missing

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment]
@jinjia812  we need to post valid AS3 declarations. User needs to validate the JSON via the AS3 schema before posting to BIG-IP. Regardless of the automation. Suggest validate AS3 JSON to resolve bad formatting. CIS shouldn’t have to validate bad AS3 JSON/configuration when we have good tools like VScode todo the job!

Closing this issue.
