### ISSUE TITLE
Documentation for VirtualServer CRD is incomplete

### ISSUE THREAD

**Issue by ajsq** [F5Networks/k8s-bigip-ctlr#2355]
#### Setup Details
n/a

#### Description  
The documentation page for the VirtualServer CRD:

https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html

does not cover all of the properties (such as `iRules`) documented in the linked OpenAPI document:

https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

#### Steps To Reproduce
n/a

#### Expected Result 
n/a

#### Actual Result  
n/a

#### Diagnostic Information
n/a

#### Observations (if any)
n/a

**Comment by trinaths** [comment]
Created [CONTCNTR-3283] for internal tracking.

**Comment by trinaths** [comment]
Document updated.
