### ISSUE TITLE
Openshift documentation issue - bigip-login vs f5-bigip-ctlr-login

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/k8s-bigip-ctlr#2360]
#### Title
Documentation enhancement: user credentials are different between command and yaml example.

#### Description
Confusion in the docs:

https://clouddocs.f5.com/containers/latest/userguide/openshift/#installing-cis-using-helm-charts

Step 1 shows creating a secret called `bigip-login`. However, Step 3 appears to be referencing this secret as `f5-bigip-ctlr-login`

Also, line 7 of the yaml explaining Kubernetes secrets is a dead link: http://clouddocs.f5.com/containers/latest/kubernetes/kctlr-secrets.html#secret-bigip-login

#### Actual Problem
If you follow this you won't have a credential with rights, and the deployment will be a failure.

#### Solution Proposed
Make the yaml example match the step 1 created account, fix dead links

@mdditt2000

**Comment by trinaths** [comment]
Document updated.
