### ISSUE TITLE
Support "Alias Service Port" for monitoring inside virtualservers.cis.f5.com

### ISSUE THREAD

**Issue by wheestermans31** [F5Networks/k8s-bigip-ctlr#2384]
#### Title
Support "Alias Service Port" for monitoring inside virtualservers.cis.f5.com

#### Description
The current virtualservers.cis.f5.comcrd has support for monitoring. But we need to have some addional support to be able to set the "Alias Service Port".

![alias-port](https://user-images.githubusercontent.com/41023907/166215251-e1a10d27-e11e-4722-891b-87304335335c.jpg)
![curent-supported-monitorING](https://user-images.githubusercontent.com/41023907/166215255-1e3908dd-bf48-4799-a795-a2947656cd78.jpg)

**Comment by mdditt2000** [comment]
Why
https://community.f5.com/t5/technical-forum/what-is-a-function-of-the-alias-service-port-setting-under/td-p/50231

Alias Service Port/Address is currently not available in the AS3 API 
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3.13/refguide/schema-reference.html?highlight=alias#monitor

Checking on the AS3 side, prerequisite for CIS

**Comment by wheestermans31** [comment]
Waiting for the feedback from AS3 side.

**Comment by tkam8** [comment]
If I understand this request correctly, AS3 has this feature and it's called targetPort. 

I've made the same request here and has JIRA created:
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2361

**Comment by lavanya-f5** [comment]
@wheestermans31 Fixed in 2.10. Please verify

**Comment by wheestermans31** [comment]
I will do asap

**Comment by trinaths** [comment]
Closing as this issue is fixed.
