### ISSUE TITLE
AS3 CM and CRD coexistence

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2401]
#### Title
Need to a smooth way to migrate from AS3 configmaps to CRDs

#### Description
Allow AS3 CM and CRDs to coexist so that individual applications can migrate on their own timing. 
CIS will need to watch both AS3 CM and CRDs.

#### Actual Problem
It is difficult to cutover all AS3 CMs all at once, especially when there are different application owners

#### Solution Proposed
CIS will watch AS3 CM and CRDs simultaneously

#### Alternatives
Build separate BIG-IP cluster, deploy another CIS that "watches" CRDs, change addressing/DNS registration, then deploy CRDs in new BIG-IP cluster. This is cumbersome and prone to error if no proper DNS LB or GSLB in place to send client requests to new VIP exposed via CRDs.

#### Additional context
Today we have documentation around AS3 to CRD migration as created by below issue but still need a smoother way to do migration

https://github.com/F5Networks/k8s-bigip-ctlr/issues/1552

**Comment by trinaths** [comment]
Recommend use policy CRD and file RFE for CRD rather than configMaps. Closing this issue.
