### ISSUE TITLE
Hyphens/dashes not allowed in VirtualServer pool path

### ISSUE THREAD

**Issue by johnson-rj** [F5Networks/k8s-bigip-ctlr#2413]
#### Setup Details
 CIS Version : 2.8.1
 Build: f5networks/k8s-bigip-ctlr:latest
 BIGIP Version: Big IP 15.1.5.1
 AS3 Version: 3.32.0-4
 Agent Mode: AS3
 Orchestration: K8S
 Orchestration Version: 1.22.4
 Pool Mode: Cluster
 Additional Setup details: Azure Kubernetes Service

#### Description

The regular expression enforcing the pattern for the `spec.pools.path` in the VirtualServer CRD incorrectly prohibits hyphens in paths.

#### Steps To Reproduce
1) Install CRDs from https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
2) Deploy a VirtualServer with a path of "/hello-k8s"

#### Expected Result

A virtual server, pool, and associated configuration should be created in the F5.

#### Actual Result

```
$ kubectl apply -f sample-deployment.yaml

The VirtualServer "hello-k8s-virtual-server" is invalid: spec.pools.path: Invalid value: "/hello-k8s": spec.pools.path in body should match '^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$'
```
#### Observations (if any)

Changing the regular expression for `spec.pools.path` in the VirtualServer CRD to the following corrects the issue:

```
^\/([A-z0-9-_+]+\/)*([A-z0-9-]+\/?)*$
```

**Comment by trinaths** [comment]
Created [CONTCNTR-3378] for internal tracking.

**Comment by mdditt2000** [comment]
@johnson-rj doing CIS 2.10 planning. Please contact me at automation_toolchain_pm@f5.com so i can prioritize.
