### ISSUE TITLE
Helm chart to be self-contained

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2452]
#### Title

Helm chart to be self-contained

#### Description

At the moment the Helm chart requires additional preparations prior to run the helm command, for example:

- secret for credentials which could be passed as argument to the command line
- PodSecurityPolicies (note this is Kubernetes version dependant -- it is being deprecated & replaced)

#### Actual Problem

This would facilitate validation with third parties which require helm only automated installs

**Comment by vklohiya** [comment]
It's fixed with above PR. See the documentation for more details: https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/helm-charts/f5-bigip-ctlr.
