### ISSUE TITLE
NodePortLocal  too verbose

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2457]
#### Title

NodePortLocal  too verbose

#### Description

Using CIS 2.8.1 found that NodePortLocal is too verbose because when it finds a POD that doesn't have the Antrea annotation it generates a log with INFO priority. Not all Services will be created with the NodePortLocal annotation therefore it is expected to find PODs without the annotations. 

#### Solution Proposed

- This log message should have DEBUG priority
- Please also notice that the message has actually a %s not substituted

**Comment by trinaths** [comment]
Created [CONTCNTR-3413] for internal tracking.
