### ISSUE TITLE
CIS send empty members declaration to BIG-IP while using HubMode

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2464]
#### Setup Details
 CIS Version : 2.9
 Build: f5networks/k8s-bigip-ctlr:2.9.0    
 BIGIP Version: Big IP 15.1.5    
 AS3 Version: 3.32 
 Agent Mode: AS3   
 Orchestration: K8S 
 Orchestration Version:   1.18.17    
 Pool Mode: Cluster 

#### Description  
 
CIS send empty members declaration to BIG-IP while using HubMode, after create configmap to push the configuration to BIG-IP, check from BIG-IP UI, the members is empty. And check the current declaration also found the members are empty.

~~~
$ curl -k -s -u 'admin:admin' https://192.168.200.204/mgmt/shared/appsvcs/declare?age=0 | jq
{
  "cistest1": {
    "app-1": {
      "app-1_app_svc_pool": {
        "class": "Pool",
        "loadBalancingMode": "least-connections-member",
        "members": [
          {
            "serverAddresses": [],
            "servicePort": 8088
          }
        ],
        "monitors": [
          "tcp"
        ]
      },
      "app_svc_vs": {
        "class": "Service_HTTP",
        "persistenceMethods": [
          "cookie"
        ],
        "pool": "app-1_app_svc_pool",
        "snat": "self",
        "virtualAddresses": [
          "10.1.10.1"
        ],
        "virtualPort": 80
      },
      "class": "Application",
      "template": "generic"
    },
    "class": "Tenant",
    "defaultRouteDomain": 0
  },
...
~~~

NOTE: the serverAddresses are empty.

#### Steps To Reproduce
1) Install CIS 2.9.0
~~~
kubectl apply -f configmap-hub/install/ns.yaml
kubectl create secret generic bigip-login --from-literal=username=admin --from-literal=password=admin -n bigip-ctlr
kubectl apply -f configmap-hub/install/rbac.yaml
kubectl apply -f configmap-hub/install/cis.yaml
~~~
2) Deploy Test APP
~~~
kubectl apply -f configmap-hub/apps.yaml
~~~
3) Deliver APP
~~~
kubectl apply -f configmap-hub/cm-hub-1.yaml
~~~
4) Examine from the BIG-IP UI

NOTE: the scripts used above can be found from https://github.com/cloudadc/cis-scripts/tree/main/configmap-hub.

#### Expected Result 

The VS and members are created correctly.

#### Actual Result  

The VS are created, but no members.

**Comment by trinaths** [comment]
Created [CONTCNTR-3419] for internal tracking.

**Comment by trinaths** [comment]
Closing as completed with PR created: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2482
