### ISSUE TITLE
multiple VS with same IP address in different namespaces not working

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2469]
#### Setup Details
 CIS Version : 2.8.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.3      
 AS3 Version: 3.25
 Agent Mode: AS3
 Orchestration: K8S

#### Description  
Multiple VS's that share same IP address using hostGroup parameter will not work if they are in different namespaces.

#### Steps To Reproduce
1) create 2x namespaces
2) create a VS crd in namespace 1, with IP address and hostGroup parameter.
3) create another VS crd in namespace 2, with matching IP address, virtualServerName, and hostGroup parameter.

#### Expected Result 
A single VS is created on BIG-IP, where the HTTP policy contains rules for hostnames of both VS crd's.

#### Actual Result  
The first VS is "overwritten" by the second VS, so config of first VS crd is lost from BIG-IP.

#### Observations
Customer hit this issue, and I was able to replicate. It appears that our hostGroup parameter only works if the 2x VS crd's are in the same namespace.

Can we support a single Virtual IP address across multiple namespaces? 

Customer has multiple applications and would like to use a single IP address, but their apps will be in different namespaces. The alternative would be to manage multiple IP's which would be cumbersome for them, or to use IPAM and then DNS automation, which is more work for them.

**Comment by mdditt2000** [comment]
Jira CONTCNTR-3254 for PM/SE tracking.

**Comment by mdditt2000** [comment]
Hi @mikeoleary 
 
Our product engineering team resources are completely tied down at this moment. We would not have the bandwidth to provide support for this specific feature at this time. As per design, hostgroup feature works only in single namespace.
 
CIS PM
