### ISSUE TITLE
Use with F5 BIG-IP "Virtual Edition" or other F5 emulator?

### ISSUE THREAD

**Issue by boldandbusted** [F5Networks/k8s-bigip-ctlr#2477]
Howdy. This is more of a user question, but could spawn some documentation. ;) 

Can this K8s Controller be used against the (proprietary) F5 BIG-IP Virtual Edition https://www.f5.com/trials/big-ip-virtual-edition? It would be great to be able to make Infrastructure as Code against that before touching actual hardware.

If it can be used, is there any documentation or tutorials forthcoming on how to use the Virtual Edition with, say, Minikube or Kind? Apologies in advance if I missed the docs where this was covered. Thanks in advance! :)

**Comment by mdditt2000** [comment]
@boldandbusted good morning. The F5 K8S controller for BIG-IP doesn't differentiate on the flavor of BIG-IP. Can be deployed as hardware or Virtual Appliances. The F5 K8S controller for BIG-IP falls under the license of the BIG-IP itself. 

 F5 K8S controller for BIG-IP provides automation ingress for the resources created in K8S. Can i get some information with regards to your use-case. You can also email me at automation_toolchain_pm@f5.com

1) What KS8 environment are you using?
2) How would you like to Ingress traffic? What K8S resources do you want to use? "CRDs, Ingress, ConfigMap," etc

Thanks Mark

**Comment by boldandbusted** [comment]
Thank you for your reply, @mdditt2000 ! :) This is great - opens up possibilities for integrating F5's products into a "lights-out" CI/CD testing scenario, as well as gaining confidence in configuration changes without impacts to services.

I'm an infrastructure engineer/consultant that's trying to get ahead of the curve, and start to get a 'feel' for how I might make an ephemeral environment for evaluation, spitballing ideas, making horrible mistakes (out of anyone's view ;) ), testing, demos, and pre-flights on production changes. I know I might have F5 in my automation and K8s future, so I wanted to see if an ephemeral environment was feasible. It's a learning exercise, but I may also be assisting peers with their configurations, and it's nice to have a way to replicate 'bugs' in the deployment in a locally-deployable lab (which is often the first step towards testing pipelines).

For this sort of testing, it would be 'vanilla' Kubernetes, probably via Minikube or Kind, using ContainerD, and I'd prefer LinkerD (but it seems Calico is better supported in the docs today?). I *might* be using ArgoCD for deployment, and it might also be a good excuse for me to start playing with Crossplane, as well (https://crossplane.io/). I'd use Ingress resources here today, but I can't say what my future clients might choose. It might be more useful to show what popular configurations are currently *not* supported by this controller. :)

Also, one more question: At some point will this project be added to https://artifacthub.io/ ? I see other non-official F5 projects represented there, but not F5 itself. :)

Thank you again for the reply! 💯

**Comment by vincentmli** [comment]
@boldandbusted @petersmichaelg just fyi, when you consider k8s CNI options, please consider the revolutionary cilium CNI https://github.com/cilium/cilium that I am actively developing and maintaining, see doc here https://github.com/f5devcentral/f5-ci-docs/blob/master/docs/cilium/cilium-bigip-info.rst. Actually, cilium CNI is the only CNI that F5 has been contributing code to. I ran k3s(lightweight k8s) + cilium CNI + BIG-IP virtual edition in VMware ESXi cluster as my daily test lab

**Comment by trinaths** [comment]
No further activity. Closing this issue.
