### ISSUE TITLE
Unable to specify a custom persistenceProfile that is in the Common partition 

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#2479]
#### Setup Details
 CIS Version : 2.9
 Build: f5networks/k8s-bigip-ctlr:2.9
 BIGIP Version: BIG-IP 15.1.5.1 Build 0.0.14 Point Release 1
 AS3 Version: 3.36.1-1
 Agent Mode: AS3
 Orchestration: K8S
 Orchestration Version: N/A
 Pool Mode: Nodeport      
 Additional Setup details: N/A

#### Description
We are trying to apply a custom persistenceProfile in the common partition but when we set it we are getting this AS3 error
```
2022/06/30 21:59:36 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/asc-stg-ham-tenant-01-test/Shared/ascendlearning_external_https_test_443/persistenceMethods/0: should be equal to one of the allowed values ["cookie","destination-address","msrdp","source-address","tls-session-id"]]
``` 
We were trying to set it to either "Ascend_Session_Cookie" or "/Common/Ascend_Session_Cookie" but for each one in the policy, it throws the error above. 

We did find out you can set it to none which removes it completely which probably will solve our issue or removing it which our custom one was to encrypt the cookie.

Would have expected any persistenceProfile would be accepted be it OOTB or custom.
  

#### Steps To Reproduce
1) Deploy VS or VM with Policy that specifys a persistenceProfile that is custom 

#### Expected Result 
persistenceProfile is set on the VS

**Comment by trinaths** [comment]
@mitchellmaler - as per the AS3 error, - persistenceMethods/0: should be equal to one of the allowed values ["cookie","destination-address","msrdp","source-address","tls-session-id"

Please the PersistenceMethods provided. 

```
2022/06/30 21:59:36 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/asc-stg-ham-tenant-01-test/Shared/ascendlearning_external_https_test_443/persistenceMethods/0: should be equal to one of the allowed values ["cookie","destination-address","msrdp","source-address","tls-session-id"]]
```

**Comment by mitchellmaler** [comment]
@trinaths correct it is only saying I can pick from those three. Do you know if there is a way to enhance it so I can choose a custom PersistenceMethod?

**Comment by trinaths** [comment]
@mitchellmaler Looks like its a RFE rather than a BUG. This can be achieved via AS3, 

```
                    "persistenceMethods": [
                        {
                            "bigip": "/Common/test"
                        }
                    ]
                
```

**Comment by trinaths** [comment]
@mitchellmaler - Please share the example config for this requirement.

**Comment by trinaths** [comment]
Created [CONTCNTR-3583] for internal tracking.

**Comment by mikeoleary** [comment]
@trinaths , FYI, I have another customer now asking for the ability to add a custom persistence profile. In this case, they want cookie persistence but their custom cookie persistence adds some things that are specific for their application.
