### ISSUE TITLE
CIS compares a Route's targetPort to the wrong Service port

### ISSUE THREAD

**Issue by ttaylor249** [F5Networks/k8s-bigip-ctlr#2494]
#### Setup Details
 CIS Version : 2.9.0
 Build: azure-2662-51497f7bcb7f43ef491ae5e4e90837566f5898c6
 BIGIP Version: Big IP 16.1.2
 AS3 Version: 3.36.0
 Agent Mode: AS3
 Orchestration: OSCP
 Orchestration Version: 4.8.44
 Pool Mode: Cluster

#### Description  

The OpenShift Route resource has a field "spec.port.targetPort".  The documentation for this field reads:
The target port on pods selected by the service this route points to. If this is a string, it will be looked up as a named port in the target endpoints port list. Required

A Service resource has an array of port specs at "spec.ports".  A port spec has two fields of note: "port" and "targetPort"

The CIS controller is incorrectly comparing the Route's "targetPort" field to the Service's "port" field.  If it can't find a port spec in the service where the port field matches the Route's targetPort field, the following message is logged:

2022/07/07 17:44:33 [INFO] [CORE] Port '6443' for service 'oauth-openshift' was not found.

In most cases, this isn't a problem because the "port" and "targetPort" fields in a Service's ports array are frequently the same.  When they're not, the CIS controller doesn't populate the pool for the service.

#### Steps To Reproduce
The oauth-openshift Deployment in the "openshift-oauth" namespace of every OpenShift cluster demonstrates this problem.

Here's an excerpt from that Deployment:

kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth-openshift
  namespace: openshift-authentication
  labels:
    app: oauth-openshift
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oauth-openshift
  template:
    metadata:
      name: oauth-openshift
      namespace: openshift-authentication
      creationTimestamp: null
      labels:
        app: oauth-openshift
        oauth-openshift-anti-affinity: 'true'
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      restartPolicy: Always
      serviceAccountName: oauth-openshift
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: oauth-openshift
                  oauth-openshift-anti-affinity: 'true'
              topologyKey: kubernetes.io/hostname
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 50Mi
          name: oauth-openshift
          command:
            - /bin/bash
            - '-ec'
          ports:
            - name: https
              containerPort: 6443
              protocol: TCP
          image: >-
            quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:97e5a919d509ba24ac4773489c456f397ac8d9b66ecaf7c826e75fd609f3b422
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
      priorityClassName: system-cluster-critical

Here's the Service that's deployed for this applicaiton:

kind: Service
apiVersion: v1
metadata:
  name: oauth-openshift
  namespace: openshift-authentication
  labels:
    app: oauth-openshift
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: v4-0-config-system-serving-cert
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1580493903
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1580493903
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 6443
  selector:
    app: oauth-openshift
  clusterIP: <assigned_svc_ip>
  clusterIPs:
    - <assigned_svc_ip>
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack

And finally, here's the Route definition:

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: oauth-openshift
  namespace: openshift-authentication
  labels:
    app: oauth-openshift
spec:
  host: oauth-openshift.apps.<cluster_domain>
  to:
    kind: Service
    name: oauth-openshift
    weight: 100
  port:
    targetPort: 6443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

#### Expected Result 

1) A pool should be created for the oauth-openshift application.
2) That pool should have 3 members because the deployment specifies 3 replicas.
3) No messages should be logged because the Route specifies a targetPort of 6443 and the pods have a containerPort of 6443 as specified in the Deployment.

#### Actual Result  

1) A pool is created for the oauth-openshift application.
2) The pool has 0 members
3) The message "[INFO] [CORE] Port '6443' for service 'oauth-openshift' was not found." is logged by the CIS controller.

A viable workaround is to create a "dummy" Route like this:

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dummy-f5-oauth-openshift
  namespace: openshift-authentication
  labels:
    app: oauth-openshift
spec:
  host: dummy-oauth-openshift.apps.<cluster_domain>
  to:
    kind: Service
    name: oauth-openshift
    weight: 100
  port:
    targetPort: 443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

The only differences between this Route and the original Route are in the following fields:
- metadata.name
- spec.host
- spec.port.targetPort

Since this route is associated with the same service as the original, it ends up using the same pool.  However, since the dummy route uses the the value of the Service's port field as the targetPort, it populates the pool with members.

The end effect is that now the application can be accessed through the BigIP using either the original Route's host name or the dummy Route's hostname.  However, if you tried to access this dummy route through the OpenShift cluster's default ingress controller, it wouldn't work because the "spec.port.targetPort" is incorrect.

**Comment by trinaths** [comment]
@ttaylor249 - Please see https://github.com/F5Networks/k8s-bigip-ctlr/issues/1602#issuecomment-803802170 if this can solve the issue.

**Comment by ttaylor249** [comment]
I don't think that comment is relevant.  I believe that comment is related to specifying CIS config with ConfigMap resources.  In my case, we are having the CIS controller build the config itself by processing OpenShift Routes.

**Comment by trinaths** [comment]
Created [CONTCNTR-3756] for internal tracking.

**Comment by trinaths** [comment]
This fix will be available in Next Gen routes only.

**Comment by vklohiya** [comment]
It's fixed in nextGen Routes with PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2446
