### ISSUE TITLE
CIS exit with "Config driver signaled to stop: 9 - killed"

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2508]
#### Setup Details
 CIS Version : 2.8.1  

#### Description  

CIS exit with the following error message  

~~~
2022/07/23 16:16:43 [CRITICAL] Config driver signaled to stop: 9 - killed
~~~

**Comment by trinaths** [comment]
@kylinsoong Please share the config manifests causing this issue.

**Comment by trinaths** [comment]
No response from issue author. Closing this issue.
