### ISSUE TITLE
the f5 Operator is missing in openshift 4.10 

### ISSUE THREAD

**Issue by jwklijnsma** [F5Networks/k8s-bigip-ctlr#2543]
#### Title
the f5 Operator is missing in openshift 4.10 when will be this release ?

#### Actual Problem
the f5 Operator is missing in openshift 4.10
 https://catalog.redhat.com/software/operators/detail/5e98727cd4ae96b7493f08ce)

**Comment by trinaths** [comment]
[CONTCNTR-3464]
