### ISSUE TITLE
[CRD] incomplete regex for trafficGroup

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2549]
#### Setup Details
 CIS Version : 2.9.1
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 15.1.0.5
AS3 Version: 3.22.1
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.21.5
Pool Mode: ClusterIP (calico bgp)
Additional Setup details: Calico

#### Description  
 
Latest CRD for transportServer and virtualServer spec.serviceAddress.trafficGroup regex doesn't allow use of dashes which is very restrictive especially since by default dashes are used. 

#### Steps To Reproduce
1) Install CRDs from https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml 
2) Deploy a VirtualServer with a trafficGroup of "/Common/traffic-group-1"

#### Expected Result 

Ability to deploy with specified traffic group

#### Actual Result  

Error

```
# k apply -f transportserver-53-tcp.yaml
The TransportServer "transport-server-53-tcp" is invalid: spec.serviceAddress.trafficGroup: Invalid value: "/Common/traffic-group-1": spec.serviceAddress.trafficGroup in body should match '^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$'
```

#### Observations (if any)

This is similar to https://github.com/F5Networks/k8s-bigip-ctlr/issues/2413 

Something like below should fix it

```
^\/([A-z0-9-_+]+\/)*([A-z0-9-]+\/?)*$
```

**Comment by trinaths** [comment]
Created [CONTCNTR-3577] for internal tracking.
