### ISSUE TITLE
Ability to specify monitors for TransportServer

### ISSUE THREAD

**Issue by braunsonm** [F5Networks/k8s-bigip-ctlr#2550]
#### Description
Right now you can only specify some basic monitor settings on `TransportServer`. You should be able to configure things like HTTP checks or other custom monitor settings from the CRD.

#### Actual Problem
If you use layer 4 with a transportserver to send traffic to an ingress controller because you need to terminate TLS on your cluster, then you cannot setup health checks other than a basic "port open" check.

#### Solution Proposed
Ability to configure more details of the monitor like the parent being an HTTP check instead of a basic port open check.

#### Context
Ingress controllers like Istio allow you to do a HTTP check check on an endpoint to see if the pod is shutting down and should not accept new traffic for a graceful upgrade. Without F5 checking this endpoint, it won't know to stop sending traffic until the whole pod is killed.

**Comment by trinaths** [comment]
@braunsonm Please share more info on custom monitor settings. What more HTTP checks do you want CIS to support in CRD mode. Please mail more detailed info to automation_toolchain_pm at f5 dot com

**Comment by trinaths** [comment]
Created [CONTCNTR-3795] for internal tracking.

**Comment by braunsonm** [comment]
Perhaps something changed but you could not create any form of HTTP health check with the transportserver @trinaths 

So this issue is requesting that be available.
