### ISSUE TITLE
big ip controller issue

### ISSUE THREAD

**Issue by asidhu11702** [F5Networks/k8s-bigip-ctlr#2560]
We currently have rancher kubernetes engine version in our environment. RKE 1 currently uses canal cni which is combination of flannel and calico https://ubuntu.com/kubernetes/docs/cni-canal

since flannel is part of canal cni, will cis work with it in cluster mode and vxlan?, Rancher by default comes with nginx ingress controller(open source) my feeling is we can unstill it and just use big ip ingress controller. I also wanted to verify if we create a service of loadbalancer type will big ip controller provide the ip from f5 and assign it to my service? Based on documentation big ip controller only works with ingress and config map resources.

**Comment by asidhu11702** [comment]
Does CIS work with calico in cluster mode for vxlan

**Comment by vincentmli** [comment]
@asidhu11702 I don't think CIS with calico in cluster mode,  again I might be biased, if you want CIS work in cluster mode, Cilium is better CNI since I contributed the VXLAN function to Cilium. 

checkout
 https://isovalent.com/blog/post/cilium-release-112/#vtep-support
https://docs.cilium.io/en/latest/installation/vtep/
https://github.com/f5devcentral/f5-ci-docs/blob/master/docs/cilium/cilium-bigip-info.rst

**Comment by asidhu11702** [comment]
Thanks vincent for sharing your thoughts really appreciate it. Our kubernetes cluster is using calico cni because there is dependency on the services and component that requires calico cni. Changing from cni to cililum is not an option for us. Is there another way we can integrate CIS with F5 using calico cni plugin other than cluster, can we use node port instead? I found this documentation that talks about calico https://clouddocs.f5.com/containers/latest/userguide/calico-config.html?highlight=calico

This link is part of cis installation.

**Comment by trinaths** [comment]
@asidhu11702 I dont see this as a CIS issue but as a compatibility and functionality. Please raise an RFE as per your usecase.

**Comment by asidhu11702** [comment]
will do. Assuming changing cni to celium is not option. This means we cannot use cluster mode with cis. what other option we have to integrate CIS with cni? Please help me
