### ISSUE TITLE
calico CNI integration with CIS in cluster mode

### ISSUE THREAD

**Issue by asidhu11702** [F5Networks/k8s-bigip-ctlr#2569]
#### Title
CIS integration with Rancher kubernetes that has calico cni

#### Description
Currently calico cni is not supported with CIS in cluster mode this will not allow Big IP to be integrated deep with any calico enabled kubernetes cluster

#### Actual Problem
Any calico cni enabled kubernetes cluster wont be able to integrate with CIS big ip solution

#### Solution Proposed
CIS must support calico cni as many kubernetes distribution uses it

#### Alternatives
alternatives should be provided in how to integrate F5 with calico enabled kubernetes distribution

**Comment by trinaths** [comment]
Recommend use Cilium 1.12 with Rancher.
