### ISSUE TITLE
Enable HTTP2 for Ingress and Routes

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2572]
#### Title
Enable HTTP2 for Ingress and Routes

#### Description
Customers need to enable HTTP2 for their applications. Something they can do with BIGIP. Currently this is limited to HTTP1.1 for Ingress and Routes and it is only possible for VirtualServer CRDs.

#### Actual Problem
Application owners need to publish their applications with the HTTP2 protocol. 

#### Solution Proposed
Provide the same functionality as you do with VS CRD.

**Comment by trinaths** [comment]
Created [CONTCNTR-3591] for internal tracking.

**Comment by trinaths** [comment]
Recommend use policy CRD with NextGen Routes to enable HTTP2 for Routes. 

No support added for Ingress. Recommend using  VS and Policy CRD.
