### ISSUE TITLE
Enable PolicyCRD for Ingress and Routes

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2573]
#### Title
Enable PolicyCRD for Ingress and Routes

#### Description
Customers need to be able to enable iRules,  disable or enable persistence, changing HTTP profiles (or even WAF profiles). These are typical requirements that customers need.

#### Actual Problem
While customer are able to provide advanced reverse proxy capabilities with VS CRDs (through PolicyCRDs), they are not able to do the same with Ingress/Routes. With Ingress and Routes our annotations don't cover the same features. For customers that are not able to switch to VS CRD it is important to provide them access to the same features.  

#### Solution Proposed
Add Policy CRD to the annotations of Ingress/Routes.

**Comment by trinaths** [comment]
For Ingress CONTCNTR-3594 and Routes CONTCNTR-3592

**Comment by mdditt2000** [comment]
@skenderidis policyCRD is getting added to Next Gen Routes. At this time there is no plans to advance Ingress. This could be re-visited later next year once Next Gen Routes is completed. At this time i am closing the RFE out.
