### ISSUE TITLE
GSLB is not available for Ingress and Routes.

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2574]
#### Title
GSLB is not available for Ingress and Routes.

#### Description
Customers using Ingress/Routes want to publish and/or provide GSLB functionality with ExternalDNS. 

#### Actual Problem
Many of the customers are using Ingress or Routes to publish their applications and they are not able to move over to VS CRDs. Unfortunately, when using Ingress/Routes we cannot take advantage of the EDNS as it is only available for CRDs

**Comment by trinaths** [comment]
For Ingress [CONTCNTR-3599] and Routes CONTCNTR-3600

**Comment by trinaths** [comment]
Routes CONTCNTR-3600 supported with PR https://github.com/F5Networks/k8s-bigip-ctlr/pull/2640

GSLB supported with Next Gen routes.

GSLB support for Ingress [CONTCNTR-3599] will not be supported.
