### ISSUE TITLE
Openshift  = Default persistence to none instead of cookie

### ISSUE THREAD

**Issue by Mabchour** [F5Networks/k8s-bigip-ctlr#2576]
#### Title
Openshift  = Change the Default persistence to none 

#### Description
stateless microservices or applications don't need a persistence session

#### Actual Problem
VS configured by openshift has a default persistence to cookie without a way or option to change it to none

#### Solution Proposed
add an argument to BIG IP Controller to change the Default persistence to none

**Comment by mdditt2000** [comment]
@Mabchour please watch my youtube video 

Example
https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.8/crd-enhancements#crd-enhancements

Demo
https://www.youtube.com/watch?v=brlNGGJ0sw0

Difference between CRD and Routes
https://github.com/mdditt2000/openshift-4-9/tree/main/route-vs-crd#readme

Let me know if you have questions

Mark

**Comment by Mabchour** [comment]
Thanks @mdditt2000  for your helpful replay .

we moved our config to CRD and you're right the CRD is very rich , but in our production we have two DataCenters with two BIGIP  so when I used the CRD i cannot configure diffrent IP for the VS in each BIG IP otherwise I got two VS with the same IP adress (IP Conflict )

Is there any way in CRD to tell BIG IP , the IP to use in each BIG IP.

Hope my question is clear .

thanks in advance.

**Comment by mdditt2000** [comment]
@Mabchour please contact me automation_toolchain_pm@f5.com so i can schedule a call to understand your issue.

**Comment by trinaths** [comment]
> Thanks @mdditt2000 for your helpful replay .
> 
> we moved our config to CRD and you're right the CRD is very rich , but in our production we have two DataCenters with two BIGIP so when I used the CRD i cannot configure diffrent IP for the VS in each BIG IP otherwise I got two VS with the same IP adress (IP Conflict )
> 
> Is there any way in CRD to tell BIG IP , the IP to use in each BIG IP.
> 
> Hope my question is clear .
> 
> thanks in advance.

Is this HA pair ? @Mabchour

**Comment by Mabchour** [comment]
Yes @trinaths  , yes this is a HA pair with different IP

**Comment by trinaths** [comment]
@Mabchour  - Suggest use two CIS instances for two BIG-IPs. This may solve this issue. Please share your findings.

**Comment by Mabchour** [comment]
@trinaths  of course we use an instance for each BIGIP 
the issue is when we used the openshift routes  way we had the possibility  to specifiy the vs ip adress in the arguments , however in the CRD way the IP VS is specified in the CRD not in the CIS arguments , so the CIS instances use the same ip adress which a problme in our case

**Comment by Mabchour** [comment]
Hi  @trinaths  

We still have the issue , as I explained in my comment the sep 16 , we've tested the CRD , sure it support the function to set the cookie profile to none , but the problem it's suppose that we have Just one VS , 
but in our the platform is stretched in two DataCenters  , so we have two BIG IP(s) , each BIG IP with his own VS IP .  the CRD communicate with One VS .

We're asking either add this function to openshift BIG IP support or to tell us how it's possible to specify the couple BIG-IP-> VS in CRD mode.

Hope my comment is clear if need meeting I'm available please.

**Comment by trinaths** [comment]
@Mabchour Please send a mail with issue details to _automation_toolchain_pm at f5 dot com_
