### ISSUE TITLE
IPAM to provide the same IP for different TS

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2581]
#### Title
IPAM to provide the same IP for different TS or VS

#### Actual Problem
There are many applications that are using multiple port (like 80,443). To publish them on BIGIP we would need 2 TS or VS with IPAM. When using either TS or VS with IPAM we cannot publish them under the same IP address. IPAM will consider 2 different TS/VS resource and provide 2 different IPs. These makes it impossible to publish the application.

#### Solution Proposed
There has to be a label that would force the indicate to IPAM that it should provide the same IP

**Comment by trinaths** [comment]
Created [CONTCNTR-3595] for internal tracking.
