### ISSUE TITLE
Version contradictions between 2 CIS docs

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2591]
#### Setup Details
 CIS Version : 2.10      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.0      
 AS3 Version: 3.38      
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Cluster     
 Additional Setup details: N/A

#### Description  
Say I want to deploy CIS 2.10. This document: https://clouddocs.f5.com/containers/latest/userguide/what-is.html#container-ingress-service-compatibility seems to say that 2.10 will be compatible with BIG-IP 12-16 and AS3 3.13 - 3.38. Yet this one: https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/upgradeProcess.md#compatibility-matrix seems to say that BIG-IP must be v16 and AS3 must be 3.38.  

#### Steps To Reproduce
N/A

#### Expected Result 
N/A

#### Actual Result  
N/A

#### Diagnostic Information
N/A

**Comment by trinaths** [comment]
The clouddocs document showcases the lower and upper version of the supported software, whereas the upgrade document only mentions the upper version or the latest supported version. No changes to the docs. Closing this issue.
