### ISSUE TITLE
[DOC] https://clouddocs.f5.com/containers/latest/userguide/vmware-tanzu/#limitations update

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2604]
#### Description  
  
At present this list doesn't include ConfigMaps as one of the supported configuration methods. This is actually supported.

**Comment by trinaths** [comment]
Created [CONTCNTR-3687] for internal tracking

**Comment by lavanya-f5** [comment]
Doc updated https://clouddocs.f5.com/containers/latest/userguide/vmware-tanzu/#limitations
