### ISSUE TITLE
spanningEnabled: should be equal to constant false] message:declaration is invalid

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2605]
#### Setup Details
 CIS Version :2.10.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 17      
 AS3 Version: 3.39
 Agent Mode: AS3       
 Orchestration:Tanzu      
 Orchestration Version: TKG 1.4.2       
 Pool Mode: Cluster     
 Additional Setup details: NodePortLocal, standalone BIG-IP

#### Description  
 
The customer used the sample VirtualServer config which is enabled by default in:

https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html?highlight=spanningenabled

AS3 failed implementing the change.

Additionally kubectl get vs would show status as "OK"

#### Steps To Reproduce

- configure the sample VS in a standalone BIG-IP

#### Expected Result 

AS3 creates the configuration

#### Actual Result  

AS3 is unable to create the configuration.

#### Observations (if any)

This is likely to be an AS3-only issue but I find the following should be done in CIS:

- CIS should not report OK, actually I would suggest that the CR additionally displays a message line with the error when running kubectl get vs
- Please remove using spanningEnabled in the basic examples:
   - it is not a common option
   - it fails at present
[bigip-logs.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/9725026/bigip-logs.txt)

**Comment by trinaths** [comment]
Created [CONTCNTR-3686] for internal tracking

**Comment by trinaths** [comment]
Closing as completed.
