### ISSUE TITLE
[DOC] Applying setup files from clouddocs fails

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2606]
#### Setup Details
 CIS Version : 2.10.1    
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 17      
 AS3 Version: 3.29      
 Agent Mode: AS3      
 Orchestration: Tanzu
 Orchestration Version: TKG 1.4.2      
 Pool Mode: Cluster/ NodePortLocal      
 Additional Setup details: Antrea

#### Description  
  
The customer followed the instructions from https://clouddocs.f5.com/containers/latest/userguide/cis-installation.html and this is outdated and breaks the startup of CIS. 

We found problems in the CRD creation with the externaldnss -> externaldnss and also with the RBACs

The problem was fixed when using the files from 

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/rbac/clusterrole.yaml

We also had to delete the stale CRD externaldsnss 

Please note that this old configuration is seen in other pages as well:

https://clouddocs.f5.com/containers/latest/search.html?q=externaldnss&check_keywords=yes&area=default

<img width="1127" alt="Screenshot 2022-10-06 at 15 12 58" src="https://user-images.githubusercontent.com/16683733/194322163-a0488fe4-eda6-4798-91f5-c334ae975e78.png">

#### Observations (if any)

It would be ideal that the sample files in clouddocs were hosted in github to avoid this type of problems in the future. That is: clouddocs text would be an text from a github URL

**Comment by trinaths** [comment]
Created [CONTCNTR-3650] for internal tracking.

**Comment by mdditt2000** [comment]
Update

Update below docs

1) https://clouddocs.f5.com/containers/latest/userguide/cis-installation.html#installing-cis-manually

3. Create a Cluster Role and Cluster Role Binding on the Kubernetes/Openshift Cluster.

Remove the content and examples under this section and update with below content.

Fetch the latest rbac for both k8s and openshift from https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/rbac/clusterrole.yaml

kubectl apply -f clusterrole.yaml

 
2) https://clouddocs.f5.com/containers/latest/userguide/loadbalancer/

Remove clusterrole.yaml[¶ ](https://clouddocs.f5.com/containers/latest/userguide/loadbalancer/#id5)

[instead provide below](https://clouddocs.f5.com/containers/latest/userguide/loadbalancer/#id5)
Create a Cluster Role and Cluster Role Binding on the Kubernetes/Openshift Cluster.
Fetch the latest rbac for both k8s and openshift from https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/rbac/clusterrole.yaml

kubectl apply -f clusterrole.yaml
