### ISSUE TITLE
NodePortLocal using Antrea CNI failing to use the annotations on BIGIP CIS

### ISSUE THREAD

**Issue by marlonfrank30** [F5Networks/k8s-bigip-ctlr#2609]
#### Setup Details
 CIS Version : Release v2.10.1   
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.3.1
 AS3 Version: 3.4      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S    
 Orchestration Version: Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Pool Mode: NodePortLocal    
 Additional Setup details: [<Platform/CNI Plugins/ cluster nodes/ etc>](https://github.com/marlonfrank30/BIGIP-ContainerIngressServices/tree/main/NodePortLocal)

#### Description  
the issue lies with the use of a configmap in order to get the CIS configuration to use the annotations provided by Antrea CNI. 
If CRD is used instead it works just fine no problems as documented the repo above.  

#### Steps To Reproduce
1) make the necessary changes to the values.yaml file to not use custom as part of the args
2) install CIS controller using helm install -f values.yaml f5-ingress f5-stable/f5-bigip-ctlr
3) Apply configmap using kubectl apply -f configMap4nginxAS3.yaml
3)

#### Expected Result 
it configures BIGIP with a Virtual, Pool, and pool members being populated by the Antrea annotations.

#### Actual Result  
it configures BIGIP with a Virtual, Pool, and pool members being populated by the Antrea annotations however the pool members are empty (it can't read the annotations provided by Antrea) 

#### Diagnostic Information
```
marlon@k8s-master:~/CIS/NodePortLocal$ oc get pods
NAME                      READY   STATUS    RESTARTS   AGE
nginx1-7c775cd4f6-rdqqs   1/1     Running   0          94s
nginx1-7c775cd4f6-zrvpk   1/1     Running   0          94s

marlon@k8s-master:~/CIS/NodePortLocal$ oc describe svc nginx1
Name:              nginx1
Namespace:         default
Labels:            app=nginx1
                   cis.f5.com/as3-app=NGINX1
                   cis.f5.com/as3-pool=nginx1_pool
                   cis.f5.com/as3-tenant=WEB1
Annotations:       nodeportlocal.antrea.io/enabled: true
Selector:          app=nginx1
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.103.144.50
IPs:               10.103.144.50
Port:              nginx1  80/TCP
TargetPort:        myhttpport/TCP
Endpoints:         10.244.1.23:80,10.244.2.21:80


marlon@k8s-master:~/CIS/NodePortLocal$ oc describe pod nginx1-7c775cd4f6-rdqqs
Name:         nginx1-7c775cd4f6-rdqqs
Namespace:    default
Priority:     0
Node:         k8s-node2/10.1.10.89
Start Time:   Wed, 12 Oct 2022 15:58:43 +0000
Labels:       app=nginx1
              pod-template-hash=7c775cd4f6
Annotations:  nodeportlocal.antrea.io: [{"podPort":80,"nodeIP":"10.1.10.89","nodePort":61008,"protocol":"tcp","protocols":["tcp"]}]
Status:       Running
IP:           10.244.1.23
IPs:
  IP:           10.244.1.23

oc logs f5-ingress-f5-bigip-ctlr-758cb9685b-sz9xd -n kube-system
2022/10/12 15:58:43 [DEBUG] key: nginx1-7c775cd4f6-rdqqs, NPL annotation not found for Pod
2022/10/12 15:58:43 [DEBUG] key: nginx1-7c775cd4f6-rdqqs, NPL annotation not found for Pod
2022/10/12 15:58:43 [DEBUG] key: nginx1-7c775cd4f6-zrvpk, NPL annotation not found for Pod
2022/10/12 15:58:43 [DEBUG] key: nginx1-7c775cd4f6-zrvpk, NPL annotation not found for Pod
2022/10/12 15:58:43 [DEBUG] key: nginx1-7c775cd4f6-rdqqs, NPL annotation not found for Pod
2022/10/12 15:58:43 [DEBUG] key: nginx1-7c775cd4f6-zrvpk, NPL annotation not found for Pod
2022/10/12 15:58:45 [DEBUG] key: nginx1-7c775cd4f6-zrvpk, NPL annotation not found for Pod
2022/10/12 15:58:46 [DEBUG] key: nginx1-7c775cd4f6-rdqqs, NPL annotation not found for Pod
2022/10/12 15:58:49 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/10/12 15:58:49 [DEBUG] [CORE] Finished syncing virtual servers nginx1 in namespace default (9.923156ms), 5/5
```  

#### Observations (if any)
even though CIS logs state that it has finished syncing the virtual server's configuration for the pool members they are not being populated as they do when I use a CRD instead...
```
2022/10/12 15:58:49 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/10/12 15:58:49 [DEBUG] [CORE] Finished syncing virtual servers nginx1 in namespace default (6.087181ms), 5/5
2022/10/12 15:58:49 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/10/12 15:58:49 [DEBUG] [CORE] Finished syncing virtual servers nginx1 in namespace default (6.556825ms), 5/5
2022/10/12 15:58:49 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/10/12 15:58:49 [DEBUG] [CORE] Finished syncing virtual servers nginx1 in namespace default (5.077345ms), 5/5
```

**Comment by lavanya-f5** [comment]
@marlonfrank30 Can you please share the configmap and CIS deployment yaml to debug further

**Comment by marlonfrank30** [comment]
VirtualServer.yaml uses CRD and it works
However when I tried it with ConfigMap it didn't...

Let me know if you need anything else.

Marlon Frank - Solutions Engineer - Security
Tel +1-469-955-4468
***@***.******@***.***<https://www.certmetrics.com/f5certified/public/badge.aspx?i=6&t=c&d=2018-03-10&ci=F50000076302>
Under DDoS Attack? Get F5 Silverline DDoS Protection! - www.f5.com/attack<http://www.f5.com/attack>
***@***.******@***.******@***.******@***.******@***.***<https://devcentral.f5.com/>
[tagline-v6-1.png]

**Comment by lavanya-f5** [comment]
@marlonfrank30 Thanks for the info. Able to reproduce on local environment. Created [CONTCNTR-3659] for internal tracking
