### ISSUE TITLE
[ Question ] Does v2.10.1 support kubernetes 1.24 ?

### ISSUE THREAD

**Issue by rajbaratht** [F5Networks/k8s-bigip-ctlr#2618]
Hello - 

Does v2.10.1 support kubenetes v1.24, if not when can we expect bigip-ctlr to support kubenetes v1.24

**Comment by trinaths** [comment]
@rajbaratht CIS 2.10.x is already compatible with k8s 1.24 https://clouddocs.f5.com/containers/latest/userguide/what-is.html#releases-and-versioning
