### ISSUE TITLE
CIS 2.10 Improve CIS performance with number of ingress resources exceeding 1000

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#2619]
#### Title
Title of the feature/enhancement request

Improve CIS performance with number of ingress resources exceeding 1000

#### Description

when number of ingresses increases, for example 1000 ingresses. adding/removing new configmap resource could take for example maybe at least 5 minutes, this is not optimal in production

#### Actual Problem

deploy large number of ingresses with example 1000 like below:

take perl script and manifest from https://github.com/vincentmli/Perl/blob/master/1-8544659861/

`./ingress-ns-2.10.pl --add -n 10 -p 1 -i 100`

then add a new configmap resource

`kubectl apply -f f5-deployment.yaml; kubectl apply -f f5-service.yaml; kubectl apply -f f5-configmap-ns.yaml`

wait and watch the configmap virtual server in BIG-IP, it takes at least > 5 minutes

**Comment by vincentmli** [comment]
@zongzw you seems having some idea before on the improvement with large number of resources CIS process when CIS start up, this is easy to reproduce with above Perl script

**Comment by vincentmli** [comment]
note I only say at least 5 minutes delay here as just approximation, it could take way longer than that.

**Comment by vincentmli** [comment]
now I understand when CIS start up, it will collect all 1000 resources and only do one declaration, so it could take a few minutes for BIG-IP to get the declaration and populate the declaration in BIG-IP.

**Comment by zongzw** [comment]
> 

@vincentmli 
Sorry, I just saw your reported problem,
In response to your performance question, I went through the latest CIS code again, especially the code related to ingress, but unfortunately, tuning performance in the short term is not an easy task, there are the following reasons. CIS team please correct me or complement if need.
    1. At deployment strategy level, CIS uses a fully declarative approach to handle K8S resource changes, which causes the all 1,000 ingress resources to be repeatedly checked when CIS is started. Personally, I think to solve this problem, a reasonable way should be saving the state before the last startup and load the state when CIS restarts to avoid repeatly resource checks, especially when the amount of configuration is large (>1000).
    AS3 is the declarative way on BIG-IP level, but it doesn't mean CIS should do the same full-set way, instead, CIS need to have some logic/ability to distinguish which set are changed and which set are not changed, then do the only changed part, so that to improve performance.
    2. At the implementation level, each ingress resource change request will trigger the processing logic for all ingress resources in the current namespace: https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/appManager.go#L1530. Is this really necessary?
    3. In addition, at the implementation level, CIS relies on AS3 to interact with BIG-IP, personally, I think AS3 performance is not so good, it makes a global lock on BIG-IP when deploying resources, and doing that in a single thread to ensure configuration consistency. China PD team did a big try to use iControlRest to replace AS3: CIS-C (https://cis-c.f5se.io/), now it's only suitable for configmap scenarios.
Finally, in CIS there are still many usage to ctlr.kubeClient.CoreV1().XXXX. It is big time costs. The correct way to retrieve resources from K8S should be to use informer.cache, otherwise, it's very slow and has performance impact to api-server of the K8S cluster.

**Comment by trinaths** [comment]
Addressing this issue from SR. Closing this duplicate issue.
