### ISSUE TITLE
Enable Address Translation on VirtualServers Managed by K8s-BigIP-Ctlr

### ISSUE THREAD

**Issue by bleech1** [F5Networks/k8s-bigip-ctlr#2636]
#### Title
Enable Address Translation on VirtualServers Managed by K8s-BigIP-Ctlr

#### Description
The applications deployed in Kubernetes behind our F5 BigIP device require that we have Address Translation turned on for the VirtualServer.  Currently, this is not possible through the K8s-BigIP-Ctlr using CCCL.  Could we please add an additional [supported ingress annotation](https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.8/#kubernetes-ingress-resources) that allows us to turn on AddressTranslation for the VirtualServer?

#### Actual Problem
We need to have Address Translation enabled for all traffic going to our applications behind our F5 BigIP devices.  Unfortunately, the K8s-BigIP-Ctlr doesn't allow us to configure this flag, so AddressTranslation on the managed VirtualServer is always turned off.

#### Solution Proposed
We would like to add an additional annotation that would allow us to turn this on for specific VirtualServers.  The annotation would allow us to enable AddressTranslation and then the K8s-BigIP-Ctlr, using CCCL in the backend, would then update the VirtualServer to enable AddressTranslation.

#### Alternatives
We have created a fork of the CCCL library [here](https://github.com/bleech1/f5-cccl/commit/e9b42741230e9f243924fd9f456468f4f602cbf1) where we added a `translateAddress` field to the VirtualServer resource that is being sent by CCCL to the F5 device.  In our fork, we set that flag always to be `enabled` since that was required for our environment, but ideally that can be toggled through an annotation on the ingress object itself.

#### Additional context
N/A

**Comment by mdditt2000** [comment]
Add something simular to what was added in PolicyCRD

**snat | String | Optional | auto |** **Reference to SNAT pool on BIG-IP**. The other allowed values are: auto (default) and none. VirtualServer. Add to both CCCL and AS3 for Ingress

Jira CONTCNTR-3670

**Comment by bleech1** [comment]
@mdditt2000 - just to clarify, the "Address Translation" we need to enable is this field on the GUI:
![image](https://user-images.githubusercontent.com/19521919/200950612-0d9c20c7-d35b-49d0-90d2-d31ffb5b8b1c.png)
It can be modified through tmsh by running a command like:
```
tmsh modify ltm virtual <VIRTUAL_SERVER_NAME> translate-address enabled
tmsh modify ltm virtual <VIRTUAL_SERVER_NAME> translate-address disabled
```
It only accepts the values `disabled` and `enabled` in tmsh.
