### ISSUE TITLE
Make throws an error at `devel-image` target

### ISSUE THREAD

**Issue by mikejoh** [F5Networks/k8s-bigip-ctlr#2654]
#### Setup Details
 CIS Version : `master`     
 Build: N/A
 BIGIP Version: N/A
 AS3 Version: N/A     
 Agent Mode: N/A     
 Orchestration: N/A    
 Orchestration Version: N/A
 Pool Mode: N/A
 Additional Setup details: N/A

#### Description
When running `make devel-image` make exits with the following error:
```
/bin/sh: -c: line 1: syntax error near unexpected token `('
```
The `BASE_OS` variable in the command for building the dev Docker image is missing the `$` in front of it.

#### Steps To Reproduce
1) `git clone https://github.com/F5Networks/k8s-bigip-ctlr.git`
2) `make devel-image`

#### Expected Result 
That a development Docker image would be built.

#### Actual Result
N/A

#### Diagnostic Information
N/A

#### Observations (if any)
N/A

**Comment by trinaths** [comment]
No update to CIS. Closing this issue.
