### ISSUE TITLE
RFE: introduce hidden command flag to log AS3 declaration at info level

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#2678]
#### Title

introduce a hidden command argument flag to log AS3 declaration at info level

#### Description

introduce a hidden command argument flag, by default the hidden argument flag is not set to reduce noise log, but when user reported resources between cluster, CIS, BIG-IP not in sync, enable this CIS hidden command flag to log the AS3 declaration, so we know what the resources are in the AS3 declaration, compare that with cluster or BIG-IP so we know where the resources is not in sync to direct us to find root causes.

#### Actual Problem

often time customer reported BIG-IP pool members or other resources are not in sync with CIS or cluster, we don't know if it is BIG-IP problem, CIS problem, or cluster problem,  it is tedious to review CIS debug log because it is too much debug information to be useful, and CIS does not log the AS3 declaration before sending to BIG-IP at any log level, so we don't know if it is BIG-IP problem, CIS problem, or cluster problem, this delays the time to root cause and users can get very frustrated

#### Solution Proposed

add a hidden command argument flag that is not exposed to user, but when asked to collect trouble shooting data, we can ask user to turn on the hidden command argument flag to log the AS3 declaration at information level, so we will have useful trouble shooting data without debug log which is too much noise.

**Comment by trinaths** [comment]
We dont log the AS3 declaration and cannot provide any hidden tags for customer to enable. The AS3 declaration contains sensitive information and cannot be logged. However, suggest checkout source code, make changes and build. Such a build is not for production use.

**Comment by vincentmli** [comment]
@trinaths what sensitive data included in the AS3 declaration? can't those sensitive data be masked
