### ISSUE TITLE
No way to access slack channel

### ISSUE THREAD

**Issue by lolwww** [F5Networks/k8s-bigip-ctlr#2681]
README suggests asking questions in slack:
_We encourage you to use the cis-kubernetes channel in our [f5CloudSolutions Slack workspace](https://f5cloudsolutions.slack.com/)_

However seems there is no way to access this slack channel unless you have an account there already.
And no way to register a new account.

**Comment by trinaths** [comment]
Suggest create SLACK account and Join the channel/workspace.
