### ISSUE TITLE
Need to Enable "HTTP MRF ROUTER" on a VirtualServer CRD to Support HTTP2 Full Proxy

### ISSUE THREAD

**Issue by jmorello-mdsol** [F5Networks/k8s-bigip-ctlr#2682]
Update to the Virtual Server CRD to enable the "HTTP MRF ROUTER" setting for HTTP2

We are able to apply a HTTP2 Profile to our Virtual Server CRD using a Policy CRD successfully. 
However, the F5 documentation for setting up a HTTP2 full proxy virtual-server states that you must also enable "HTTP MRF ROUTER" on the virtual-server.

https://techdocs.f5.com/en-us/bigip-15-1-0/big-ip-http2-full-proxy-configuration/http2-full-proxy-configuring.html#concept-1206

We are able to accomplish this using a configMap, but would really like to move this application over to a Virtual Server CRD.

F5 CIS v2.10

**Comment by trinaths** [comment]
Created [CONTCNTR-3743] for internal tracking.
