### ISSUE TITLE
Openshift/OVN routed mode: automate L3 route creation 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2696]
#### Title
Openshift/OVN: automate L3 route creation 

#### Description

When using OVN in routed mode at present we require the customers to create the routes manually (See https://github.com/mdditt2000/k8s-bigip-ctlr/tree/main/user_guides/ovn-kubernetes-ha#step-3-configure-big-ip-routes).

This RFE is for automating this static route creation in CIS.

#### Actual Problem

Kubernetes clusters might have hundreds of nodes and these are not static either. Nodes might be scaled-in/out at any time. 

#### Solution Proposed

Updating the routes could be done similarly to the way VxLAN FDB entries are updated currently. One remarkable difference is that the routes should be created in CIS' instance partition instead of common, in order to allow several instances of CIS.

#### Alternatives

To the best of our knowledge it is not possible to automate this BIG-IP configuration from within Openshift's mechanisms.

**Comment by trinaths** [comment]
No planned implementation with CIS. Recommend use OVNK8s+OCP with CIS.
