### ISSUE TITLE
OVN in hybrid overlay and routed modes with traffic to non-cluster hosts

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2697]
#### Title

OVN with hybrid overlay mode and non-cluster traffic

#### Description

It is typical that the same VLAN where the cluster is deployed there are additional hosts with services such as databases. By default, when following our current documentation these services are unreachable from the PODs unless a virtual forwarding is created in the BIG-IP.

In more detail next.

Hybrid overlay requires to add the following annotations to the namespaces.
 
  annotations:
    k8s.ovn.org/hybrid-overlay-external-gw: 10.142.2.60 #self ip of Vxlan tunnel
    k8s.ovn.org/hybrid-overlay-vtep: 10.192.125.60 #BIG-IP interface address rotatable to the
 
These annotations have the behaviour of enforcing to route all the traffic that is not of the cluster’s using the external gateway. When hybrid-overlay is used, the behaviour is that PODs that want to connect with other hosts in the same subnet as the OCP Node’s subnet, they go through the external gateway, adding an additional hop.
 
Using the following network diagram
 
```
     Node
+---------------+
|    -------    |   OCP Node’s subnet
|    | POD |    | -----------------------[ External gateway]        
|    -------    |           |
+---------------+           |
                            |
                       Other hosts
                   in the same subnet
```
 
Where the external gateway is the BIG-IP.

The L3 hops from the POD to other hosts in the same subnet is as follows:
 
POD --- CNI --- External gateway --- Other hosts in the same subnet
 
If the BIG-IP is not configured with a forwarding VIP, these other hosts which are cluster local are unreachable.

This situation is the same for generic egress traffic (to 0.0.0.0/0) but customers find it more unexpected for local traffic.

#### Actual Problem

This behaviour is currently not documented in BIG-IP's documentation. 

#### Solution Proposed

* This should be in our documentation.

* Worth to consider if we could add the following switches:
  * --egress-vip=local for automatically creating a local network-only forwarding VIP
  * --egress-vip=all for automatically creating a generic forwarding VIP
  * --egres-vip=none for not creating any forwarding VIP automatically

**Comment by trinaths** [comment]
No planned support in CIS. Recommend use OVN Kubernetes rather than hybrid overlay.
