### ISSUE TITLE
Add ability to choose WebSocket Profile on virtualservers.cis.f5.com

### ISSUE THREAD

**Issue by gnobironts** [F5Networks/k8s-bigip-ctlr#2700]
#### Title
Add ability to choose WebSocket Profile on virtualservers.cis.f5.com

#### Description
Add a new parameter on virtualservers.cis.f5.com CRD to make the **WebSocket Profile** configuration customizable

#### Actual Problem
Virtual Servers created using the virtualservers.cis.f5.com CRD don't have the websocket profile enabled by default and don't offer any parameter to change this

#### Solution Proposed
Add a new parameter on the CRD to let the user enable websockets

**Comment by trinaths** [comment]
@gnobironts  Please mail us automation_toolchain_pm <automation_toolchain_pm@f5.com> your requirements with more details. This config must be added to Policy CRD and used with VS crd.

**Comment by trinaths** [comment]
Created [CONTCNTR-3761] for internal tacking. ETA 2.13
