### ISSUE TITLE
Create separate virtualservers with different virtual address for different BIG-IP

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2712]
In each site, they want to expose the NGINX IC to both BIG-IPs, but with separate virtual server addresses. Is this possible without creating two sets of NGINX IC each in their own namespace, and have separate CIS instances to monitor each NGINX IC? Presumably, externalDNS can’t be planned until we solve this

**Comment by pedley-f5** [comment]
Per Mark, this should work. I have 2 CIS pods running version 2.11.1 pointing to 2 separate standalone BIG-IPs. Per Mark, the deployment/services should exist in namespace hello-world, and 2 virtual services are deployed in hello-world1 and hello-world2, with the virtual address being unique (can't use the same address on 2 standalone BIG-IPs on the same network).  As per Mark, cis pod 1 monitors hello-world and hello-world1, cis pod 2 monitors hello-world and hello-world2. The configurations are pushed out to the BIG-IPs as expected, but the pool members are empty. This is likely due to the virtual servers being configured in separate namespaces.

**Comment by trinaths** [comment]
Created [CONTCNTR-3771] for internal tracking.

**Comment by lavanya-f5** [comment]
@pedley-f5 can you check if you're using serviceNamespace parameter on the pool as the service is in different namespace than the virtualserver. 

Example configuration for serviceNamespace https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/VirtualServer/virtual-with-pool-svc-different-ns/vs-with-pool-svc-diff-ns.yaml

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/CustomResource.md

**Comment by pedley-f5** [comment]
That works, thanks! I didn't see it in the virtualserver CR document: https://clouddocs.f5.com/containers/latest/userguide/crd/virtualserver.html

**Comment by lavanya-f5** [comment]
@pedley-f5 Thanks.Will update the missing parameter in clouddocs

**Comment by trinaths** [comment]
This option is documented in github docs - See https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/CustomResource.md
