### ISSUE TITLE
virtualserver clashes with NGINX virtual server

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2713]
•	Customer has identified that “virtualserver” for NGINX and CIS clash and wonder if there’s a more permanent fix. They are currently adding short name f5vs to the CIS virtualserver, but this is not a long-term strategy. Ingresslink can’t be used because it is lacking functionality of the virtualserver CR that the customer requires.

**Comment by trinaths** [comment]
@pedley-f5 

> Ingresslink can’t be used because it is lacking functionality of the virtualserver CR that the customer requires.

Please give more info on functionality required here.  Changing the CR name would be a breaking change for many.

**Comment by srikanthmalyala** [comment]
Ingress link is not having support for profiles

**Comment by pedley-f5** [comment]
Why are we asking about ingresslink? I'm referring to virtualservers. As previously mentioned, the customer needs to use CIS virtualservers along with NGINX ingess controller because ingresslink does not support functionality such as TLS offload. The challenge is there is no way to use kubectl commands to list both NGINX virtual servers and CIS virtual servers without modifying the CRD.

**Comment by trinaths** [comment]
@pedley-f5 - Is the lacking functionality with IngressLink is only the CRD name conflict ?

**Comment by srikanthmalyala** [comment]
@pedley-f5 Why there is no way to use the kubectl list? You can list it using the full CRD name 
for e.g - k get virtualserver.k8s.nginx.org -A

**Comment by trinaths** [comment]
No update to CIS. Recommend using alias, adding short name f5vs to the CIS virtualserver.
