### ISSUE TITLE
MRF Support

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2714]
Will MRF be supported by CIS in the future? If not on the roadmap, customer will request an enhancement

**Comment by trinaths** [comment]
@pedley-f5 Please see https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/VirtualServer/HttpMrfRoutingEnabled/vs-with-mrfrouting-enabled.yaml 

MRF routing is supported in VS CRD. Any other usecase in focus ?

**Comment by pedley-f5** [comment]
Is there any additional documentation on this?

**Comment by trinaths** [comment]
@pedley-f5 - Please share your usecase so that we can discuss more on this config. Lets sync via teams.

**Comment by pedley-f5** [comment]
I don't have a complete use case at this time. I just need to know at this time what CIS is capable of with regards to MRF, more specifically, what does httpMrfRoutingEnabled? Does this support MRF other than HTTP?

**Comment by trinaths** [comment]
Please refer documentation at https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/CustomResource.md
