### ISSUE TITLE
Egress via VXLAN

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2715]
•	How do we support egress via VXLAN? Customer plans to use the BIG-IP as an explicit proxy for egress HTTP traffic, and they have a project requirement that all traffic must ingress and egress via the BIG-IPs

**Comment by vincentmli** [comment]
@pedley-f5 if customer cluster uses Cilium CNI, you can specify a BIG-IP VXLAN tunnel subnet say 10.1.1.0/24 that is  outside of  pod CIDR 10.0.0.0/16, then all egress traffic to tunnel subnet 10.1.1.0/24 can be directed through BIG-IP, not sure if that matches your requirement.

**Comment by trinaths** [comment]
Egress is not supported.
