### ISSUE TITLE
(vsname)_443_tls_irule

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2716]
•	When proxying TLS, iRule (vsname)_443_tls_irule gets pushed to the BIG-IP and sometimes gets assigned to the VS. Under what circumstances does the iRule get assigned, and what does it do?

**Comment by trinaths** [comment]
@pedley-f5 Please the example and the context for clear discussion.

**Comment by pedley-f5** [comment]
1) What does the irule do, as it is not self documenting and 2) what in CIS causes the irule to be applied/removed?

**Comment by trinaths** [comment]
iRule is applied in Re-encrypt and A/B Deployment usecases.

**Comment by pedley-f5** [comment]
Understood, but what exactly does it do?

**Comment by trinaths** [comment]
In CIS, we use this irule and apply for any kind of https virtual server for both edge and reencrypt termination. To sniff host header and path and select the corresponding pool based on the internal DataGroup. And for reencrypt, we use this irule to apply/add server side tls on the backend. Even we select respective pool for wildcard hosts. We always apply one irule per VS(VIP) incase of https. Hope this helps.
