### ISSUE TITLE
as3=false not working when filter-tenants=true

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2725]
#### Setup Details
CIS Version : 2.11.1
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 15.1.8
AS3 Version: 3.26
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.21.5
Pool Mode: Nodeport 
Additional Setup details: Calico

#### Description  

When filter-tenants=true, CIS doesn't watch for as3=false in configmap mode in the later CIS versions (so far tested 2.10, 2.11.1) so unable to delete tenants. Whereas in 2.7.1 and filter-tenants=true, I am able to add/remove tenants with as3=true and as3=false in the configmaps. 

#### Steps To Reproduce
1) Deploy CIS with filter-tenants=true
2) Deploy any configmap with as3=true
3) Confirm that tenant exists on BIG-IP
4) Modify same configmap with as3=false, and note that CIS doesn't pick up on the changed cm

Note, this works fine in v2.7.1

#### Expected Result 

CIS can delete tenants when as3=false in the configmap when using filter-tenants

#### Actual Result  

CIS ignores as3=false

#### Diagnostic Information

my arguments:
```
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=[200a:b:c:d:0:0:0:114]",
            "--bigip-partition=k8s",
            "--insecure=true",
            "--pool-member-type=nodeport",
            "--log-as3-response=true",
            "--log-level=debug",
            "--manage-configmaps=true",
            "--as3-validation=true",
            "--agent=as3",
            "--filter-tenants=true",
            "--enable-ipv6=true",
            "--verify-interval=60"
            ]
```

**Comment by trinaths** [comment]
Created [CONTCNTR-3764] for internal tracking
