### ISSUE TITLE
[CONTCNTR-3765]  metrics broken in v2.11.1

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2726]
#### Setup Details
CIS Version : 2.11.1
Build: f5networks/k8s-bigip-ctlr:latest
BIGIP Version: Big IP 15.1.8
AS3 Version: 3.26
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.21.5
Pool Mode: Nodeport
Additional Setup details: Calico

#### Description  
Below related queries/issues:

1. /metrics endpoint not showing anything f5 related in v2.11.1, where in v2.10 I can see bigip_monitored_nodes
2. /metrics endpoint not listening at all on the metrics port in --custom-resource-mode=true in v2.11.1
3. Any additional documentation on what F5 specific stats we are supposed to see when we hit metrics? (e.g. in AS3 mode, with configmaps or with custom resources)?
  

#### Steps To Reproduce
1) Deploy v2.11.1, and notice that /metrics doesn't show bigip_monitored_nodes
2) Deploy v2.10 and can see bigip_monitored_nodes
3) Redeploy v2.11.1 with --custom-resource-mode=true, and then see that you get a "Connection refused"

#### Expected Result 
In Configmap or CRD Mode, expect to see below at least:
# curl -g http://[2600:2000:1000:1111:14:2:0:64a2]:8080/metrics
# HELP bigip_monitored_nodes Total count of monitored nodes by the BigIP k8s CTLR
# TYPE bigip_monitored_nodes gauge
bigip_monitored_nodes{nodeselector=""} 2

#### Actual Result  

AS3 Configmap Mode:
# curl -g http://[2600:2000:1000:1111:14:2:0:64a2]:8080/metrics
# HELP bigip_monitored_nodes Total count of monitored nodes by the BigIP k8s CTLR
# TYPE bigip_monitored_nodes gauge
bigip_monitored_nodes{nodeselector=""} 2

Custom Resource Mode:
# curl -g http://[2600:2000:1000:1111:14:2:0:64a6]:8080/health
curl: (7) Failed connect to 2600:2000:1000:1111:14:2:0:64a6:8080; Connection refused

#### Diagnostic Information

my args

```
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=[200a:b:c:d:0:0:0:114]",
            "--bigip-partition=k8s",
            "--insecure=true",
            "--pool-member-type=nodeport",
            "--log-as3-response=true",
            "--log-level=debug",
            "--manage-configmaps=true",
            "--http-listen-address=[0:0:0:0:0:0:0:0]:8080",
            "--as3-validation=true",
            "--agent=as3",
            "--filter-tenants=true",
            "--enable-ipv6=true",
            "--verify-interval=60"
            ]
```  

#### Observations (if any)
Note, I am using IPv6 pod network.
Also note, in v2.11.1 in crd mode (and even in earlier versions where crd mode should allow metrics because of https://github.com/F5Networks/k8s-bigip-ctlr/issues/1873 ), I get connection refused when hitting the pod internal IP:

```
# curl -g http://[2600:2000:1000:1111:14:2:0:64a2]:8080/metrics
curl: (7) Failed connect to 2600:2000:1000:1111:14:2:0:64a2:8081; Connection refused
```

I can see in configmap mode that at least it's listening on 8080:
```
# nsenter -t 105999 -n netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::8080                 :::*                    LISTEN      105999/k8s-bigip-ct
```

but when --custom-resource-mode=true on v2.11.1, nothing's listening on 8080
```
# nsenter -t 21650 -n netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
```

**Comment by trinaths** [comment]
Created [CONTCNTR-3765] for internal tracking.

**Comment by vklohiya** [comment]
@tkam8 , I was able to reproduce the metrics issue on my local setup. But I am unable to reproduce the connection refused error with above mentioned steps using CIS 2.11.1 and I see that CIS is exposing the port 8080 in  v2.11.1 with --custom-resource-mode=true.

```
sudo nsenter -t 23663 -n netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::8080                 :::*                    LISTEN      23663/k8s-bigip-ctl
```

Can you again confirm the steps to reproduce, to be sure I am not missing anything?

**Comment by tkam8** [comment]
@vklohiya  I've opened a new issue to track the second point here, I've included repro steps:

https://github.com/F5Networks/k8s-bigip-ctlr/issues/2912
