### ISSUE TITLE
CIS IN CRDS mode: Use the same IP for two vip in different port

### ISSUE THREAD

**Issue by Vhartmannfigaro** [F5Networks/k8s-bigip-ctlr#2740]
#### Setup Details
k8s-bigip-ctrlr: 2.11.0
F5 version: BIG-IP 16.1.3.2 Build 0.0.4 Point Release 2
appscvs version: f5-appsvcs-3.41.0-1.noarch
Mode: Nodeport, CIS in CRDS mode
Infrastructure: K8S in data center

#### Description  
I want to use the same IP for two vip in different port, when i create two virtual server, the second eraze the first, i also tried to put two different VirtualServerName but it doesn't change anything, 

Do you have an example of yaml to do this ?

Thanks in advance,

Best regards

**Comment by trinaths** [comment]
@Vhartmannfigaro - Try using virtualServerHTTPPort along with servicePort as shown in VS CRD https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/VirtualServerWithTLSProfile/custom-virtual-address-port/custom-http-port.yml
