### ISSUE TITLE
supported AS3 schema versions to CIS versions

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/k8s-bigip-ctlr#2742]
#### Title
supported AS3 schema versions to CIS versions

#### Description
Is there a table or documentation that lists the supported AS3 schema versions for every CIS version?

**Comment by prabhatkarki** [comment]
To be more clear. The CIS release notes of each version only indicate the compatibility of a new version of AS3 schema. But it doesn't indicate upto which older version of AS3 schema is supported. For example, does CIS 2.10 support the AS3 3.18 schema?

**Comment by trinaths** [comment]
@prabhatkarki  Please see CIS compatibility matrix - https://clouddocs.f5.com/containers/latest/userguide/what-is.html#id3
