### ISSUE TITLE
Certificate and Key file not deleted from F5 when CRDs deleted in Kubernetes

### ISSUE THREAD

**Issue by walkingtub** [F5Networks/k8s-bigip-ctlr#2746]
#### Setup Details
 CIS Version : 2.10.0  
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.5.1    
 AS3 Version: 3.27      
 Agent Mode: AS3      
 Orchestration: K8S     
 Orchestration Version:       
 Pool Mode: Cluster    

#### Description  
 This may be related to Issue #2595 or may be slightly different. We are running 2.10 so not sure when that issue was fixed. We had a TLSProfile with Kubernetes secret deployed and later realized the FQDN should be changed. The CRDS (vs, tls, secret) were removed, new cert with new SAN generated (but named the exact same), and CRDS redeployed. We saw that the TLS Profile name was new but when looking at the certificate on the F5 it was still showing the old SAN. Removed all the crds and saw the vip, tls profile, be removed but the certificate persisted. Deleted the cert/key via tmsh but the cert/key persisted in the downloads folder. When new TLSprofile is deployed it was still using the old cert. Doesn't seem CIS deletes the cert/key file from the downloads folder when those are removed in Kubernetes. Had to manually deleted the cert/key, then redeploy.
  

#### Steps To Reproduce
1) Deployed TLS Profile with Kubernetes Secrets so that it pushes the certificate and key to F5.
2) Changed the certificate SAN and name of TLS Profile
3) Re-deployed TLS Profile and observed the original cert in /var/config/rest/downloads is still there with new name but old SAN.
4) Deleted VS, TLSProfile, Secret in K8s, cert and key still persist in downloads folder
5) Manually remove files with "rm -f"
6) Redeploy

#### Expected Result 
When removing TLSProfile and Secret (whichever step puts the certificate on the F5) it should also remove those files from the big ip config as well as the downloads folder. In the rare event as we found the cert is named the same, but cert properties have changed so we need to make sure it uses the cert. From a technical debt perspective if CIS is not deleting certs they will just persist in the downloads folder until manually deleted.

**Comment by walkingtub** [comment]
Upon further testing manually deleting everything and redeploying still did not fix the cert issue. We had to change the name of the secret and deploy. Finally the F5 is using the new CN. The whole time the contents of the secret in K8s has been the same. Only thing changed was the name of the secret.

**Comment by trinaths** [comment]
@walkingtub - Share your finding with 2.11.1.

**Comment by trinaths** [comment]
@walkingtub Any update on this  ?

**Comment by walkingtub** [comment]
Can confirm it is working as expected in version 2.11.1.
Certificate is being removed when virtual server is removed. Therefore K8s secret can be directly updated with new cert, secret name, cert name, tlsprofile name can all be the same. F5 receives updated cert upon redeployment of virtualserver.

Please close issue.
