### ISSUE TITLE
CIS looking for Services in the wrong namespace. 

### ISSUE THREAD

**Issue by pedrorouremalta** [F5Networks/k8s-bigip-ctlr#2751]
#### Setup Details
 CIS Version : 2.11 
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.3
 AS3 Version: 3.x      
 Agent Mode: AS3   
 Orchestration: K8S    
 Orchestration Version:       
 Pool Mode: Nodeport      
 Additional Setup details: Using an old Antrea CNI version which does not support NodePortLocal feature. 

#### Description  
 
I’m working with a customer in CIS deployment using CRD. We created a VirtualServer CRD in one namespace referencing Services in another namespace. Everything is working. The CIS controller is able find the Services in the appropriate namespace and the Pools are populated correctly. But it seems that the CIS also looks for the Services in the namespace where the Virtual Server CRD was deployed and we see  some messages in the CIS logs stating CIS is not able to find the Services in this namespace.

I managed to replicate the issue in a lab. I have two Services **app1-svc** and **app2-svc** deployed in the namespace **apps**. The Virtual Server CRD is deployed in the namespace **default** referencing the Services **app1-svc** and **app2-svc** in the namespace **apps**. The CIS finds the Services and the Pools are correctly populated but I get the following error messages in the CIS logs:

2023/01/07 14:41:18 [ERROR] Error: Service default/app1-svc not found
2023/01/07 14:41:18 [ERROR] Error: Service default/app2-svc not found

It seems CIS is also trying to find the Services **app1-svc** and **app2-svc** in the namespace **default**.

#### Steps To Reproduce
1) Create a VirtualServer CRD referencing Services in a different namespace. 
2) Check the CIS logs. 

#### Expected Result 

CIS looks for the Services only in the namespace specified in the VirtualServer CRD configuration. 

#### Actual Result  

CIS is looking for the Services in in the namespace specified in the VirtualServer CRD configuration but also in the namespace in which the VirtualServer CRD was deployed. 

#### Diagnostic Information

VirtualServer CRD Manifest: 

kind: VirtualServer
metadata:
   name: apps-virtualserver
   labels:
     f5cr: "true"
spec:
   virtualServerAddress: "10.1.10.100"
   pools:
   - path: /app1
     service: app1-svc
     serviceNamespace: apps
     servicePort: 80
     monitor:
       type: "http"
       send: "GET /\r\n"
       recv: "app1"
       interval: 5
   - path: /app2
     service: app2-svc
     serviceNamespace: apps
     servicePort: 80
     monitor:
       type: "http"
       send: "GET /\r\n"
       recv: "app2"
       interval: 5

CIS logs:

2023/01/07 14:41:18 [ERROR] Error: Service default/app1-svc not found
2023/01/07 14:41:18 [ERROR] Error: Service default/app2-svc not found

**Comment by trinaths** [comment]
This issue is fixed with PR https://github.com/F5Networks/k8s-bigip-ctlr/pull/2741
Please validate this issue with CIS dev image quay.io/f5networks/k8s-bigip-ctlr-devel:3c61666aff2a202549ee9213c3cb21557fb193fd
