### ISSUE TITLE
CIS installation to support Pod Security Standards mechanism

### ISSUE THREAD

**Issue by pierluigilenoci** [F5Networks/k8s-bigip-ctlr#2756]
#### Title
CIS installation to support Pod Security Standards mechanism

#### Description

Pod Security Mechanism is a Kubernetes security feature that is enabled by default in Tanzu Kubernetes Grid and supported at least in Openshift and Rancher

See https://kubernetes.io/docs/concepts/security/pod-security-standards/

#### Actual Problem
In clusters/namespaces with this feature enabled the installation of CIS fails

#### Solution Proposed
Provide PSS policies in the documentation

RFE updated #1719 

FYI: @alonsocamaro @trinaths

**Comment by trinaths** [comment]
@pierluigilenoci Do you want to update Helm charts for CIS to enable PSS policies ?

**Comment by pierluigilenoci** [comment]
@trinaths I would like to prevent CIS installation from failing in clusters where PSS are active.

**Comment by trinaths** [comment]
Adding this RFE to existing JIRA [CONTCNTR-3728] for Helm charts.
