### ISSUE TITLE
Add EDNS support for service typeLB

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2785]
#### Title
A customer wants to use EDNS for their TypeLB that are being deployed with BIGIP. 
Currently ENDS works with TS, VS, IngressLink but not Service Type LB. 

#### Solution Proposed
Add an annotation where the Host is inserted, so that EDNS can pick it up.

**Comment by trinaths** [comment]
Created [CONTCNTR-3921] for internal tracking.
