### ISSUE TITLE
AS3 Post delay - Not working as expected.

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2789]
#### Setup Details
 CIS Version : 2.12     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1
 AS3 Version: 3.31      

#### Description  
When I deploy 3 CRDs services, I always get the first one on the first AS3 call and then there is another AS3 for the remaining 2. 

When  I deploy CIS with AS3-post-delay of 10 seconds, I still get the same thing but with 10 seconds delay. The first AS3 call will only have 1 CRD configuration.   
Check the logs below
```
2023/02/28 11:05:41 [DEBUG] [AS3] Delaying post to BIG-IP for 10 seconds
2023/02/28 11:05:51 [DEBUG] [AS3] PostManager Accepted the configuration
2023/02/28 11:05:51 [DEBUG] [AS3] posting request to https://10.1.1.5/mgmt/shared/appsvcs/declare/cis-crd
2023/02/28 11:05:55 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:cis-crd --- message: success
2023/02/28 11:05:55 [DEBUG] [AS3] Delaying post to BIG-IP for 10 seconds
2023/02/28 11:06:05 [DEBUG] [AS3] PostManager Accepted the configuration
2023/02/28 11:06:05 [DEBUG] [AS3] posting request to https://10.1.1.5/mgmt/shared/appsvcs/declare/cis-crd
2023/02/28 11:06:09 [DEBUG] [AS3] Response from BIG-IP: code: 200 --- tenant:cis-crd --- message: success
```

I would expect that within this 10 seconds, if there is any new configuration, it would be added on the first AS3 call

**Comment by trinaths** [comment]
Created [CONTCNTR-3827] for internal tracking
