### ISSUE TITLE
Delay when deploying Virtual Server with IPAM

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2791]
#### Setup Details
 CIS Version : 2.12      

#### Description  
I deployed 50 VS with IPAM and it takes 15 sec for the IPs to be allocated (then the AS3 will be sent) 
I deployed 100 VS with IPAM and it takes 20 sec for the IPs to be allocated 
I deployed 250 VS with IPAM and it takes 120 sec for the IPs to be allocated 
I deployed 500 VS with IPAM and it takes 2500 sec (I stopped the deployment)

Please find attached the logs from CIS and IPAM (seems like CIS is on a loop)
I have attached also the manifest.

[ipam-logs.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/10868430/ipam-logs.txt)
[cis-logs.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/10868431/cis-logs.txt)
[vs-500.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/10868435/vs-500.txt)

**Comment by trinaths** [comment]
Created [CONTCNTR-3829] for internal tracking.

**Comment by vklohiya** [comment]
@skenderidis , Are you using infoblox IPAM or static IPAM ?

**Comment by skenderidis** [comment]
Static

Regards,

Kostas Skenderidis

________________________________

**Comment by nandakishorepeddi** [comment]
@skenderidis  This issue has been resolved in the upcoming CIS v2.13, scheduled to be available on June 1, 2023. Please reopen, if it still exists.
