### ISSUE TITLE
In which CIS version is JIRA CONTCNTR-3697 implemented?

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#2794]
description: If name-space-filter (or name-space argument) is used the CIS-Log will be flooded by huge amount of messages.

**Comment by trinaths** [comment]
ETA 2.12.1 Early April'23

**Comment by trinaths** [comment]
Fixed with https://github.com/F5Networks/k8s-bigip-ctlr/pull/2805
