### ISSUE TITLE
In which CIS version is JIRA CONTCNTR-3128 implemented?

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#2795]
description: CIS long-init time (F5 case 00303432)
See also issue #2619 - CIS 2.10 Improve CIS performance with number of ingress resources exceeding 1000

**Comment by trinaths** [comment]
Ingress partition support JIRA CONTCNTR-3128 is implemented in 2.12. Please see release notes - https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/RELEASE-NOTES.rst#2120
