### ISSUE TITLE
Enhance product documentation to add description of log levels

### ISSUE THREAD

**Issue by jputrino** [F5Networks/k8s-bigip-ctlr#280]
At present, we only have one entry in the troubleshooting doc for Kubernetes. 
At a minimum, we should add instructions for changing the log level to debug the controller. 
We should add commonly-encountered issues to this doc as they are identified. 

CC @rsalsa @andrewjjenkins

**Comment by amudukutore** [comment]
@jputrino - the product documentation component to this (if any) should be tracked here. The solution docs component should be tracked on https://github.com/F5Networks/f5-ci-docs/issues/295.

**Comment by jputrino** [comment]
The troubleshooting doc will live in f5-ci-docs; this issue should cover adding log messages to the docs/README.

**Comment by amudukutore** [comment]
Something along these lines: https://github.com/F5Networks/cf-bigip-ctlr/tree/master/docs#instrumentation-and-logging

**Comment by kmunson1973** [comment]
If you BIG-IP is rebooting or down the CC will crash, it will come back online but could be several minutes.

**Comment by amudukutore** [comment]
@kmunson1973 - please see https://github.com/F5Networks/k8s-bigip-ctlr/issues/438 which I just filed to capture this issue.
