### ISSUE TITLE
Source IP restriction per pool/host header/path in a VS CRD

### ISSUE THREAD

**Issue by andreasjacobi** [F5Networks/k8s-bigip-ctlr#2806]
#### Title
Source IP restriction per pool/host header/path in a VS CRD

#### Description
Both for a single VirtualServer and multiple hostGroup based VirtualServers it should be possible to restrict access to the backend based on source IP address. In a hostGroup scenario it should be per host header/pool/path and not for the entire VS.

#### Actual Problem
Sometimes it is required to not expose a VirtualServer to any source IP but instead it is mandatory to limit the clients based on the IP address.
This requirement could also be very granular and per application so in a hostGroup VirtualServer scenario one application might allow any source but another application needs to allow specific sources.

#### Solution Proposed
Looking at LTM policies, similar to what is implemented in CIS for the hostGroup and host header rule match criteria, a LTM policy rule match criteria that uses "TCP address matches any of the following <ip-addresses> at request time" should do the trick.

**Comment by trinaths** [comment]
Created [CONTCNTR-3918] for internal tracking

**Comment by mdditt2000** [comment]
@andreasjacobi currently only option would be to use a CRD policy with allowSourceRange

allowSourceRange | String | Optional | N/A | Comma-separated list of CIDR addresses to allow inbound to services corresponding to VirtualServer CRD. Allowed values are comma-separated, CIDR formatted, IP addresses. For example: 1.2.3.4/32,2.2.2.0/24

https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/customResource/Policy

You could also use a firewallPolicy policy. Currently the API between CIS and BIG-IP does not have a way to decline a source based on Host Header. Policy action is “request”, “response” only. This is not something we want todo in the iRule. 

Closing this request
