### ISSUE TITLE
[ERROR] Not found cis.f5.com/ipamLabel 

### ISSUE THREAD

**Issue by efaverman** [F5Networks/k8s-bigip-ctlr#2816]
#### Setup Details
CIS Version : v2.11.0
Build: f5networks/k8s-bigip-ctlr:2.11.0
BIGIP Version: Big IP 16.1.2.1 Build 0.0.10 Point Release 1
AS3 Version: 3.36.0-6
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: v1.20.15
Pool Mode: Nodeport

#### Description  
 When configuring VirtualServer from manifest and a LoadBalancer Service WITHOUT `cis.f5.com/ipamLabel` annotation, everything works properly, however misleading error appears in CIS logs

#### Steps To Reproduce
1) Configure LoadBalancer Service WITHOUT `cis.f5.com/ipamLabel` annotation
2) Configure VirtualServer or TransportServer for LoadBalancer Service

#### Expected Result 
No error in logs

#### Actual Result  
Everything works properly, but we get error in logs: 
```
[ERROR] Not found cis.f5.com/ipamLabel in <my service> Unable to process.
```

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment]
[CONTCNTR-3843] for internal tracking
