### ISSUE TITLE
CIS errors should contain offending resource name

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2824]
#### Title
CIS errors should contain offending resource name

#### Description
CIS stdout logs should identify the actual resource (configmap or CR) that contains semantic/syntax errors to reduce time to resolution

#### Actual Problem

Currently, debug logs do not identify the resource that causes errors like below, so it is painful to find the offending resource that is actually causing the issue. In many cases there are 40-50 resources. 

2022/12/20 10:10:29 [DEBUG] [CORE] Finished syncing virtual servers webserver-test-1 in namespace ns-webserver-test-1 (7.486µs)
2022/12/20 10:10:29 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0
2022/12/20 10:10:29 [DEBUG] [CORE] Finished syncing virtual servers webserver-test-2 in namespace istio-operator (7.942µs)
2022/12/20 10:10:29 [ERROR] [AS3] Template is not valid. see errors
2022/12/20 10:10:29 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/12/20 10:10:29 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
2022/12/20 10:10:29 [ERROR] - declaration.members.0: Must validate one and only one schema (oneOf)
2022/12/20 10:10:29 [ERROR] - declaration.members.0.serverAddresses: Invalid type. Expected: array, given: null
2022/12/20 10:10:29 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/12/20 10:10:29 [ERROR] - declaration.members.0: Must validate all the schemas (allOf)
2022/12/20 10:10:29 [ERROR] - declaration: Must validate all the schemas (allOf)
2022/12/20 10:10:29 [DEBUG] [CORE] Updated 0 of 0 virtual server configs, deleted 0

#### Solution Proposed

Error logs should say something like below:

2022/12/20 10:10:29 [ERROR] [AS3] **configmap-test1 in namespace linerate-app-test** Template is not valid. see errors
2022/12/20 10:10:29 [ERROR] - declaration: Must validate "then" as "if" was valid
2022/12/20 10:10:29 [ERROR] - declaration.members.0: Must validate "then" as "if" was valid
--snip--

#### Alternatives

The only alternative is to manually check one by one every resource watched by CIS to check for something like a port number mismatch with the service port. This is cumbersome and prone to mistake. 

#### Additional context

Tried checking BIG-IP logs like restjavad-audit.log but no clues show up.

**Comment by trinaths** [comment]
Created [CONTCNTR-3920] for internal tracking.

**Comment by trinaths** [comment]
No further update to CIS required.
