### ISSUE TITLE
High availability between 2 virtualserver

### ISSUE THREAD

**Issue by DmitriyGlu95** [F5Networks/k8s-bigip-ctlr#2829]
CIS Version : 2.10.1       
 AS3 Version: 3.42.0-5       
 Agent Mode: AS3  
 Orchestration: K8S

We have two virtual servers deployed via CIS on one F5, each located in its own partition (each virtual server is used for one Kubernetes cluster). They use the same anycast IP (routeAdvertisement: "enable"). How can we ensure high availability between these two virtual servers? The problem is that when there are no members behind one virtual server (pods behind server in k8s are scaled to 0), the virtual server still announces its route. In a standard situation, if all members failed the health check, the virtual server would stop announcing the route. However, in our situation, the members are absent, and the virtual server does not stop announcing the route. But second virtual server with the same IP has working members. We cannot specify an additional health check for the service (it's check only endpoints for service). The annotation "cis.f5.com/f5.pool.action: reject" does not work. We cannot add a service from another cluster to the second pool VirtualServer.

What should we do in this situation?

**Comment by DmitriyGlu95** [comment]
And how set "Default Pool" for virtual server via cis? By default it's create pool but not set it in default for virtual server. Default Pool - None.

**Comment by DmitriyGlu95** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2377
"Recommend using a TransportServer as an option.", working, but I need use profiles and monitoring at http level.

**Comment by trinaths** [comment]
@DmitriyGlu95 Do you still have this issue ?

**Comment by trinaths** [comment]
No reply for user. Closing this issue.

**Comment by DmitriyGlu95** [comment]
@trinaths it's not solution, I need use L7 balancing. I need ssl termination

**Comment by trinaths** [comment]
@DmitriyGlu95 Please mail [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com) this issue with required CIS configuration and resource examples.

**Comment by trinaths** [comment]
@DmitriyGlu95 Please mail [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com) this issue with required CIS configuration and resource examples.

**Comment by trinaths** [comment]
Closing this issue. No further communication.
