### ISSUE TITLE
VS is not correctly added to GSLB pool

### ISSUE THREAD

**Issue by KoviPK** [F5Networks/k8s-bigip-ctlr#2848]
#### Setup Details
 CIS Version : 2.12.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.8.1 Build 0.64.3 Engineering Hotfix     
 AS3 Version: 3.40
 Pool Mode: Cluster     

#### Description  
 
Hello, 

we are having issue with our deployment of VS and externalDNS

Our issue is that if we undeploy virtualServer and externalDNS and deploy it again, cis is unable to correctly add VS to GSLB pool as a member. It creates GSLB WIDEIP A record and a GSLB pool, but there is no VS as a member. VS is correctly created on f5 with a proper pool. That works fine.
This is happing also if we deploy it all from a scratch.

If try to redeploy only externalDNS, it works fine. I guess its because VS is already on f5 and is able to map it correctly.

I saw this issue https://github.com/F5Networks/k8s-bigip-ctlr/issues/2796 and it was fixed in  https://github.com/F5Networks/k8s-bigip-ctlr/pull/2819 for CIS 2.12.1, but that was for transportServer but not virtualServer.

I even try to update our AS3 because of this -  https://github.com/F5Networks/f5-appsvcs-extension/issues/578 but no luck.

For a workaround we used this anotation in externalDNS for ArgoCD to wait one wave of deploy and that seems to work, but we didnt test it fully and its not a native  solution and it adds time to deployment.
  annotations:
    argocd.argoproj.io/sync-wave: "1"

We are using ArgoCD for a deployment.
Here are our YAMLs:

---
apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: demo-v1-exdns
  labels:
    f5cr: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  domainName: foo.bar.foo.bar.eu
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/foo-bar-dns-server
    monitor:
      type: https
      send: "GET /monitor.html HTTP/1.1\r\nHost: foo.bar.foo.bar.eu\r\n"
      recv: ""
      interval: 10
      timeout: 30

apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: demo-v1-edge-tls
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/foo_bar_automated
    reference: bigip
  hosts:
    - foo.bar.foo.bar.eu

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: demo-v1-vs
  labels:
    f5cr: "true"
spec:
  host: foo.bar.foo.bar.eu
  hostGroup: f5route
  tlsProfileName: demo-v1-edge-tls
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: "GET /monitor.html HTTP/1.1\r\nHost: foo.bar.foo.bar.eu\r\n"
      timeout: 10
      type: http
    path: /
    service: demo-v1-service
    servicePort: 80
  virtualServerAddress: 1.1.1.1

#### Expected Result 

GSLB WIDEIP with a pool and VS as a member.

#### Actual Result  

No VS member in GSLB pool.

#### Diagnostic Information

I was able to find this in a CIS log:

2023/04/12 12:43:30 [DEBUG] [2023-04-12 12:43:30,651 urllib3.connectionpool DEBUG] https://x.x.x.x:443 "GET /mgmt/tm/gtm/pool/a/~Common~foo.bar.foo.bar.eu_x_x_x_x_foo-bar-/members/~Common~foo-bar-dns-server:~foo-bar~Shared~crd_x_x_x_x_443 HTTP/1.1" 404 141
2023/04/12 12:43:30 [INFO] Text: '{"code":404,"message":"Object not found - /Common/foo-bar-dns-server:/foo-bar/Shared/crd_x_x_x_x_443","errorStack":[],"apiError":1}'
2023/04/12 12:43:30 [DEBUG] [2023-04-12 12:43:30,651 icontrol.session DEBUG] RESPONSE::STATUS: 404 Content-Type: application/json; charset=UTF-8 Content-Encoding: None
2023/04/12 12:43:30 [DEBUG] [2023-04-12 12:43:30,651 __main__ DEBUG] Pool Member: /Common/foo-bar-dns-server:/foo-bar/Shared/crd_x_x_x_443, exists: False

Thank you.
Petr K.

**Comment by trinaths** [comment]
@KoviPK Please share complete CIS logs and resource YAML to [automation_toolchain_pm at f5 dot com](mailto:automation_toolchain_pm@f5.com)

**Comment by trinaths** [comment]
@KoviPK Please share complete CIS logs and resource YAML to [automation_toolchain_pm at f5 dot com](mailto:automation_toolchain_pm@f5.com)

**Comment by trinaths** [comment]
No update from the user. closing this issue.
