### ISSUE TITLE
The configuration for the F5 is not being added from pod inside Openshift Cluster

### ISSUE THREAD

**Issue by hfernandez-2** [F5Networks/k8s-bigip-ctlr#2851]
#### Setup Details
 CIS Version : 2.12.1     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 17.1.0      
 AS3 Version: 3.6.0     
 Agent Mode: AS3       
 Orchestration: OSCP      
 Orchestration Version: 4.10.52    
 Pool Mode: Cluster      
 Additional Setup details: OVNKubernetes, clusterNetwork: cidr: 10.128.0.0/15

#### Description  
  The configuration for the F5 is not being added. We are following this procedure: [https://github.com/mdditt2000/k8s-bigip-ctlr/tree/main/user_guides/ovn-kubernetes-standalone#readme](url)

#### Steps To Reproduce
1) Create a dedicated partition for the OCP
2) Follow this procedure [https://github.com/mdditt2000/k8s-bigip-ctlr/tree/main/user_guides/ovn-kubernetes-standalone#readme](url)

#### Expected Result 
We expected to see the changes to be updated in the F5 configuration web page but nothing happens

#### Actual Result  

We can see the pod is reaching the F5 and is able to establish a connection for the management port
![image](https://user-images.githubusercontent.com/131004712/232537043-3c073666-ac3c-49a4-9672-8695fd5246ee.png)

Access from the workers
![image](https://user-images.githubusercontent.com/131004712/232537254-0c627de1-7aad-4363-a577-5cbab309b2e3.png)

A Java error from AS3 log
![image](https://user-images.githubusercontent.com/131004712/232537327-7331364c-f39f-469a-a62d-9e6bb835a7d2.png)

#### Observations (if any)
We think is similar to this other issue https://github.com/F5Networks/k8s-bigip-ctlr/issues/2814

**Comment by trinaths** [comment]
@hfernandez-2 Please share complete CIS logs and resource YAML to [automation_toolchain_pm at f5 dot com](mailto:automation_toolchain_pm@f5.com)

**Comment by hfernandez-2** [comment]
> @hfernandez-2 Please share complete CIS logs and resource YAML to [automation_toolchain_pm at f5 dot com](mailto:automation_toolchain_pm@f5.com)

Attached and sended to the email.
[log_cis.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/11252970/log_cis.txt)
[yamls.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/11252971/yamls.txt)

**Comment by trinaths** [comment]
CIS deployment in OCP 4.12 at user end is working fine with CRDs. However, OCP setup must be improved for Route processing for CIS. Closing this issue.
