### ISSUE TITLE
RFE: add static route mode support for Cilium CNI

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#2861]
#### Title
Title of the feature/enhancement request
add static route mode support for Cilium CNI

#### Description
A small overview of the feature/enhancement proposed

User has Cilium in route mode and BIG-IP is able to reach Cilium pod through static route

#### Actual Problem

BIG-IP is unable to reach to Cilium pod when Cilium in route mode and user does not want to use VXLAN in cluster mode

#### Solution Proposed

add static mode for Cilium CNI

**Comment by vincentmli** [comment]
and cilium need to have `ipam: cluster-pool`, so the k8s node has annotation:

```
Annotations:        io.cilium.network.ipv4-cilium-host: 10.42.0.235
                    io.cilium.network.ipv4-health-ip: 10.42.0.64
                    io.cilium.network.ipv4-pod-cidr: 10.42.0.0/24

```

**Comment by vincentmli** [comment]
cilium v1.13.0 switched to annotation `network.cilium.io/ipv4-pod-cidr` with `ipam: kubernetes`

**Comment by trinaths** [comment]
Created [CONTCNTR-3947] for internal tracking.
