### ISSUE TITLE
Kubernetes pod restart is triggering pool members deletion[obj_delete] 

### ISSUE THREAD

**Issue by surendarmsk1** [F5Networks/k8s-bigip-ctlr#2884]
#### Setup Details
 CIS Version : 2.9.1    
 Build: f5networks/k8s-bigip-ctlr:2.9.1
 BIGIP Version: Big IP 2.9.1
 Kubernetes Version: v1.21.14
 AS3 Version: 3.28.0    
 Pool Mode: Cluster/Nodeport      

**Problem:** Kubernetes pod restart is triggering pool members deletion[obj_delete] in F5. Need to know why would BigIP controller will trigger the obj_delete ? Also why would this occur for only when there's more number of VIP on a single partition?

#### Steps To Reproduce
1) Issue occurs when there's multiple VIPs[more than 100+] running on a single F5 **partition**. Pod restart on kubernetes clusters, which inturn leads to all pool member deletion on F5 on the respective poo/VIP. 

#### Diagnostic Information
**F5 BigIP logs**

```
May 12 03:37:38 onprem-f5.com notice mcpd[4622]: 01070417:5: AUDIT - client tmsh, tmsh-pid-28660, user svc-f5 - transaction #2713705517-40 - object 0 - obj_delete { pool_member_metadata { pool_member_metadata_pool_name "/OpenDB/Shared/opendb" pool_member_metadata_node_name "/Common/12.16.52.5" pool_member_metadata_port 30918 } } [Status=Command OK]


May 12 03:37:38 onprem-f5.com notice mcpd[4622]: 01070417:5: AUDIT - client tmsh, tmsh-pid-28660, user svc-f5 - transaction #2713705517-31 - object 0 - obj_delete { pool_member_metadata { pool_member_metadata_pool_name "/OpenDB/Shared/opendb" pool_member_metadata_node_name "/Common/12.16.53.12" pool_member_metadata_port 30918 } } [Status=Command OK]


May 12 03:37:38 onprem-f5.com notice mcpd[4622]: 01070417:5: AUDIT - client tmsh, tmsh-pid-28660, user svc-f5 - transaction #2713705517-28 - object 0 - obj_delete { pool_member_metadata { pool_member_metadata_pool_name "/OpenDB/Shared/opendb" pool_member_metadata_node_name "/Common/12.16.52.9" pool_member_metadata_port 30918 } } [Status=Command OK]
```

**Comment by trinaths** [comment]
@surendarmsk1 Please share CIS configuration, Valid resources and complete CIS debug logs to automation_toolchain_pm at f5 dot com to validate this issue.

**Comment by surendarmsk1** [comment]
logs sent to F5 team and being dealt with different channel
