### ISSUE TITLE
etcd failure should not impact data plane

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#2909]
#### Setup Details
CIS Version : 2.11.1
Build: f5networks/k8s-bigip-ctlr:2.11.1
BIGIP Version: Big IP 15.1.8
AS3 Version: 3.26
Agent Mode: AS3
Orchestration: K8S
Orchestration Version: 1.21.5
Pool Mode: Nodeport
Additional Setup details: Calico

#### Description  
CIS behavior is to delete configuration like pool members when etcd is down ( getEndpoints function fails) 

#### Steps To Reproduce
1) Deploy application e.g. with AS3 configmap
2) etcd becomes unreachable (e.g. due to disk failure/ full disk)
3) Confirm CIS removes pool members when discovery returns no endpoints due to getEndpoints failure

#### Expected Result 

Even if etcd is down, data plan should remain in tact as pods could still be in running state ready for processing traffic

#### Actual Result  

pool members deleted causing downtime

#### Diagnostic Information
```logs
2023/05/25 08:45:31 [ERROR] [CORE] Error getting service list. etcdserver: leader changed
2023/05/25 08:45:31 [DEBUG] [CORE] Discovered members for service my-service1-ns/my-service1 is []
```  

Below KB article outlines the same issue
https://my.f5.com/manage/s/article/K41481489

**Comment by trinaths** [comment]
Created [CONTCNTR-3988] for internal tracking.
