### ISSUE TITLE
DOC: OpenShift installation fails following docs

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2967]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest (2.13.1)
 BIGIP Version: Big IP 17      
 AS3 Version: 3.45      
 Agent Mode: AS3       
 Orchestration: OpenShift      
 Orchestration Version:   4.12.22   
 Pool Mode: Cluster      
 Additional Setup details: OVNKubernetes

#### Description  

When following either https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-standalone.html
or  https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-cluster.html

CIS creation brings the following warning:
```
$ oc create -f f5-bigip1-ctlr-deployment.yaml 
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cntr-ingress-svcs" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cntr-ingress-svcs" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cntr-ingress-svcs" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cntr-ingress-svcs" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/k8s-bigip-ctlr-deployment created

```

Also please note that there is a quoting typo in the instructions:
<img width="1026" alt="Screenshot 2023-07-10 at 12 11 22" src="https://github.com/F5Networks/k8s-bigip-ctlr/assets/16683733/98b2aa7c-f906-429d-a3a6-540f2ecffd45">

#### Steps To Reproduce

Follow the instructions of the documentation

#### Expected Result 

No warning should be shown

**Comment by alonsocamaro** [comment]
Also, please consider moving the order of the steps:

- Step 2 after Step 3
- Step 4 before Step 3

Regards

**Comment by alonsocamaro** [comment]
Also, the comment "Note:  Manually sync the BIG-IP so the routes are deployed on the standby." is wrong as these are not sync'ed

**Comment by alonsocamaro** [comment]
Also, the page is missing links to the Service definitions of the example

**Comment by trinaths** [comment]
Created [CONTCNTR-4068] for internal tracking.
