### ISSUE TITLE
DOC: how to avoid OpenShift Routes not being processed by both OpenShift router and BIG-IP

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2971]
#### Setup Details
 CIS Version : 2.13      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: NA
 AS3 Version: NA     
 Agent Mode: AS3
 Orchestration: OCP      
 Orchestration Version: 4.12       
 Pool Mode: ClusterIP      
 Additional Setup details: NA
 
#### Description  
  
In ClusterIP mode the routes should be only processed by BIG-IP and the following should be applied in the default OpenShift router so it is not processed by it as well:

https://docs.openshift.com/container-platform/4.12/networking/ingress-sharding.html#nw-ingress-sharding-default_ingress-sharding

**Comment by trinaths** [comment]
Created [CONTCNTR-4070] for internal tracking.
