### ISSUE TITLE
Nodes in 'NotReady' state are not removed from their pool(s) when using ServiceType Loadbalancer

### ISSUE THREAD

**Issue by marcriddle** [F5Networks/k8s-bigip-ctlr#2978]
#### Setup Details
 CIS Version : 2.13.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: BIG-IP 15.1.5.1 Build 0.0.14 Point Release 1
 AS3 Version: 3.45.0     
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version: v1.25.9       
 Pool Mode: Nodeport      

#### Description  
Nodes in 'NotReady' state are not removed from pool when using ServiceType Loadbalancer. If nodes are in this state when a service is created, they are not added to the pool that is created, but if they transition to this state they are not removed from the pool. Additionally, when new nodes are added to a cluster or 'NotReady' nodes transition to 'Ready' they are not added to the pool.

We have some automated processes that build, destroy, and reboot nodes, and part of this lifecycle involves the nodes transitioning to 'NotReady' before being restarted/destroyed. Ideally, they would be removed from any bigip pools at this point, as if not they'll need to fail health checks before being marked down, resulting in some number of failed requests to that node.

  

#### Steps To Reproduce
1) Create service of type 'LoadBalancer'
2) Stop kubelet on a node that belongs to the pool that was created, or otherwise transition node to 'NotReady'
3) Observe that node is still a member of the pool

#### Expected Result 
Nodes marked 'NotReady' should be removed from pools that they belong to. 

#### Actual Result  
Nodes remain in pool and are not removed

**Comment by trinaths** [comment]
@marcriddle Please mail automation_toolchain_pm [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com) this issue with required CIS configuration and resource examples to reproduce at our end.

**Comment by marcriddle** [comment]
Sent an email to the above address with details, please let me know if any additional information is needed.

**Comment by trinaths** [comment]
Created [CONTCNTR-4083] for internal PD tracking. ETA ~ 2.14

**Comment by vklohiya** [comment]
Fixed with https://github.com/F5Networks/k8s-bigip-ctlr/pull/2855.  Fix will be available in 2.14.0 release.

**Comment by vklohiya** [comment]
Already fixed. Hence closing the issue.
