### ISSUE TITLE
What is the time interval for CIS to scan for changes in pods configured as pool members in BIGIP and push the change to BIGIP?

### ISSUE THREAD

**Issue by prabhatkarki** [F5Networks/k8s-bigip-ctlr#2984]
#### Title
What is the time interval for CIS to scan for changes in pods configured as pool members in BIGIP and push the change to BIGIP?
#### Description
What is the time interval for CIS to scan for changes in pods configured as pool members in BIGIP and push the change to BIGIP?
#### Actual Problem
If this time interval is configurable

#### Solution Proposed
Would like to be able to configure the time interval

**Comment by trinaths** [comment]
See `periodic-sync-interval` in CIS deployment options.
