### ISSUE TITLE
multicluster preview: improve CIS primary and secondary coordination

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2985]
#### Title

multicluster: use metadata in BIG-IP to determine which CIS should take over the configuration

#### Description

The goal of this RFE is to have a robust coordination between the primary and secondary CIS instances to avoid both of them trying to write the BIG-IP configuration. Although AS3 avoids writing two AS3 declarations concurrently, this might not be enough because the two CIS instances might have a different view of the clusters and this could produce configuration flapping.

Moreover, at present checking if the primary CIS is down is checked indirectly with the primaryClusterEndPoint which doesn´t guarantee whether CIS is not really up or down 

#### Actual Problem

In the preview code of the multiCluster feature the secondary CIS takes over when a TCP or a HTTP monitor fails. The primary CIS 1) doesn´t perform the same monitoring and 2) doesn't coordinate with the secondary CIS. Overall, both CIS might try to write the configuration in BIG-IP because they have a different view and create configuration flapping.

#### Solution Proposed 1

The proposed solution is to take a similar approach as AS3 and synchronize the primary and secondary CIS instances, **in a centralized manner in the BIG-IP** itself:

- AS3's lib/mutex.js provides exclusive access to write the configuration. 
- Implement a heartbeat from the primary CIS: with the mutex taken, write metadata with a timestamp from the primary CIS on owned partition
- check the heartbeat from the secondary and take over if heartbeat expired: In the secondary CIS using the AS3 mutex, check if the heartbeat has expired or not. If expired take over the configuration. The secondary doesn´t update the metadata. Using this model the primary always preempts the secondary CIS as it is right now.

Using a centralized approach as described above, both CIS have the same view and doesn´t require any additional configuration from the user. Currently we require to setup TCP/HTTP monitoring to "something" which might not provide the actual status of CIS' primary availability.

#### Solution Proposed 2

A simpler solution could be based in Primary CIS having a liveness probe endpoint, exposed with a Service Type NodePort which the Secondary CIS can check.

This liveness probe should be of type HTTP to guarantee that the CIS application is alive (in contrast a TCP liveness prove only requires the OS). CIS should also stop the keep-alives if there is any fatal error which inhibits the CIS instance to update the BIG-IP's config. This could be accessing the BIG-IP, the Kubernetes APIs or any other fatal error.

If this Primary liveness probe is also used as a regular Kubernetes liveness probe, it seems that the timers for Kubernetes should be longer than for CIS HA to avoid too-fast restart loops when restarts might not solve the issue. 

Please note that in order to implement this it has the problem that for each BIG-IP it is required a separate Primary CIS, hence the single primaryEndpoint parameter in the current global cm is not enough.
 
#### Alternatives

Non preemptive models could be used but in that case the concept of "primary" or "secondary" would not make sense.

**Comment by trinaths** [comment]
Created [CONTCNTR-4071] for internal tracking.

**Comment by alonsocamaro** [comment]
I have tried Solution #2 using the :8080/health endpoint for Prometheus and exposing the port as NodePort Service. I'm using an HTTP probe as I mentioned above. It is working fine.

It would be nice if this health endpoint returned an error when CIS is not operational, ie: when it cannot post to BIG-IP or access the Kubenetes APIs.

I find that the CIS failover events should be have NOTICE leve logs of the following events:
- healthcheck probe fails, while in Standby and while Active
- healthcheck probe max retry reached, while in Standby and while Active. That is, these two last health probe messages are printed every probeInterval while secondary is Active, like a continuous alarm.
- secondary CIS becoming active, even it might sound redundant
- when secondary CIS becomes standby again because healthcheck probe worked again

**Comment by alonsocamaro** [comment]
Additionally, the BIG-IPs should have an HA group where both CIS are health checked and if these fail then do a failover between the BIG-IPs.
