### ISSUE TITLE
Is possible to add a REST Agent

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2987]
Is there possible a add a REST Agent?

The AS3 agent syn the config to BIG-IP take long time, which mainly because the AS3 operation will execute the save sys and take long time.

The china dev team has development a CIS-C 

1. Deploy AS3 on K8S side
2. Use iControl REST transaction api

which 90% fast compare AS3 agent.

Is possible to add a REST Agent?

**Comment by trinaths** [comment]
Not sure about CIS-C. No support from CIS.
