### ISSUE TITLE
logging api server response

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2988]
CIS has ability to loging-as3 response, Shall we add a feature of api-server-response?  which use threshold to control logging api server's event, Simply like:

- API server has new events(like endpoint changed)
- CIS got this events
- CIS logging the event if the threshold is open

Which this is a request from customer, is possible to add this feature to new release?

**Comment by trinaths** [comment]
@kylinsoong please share example config and logs for clarity.

**Comment by trinaths** [comment]
Suggest checking /var/log/kube-apiserver.log - API Server, responsible for serving the API. No RFE for CIS. Closing this issue.
