### ISSUE TITLE
multicluster preview: "Starting  Node Informer" doesn´t include cluster name

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2997]
#### Setup Details
 CIS Version : 2.10     
 Build: f5networks/k8s-bigip-ctlr:latest       
 
#### Description  

When CIS starts seems that the informer for the local cluster is not shown properly always in log

In the primary CIS it is shown the following when running in cluster ocp2 and ocp1 is the cluster where secondary CIS is running

``` 
2023/07/25 11:13:53 [INFO] Starting  Node Informer
[...]
2023/07/25 11:13:53 [INFO] Starting ocp1 Node Informer
```

Checking the logs in the secondary CIS, it is shown the same:
```
2023/07/25 11:13:51 [INFO] Starting  Node Informer
[...]
2023/07/25 11:13:51 [INFO] Starting ocp1 Node Informer
```

#### Steps To Reproduce

Setup CIS in active-active mode, with only two clusters

#### Expected Result 

The cluster to be shown all the time

**Comment by trinaths** [comment]
Created [CONTCNTR-4090] for internal tracking.

**Comment by trinaths** [comment]
Dev PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/3033
dev PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/3032

Closed as complete
