### ISSUE TITLE
RFE: multicluster preview: improve log "No multi cluster config provided"

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2999]
#### Title

multicluster preview: improve log "No multi cluster config provided"

#### Description

This message is confusing because it suggests that no clusters were specified while it means that no clusters were specified in a multiClusterConfig. 

#### Solution Proposed
Please replace the message which matches the actual precondition:
```
        if multiClusterConfigs == nil || len(multiClusterConfigs) == 0 {
```

"There is no multiClusterConfig section or there are no clusters defined in it."

#### Alternatives

Actually, the section multiClusterConfig name is misleading because it really refers to external clusters (clusters without CIS) as the comment suggests.

Why not rename the multiClusterConfig section to externalClustersConfig?

It would indicate explicitly what it means.

Non HA CIS deployments would be specified in the highAvailabilityClusterConfigs where no secondary is specified.

**Comment by trinaths** [comment]
Created [CONTCNTR-4089] for internal tracking.
