### ISSUE TITLE
ExternalDNS Global Availability Mode not working

### ISSUE THREAD

**Issue by sorinboia** [F5Networks/k8s-bigip-ctlr#3004]
#### Setup Details
 CIS Version : 2.13.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S      
 Orchestration Version:       
 Pool Mode: Nodeport      

The described architecture for global availability in this link https://clouddocs.f5.com/containers/latest/userguide/crd/externaldns.html#:~:text=ExternalDNS%20Global%20Availability%20Mode%C2%B6.
If the Virtual Server/Pool of the wide IP in order location 0 goes down the wide IP is not choosing the next VS/pool and it will go the local BIND server due to the default fallback of "return to DNS".
This behavior is expected and described in this article https://my.f5.com/manage/s/article/K30100851 .
If order to make this work we need the pool fallback option exposed to the ExternalDNS CRD in order to configure it to "none"

**Comment by trinaths** [comment]
@sorinboia - Is CIS configured with CCCL or AS3 for EDNS ?

**Comment by lavanya-f5** [comment]
@sorinboia Fix will be part of 2.14 image. Feel free to tryout the devbuild shared below and provide feedback

Dev build for the issue: quay.io/f5networks/k8s-bigip-ctlr-devel:4c859a9c887ce75b84c4a11d1a16b3655fbb8714
Latest CRD schema : https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/customResourceDefinitions/customresourcedefinitions.yml
Example config: https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/ExternalDNS/external-dns-with-lbModeFallback
