### ISSUE TITLE
RFE: ConfigMap handling: automatic CIS restart when needed

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3048]
#### Title
ConfigMap handling: automatic CIS restart when needed

#### Description
At present it is not well documented when a change happens to a ConfigMap if this change will be updated on the fly by CIS. 

It shouldn't be needed to be documented: instead when CIS cannot apply a change on the fly should just kill itself and Kubenetes would re-start it without any further user intervention.

#### Actual Problem
- There is no clarity on what settings are updated on the fly and which are not, it is better not requiring that knowledge either. 

- Having to know when parameters are interpreted on the fly or not overloads the doc and the customers requiring them to know them more about internals of CIS.

#### Solution Proposed

Improve usability by:

- when a parameter is updated in the configmap and applied on the fly print this circumstance as INFO log level.
- when a parameter has been updated and cannot be applied on the fly, log this circumstance and kill the CIS POD.

This is a general behaviour easy to understand: if the customer updates the configmap the changes will be applied no matter what.

**Comment by trinaths** [comment]
@alonsocamaro Are new ConfigMaps and updates to them are not properly handled by CIS ? CIS listens to configMap informers for all the configMap events. Please elaborate the usecase properly.

**Comment by alonsocamaro** [comment]
It is not clear which fields can be updated on the fly and which can´t.

This RFE was an idea from me, not from the customer. Actually, the customer is requesting a different RFE so I would suggest to put this on hold for the time being. Likely we will close this one and I will submit a new RFE from the customer.

**Comment by alonsocamaro** [comment]
Closing in favor of https://github.com/F5Networks/k8s-bigip-ctlr/issues/3074 which comes from the customer. The customer cannot afford to have alarms when changing application level parameters.
