### ISSUE TITLE
multicluster preview: Route status not always updated in clusters where CIS is not Primary

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3052]
#### Setup Details
 Build: quay.io/f5networks/k8s-bigip-ctlr-devel:6acfa932091c518f87d3d71070501dd68fcebf33      
 BIGIP Version: Big IP 17
 AS3 Version: 3.45      
 Agent Mode: AS3
 Orchestration: OSCP      
 Orchestration Version: 4.12.22       
 Pool Mode: Cluster      
 Additional Setup details: OVN, multi-cluster 

#### Description

When triggering a Route Admission error, this can be seen in both clusters:

```
[cloud-user@ocp-provisioner example-tls-and-nontls]$ ../run-clusters.sh oc -n eng-caas-nginx-app1 get route
Switched to context "default/api-ocp1-f5-udf-com:6443/f5admin".
NAME         HOST/PORT                  PATH   SERVICES     PORT   TERMINATION     WILDCARD
nginx-app1   ExtendedValidationFailed          nginx-app1   8080   edge/Redirect   None
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
NAME         HOST/PORT                  PATH   SERVICES     PORT   TERMINATION     WILDCARD
nginx-app1   ExtendedValidationFailed          nginx-app1   8080   edge/Redirect   None
```

Then fixing the error, only clears the error in the cluster where CIS is Primary:

```
[cloud-user@ocp-provisioner base-config]$ ../run-clusters.sh oc -n eng-caas-nginx-app1 get route 
Switched to context "default/api-ocp1-f5-udf-com:6443/f5admin".
NAME         HOST/PORT                    PATH   SERVICES     PORT   TERMINATION     WILDCARD
nginx-app1   nginx-app1.apps.f5-udf.com          nginx-app1   8080   edge/Redirect   None
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
NAME         HOST/PORT                  PATH   SERVICES     PORT   TERMINATION     WILDCARD
nginx-app1   ExtendedValidationFailed          nginx-app1   8080   edge/Redirect   None
Switching back to initial context default/api-ocp2-f5-udf-com:6443/f5admin
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
```
Please note that for this reproduction I´m using the error described in https://github.com/F5Networks/k8s-bigip-ctlr/issues/3050, please note:

- the Admission error is caused by the global configmap problem, not by a problem in the routes themselves. Actually, the routes are never modified during this reproduction. 
- after fixing the issue, although the status in ocp2 reports to be not admitted the pool members from ocp2 are actually added. In other words, the status reported by the Route is bogus / is not updated.

Recreating the routes fixes the status 

```
[cloud-user@ocp-provisioner base-config]$ ../run-clusters.sh oc -n eng-caas-nginx-app1 delete route nginx-app1 
Switched to context "default/api-ocp1-f5-udf-com:6443/f5admin".
route.route.openshift.io "nginx-app1" deleted
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
route.route.openshift.io "nginx-app1" deleted

[cloud-user@ocp-provisioner example-tls-and-nontls]$ ../run-clusters.sh ./create-repro.sh 
Switched to context "default/api-ocp1-f5-udf-com:6443/f5admin".
route.route.openshift.io/nginx-app1 created
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
route.route.openshift.io/nginx-app1 created
 
[cloud-user@ocp-provisioner example-tls-and-nontls]$ ../run-clusters.sh oc -n eng-caas-nginx-app1 get route 
Switched to context "default/api-ocp1-f5-udf-com:6443/f5admin".
NAME         HOST/PORT                    PATH   SERVICES     PORT   TERMINATION     WILDCARD
nginx-app1   nginx-app1.apps.f5-udf.com          nginx-app1   8080   edge/Redirect   None
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
NAME         HOST/PORT                    PATH   SERVICES     PORT   TERMINATION     WILDCARD
nginx-app1   nginx-app1.apps.f5-udf.com          nginx-app1   8080   edge/Redirect   None
Switching back to initial context default/api-ocp2-f5-udf-com:6443/f5admin
Switched to context "default/api-ocp2-f5-udf-com:6443/f5admin".
```
 
#### Steps To Reproduce
1) trigger an Admission error, like https://github.com/F5Networks/k8s-bigip-ctlr/issues/3050
2) fix the admission
3) only one of the clusters will get the Route status update

#### Expected Result 

The status is updated consistently

#### Actual Result  

Seems the status is only updated in the non Primary clusters when there is an error.

**Comment by trinaths** [comment]
Created [CONTCNTR-4159] for internal tracking.

**Comment by vklohiya** [comment]
@alonsocamaro , It is as per the design. Only active cluster's route resource are considered as source of truth. Hence only routes from active clusters are updated with the status.
