### ISSUE TITLE
Enhance availability on scale-down and rollout updates of deployments

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3057]
#### Title
Enhance availability on scale-down and rollout updates of deployments

#### Description
When there is a scale down event or when there is a deployment update, existing POD members disappear. The BIG-IP and the Kubernetes status is never going to be in lock-step so it is expected that some requests will always be sent to disappearing Pods.

Running an ab -n 20000 -c 20 on an URL with 30 PODs behind, it can be seen ~2% of failed requests 

When using an irule to force a LB::reselect when LB_FAILED is triggered (this can be done only once from an irule) this is reduced to 0.5%. Being able to increment the retries further would reduce this to 0%.

#### Actual Problem

There are failures when sending requests to disappearing Pods when doing regular operations in a Kubernetes cluster (ie: scale-in, app re-deployment)

#### Solution Proposed

- support in the Policy CR the pool's reselect retries attribute.

- Please also include the related pool settings:
  - "Action On Service Down".
  - "Slow Ramp Time"

Although pool member reselection, action on service down and slow ramp time are per pool in BIG-IP, they are general enough to used in a per policy basis and avoid the use of annotations.

#### Additional information

The KB below suggest to use N-1 but I find that way to large in a Kubernetes environment as it would create a syn flood storm. Implementing a dynamic value which can be also be hinted by the customer and that adapts to large and small pool seems challenging. Maybe a static value would be more predictable and ultimately preferable to start with.

See https://my.f5.com/manage/s/article/K42101213 and https://my.f5.com/manage/s/article/K10386

**Comment by alonsocamaro** [comment]
All these settings are AS3 supported:

```
reselectTries (integer) | 0 | [0, 65535] | Maximum number of attempts to find a responsive member for a connection
-- | -- | -- | --
serviceDownAction (string) | “none” | “drop”, “none”, “reselect”, “reset” | Specifies connection handling when member is non-responsive
slowRampTime (integer) | 10 | [0, 900] | BIG-IP AS3 slowly the connection rate to a newly-active member slowly during this interval (seconds)
```

**Comment by trinaths** [comment]
Created [CONTCNTR-4139] for internal tracking.

**Comment by alonsocamaro** [comment]
Confirmed with customer that static parameter for ```#retries``` is what is desired
