### ISSUE TITLE
multicluster preview: when changing cluster ratios there are [F5RST: No pool member available]

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3058]
#### Setup Details      
 Build: quay.io/f5networks/k8s-bigip-ctlr-devel:6acfa932091c518f87d3d71070501dd68fcebf33
 BIGIP Version: Big IP 17
 AS3 Version: 3.45      
 Agent Mode: AS3       
 Orchestration: OSCP      
 Orchestration Version: OCP 4.12
 Pool Mode: Cluster    
 Additional Setup details: multicluster, OVN

#### Description  

In my testing with 2 OCP clusters, when changing ratios (no matter the original or updated values) there is 0.5 seconds when there are no pool members hence the BIG-IP sends the reset above (logged with tm.rstcause.pkt enable).

#### Steps To Reproduce
1) In one terminal run ab -n 20000 -c 20 
2) In another terminal apply the updated config map

#### Expected Result 

The pool members don´t change hence I would expect no disruption at all. I guess the underlying problem is in AS3.

#### Actual Result  

There is service disruption

**Comment by alonsocamaro** [comment]
This is the verification that while changing the ratio the pool members are not changed:

```
--- /tmp/k8s-bigip2-ctlr.request1.log	2023-08-29 03:35:29.477163602 -0400
+++ /tmp/k8s-bigip2-ctlr.request2.log	2023-08-29 03:35:43.996549982 -0400
@@ -216,15 +216,15 @@
           "records": [
             {
               "key": "guestbook-app1.apps.f5-udf.com",
-              "value": "guestbook_app1_3000_eng_caas_guestbook_app1,0.333;guestbook_app1_3000_eng_caas_guestbook_app1_ocp2,1.000"
+              "value": "guestbook_app1_3000_eng_caas_guestbook_app1,0.500;guestbook_app1_3000_eng_caas_guestbook_app1_ocp2,1.000"
             },
             {
               "key": "nginx-app1-passthrough.apps.f5-udf.com",
-              "value": "nginx_app1_8443_eng_caas_nginx_app1,0.333;nginx_app1_8443_eng_caas_nginx_app1_ocp2,1.000"
+              "value": "nginx_app1_8443_eng_caas_nginx_app1,0.500;nginx_app1_8443_eng_caas_nginx_app1_ocp2,1.000"
             },
             {
               "key": "nginx-app1.apps.f5-udf.com",
-              "value": "nginx_app1_8080_eng_caas_nginx_app1,0.333;nginx_app1_8080_eng_caas_nginx_app1_ocp2,1.000"
+              "value": "nginx_app1_8080_eng_caas_nginx_app1,0.500;nginx_app1_8080_eng_caas_nginx_app1_ocp2,1.000"
             }
           ]
         },
```

**Comment by alonsocamaro** [comment]
Please check the 3 reproductions available in my personal folder "CIS issue - ab while changing ratio".

These include at least the following files:

```
ab-while-ratio*.txt -> ab log with timestamps + configmap apply + CIS summary log
ab-while-ratio.pcap -> packet capture
k8s-bigip2-ctlr.log -> full CIS log
```

Please check the reproduction named ab-while-ratio-2 as it contains CIS logs with AS3DEBUG turned on

**Comment by trinaths** [comment]
@alonsocamaro Where are the files given above attached ?

**Comment by trinaths** [comment]
Created [CONTCNTR-4141]for internal tracking.

**Comment by vklohiya** [comment]
Created the issue in AS3 repo:  F5Networks/f5-appsvcs-extension#752

**Comment by vklohiya** [comment]
Closing this issue.
