### ISSUE TITLE
[Doc] RBAC manifest needs updating

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#3060]
#### Setup Details
(Doc issue)

#### Description  

Below page does not provide the latest rbac definition:
https://clouddocs.f5.com/containers/latest/userguide/cis-helm.html#installing-cis-manually

For instance, it doesn't list the lastest CRs like policies in the cis.f5.com api group.

Please update the documentation to reflect the RBAC needed for proper functionality of CIS.
It should use the latest ( I believe below is the one).
https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/rbac/clusterrole.yaml

#### Expected Result 

Documentation for helm chart rbac reflects the latest RBAC requirements to meet least privileges requirements for production K8s environments.

#### Actual Result  

Documentation is outdated so will lead to issues in getting proper resources.

**Comment by trinaths** [comment]
@tkam8 as per the docs, Its an example RBAC. User may update as per their usecase and choice of usage. 

> The example below shows the broadest supported permission set. You can narrow the permissions down to specific resources, namespaces, etc. to suit your needs. See the [Kubernetes RBAC documentation](https://kubernetes.io/docs/admin/authorization/rbac/) for more information.

**Comment by tkam8** [comment]
Please let me clarify. 

I understand it's an example, but the example should include the "Minimum" set of RBAC so that it works. Otherwise, there is much cause for confusion.
