### ISSUE TITLE
RFE: multicluster preview: provide stable pool names for ratio load balancing

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3061]
#### Title
multicluster preview: provide stable pool names

#### Description
At present the pools are named

```<service>_<namespace><_optional>```

where the <_optional suffix> is added when the CIS writting the configuration is in the same cluster as the pool.

If there are two clusters and the primary cis is active the pools are named:

```
guestbook_app1_3000_eng_caas_guestbook_app1
guestbook_app1_3000_eng_caas_guestbook_app1_ocp2
```

On the other hand if the secondary cis is active the pools are named:

```
guestbook_app1_3000_eng_caas_guestbook_app1_ocp1
guestbook_app1_3000_eng_caas_guestbook_app1
```

#### Actual Problem

This is a problem because scripts, automation and monitoring tools expect consistent naming.

#### Solution Proposed

Please use always the cluster name as suffix and if required to indicate who wrote the config please put it in the metadata/description of the pool.

**Comment by trinaths** [comment]
Created [CONTCNTR-4143] for internal tracking.
