### ISSUE TITLE
Provide CRD parameter to enable Connection Mirroring

### ISSUE THREAD

**Issue by adityoari** [F5Networks/k8s-bigip-ctlr#3062]
#### Title
Provide parameter to enable Connection Mirroring in TransportServer CR

#### Description
Expose a new parameter in TransportServer (and potentially also VirtualServer) to enable Connection Mirroring

#### Actual Problem
Customer is deploying CIS instances for their new OCP Clusters, and looking to use TransportServer CR to front their TCP apps becauso of its simple YAML format. Due to the nature of the app traffic, connection mirroring is mandatory, but it doesn't seem to be configurable in TransportServer CR.

#### Solution Proposed
Expose a new parameter in TransportServer CR to enable Connection Mirroring, which is already supported by the underlying Service_TCP class in AS3.

#### Alternatives
Switching to AS3 ConfigMap, which is harder for the customer's team to understand & craft.

#### Additional context
Customer is considering other Ingress solution/vendor if the AS3 ConfigMap is rejected by their ops team.

**Comment by trinaths** [comment]
@adityoari Please mail automation_toolchain_pm [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com) this issue with required CIS configuration and resource examples to review at our end.

**Comment by trinaths** [comment]
Created [CONTCNTR-4173] for internal tracking. ETA ~ 2.15
