### ISSUE TITLE
multicluster preview: ratio load balance with persistence issues

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3065]
#### Setup Details
 Build: quay.io/f5networks/k8s-bigip-ctlr-devel:6acfa932091c518f87d3d71070501dd68fcebf33
 BIGIP Version: Big IP 17
 AS3 Version: 3.45      
 Agent Mode: AS3
 Orchestration: OSCP      
 Orchestration Version: OCP 4.12      
 Pool Mode: Cluster 
 Additional Setup details: OVN, Multi-cluster with ratio mode

#### Description  
 
At present, when doing ratio load balancing with persistence it is required that the persistence profile has the toggle "Match Across Pools" enabled in the applied persistence profile. Otherwise the connections are first load balanced to cluster´s, pool then persistence applied in that pool only. Therefore the persistence is in a per-cluster basis.

When using persistence the expected behaviour is that client connections always go to the same server regarless in which cluster resides. Therefore this toggle is a must when using ratio load balancing and persistence.

Something analogous happens for multi-cluster in active-activemode with A/B routes, see https://github.com/F5Networks/k8s-bigip-ctlr/issues/3066. This means that when using A/B routes no matter what multi-cluster mode is used, it also requires Match across  pools.

**Comment by trinaths** [comment]
@alonsocamaro This issue still exists ?

**Comment by alonsocamaro** [comment]
This was fixed time ago.
