### ISSUE TITLE
CRD update for creating SCTP profile and SCTP Virtual server

### ISSUE THREAD

**Issue by luckymuk** [F5Networks/k8s-bigip-ctlr#3080]
#### Title
Title of the feature/enhancement request
SCTP support for CRDs
#### Description
A small overview of the feature/enhancement proposed
We are working with 5G control plane and data plane vendor to enable 5G in AWS. AWS doesn't support mobility protocols so f5 customer is using f5 to expose SCTP
#### Actual Problem
We want to use CRDs to configure our BIGIPs in cloud
#### Solution Proposed
need CRD to configure SCTP profile and SCTP VS
#### Alternatives
We are using Config maps at the moment.

**Comment by vklohiya** [comment]
@luckymuk , Transport server CR supports SCTP protocol. Here is the example of SCTP transport server: https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/TransportServer/sctp-transport-server.yaml

**Comment by trinaths** [comment]
CIS supports SCTP profile and VS in CRD mode. Closing this issue.
