### ISSUE TITLE
Update OVN-K8s documentation to be clear if static-routing-mode is true or false

### ISSUE THREAD

**Issue by jhennf5** [F5Networks/k8s-bigip-ctlr#3082]
#### Title
Update OVN-K8s documentation to be clear if static-routing-mode is true or false

#### Description

This is a request received via Support case 00468444.

1
https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-cluster.html
2
https://github.com/f5devcentral/f5-cis-docs/tree/main/user_guides/ovn-kubernetes-ha

1  
says CIS automatically creates static routes thereby assuming static-routing-mode is true
2
instructs to create routes manually thereby assuming static-routing-mode is false

Requestor would like this to be explicitly clear.

#### Actual Problem

Requestor did not understand that the automatic creation of static routes depends on a setting

#### Solution Proposed

Requestor would like this made explicitly clear in the documentation

#### Alternatives

Alternative solution would be some disclaimer in the doc stating its scope and usage (if it is not, for example, supposed to be a step-by-step deployment guide, or if there are requirements (even non-F5 cluster requirements) which are assumed)

**Comment by mdditt2000** [comment]
@jhennf5 its very clear  if static-routing-mode is true or false

Here is the options in CIS for static-routing-mode is true or false using OVN-K8S with OCP

```
 "--static-routing-mode=true",
"--orchestration-cni=ovn-k8s",
```
please make sure you have both CIS deployment statements

https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html?highlight=static%20routing%20mode#configuration-parameters

**Comment by trinaths** [comment]
@dramdayal - Any update on this ?

**Comment by trinaths** [comment]
Created [CONTCNTR-4172] to track documentation improvement.
