### ISSUE TITLE
RFE: Implement annotation equivalent to haproxy.router.openshift.io/pod-concurrent-connections 

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3086]
#### Title

Implement annotation equivalent to haproxy.router.openshift.io/pod-concurrent-connections 

#### Description

Customer wants to have this functionality at Route level.

The functionality is implemented with the following AS3 PoolMember attribute: connectionLimit. That is, the annotation value will need to be applied to all pool members.

#### Actual Problem

This functionality avoids backends' overload and it has been widely used in BIG-IP.  Implementing it allows customers to switch from OpenShift's default HA-Proxy to BIG-IP.

#### Solution Proposed

Create an annotation at Route level. Ideally, this annotation should be available to equivalent resource types for functionality: VirtualServer and Ingress but also TransportServer.

#### Additional context

Implementing this at Route level means that if a service is reused between two Routes the connection limit value might be overridden. The customer is fine with this behavior. The customer prefers to have this at Route level instead of Service level. 

If two Routes with different connection limits share the same service, the customer can always create a separated Service to avoid the limits to be overridden.

**Comment by trinaths** [comment]
Created [CONTCNTR-4255] for internal tracking.
