### ISSUE TITLE
[Migration to CRD] Validation with two CIS in different manage modes

### ISSUE THREAD

**Issue by tkam8** [F5Networks/k8s-bigip-ctlr#3088]
#### Title
[Migration to CRD] Validation with two CIS in different manage modes

#### Description
Need engineering to validate that two CIS running in different modes (as3-configmap and custom-resource-mode) in the same cluster, pointing to the same BIG-IP will work.

#### Actual Problem
I need to slowly migrate from AS3 configmaps to CRDs. Today AS3 configmap and crd modes cannot be enabled at the same time on the same CIS. 

#### Solution Proposed
Confirmation that there are no issues when running two CIS in different modes in the same cluster pointing to the same BIG-IP

#### Alternatives
Need to build another BIG-IP cluster to migrate (operational burden)

#### Additional context
I understand that when custom-resource-mode=true, ConfigMaps, Routes, and Ingress are not processed by CIS. Need to just verify nothing else will conflict.

**Comment by trinaths** [comment]
> Need engineering to validate that two CIS running in different modes (as3-configmap and custom-resource-mode) in the same cluster, pointing to the same BIG-IP will work.

It should work. Configure CIS monitoring AS3 ConfigMap and CIS monitoring CRD to same BIG-IP with different partitions. 

Please let know if any issues.
