### ISSUE TITLE
RFE: liveness probes feedback

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3089]
#### Title
RFE: liveness probes feedback

#### Description

We would like that you reconsider:

1. Customer remarked that liveness probes are meant to restart the containers, not to check if the containers are ready to accept traffic. 

Usually the probes used in both readiness and liveness  probes are the same but it might not be always the case. Hence:

- we ask to replace the liveness probes by readiness probes (and replace the keywords in the configs)

2. We previously understood that there RFE for liveness probes came from a different customer and hence it required to have it by default. Given that it is not the case we strongly encourage you to:

- make none the default value because readiness/liveness probes are a) a change in behaviour from all other previous CIS implementations and b) it might cause high load in customer systems. This customer, Kostas and me also think this is the most sensible approach. It is better to amend this now than further later on.

#### Solution Proposed

- change the behaviour to none ASAP
- replace liveness-probes to readiness-probes later on

**Comment by alonsocamaro** [comment]
Note that Kubernete's NodePort also makes use of Readyness to send traffic to a POD or not:

https://kubernetes.io/docs/concepts/services-networking/service/

`For a node port Service, Kubernetes additionally allocates a port (TCP, UDP or SCTP to match the protocol of the Service). Every node in the cluster configures itself to listen on that assigned port and to forward traffic to one of the ready endpoints associated with that Service. You'll be able to contact the type: NodePort Service, from outside the cluster, by connecting to any node using the appropriate protocol (for example: TCP), and the appropriate port (as assigned to that Service).`

**Comment by trinaths** [comment]
Created [CONTCNTR-4256] for internal tracking.
