### ISSUE TITLE
[DOC] wrong example in https://clouddocs.f5.com/containers/latest/userguide/crd/externaldns.html

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3092]
#### Description  

The example in [Single Health Monitor](https://clouddocs.f5.com/containers/latest/userguide/crd/externaldns.html?highlight=gslb#single-health-monitor) is for the VirtualServer CRD and not for the ExternalDNS CRD which is the expected one.

**Comment by trinaths** [comment]
Created [CONTCNTR-4309] for internal tracking

**Comment by trinaths** [comment]
Updated. Docs published.
