### ISSUE TITLE
[Document Improvement Request] OpenShift 4.12 and F5 BIG-IP CIS User-Guide using OVN-Kubernetes with No Tunnels

### ISSUE THREAD

**Issue by jyeung-F5** [F5Networks/k8s-bigip-ctlr#3097]
**Problem Description**
This ticket is an improvement request for the following doc based on the received feedbacks from partners and customers:
OpenShift 4.12 and F5 BIG-IP Container Ingress Services (CIS) User-Guide for Standalone BIG-IP using OVN-Kubernetes iCNI with NO Tunnels
https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-standalone.html

**Expected Result**
Users can successfully deploy CIS in OpenShift by simply following the doc.

**Proposed Solution**
Here are the suggestions:

1) Please start w/ a pre-requisite section which clearly states the following:

- AS3 is installed on the BIG-IP and provide the AS3 installation link

- specify which CIS version is required for this document, for example, CIS v2.13 and later are required.  It’s because, for example, “static-routing-mode” is not available until v2.13.

- apply the latest CRD schema and provide the reference yaml, for example, oc apply -f https://raw.githubusercontent.com/F5Networks/k8s-bigip-ctlr/master/docs/config_examples/customResourceDefinitions/stable/v2.12.0/customresourcedefinitions.yml

*Note: please include the ref link so users understand why/when/what need to update from CRD perspective such as this ref link: https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResourceDefinitions/crd_update.md

- cafe namespace is created and provide the reference repo

- applications: tea, coffee, mocha are deployed in the cafe namespace and provide the reference repo

2) In step 1, please specify the change only applies to 4.11 not 4.12 as OVN-Kubernetes is the default in 4.12.  

3) In step 3,
- please add explanation/short description of “static-routing-mode=true” and “orchestration-cni=ovn-k8s” as well under “Add the following parameters to the CIS deployment”
- there is a typo in the shown CIS deployment example, should be “—namespace=cafe”
- we should also mention it is no longer required to create a partition 1st on the BIG-IP 

4) In step 4, please update the screenshot because it does not match the CIS sample config in step 3 - the screenshot shows /common partition which requires “shared-static-routes=true”.  

*Note: If decided to update the CIS sample config in step 3 instead to match the existing /common partition screenshot, we should then ensure the CIS version requirement in the pre-req section is correct because “shared-static-routes=true” is not available until v2.14.  

5) This is my observations in my testings:
	—>for newly deployed partition (never deployed before on the BIG-IP), partition won’t get created until OpenShift Routes are created
	—>for a partition that had created before (even it is no longer existed on the BIG-IP), partition will get create before OpenShift Routes are created

Based on above, suggest to do verification after all is configured (swap the order of step 4 and step 5).  In other words, "Creating OpenShift Routes for cafe.example.com" first, then "Verify BIG-IP Static Routes".  Or even better is to move "Verify BIG-IP static routes" to the validation section.

6) In validation step 4, we should make a note to remind the users DNS is required/setup in our example to resolve the vip.

7) Please provide an Operator version for this same doc.  It can be a separate doc or include in the same doc, so that users can also deploy successfully using Operator, and, we should provide a sample CIS config as well.

8) Please also improve the HA version with all the suggestions above (1 to 7): https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-cluster.html

Please reach out if there are any questions.  Thank you for your support.

**Comment by trinaths** [comment]
Created [CONTCNTR-4291] for internal tracking.

**Comment by trinaths** [comment]
Updated. Docs published.

**Comment by jyeung-F5** [comment]
@trinaths 

Hi, 
It doesn't look like the doc is updated accordingly as below are still missing per the ticket:

1. "Please start w/ a pre-requisite section which clearly states the following:...." - there is still no pre-requisite section to note all those info.
3. "we should also mention it is no longer required to create a partition 1st on the BIG-IP" - this is not mentioned in the doc still.
4. I see you added comments about “shared-static-routes=true” to match the screenshot.  If that's the case, we should mention “shared-static-routes=true” is available in v2.14 and later.
6. "In validation step 4, we should make a note to remind the users DNS is required/setup in our example to resolve the vip." - Please add this.
7. "Please provide an Operator version for this same doc. It can be a separate doc or include in the same doc, so that users can also deploy successfully using Operator, and, we should provide a sample CIS config as well." - Did not see this yet still.

Please note these suggestions are based on the feedback from our customers and partners.  The goal to provide a document with no assumptions so that anyone can deploy CIS in OpenShift by simply following the doc.  If you have any questions, please let me know.  Thanks.
