### ISSUE TITLE
RFE: improve usability by making logs more user friendly

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3118]
#### Title
RFE: make logs more user friendly / usable

#### Description

Please consider the following suggestions to improve the logs' user friendliness. These suggestions come from me as well as from the customer I´ve been working with lately.

#### Actual Problem

- INFO level logs don´t always contain the information required, customers should be able to know easily that manifests or events are managed by CIS and if they are applied successfully or not.
- Some INFO level logs are clearly user friendly and should be considered DEBUG
- When an error occurs, and it is needed detailed information to troubleshoot it is, required to restart CIS to increase the DEBUG level.

See below specific examples & proposal

Many thanks

#### Solution Proposed

**A**- Every time there is an user or Kubernetes action, ie: create, update or delete a manifest there should be the following:

   1. A simple, user readable, message at INFO level indicating that CIS is taking care of the action, something alike:

    ```<cluster name> requested <action> in <resource type> <namespace>/<manifest name>```

  for example:

    ```ocp1 requested CREATE in Route test/web```
    ```ocp1 requested UPDATE in Service test/web-pool```

  2.  A corresponding message with INFO level indicating if the action has completed successfully or not:
  
    ```<cluster name> requested <action> in <resource type> <namespace>/<manifest name> <result><: optional error message>```

  for example:

    ```ocp1 requested CREATE in Route test/web resulted in SUCCESS```
    ```ocp1 requested UPDATE in Service test/web-pool resulted in FAILURE```

  Please consider that if the requests have some sort of CIS identifier, this could be prepended (ie: ```<transaction ID>``` to find the matching lines. Please also consider the capitalization of the key information action and result.

   if both item i and ii are excessive, at least item ii should be shown in the logs

**B** - I guess that some errors will not be discovered until the AS3 manifest will be submitted. I propose that:

  1. When a set of events trigger the creation of an updated AS3 manifest, a user friendly log message at INFO level is shown, for example:
  
  ```AS3: creating a new AS3 manifest for the next Kubernetes events```

  Then the messages mentioned at the top would follow.
  
  2. When the AS3 declaration is submitted a user readable log message shows the outcome of the AS3 submission, for example:

  ```AS3: posted AS3 manifest resulted in SUCCESS``` // with INFO log level

  ```AS3: posted AS3 manifest resulted in ERROR: <error message>``` // with ERROR log level

  Overall it could look as follows:

```
AS3: creating a new AS3 manifest for the next Kubernetes events
ocp1 requested CREATE in Route test/web
ocp1 requested UPDATE in Service test/web-pool
ocp1 requested CREATE in Route test/web resulted in SUCCESS
ocp1 requested UPDATE in Service test/web-pool resulted in SUCCESS
AS3: posted AS3 manifest resulted in SUCCESS
```
  I guess that if the one of the requested changes don´t success, then I understand that no AS3 declaration is submitted and something alike the following could be shown:

```
AS3: previous failures aborted posting an AS3 manifest
```
**C** -  The following log should not be ERROR but NOTICE level as it might be intentional to temporarily remove a Service from a Route or to do not have that Service in a given cluster.

```2023/10/16 14:20:50 [ERROR] [MultiCluster] Service {guestbook-app1 ocp2 eng-caas-guestbook-app1} not found! from cluster: ocp2```

In general I find that ERROR messages should be shown when there is a CIS problem which it inhibits working, ie: accessing an API or CIS HA not working properly, but not when the failure comes for the regular working of Kubernetes or AS3.

**D**-   if there is an AS3 error, then the AS3 declaration is dumped (like AS3DEBUG) regardless of the debug level. This way an issue can be troubleshooted without having to restart CIS

**E** -  include always cluster name in all messages, when not running in multi-cluster mode, cluster name could be a generic name, ie: "local"

**F** -  There are a set of messages with the ```[INFO] Text:``` token which should be changed to DEBUG level, they are not user readable

```
2023/10/16 13:08:09 [INFO] Text: '{"kind":"tm:sys:syscollectionstate","selfLink":"https://localhost/mgmt/tm/sys?ver=17.1.0.1","items":[{"reference":{"link":"https://localhost/mgmt/tm/sys/application?ver=17.1.0.1"
}},{"reference":{"link":"https://localhost/mgmt/tm/sys/crypto?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/daemon-log-settings?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/t
m/sys/diags?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/disk?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/dynad?ver=17.1.0.1"}},{"reference":{"link":"https://localho
st/mgmt/tm/sys/ecm?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/file?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/fpga?ver=17.1.0.1"}},{"reference":{"link":"https://l
ocalhost/mgmt/tm/sys/icall?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/ipfix?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/log-config?ver=17.1.0.1"}},{"reference":{"l
ink":"https://localhost/mgmt/tm/sys/pfman?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/sflow?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/software?ver=17.1.0.1"}},{"r
eference":{"link":"https://localhost/mgmt/tm/sys/turboflex?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/url-db?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/aom?ver=17
.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/autoscale-group?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/cluster?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mg
mt/tm/sys/config?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/core?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/daemon-ha?ver=17.1.0.1"}},{"reference":{"link":"https:
//localhost/mgmt/tm/sys/datastor?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/db?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/dns?ver=17.1.0.1"}},{"reference":{"link"
:"https://localhost/mgmt/tm/sys/feature-module?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/folder?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/global-settings?ver=17
.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/ha-group?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/httpd?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys
/iapp-restricted-key?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/icontrol-soap?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/internal-proxy?ver=17.1.0.1"}},{"referenc
e":{"link":"https://localhost/mgmt/tm/sys/log-rotate?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/management-dhcp?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/management-ip?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/management-ovsdb?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/management-proxy-config?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/management-route?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/ntp?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/outbound-smtp?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/provision?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/scriptd?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/service?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/smtp-server?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/snmp?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/sshd?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/state-mirroring?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/syslog?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/telemd?ver=17.1.0.1"}},{"reference":{"link":"https://localhost/mgmt/tm/sys/ucs?ver=17.1.0.1"}}]}'

2023/10/16 13:08:09 [INFO] Enqueueing Namespace: &Namespace{ObjectMeta:{cis-mc-onetier    a37b8e45-f02c-4b4c-b1a7-a286feed4dcd 10160835 0 2023-10-16 13:07:55 +0000 UTC <nil> <nil> map[environment:test kubernetes.io/metadata.name:cis-mc-onetier pod-security.kubernetes.io/audit:privileged pod-security.kubernetes.io/audit-version:v1.24 pod-security.kubernetes.io/warn:privileged pod-security.kubernetes.io/warn-version:v1.24] map[openshift.io/sa.scc.mcs:s0:c29,c24 openshift.io/sa.scc.supplemental-groups:1000860000/10000 openshift.io/sa.scc.uid-range:1000860000/10000] [] []  [{kubectl-create Update v1 2023-10-16 13:07:55 +0000 UTC FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:kubernetes.io/metadata.name":{}}}}} {cluster-policy-controller Update v1 2023-10-16 13:07:57 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:openshift.io/sa.scc.mcs":{},"f:openshift.io/sa.scc.supplemental-groups":{},"f:openshift.io/sa.scc.uid-range":{}},"f:labels":{"f:pod-security.kubernetes.io/audit":{},"f:pod-security.kubernetes.io/audit-version":{},"f:pod-security.kubernetes.io/warn":{},"f:pod-security.kubernetes.io/warn-version":{}}}}} {kubectl-label Update v1 2023-10-16 13:08:03 +0000 UTC FieldsV1 {"f:metadata":{"f:labels":{"f:environment":{}}}}}]},Spec:NamespaceSpec{Finalizers:[kubernetes],},Status:NamespaceStatus{Phase:Active,Conditions:[]NamespaceCondition{},},}

2023/10/16 13:08:09 [INFO] Text: '{"kind":"tm:net:fdb:tunnel:records:recordscollectionstate","selfLink":"https://localhost/mgmt/tm/net/fdb/tunnel/~Common~http-tunnel/records?ver=17.1.0.1","items":[]}'
2023/10/16 13:08:09 [INFO] Text: '{"kind":"tm:net:fdb:tunnel:records:recordscollectionstate","selfLink":"https://localhost/mgmt/tm/net/fdb/tunnel/~Common~socks-tunnel/records?ver=17.1.0.1","items":[]}'

2023/10/16 13:08:40 [INFO] Text: '{"kind":"tm:auth:partition:partitionstate","name":"Common","fullPath":"Common","generation":1,"selfLink":"https://localhost/mgmt/tm/auth/partition/Common?ver=17.1.0.1","defaultRouteDomain":0,"description":"Updated by AS3 at Fri, 13 Oct 2023 14:27:49 GMT"}'
```

**G** -  Additionally, the next ones are additionally not expected when using OVN in routed mode

2023/10/16 13:08:40 [INFO] Text: '{"kind":"tm:auth:partition:partitionstate","name":"Common","fullPath":"Common","generation":1,"selfLink":"https://localhost/mgmt/tm/auth/partition/Common?ver=17.1.0.1","defaultRouteDomain":0,"description":"Updated by AS3 at Fri, 13 Oct 2023 14:27:49 GMT"}'

**Comment by alonsocamaro** [comment]
After conversation with Vivek, having something simple alike the following, easily readable without any unwanted messages at INFO level would be fantastic:

```
INFO: ocp1 requested CREATE in Route test/web
INFO: ocp1 requested UPDATE in Service Endpoint test/web-pool
ERROR: AS3: posted AS3 manifest resulted in FAILURE: <error string from AS3 or API endpoint>
ocp1 requested DELETE in Service test/web-pool
INFO: AS3 posted AS3 manifest resulted in SUCCESS
```

Where the logs should be simple and and can be parsed in a easy/deterministic way

**Comment by alonsocamaro** [comment]
Further suggestions:

- The following should be INFO level rather than DEBUG:

```
2023/10/26 09:11:21 [DEBUG] [MultiCluster] CIS running with multi-cluster-mode: secondary
2023/10/26 09:11:23 [DEBUG] [MultiCluster] Added namespace label informer: environment=test,environment=test
2023/10/26 09:11:23 [DEBUG] [MultiCluster] Cluster ratios: ocp2:1 ocp1:1
```

btw, why environment=test is shown twice?

**Comment by trinaths** [comment]
Created [CONTCNTR-4296] for internal tracking.

**Comment by vklohiya** [comment]
> Added namespace label informer

environment=test is shown twice, As you are using same label for controller monitored namespacelabel and routegroup label.
