### ISSUE TITLE
 RFE: improve usability by changing the log level without CIS restart

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3121]
#### Title
 RFE: improve usability by changing the log level without CIS restart

#### Description

This comes from item D in https://github.com/F5Networks/k8s-bigip-ctlr/issues/3118

As per conversation with Vivek, the log level cannot be changed on the fly by means of having a log level toggle in the Global ConfigMap which would be ideal.

Sometimes it is desired to troubleshoot an AS3 problem (using AS3DEBUG) without CIS restart, keeping the state of the problem. Vivek proposes alternatively to have a toggle in the ConfigMap to deal with this specific circumstance.

I think this could be useful but please consider https://github.com/F5Networks/k8s-bigip-ctlr/issues/3118  higher priority

**Comment by trinaths** [comment]
@alonsocamaro - We are considering this feature for CIS 3.x supporting BIG-IP Next.
