### ISSUE TITLE
IngressLink spec.host

### ISSUE THREAD

**Issue by liuqi-sun** [F5Networks/k8s-bigip-ctlr#3123]
cafe.example.com host is registered through ingresslink in the user wizard. What should I do if I want to register another book.example.com host?
![企业微信截图_16977039307651](https://github.com/F5Networks/k8s-bigip-ctlr/assets/48784730/f6e4a8e7-23a0-4cdd-88ad-d8ffd1cefbe4)

**Comment by trinaths** [comment]
@liuqi-sun for the same VS Address ?

**Comment by trinaths** [comment]
@liuqi-sun Please share requested info.

**Comment by trinaths** [comment]
Closing this issue. Idle for a longer time.
