### ISSUE TITLE
multi-cluster: incorrect pool name running active-active mode

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3129]
#### Setup Details
 CIS Version : 2.X      
 Build: quay.io/f5networks/k8s-bigip-ctlr-devel:6f02e742c6f7e118f6576fda6d3256cf2afa0ed6

#### Description  

When  using active-active load balancing the pool names contain the name of the first cluster. When using active-active there is a single pool for all clusters though.

#### Steps To Reproduce

Configure CIS in active-active mode

#### Actual Result  

The pool name is something alike the following:

```
nginx_app1_8443_mc_onetier_eng_caas_nginx_app1_ocp1
```

#### Expected Result 

Ideally it should contain the name of all clusters, if not considered to be appropriate, then an "_all" suffix or no cluster suffix should be used.

**Comment by trinaths** [comment]
Created [CONTCNTR-4301] for internal tracking.
