### ISSUE TITLE
DOC: typos in examples of virtual-server.f5.com/health

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3132]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       

#### Description  

As far as I know the following annotation in https://clouddocs.f5.com/containers/latest/userguide/routes.html is not correct:

```
 annotations:
     virtual-server.f5.com/health: |
        [
           {
              "send": "HTTP GET /pyapps",
              "interval": 5,
              "timeout": 16,
              "type": "https",
           }
        ]
```

More precisely, the HTTP should not be in the send string AFAIK.

This is also present in many files of the git repository. Please run the next command:

```
find . -type f -exec grep "HTTP GET" {} \; -print
```

google also finds other references using the next search:

```
site:clouddocs.f5.com virtual-server.f5.com/health
```

It seems that the HTTP string was needed in the past but it is not any more but I don´t see it reflected in the documentation.

**Comment by trinaths** [comment]
Created [CONTCNTR-4302] for internal tracking.

**Comment by trinaths** [comment]
No updates required. Health monitor works well as per the example.
