### ISSUE TITLE
Latest CIS - 2.14 not supporting AS3 - 3.46.1

### ISSUE THREAD

**Issue by surendarmsk1** [F5Networks/k8s-bigip-ctlr#3135]
CIS - Latest version - 2.14
AS3 version [Long Term Support] - 3.46.1; [EOL - 12-Sep-2024]
 
As our current AS3 is out-of support, we want to upgrade our AS3 to 3.46.1 however 3.46.1 is not yet released in latest CIS version 2.14. 

CIS-2.14 is having AS3 support only till 3.45 which is already EndofSupport. So with this we cannot proceed on CIS upgrade since even-though we upgrade CIS it doesn't give the LTS AS3 version - 3.46.1. Can we know on which CIS version AS3 LTS support v-3.46.1 will be released?

please clarify

**Comment by trinaths** [comment]
2.15 will compatible with AS3 3.48

**Comment by surendarmsk1** [comment]
Thanks for the response, will wait for the release
