### ISSUE TITLE
DOC: suggestions to OpenShift documentation

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3139]
#### Title
DOC: re-arrange CNI section for OpenShift

#### Description 

At time of this writing we provide the following arrangement

<img width="402" alt="Screenshot 2023-11-07 at 09 34 06" src="https://github.com/F5Networks/k8s-bigip-ctlr/assets/16683733/c846933d-8d8f-41d2-aed0-02f0f3685252">

and it is confusing for customers because

- it suggests only the specified versions are supported
- there is no recommendation on which CNI/configuration to use
- there is no mention to OpenShiftSDN
- it mixes service configuration and CNI configuration

#### Solution Proposed

Create the following sections:

- CNI configuration

  - Overview of the CNIs indicating that it is only required if using ClusterIP mode. Making strong recommendation to use OVNKubernetes in routed mode, indicating that OpenShiftSDN is being deprecated pointing to official documentation https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-future-deprecation-sdn and indicating that OpenShift provides a path to migrate from OpenShiftSDN to OVNKubernetes https://docs.openshift.com/container-platform/4.14/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html 
  
     With respect of versioning information we could state something like:

     - OVNKubernetes in routed mode has been validated since version 4.x
     - OVNKubernetes in hybrid mode has been validated from version 4.y (to version 4.z if no longer validated
     - OpenShiftSDN has veen validated since version a.b 
  
  - OVNKubernetes in routed mode indicating the CIS parameters required and vlan/self-ip configuration and explicitly indicating that no further manual configuration is needed in the BIG-IPs when OpenShift nodes are added/removed and that CIS will take charge of dynamically modifying the BIG-IP configuration .
  
  - OVNKubernetes in hybrid mode with a **NOTICE** that it is is no longer recommended, and that it's configuration is the same as OpenShiftSDN. Then indicating cluster network configuration for hybrid networking.
  
  - OpenShiftSDN, making a remark that it will be deprecated and it is not the recommended CNI because it requires manual configuration in the BIG-IPs when OpenShift nodes are added/removed. Then configuration details in the BIG-IP.
  
- CIS installation section as it is now

- Using CIS with the OpenShift Route resource
   
   Include in this section the subsection [Sharding the OpenShift Default Ingress Controller](https://clouddocs.f5.com/containers/latest/userguide/openshift/#sharding-the-openshift-default-ingress-controller) and include a link to OpenShift's official documentation.

- Using the CIS with F5 CRDs

**Comment by trinaths** [comment]
Created [CONTCNTR-4307] for internal tracking.

**Comment by trinaths** [comment]
This documentation has evolved based on the UX. As we move to support OVNK8S CNI, no guidance to OpenShift SDN is required. Closing this issue.
