### ISSUE TITLE
Using CRD VirtualServer with multiple domains overrides pools

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3145]
#### Setup Details
 CIS Version : 2.X      
 Build: quay.io/f5networks/k8s-bigip-ctlr-devel:a5904e200bf11402611448289d6c864fc7427504
 Agent Mode: AS3       
 Orchestration: OSCP      
 Orchestration Version:4.12       
 Pool Mode: Cluster      
 Additional Setup details: OVN, single cluster

#### Description  
 
Applying the following VirtualServer works fine:

```
[cloud-user@ocp-provisioner routes-bigip]$ oc -n istio-system get vs
NAME                    HOST               TLSPROFILENAME      HTTPTRAFFIC   IPADDRESS     IPAMLABEL   IPAMVSADDRESS   STATUS   AGE
virtualserver-route-c   www.sc-istio.com   reencrypt-tls-www                 10.1.10.105               10.1.10.105     Ok       2m57s
```

Then adding VirtualServer using a different FQDN

```
[cloud-user@ocp-provisioner routes-bigip]$ oc -n istio-system get vs
NAME                    HOST                   TLSPROFILENAME          HTTPTRAFFIC   IPADDRESS     IPAMLABEL   IPAMVSADDRESS   STATUS   AGE
virtualserver-route-c   www.sc-istio.com       reencrypt-tls-www                     10.1.10.105               10.1.10.105     Ok       4m1s
virtualserver-route-d   account.sc-istio.com   reencrypt-tls-account                 10.1.10.105               10.1.10.105     Ok       10s
```

overrides the pool for virtualserver-route-c, see the next screenshot

<img width="515" alt="Screenshot 2023-11-13 at 13 00 21" src="https://github.com/F5Networks/k8s-bigip-ctlr/assets/16683733/3482a624-62ec-469a-b592-0e33ed52c517">

No errors are shown in CIS log 8attached) 

#### Steps To Reproduce
1) Create route-c
2) Create route-d

#### Expected Result 

Both routes should work concurrently using the same IP

#### Actual Result  

The first route is overriden

#### Diagnostic Information

CIS log, manifests used

[cis.log](https://github.com/F5Networks/k8s-bigip-ctlr/files/13334607/cis.log)
[reencrypt-tls-www.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13334619/reencrypt-tls-www.yaml.txt)
[reencrypt-tls-account.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13334620/reencrypt-tls-account.yaml.txt)
[virtualserver-route-d.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13334621/virtualserver-route-d.yaml.txt)
[virtualserver-route-c.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13334622/virtualserver-route-c.yaml.txt)

**Comment by lavanya-f5** [comment]
@alonsocamaro Can you try configuring hostgroup(merge different virtuals with different hostname but same vip or ipamlabel as single virtual onto bigip)option as described https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/customResource/VirtualServer/virtual-with-hostGroup

example https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/VirtualServer/virtual-with-hostGroup/virtual-with-hostGroup.yaml

**Comment by alonsocamaro** [comment]
it was a miss-configuration on my side. I was using using hostgroup but somehow i was triggering another problem beforehand (default SNI SSL profile) which somehow I was not realizing.

**Comment by alonsocamaro** [comment]
it was a miss-configuration on my side. I was using using hostgroup but somehow i was triggering another problem beforehand (default SNI SSL profile) which somehow I was not realizing.
