### ISSUE TITLE
[DOC] typo in https://clouddocs.f5.com/containers/latest/userguide/multicluster/

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3149]
#### Description  
  
Please fix "Virtutal" in the following sentence: Virutal Server Pool with Multi-ClusterServices[¶](https://clouddocs.f5.com/containers/latest/userguide/multicluster/#virutal-server-pool-with-multi-clusterservices)

**Comment by trinaths** [comment]
Updated. Docs published.
