### ISSUE TITLE
[DOC] Improve multicluster documentation

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3150]
#### Title

[DOC] Improve multicluster documentation

#### Description

These are suggestions to improve https://clouddocs.f5.com/containers/latest/userguide/multicluster/

- The example below the sentence "Below is the sample multi-cluster config in an extended global ConfigMap." includes the section extendedRouteSpec which onluy applies to NextGenRoutes

  The same applies to exeample after the sentences:
  
   - "Below is an example of multi-cluster configs, with HA, in an extended global ConfigMap."
   - "Below is the sample multi-cluster configs, with HA and ratio, in an extended global ConfigMap."
   - "Below is the sample Multi-Cluster Configs with standalone CIS and cluster AdminState in Extended Global ConfigMap."
   
   such additions should be indicated in the following section: OpenShift Routes with multi-cluster[¶](https://clouddocs.f5.com/containers/latest/userguide/multicluster/#openshift-routes-with-multi-cluster) indicating that equivalent section is not required when using CRDs
   
There should be a mention on the need of specifying ```--route-spec-configmap=```

There should be a section afterwards indicating for configuring with CRDs where it should be specified that the multicluster config is indicated with

```--extended-spec-configmap=```

- AFAIK the section Static Routing Mode[¶](https://clouddocs.f5.com/containers/latest/userguide/multicluster/#static-routing-mode) is not exclusive of multi-cluster and should probably be eliminated

- The sections
   -  CIS Deployment Parameter[¶](https://clouddocs.f5.com/containers/latest/userguide/multicluster/#id5) and
   - CIS Deployment Parameter[¶](https://clouddocs.f5.com/containers/latest/userguide/multicluster/#id10)
   
   are confusing and it is not clear what it is being indicated

**Comment by alonsocamaro** [comment]
The examples assume that NextGenRoutes are used, please indicate in the README file that the section extendedRouteSpec section is ignored when using CRDs and should just be deleted in that case

**Comment by trinaths** [comment]
Created [CONTCNTR-4344] for internal tracking.

**Comment by trinaths** [comment]
Closing this issue.
