### ISSUE TITLE
Infoblox IPAM assigns the same IP to each of the two different clusters.

### ISSUE THREAD

**Issue by ejes3409** [F5Networks/k8s-bigip-ctlr#3160]
#### Title
Infoblox IPAM assigns the same IP to each of the two different clusters.

#### Description
1. There are two different clusters.
2. Two different clusters each have F5 CIS installed and are linked to the same F5 BIG-IP Appliance LTM.
3. F5 CIS in two different clusters are connected to the same Infoblox IPAM and have the same Label and CIDR.
4. In two different clusters, set the LB Type as follows.
-- Service Name is the same. (ex: nginx-svc)
-- Infoblox IPAM Label is the same.

In the above situation, what we want is for two different clusters to be assigned different VIPs and set up LB with different virtual addresses on the F5 BIG-IP Appliance.

#### Actual Problem
If you set it as described in the description,

Each cluster is assigned the same IP, so one VS is created in the F5 BIG-IP Appliance. When you enter the kubectl get svc command in each cluster, it is confirmed that both clusters are assigned the same IP.

Even if you check in Infoblox IPAM, it is confirmed that only 1 IP is assigned.

#### Solution Proposed
I would like to be assigned different IPs from Infoblox IPAM through a separate identifier such as a key or ID.

#### Alternatives
All you need to do is to assign different IPs through the separator that was an option in the helm used when linking ipam and a separate annotation in the LB Type.

**Comment by trinaths** [comment]
@ejes3409 Can you verify configure CIS with different IPAM label and CIDR ?

**Comment by ejes3409** [comment]
@trinaths 
hi, Thanks for you reply.

There is no problem if you use a different CIDR than other labels.
But what I need is to use the same label and CIDR.

**Comment by nandakishorepeddi** [comment]
Hi @ejes3409 ,  Good Day ! In order to provide different IPs with the same label and CIDR,  Can you try deploying two F5 IPAM controllers with different netviews(using option: --infoblox-netview). So each F5 IPAM controller provides you with a different IP as it is isolated with infoblox-netview.

**Comment by ejes3409** [comment]
I tried giving different netview options to each, but
It has been confirmed that the same IP is being received.

I thought the netview option was for management purposes in K8s.
It seems different from Infoblox's netview.

**Comment by ejes3409** [comment]
I created a netview called default and another in infoblox as shown below.
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/c5d82050-2a62-4caa-860b-ab577d3d9d60)
[default]
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/39efc8d1-58e1-4d58-a7dd-cdf4795f4815)
[another]
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/73a68cec-c61a-435c-babc-ee711dbd4b2a)

And in CIS of two different clusters, IPAM was installed using helm with the settings below.
[cluster01/default]
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/5f343a02-7319-4f06-b376-0b658bef8f5c)
[cluster02/another]
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/e5032854-dd44-42c1-bed5-fa72af7f6074)



Afterwards, a service was created through nginx ( Loadbalancer Type ).
And when you check with kubectl get svc, it is confirmed that both received the same IP.

[cluster01/nginx-svc-loadbalancer]
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/3b5f752c-bc69-4c5e-af02-a2dcd902d878)
[cluster02/nginx-svc-loadbalanacer]
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/02b98992-a3c1-4f97-b0ed-a3cda5d10289)


In my opinion, the name of the service is the separator as shown below.
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/44c55486-2b9f-44eb-b21a-4818b39df1ac)

When creating vs., if you divide the hosts as follows:
Each receives a different IPAM.

[cluster01/vs]
spec:
   host: ipam.nginx.com
   ipamLabel: Dev

[cluster02/vs]
spec:
   host: ipam.nginx2.com
   ipamLabel: Dev

However, if you apply the same host as below when creating vs.
It receives the same IPAM.

[cluster01/vs]
spec:
   host: ipam.nginx.com
   ipamLabel: Dev

[cluster02/vs]
spec:
   host: ipam.nginx.com
   ipamLabel: Dev

I think the separator is "name"

**Comment by nandakishorepeddi** [comment]
Thanks @ejes3409 for the detailed information,  As I understand providing the same CIDR with different netviews, which would result in obtaining the same IP. 
Is it possible for this usecase to have different CIDRs with same label? 
As you know divide the pool (network CIDR, network range) into two, and allocate one pool for each F5 IPAM Controller. So different netviews with different network CIDRs/ranges would help here in providing different IPs from the respective pool without changing the label.

**Comment by ejes3409** [comment]
@nandakishorepeddi 

Thanks for your reply.

What I want is to assign a different IP when the same CIDR, label, and service name are requested from another cluster.
Is there no way?

**Comment by nandakishorepeddi** [comment]
Hi @ejes3409 , Could you confirm that you use different bigip-partition(CIS managed bigip-partition) for each F5 CIS Controller residing in different clusters. 
Reference CIS deployment parameter: - --bigip-partition

**Comment by trinaths** [comment]
@ejes3409 any update based on @nandakishorepeddi  recommendations ?

**Comment by ejes3409** [comment]
Hi, @nandakishorepeddi.
Thanks for your update. and I'm sorry. I'm a little late in checking.

could you please summarize the information again?

First of all, the names of the two clusters are the same.
f5-bigip-ctlr / f5-ipam-controller

However, the similar alphanumeric combination of UUID that follows is slightly different.
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/97bd5f4b-d0bf-4efa-b419-a40399631cb0)
![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/0a3a7b78-ffbb-42e9-b0cb-7ee2d137bcad)

Are you saying how to apply the ipam controller?
I checked the link you shared, but I don't quite understand it.

**Comment by nandakishorepeddi** [comment]
Steps to apply these changes: 
1.  Remove ipam cr in kube-system namespace in both clusters.  
e.g: 
kubectl -n kube-system get ipam # list all available ipams and remove all ipam CR in these namespace
kubectl -n kube-system delete ipam <CIS_deployment_name>.<CIS_managed_bigip_partition>.ipam

2. Add new CIS deployment parameter per cluster
--ipam-cluster-label in the F5 CIS per cluster. 
Please provide a unique string name for each F5 CIS controller as part of the deployment parameter. 
Eg: "cluster1" and "cluster2" for respective F5 CIS controllers.
In your case please update f5-bigip-ctlr deployment in both clusters with an additional deployment parameter : --ipam-cluster-label with values 

3. Dont change any configuration on F5 IPAM Controller. Let F5 IPAM Controller refers to the same netview with the same CIDR/network range. 

5.  Restart CIS (f5-bigip-ctlr) in both clusters. 

At step 5, expected that IPAM infoblox provides with different IPs for the different clusters.

**Comment by ejes3409** [comment]
I installed it with helm,
Can I just add ipam-cluster-label to the content below?

![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/39111359/9b73e388-99eb-4bc9-82fb-cf3951cdefc5)

**Comment by nandakishorepeddi** [comment]
@ejes3409 , Currently helm doesn't have knowledge of this new deployment parameter. So manually can you edit  manually the f5-bigip-ctlr deployment and try to add the deployment paramer under spec. 

eg: 
- --ipam-cluster-label
- "cluster1"

please change the value for second F5 CIS controller accordingly.

**Comment by ejes3409** [comment]
@nandakishorepeddi 


Will a way to apply it manually be added in the future?
Since all items are installed using helm, support for helm is required.

**Comment by ejes3409** [comment]
@nandakishorepeddi 
So, is it okay to wait for v2.15.1??
They are all installed with helm, so even if provided manually, eventually
It cannot be reflected without helm.

(It may be meaningful for testing.)

**Comment by ejes3409** [comment]
@nandakishorepeddi 
Can you tell me the load map or release date for 2.15.1v?
