### ISSUE TITLE
AS3 Multiple ConfigMap Support

### ISSUE THREAD

**Issue by capta1nBee** [F5Networks/k8s-bigip-ctlr#3192]
#### Title
AS3 Multiple ConfigMap Support

#### Description
In large systems, presenting all f5 integrations in a single configuration map is problematic.

#### Actual Problem
Applications must be defined in different configuration maps within the same tenant. A single configuration map is problematic in large systems. Is there a method for this?

#### Additional context
I cannot use configmap-app1.yaml  and configmap-app2.yaml  separately. Is there a way to do this? Or is this feature supported?
I do not want to set different tenants to use configmap-app1.yaml and configmap-app2.yaml separately.

configmap-app1.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-as3-declaration-application1
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "12345678",
            "label": "http",
            "remark": "Application1",
            "kubernetes": {
                "class": "Tenant",
                "kubernetes_app": {
                    "class": "Application",
                    "template": "generic",
                    "Application1": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "1.1.1.1"
                        ],
                        "pool": "web_pool",
                        "virtualPort": 80
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
configmap-app2.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-as3-declaration-application2
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "12345678",
            "label": "http",
            "remark": "Application2",
            "kubernetes": {
                "class": "Tenant",
                "kubernetes_app": {
                    "class": "Application",
                    "template": "generic",
                    "Application2": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "2.2.2.2"
                        ],
                        "pool": "web_pool_2",
                        "virtualPort": 80
                    },
                    "web_pool_2": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }

**Comment by trinaths** [comment]
@capta1nBee  Recommend use CRDs. No update to ConfigMap support.
