### ISSUE TITLE
AS3 CIS managed partition 

### ISSUE THREAD

**Issue by capta1nBee** [F5Networks/k8s-bigip-ctlr#3193]
Hi,

I create the f5 ctrl pod with the following arguments. (args)
I get an error when I use the kubernetes partition in the configmap-p1.yaml file. 
I can't use the partition I created in k8s-bigip-ctlr.

Error : [AS3] CIS managed partition <kubernetes> should not be used in ConfigMaps as a Tenant

args:

args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=https://1.1.1.1",
            "--bigip-partition=kubernetes",
            "--pool-member-type=nodeport",
            "--insecure=true",
            "--agent=as3",
            "--log-as3-response=true",
            "--log-level=DEBUG",
            "--manage-configmaps=true",
            "--filter-tenants=true"
            ]

configmap-p1.yaml 

apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-as3-declaration-application2
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "12345678",
            "label": "http",
            "remark": "Application2",
            "kubernetes": {
                "class": "Tenant",
                "kubernetes_app": {
                    "class": "Application",
                    "template": "generic",
                    "Application2": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "2.2.2.2"
                        ],
                        "pool": "web_pool_2",
                        "virtualPort": 80
                    },
                    "web_pool_2": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }

**Comment by trinaths** [comment]
@capta1nBee The error message is clear. Please configure CIS properly.

> Error : [AS3] CIS managed partition should not be used in ConfigMaps as a Tenant
