### ISSUE TITLE
Does F5 CIS Support OpenShift with cilium as CNI 

### ISSUE THREAD

**Issue by zohebshaik41** [F5Networks/k8s-bigip-ctlr#3196]
Hi Team,

We wanted to use cilium as CNI for our red hat OpenShift active active clusters. Does F5 CIS Supports this case?

Kindly share document related to this. if it's supported.

**Comment by trinaths** [comment]
@zohebshaik41 CIS is not validated with OCP + Cilium. However we validated Cilium + K8S. Please try OCP + Cilium and share your finding. Using static routes with Cilium ?

**Comment by trinaths** [comment]
@zohebshaik41 Any update on this ?

**Comment by zohebshaik41** [comment]
@trinaths It's not yet implemented and it will take sometime. I will close this ticket and will reopen if required.

**Comment by trinaths** [comment]
As per user comments closing this issue.
