### ISSUE TITLE
Image mismatch in F5 operator metadata

### ISSUE THREAD

**Issue by raresd** [F5Networks/k8s-bigip-ctlr#3197]
#### Description 
Mirroring F5 images for a disconnected installation of the F5 operator always fails. Running the 'oc mirror' plugin with a simple config which includes only the f5-bigip-ctlr-operator fails with the following error: 

```
error: unable to retrieve source image registry.redhat.io/f5networks/cntr-ingress-svcs manifest sha256:86ea684ba60cb034c6a57baf0c922937e11199074bdcb2f83513d3cf14bd2eb1: unauthorized: access to the requested resource is not authorized
error: an error occurred during planning 
```

The operator version 1.15 of f5-bigip-ctlr-operator is setting the following relatedImages in the CSV: 

[relatedImages in operator version 1.15](https://github.com/redhat-openshift-ecosystem/certified-operators/blob/d9e4e4762f70ea1c911b36279fbeba56ef9fd2a3/operators/f5-bigip-ctlr-operator/v1.15.0/manifests/f5-bigip-ctlr-operator.clusterserviceversion.yaml#L396C3-L396C10 )

Looking at the operator bundle we actually see the images hosted in a different image registry: 

```
  "csvName": "f5-bigip-ctlr-operator.v1.15.0",
  "packageName": "f5-bigip-ctlr-operator",
  "bundlePath": "registry.connect.redhat.com/f5networks/k8s-bigip-ctlr-operator-bundle@sha256:88776ebcff69af9846e6b65a4e6784743d579669f4b360cf8afc8a0666af7b94",
      "value": "{\"packageName\":\"f5-bigip-ctlr-operator\",\"version\":\"1.15.0\"}"
  "csvName": "f5-bigip-ctlr-operator.v1.15.0",
  "packageName": "f5-bigip-ctlr-operator",
  "bundlePath": "registry.connect.redhat.com/f5networks/k8s-bigip-ctlr-operator-bundle@sha256:88776ebcff69af9846e6b65a4e6784743d579669f4b360cf8afc8a0666af7b94",
      "value": "{\"packageName\":\"f5-bigip-ctlr-operator\",\"version\":\"1.15.0\"}"  
```

#### Setup Details 
Disconnected environment 
registry.redhat.io/redhat/certified-operator-index:v4.12
f5-bigip-ctlr-operator.v1.15.0
 

#### Expected Result 
The correct images are mirrored using 'oc mirror' command. 

#### Actual Result  
The images are not found as the F5 operator provides wrong metadata.

**Comment by raresd** [comment]
cc @vklohiya

**Comment by trinaths** [comment]
Created [CONTCNTR-4362] for internal tracking.
