### ISSUE TITLE
[LOGS] suggested additional changes

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3210]
#### Title
It is believed the following could be made more user friendly

#### Description

About CIS HA, the following messages are shown when the primary goes down:

```
[cloud-user@ocp-provisioner cis-config]$ oc -n cis-mc-twotier logs deployment/k8s-bigip1-ctlr-deployment | grep primary
2023/12/26 10:16:48 [INFO] [MultiCluster] Enqueueing primary CIS/cluster down event
2023/12/26 10:16:48 [INFO] posting declaration on primary cluster down event
```

I find that:

1) the user would like to see when a when a probe fails as WARNING (indicating as suplementary the error message, no tcpdump should be required to figure out)
2) the user would like to see an additional message alike:
2023/12/26 10:16:48 [WARNING] [MultiCluster] X probes failed with primary CIS endpoint. Declaring the primary CIS DOWN.
3) if the primary comes back up an additional INFO message should be shown

The two messages above in the grep command could be DEBUG level IMHO

Additionally, It is not obvious to me (I don´t know what it means either) the following message:

```
2023/12/26 10:16:48 [INFO] [Request: 3] cluster local requested  in HACIS /
```

**Comment by alonsocamaro** [comment]
The following messages don´t have the same format and probably should be DEBUG as they are not user-related events, they are instead very internal ones. Only if there is an error or alike should be shown in ERROR or WARNING level

```
I1226 11:31:55.920741       1 shared_informer.go:240] Waiting for caches to sync for F5 CIS Ingress Controller
I1226 11:31:56.021781       1 shared_informer.go:247] Caches are synced for F5 CIS Ingress Controller 
```

**Comment by vklohiya** [comment]
> Waiting for caches

@alonsocamaro , These are not printed by CIS logger. These are printed by k8s library which is not controller by CIS. These logs are printed in all log levels.
