### ISSUE TITLE
RFE: provide the /ready endpoint to CIS in non multi-cluster mode

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3217]
#### Title
RFE: provide the /ready endpoint to CIS in non multi-cluster mode

#### Description

With CIS 2.x, It is required to use two CIS instances per BIG-IP. When the CIS instance of the Active BIG-IP fails there is no documented method to detect this and failover to the Standby BIG-IP. For this to work the /ready endpoint, introduced and available only when using the multi-cluster feature is ideal by using HA groups with it. See https://youtu.be/NNsUfqHgJAM?t=480 for details

#### Actual Problem

CIS failure is fatal and makes redudant BIG-IPs useless because there is no failover 

#### Solution Proposed

Enable /ready for non-multicluster setups as well
 
#### Alternatives

Use of /health can be used yet the self-checks are not as comprehensive

**Comment by vklohiya** [comment]
"/ready" endpoint is also available in non multi-cluster mode. Please see the release notes for CIS 2.15.0 : https://clouddocs.f5.com/containers/latest/reference/release-notes.html#release-notes-2-15.

Let us know if it's broken or not working.

**Comment by trinaths** [comment]
"/ready" EP is available in CIS.
