### ISSUE TITLE
A separate document for OpenShift integration

### ISSUE THREAD

**Issue by lihongan** [F5Networks/k8s-bigip-ctlr#322]
I'm doing some testing on integration k8s-bigip-ctlr and OpenShift, I tested the OCP (OpenShift Container Platform) F5 router before so I know something about F5 BIP-IP. I feel it is hard to find complete section of how to deploy and configure k8s-bigip-ctlr in OpenShift.

I also checked the doc: http://clouddocs.f5.com/containers/v1/openshift/kctlr-openshift-app-install.html but some wrong yaml file misled me.

So I expect to have a separate document or section for OpenShift integration here and make it more straightforward. I am happy to help:)

**Comment by rsalsa** [comment]
@lihongan - do you create a VXLAN tunnel on the BIG-IP within OS cluster as defined on the: [Add BIG-IP device to an OpenShift Cluster](http://clouddocs.f5.com/containers/v1/openshift/kctlr-use-bigip-openshift.html#bigip-openshift-setup) page?

If you could list a few things that you found difficult, that would be helpful as well.

Thank you!

**Comment by lihongan** [comment]
@rsalsa Yes, VxLAN tunnel was created on BIG-IP. And after updating some yaml file on the http://clouddocs.f5.com/containers/v1/openshift/kctlr-openshift-app-install.html page, the k8s-bigip-ctlr pod was running and it has configured the FDB for VxLAN tunnel. So the connections between BIP-IP and pods in cluster are OK.

Errors in the yaml file:
(1) f5-kctlr-openshift-clusterrole-binding.yaml
```
userNames:
- system:serviceaccount:default:bigip-ctlr
```
I should be `system:serviceaccount:kube-system:bigip-ctlr` or cannot list resources.
(2) f5-k8s-bigip-ctlr_openshift-sdn.yaml
```
    spec:
      containers:
      serviceAccountName: bigip-ctlr
        - name: k8s-bigip-ctlr
<...snip...>
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
```
it is invalid format and I updated it as
```
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
<...snip...>
          args: [ "--bigip-username=$(BIGIP_USERNAME)",
            "other args",
```

Currently my testing stuck in creating vserver by configmap. When testing OpenShift F5 router I usually configure Virtual Server manually and just add the "frontend" part, I don't know why need "backend" in the ConfigMap, seems it cannot be removed. In the doc "backend" means `Identifes the Kubernets Service acting as the server pool` but I think the service/pool should be added/deleted by controller pod, right ?

In addition, OpenShift supports 4 types routes resources and need create an iRule and copy SSL key/cert files to BIG-IP, I didn't find related docs about these.

**Comment by sjberman** [comment]
Documentation for OpenShift Routes has been added with the release of controller version 1.2.
