### ISSUE TITLE
Large number of VIP's causing AS3 POST API timeouts

### ISSUE THREAD

**Issue by surendarmsk1** [F5Networks/k8s-bigip-ctlr#3220]
#### Setup Details
 CIS Version : 2.9.1
 Build: f5networks/k8s-bigip-ctlr:v 2.9.1
 BIGIP Version: Big IP  2.9.1
 AS3 Version: 3.28.0      
 Orchestration: K8S/OSCP          
 Pool Mode: Nodeport

#### Description
I have BIGIP CIS version-2.9.1 running on kubernetes cluster where BIGIP controller watches for any new transport or pool members additions on the cluster or transport server deletion and controller auto triggers the AS3 POST api call to update the changes in F5. 

One of the partition/tenant in F5 is having 200 VIP's and each pool has 50+ pool members. Due to the large volume of VIP's on single partition, AS3 POST API calls are getting timeout.

**Question :** is there a fix on any AS3 version which will trigger POST call only for the incremental changes happening instead of creating POST call Json for entire VIP list ? 
 
please clarify

**Comment by surendarmsk1** [comment]
@mdditt2000  - please suggest if feasible

**Comment by trinaths** [comment]
@surendarmsk1 Recommend using multiple partitions with AS3 and upgrade CIS. Per-APP feature in AS3 is a WIP.
