### ISSUE TITLE
persistenceprofile in two VirtualServer manifests with same hostGroup

### ISSUE THREAD

**Issue by wheestermans31** [F5Networks/k8s-bigip-ctlr#3225]
#### Setup Details

 CIS Version : 2.15.0    
 Build: f5networks/k8s-bigip-ctlr:2.15.0
 Agent Mode: AS3
 Orchestration: OSCP      
 Orchestration Version:   4.13.21
 Pool Mode: Cluster
 Additional Setup details: ovn-kubernetes

#### Description  
  
When applying two VirtualServer CRDs with different host names and the same hostGroup (hence sharing the same virtual server), it is not possible to have different persistence applied which is unexpected. Persistence profiles should be in a per host basis.

#### Steps To Reproduce

[virtualserver-deploytestjetty.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13860957/virtualserver-deploytestjetty.txt)
[virtualserver-deploytestjetty2.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13860958/virtualserver-deploytestjetty2.txt)

1) Apply the two manifests attached, one has the follwoing key sections:
 
hostgroup: blah
persistenceProfile: none
 
hostgroup: blah
persistenceProfile: cookie

Whatever manifest is applied last, its persistenceProfile configuration will prevail

#### Expected Result 

It is possible to have persistence profiles in a per host basis, regardless the hostgroup applied. 
 
The persistence profile should be applied in an LTM profile rule, after the host name has been evaluated. 

#### Actual Result  

The actual behaviour is that unexpectedly, CIS applies the persistence profile in the virtual server, regardless of the host or URL.

#### Observations (if any)

For CIS 3.0 (BIG-IP Next) consider that the persistence profile can be applied in a per URL (application basis) instead in a per VirtualServer basis

**Comment by trinaths** [comment]
Created [CONTCNTR-4381] for internal tracking.

**Comment by vidyasagar-m** [comment]
Hi @wheestermans31, could you test the above with this build image [vidyasagar0416/k8s-bigip-ctlr:latest](https://hub.docker.com/layers/vidyasagar0416/k8s-bigip-ctlr/latest/images/sha256-987d9c840bcd3cc220b4a49301559fa4dac9e269afc4dd832a6715384cfa41af?context=repo) and confirm.

**Comment by wheestermans31** [comment]
I will do testing tomorrow

This is what is needed inside the VirtualServer CRD:

hostgroup: blah
persistenceProfile: none

hostgroup: blah
persistenceProfile: cookie

**Comment by vklohiya** [comment]
@wheestermans31 , To use this feature see the example: https://github.com/F5Networks/k8s-bigip-ctlr/tree/2.x-master/docs/config_examples/customResource/VirtualServer/virtual-server-with-hostPersistence

**Comment by wheestermans31** [comment]
I have started verification of the new functionality

**Comment by wheestermans31** [comment]
The CRD update is downloaded and applied

**Comment by wheestermans31** [comment]
I have tested using sourceAddress.

Are there some examples using the cookie ones, like cookieHash abd cookieInsert

**Comment by wheestermans31** [comment]
I have tried some values, but always got 422

  hostPersistence:
      # Supported values for method are sourceAddress, destinationAddress, cookieInsert, cookieRewrite, cookiePassive, cookieHash, universal, hash, and carp
      # https://my.f5.com/manage/s/article/K83419154
      method: cookieInsert
      # If method is sourceAddress or destinationAddress then netmask and timeout are required in metaData
      # If method is cookieInsert or cookieRewrite then name and expiry are required in metaData
      # If method is carp or universal or hash then key and timeout are required in metaData
      # If method is cookieHash then name, timeout, offset, and length are required in metaData
      # If method is cookiePassive then name is required in metaData
      metaData:
        #netmask: 255.255.255.255
        #timeout: 2
        name: oct-bezavhoi-01-test-deploytestjetty
        **expiry: "1:0:0"**

I need some samples for the expiry value

**Comment by trinaths** [comment]
@wheestermans31 Please share CIS error logs with AS3 422 status.

**Comment by wheestermans31** [comment]
@trinaths I will provide that info asap, but can you already advise of the correct syntax of the expiry field. What I like for example is to have an expire of 1 hour.

**Comment by wheestermans31** [comment]
We are running this AS3 version, testing again and will provide some additional logging

2024/02/08 09:10:13 [DEBUG] [AS3] BIGIP is serving with AS3 version: 3.45.0

**Comment by wheestermans31** [comment]
CIS version
2024/02/08 09:10:10 [INFO] [INIT] Starting: Container Ingress Services - Version: 2.16.0-WIP, BuildInfo: v.morthala-dbee6432-dirty-20240201121408

**Comment by wheestermans31** [comment]
2024/02/08 10:08:10 [DEBUG] [AS3] Raw response from Big-IP: map[code:422 declaration:map[AS3-OpenShift-oct-behoi-01:map[Shared:map[class:Application template:shared] class:Tenant label:AS3-OpenShift-oct-behoi-01] class:ADC controls:map[archiveTimestamp:2024-02-08T10:08:04.178Z class:Controls userAgent:CIS/v2.16.0-WIP K8S/v1.26.9+636f2be] id:urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d label:CIS Declaration remark:Auto-generated by CIS schemaVersion:3.45.0 updateMode:selective] results:[map[code:422 host:localhost message:declaration failed response:010716d9:3: Virtual server /AS3-OpenShift-oct-behoi-01/Shared/crd_10_100_4_237_80 requires a profile of type cookie persistence for ltm policy /AS3-OpenShift-oct-behoi-01/Shared/crd_10_100_4_237_80_oct_behoi_01_policy. runTime:8713 tenant:AS3-OpenShift-oct-behoi-01]]]

**Comment by wheestermans31** [comment]
Seems the persistenceProfile needs to be set to cookie to have it to work. 

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: tme-test-test
  name: deploytestjetty
  labels:
    f5cr: "true"
spec:
  host: "internal-docker-k8s-test-deploytestjetty-test.toyota-europe.com"
  hostGroup: "oct-behoi-01"
  virtualServerAddress: "10.100.4.237"
  virtualServerHTTPPort: 80
  virtualServerName: "oct-behoi-01"  
  persistenceProfile: "cookie"
  pools:
    - path: /
      service: deploytestjetty
      servicePort: 8080
      # reselectTries specifies the maximum number of attempts to find a responsive member for a connection
      # Supported values: [0, 65535]
      reselectTries: 1
      # serviceDownAction specifies connection handling when member is non-responsive
      # Supported values: “drop”, “none”, “reselect”, “reset”
      serviceDownAction: drop
      monitor:
        name: /Common/http_head_f5
        reference: bigip
        interval: 10
        timeout: 3        
  hostPersistence:
      # Supported values for method are sourceAddress, destinationAddress, cookieInsert, cookieRewrite, cookiePassive, cookieHash, universal, hash, and carp
      # https://my.f5.com/manage/s/article/K83419154
      method: cookieInsert 
      # If method is sourceAddress or destinationAddress then netmask and timeout are required in metaData
      # If method is cookieInsert or cookieRewrite then name and expiry are required in metaData
      # If method is carp or universal or hash then key and timeout are required in metaData
      # If method is cookieHash then name, timeout, offset, and length are required in metaData
      # If method is cookiePassive then name is required in metaData
      metaData:
        name: oct-bezavhoi-01-test-deploytestjetty
        expiry: "01:00:00"

But how do I then use one VirtualServer with different policies/pools, and I like to have the VirtualServer default profile set to 'none', and use the new hostPersistence for only a few policies/pools?

**Comment by wheestermans31** [comment]
But how do I then use one VirtualServer with different policies/pools, and I like to have the VirtualServer default profile set to 'none', and use the new hostPersistence for only a few policies/pools to have the default overruled?

**Comment by vidyasagar-m** [comment]
@wheestermans31 We have verified that host persistence is given precedence over the persistence profile. We have also verified when you set the persistence profile to none AS3 is throwing a 422 error. We recommend just removing the persistence profile from the VS and using host persistence there is no functionality impact.
If you want to set the persistence profile as none, we request you raise a separate GitHub issue.

The expiry param needs to be provided in the format [Nd][HH:MM:[SS]]
Expiry examples:
"1d"
"1d00:04"
"1d00:04:10"
"00:04"
"00:04:10"

**Comment by wheestermans31** [comment]
@vidyasagar-m  Seems that the image can't be pulled anymore?

docker pull vidyasagar0416/k8s-bigip-ctlr:latest 
Error response from daemon: manifest for vidyasagar0416/k8s-bigip-ctlr:latest not found: manifest unknown: manifest unknown

**Comment by vidyasagar-m** [comment]
@wheestermans31 could you try with this image vidyasagar0416/k8s-bigip-ctlr:HostPersistence

**Comment by wheestermans31** [comment]
That is working fine.

Tested now your suggestion "**We recommend just removing the persistence profile from the VS and using host persistence there is no functionality impact.**"

apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: tme-test-test
  name: deploytestjetty
  labels:
    f5cr: "true"
spec:
  host: "internal-docker-k8s-test-deploytestjetty-test.toyota-europe.com"
  hostGroup: "oct-behoi-01"
  virtualServerAddress: "10.100.4.237"
  virtualServerHTTPPort: 80
  virtualServerName: "oct-behoi-01"  
  **#persistenceProfile: "cookie"**
  pools:
    - path: /
      service: deploytestjetty
      servicePort: 8080
      # reselectTries specifies the maximum number of attempts to find a responsive member for a connection
      # Supported values: [0, 65535]
      reselectTries: 1
      # serviceDownAction specifies connection handling when member is non-responsive
      # Supported values: “drop”, “none”, “reselect”, “reset”
      serviceDownAction: drop
      monitor:
        name: /Common/http_head_f5
        reference: bigip
        interval: 10
        timeout: 3        
  **hostPersistence:
      method: cookieInsert 
      metaData:
        name: oct-bezavhoi-01-test-deploytestjetty
        expiry: "01:00:00"**

The VirtualServer is created and the policy has ben created too with the cookieInsert persitency as specified inside the crd. 

But the default persistency of the VirtualServer itself is set to 'cookie' too, not 'none'. 

What we like to have a VirtualServer with default set to 'none' and overruled on the policy level.

**Comment by wheestermans31** [comment]
So, this is what we like

Virtual Server --> default 'none'

policy 1 --> insertCookie set
policy 2 --> nothing set, so takes the default from the VirtualServer
...

**Comment by wheestermans31** [comment]
But wondering if this is possible because when I try to modify manually the default VirtualServer persistency to 'none', then I have the following error:

010716d9:3: Virtual server /AS3-OpenShift-oct-behoi-01/Shared/crd_10_100_4_237_80 requires a profile of type cookie persistence for ltm policy /AS3-OpenShift-oct-behoi-01/Shared/crd_10_100_4_237_80_oct_behoi_01_policy.

**Comment by alonsocamaro** [comment]
@vidyasagar-m When using BIG-IP 17.1 (likely any BIG-IP 17.x, needs to be tested) the error message is instead:

``
010716d9:3: Virtual server /Common/test requires a profile of type http-connect for ltm policy /Common/cookie-insert.
``

That is it is not required to have a cookie profile

**Comment by wheestermans31** [comment]
We are now testing with passive cookie persistence.

There seems to be no way to specify the none persistence on the policy level. Then we could have the cookie on the VS default persistency, and on the policy we set the cookie name or not (using None) we don't need cookie persistance. What do you think?

**Comment by vklohiya** [comment]
@wheestermans31 , Can you confirm, if following understanding is correct?

Let's say you have 3 host(foo.com, bar.com and example.com) using the same virtual server(x.x.x.x:443). In this scenario, you want to enable the persistence on foo.com only, other two domains(bar.com and example.com) you don't want any persistence.

**Comment by wheestermans31** [comment]
Yes, that is correct. What we try to setup is to have one VirtualServer, where we have multiple hosts and most of these don't need the persistence, only a few need it. But we like to have that setup in one VirtualServer.

_Also can you confirm how many domains per virtual server you are targeting?_, we foresee around 100 hosts for now

**Comment by trinaths** [comment]
Fixed in 2.15.1
