### ISSUE TITLE
CRD multicluster configuration triggers Raw response from Big-IP: map[code:422 declarationFullId: message:declaration has duplicate values in rules]

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3230]
#### Setup Details
 CIS Version : 2.15.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 17.1
 AS3 Version: 3.45
 Agent Mode: AS3
 Orchestration: OSCP      
 Orchestration Version: 4.12       
 Pool Mode: Cluster      
 Additional Setup details: OVNKubernetes in multi-cluster mode

#### Description  

The attached configuration triggers the duplicate values in the EndPoint rules because it creates two equal entries with the name vs_mc_istio_com_svc_route_d__istio_system_account_mc_istio_com_ocp2  

[issue.tar.gz](https://github.com/F5Networks/k8s-bigip-ctlr/files/13928929/issue.tar.gz)
[virtualserver-route-d.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/13928992/virtualserver-route-d.yaml.txt)

Logs and wrong AS3 definition can be found in

issue/cis.log
issue/as3.json

#### Steps To Reproduce

1) Configure CIS with CIS in multicluster mode 
2) Apply the VirtualServer attached in cluster ocp1

#### Expected Result 

No user configuration should result in a bad AS3 declaration

#### Actual Result  

A bad AS3 declaration is generated

#### Observations 

Manually posting the AS3 declaration without one of the duplicate vs_mc_istio_com_svc_route_d__istio_system_account_mc_istio_com_ocp2 sections eliminates the error

Removing the following section from the VS avoids the problem

```
    extendedServiceReferences:
    - clusterName: ocp2
      namespace:  istio-system
      port: 8443
      serviceName: svc-route-d
```

Re-adding the extendedServices section and changing the clusterName from ocp2 to ocp3 eliminates the problem

**Comment by trinaths** [comment]
Created [CONTCNTR-4385] for internal tracking.

**Comment by trinaths** [comment]
Completed and closed.
