### ISSUE TITLE
[multicluster] cluster name should not be included in pool name when using active-active mode

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3233]
#### Setup Details
 CIS Version : 2.15  
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 17.1
 AS3 Version: 3.45      
 Agent Mode: AS3
 Orchestration: OSCP      
 Orchestration Version: 4.12       
 Pool Mode: Cluster      
 Additional Setup details: multi-cluster

#### Description  

When using the following CRD configuration in multi-cluster active-active mode, a single pool with the name 
svc_route_d__istio_system_account_mc_istio_com_ocp1 is created and the pool should not include the cluster name as it includes members from all clusters.

<img width="1712" alt="Screenshot 2024-01-15 at 09 15 16" src="https://github.com/F5Networks/k8s-bigip-ctlr/assets/16683733/bb951e6c-5385-4426-b1e6-a77abc6eb612">

Configurations and logs included in the next file

[issue-poolname.tar.gz](https://github.com/F5Networks/k8s-bigip-ctlr/files/13936587/issue-poolname.tar.gz)

#### Steps To Reproduce
1) Apply the attached configuration

#### Expected Result 

The cluster name should not be included in the pool name in active-active mode

**Comment by trinaths** [comment]
Created [CONTCNTR-4387] for internal tracking.

**Comment by arzzon** [comment]
This issue has been fixed in CIS 2.15.1 release.
