### ISSUE TITLE
RFE: Support for automatic creation of https monitors with SNI

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3236]
#### Title
Support for automatic creation of https monitors with SNI

#### Description

At time of this writing it is required for customers to create https monitors in order to health check an application that is hosting several domain names. This is the typical case of sending traffic to an ingress controller (2-tier deployments).

This requires:

- the creation of a server TLS profile
- the creation of the monitor itself

as follows:

```
ltm profile server-ssl serverssl.www.mc-nginx.com {
    app-service none
    defaults-from serverssl
    server-name www.mc-nginx.com
}
ltm monitor https www.mc-nginx.com {
    defaults-from https
    send "GET / HTTP/1.1\r\nHost: www.mc-nginx.com\r\nConnection: close\r\n\r\n"
    ssl-profile /Common/serverssl.www.mc-nginx.com
}
```

#### Actual Problem

Customers cannot automate the monitoring for this typical use case because the monitors need to be pre-created

#### Solution Proposed

When indicating an https monitor in the manifest, this should be by default SNI enabled

#### Additional context

In order for SNI enabled monitors to work in BIG-IP Classic it is necessary to enable the following DB key

```
tmsh modify sys db bigd.tmm value enable
```

See https://my.f5.com/manage/s/article/K85210713 for more details. Given that in-TMM monitoring has been affected by issues in the past and has an impact in data plane's performance. I would recommend that https monitors with SNI (which require in-TMM right now) have a different name than https in the manifests, for example: https-sni

**Comment by alonsocamaro** [comment]
Note that one of the TLS server profiles of the monitors will need to have ticked the option 

```
    sni-default true
```
otherwise AS3 complains (I believe it shouldn´t in this case), maybe an AS3 bug should be raised?

"2024/01/17 14:26:38 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declaration:HTML Tag-like Content in the Request URL/Body results:[map[code:422 host:localhost message:declaration failed response:0107180b:3: Virtual Server /mc-twotier/Shared/crd_10_1_10_115_443 has more than one clientssl/serverssl profile but none of them is default for SNI. runTime:3097 tenant:mc-twotier]]]"

**Comment by lavanya-f5** [comment]
@alonsocamaro This may not be AS3 issue, but requirement from bigip to support multiple profiles on same virtual. See https://community.f5.com/t5/technical-forum/unable-to-assign-different-certificate-to-same-virtual-server/td-p/215962

**Comment by alonsocamaro** [comment]
@lavanya-f5  please note that in this case the profile is attached to the monitor, not to the virtual server

**Comment by alonsocamaro** [comment]
Given that at present we don´t create automatically TLS profiles even for the data plane (see TLSProfile CRD) it seems that for now we should just:

Expose the ssl-profile in the monitor section (it is actually exposed in NextGen Routes) in which case the customer will be left to do:

- tmsh modify sys db bigd.tmm value enable (this needs to be done only once)
- create the server-ssl profile (this should need to be done one time per FQDN

It would be nice if in CIS 3.0 it is possible to create SSL profiles with a manifests so DevOps can fully configure a service without having to do a separate automation or manually creating these

**Comment by alonsocamaro** [comment]
Additionally, at present the only the Ingress resource supports specifying a ssl profile in the monitor, see:

https://clouddocs.f5.com/containers/latest/userguide/ingress.html

That is, the Route resource doesn´t support it as of yet. This should be implemented as well to have consistent health checking across the different resource types.

**Comment by lavanya-f5** [comment]
@alonsocamaro dev build with support for setting sslProfile in https monitor with nextgen routes and virtualserver quay.io/f5networks/k8s-bigip-ctlr-devel:b447bdff59b9194a0ee9e1d8dba595d85965e726.

**Comment by alonsocamaro** [comment]
@lavanya-f5 many thanks!

**Comment by lavanya-f5** [comment]
@alonsocamaro  dev build with fix for handling default value quay.io/f5networks/k8s-bigip-ctlr-devel:343cf970ef31d6e2de3b1b059e5e8c7a3f379098

**Comment by alonsocamaro** [comment]
It worked like a charm. Closing this issue.

Thanks!
