### ISSUE TITLE
RFE: change log level of message from INFO to ERROR on code 4XX of CCC calls

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3237]
#### Title
RFE: change log level of message from INFO to ERROR on code 4XX of CCC calls

#### Description

I find not appropriate to show the following error message at INFO level

 ```
2024/01/17 14:33:45 [INFO] Text: '{"code":400,"message":"01070734:3: Configuration error: invalid static route, the dest/netmask pair 10.130.0.0/255.255.240.0 already exists for /sc-twotier/k8s-master-1.ocp3.f5-udf.com-10.1.10.9","errorStack":[],"apiError":3}'
```

If I understand right this message doesn´t come from AS3 but instead from the CCC agent. 

#### Actual Problem

Miss leading log level

#### Solution Proposed

Rest calls resulting in 4XX error (or 5XX) codes should be returned with ERROR level given that the kubernetes user hasn´t made any manifest configuration error to trigger these.

**Comment by trinaths** [comment]
No changes to CIS 2.x. The log level is clear on INFO however there are errors with CCCL agent.
