### ISSUE TITLE
RFE: Support a mix of k8s Secret and bigip reference in TLSProfile

### ISSUE THREAD

**Issue by mikejoh** [F5Networks/k8s-bigip-ctlr#3239]
#### Title
Support a mix of k8s Secret and bigip reference in TLSProfile.

#### Description
Support a mix of k8s Secret and bigip reference in TLSProfile.

#### Actual Problem
We're running `cert-manager` + BIGIP + `k8s-bigip-ctlr`, and issues a certificates in-cluster via our PKI (which is put into a `Secret` ) and then use those certificates with a `VirtualServer` via a `TLSProfile`. What doesn't work is to use `termination` mode set to `reencrypt` and then a mix of references pointing at:
* Certificate locally added in the BIGIP (in /Common/); and
* certificate added as a `Secret` in the cluster.

This is very frustrating and blocking us at the moment.

#### Solution Proposed
Add support for mixing references in the `tls` configuration of the `TLSProfile` CRD.

#### Alternatives
Non at the time of writing this, we've been stuck at using `edge` as termination but we want a higher degree of encryption of traffic and let the backend traffic be encrypted also.

#### Additional context
There's been other users asking about this earlier when searching through the F5 Network slack, here's my message there: https://f5cloudsolutions.slack.com/archives/C7NJD8LGH/p1702559023827449. And here's another user with the same problem, that user never got back on how and if they solved the same:ish problem: https://f5cloudsolutions.slack.com/archives/C7NJD8LGH/p1660649008586289.

**Comment by trinaths** [comment]
@mikejoh Please validate this issue with quay.io/f5networks/k8s-bigip-ctlr-devel:cd502d72cc64d4bf9b1cce883f003263c92a2d34 and share your feedback.

**Comment by trinaths** [comment]
Created [CONTCNTR-4514] for internal tracking.

**Comment by mikejoh** [comment]
@trinaths Thanks! Will do! 👍🏻

**Comment by trinaths** [comment]
@mikejoh Any update ?

**Comment by mikejoh** [comment]
> @mikejoh Any update ?

Not yet unfortunately, we've planned the work to test this but we haven't done anything yet.

**Comment by lavanya-f5** [comment]
Example - https://github.com/F5Networks/k8s-bigip-ctlr/tree/2.x-master/docs/config_examples/customResource/VirtualServerWithTLSProfile/reencrypt-hybrid-reference
latest crd schema - https://github.com/F5Networks/k8s-bigip-ctlr/blob/2.x-master/docs/config_examples/customResourceDefinitions/incubator/customresourcedefinitions.yml

**Comment by klippo** [comment]
@lavanya-f5 We've now tested this functionality and can confirm that it works as expected. Many thanks for the quick response to this

**Comment by mikejoh** [comment]
@lavanya-f5 @trinaths Thanks for the help!

**Comment by trinaths** [comment]
Closing this issue as fixed.
