### ISSUE TITLE
Single shared Virtual Server

### ISSUE THREAD

**Issue by sanyu** [F5Networks/k8s-bigip-ctlr#325]
Hi!

I've read the docs and tried a few different things, but can't seem to get it to work for our scenario. 
I'd like to be able to share **1 single Virtual Server** (1 IP) and have **k8s-bigip-ctlr** manage the pools and IRules or Policies to forward traffic to the correct pool. 

Using an _Ingress_ resource wouldn't work as it will create a new Virtual Server (which requires a new IP) per Ingress/Application. 
Name Based _Ingress_ _could_ work, but unfortunately, each app runs in its own namespace and must be able to provide their own _Ingress_ object (with the current k8s-bigip-ctlr implementation this would mean a new IP address per _Ingress_ object as VS can't be shared).

One thing that could work is having multiple _Ingress_ objects updating the same BIGP _Policy_ , but I doesn't seem like we can do this at the moment (BIGIP won't allow policies with conflicting controls associated with the same VS).

I found this in the docs:
_

> If virtualAddress or bindAddr are not provided in the Frontend configuration, then the controller will configure and manage pools, pool members, and healthchecks for the service without a virtual server on the BIG-IP. Instead you should already have a BIG-IP virtual server that handles client connections and has an irule or traffic policy to forward the request to the correct pool. The stable name of the pool will be the namespace of the Kubernetes service followed by an underscore followed by the name of the service ConfigMap.

_

This means that we could get this scenario working using ConfigMaps describing the pool, and then using another external system to create the IRule or traffic policy to forward the request to the correct pool. 

Is there any other way we could achieve this?
Are there any plans to support this scenario?

**Comment by jaxxstorm** [comment]
Any news here? I'd love to give help if I can

**Comment by amudukutore** [comment]
@jaxxstorm - the single shared virtual server feature (i.e., configuring a single virtual server on the BIG-IP to support multiple ingresses) is currently being worked on and will be part of our next release (1.4.0) which should be out in early January.
