### ISSUE TITLE
documentation issue: empty section headers for TLSprofiles

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#3251]
#### Description  
This page has 3x empty section headers:

https://clouddocs.f5.com/containers/latest/userguide/crd/tlsprofile.html

I've attached a screenshot of what this documentation page looks like for me today. I remember in the past that there was more information around the possible values under the headings.

#### Observations (if any)
![Capture](https://github.com/F5Networks/k8s-bigip-ctlr/assets/38844924/d65096d0-0cb8-419f-8781-ddac4d8ce36d)

**Comment by trinaths** [comment]
Created [CONTCNTR-4536] for internal tracking.

**Comment by lavanya-f5** [comment]
Fixed in latest
