### ISSUE TITLE
RFE: Support user-defined/custom names for the virtual server created by CIS when using CRD hostGroup option.

### ISSUE THREAD

**Issue by kerryb48** [F5Networks/k8s-bigip-ctlr#3263]
#### Title
Support user-defined/custom names for the virtual server created by CIS when using CRD hostGroup option.

#### Description
When using the hostGroup option in CRD VirtualServer definitions, the shared VS that is created uses the name format of crd_<VIP address>_<port>.  Would like a to able to customize the name of the actual virtual server resource provisioned on the LTM.  

#### Actual Problem
Our organization has naming standards for F5 LTM resources such as virtual servers.  The default naming scheme of the virtual server created as part of a hostGroup does not meet these standards, but there is currently no way to customize/explicitly define this name.  Would love to be able to customize this to ensure it follows our organizations standards/policies and that I do not need to file for exceptions because it is being created through automation.

#### Solution Proposed
Use the hostGroup name as defined in the VirtualServer CRD definition.  

#### Alternatives
Add a new  parameter to explicitly define the name separate from the existing hostGroup property of the VirtualServer CRD.

#### Additional context
N/A

**Comment by trinaths** [comment]
Created [CONTCNTR-4535] for internal tracking.

**Comment by trinaths** [comment]
Closed as completed.
