### ISSUE TITLE
RFE: Improve log 2024/01/31 09:41:47 [DEBUG] Updated Route xxx with TLSProfile

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3264]
#### Title
RFE: Improve log 2024/01/31 09:41:47 [DEBUG] Updated Route xxx with TLSProfile

#### Description

The log above doesn´t indicate the TLSProfile being applied

#### Solution Proposed

Include the name of the profile. It would be a plus if it is possible to indicate from where it is getting that config, ie: baseRouteSpec? extendedRouteSpec's policyCR? from the manifest annotation? from the spec?

Given the non trivial nature of the rules governing SSL certificates used any hints in the logs would be appreciated

Right now I´m trying to figure out why certificates from the spec are not used and I don´t see any hint in the logs.

Please also consider showing which certs have been discarded and why

**Comment by alonsocamaro** [comment]
It would be neat to see the output from getSSLProfileOption().

Thinking that maybe the logs should be at INFO level given this part of the config is not trivial and it is very important

**Comment by trinaths** [comment]
Created [CONTCNTR-4567] for internal tracking.
