### ISSUE TITLE
RFE: Improve SSL/TLS handling using embedded (spec) certificates and SSL/TLS profiles

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3269]
#### Title
RFE: Improve SSL/TLS handling using embedded (spec) certificates and SSL/TLS profiles

#### Description

Note: this is a customer found issue while testing Next Gen Routes

At present, when using embedded certs, if a single Route misses to include the certificate in it, this causes that all Route´s certificates get replaced their embedded certificate with the defaultTLS certificate, breaking the configuration.

At present, it is also not possible to mix annotations and embedded (spec) certs in the same router group.

#### Actual Problem

This behaviour can cause a general outage by a Route affecting the configuration of other Routes.

#### Solution Proposed

Request the required functionality to AS3 and implement defaultTLS in a per Route basis.

In addition to avoid this issue, this AS3 functionality would allow to also mix annotated certificates and embedded certificates. 

Overall, with this AS3 functionality it would allow CIS to impose less restrictions to customers, and the current non trivial SSL profiles precedence would be very clear

**Comment by alonsocamaro** [comment]
As a side note, when not using defaultTLS and one of the Routes misses the embedded certificate, then it gets applied to one of the certificates of one of the other Routes.

**Comment by trinaths** [comment]
Created [CONTCNTR-4550] for internal tracking.

**Comment by trinaths** [comment]
There is a limitation from AS3 which doesn't allow bigIP reference and certificates to be defined as a combination for any specific TLS profile (server/client).
