### ISSUE TITLE
Support for ICNIv1 has been removed from openshift4.13+

### ISSUE THREAD

**Issue by colaMouseTrap** [F5Networks/k8s-bigip-ctlr#3306]
#### Setup Details
 CIS Version : 2.15.1   
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.10.3      
 AS3 Version: 3.47.0      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: Openshfit 4.13

#### Description  
Please update public docs to state that the 4.8 openshift cluster configuration is no longer supported in 4.13+ and/or provide a work around.  

According to https://access.redhat.com/solutions/7051403: 
Support for ICNIv1 was removed from openshift4.13+ as per the [Jira](https://issues.redhat.com/browse/OCPBUGS-24046) hence the feature listed in the 3rd party F5 [document](https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-8-cluster.html) doesn't work.

#### Steps To Reproduce
1)  Try to upgrade with 4.8 Hybrid overlay design 
 
#### Expected Result 
This is just a report to update the documentation to notify customers that this design is no longer valid in newer versions of Openshift.  If VXLAN or hybridOverlay is somehow still supported, update the F5 clouddocs documentation with work arounds. 

#### Actual Result  
Network connectivity is lost to the pods in the cluster. 

#### Diagnostic Information
N/A

**Comment by trinaths** [comment]
Created [CONTCNTR-4639] for internal tracking.
