### ISSUE TITLE
Support for both NodePort/ClusterIP as pool members for load balancers in same cluster.

### ISSUE THREAD

**Issue by avinashchundu9** [F5Networks/k8s-bigip-ctlr#3330]
#### Title
Support for both NodePort/ClusterIP as pool members for load balancers in the same cluster.

#### Description
CIS currently has the option pool_member_type which needs to be either clusterIP or nodeport. This setting applies to all load balancers managed by CIS in that cluster. Enabling both options in the same cluster will give users more flexibility to select options based on application requirements. 

#### Actual Problem
Application owners doesn't have flexibility to select the members of the pool to be ClusterIP or nodeport. It's decided on CIS by cluster admin and applies to all load balancers.

#### Solution Proposed
Allow "pool_member_type: both" in CIS and let the service decide which type the pool members it can be. If the service is of type nodeport and the transport server is pointed to that service then the pool member should be node port. The same applies to clusterIP as well. This will give application owners more flexibility on how their load balancers can be configured.

**Comment by mdditt2000** [comment]
@avinashchundu9 thanks for opening this issue. @trinaths  we spoke about this yesterday. Adding this flexibility for CIS to detect NodePort/ClusterIP as pool members based on the service would allow of one CIS controller to be installed.

Next steps to create a Jira task and prioritize for 2.17

**Comment by trinaths** [comment]
@avinashchundu9  This feature is supported in 2.16 

Support for pool-member-type auto for CRD, NextGen Routes and multiCluster mode. Please refer `Documentation <https://github.com/F5Networks/k8s-bigip-ctlr/blob/2.x-master/docs/config_examples/PoolType-Auto/README.md>`_
