### ISSUE TITLE
AS number other than default AS number(64512) to BGP with Calico is not working

### ISSUE THREAD

**Issue by avinashchundu9** [F5Networks/k8s-bigip-ctlr#3331]
#### Setup Details
 CIS Version : 2.15.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP v16.1.3.1      
 AS3 Version: 3.47
 Agent Mode: AS3      
 Orchestration: K8S
 Orchestration Version:  
 Pool Mode: Cluster
 Additional Setup details: calico CNI with version v3.26.1

#### Description  
BGP between F5 and Calico works if we are using the default AS number. But if we use any other AS number it fails.

#### Steps To Reproduce
1) Try to establish a BGP peering between F5 and Calico running on Kubernetes with AS number other than the default

#### Expected Result 
BGP peer should be established.

#### Actual Result  
BGP peer wasn't established.

**Comment by mdditt2000** [comment]
Spike CONTCNTR-4644

**Comment by trinaths** [comment]
created a Spike CONTCNTR-4644 to dig into this issue more

**Comment by vidyasagar-m** [comment]
@avinashchundu9 We tried with different AS Number in our local and the BGP Connection is established without any failure. Could you provide us the port lockdown in the VLAN of the BIGIP.

![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/42372699/64ea7bcb-59b4-48a5-8cc1-a75fdb541007)

**Comment by vidyasagar-m** [comment]
@avinashchundu9 Could you also send the AS Number used in the BIGIP end and the cluster end?

**Comment by avinashchundu9** [comment]
++ Lei

Currently we using 64512. But we tried some lower number a while back.

**Comment by avinashchundu9** [comment]
We used AS 6451 on both F5 and k8s and it did not work

On F5, under self Ips, all IP’s port lockdown=allow all, see below

Thanks
Lei

***@***.***

From: Chundu, Avinash ***@***.***>
Sent: Wednesday, March 27, 2024 5:46 PM
To: F5Networks/k8s-bigip-ctlr ***@***.***>; F5Networks/k8s-bigip-ctlr ***@***.***>; chen, LLei ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [F5Networks/k8s-bigip-ctlr] AS number other than default AS number(64512) to BGP with Calico is not working (Issue #3331)

++ Lei

Currently we using 64512. But we tried some lower number a while back.

**Comment by avinashchundu9** [comment]
Here is the node error log.

bird: Global_x_x_x_10: Received: Bad peer AS: 64512
bird: Global_ x_x_x_10: State changed to stop
bird: Global_ x_x_x_10: State changed to down
bird: Global_ x_x_x_10: Starting
bird: Global__ x_x_x_10: State changed to start

thanks
LEi

From: chen, LLei
Sent: Wednesday, March 27, 2024 5:54 PM
To: Chundu, Avinash ***@***.***>; F5Networks/k8s-bigip-ctlr ***@***.***>; F5Networks/k8s-bigip-ctlr ***@***.***>
Cc: Mention ***@***.***>; Ireland, Paul ***@***.***>
Subject: RE: [F5Networks/k8s-bigip-ctlr] AS number other than default AS number(64512) to BGP with Calico is not working (Issue #3331)

We used AS 6451 on both F5 and k8s and it did not work

On F5, under self Ips, all IP’s port lockdown=allow all, see below

Thanks
Lei

***@***.***

From: Chundu, Avinash ***@***.******@***.***>>
Sent: Wednesday, March 27, 2024 5:46 PM
To: F5Networks/k8s-bigip-ctlr ***@***.******@***.***>>; F5Networks/k8s-bigip-ctlr ***@***.******@***.***>>; chen, LLei ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [F5Networks/k8s-bigip-ctlr] AS number other than default AS number(64512) to BGP with Calico is not working (Issue #3331)

++ Lei

Currently we using 64512. But we tried some lower number a while back.

**Comment by vidyasagar-m** [comment]
@avinashchundu9 tried with AS Number 6451 and the connection to the BGP Peers is successful. Seems like the issue is related to BIGIP. Could you raise a BIGIP SR regarding the issue.

**Comment by trinaths** [comment]
From the above discussion the no issue with CIS.
