### ISSUE TITLE
[CIS 3.0] Add controller status in kubectl describe

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3334]
#### Title
[CIS 3.0] Add controller status in kubectl describe

#### Description
At present it is needed to check the logs to see everything is all right. This is not trivial or user-frienly.

#### Actual Problem

It is difficult to know the "current" status of the controller

#### Solution Proposed

show a status field in a describe of the upcoming CRD for the Controller, items that could be included:

- CCCL- equivalent connectivity status for Next 
- AS3 connectivity status
- Kubernetes API connectivity status
- multi-cluster status, is it primary? secondary? active? standby?
- own health endpoint status
- remote health endpoint status
- timestamp of last valid configuration applied successfully
- timestamp of last applied configuration successful or not, including AS3 status (--log-as3-response=true)
- ideally, we could indicate the manifests that could not be applied succesfully
- actual global CIS configuration being used

**Comment by skenderidis** [comment]
+1

**Comment by alonsocamaro** [comment]
Add AS3 status and timestamp

**Comment by trinaths** [comment]
Created [CONTCNTR-4651] for internal tracking.
