### ISSUE TITLE
Ratio on multi cluster CIS not working and removing cluster2 members from pool

### ISSUE THREAD

**Issue by avinashchundu9** [F5Networks/k8s-bigip-ctlr#3341]
#### Setup Details
 CIS Version : 2.15.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP v16.1.3.1
 AS3 Version: 3.47     
 Agent Mode: AS3      
 Orchestration: K8S          
 Pool Mode: ClusterIP/NodePort 

#### Description  
 When a CIS config file is changed from Active-Active mode to Ratio mode. CSI updates all the pool members with only Cluster 1 nodeports/clusterIP's and removes Cluster 2 members and no ratio has been applied to the pool members.

#### Steps To Reproduce
1) Deploy CIS in Active-Active mode and create a few transport servers.
2) Change the config file from Active-Active to ratio mode on both clusters
3) Check the pool members in F5

#### Expected Result 
Both cluster members should still be part of the pool and ratio settings should be applied.

#### Actual Result  
Ratio not applied and only members from cluster1 show up in the pool members.

![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/103086833/d3ef8334-bf79-432f-a9be-9f08c109731d)

**Comment by trinaths** [comment]
Created [CONTCNTR-4647] for internal tracking

**Comment by trinaths** [comment]
Fixed in 2.16.1

**Comment by trinaths** [comment]
Improved documentation. No CIS code improvements.
