### ISSUE TITLE
[DOC] multi-cluster fix description of table "When the primary cluster is down"

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3348]
#### Description  

In https://clouddocs.f5.com/containers/latest/userguide/multicluster/ the following table

![image](https://github.com/F5Networks/k8s-bigip-ctlr/assets/16683733/a83b1aab-44b4-46a9-9d62-d0f83f4558cb)

should be fixed as per conversation
  
#### Expected Result 

The rows active-active and ratio should have different value for "Primary Cluster Pool Members" but the behaviour is really the same. The behaviour is that the primary cluster pool members are always considered.

The description of the meaning of the table should be also clarified.

I would expect that the table indicates what is the behaviour when the CIS is down, meaning that the API of that cluster might be healthy.

It is expected that if the API is not available no service discovery is possible. To avoid ambiguity this should be indicated in the meaning of the tables with a sentence alike:

"Pool members discoverability of a service will ultimately depend if the Kubernetes API in the corresponding cluster is available"

**Comment by trinaths** [comment]
Created [CONTCNTR-4657] for internal tracking.

**Comment by trinaths** [comment]
Fixed in 2.17. ETA Early June'24
