### ISSUE TITLE
Enable weight for transport server similar to virtual server in multi-cluster CIS

### ISSUE THREAD

**Issue by avinashchundu9** [F5Networks/k8s-bigip-ctlr#3352]
#### Title
Enable weight for transport server similar to a virtual server in multi-cluster CIS

#### Description
virtual server CRD has weight included to distribute workload between the clusters. Requesting the same functionality to be added to the Transport server.

#### Actual Problem
Users can't do canary deployments if they are using a transport server.

#### Solution Proposed
Implement weight in Transport server CRD.

**Comment by trinaths** [comment]
Created [CONTCNTR-4662] for internal tracking.

**Comment by trinaths** [comment]
Fixed in 2.17. ETA Early June'24
