### ISSUE TITLE
Please include required namespace annotations to the documentation for OpenShift HA with static routing

### ISSUE THREAD

**Issue by josephxtrahe-vumc** [F5Networks/k8s-bigip-ctlr#3365]
#### Title
Please include required namespace annotations to the documentation for OpenShift HA with static routing.

#### Description
Please include the information from step 4 of Mark Dittmer's [OpenShift OVN-Kubernetes using F5 BIG-IP HA with NO Tunnels](https://github.com/mdditt2000/k8s-bigip-ctlr/tree/main/user_guides/ovn-kubernetes-ha#step-4-configure-egress-from-openshift-cluster-to-big-ip) in the public documentation for [OpenShift 4.12 and F5 BIG-IP Container Ingress Services (CIS) User-Guide for High Availability BIG-IP using OVN-Kubernetes iCNI with NO Tunnels](https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-cluster.html)

#### Actual Problem
After the deprecation of ICNIv1 from OpenShift, there is a need to configure CIS to use static routing rather than VXLAN. The documentation today does not provide enough info to properly configure CIS with static routing.

#### Solution Proposed
Please include a section in the docs describing the need for namespaces to include the `k8s.ovn.org/routing-external-gws: <BIG-IP self IP>` annotation for traffic to be routed back through the BIG-IP.

#### Alternatives
There are no alternatives. While troubleshooting this issue, we tried configuring EgressIP and AdminPolicyBasedExternalRoute objects in our OpenShift cluster. While these seem to be suitable options for egress in general, EgressIP doesn't seem to play nicely with CIS, and AdminPolicyBasedExternalRoute is a new feature that is still buggy at the moment.

#### Additional context
This goes hand-in-hand with [GH-3306](https://github.com/F5Networks/k8s-bigip-ctlr/issues/3306). It would be nice to know that OpenShift is deprecating ICNIv1 in the docs for configuring CIS with VXLAN tunnels in the first place. Our org has gone through a lot of trouble over the past few months due to this. We could have reduced months of troubleshooting down to an afternoon if we had known that ICNIv1 was being deprecated, and that it is necessary to annotate namespaces with  `k8s.ovn.org/routing-external-gws: <BIG-IP self IP>`.

**Comment by trinaths** [comment]
Created [CONTCNTR-4678] for internal tracking.

**Comment by alonsocamaro** [comment]
Please note that the annotation is not the PREVIEW code of the feature in OVN, the GA version of the feature has to be implemented as follows:

https://docs.openshift.com/container-platform/4.14/networking/ovn_kubernetes_network_provider/configuring-secondary-external-gateway.html#configuring-secondary-external-gateway

**Comment by thejimbo27** [comment]
We did attempt the configuration with AdminPolicyBasedExternalRoutes, however this resource was not introduced until OpenShift 4.14, so anybody using 4.12 or 4.13 is still left without a workaround. Also, even in 4.14, there is a [bug (OCPBUGS-29342)](https://issues.redhat.com/browse/OCPBUGS-29342) prior to 4.14.19 (which was just released a few days ago) where pods created *after* the AdminPolicyBasedExternalRoute is applied do not have their default route changed.

Since AdminPolicyBasedExternalRoute is a new resource that until very recently didn't work as expected, I would be hesitant to use that as the standard implementation for now.

**Comment by josephxtrahe-vumc** [comment]
We did attempt the configuration with AdminPolicyBasedExternalRoutes, however this resource was not introduced until OpenShift 4.14, so anybody using 4.12 or 4.13 is still left without a workaround. Also, even in 4.14, there is a [bug (OCPBUGS-29342)](https://issues.redhat.com/browse/OCPBUGS-29342) prior to 4.14.19 (which was just released a few days ago) where pods created after the AdminPolicyBasedExternalRoute is applied do not have their default route changed.

Since AdminPolicyBasedExternalRoute is a new resource that until very recently didn't work as expected, I would be hesitant to use that as the standard implementation for now.

**Comment by vklohiya** [comment]
Updated the documentation. https://clouddocs.f5.com/containers/latest/userguide/openshift/openshift-4-12-cluster.html#step-3-optional-configure-egress-from-openshift-cluster-to-big-ip-needed-when-no-snat-is-used
