### ISSUE TITLE
Multi-Cluster Support for NodePortLocal with Antrea CNI

### ISSUE THREAD

**Issue by jokoyuliantoro** [F5Networks/k8s-bigip-ctlr#3379]
#### Title
Multi-Cluster Support for NodePortLocal with Antrea CNI

#### Description
CIS already supports multi-cluster Kubernetes/OpenShift in NodePort mode. A global bank plans to deploy multi-cluster Kubernetes in NodePortLocal mode with Antrea CNI. BIG-IP is the main load balancing tool in this global bank and could be positioned as the load balancer of the multi cluster Kubernetes nodes.

#### Actual Problem
The global bank is exploring the solution options for the load balancer of the multi cluster Kubernetes nodes and is about to make a final decision whether BIG-IP + CIS can be considered as a candidate for the solution or not. 

#### Solution Proposed
CIS to support NodePortLocal mode with Antrea CNI for multi cluster Kubernetes setup.

#### Alternatives
N/A

#### Additional context
N/A

**Comment by jokoyuliantoro** [comment]
The bank is on the way to setup production multi-cluster in one month's time, FYI.

**Comment by trinaths** [comment]
@jokoyuliantoro We validated CIS with Antrea CNI on NodePortLocal with Static Route mode.
 
CIS multi-cluster support with Antrea CNI on NodePortLocal with Static Route mode is not validated. IMO, this should be valid.
 
Please try and share your feedback.
