### ISSUE TITLE
RFE: F5 IPAM Controller support for OpenShift ver 4.12++

### ISSUE THREAD

**Issue by adityoari** [F5Networks/k8s-bigip-ctlr#3419]
#### Title
Request support for F5 IPAM Controller in newer versions of OpenShift (4.12 and higher)

#### Description
Currently F5 IPAM Controller only supports OpenShift up until version 4.11, while customer is running OCP 4.14.

#### Actual Problem
Customer can't find and install F5 IPAM Controller for their OpenShift v4.14 clusters

#### Solution Proposed
Provide fully working F5 IPAM Controller for newer versions of OpenShift

#### Alternatives
- Brand new Operator/Controller for newer OpenShift to fully emulate the capability of existing F5 IPAM Controller 
- Build the IPAM integration capability directly into the CIS

**Comment by trinaths** [comment]
Created [CONTCNTR-4736] for internal tracking.

**Comment by vklohiya** [comment]
Operator v1.17.0 is released.
