### ISSUE TITLE
Add support for Virtual Server to use a SNAT Pool

### ISSUE THREAD

**Issue by schwartzmeier** [F5Networks/k8s-bigip-ctlr#3423]
#### Title
Add support for Virtual Server to use a SNAT Pool

#### Description
We need CIS to be able to create a snat pool with an address from IPAM and assign that to the virtual server. We cannot use "Autosnat" or an existing snatpool.

#### Actual Problem
Currently CIS only supports virtual server using Autosnat, existing snat pool, or none.

#### Solution Proposed
Define an IP address in IPAM for CIS to use to create a SNAT Pool and assign that to the virtual server its creating.

**Comment by trinaths** [comment]
@schwartzmeier Please share relevant AS3 configuration for this RFE to automation_toolchain_pm <automation_toolchain_pm@f5.com>

**Comment by trinaths** [comment]
Closing this issue. No further response from the user.
