### ISSUE TITLE
Add support for FTP profile in policy CR

### ISSUE THREAD

**Issue by sandwicher0** [F5Networks/k8s-bigip-ctlr#3438]
#### Title
Add support for FTP profile in policy CR

#### Description
Add support for FTP profile in policy CR

#### Actual Problem
Policy CR doesn't support FTP profile.
https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/customResource/Policy

**Comment by mikeoleary** [comment]
@trinaths  - I am currently working with another customer, in addition to the original poster, who requires an FTP profile on a Profile.

In my case, they are running IBM Sterling FTP server in Openshift. Feel free to call if you have questions.

**Comment by trinaths** [comment]
Created [CONTCNTR-4796] for internal tracking.

**Comment by mdditt2000** [comment]
Resolved in CIS 2.18 - https://clouddocs.f5.com/containers/latest/reference/release-notes.html
