### ISSUE TITLE
Support for multiple LTM monitors when using HostGroup

### ISSUE THREAD

**Issue by thomas-cripps-fg** [F5Networks/k8s-bigip-ctlr#3442]
#### Title
Support for multiple LTM monitors on a pool when virtual server using HostGroup

#### Description
When deploying multiple virtual server configurations when also using HostGroup LTM monitors appear to overwrite themselves, unsure if RFE or Bug.

#### Actual Problem
Unable to monitor multiple applications in same backend pool as LTM monitors overwrite themselves. When a batch of VirtualServer CRDs are deployed it seems like the last CRD in the batch is the LTM monitor which persists giving the illusion of appending configuration

#### Solution Proposed
Allow support for multiple LTM monitors within same backend pool and the use of MinimumMonitors allows the pool not to go down

#### Alternatives
Unsure if anything else would work

#### Additional context
N/A

**Comment by mdditt2000** [comment]
@thomas-cripps-fg  please follow the example https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/VirtualServer/HealthMonitor/monitors-virtual-server.yaml

Schema should allow this. Add HostGroup to the example. Let me know the results or share your CRD to automation_toolchain_pm@f5.com

**Comment by mdditt2000** [comment]
re-opened. Let me review this with my team.

**Comment by thomas-cripps-fg** [comment]
Thanks Mark.

Issue seems to be when we have multiple virtual server CRDs all using the same virtual server and pool due to the use of HostGroup

Tom Cripps

Digital Platform & Network Security Manager


[cid:img_c83ded47-7f94-4294-a5d8-ba09255268b9.jpg]

PHONE


0344 245 9200


ADDRESS


Unit A Brook Park East, NG20 8RY


EMAIL DISCLAIMER
All statements made in this email, including in the attachments, are subject to contract. The contents are not to be regarded as a contractual offer or acceptance unless expressly stated otherwise. Frasers Group Plc is a public limited company incorporated in England (Company No 6035106) with its registered office at Unit A, Brook Park East, Shirebrook, NG20 8RY. This disclaimer also incorporates our full terms and conditions which can be found here<https://frasers.group/legal/disclaimer>.




________________________________

**Comment by thomas-cripps-fg** [comment]
Hi Trinath,

The CRD is not a problem here, we can confirm that is working.

The behaviour we see seems to relate to configuration being overwritten, appreciate AS3 is declarative but with HostGroup does that change anything?


Tom Cripps

Digital Platform & Network Security Manager


[cid:img_c83ded47-7f94-4294-a5d8-ba09255268b9.jpg]

PHONE


0344 245 9200


ADDRESS


Unit A Brook Park East, NG20 8RY


EMAIL DISCLAIMER
All statements made in this email, including in the attachments, are subject to contract. The contents are not to be regarded as a contractual offer or acceptance unless expressly stated otherwise. Frasers Group Plc is a public limited company incorporated in England (Company No 6035106) with its registered office at Unit A, Brook Park East, Shirebrook, NG20 8RY. This disclaimer also incorporates our full terms and conditions which can be found here<https://frasers.group/legal/disclaimer>.



From: Trinath Somanchi ***@***.***>
Date: Wednesday, 5 June 2024 at 06:55
To: F5Networks/k8s-bigip-ctlr ***@***.***>
Cc: Tom Cripps ***@***.***>, Mention ***@***.***>
Subject: Re: [F5Networks/k8s-bigip-ctlr] Support for multiple LTM monitors when using HostGroup (Issue #3442)

@thomas-cripps-fg<https://github.com/thomas-cripps-fg> Please follow the example https://github.com/F5Networks/k8s-bigip-ctlr/blob/2.x-master/docs/config_examples/customResource/VirtualServer/HealthMonitor/monitors-virtual-server.yaml and share your feedback.

**Comment by mdditt2000** [comment]
@thomas-cripps-fg @trinaths  lets take this conversation off GitHub and schedule a meeting to see whats going on. I will send a email.

**Comment by thomas-cripps-fg** [comment]
Thanks Mark.

FYI I’m UK based so BST right now


Tom Cripps

Digital Platform & Network Security Manager


[cid:img_c83ded47-7f94-4294-a5d8-ba09255268b9.jpg]

PHONE


0344 245 9200


ADDRESS


Unit A Brook Park East, NG20 8RY


EMAIL DISCLAIMER
All statements made in this email, including in the attachments, are subject to contract. The contents are not to be regarded as a contractual offer or acceptance unless expressly stated otherwise. Frasers Group Plc is a public limited company incorporated in England (Company No 6035106) with its registered office at Unit A, Brook Park East, Shirebrook, NG20 8RY. This disclaimer also incorporates our full terms and conditions which can be found here<https://frasers.group/legal/disclaimer>.



From: mark dittmer ***@***.***>
Date: Wednesday, 5 June 2024 at 18:13
To: F5Networks/k8s-bigip-ctlr ***@***.***>
Cc: Tom Cripps ***@***.***>, Mention ***@***.***>
Subject: Re: [F5Networks/k8s-bigip-ctlr] Support for multiple LTM monitors when using HostGroup (Issue #3442)

@thomas-cripps-fg<https://github.com/thomas-cripps-fg> @trinaths<https://github.com/trinaths> lets take this conversation off GitHub and schedule a meeting to see whats going on. I will send a email.

**Comment by trinaths** [comment]
Created [CONTCNTR-4797] for internal tracking.

**Comment by mdditt2000** [comment]
Resolved in CIS 2.18 - https://clouddocs.f5.com/containers/latest/reference/release-notes.html
