### ISSUE TITLE
Please provide Custom Resource Definitions with Helm Chart

### ISSUE THREAD

**Issue by svvsigstr** [F5Networks/k8s-bigip-ctlr#3472]
#### Title
Please provide Custom Resource Definitions with Helm Chart

#### Description
In helm-charts/f5-bigip-ctlr, add a folder crds with the CRDs

#### Actual Problem
We use two controllers from F5Networks, f5-bigip-ctlr from this repo and f5-ipam-controller from [this repo](https://github.com/F5Networks/f5-ipam-controller). Installing, upgrading and removing the controllers are done with ansible-playbook and Helm. We want the playbook to install one specific version of the controller. That implies that the version of the CRDs that are installed should not be handled outside or manually, but since Helm does not update CRDs, we need to address that in the playbook. But then the location of the CRDs should preferably not change.
In the v3.0.0-beta-version of the repo, the location has changed.

#### Solution Proposed
Place the CRDs in the folder helm-charts/f5-bigip-ctlr/crds (and similar for the other charts).
Here is an example: https://github.com/percona/percona-helm-charts/tree/main/charts/psmdb-operator.

#### Alternatives
As long as the location of the CRDs do not change depending on the version, any location within the repository is fine (i.e., [this feature request](https://github.com/F5Networks/k8s-bigip-ctlr/issues/3428)).

#### Additional context
N/A

**Comment by vklohiya** [comment]
v3.0.0-beta-version does not support the helm charts yet. Helm chart support will be added in GA release.

**Comment by vklohiya** [comment]
@svvsigstr ,  v3.0.0-beta-version will support BiGIP-Next 20.x. Are you using BIGIP-Next?

**Comment by vklohiya** [comment]
@svvsigstr , For CIS 2.x crds are packaged with helm charts. Please follow the documentation for installing CIS using helm charts https://clouddocs.f5.com/containers/latest/userguide/cis-installation.html#installing-cis-using-helm-charts .

**Comment by svvsigstr** [comment]
@vklohiya: Thanks! I realized later that I hadn't thought this through. I'll look info your suggestions and try to find a solution that will work for us. (We are not using BIGIP-Next. At least not yet.)

**Comment by trinaths** [comment]
For CIS 2.x crds are packaged with helm charts. Please follow the documentation for installing CIS using helm charts https://clouddocs.f5.com/containers/latest/userguide/cis-installation.html#installing-cis-using-helm-charts .
