### ISSUE TITLE
Allow users to omit TargetPort in Route configuration.

### ISSUE THREAD

**Issue by sjberman** [F5Networks/k8s-bigip-ctlr#350]
Currently, if an OpenShift Service is running on a port other than 80 or 443, we require the user to specify that port in their Route configuration.

By default, Routes don't require this field to be populated, so it would be convenient to allow users to ignore this field. The controller would need to grab a port (the first port) off of the Service that the Route refers to, and use that.

This will require a bit of rework in the current structure of the controller. We would need to make sure that the port used for a specific Route doesn't get used for all other Routes during processing (since we process all Routes at the same time). Since we process all Routes for every Service update (regardless if the Service update was for each Route), we would need to get the Service ports for all other Routes as well during this process.

Also be wary of the way we store configs by ServicePort during processing, this may have unknown implications in that aspect.

**Comment by sjberman** [comment]
Something noteworthy: If the Route is created via the OpenShift UI, the targetPort field gets populated with the name of the Service port, not the number of the port. Most ports are named with the convention "8080-tcp", along those lines. The controller should be aware of this naming and attempt to extract the port from the name. We should also consider ports named "https", http", and "tcp" to properly configure the port.

**Comment by chen23** [comment]
@sjberman I believe this should be a higher priority fix.  In OpenShift Origin 1.5.x the GUI will default to a targetport that includes "TCP" and causes the config to fail to load.  The workaround is to edit the YAML to remove "-tcp" and reload the controller.

```
apiVersion: v1
kind: Route
metadata:
  name: simpleweb
  namespace: my-project
  selfLink: /oapi/v1/namespaces/my-project/routes/simpleweb
  uid: 94deede7-aa83-11e7-ae7e-0aec92cc05ee
  resourceVersion: '728026'
  creationTimestamp: '2017-10-06T10:46:17Z'
spec:
  host: simpleweb.f5demo.com
  path: /
  to:
    kind: Service
    name: simpleweb
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
status:
  ingress: null
```

Logs
```
2017/10/11 02:23:51 [INFO] Port '0' for service 'simpleweb' was not found.
2017/10/11 02:23:51 [INFO] Port '0' for service 'simpleweb' was not found.
```

**Comment by amudukutore** [comment]
@chen23 - we will prioritize this work for the next release cycle.

**Comment by sjberman** [comment]
@chen23 Does "8080-tcp" in the Route config match the name of a port in the Service simpleweb?
