### ISSUE TITLE
Support for REQUEST ADAPT Profiles in CIS (VirtualServer CRD or Policy CRD)

### ISSUE THREAD

**Issue by de1chk1nd** [F5Networks/k8s-bigip-ctlr#3511]
#### Title
Support for REQUEST ADAPT Profiles in CIS (VirtualServer CRD or Policy CRD)

#### Description
Provide an option to assign existing Request Adapat profiles to VirtualServer CRD or Policy CRD. this allows ICAP scanning on LTM traffic (w/o requireing aWAF).

#### Actual Problem
Customer wants to use ICAP inspection of "LTM" (Ingress w/o WAF) traffic: https://techdocs.f5.com/en-us/bigip-17-0-0/big-ip-local-traffic-manager-implementations/configuring-content-adaptation-for-http-requests.html

To achieve this, we need to be able to assign request/response adapt profiles. Since this is possible via AS3, we need an option in f5 CRDs, too.

#### Solution Proposed
We need to be able to assign request/response adapt profiles. Since this is possible via AS3, we need an option in f5 CRDs, too.

#### Alternatives
n/a

#### Additional context
n/a

**Comment by trinaths** [comment]
Created [CONTCNTR-4807] for internal tracking.

**Comment by mdditt2000** [comment]
Resolved in CIS 2.18 - https://clouddocs.f5.com/containers/latest/reference/release-notes.html
