### ISSUE TITLE
[LOG] change log level of message "secret: xxx for cluster: yyy should be in the format <namespace/secret-name>"

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3531]
#### Setup Details
 CIS Version : 2.17.1      
 
#### Description  

The following error message:

```
2024/08/23 07:52:54 [WARNING] [MultiCluster]  [MultiCluster] secret: cluster-a2 for cluster: cluster-a2 should be in the format <namespace/secret-name>
```

should be ERROR level because it causes the cluster defined in the ConfigMap to do not be ingested by CIS and trigger the subsequent error:
```
2024/08/23 07:52:54 [ERROR] [MultiCluster] invalid extendedServiceReference: {cluster-a2 nginx default {0 80 } <nil>} for VS: nginx: cluster config for the cluster cluster-a2 is not provided in extended configmap
```

Also, please notice that the string "[MultiCluster]" is shown twice.

**Comment by trinaths** [comment]
Log level are appropriate. no changes.
