### ISSUE TITLE
TLS profile not created in F5 until it's assigned to VS/TS

### ISSUE THREAD

**Issue by avinashchundu9** [F5Networks/k8s-bigip-ctlr#3545]
#### Title
TLS profile not created in F5 until it's assigned to VS/TS

#### Description
When a TLS profile is created in Kubernetes. CIS is not pushing that configuration to F5 until VS/TS associated with that TLS profile

#### Actual Problem
TLS profile with Certmanager is a great way of managing the certificate lifecycle. This should be available for load balancers that are created by CIS and manually created load balancers. 

#### Solution Proposed
Allowing TLS profiles to be created without the need for VS/TS will help manage certificates with load balancers created manually.

**Comment by trinaths** [comment]
TLS profile is attached to VS/TS. Not considering this RFE.
