### ISSUE TITLE
Compatibility of versions >= 20 with BIGIP (_not_ BIG-IP Next)?

### ISSUE THREAD

**Issue by 9numbernine9** [F5Networks/k8s-bigip-ctlr#3610]
#### Title
Compatibility of versions >= 20 with BIGIP (_not_ BIG-IP Next)?

#### Description
(This is a question and not _necessarily_ a feature request). 

Version `20.3.0` of `k8s-bigip-ctlr` was released earlier today - is this version compatible with F5 BIG-IP or does it _only_ work with the newer BIG-IP Next product?

#### Actual Problem
Hello!

I noticed today that a new release (and Docker tag) for version `20.3.0` of the `k8s-bigip-ctlr` image has been released. Is this version compatible with the "regular" (or is it classic now?) BIG-IP product, or does it only work with the newer BIG-IP Next product? 

My concern is that if versions >= `20` are only compatible with BIG-IP Next, then it's somewhat misleading/confusing to have the Docker images named exactly the same. Ideally if there are now different, incompatible Docker images being released then they should have different naming schemes to avoid confusion. 

For some context, we use [Renovate](https://github.com/renovatebot/renovate/) to keep the deployed images of our tools up-to-date, and Renovate has raised a PR to upgrade our currently deployed `2.18.0` controller to `20.3.0`. If `20.3.0` is incompatible with BIG-IP (we are using `17.x`) then we need to write some unusual configuration to have Renovate ignore versions >= 20 of this image. (Users of Dependabot or other similar tools would find themselves in the same situation.)

#### Solution Proposed
Assuming the currently released `20.3.0` version is incompatible with BIG-IP `17.x` and older, then ideally I think the image should be released separately as `f5networks/k8s-bigip-next-ctlr` in order to avoid overlap with the previous `k8s-bigip-ctlr` images.

#### Alternatives
Ensure that the images being published are compatible with both BIG-IP _and_ BIG-IP Next? (If this is possible, the documentation should make this abundantly clear.)

#### Additional context
N/A

**Comment by trinaths** [comment]
We will tag and name the release image to reflect the same.
