### ISSUE TITLE
BIG-IP Server SSL profiles configured by the controller do not specify to validate the server certificate

### ISSUE THREAD

**Issue by f5gary** [F5Networks/k8s-bigip-ctlr#363]
While testing the controller with a Server SSL profile that should not be able to validate the server's certificate, I discovered that the validations always succeed. Upon further examination, I discovered that server certificate validation is not being configured in the SSL profile. The specific option that needs to be enabled on the Server SSL profile is in the BIG-IP GUI in the "Server Authentication" section and is named "Server Certificate". It should be set to "require". Currently the CCCL module that is used to configure SSL profiles does not provide a way to configure this value.

**Comment by amudukutore** [comment]
This is compatible with the current behavior supported by F5Router - removing P2 tag.

**Comment by f5gary** [comment]
This issue has been fixed.
