### ISSUE TITLE
AS3 version which supports incremental changes

### ISSUE THREAD

**Issue by surendarmsk1** [F5Networks/k8s-bigip-ctlr#3656]
Setup Details
CIS Version : 2.9.1
Build: f5networks/k8s-bigip-ctlr:v 2.9.1
BIGIP Version: Big IP 2.9.1
AS3 Version: 3.28.0
Orchestration: K8S/OSCP
Pool Mode: Nodeport

As per https://github.com/F5Networks/k8s-bigip-ctlr/issues/3220 - Do we have latest version releases where AS3 will perform incremental changes instead of creating POST call for entire json list.?

**Comment by trinaths** [comment]
@surendarmsk1  Please use CIS 2.18.1 and AS3 latest and validate the issue.
