### ISSUE TITLE
Configure weight ratio for K8S pool members

### ISSUE THREAD

**Issue by sachinborade22** [F5Networks/k8s-bigip-ctlr#3677]
Hi Mark,

1. Describe the new feature in as much detail as possible.
--> The K8S pool member's hardware is heterogeneous, which results in varying performance and occasionally causes issues as some nodes perform good while others become overloaded with the same QPS because all nodes receive the same amount of traffic and there is no way to adjust the weight ratio.

 
2. What is the problem that would be resolved by adding this new feature?
--> We would be able to set appropriate weight ratio per pool members accordingly capacity
 

3. What is the business impact to your site due to the lack of this?
--> This is resulting in service degradation and causing higher latency/timeout issues.

**Comment by trinaths** [comment]
@sachinborade22 

Request more info.
 

1. Is this for CRDs  or other CIS managed resources ?
2. Since the node infra is heterogeneous, share example YAML manifests with desired configuration.

**Comment by trinaths** [comment]
Closing this issue. considering the SR 00758115
