### ISSUE TITLE
Ability to specify tcp profile、http profile、awaf policy in Ingress annotations

### ISSUE THREAD

**Issue by guardian0916** [F5Networks/k8s-bigip-ctlr#3678]
**Title：**
Ability to specify tcp、http、awaf、 profile in Ingress annotations

 **Description：**
Currently, we cannot add a tcp profile, http profile, or awaf policy to the ingress,as the annotation，which greatly limits functionality.I've seen the issue：Ability to specify http profile in Ingress annotations #3161,the answer is that crd can be used,I would like to ask if there are any updates to the current features if only ingress is used。

#### Solution Proposed
 1.can we customize the parameters of the ingress annotation?
2.Are there plans to add ingress annotation options in the future?

#### Alternatives
none

#### Additional context
none

**Comment by trinaths** [comment]
@guardian0916 - CRDs are similar to Ingress resources and are more advanced and stable. With BIG-IP Next, CIS 20.x will support GatewayAPI for Ingress. 

How many Ingress resources does CIS manage as per your usecase ? Please share more info to  [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com)

**Comment by guardian0916** [comment]
the CIS should manage the coustom tcp profile、http profile、log profile 、awaf policy

**Comment by mdditt2000** [comment]
Please use TS/VS CRD with policy CRD for all profiles and profiles. No additional additions to Ingress due to the shift towards Gateway API. Everything can be achieved with s simple CRD.

**Comment by guardian0916** [comment]
OK！I see! Thank you!

**Comment by trinaths** [comment]
closing this issue.
