### ISSUE TITLE
Support ConfigMap and Ingress watch labels (similar to route-label)

### ISSUE THREAD

**Issue by sjberman** [F5Networks/k8s-bigip-ctlr#398]
Current functionality for ConfigMap and Ingress management is to watch all ConfigMaps (with virtual-server label) and all Ingresses for all namespaces managed by the controller.

However, a user may want to run multiple controllers, watching all namespaces, and have each controller manage a subset of ConfigMaps and/or Ingresses. We currently support functionality for OpenShift Routes to specify a label that the controller will watch for. This label is user-chosen, so in theory a user could have Routes with different labels in the same namespace, and have multiple controllers manage different Routes without collisions.

We should support this same label functionality for ConfigMaps and Ingresses.

**Comment by trinaths** [comment]
From 1.13, We implemented Ingress.class and manage-ingress-class-only annotation for ingress.
