### ISSUE TITLE
What is the oldest version of BIG-IP supported by F5 Controller?

### ISSUE THREAD

**Issue by snsumner** [F5Networks/k8s-bigip-ctlr#405]
I found nowhere in the documentation that indicates what versions of BIG-IP are supported by F5 Controller. It would be helpful to know what is the oldest version (e.g. 10.x, 11.x, 12.x, 13.x) supported.

**Comment by swormke** [comment]
Hi @snsumner the versions supported are listed here: http://clouddocs.f5.com/containers/v1/releases_and_versioning.html

Let us know if you need any more information or do not find what you are looking for on [clouddocs.f5.com](http://clouddocs.f5.com)

**Comment by amudukutore** [comment]
As @swormke says, we test against BIG-IP versions 11.6.1+, v12.x, v13.x. Please let us know if this addresses your issue.

**Comment by sjsharma2001** [comment]
Closing this issue since the question has been answered.
