### ISSUE TITLE
Events published to Ingress resources in multiple namespaces result in confusing error messages

### ISSUE THREAD

**Issue by f5gary** [F5Networks/k8s-bigip-ctlr#417]
When the controller is handling Ingress resources in multiple namespaces, errors appear in the controller log after publishing events on the Ingress resources. This behavior has not yet been seen when all of the Ingress resources are within the same namespace.

E1107 01:50:59.704583       1 event.go:208] Unable to write event: 'can't create an event with namespace 'kube-system' in namespace 'testing'' (may retry after sleeping)
E1107 01:50:59.704585       1 event.go:208] Unable to write event: 'can't create an event with namespace 'testing' in namespace 'kube-system'' (may retry after sleeping)

**Comment by amudukutore** [comment]
Are these messages harmless? 
Are they triggering new config actions each time through the config reconcile loop?

**Comment by f5gary** [comment]
I do not believe they are triggering new config actions. What is happening from a user perspective is these error messages appear in the controller log and the event is not being applied to the Ingress resource, so information displayed by the "kubectl describe ingress" command is not complete.
