### ISSUE TITLE
Need to document required user roles for the BIG-IP controllers.

### ISSUE THREAD

**Issue by kmunson1973** [F5Networks/k8s-bigip-ctlr#426]
#### Description
Configured a BIG-IP user with manager permission on dedicated partition, this partition also held the vxlan self, and tunnel.  When instantiated the CC I receive this error:
2017/11/15 01:59:01 [ERROR] [2017-11-15 01:59:01,098 f5_cccl.utils.network ERROR] Failed to configure the FDB for VxLAN tunnel /K8s/osevxlan: 400 Unexpected Error: Ba                       d Request for uri: https://10.105.157.201:443/mgmt/tm/net/fdb/tunnel/~K8s~osevxlan/?ver=11.5.0

If I set the user to admin privileges everything works.  With the manager permissions the VIP and Pool objects are created it looks like that the fdb table entries do not get updated.

#### Kubernetes Version
OCP 3.6

#### Controller Version
1.3

#### BIG-IP Version
12.1.1
#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by russokj** [comment]
To create network resources, you need user with a role of resource-manager or greater. The manager role can only create LTM resource, like you observed.  We'll make sure the documentation is updated to describe this.

**Comment by russokj** [comment]
There are three roles that the controller use can have:
   Admin, Resource-Administrator, Manager
These are described here: https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-concepts-11-5-0/10.html and are listed in order of allowed permissions with Admin having the highest permissions.
More importantly, the following minimum role required by our various controllers are: 
Bigip-k8s-controller (cluster mode) - resource-administrator
Bigip-k8s-controller (node mode) - manager
Bigip-marathon-controller - manager
Bigip-cf-controller - manager
