### ISSUE TITLE
Virtual servers consistently updated when there are no changes

### ISSUE THREAD

**Issue by sjberman** [F5Networks/k8s-bigip-ctlr#428]
Virtual servers are being updated at every verify-interval:

```2017/11/16 15:42:43 [INFO] [2017-11-16 15:42:43,950 f5_cccl.resource.resource INFO] Updating ApiVirtualServer: /test/default_svc-1-ingress_http```

Nothing is changing on the virtual server, but there must be a field that doesn't match CCCL's expectations, resulting in unnecessary updates.

**Comment by amudukutore** [comment]
While fixing this, we should look at adding info about the change in configs that triggers these actions (at default log level - info) to make it easier to diagnose these issues going forward.
