### ISSUE TITLE
OpenShift Documentation issue VTEP

### ISSUE THREAD

**Issue by kmunson1973** [F5Networks/k8s-bigip-ctlr#436]
#### Description
Documentation issue:

http://clouddocs.f5.com/containers/v1/openshift/kctlr-use-bigip-openshift.html
Indicates that you have to set the port lock down to allow all, this enables both SSH and HTTPS access to the self ip, which is not a requirement to terminate a vtep connection.

admin@BIG-IP(cfg-sync Standalone)(Active)(/Common)(tmos)$ create net self 10.129.2.10/14 allow-service all vlan openshift_vxlan
 This should be sufficient for our OCP integration
admin@BIG-IP(cfg-sync Standalone)(Active)(/Common)(tmos)$ create net self 10.129.2.10/14 allow-service none vlan openshift_vxlan

#### Kubernetes Version
OpenShift 3.6
#### Controller Version
1.3
#### BIG-IP Version
12.x/13.x
#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by jputrino** [comment]
This change is included in v2 of the solution docs: http://clouddocs.f5.com/containers/v2/openshift/kctlr-use-bigip-openshift.html#k8s-openshift-create-bigip-self-ip

v1 is deprecated
