### ISSUE TITLE
Investigate and document behavior when controller cannot communicate with BIG-IP

### ISSUE THREAD

**Issue by amudukutore** [F5Networks/k8s-bigip-ctlr#438]
#### Description
Investigate what happens when the controller cannot communicate with the BIG-IP (at startup time and also once it has established a connection once). This behavior should be documented (perhaps in the troubleshooting section). Also, if the behavior is unreasonable, file a follow up issue.

**Comment by sjsharma2001** [comment]
Investigate the crash behavior as reported in #280.

**Comment by f5yacobucci** [comment]
The behavior should also be consistent. Once the controller connects to a BIG-IP and then operations fail it enters a backoff loop retrying new operations. This behavior can be duplicated for the startup case where it will probably exit from code inspection.

Not being able to connect to the bigip is a recoverable error which can be retried and logged, notifying administrators to problems as the error repeats.

**Comment by amudukutore** [comment]
Changing to P3 based on scope of task. This should be fixed in the 1.5 timeframe.

**Comment by vincentmli** [comment]
I agree with what f5yacobucci says. in my deployment scenario, I run a local only k8s environment https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md and there is no BIGIP available for connection, this would help on testing/debugging/troubleshooting when I find solutions for customers issues

**Comment by russokj** [comment]
If the controller cannot communicate with the BIG-IP on startup, it will terminate.  With the release of 1.4.0 of the controller, a backoff loop will be entered if the controller stops communicating with the BIG-IP (previously it would hang).

There needs to be an additional change to allow the controller to keep running on certain startup errors (like failure to communicate with BIG-IP).

**Comment by devarti** [comment]
I get following error while f5 controller connector container trying to connect to bigip

Error from server: Get https://HOSTNAME:10250/containerLogs/kube-system/k8s-bigip-ctlr-deployment-2874000839-ckjkn/k8s-bigip-ctlr: dial tcp BIGIP:10250: getsockopt: no route to host
