### ISSUE TITLE
Clouddocs showing incorrect version of k8s controller

### ISSUE THREAD

**Issue by sjsharma2001** [F5Networks/k8s-bigip-ctlr#527]
#### Description
Clouddocs is showing incorrect version of k8s controller (v1.4.2)

#### Kubernetes Version
Any

#### Controller Version
v1.4.0

#### BIG-IP Version
Any

#### Diagnostic Information
Visit http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.4/
It shows "F5 BIG-IP Controller for Kubernetes v1.4.2" in the left frame.
It should show the correct version (v1.4.0)

**Comment by amudukutore** [comment]
Fixed as part of https://github.com/F5Networks/k8s-bigip-ctlr/pull/532.
