### ISSUE TITLE
[DOC] [BIG-IP Setup for VXLAN] add a Floating IP to the VXLAN tunnel 

### ISSUE THREAD

**Issue by nmenant** [F5Networks/k8s-bigip-ctlr#533]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>
related pages: 

- http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-bigip-k8s.html

- http://clouddocs.f5.com/containers/v2/openshift/kctlr-use-bigip-openshift.html

Description: 
When we follow those pages and setup a Self IP (non floating) for the VXLAN network, we will be able to see our pool members switching to green (if monitors have been setup) if an app is already deployed and CC is in place. Unfortunately, it’s more than likely that the Virtual server won’t work.
 
One of the reason is the use of SNAT Automap. When you use SNAT automap, here is the behavior of it ([overview of SNAT automap](https://support.f5.com/csp/article/K7336)):
 
The secure network address translation (SNAT) Automap feature selects a translation address from the available self IP address in the following order of preference:

1. Floating self IP addresses on the egress VLAN
2. Floating self IP addresses on different VLANs
3. Non-floating self IP addresses on the egress VLAN
4. Non-floating self IP addresses on different VLANs

 
When we will use a BIG-IP that is already in production, it is more than likely that Floating IP have been set to ensure proper failover:

- Failover of the External network (hosting the VS IP)
This allow to potentially not break the client connection or at least disrupt the client session
Will allow to trigger some security feature on switches/FW that are not happy when suddenly a VS IP change it’s MAC address (when you create a floating, it gets a virtual MAC). If you don’t use a floating, the new BIG-IP will do a ARP broadcast to change the IP/MAC for the VS and some security product block it.

- Failover of the Internal network.
Some people use the BIG-IP as an edge device and we can be the default gateway for a VLAN. Then you need a floating too.
 
The issue we hit then is the following:

1. Client try to connect to the VS created by CC on the BIG-IP (lots of default config pushed by cc enable snat automap). It works and a LB decision is done.

2. BIG-IP sees that SNAT automap is setup on the VS and then look for a Floating IP to use as a source IP to forward the traffic. Since we haven’t set a floating IP in the VXLAN overlay, the BIG-IP will use another VLAN and its route to send the traffic somewhere. THIS IS WHERE IT FAILS AND WE CAN’T ACCESS THE resource

@chen23 @pcloup @kmunson1973 @pdp2shirts for comments

What would be ideal is to add on the mentioned pages the creation of a Floating IP for the vxlan network. After this section: 
`If you don’t specify a traffic group, the self IP will use the BIG-IP system’s default.

admin@BIG-IP(cfg-sync Standalone)(Active)(/Common)(tmos)$ create net self 10.244.30.15/16 allow-service all vlan flannel_vxlan
`
add something like (for the flannel kubernetes page): 

`if you use a BIG-IP cluster, you will also need to add a Floating IP to the cluster:

admin@BIG-IP(cfg-sync Standalone)(Active)(/Common)(tmos)$ create net self 10.244.30.16/16 allow-service all traffic-group traffic-group-1 vlan flannel_vxlan
`
#### Kubernetes Version
<Version of Kubernetes being used>
True for all versions
#### Controller Version
<Version of k8s-bigip-ctlr being used>
True for all versions
#### BIG-IP Version
<Version of BIG-IP being used>
True for all v11, v12 and v13
#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by jputrino** [comment]
Issue moved to [F5Networks/f5-ci-docs #353](https://github.com/F5Networks/f5-ci-docs/issues/353) via [**ZenHub**](https://www.zenhub.com/)
