### ISSUE TITLE
iApp deployment: connection request queuing is not declarative friendly

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#534]
#### Description

When deploying an iApp the pool is initially created empty but this is not compatible with the connection request queuing feature, the following error is returned by the BIG-IP:

```
0107006b:3: Connection limit-based connection request queuing for pool /mcd/coolstore_coolstore-gwy.dc-onp.mcd.bd.f5.com.app/coolstore-gwy.dc-onp.mcd.bd.f5.com__pool requires at least one pool member or node to have a connection limit.
```
This feature is included in the widely used f5.http iApp.

The issue is not in k8s-bigip-ctlr's code. A workaround could be to create a dummy initial pool member in the iApp. To properly solve this I think this should be fixed in BIG-IP's code.

#### Kubernetes Version
openshift v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
#### Controller Version
NA
#### BIG-IP Version
BIG-IP 12.1.2

#### Diagnostic Information

```
2018/01/31 12:00:54 [INFO] [2018-01-31 12:00:54,220 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /mcd/coolstore_coolstore-gwy.dc-onp.mcd.bd.f5.com
2018/01/31 12:00:54 [ERROR] [2018-01-31 12:00:54,447 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiApplicationService) /mcd/coolstore_coolstore-gwy.dc-onp.mcd.bd.f5.com.
2018/01/31 12:00:54 [ERROR] [2018-01-31 12:00:54,448 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://10.105.157.198:443/mgmt/tm/sys/application/service/
2018/01/31 12:00:54 [INFO] Text: u'{"code":400,"message":"0107006b:3: Connection limit-based connection request queuing for pool /mcd/coolstore_coolstore-gwy.dc-onp.mcd.bd.f5.com.app/coolstore-gwy.dc-onp.mcd.bd.f5.com__pool requires at least one pool member or node to have a connection limit.","errorStack":[],"apiError":3}'
2018/01/31 12:00:54 [ERROR] [2018-01-31 12:00:54,448 f5_cccl.service.manager ERROR] Resource /mcd/coolstore_coolstore-gwy.dc-onp.mcd.bd.f5.com creation error, requeuing task...
```

**Comment by mdditt2000** [comment]
CIS 1.9 will be using AS3 from next month. Connection request queuing is currently set to NO in AS3. AS3 doesn't have a value change the setting from NO to YES. If connection request queuing is a requirement i will open a issue with the AS3 team.  

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html?highlight=enable%20request%20queueing#pool

Closing this issue for now. Will open a new issue with the AS3 board if required.
