### ISSUE TITLE
Setting verify-interval to 0 should mean disable verification

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#538]
#### Description
Hi all, 

When setting the verify-interval parameter to 0 internally the value is set to the default value (30 seconds). As per conversation with Matt Y setting this parameter to 0 should disable verifying.

Being able to disable verification is important given that the verification actually means rewrite the configuration, overwriting settings which might be required for for debugging and troubleshooting purposes.

#### Kubernetes Version
NA
#### Controller Version
All
#### BIG-IP Version
NA
#### Diagnostic Information
NA

**Comment by trinaths** [comment]
There are no enhancements to CCCL. This feature is not supported. CIS with agent AS3 will only post the change to BIG-IP when there is a change in monitored resources.
