### ISSUE TITLE
Move from configMaps to CRDs

### ISSUE THREAD

**Issue by johscheuer** [F5Networks/k8s-bigip-ctlr#579]
#### Description
Enhancement:

Since Kubernetes 1.7 [CustomResourceDefinitions](https://kubernetes.io/docs/concepts/api-extension/custom-resources/#customresourcedefinitions) are available. CRDs allow a much more tighter integration into Kubernetes than only using ConfigMaps see: https://kubernetes.io/docs/concepts/api-extension/custom-resources/#should-i-use-a-configmap-or-a-custom-resource. 

Moving from ConfigMaps to CRDs allows users to use 'kubectl' fo inspect the resources (instead of fetching all ConfigMaps with the specific label). Also this allows to send Kubernetes events and use the `.status` field of a CRD (to see if a Resource is successfully created without digging into the F5 CTLR logs).

Also CRDs allow validation of the resources: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation which means that a user will be notified if he missed a required field or used a wrong data type (or pattern). In the current setup a user would only recognise a bad configured ConfigMap for the BigIP when he looks into the logs of the F5 K8s CTLR (or the Prometheus metrics).

#### Kubernetes Version
1.7+

**Comment by roldancer** [comment]
Any idea when bigip-ctlr will support CRD ?

Thanks

**Comment by russokj** [comment]
We definitely see advantages to supporting CRDs.  However, supporting the feature isn't on the immediate road map.

**Comment by mdditt2000** [comment]
Once OpenShift Routes and Ingress has being mapped to AS3 we going to introduce CRDs. CRDs will be an abstracted AS3 declaration. Coming soon!

**Comment by mdditt2000** [comment]
Epic for CRC Alpha CONTCNTR-1506 for PM tracking. Alpha is scheduled for CIS 2.0

**Comment by mdditt2000** [comment]
Completed with the release of CIS 2.0. Please review https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/crd/CustomResource.md

**Comment by sbarre-esit** [comment]
@mdditt2000 ETA on when this will be GA and not ALPHA? Also when it will support non-http ports?
