### ISSUE TITLE
Sample usage for config parameters - node-label-selector

### ISSUE THREAD

**Issue by amudukutore** [F5Networks/k8s-bigip-ctlr#588]
#### Description
A handful of controller configuration parameters have an example that demonstrates the proper formatting/usage of the parameter in the product documentation. However, a majority of these do not have examples (for example, 'namespace-label', 'node-label-selector'). The ask here is to look through all config parameters and supplement them with examples as necessary.

**Comment by mdditt2000** [comment]
CIS 2.0 new documentation improvements.

**Comment by mdditt2000** [comment]
**Manage node labels**

When using nodeport by default all nodes from the cluster will be added to the pool. In most cases you only want to add the worker nodes and exclude master nodes. To exclude master nodes using the label node-role.kubernetes.io/node parameter

Use the label node <node name> to create a new label for the node. This works in conjunction with the node-label-selector configured in CIS to only add nodes to the pool with the associated <node name>. In this quick start guide CIS will only add the nodes with label worker to the pool. Excluding the master node from the pool 

```
# kubectl label nodes k8s-1-18-node1.example.com node-role.kubernetes.io/f5role=worker
# kubectl label nodes k8s-1-18-node2.example.com node-role.kubernetes.io/f5role=worker
```
Show the node labels
```
# kubectl get nodes
NAME                         STATUS   ROLES    AGE     VERSION
k8s-1-18-master.example.com   Ready    master   7d19h   v1.18.0
k8s-1-18-node1.example.com    Ready    f5role   7d19h   v1.18.0
k8s-1-18-node2.example.com    Ready    f5role   7d19h   v1.18.0
```
args: 
     - "--bigip-username=$(BIGIP_USERNAME)"
     - "--bigip-password=$(BIGIP_PASSWORD)"
     - "--bigip-url=192.168.200.92"
     - "--bigip-partition=k8s"
     - "--namespace=default"
     - "--pool-member-type=nodeport" - As per code it will process as nodeport
     - "--log-level=DEBUG"
     - "--insecure=true"
     - "--manage-ingress=false"
     - "--manage-routes=false"
     - "--manage-configmaps=true"
     - "--agent=as3"
     - "--as3-validation=true"
     **- "--node-label-selector=f5role=worker"**
```

**Comment by mdditt2000** [comment]
Documented https://github.com/mdditt2000/kubernetes-1-18/blob/master/kubernetes-faq.md#manage-node-labels Closing issue out

**Comment by AMoghrabi** [comment]
Hey @mdditt2000 , do you know if its possible to specify more than one label?
