### ISSUE TITLE
Debug logs are impossibly verbose

### ISSUE THREAD

**Issue by sjberman** [F5Networks/k8s-bigip-ctlr#596]
#### Description
Between controller, CCCL, sdk, and the requests library, the DEBUG logs spit out too much to easily process. We should look into adding requests and maybe sdk logs to another log level (trace). This will help make debug logs actually useful

#### Kubernetes Version
1.8

#### Controller Version
1.4

#### BIG-IP Version
12.1

**Comment by ssurenr** [comment]
Removing the Python SDK reduces the debug logs significantly. This item shoud be evaluated post 2.0 release.

**Comment by mdditt2000** [comment]
Moving to agent based logging we should significant less logging in CIS.

**Comment by mdditt2000** [comment]
This issue is resolved in CIS 2.0 with improved logging for AS3. No additional enhancements for CCCL planned
