### ISSUE TITLE
multiple cluster support?

### ISSUE THREAD

**Issue by zetaab** [F5Networks/k8s-bigip-ctlr#598]
Is there multiple cluster support in this k8s-bigip integration? What we would like to have is that we have two separate clusters like `*.dc1.example.com` and `*.dc2.example.com`. In both of these clusters we have same application running in for instance `foo.dc1.example.com` and `foo.dc2.example.com`. We would like to have "HA endpoint" for these using F5. So the url `foo.dc.example.com` should do healthcheck to both of these clusters and loadbalance between `foo.dc1.example.com` and `foo.dc2.example.com` according to settings in annotations. Is this currently possible with this controller?

Some guys are saying that this is possible, but I cannot find any documentation which says this thing clearly. So is multiple clusters supported in this way?

**Comment by f5yacobucci** [comment]
Are you licensed for BIG-IP DNS? The controller is not multi-cluster aware at the moment. We are actively working towards this goal, probably a separate controller that should hopefully plug into cluster-registry and the internal plumbing of kubemci but we haven't gotten there yet.

At this moment, if you're using BIG-IP DNS you can manually create the Data Center, Servers, WideIP, and Listeners to do GSLB between the individual dc1 and dc2 LTMs. Each LTM can be automatically updated with a CC running locally. Right now, there will need to be a split of manually tasks to configure the BIG-IP global load balancing and then automation for the individual cloud ingress.

**Comment by rajatjindal** [comment]
Hi @f5yacobucci 

We are trying to achieve same thing except that we want ELB instead of LTM. is this still possible?

when i am trying to add a pool using ELB name (or its cname), it adds only one IP but that ELB is HA and has 3 IP. 

is it possible to add all the 3 IP address like that?

**Comment by trinaths** [comment]
Multi cluster support can be achieved using AS3 DNS. post CIS 2.1 we want to revisit multi cluster support.
