### ISSUE TITLE
Enhancement Request: persistence profile for Ingress

### ISSUE THREAD

**Issue by iljaweis** [F5Networks/k8s-bigip-ctlr#611]
#### Description
Enhancement Request: 

We have an application that relies on session persistence. Right now, the virtual service is manually managed with a persistence profile.

We would like to be able to choose a persistence profile when deploying an Ingress resource that is managed by k8s-bigip-ctlr.

**Comment by amudukutore** [comment]
@iljaweis - this is on our roadmap for our next release cycle (i.e., release timeframe around 3-4 months). Is there a specific persistence profile you were interested in (cookie, source-address, destination-address, SSL, etc)?

**Comment by iljaweis** [comment]
Thanks @amudukutore. We're mostly using cookie or custom profiles derived from cookie.

**Comment by mrwulf** [comment]
:+1: 
We would also like to see the `source-address` persistence profile

**Comment by mzahorik** [comment]
I'd love to see this officially too.  I'm running a fork that I added support for this (and static iRule references), but only for Ingress objects (and currently without test cases) at https://github.com/mzahorik/k8s-bigip-ctlr/blob/irules_and_persistence/docs/README.rst

We use a primary of /Common/ssl and a fallback of /Common/source_addr, but in some cases we would use cookie persistence.

**Comment by Joshua-Barclay** [comment]
Is there a workaround for this issue, even one requiring manual configuration? For an application requiring session-affinity (most web-apps) this is a deal-breaker unless your network configuration allows you to disable SNAT on the F5, which we can't.

@mzahorik's pull request, which requires the persistence profile to already exist, would suit us perfectly. Is there any way to achieve similar functionality using an official release?

**Comment by mzahorik** [comment]
@Joshua-Barclay My pull request shouldn't be used.  The F5-CCCL library or the Python client embedded in the controller needs more logic to handle persistence profiles, as the F5 accepts a single string as a persistence profile (ie. "persist":"/Common/source_addr") but the F5 returns an array of persistence profiles.  This causes the F5-CCCL library to detect a difference, and goes into a modification loop.

F5 recently said they'd enable whitelisting, where you create the virtual servers, pools, etc in advance and the k8s-bigip-ctlr only manages pool members.  I haven't tried it.

They also have the ability to deploy iApps, where you script the virtual server build using the bigip internal scripting language.

I decided to forego all the above, and wrote a pure Go Kubernetes-only single-path ingress-only F5 controller that met our business needs.  It's much simpler as a result of not supporting configmaps, openshift, etc.  It's named f5-ingress-ctlr under my github account.  It supports many of the F5 annotations, but not all, and adds persistence profiles and static iRule references.  I also dropped in Infoblox integration.

If it's useful to you, let me know.  It could use more polish, such as test cases, better docs, and a move away from polling Kubernetes to an event notification model, but it has been deployed in our lab/non-prod clusters for several months, and has been live in production for the past few weeks on one of our key SaaS applications.  There have been no functional issues.

**Comment by Joshua-Barclay** [comment]
@mzahorik thank you for such a thorough response. The mention of your PR was more a note to the F5 team in regards to the API you'd added. I'm in a large enterprise and cannot consider using anything other than an official release unfortunately.

Your suggestion to use the iApps ConfigMap support was a very good one - I've managed to configure an equivalent solution with the addition of cookie based session persistence. I'm not sure if this is an appropriate place but I'm going to dump the config map configuration that worked for me for future visitors from google:
based one https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.6/#f5-resource-configmap-properties
```
metadata:
  name: [service-name].vs.http
  namespace: default
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "[service-name]",
          "servicePort": 8080
        },
        "frontend": {
          "partition": "k8s",
          "iapp": "/Common/f5.http",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "[service-name].http iApp"
          },
          "iappVariables": {
            "monitor__monitor": "/#create_new#",
            "monitor__response": "none",
            "monitor__uri": "/",
            "net__client_mode": "wan",
            "net__server_mode": "lan",
            "pool__addr": "[VIP IP]",
            "pool__pool_to_use": "/#create_new#",
            "pool__port": "80",
            "pool__persist": "/#cookie#",
            "client__use_wa": "no",
            "client__standard_caching_without_wa": "/#do_not_use#"
          }
        }
      }
    }
```

**Comment by mdditt2000** [comment]
We are making some enhancement to the cfgmap. Integrating a declarative API coming April. You can get more information on this declarative API at https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/

With the use of the declarative API you can simply enable any advanced option available on big-ip today. Persistence will be enabled by default based on the servicehttp as shown in the AS3 documentation.

**Comment by walter-heestermans-toyota** [comment]
Is there now a solution for persistence profile when creating Kubernetes Ingress resources?

**Comment by mdditt2000** [comment]
CIS 1.9 released next month will support AS3. AS3 provides every persistence profiles on BIG-IP
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html?highlight=enable%20request%20queueing#persist-cookie

Closing this issue out since support will be in CIS 1.9
