### ISSUE TITLE
Enhancement: Allow arbitrary iRules

### ISSUE THREAD

**Issue by mzahorik** [F5Networks/k8s-bigip-ctlr#613]
#### Description

We have multiple applications that use iRules today, and they are transitioning to Docker containers.  I see that the go-based controller can pass iRules to the Python script for instantiation, but these appear to be all hard-coded within the go code for specific purposes.  We'd like to be able to define iRules in configmaps/annotations and have them passed along to be created with the virtual server.

The simplest use case is an iRule that adds the real client IP in a header for SSL terminated and re-encrypted on the F5.

#### Kubernetes Version
1.9.3

#### Controller Version
1.4.2

#### BIG-IP Version
BIG-IP 12.1.3 Build 0.0.378

**Comment by alonsocamaro** [comment]
@mzahorik have you considered deploying the iRules with iApps? These can be deployed with config maps.

I take the opportunity of suggesting you to take a look to my project https://github.com/f5devcentral/f5-tmsh2iapp

**Comment by mzahorik** [comment]
@alonsocamaro I have those on the team dedicated to the F5s looking at that as an alternative.

We're using the ingress implementation, as this is more consistent for our developers, and a recent commit added serverssl support to ingress but not configmap.

This ticket really was to spur discussion.. is this a feature on the roadmap, if so, how soon?  An initial implementation would be to just add a iRule field that accepts an array of pre-defined iRules in, say, /Common.  Later enhancements could accept arbitrary text to add adHoc rules visible in the YAML instead of opaque rules in the F5.

I'm glad to work on the former if it's not already being worked on and someone can point me the right direction.

**Comment by alonsocamaro** [comment]
@mzahorik btw, I'm not part of product development/product management. I'm sure they will join the discussion soon.

**Comment by russokj** [comment]
There are plans to reach SSL-support parity (with Openshift Routes) for both Ingress and Configmaps resources in an upcoming release.  However, we do not plan to support generic iRules as annotations.   There are too many issues in regards to supporting such a feature.

In the next release, we will be providing a feature that allows specific virtual servers within the managed partition to be whitelisted.  This will give the user the ability to create their own virtual servers, or modify virtual servers created by the controller (for example, using an ansible script).  However, a word of caution has to be mentioned in whitelisting virtual server resources created and/or managed by the controller.  The user needs to ensure that the customization they make will not interfere with the behavior expected by the controller in the particular orchestration environment.

**Comment by mzahorik** [comment]
Hi @russokj, can you elaborate on the issues in supporting this feature?

Would the simpler use case I mention, where already defined iRules on the F5 are simply associated with the new virtual server, run afoul of the issues you allude to?

An example would be an annotation such as virtual-server.f5.com/iRules: "[ '/Common/Add-XFF' ]"

**Comment by russokj** [comment]
We realize that users might have a need to perform some customization of resources (like virtual servers) that the controller manages in the orchestration environment.  Using annotations would be one method for allowing this customization to occur (as the proposed iRule annotation above would do).  However, we want to keep to a minimum the set of annotations the CC is responsible for so that they can be fully tested, supported, and documented (the more annotations we add, the more permutations we need to test).  

We decided to provide a different, and hopefully more generic way, for users to do their customization by allowing resources to be whitelisted.  A whitelisted resource will be allowed to exist, as is, in the partition being managed by the controller.  The controller may attempt to modify the resource, if necessary, but its up to the end user to verify that the resulting changes work with the customization they performed.

**Comment by mzahorik** [comment]
I hear you on ballooning testing permutations.

I argue that iRules are one of the key competitive features of the F5s, and the simpler annotation I proposed would minimize testing relative to a more ad-hoc "I'll take anything in a blob" approach.  I expect your users (like myself) would expect simple use cases of a key feature to be managed by the controller without having to construct a parallel solution to deploy iRules.

If I submit a PR including an iRule annotation and tests, would it be considered and of sufficient quality, accepted?

**Comment by russokj** [comment]
After discussing this with colleagues, the decision was made to not accept a feature that modifies the controller to accept a list of arbitrary iRules, specified as annotations within the orchestration resource.   

We will be offering a feature in the upcoming release that supports whitelisted Big-IP resources where the controller will add, if necessary, its customization to the resource but otherwise leave it alone. In this case, the user takes full responsibility for the resulting config.  This feature may or may not help you in your need.

If not, feel free to fork the repo and modify the forked version to include your feature.

**Comment by evanhfox** [comment]
> After discussing this with colleagues, the decision was made to not accept a feature that modifies the controller to accept a list of arbitrary iRules, specified as annotations within the orchestration resource. We will be offering a feature in the upcoming release that supports whitelisted Big-IP resources where the controller will add, if necessary, its customization to the resource but otherwise leave it alone. In this case, the user takes full responsibility for the resulting config. This feature may or may not help you in your need.

Is the ability to whitelist certain resources (such as iRules, TCP Profiles, ect) still planned or in-development? Trying to figure out how I can apply a custom iRule that uses the universal persistence engine so I can customize persistence as needed.

**Comment by vincentmli** [comment]
I had a simple patch to add custom irule from Common partition to ingress with a new annotation, the patch may need more improvement as when updating the ingress irule annotation lively without deleting and re-adding the ingress, the irule will not be updated.

<pre>
diff --git a/pkg/appmanager/appManager.go b/pkg/appmanager/appManager.go
index b6084d8..4ce57bc 100644
--- a/pkg/appmanager/appManager.go
+++ b/pkg/appmanager/appManager.go
@@ -66,6 +66,7 @@ const f5VsAppRootAnnotation = "virtual-server.f5.com/rewrite-app-root"
 const f5ClientSslProfileAnnotation = "virtual-server.f5.com/clientssl"
 const f5ServerSslProfileAnnotation = "virtual-server.f5.com/serverssl"
 const f5ServerSslSecureAnnotation = "virtual-server.f5.com/secure-serverssl"
+const f5IruleAnnotation = "virtual-server.f5.com/irules"
 const defaultSslServerCAName = "openshift_route_cluster_default-ca"
 
 type ResourceMap map[int32][]*ResourceConfig
@@ -1069,6 +1070,17 @@ func (appMgr *Manager) syncIngresses(
                                }
                                rsCfg.SortMonitors()
                        }
+                       // Handle custom iRule annotation
+                       iRuleStr, found := ing.ObjectMeta.Annotations[f5IruleAnnotation]
+                       if found {
+                               iRuleStr := strings.TrimSpace(iRuleStr)
+                               parts := strings.Split(iRuleStr, ",")
+                               for _, iruleName := range parts {
+                                       iruleName := strings.TrimSpace(iruleName)
+                                       rsCfg.Virtual.AddIRule(iruleName)
+                               }
+                       }
+
                        // Collect all service names on this Ingress.
                        // Used in handleConfigForType.
                        var svcs []string
</pre>

**Comment by rlombardi12** [comment]
@vincentmli , can you elaborate how do you change/update this appManager.go file?

**Comment by vincentmli** [comment]
I have not following up recent CIS/k8s-bigip-ctlr development, can't the new CIS development support ingress with AS3 that support irule? if you still want this not supported irule annotation way, you can git clone the k8s-bigip-ctlr source code, make the code changes above to pkg/appmanager/appManager.go,  build the container image and upload to local or dock hub container image repo, then in the controller yaml file, change it to pull image from your local container repo or docker hub repo, please be aware this is not supported by F5

**Comment by Rockbob89** [comment]
Hey, we're currently investigating a Use Case where we would welcome this feature aswell. 

We can't use the CRDs and are forced to use the Ingress resource.

Maybe the team could have another look at this?
