### ISSUE TITLE
Ingress rules not being created on the load-balancer

### ISSUE THREAD

**Issue by CalvinHartwell** [F5Networks/k8s-bigip-ctlr#618]
Hi all,

I'm currently documenting integration of F5 Networks Big-IP with Canonical Kubernetes so that multiple customers can use the two products together [https://github.com/CalvinHartwell/canonical-kubernetes-f5-bigip](https://github.com/CalvinHartwell/canonical-kubernetes-f5-bigip). 

I seem to have both products working together, but when I create new ingress rules with the correct annotations, it does not seem to create anything on the load-balancer. 

Is there any pre-steps I need to perform before using the integration? Ideally I'd like to be able to create ingress rules on the load balancer. 

Thanks a lot! 

#### Kubernetes Version
Kubernetes 1.9.3 (Canonical Kubernetes)

#### Controller Version
v1.4.2

#### BIG-IP Version
v13 latest on AWS. 

#### Diagnostic Information
Here is the output from the log: 

```calvinh@ubuntu-ws:~$ kubectl logs -f k8s-bigip-ctlr-68549fc7d5-v7pd9
2018/03/14 21:07:26 [INFO] Starting: Version: v1.4.2, BuildInfo: n829-346558842
2018/03/14 21:07:26 [INFO] ConfigWriter started: 0xc420287f80
2018/03/14 21:07:26 [INFO] Started config driver sub-process at pid: 13
2018/03/14 21:07:26 [INFO] NodePoller (0xc42008a7e0) registering new listener: 0x407050
2018/03/14 21:07:26 [INFO] NodePoller started: (0xc42008a7e0)
2018/03/14 21:07:26 [WARNING] Overwriting existing entry for backend {ServiceName:cdk-cats ServicePort:80 Namespace:default}
2018/03/14 21:07:26 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2018/03/14 21:07:26 [INFO] [2018-03-14 21:07:26,769 __main__ INFO] entering inotify loop to watch /tmp/k8s-bigip-ctlr.config017314497/config.json

2018/03/14 21:07:44 [INFO] Port '80' for service 'cdk-cats' was not found.
2018/03/14 21:07:44 [INFO] Service 'cdk-cats' has not been found.
2018/03/14 21:07:44 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2018/03/14 21:07:44 [INFO] Port '80' for service 'cdk-cats' was not found.
2018/03/14 21:07:44 [INFO] Service 'cdk-cats' has not been found.
2018/03/14 21:07:44 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2018/03/14 21:07:53 [INFO] Wrote 0 Virtual Server and 0 IApp configs
error: stream error: stream ID 3; INTERNAL_ERROR
```

... and the example ingress rule:

```
---
...omitted 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cdk-cats
  namespace: default
  annotations:
    # Provide an IP address from the external VLAN on your BIG-IP device
    virtual-server.f5.com/ip: "10.190.25.70"
    # Specify the BIG-IP partition containing the virtual server
    virtual-server.f5.com/partition: "k8s"
spec:
  backend:
    # The name of the Kubernetes Service you want to expose to external traffic
    serviceName: cdk-cats
    servicePort: 80
```

FYI the svc and deployment exist and everything is in the same namespace called default.

**Comment by sjberman** [comment]
Closing since we found the culprit (service needed to be of type NodePort).

**Comment by CalvinHartwell** [comment]
In-case anyone else is stuck, please review this documentation here: [http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-modes.html](http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-modes.html)
