### ISSUE TITLE
Support ingress.kubernetes.io/rewrite-target

### ISSUE THREAD

**Issue by ccjoelm** [F5Networks/k8s-bigip-ctlr#621]
#### Description
We are trying to use a fan-out ingress controller for multiple services that all use the root context ( / )

From what I can tell other ingress providers use the ingress.kubernetes.io/rewrite-target: / to accomplish this, but it doesn't look like this is supported with the bigip-ctlr

#### Kubernetes Version
1.8.5

#### Controller Version
1.4.2

#### BIG-IP Version
BIG-IP 13.1.0 Build 0.0.1868 Final

#### Diagnostic Information
Ingress YAML:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cfs-ingress
  namespace: dev02
  annotations:
    # set class to f5, so the bigip-ctlr knows to implement
    kubernetes.io/ingress.class:  "f5"
    # rewrite target path to /
    ingress.kubernetes.io/rewrite-target: /
    # Provide an IP address for the BIG-IP virtual server;
    # Set to "controller-default" if you want to use the Controller's
    # "default-ingress-ip" (introduced in v1.4.0)
    virtual-server.f5.com/ip: "10.69.72.169"
    # Specify the BIG-IP partition where the Controller should create the virtual server.
    virtual-server.f5.com/partition: "DEV"
    # Specify the desired load balancing algorithm
    virtual-server.f5.com/balance: "least-connections-node"
    # Health Checks on service
    virtual-server.f5.com/health: |
      [
        {
          "path":     "dev02ms.example.com/charlie-service",
          "send":     "HTTP GET /v1/actuator/health",
          "interval": 5,
          "timeout":  10
        }, {
          "path":     "dev02ms.example.com/bravo-service",
          "send":     "HTTP GET /v1/actuator/health",
          "interval": 5,
          "timeout":  10
        }
      ]
spec:
  rules:
    - host: dev02ms.example.com
      http:
        paths:
        - path: /charlie-service
          backend:
            serviceName: charlie-service-svc
            servicePort: 8080
        - path: /bravo-service
          backend:
            serviceName: bravo-service-svc
            servicePort: 8080

**Comment by russokj** [comment]
We are adding URL rewrite support to the next release of our controller.  The specific details are currently being worked out.
