### ISSUE TITLE
Support for route advertisements for ingress resources

### ISSUE THREAD

**Issue by sfudeus** [F5Networks/k8s-bigip-ctlr#624]
#### Description
Currently when the f5 controller creates the VirtualServer for an ingress resource, the route advertisements are disabled. It is not really an option to have to enable them manually after the creation of the ingress.
I would wish for route advertisements being enabled by default or have that configurable. 

#### Kubernetes Version
1.9.3

#### Controller Version
1.4.2

#### BIG-IP Version
12.1.3

**Comment by mdditt2000** [comment]
We are making some enhancement to the cfgmap. Integrating a declarative API coming April. You can get more information on this declarative API at https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#advertising-a-route-for-a-service-address

Later in the year we plan to move to CRDs. With the use of the declarative API you can simply enable any advanced option available on big-ip today. If you have addition questions on this this enhancement please reach out to me. Thanks Mark

**Comment by mdditt2000** [comment]
CIS 1.9 released next month will support AS3. AS3 provides route advertisements

Closing this issue out since support will be in CIS 1.9

**Comment by fsck-ext4** [comment]
@mdditt2000 hello, is there any chance of implementing this as an Ingress annotation? AS3 is a great solution, but Ingresses are much simplier (especially in case when developers need to write it) and are much more safe in case of an error. Currently we are migrating to k8s-bigip-controller, and route advertisement is the only thing which stops us from switching completely to it.
Thanks in advance!

**Comment by mdditt2000** [comment]
@fsck-ext4 please review Github https://github.com/F5Networks/k8s-bigip-ctlr/issues/1592

In this dev sprint we are adding "routeAdvertisement": "all", to the virtualserver using a CRD. CRD are very easy for your developers. I can provide you an example in a few days and maybe a early pre-view release. 

https://clouddocs.f5.com/containers/latest/userguide/crd/

**Comment by fsck-ext4** [comment]
@mdditt2000 wow, thanks, looks great!
Can I contact you on Slack?

**Comment by mdditt2000** [comment]
@fsck-ext4 slack is perfect. I am online.
