### ISSUE TITLE
[DOC] Improve troubleshooting/kubernetes.html#iapp-traffic-group

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#625]
#### Description

I find it is not clear the following:

- The trafficGroup example is in the second item and I think it refers to the first item (the iAppOptions) an example that encompasses the iAppOptions would clarify this:

```
          "iappOptions": {
            "description": "os.routing-virtual iApp",
            "trafficGroup": "/Common/traffic-group-local-only"
          },
```

- I don't know how to setup the Preferred option " Set the desired traffic group as the default for the partition" further details would be helpful.

Please see the next screenshot of the section I'm referring to:

<img width="1101" alt="screen shot 2018-03-21 at 11 21 59" src="https://user-images.githubusercontent.com/16683733/37704782-22fd5358-2cfa-11e8-8186-61beddb904ce.png">

**Comment by russokj** [comment]
The above example would be good to have.  In addition we should make sure that it's clear to the user to do only one of the two options given, with the second option being the preferred method.  Also, the second option should clearly state that the actions are done on the Big-IP itself, not through the controller/environment.

**Comment by jputrino** [comment]
Issue moved to [F5Networks/f5-ci-docs #389](https://github.com/F5Networks/f5-ci-docs/issues/389) via [**ZenHub**](https://www.zenhub.com/)
