### ISSUE TITLE
Node names should not contain `%` character

### ISSUE THREAD

**Issue by mrwulf** [F5Networks/k8s-bigip-ctlr#632]
#### Description
The controller creates nodes with names containing a `%` -- which are not supposed to be allowed. Node names that get created are all in the format `<ip address>%0`. The web config rejects creating names with `%`. The percent character **is** allowed in the description field if it is needed to store the route domain.

This is only an issue for us because the puppet f5 module pre-fetches f5 objects (including nodes) and validates the names.

#### Kubernetes Version
tried with 1.9.1 and 1.9.4

#### Controller Version
1.4.2

#### BIG-IP Version
BIG-IP 13.1.0.3 Build 0.0.5 Point Release 3

#### Controller parameters used
            --bigip-username=$(BIGIP_USERNAME)
            --bigip-password=$(BIGIP_PASSWORD)
            --bigip-url=$(BIGIP_IPADDR)
            --bigip-partition=dev-k8s
            --use-secrets=false
            --resolve-ingress-names=LOOKUP
            --log-level=INFO
            --pool-member-type=cluster
            --use-node-internal=true
            --flannel-name=flannel_vxlan

#### Example VIP ConfigMap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-kub-dashboard-vip
  namespace: kube-system
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.4.json"
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "tcp",
          "partition": "dev-k8s",
          "virtualAddress": {
            "bindAddr": "10.0.127.120",
            "port": 443
          }
        },
        "backend": {
          "serviceName": "kubernetes-dashboard",
          "servicePort": 443
        }
      }
    }
```

#### Diagnostic Information
Relavent audit log entries (newest to oldest):
* pid=4916 user=f5auto folder=/Common module=(tmos)# status=[Command OK] cmd_data=create net arp /Common/k8s-10.2.5.199 { mac-address a2:96:84:f9:38:b3 ip-address 10.2.5.199 }:
* client tmsh, tmsh-pid-4916, user f5auto - transaction #15740055-2 - object 0 - create { arp_static_entry { arp_static_entry_name "/Common/k8s-10.2.5.199" arp_static_entry_ip_addr 10.2.5.199 arp_static_entry_mac_addr A2:96:84:F9:38:B3 } } [Status=Command OK]:
* pid=4916 user=f5auto folder=/dev-k8s module=(tmos)# status=[Command OK] cmd_data=modify ltm node /dev-k8s/10.2.5.199%0 { logging disabled monitor default fqdn { down-interval 5 interval 3600 } state user-up session user-enabled dynamic-ratio 1 connection-limit 0 ratio 1 rate-limit disabled app-service none description none }:
* client tmsh, tmsh-pid-4916, user f5auto - transaction #15739990-2 - object 0 - modify { node_address { node_address_name "/dev-k8s/10.2.5.199%0" node_address_app_id "" node_address_conn_limit 0 node_address_description "" node_address_dynamic_ratio 1 node_address_fqdn_down_interval 5 node_address_fqdn_up_interval 3600 node_address_log 0 node_address_monitor_rule "" node_address_rate_limit 0 node_address_ratio 1 node_address_new_session_enable 2 node_address_monitor_state 3 } } [Status=Command OK]:
* client tmsh, tmsh-pid-4916, user f5auto - transaction #15739707-9 - object 0 - create_if { pool_member { pool_member_pool_name "/dev-k8s/cfgmap_kube-system_dev-kub-dashboard-vip" pool_member_node_name "/dev-k8s/10.2.5.199%0" pool_member_port 80 pool_member_description "" pool_member_conn_limit 0 pool_member_ratio 1 pool_member_priority 0 pool_member_new_session_enable 2 } } [Status=Command OK]:

**Comment by russokj** [comment]
The use of route domains in the node name is a requirement to support non-zero default route domains in the Big-IP partitions.  When creating pool members that include route domains, the Big-IP will automatically name the node using the pool IP and the route domain: <ip>%<rd>" (this is done if a name isn't explicitly provide).

It sounds like the puppet module currently doesn't support handling of route domains.

**Comment by mrwulf** [comment]
Ah- it looks like you can create nodes without explicit names through tmsh or the api. Interesting that the web gui doesn't allow that character. Also, it seems like the name wouldn't need to store the route domain, because -- as you mentioned -- it could be set to something else.

I agree the puppet module should be more accepting, but maybe giving the nodes a useful name (maybe the pod name?) would be helpful too.

@russokj  thanks for the quick response!
