### ISSUE TITLE
configMap disable

### ISSUE THREAD

**Issue by roldancer** [F5Networks/k8s-bigip-ctlr#662]
Hi All, We would like to use F5 for our Openshift infrastructure, but we only want to permit F5 auto-configuration via Openshift's Route, I mean ConfigMap must not be permitted for F5 configuration, is there any way to permit only Route and disable other kind of configuration such as configmap.

Flexibility is great but for a production environment ... but sometimes flexibility means security risks ...

Many thanks.

**Comment by rsalsa** [comment]
@roldancer - you could not give the controller permission to interact with the API Server for configmaps. So the [RBAC permissions](http://clouddocs.f5.com/containers/v2/openshift/kctlr-openshift-app-install.html#set-up-rbac-authentication) you'd use for the controller wouldn't include the `configmaps`.

**Comment by roldancer** [comment]
Hi @rsalsa , Good idea, I would try that approach.

Thanks.

**Comment by roldancer** [comment]
Hi, If we disable configmap at the CLusterRole we get this error message:

E0514 11:12:01.891948       1 reflector.go:201] github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:631: Failed to list *v1.ConfigMap: User "system:serviceaccount:kube-system:bigip-ctlr" cannot list configmaps at the cluster scope: User "system:serviceaccount:kube-system:bigip-ctlr" cannot list all configmaps in the cluster (get configmaps)

Bye,

**Comment by amudukutore** [comment]
@caphrim007 - does your new command-line arg to stop watching for configmap resources fix this use case? I believe it does.

**Comment by caphrim007** [comment]
@amudukutore yes

**Comment by amudukutore** [comment]
@roldancer - this issue has been fixed as part of https://github.com/F5Networks/k8s-bigip-ctlr/pull/737 and will be available in the next release of the controller (v1.7.0).
