### ISSUE TITLE
verify-interval behavior for iApps

### ISSUE THREAD

**Issue by jputrino** [F5Networks/k8s-bigip-ctlr#665]
#### Description
See conversation on PR #642 

@f5yacobucci: "CCCL does attempt to to check iApps as it does other BIG-IP resources. It pulls down the existing iApps and uses the 'variables' and 'tables' sections explicitly to compare desired versus existing configurations.

If we're seeing iApps being overwritten too frequently this isn't a design choice and really a bug, the solution/product docs shouldn't be updated to document bugs - I think mentioning that behavior is more appropriately discussed in a "Known Bugs" or "Limitations" section."

@alonsocamaro: What I have found is that iApps get re-instantiated but that doesn't create new objects if these already exist. Creating new objects would cause service disruption. I'm afraid that when loading complex configurations such as ASM policies some disruption might occur but I haven't tested this as of yet. 

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by pdp2shirts** [comment]
@alonsocamaro should this issue be closed? It appears as though there was a doc fix PRs merged to address, but not certain all aspects of the issue were addressed by those PRs

**Comment by trinaths** [comment]
moving to AS3 as default agent to CIS.
