### ISSUE TITLE
1.5.0: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Lucius-** [F5Networks/k8s-bigip-ctlr#682]
#### Description
When deploying the latest `k8s-bigip-ctlr` the controller repeatedly throws exceptions, stating `TypeError: object of type 'NoneType' has no len()` and fails to update the LTM configuration.

Sorry for the sparse amount of information, I'm currently not in a position to further debug this. If there's anything I can do to provide you with any more information, let me know!

#### Kubernetes Version
OpenShift 3.7 / Kubernetes 1.7

#### Controller Version
1.5.0

#### BIG-IP Version
12.1.2

#### Diagnostic Information
I've attached our controller config, controller debug logs and the generated config.json file.

[k8s-bigip-ctlr-routes.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1947685/k8s-bigip-ctlr-routes.yaml.txt)

[debug.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1947686/debug.txt)

[config.json.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1947687/config.json.txt)

**Comment by sjberman** [comment]
Could we get your BIG-IP config for the managed partition? Be sure to redact any sensitive info.

**Comment by Lucius-** [comment]
@sjberman Attached. The config was originally created by the previous version of the controller (1.4.2), which does not run into this issue.

[bigip_config.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/1948156/bigip_config.txt)

**Comment by sjberman** [comment]
Thanks. We found that the issue involves the new version of the controller updating the metadata field, whereas the previous version did not. This causes an issue if the resources were created on the BIG-IP by the previous controller, as they won't have metadata, and the new controller tries to access this metadata.

We are working on fixing this bug. In the meantime, there are a couple of workarounds:
1) Add a dummy metadata field to your LTM resources that are affected (virtuals, pools, etc). The controller will then properly see the metadata field and write the correct info.
2) Remove OpenShift Route resources to "clear out" the BIG-IP, and recreate them. The new controller will create these resources from scratch, and there should be no issues.

**Comment by amudukutore** [comment]
Created https://github.com/F5Networks/k8s-bigip-ctlr/issues/683 to track this.

**Comment by Lucius-** [comment]
Awesome, I can confirm that #2 works. Thanks a lot for the quick response on this!
