### ISSUE TITLE
Enhancement Request: Add custom profile on virtual server

### ISSUE THREAD

**Issue by rendhalver** [F5Networks/k8s-bigip-ctlr#690]
#### Description
We would like the ability to add a custom profile to virtual servers created with the k8s-bigip-ctlr.
We are currently seeing timeout issues that seem related to using f5 virtual servers in front of ingress.

We are happy to try and implement the solution.
Can you give us some pointers to where this would need to go?

Thanks.

#### Kubernetes Version
<Version of Kubernetes being used>

#### Controller Version
<Version of k8s-bigip-ctlr being used>

#### BIG-IP Version
<Version of BIG-IP being used>

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by benlangfeld** [comment]
Specifically this would be a TCP profile.

**Comment by amudukutore** [comment]
@rendhalver, @benlangfeld - can you take a look at the docs section on attaching routes/ingresses to existing BIG-IP virtual servers to see if it meets your needs? 
https://clouddocs.f5.com/containers/v2/openshift/kctlr-openshift-routes.html?highlight=existing#attach-routes-to-existing-big-ip-virtual-servers

**Comment by rendhalver** [comment]
From the looks of that we have to disable management of the resources and manually change them ourselves.
Can we get the functionality put into the controller so it can manage the profile?

**Comment by mitchellmaler** [comment]
I was looking for the same thing and ended up here. We have multiple custom profiles we want to set instead of using the defaults set by the controller.
- Protocol Profile Client
- Protocol Profile Server
- HTTP Profile Client
- HTTP Profile Server
- OneConnect Profile

**Comment by mdditt2000** [comment]
This can we achieved using AS3 and a configmap - https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/profiles.html#using-a-multiplex-oneconnect-profile-in-a-declaration

Let me know if you have any questions.

**Comment by mitchellmaler** [comment]
@mdditt2000 Are there examples of doing so without using the ingress controller such as adding a custom client and/or server profile to a vip created using the controller?
