### ISSUE TITLE
Ingress resource - Set X-Forwarded-For

### ISSUE THREAD

**Issue by joshbenner** [F5Networks/k8s-bigip-ctlr#693]
#### Description
Provide a means for controller to configure BIG-IP to set `X-Forwarded-For` header.

This is useful for cases where the BIG-IP is not acting as the gateway for the cluster, and is instead an opaque/traditional reverse proxy. This is done by other Kubernetes ingress implementations by default, notably the Nginx ingress that is part of the Kubernetes project.

I could see making this feature opt-in via a simple true/false annotation, or annotations that are more involved such as `virtual-server.f5.com/real-ip-header: X-Forwarded-For`.

There are several other related headers that are commonly used. The Nginx ingress controller sets these by default:
```
proxy_set_header X-Real-IP              $the_real_ip;

proxy_set_header X-Forwarded-For        $the_real_ip;

proxy_set_header X-Forwarded-Host       $best_http_host;
proxy_set_header X-Forwarded-Port       $pass_port;
proxy_set_header X-Forwarded-Proto      $pass_access_scheme;
proxy_set_header X-Original-URI         $request_uri;
proxy_set_header X-Scheme               $pass_access_scheme;
```

**Comment by vincentmli** [comment]
I just come up with a patch like below to achieve the goal, the patch might need a little bit more polish

<pre>
diff --git a/pkg/appmanager/appManager.go b/pkg/appmanager/appManager.go
index 4ce57bc..75f9a37 100644
--- a/pkg/appmanager/appManager.go
+++ b/pkg/appmanager/appManager.go
@@ -67,6 +67,7 @@ const f5ClientSslProfileAnnotation = "virtual-server.f5.com/clientssl"
 const f5ServerSslProfileAnnotation = "virtual-server.f5.com/serverssl"
 const f5ServerSslSecureAnnotation = "virtual-server.f5.com/secure-serverssl"
 const f5IruleAnnotation = "virtual-server.f5.com/irules"
+const xForwardedFor = "ingress.kubernetes.io/x-forwarded-for"
 const defaultSslServerCAName = "openshift_route_cluster_default-ca"
 
 type ResourceMap map[int32][]*ResourceConfig
@@ -1081,6 +1082,17 @@ func (appMgr *Manager) syncIngresses(
                                }
                        }
 
+                       XForwardedFor := getBooleanAnnotation(ing.ObjectMeta.Annotations,
+                               xForwardedFor, false)
+
+                       if XForwardedFor {
+                               log.Debugf("IRule: Applying HTTP X-Forwarded-For iRule.")
+                               appMgr.addIRule(httpXForwardForIruleName, DEFAULT_PARTITION,
+                                       httpXForwardedFor())
+                               ruleName := joinBigipPath(DEFAULT_PARTITION, httpXForwardForIruleName)
+                               rsCfg.Virtual.AddIRule(ruleName)
+                       }
+
                        // Collect all service names on this Ingress.
                        // Used in handleConfigForType.
                        var svcs []string
diff --git a/pkg/appmanager/routing.go b/pkg/appmanager/routing.go
index 0887259..6769dfa 100644
--- a/pkg/appmanager/routing.go
+++ b/pkg/appmanager/routing.go
@@ -35,6 +35,7 @@ import (
 const httpRedirectIRuleName = "http_redirect_irule"
 const abDeploymentPathIRuleName = "ab_deployment_path_irule"
 const sslPassthroughIRuleName = "openshift_passthrough_irule"
+const httpXForwardForIruleName = "http_x_forwarded_for_irule"
 
 // Internal data group for passthrough routes to map server names to pools.
 const passthroughHostsDgName = "ssl_passthrough_servername_dg"
@@ -374,6 +375,16 @@ func httpRedirectIRule(port int32) string {
        return iRuleCode
 }
 
+func httpXForwardedFor() string {
+       iRuleCode := fmt.Sprintf("%s\n", `
+                       when HTTP_REQUEST {
+                               HTTP::header insert X-Forwarded-For [IP::remote_addr]
+                       }
+               `)
+
+       return iRuleCode
+}
+
 func selectPoolIRuleFunc() string {
        iRuleFunc := fmt.Sprintf(`
                proc select_ab_pool {path default_pool } {
</pre>

a sample ingress yaml:

<pre>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: single-service
  annotations:
     ingress.kubernetes.io/allow-http: "false"
     ingress.kubernetes.io/allow-https: "true"
     ingress.kubernetes.io/x-forwarded-for: "true"
     kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"ingress.kubernetes.io/allow-http":"false","ingress.kubernetes.io/ssl-redirect":"true","kubernetes.io/ingress.class":"f5","virtual-server.f5.com/balance":"round-robin","virtual-server.f5.com/ip":"10.169.72.169","virtual-server.f5.com/partition":"test","virtual-server.f5.com/serverssl":"Common/serverssl"}}}
     kubernetes.io/ingress.class: f5
     'virtual-server.f5.com/ip': '192.168.2.169'
     'virtual-server.f5.com/serverssl': 'Common/serverssl'
     'virtual-server.f5.com/health': |
      [
        {
          "path":     "/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  16
        }
      ]
spec:
  tls:
#  - secretName: test/test-clientssl
  - secretName: Common/clientssl
  backend:
    serviceName: nginxservice 
    servicePort: 80
</pre>

**Comment by mdditt2000** [comment]
Create CONTCNTR-1117 for PM tracking

**Comment by mdditt2000** [comment]
Issues is resolved in AS3 override. Reference a custom http profile with the x-forwarded-for setting. Review the example below. 

`"ingress_10_192_75_108_80": {
                        "profileHTTP": {
                            "bigip": "/Common/http-custom"
                        },

https://github.com/mdditt2000/kubernetes-1-16/blob/master/cis%201.14/ingress%20resources/f5-as3-configmap.yaml

Closing issue out.
