### ISSUE TITLE
Attach pre-existing irules to Virtual server though Config-maps kubernetes

### ISSUE THREAD

**Issue by vinayprsc** [F5Networks/k8s-bigip-ctlr#694]
#### Description
This feature is to let you to attach the a pre-existing irule to virtual-server using config-maps in kubernetes.
also set a boolean option to not delete pre-existing irules from the partition.

#### Kubernetes Version
1.9

#### Controller Version
1.5.1

#### BIG-IP Version
BIG-IP 12.1.1 Build 1.0.196 Hotfix HF1

**Comment by mdditt2000** [comment]
Using AS3 and CIS 1.9.1 you can reference or fetch external irule associated to the VIP. 

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/profiles.html#referencing-existing-irules-lx-profiles

Let me know if you have questions.
