### ISSUE TITLE
Enhancement Request: Network Firewall Policy / iRule configuration via k8s-bigip-ctlr

### ISSUE THREAD

**Issue by litmaj0r** [F5Networks/k8s-bigip-ctlr#696]
#### Description
A customer is looking to configure firewall policies related to Virtual Servers, however this functionality is not currently configurable directly via k8s-bigip-ctlr configuration (as defined per schemas and Ingress Resources). Here's the RFE template to add context to the need for this feature:

=== RFE Template ===

1. Describe the new feature in as much detail as possible.
The customer is requesting support for consuming/using existing defined 
iRules.   If the controller can build them, that would be ideal, if not the customer 
would need it to allow the assignment of already created iRules in other partitions.

2. What is the problem that would be resolved by adding this new feature?
The customer uses iRules to define custom traffic processing and secure analysis of
traffic flow.

3. What is the business impact to your site due to the lack of this feature?
The customer is severely impacted in their ability to use the kubernetes controller
for f5 in our environment without its ability to support iRules.

#### Kubernetes Version
v.1.8.x

#### Controller Version
v1.5.0

#### BIG-IP Version
v13.1.x

#### Diagnostic Information
Reference info related to this on what resources can currently be modified are as follows: 

  The latest schema for Virtual Servers, which are used in the F5 Resource ConfigMaps:
  https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/schemas/bigip-virtual-server_v0.1.7.json

  Ingress Resources:
  http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.5/#ingress-resources

It was advised that there may be a workaround possible via an iApp; configuration guide info available at: http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.5/index.html#iapps

**Comment by mdditt2000** [comment]
AS3 override will allow you to reference irule. Example:
`
           "iRules": [
              {
                "bigip": "/appaotel1_AS3/Shared/http_redirect_irule"
              },
              {
                "bigip": "/Common/_sys_APM_ExchangeSupport_helper"
              }
              ],
`
https://github.com/mdditt2000/openshift-3-11/blob/master/issues/yosef/f5-override-as3-declaration.yaml

Closing issue out as resolved.
