### ISSUE TITLE
Question: Support of whitelist in Openshift Route annotation 

### ISSUE THREAD

**Issue by roldancer** [F5Networks/k8s-bigip-ctlr#697]
Hi All, I would like to know if the following annotation in Openshift Route object is supported by the controller ?

  annotations:
    haproxy.router.openshift.io/ip_whitelist: 192.168.1.10

For more information about this annotation this is the link to the documentation https://docs.openshift.com/container-platform/3.7/architecture/networking/routes.html#whitelist

**Comment by amudukutore** [comment]
@caphrim007 - does the new whitelist feature you've added support this use case?

**Comment by mdditt2000** [comment]
Moved away from whitelisting since moved to declarative API. No longer supporting whitelisting using agent-as3 AS3. Request to use a AS3 configmap. Closing issue out.
