### ISSUE TITLE
ingress allow-http and ssl-redirect do not seem to be working as documented

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#700]
#### Description
when setting ssl-redirect to false and allow-http to true the traffic is still redirected.  based on the documentation one would expect to see http traffic allowed.  It's unclear how that is meant to work since it seems that you can only specific a single target service port.

#### Kubernetes Version
1.7.12

#### Controller Version
1.5.1

#### BIG-IP Version
13.1.0.7

#### Diagnostic Information
ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blue-green-ingress-tls
  annotations:
    virtual-server.f5.com/ip: "10.1.10.82"
    virtual-server.f5.com/https-port: "443"
    virtual-server.f5.com/http-port: "8080"
    virtual-server.f5.com/ssl-redirect: "false"
    ingress.kubernetes.io/allow-http: "true"
    virtual-server.f5.com/clientssl: "/Common/_wildcard_.f5demo.com_clientssl"
    virtual-server.f5.com/serverssl: "/Common/serverssl"
    virtual-server.f5.com/secure-serverssl: "false"
    virtual-server.f5.com/partition: "kubernetes"
    virtual-server.f5.com/health: |
      [
        {
          "path":     "blue.f5demo.com/",
          "send":     "GET / HTTP/1.0",
          "interval": 5,
          "timeout":  15
        }, {
          "path":     "green.f5demo.com/",
          "send":     "GET / HTTP/1.0",
          "interval": 5,
          "timeout":  15
        }
      ]    
    kubernetes.io/ingress.class: "f5"
spec:
  tls:
  - secretName: /Common/_wildcard_.f5demo.com_clientssl
 
  rules:
  - host: blue.f5demo.com
    http:
      paths:
      - backend:
          serviceName: node-blue
          servicePort: 443
  - host: green.f5demo.com
    http:
      paths:
      - backend:
          serviceName: node-green
          servicePort: 443
```
test
```
$ curl 10.1.10.82:8080 -H host:blue.f5demo.com -v
* About to connect() to 10.1.10.82 port 8080 (#0)
*   Trying 10.1.10.82...
* Connected to 10.1.10.82 (10.1.10.82) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> host:blue.f5demo.com
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< Location: https://blue.f5demo.com:443/
< Server: BigIP
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
< Content-Length: 0
```
LTM config
```
ltm virtual ingress_10-1-10-82_443 { destination 10.1.10.82%0:https ip-protocol tcp mask 255.255.255.255 metadata { user_agent { value k8s-bigip-ctlr-1.5.1-n1107-373131503 } } partition kubernetes policies { ingress_10-1-10-82_443 { } } profiles { /Common/_wildcard_.f5demo.com_clientssl { context clientside } /Common/http { } /Common/serverssl { context serverside } /Common/tcp { } } source 0.0.0.0/0 source-address-translation { type automap } translate-address enabled translate-port enabled vs-index 29 }
ltm virtual ingress_10-1-10-82_8080 { destination 10.1.10.82%0:webcache ip-protocol tcp mask 255.255.255.255 metadata { user_agent { value k8s-bigip-ctlr-1.5.1-n1107-373131503 } } partition kubernetes policies { ingress_10-1-10-82_8080 { } } profiles { /Common/http { } /Common/tcp { } } rules { http_redirect_irule_443 } source 0.0.0.0/0 source-address-translation { type automap } translate-address enabled translate-port enabled vs-index 28 }
```

**Comment by vincentmli** [comment]
this seems to be resolved by fix in https://github.com/F5Networks/k8s-bigip-ctlr/issues/802, I tested with below yaml

<pre>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: single-service
  annotations:
     ingress.kubernetes.io/ssl-redirect: "false"
     ingress.kubernetes.io/allow-http: "true"
#     ingress.kubernetes.io/allow-https: "true"
     kubernetes.io/ingress.class: f5
     'virtual-server.f5.com/ip': '10.169.72.169'
     'virtual-server.f5.com/http-port': '8080'
     'virtual-server.f5.com/https-port': "443"
spec:
  tls:
  - hosts:
    - www.example.com
    secretName: Common/clientssl
  rules:
   - host: www.example.com
     http:
       paths:
       - path: /  
         backend:
            serviceName: nginxservice 
            servicePort: 80
   - host: www1.example.com
     http:
       paths:
       - path: /  
         backend:
            serviceName: nginxservice1 
            servicePort: 80
</pre>

it works

<pre>
# curl http://www.example.com:8080 -v
* About to connect() to www.example.com port 8080 (#0)
*   Trying 10.169.72.169...
* Connected to www.example.com (10.169.72.169) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.example.com:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.15.8
</pre>

**Comment by ssurenr** [comment]
1.12 also addresses this issue on the AS3 backend.
