### ISSUE TITLE
iApp deployment: Unable to configure "iappLists" parameters

### ISSUE THREAD

**Issue by sgelmiWellcomm** [F5Networks/k8s-bigip-ctlr#712]
#### Description
In iApp deployment, i'm not be able to configure the iAppLists param, such as iRules or LTM Policy.
The following error is shown:
`"iappLists: Additional property iappLists is not allowed"`

With a normal deployment, these parameters can be deployed with iApp.
The params are seen by previous deployment, with the following command:
`tmsh list sys app service <appname>`

The correct param is Lists.

The iApp template is http.v.1.2.0

#### Kubernetes Version
1.8

#### Controller Version
Version: 1.5.0-WIP

#### BIG-IP Version
12.1.2

#### Diagnostic Information
iApp TMSH:

> sys application service test.app/test {
>   device group none
>   inherited-devicegroup true
>   inherited-traffic-group true
>   lists {
>     irules__irules {
>       value { test_add_x_forwarded_proto }
>     }
>     local_traffic__policies {
>       value { test-policy-traffic }
>     }
>     net__client_vlan {
>        value { Internal }
>     }
>   }
>   etc...

**Comment by alonsocamaro** [comment]
Checking the schema seems it is not supported:

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/schemas/bigip-virtual-server_v0.1.7.json

**Comment by sgelmiWellcomm** [comment]
Is an iAppVariables property.
Thanks

**Comment by alonsocamaro** [comment]
Yes, just tested it. It works just fine:

```
          "iappVariables": {
            "ssl_encryption_questions__advanced": "yes",
            "irules__irules": "/Common/test /Common/test2"
```

works fine although when listing the app service there is no list element:

```
# tmsh list sys application service /coolstore/coolstore_test.app/coolstore_test | grep list | wc -l
0
```

it is instantiated fine:

```
# tmsh list ltm virtual /coolstore/coolstore_test.app/coolstore_test_vs rules
ltm virtual /coolstore/coolstore_test.app/coolstore_test_vs {
    rules {
[test-f5-http-configmap.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/2231358/test-f5-http-configmap.txt)


        test
        test2
    }
}
```

This seems to be a feature of the iApp framework. I think this behaviour should be documented in the Container Connector documentation.

See attached Yaml file for more details.

**Comment by pdp2shirts** [comment]
@alonsocamaro if this works and documentation is all that is needed, can you open a PR to update the docs, and then close the issue, or get me the info and I can update docs.

**Comment by trinaths** [comment]
inactive since 2018.
