### ISSUE TITLE
Cilium and bigip 

### ISSUE THREAD

**Issue by nirmoy** [F5Networks/k8s-bigip-ctlr#713]
Calico works with big-ip using BGP peering. Cilium[1] can also achieve similar goal with an external bgp agent.  I wonder if anyone already tried such setup ?

[1] https://devcentral.f5.com/articles/calico-kubernetes-and-big-ip-26850
[2] https://github.com/cilium/cilium/

**Comment by mdditt2000** [comment]
At this we have no plans to support Cilium

**Comment by vincentmli** [comment]
I have a demo showing BIG-IP work with Cilium in cluster/Tunnel mode without BGP routing dependency https://youtu.be/PkaYM_BBVT4
