### ISSUE TITLE
RFE: support flannel with etcd backend

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#722]
#### Description

One of our partners use flannel with the etcd backend, that is: without using the k8s API to store MAC VTEPs, PodCIDRs, etc...

This important parner for us is not going to change to the k8s backend anytime soon because it implies several major changes to the way they deploy k8s. If flannel has to use k8s api, it has to run as a pod. Which requires privileged containers. It also needs to run on master, so we would need to run kubelet on master with privileged containers enabled. 

This request **should be considered medium to high priority**. Please contact the BD team for more info.

#### Kubernetes Version
1.9
#### Controller Version
1.5
#### BIG-IP Version
NA

**Comment by trinaths** [comment]
inactive since 2018.
