### ISSUE TITLE
k8s-bigip-ctlr stops processing subsequent resources after resource error

### ISSUE THREAD

**Issue by amudukutore** [F5Networks/k8s-bigip-ctlr#734]
#### Description
The F5 Big IP K8S controller processes the ingress configuration files via the K8S api and applies them to the F5 Big IP LTM.  We have the individual ingress associated with a K8S namespace.  If an update to an ingress happens, which contains errors, the F5 K8S controller halts on processing.  This in turn effects any new ingress created for other namespaces within the K8S environment.  We would like to see the F5 K8S controller mark/log the offending ingress as an error and continue processing other ingress requests.  The way it stands now, every ingress for each namespace can not process changes/updates/or new ingress deployments unless the offending/error is correct.

#### Kubernetes Version
v1.11

#### Controller Version
1.5.0, 1.6.0

#### BIG-IP Version
13.1.07

#### Diagnostic Information
```
2018/08/10 14:33:10 [ERROR] [2018-08-10 14:33:10,981 f5_cccl.service.manager ERROR] Resource ingress1 update error, requeuing task...\
2018/08/10 14:33:10 [INFO] [2018-08-10 14:33:10,981 f5_cccl.resource.resource INFO] Creating ApiPolicy: ingress1\
2018/08/10 14:33:11 [ERROR] [2018-08-10 14:33:11,010 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiPolicy) ingress1.\
2018/08/10 14:33:11 [ERROR] [2018-08-10 14:33:11,010 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://<IP>:<PORT>/mgmt/tm/ltm/policy/\
2018/08/10 14:33:11 [INFO] Text: u'\{"code":400,"message":"010716e5:3: Policy ingress1\\', rule \\'ingress_2\\'; action refers to an invalid pool \\'/kubernetes/ingress_2\\'.","errorStack":[],"apiError":3\}'\
2018/08/10 14:33:11 [ERROR] [2018-08-10 14:33:11,010 f5_cccl.service.manager ERROR] Resource ingress1 creation error, requeuing task...\
...
```
Task was requeued, error re-triggered, requeued, and loop goes on. BIG-IP was not able to continue processing other ingress requests UNTIL he fixed this error.

#### Steps to reproduce:
1. Deploy an app and service to K8S
2. Deploy a configmap that has a syntax error.  In my case, I made the load balancing method "roun-robin"
3. The CC logs will show that there is a syntax error that begins like this:
    2018/08/20 18:07:36 [ERROR] [2018-08-20 18:07:36,660 __main__ ERROR] CCCL Error: Service congifuration provided does not match schema:
4. Deploy another, different configmap or an ingress that is valid
5. The CC logs will not show any activity related to the newly deployed resource and the BIG-IP configuration is not updated
6. Delete the invalid configmap deploy in step #2
7. CC logs will show the resource deployed in step #4 being processed and the BIG-IP configuration is updated

**Comment by sjberman** [comment]
I believe this issue likely lives in the f5-ctlr-agent. There is a backoff loop that gets started when a CCCL config is invalid, and I think this loop just keeps going indefinitely and doesn't allow progress to be made until the config is valid.

**Comment by dgarrisonf5** [comment]
Closing this issue because Container Connector was deployed on Kubernetes v1.11 which is not a version that is officially supported.

**Comment by mdditt2000** [comment]
This issue is resolved using GOJSON schema validation. CIS will validate the configmap AS3 declaration against the schema. If there is a error in the configuration CIS will display a error in the log. Please can you move to agent-as3 and CIS 1.10. I am available to help. Please reach out to me at m.dittmer@F5,.com. Thanks! I would like to close this issue out.

**Comment by mdditt2000** [comment]
Closing tis issue out.
