### ISSUE TITLE
Enhancement Request: Support for Source Address Translation: None

### ISSUE THREAD

**Issue by kpschuck** [F5Networks/k8s-bigip-ctlr#741]
#### Description
Per #631, `Source Address Translation: None` was explicitly not implemented. We have a use case where we need to disable SNAT for the entire controller partition.

I propose that when `vs-snat-pool-name` is set to `none` that this take effect. Alternatively, add an additional field `vs-snat` which can be set to `none`, `automap`, or `snat`

#### Kubernetes Version
1.11.2

#### Controller Version
1.6.0

#### BIG-IP Version
12.1.1

**Comment by mdditt2000** [comment]
@kpschuck you can now modify the SNAT configuration per Vserver using an AS3 declaration. Please let me know if you would like to see a demo. Mark

**Comment by mdditt2000** [comment]
Using AS3 in the configmap change the SNAT none
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/examples.html

Closing issue. Please contact me if you need help with the declaration or demo

**Comment by camrossi** [comment]
Hi @mdditt2000,

I am not familiar with AS3.
Can you share an example on how to disable SNAT on all the VIPs that are created by the k8s bigip-ctlr?

Cam

**Comment by mdditt2000** [comment]
Re-opened issue

**Comment by mdditt2000** [comment]
Using AS3 override in combination of openshift route you can override CIS configured virtual snat. Here is an example:

`"snat": {
                "bigip": "/Common/RD_000_SNATPOOL_GENERIC"
              },
`
https://github.com/mdditt2000/openshift-3-11/blob/master/issues/yosef/f5-override-as3-declaration.yaml

Closing this issue out
