### ISSUE TITLE
OpenShift/CC deleting all routes when service deleted

### ISSUE THREAD

**Issue by amudukutore** [F5Networks/k8s-bigip-ctlr#743]
#### Description
All pools are deleted after deleting a service

Create an openshift route that contains services from two different projects.  If you delete the service from the 2nd project it will cause traffic to the first service to be disrupted.  If you delete
 the route from the 2nd project the route to the 1st project is not disrupted.  Ideally the Container Connector should gracefully handle the first case.

#### STEPS TO REPRODUCE
    1.  Deploy/Create workload app (pod) yaml (oc create -f nginx-dc.yaml)
    2.  Deploy/Create workload service yaml (oc create -f nginx-svc.yaml)
    3.  Deploy/Create workload route yaml (oc create -f nginx-route.yaml)
    4.  Verify that route is in f5 pool
    5.  Verify that workload can be accessed via browser URL (URL endpoint defined in OCP console for the project)
    6.  Delete workload service (oc delete -f nginx-svc.yaml)
    7.  f5 pools begin deleting
    8.  Recreate workload service yaml (oc create -f ngninx-svc.yaml)
    9.  f5 pools are recreated.

#### Orchestration Version
OpenShift 3.9

#### Controller Version
K8S-BIGIP-Ctlr 1.5.0

#### BIG-IP Version
BIGIP 13.1.0.8

#### Workaround
Update route associated with service being deleted before deleting the service.

**Comment by sjberman** [comment]
This is an issue that affects both Ingress and Routes. Basically a virtual server that has multiple pools associated with it can see this issue if one of the services for a pool is deleted.

I have found the root cause and am working on the fix now.

**Comment by amudukutore** [comment]
FYI – we’ve just released bugfix version v1.6.1 for the BIG-IP Controller for Kubernetes and OpenShift (k8s-bigip-ctlr) to address some bugs filed recently.
 
Images for these versions are now public and accessible via the following links:
 
**BIG-IP Controller for Kubernetes v1.6.1**
DockerHub: https://hub.docker.com/r/f5networks/k8s-bigip-ctlr/
Docker CLI: `docker pull f5networks/k8s-bigip-ctlr:1.6.1`
GitHub: https://github.com/F5Networks/k8s-bigip-ctlr/releases/tag/v1.6.1
Solution Documentation: http://clouddocs.f5.com/containers/latest/kubernetes/
Product Documentation: http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
Release Notes: http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.6/RELEASE-NOTES.html
 
**BIG-IP Controller for OpenShift v1.6.1 (container built on RHEL7 base image)**
Red Hat Container Repository: https://access.redhat.com/containers/?tab=tags - /registry.connect.redhat.com/f5networks/k8s-bigip-ctlr
Docker CLI: `docker pull registry.connect.redhat.com/f5networks/k8s-bigip-ctlr`
GitHub: https://github.com/F5Networks/k8s-bigip-ctlr/releases/tag/v1.6.1
Solution Documentation: http://clouddocs.f5.com/containers/latest/kubernetes/
Product Documentation: http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
Release Notes: http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.6/RELEASE-NOTES.html
 
Note: This is a bugfix release and is essentially v1.6.0 + the following bug-fixes:
#743 - Controller doesn’t temporarily remove entire BIG-IP configs after deleting a single service.
#746 - Log messages and documentation added to ensure Route profile configuration is clear.
#486 - User cannot configure the controller to manage the Common partition.
