### ISSUE TITLE
k8s-bigip-ctlr appears to load a configmap but fails to create anything on the Big-IP

### ISSUE THREAD

**Issue by randyrue** [F5Networks/k8s-bigip-ctlr#750]
#### Description
Loading a configmap.yaml file via kubectl reports successful creation of the configmap but no objects are created on the Big-IP. Logs for the controller pod show:
```
[WARNING] Could not get config for ConfigMap: redis-dev - The partition '' in the ConfigMap does not match 'kubernetes' that the controller watches for
[ERROR] Error parsing ConfigMap test_redis-dev
```
Increasing the controller's logging level to debug doesn't provide any more detail on those two errors.
I can create an Ingress, indicating that the controller is successfully managing the Big-IP appliance i.e. the problem isn't with credentials, secrets or connectivity between the cluster and the Big-IP.

#### Kubernetes Version
1.11.2

#### Controller Version
Version: v1.6.1
Build: n1190-426970563

#### BIG-IP Version
11.6.0 (Build 6.0.442)

#### Diagnostic Information
ConfigMap.yaml:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-dev
  namespace: test
  labels:
    f5type: virtual-server
data:
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 26379,
          "serviceName": "redis-sentinel"
          }
        },
        "frontend": {
          "virtualAddress": {
            "port": 6379,
            "bindAddr": "10.6.164.227"
          },
          "partition": "kubernetes",
          "balance": "round-robin",
          "mode": "tcp"
        }
      }
```

**Comment by pdp2shirts** [comment]
@randyrue Have you created the "kubernetes" partition on the BIG-IP this controller is managing? The ConfigMap above refers to the "Kubernetes" partition, and manages the objects in that partition. But that partition must exist on the BIG-IP for the controller to manage the partition. 
The instructions for doing this are linked in the "Initial setup" section of this page: https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html

**Comment by amudukutore** [comment]
@randyrue - the incompatibility with BIG-IP versions < 11.6.1 is not new and has existing tickets (see
https://github.com/F5Networks/k8s-bigip-ctlr/issues/248). We don't have plans to support BIG-IP versions 11.x . Please upgrade to newer BIG-IP versions.
