### ISSUE TITLE
RFE: Support to trigger external automation actions such as AnsibleTower or Jenkins

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#751]
#### Description

The idea of this RFE is to trigger a REST call to an endpoint defined in the BIG-IP Controller configuration when there is a pool member update. This allows customization of the automation when there is such a relevant event.

The first use case of this is GTM integration. Given that GTM configuration is very versatile and has many options I believe that it is not worth to try having built-in support for GTM in BIG-IP Controller. Instead, by just triggering a single REST call to AnsibleTower or Jenkins would allow customer's required automation of GTM or any other tasks he might want to perform. Other use cases could be IPAM, FW or audit logging.

This REST call should send to the automation server as much information as possible so we don't limit the automation that customers can do. 

Areas of consideration are: should this action happen synchronously or asynchronously, pre or post LTM configuration? Some initial thoughts: 

- I think that most use cases would work just fine post-configuration of the LTM (after configuration has succeeded, not async), if the external automation is actually a pre-requisite it would just incur in a transient, initial delay. On the other hand by running the action post LTM configuration we can make sure that the LTM configuration took place.

- In the case that the endpoint call fails I don't see that we should do anything else other than logging the event. I don't see any policy we could apply in general when such condition occurs.

This feature should be implemented in all BIG-IP Controller incarnations, not only k8s/Openshift. Suggested initial endpoint types of automation servers would be AnsibleTower and Jenkins.

#### Kubernetes Version
NA

#### Controller Version
1.6

#### BIG-IP Version
NA

**Comment by alonsocamaro** [comment]
As it has been mentioned above I think that having a GTM integration built-in the BIG-IP controller is not the best path because it would require to either have only the typical options implemented or spend a lot of effort trying to implement all possible GTM configuration options in BIG-IP controller. This in turn would require BIG-IP Controller to deal with GTM versioning.

Another reason to opt for the approach described in this RFE is that using an Automation Server would also allow an operator to confirm/enable the changes that have been implemented in the GTM. For example, requiring an operator to enable a new wideip. This could not be done with an integrated approach.

**Comment by s-archer** [comment]
+1 for this idea.  I have two customers in the UK that could make use of this.

**Comment by trinaths** [comment]
inactive since 2018.
