### ISSUE TITLE
RFE: Ability to select the VServer Policy traffic matching strategy

### ISSUE THREAD

**Issue by efenex** [F5Networks/k8s-bigip-ctlr#755]
#### Description
Currently, the VServer Policy traffic matching strategy is hardcoded to be "first-match". We would like the ability to change this to "best-match".

Use case is as follows: we have multiple applications being deployed onto OpenShift, with Route objects configured by the k8s-bigip-ctlr onto the F5. One of these apps is the "root" app, meaning it is available on /. Other apps are configured on /\<appname\>. 

In the first-match policy, we have to ensure that the root app is always the last rule in the policy. This can only be ensure by deleting and re-adding the route for the "root" app whenever any route is added, since route order is based on creationTimestamp of the Route object. This approach means that we need to remove and readd the main route object for our application on every deploy, causing a short outage while the k8s-bigip-ctlr removes and readds the rule.

Using the best-match policy, traffic is directed towards the correct pod regardless of the route order, and we no longer need to recreate the root app rule.

#### OpenShift Version
3.9

#### Controller Version
1.6.1

#### BIG-IP Version
13.1.10.3 Build 0.0.5 Point Release 3

#### Diagnostic Information
Currently, the first-match policy appears to be hardcoded [here](https://github.com/F5Networks/k8s-bigip-ctlr/blob/25739b34e1be6340e743a68fc1afb0e274ac96b2/pkg/appmanager/routing.go#L184)

**Comment by sjberman** [comment]
See related issue #765
