### ISSUE TITLE
RFE: configurable appMgr watch time interval

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#762]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

in k8s-bigip-ctrl cmd/k8s-bigip-ctlr/main.go the appMgr watcher is hard coded with 30 seconds, users might prefer a configurable time interval to control the Virtual syncing from k8s cluster, also user might be confused this watcher sync period with node-poll-interval or verify-interval and thought changing the node-poll-intervla or verify-interval would affect virtual syncing from k8s which isn't. 

setupWatchers(appMgr, 30*time.Second)

### Kubernetes Version
Kubernetes 1.11.0

#### Controller Version
1.7.0
#### BIG-IP Version
13.1.0
#### Diagnostic Information

I changed the appMgr watcher to 60 seconds which result in log below with 60 seconds interval, it makes sense to make the watcher time period configurable to users can configure it as they wish 

2018/10/05 22:49:50 [DEBUG] Finished syncing virtual servers {Namespace:default ServiceName:nginxservice} (1.199878347s)

2018/10/05 22:50:49 [DEBUG] Finished syncing virtual servers {Namespace:default ServiceName:nginxservice} (8.955267ms)

Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by mdditt2000** [comment]
Looking to add this functionality in CIS 1.10 available soon. 
Allow the user to change the verify-interval for CCCL from the default 30 sec to configurable value. 
https://jira.pdsea.f5net.com/browse/CONTCNTR-770

**Comment by trinaths** [comment]
Using CIS with AS3, we dont post until there is change in resources being monitored. We can also configure this with as3-post-delay in controller deployment.
