### ISSUE TITLE
Enhancement Request: add ConfigMap serverssl support

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#768]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>
<For enhancement: Describe the enhancement request in detail>

 k8s-bigip-ctlr support both k8s Ingress and openshift route serverssl,  ConfigMap serverssl is not supported

#### Kubernetes Version
<Version of Kubernetes being used>
k8s v1.11.0

#### Controller Version
<Version of k8s-bigip-ctlr being used>
1.7.0

#### BIG-IP Version
<Version of BIG-IP being used>
13.1.0.8

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/resourceConfig.go#L1359
SslProfile only support client side ssl as customProfileClient

Ingress use f5ServerSslProfileAnnotation = "virtual-server.f5.com/serverssl", maybe extend it to ConfigMap ?

<pre>
if nil != cfgMap.VirtualServer.Frontend.SslProfile {
            if len(cfgMap.VirtualServer.Frontend.SslProfile.F5ProfileName) > 0 {
                profRef := convertStringToProfileRef(
                    cfgMap.VirtualServer.Frontend.SslProfile.F5ProfileName,
                    customProfileClient, ns)
                cfg.Virtual.AddOrUpdateProfile(profRef)
            } else {
                for _, profName := range cfgMap.VirtualServer.Frontend.SslProfile.F5ProfileNames {
                    profRef := convertStringToProfileRef(profName, customProfileClient, ns)
                    cfg.Virtual.AddOrUpdateProfile(profRef)
                }
            }
        }
</pre>

**Comment by vincentmli** [comment]
I come up with a patch to use annotation f5ServerSslProfileAnnotation similar to Ingress, tested and works in lab

<pre>
diff --git a/pkg/appmanager/profiles.go b/pkg/appmanager/profiles.go
index 8e0914c..66373ab 100644
--- a/pkg/appmanager/profiles.go
+++ b/pkg/appmanager/profiles.go
@@ -491,6 +491,21 @@ func (appMgr *Manager) deleteUnusedProfiles(
 							}
 						}
 					}
+					if serverProfile, ok :=
+						cm.ObjectMeta.Annotations[f5ServerSslProfileAnnotation]; ok == true {
+						appMgr.checkProfile(
+							prof,
+							&toRemove,
+							cm.ObjectMeta.Namespace,
+							serverProfile,
+							&referenced,
+						)
+						log.Infof("server ssl prof.name in deletedUnusedProfile: %s", prof.Name)
+		
+					}
+					if referenced {
+						break
+					}
 				}




diff --git a/pkg/appmanager/resourceConfig.go b/pkg/appmanager/resourceConfig.go
index 2a231a8..47640ba 100644
--- a/pkg/appmanager/resourceConfig.go
+++ b/pkg/appmanager/resourceConfig.go
@@ -1310,6 +1310,13 @@ func parseConfigMap(cm *v1.ConfigMap, schemaDBPath, snatPoolName string) (*Resou
 						}
 					}
 				}
+				if serverProfile, ok :=
+					cm.ObjectMeta.Annotations[f5ServerSslProfileAnnotation]; ok == true {
+					secretName := formatIngressSslProfileName(serverProfile)
+					profRef := convertStringToProfileRef(
+						secretName, customProfileServer, cm.ObjectMeta.Namespace)
+					cfg.Virtual.AddOrUpdateProfile(profRef)
+				}
 			} else {
 				var errors []string
 				for _, desc := range result.Errors() {

</pre>

ConfigMap Yaml

<pre>
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
     virtual-server.f5.com/serverssl: "Common/serverssl"
  name: configmap-https
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "nginxservice",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /\r\n",
            "recv": "200|OK",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 443,
            "bindAddr": "10.169.72.166"
          },
          "partition": "test",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileName": "Common/clientssl"
          }
        }
      }
    }
</pre>

BIGIP virtual deployed with serverssl
<pre>
ltm virtual default_configmap-https {
    destination 10.169.72.166%0:https
    ip-protocol tcp
    mask 255.255.255.255
    metadata {
        user_agent {
            value k8s-bigip-ctlr-1.7.0-WIP-root-d241ef0-20181016095731
        }
    }
    partition test
    pool cfgmap_default_configmap-https_nginxservice
    profiles {
        /Common/clientssl {
            context clientside
        }
        /Common/http { }
        /Common/serverssl {
            context serverside
        }
        /Common/tcp { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
    vs-index 67
}
</pre>

**Comment by mdditt2000** [comment]
This is supported using a configmap and AS3. Example https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-9/as3%20declaration/end-to-end-ssl.yaml

Closing issue
