### ISSUE TITLE
RFE - ASM-Policy for OpenShift Routes

### ISSUE THREAD

**Issue by joebride** [F5Networks/k8s-bigip-ctlr#769]
#### Description
Enhancement:
The BIG-IP Controller should assign ASM-Policy to OpenShift Routes.
-Each OpenShift Route should use an individual ASM-Policy.
-The ASM-Policy is pre-configured and located in Partition /Common.

#### Kubernetes Version
Kubernetes Master:v1.10.0+b81c8f8  
OpenShift Master:v3.10.45  

#### Controller Version
k8s-bigip-ctlr:1.6

#### BIG-IP Version
AWAF 13.1.0.8

#### Diagnostic Information
n/a

**Comment by mdditt2000** [comment]
https://jira.pdsea.f5net.com/browse/CONTCNTR-752

**Comment by mdditt2000** [comment]
Added support for WAF policy reference through virtual-server.f5.com/waf annotation in OpenShift Routes. https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.11/RELEASE-NOTES.html

**Comment by mdditt2000** [comment]
@joebride closing issue as resolved
