### ISSUE TITLE
Can I used two k8s-bigip-ctlr  control two different partitions of a bigip device?

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/k8s-bigip-ctlr#770]
#### Description
Hello
I have two different partitions, one called k8s partition and one called lilong partition  on the same device.In the kube-system namespace and I deployed two k8s-bigip-ctlr, One configured is"  - --bigip-url=192.168.0.134- --bigip-partition=k8s"  and the other configured as  "--bigip-url=192.168.0.134- --bigip-partition=lilong"
I found that only one partition  can write configuration in BIGIP by one  k8s-bigip-ctlr instance .
Can I used two k8s-bigip-ctlr  control two different partitions on the same bigip device?

Many Thanks
#### Kubernetes Version
<Version of Kubernetes being used>
v1.9.0"

#### Controller Version
<Version of k8s-bigip-ctlr being used>
1.6.1 (latest)

#### BIG-IP Version
<Version of BIG-IP being used>
BIG-IP 13.1.0.7 Build 0.0.1 Point Release 7

**Comment by vincentmli** [comment]
it appears  you can't not deploy two controllers to monitor different partitions on same BIGIP, I tried the same and got same result as you and got error like below, I did not dig further why this isn't allowed.

<pre>
2018/10/19 17:58:11 [WARNING] Could not get config for ConfigMap: configmap-https-1 - The partition 'test1' in the ConfigMap does not match 'test' that the controller watches for
Oct 19 10:58:11 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:11 [ERROR] Error parsing ConfigMap default_configmap-https-1
Oct 19 10:58:11 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:11 [ERROR] Error parsing ConfigMap default_configmap-https-1
Oct 19 10:58:11 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:11 [ERROR] Error parsing ConfigMap default_configmap-https-1
Oct 19 10:58:17 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:17 [ERROR] Error parsing ConfigMap default_configmap-https-1
Oct 19 10:58:17 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:17 [ERROR] Error parsing ConfigMap default_configmap-https-1
Oct 19 10:58:20 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:20 [ERROR] Error parsing ConfigMap default_configmap-https-0
Oct 19 10:58:20 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:20 [ERROR] Error parsing ConfigMap default_configmap-https-0
Oct 19 10:58:20 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:20 [WARNING] Could not get config for ConfigMap: configmap-https-0 - The partition 'test' in the ConfigMap does not match 'test1' that the controller watches for
Oct 19 10:58:20 centos-k8s-master dockerd-current[801]: 2018/10/19 17:58:20 [ERROR] Error parsing ConfigMap default_configmap-https-0
/pre>

**Comment by lilongabc** [comment]
@vincentmli Thank you most sincerely.

**Comment by myf5** [comment]
Seem like the partition in the configmap resource different to the partition of the ctlr.  Try separate them in different namespaces, different ctlr monitor different NS.

**Comment by vincentmli** [comment]
@myf5 I tried different ctlr to different partition, had not thought about different namespace, it is worth trying monitor different namespace

**Comment by lilongabc** [comment]
@vincentmli  @myf5  Thanks for your help：）
