### ISSUE TITLE
How to set verify-interval in k8s-bigip-ctlr?

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/k8s-bigip-ctlr#771]
#### Description
I read the article in the link below but didn't find out how to configure it.
https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.6/
I entered the container by command and I also did not find the configuration file..
"kubectl exec -it k8s-bigip-ctlr-deployment-5f77bb5955-fwlw8 sh -n kube-system"
How to set vs-snat-pool-name or verify-interval in k8s-bigip-ctlr?
Many Thanks
#### Kubernetes Version
v1.9.0

#### Controller Version
1.6.1 (latest)

#### BIG-IP Version
BIG-IP 13.1.0.7 Build 0.0.1 Point Release 7

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by amudukutore** [comment]
@lilongabc  - you can look at any deployments examples we have (https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/sample-k8s-bigip-ctlr-secrets.yaml for instance) and add `--vs-snat-pool-name=<name-of-snat-pool>` to the `args` section.

**Comment by lilongabc** [comment]
@amudukutore .Thank you most sincerely.
