### ISSUE TITLE
Request Enhancement: allow to  specify which openshift internal node ip as VTEP endpoint

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#773]
#### Description

<For enhancement: Describe the enhancement request in detail>

user  have multiple node ip on  openshift worker node and  would like to have an option to specify which node ip they can use in the net FDB entry configured by BIGIP for the VXLAN pod network.

for example:
two internal node ips:
<pre>
#oc describe node example-wrk-01
Name:               example-wrk-01
........CUT......
Addresses:
  InternalIP:  10.1.1.63
  InternalIP:  10.1.2.63
  Hostname:    example-wrk-01
............CUT....
</pre>

User prefer to use internal ip 10.1.1.63 for VTEP FDB entry in BIGIP for POD VXLAN traffic,  10.1.2.63 is for management traffic. the current k8s-bigip-ctrl would add both internal IPs to the VTEP FDB entry in BIGIP, user  hacked and hard coded a workaround here 
<pre>
nodeAddrs := node.Status.Addresses
rec := fdbRecord{}
for _, addr := range nodeAddrs {
	if addr.Type == addrType && strings.Contains(addr.Address, "10.1.1"){

</pre>

 but request to have a more robotic design to have this feature implemented.

 Examined 'useNodeInternal' option, not meeting this requirement.

#### Kubernetes Version
<Version of Kubernetes being used>
Openshift
#### Controller Version
<Version of k8s-bigip-ctlr being used>
1.6.1
#### BIG-IP Version
<Version of BIG-IP being used>
13.1.0.8
#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by mdditt2000** [comment]
Issue resolved in https://github.com/F5Networks/k8s-bigip-ctlr/issues/797

Bug is fixed in CIS 1.9.1
https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.9/RELEASE-NOTES.html

Closing this issue.
