### ISSUE TITLE
How to used two ssl profile  attach to the same one VS by configmap?

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/k8s-bigip-ctlr#781]
#### Description
Hello

How to used two ssl profile  attach to one VS by configmap?

Thanks
#### Kubernetes Version
v1.9.0"

#### BIG-IP Version
1.6.1 (latest)

#### Diagnostic Information
My yaml had erro log is "
2018/10/22 16:17:17 [WARNING] Could not get config for ConfigMap: f5-sni-configmap - invalid character '\'' looking for beginning of value
2018/10/22 16:17:17 [WARNING] Could not get config for ConfigMap: f5-sni-configmap - invalid character ']' looking for beginning of value

Configmap Yaml is below:
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-sni-configmap
  namespace: f51-namespace
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "f51-namespace-svc",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /",
            "recv": "Frontend",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 8443,
            "bindAddr": "192.168.0.140"
          },
          "partition": "f51-namespace",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileName": [
            "f51-namespace/f5ssl1",
            "f51-namespace/f5ssl2",
            ]
            }
          }
        }
      }
    }

**Comment by vincentmli** [comment]
according to code below, you should try F5ProfileNames instead of f5ProfileName
<pre>
"SslProfile": {
"F5ProfileNames": [
"f51-namespace/f5ssl1",
"f51-namespace/f5ssl2",
]
}

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/profiles.go#L479
if nil != cfgMap.VirtualServer.Frontend.SslProfile {
	ssl := cfgMap.VirtualServer.Frontend.SslProfile
		if len(ssl.F5ProfileName) > 0 {
				profNames = append(profNames, ssl.F5ProfileName)
		} else {
				for _, profName := range ssl.F5ProfileNames {
				     profNames = append(profNames, profName)
				}
		}
</pre>

**Comment by vincentmli** [comment]
if I recall correct,  you should also create the ssl profile in Common partition before you apply the configmap, do not create the ssl profile in f51-namespace the controller manages
<pre>

"SslProfile": {
"F5ProfileNames": [
"Common/f5ssl1",
"Common/f5ssl2",
]
}
</pre>

**Comment by lilongabc** [comment]
@vincentmli 
The changes still do not work properly.
My yaml is below:
--------------------------------
data:
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "f51-namespace-svc",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /",
            "recv": "Frontend",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 8443,
            "bindAddr": "192.168.0.140"
          },
          "partition": "f51-namespace",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileNames": [
            "Common/f5ssl1",
            "Common/f5ssl2",
            ]
          }
        }
      }
     }
  schema: f5schemadb://bigip-virtual-server_v0.1.7.json
kind: ConfigMap
metadata:
  creationTimestamp: 2018-10-23T14:43:18Z
  labels:
    f5type: virtual-server
  name: f5-sni-configmap
  namespace: f51-namespace
  resourceVersion: "4061764"
  selfLink: /api/v1/namespaces/f51-namespace/configmaps/f5-sni-configmap
  uid: fb6500e1-d6d1-11e8-86df-005056aa58a8
--------------------------------------

#My log display is error:
#[root@kube-master ~]# kubectl log cc-f51-namespace-6bf4789d57-5wb6q -n f51-namespace | grep f5-sni-configmap
2018/10/23 14:46:48 [WARNING] Could not get config for ConfigMap: f5-sni-configmap - invalid character ']' looking for beginning of value
2018/10/23 14:46:48 [ERROR] Error parsing ConfigMap f51-namespace_f5-sni-configmap
2018/10/23 14:47:18 [WARNING] Could not get config for ConfigMap: f5-sni-configmap - invalid character ']' looking for beginning of value
2018/10/23 14:47:18 [ERROR] Error parsing ConfigMap f51-namespace_f5-sni-configmap
2018/10/23 14:47:18 [ERROR] Error parsing ConfigMap f51-namespace_f5-sni-configmap
2018/10/23 14:47:48 [ERROR] Error parsing ConfigMap f51-namespace_f5-sni-configmap
2018/10/23 14:47:48 [WARNING] Could not get config for ConfigMap: f5-sni-configmap - invalid character ']' looking for beginning of value
2018/10/23 14:47:48 [ERROR] Error parsing ConfigMap f51-namespace_f5-sni-configmap
2018/10/23 14:47:48 [ERROR] Error parsing ConfigMap f51-namespace_f5-sni-configmap
2018/10/23 14:48:11 [WARNING] Could not get config for ConfigMap: f5-sni-configmap - invalid character ']' looking for beginning of value

Thanks

**Comment by vincentmli** [comment]
this is my yaml, it appears to be working

<pre>

kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
     virtual-server.f5.com/serverssl: "Common/serverssl"
  name: configmap-https
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "nginxservice",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /\r\n",
            "recv": "200|OK",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 443,
            "bindAddr": "10.169.72.160"
          },
          "partition": "test",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileNames": ["Common/clientssl-1", "Common/clientssl"]
          }
        }
      }
    }
</pre>

I get error

<pre>

2018/10/23 18:58:39 [INFO] Text: u'{"code":400,"message":"0107149e:3: Virtual server /test/default_configmap-https has more than one clientssl/serverssl profile with same server name.","errorStack":[],"apiError":3}'

</pre>

that is probably because my clientssl and clientssl-1 is  same default from clientssl

my config.json

[root@centos-k8s-master kubernetes]# cluster/kubectl.sh exec -it -n kube-system bigip-cc-5bff8fb9f7-jj5r8 -- sh -c "cat /tmp/k8s*/config.json" | jq "."

<pre>

{
  "bigip": {
    "username": "admin",
    "password": "admin",
    "url": "https://10.169.72.36",
    "partitions": [
      "test"
    ]
  },
  "global": {
    "log-level": "INFO",
    "verify-interval": 30,
    "vxlan-partition": "Common"
  },
  "resources": {
    "test": {
      "virtualServers": [
        {
          "name": "default_configmap-https",
          "pool": "/test/cfgmap_default_configmap-https_nginxservice",
          "destination": "/test/10.169.72.160:443",
          "enabled": true,
          "ipProtocol": "tcp",
          "sourceAddressTranslation": {
            "type": "automap"
          },
          "profiles": [
            {
              "name": "clientssl",
              "partition": "Common",
              "context": "clientside"
            },
            {
              "name": "clientssl-1",
              "partition": "Common",
              "context": "clientside"
            },
            {
              "name": "http",
              "partition": "Common",
              "context": "all"
            },
            {
              "name": "serverssl",
              "partition": "Common",
              "context": "serverside"
            },
            {
              "name": "tcp",
              "partition": "Common",
              "context": "all"
            }
          ]
        }
      ],
      "pools": [
        {
          "name": "cfgmap_default_configmap-https_nginxservice",
          "loadBalancingMode": "round-robin",
          "members": [
            {
              "address": "10.244.0.234",
              "port": 80,
              "session": "user-enabled"
            },
            {
              "address": "10.244.0.235",
              "port": 80,
              "session": "user-enabled"
            }
          ],
          "monitors": [
            "/test/cfgmap_default_configmap-https_nginxservice_0_http"
          ]
        }
      ],
      "monitors": [
        {
          "name": "cfgmap_default_configmap-https_nginxservice_0_http",
          "interval": 30,
          "type": "http",
          "send": "GET /\r\n",
          "recv": "200|OK",
          "timeout": 120
        }
      ]
    }
  },
  "vxlan-arp": {
    "arps": [
      {
        "name": "k8s-10.244.0.234",
        "ipAddress": "10.244.0.234",
        "macAddress": "f2:77:81:99:0d:e7"
      },
      {
        "name": "k8s-10.244.0.235",
        "ipAddress": "10.244.0.235",
        "macAddress": "f2:77:81:99:0d:e7"
      }
    ]
  },
  "vxlan-fdb": {
    "name": "flannel_vxlan",
    "records": [
      {
        "name": "f2:77:81:99:0d:e7",
        "endpoint": "10.169.72.93"
      }
    ]
  }
}

</pre>

so you should remove the extra ',' 
<pre>

"f5ProfileNames": [
"Common/f5ssl1",
"Common/f5ssl2"
]

</pre>

**Comment by lilongabc** [comment]
@vincentmli  Cool,Thanks for you help :+1: :100:
