### ISSUE TITLE
How to use k8s secret on Https Ingress?

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/k8s-bigip-ctlr#782]
#### Description
Hello 

I used kubectl  create tls secret,I want ues the secret (f5-k8s-secret)
apply https vs by ingress. I try use " - secretName: f5-k8s-secret",But the configuration is not in effect.
How to use secret？
Thanks 

#### Kubernetes Version
v1.9.0"

#### Controller Version
1.6.1 (latest)

#### BIG-IP Version
12.1.3.6

#### Diagnostic Information
r1master1:~ # kubectl get secret
NAME                                 TYPE                                  DATA      AGE
f5-k8s-secret                        kubernetes.io/tls                     2         12m
r1master1:~/f5_cc_yaml/http-https # kubectl describe ingress http2https -n f51-namespace
Name:             http2https
Namespace:        f51-namespace
Address:          197.3.63.129
Default backend:  default-http-backend:80 (<none>)
TLS:
  f5-k8s-secret terminates 
Rules:
  Host                           Path  Backends
  f51-namespace-svc.example.com  
                                 /   f51-namespace-svc:80 (<none>)
Annotations:
  allow-http:    false
  ssl-redirect:  true
Events:
  Type    Reason              Age                 From            Message
  Normal  ResourceConfigured  12s (x216 over 2h)  k8s-bigip-ctlr  Created a ResourceConfig 'ingress_197-3-63-129_443' for the Ingress.
  ----                           ----  --------
Yaml file is blow:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http2https
  namespace: f51-namespace
  annotations:
    virtual-server.f5.com/ip: "197.3.63.129"
    virtual-server.f5.com/partition: "f51-namespace"
    virtual-server.f5.com/health: |
      [
        {
          "path":     "f51-namespace-svc.example.com/",
          "send":     "GET /",
          "recv":     "Frontend",
          "interval": 5,
          "timeout":  10
        }
      ]
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/allow-http: "false"
spec:
  rules:
  - host: f51-namespace-svc.example.com
    http:
      paths:
      - backend:
          serviceName: f51-namespace-svc
          servicePort: 80
        path: /
  tls:
    - secretName: f5-k8s-secret

**Comment by tkam8** [comment]
Is your pod status showing as "CreateContainerConfigError"  ??

If so, try recreating your secret using below command format:

`kubectl create secret generic bigip-login -n kube-system --from-literal=username=admin --from-literal=password=admin`


Reference: https://stackoverflow.com/questions/50424754/pod-status-as-createcontainerconfigerror-in-minikube-cluster

**Comment by lilongabc** [comment]
@tkam8 
Do not display status CreateContainerConfigError.
I created  secret  tls is 5-k8s-secret,then used "secretName: f5-k8s-secret" at my yaml file.
But There is no SSL profile on virtual server.
root@(v13)(cfg-sync Standalone)(LICENSE EXPIRES IN 5 DAYS:Active)(/f51-namespace)(tmos)# list ltm virtual ingress_192-168-0-142_443 
ltm virtual ingress_192-168-0-142_443 {
    destination 192.168.0.142%0:https
    ip-protocol tcp
    mask 255.255.255.255
    metadata {
        user_agent {
            value k8s-bigip-ctlr-1.7.0-n1260-443736128
        }
    }
    partition f51-namespace
    pool ingress_f51-namespace_f51-namespace-svc
    profiles {
        /Common/http { }
        /Common/tcp { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
    vs-index 10463
}
 

Thanks

**Comment by tkam8** [comment]
Did you make sure your secret exists in your "f51-namespace" namespace?

**Comment by lilongabc** [comment]
@tkam8  You are right. The namespace "f51-namespace" not have this secret.Thanks for you help:)
