### ISSUE TITLE
Multiple ports on a service referenced in an ingress forces to single port

### ISSUE THREAD

**Issue by nconnor** [F5Networks/k8s-bigip-ctlr#784]
#### Description
For a single kubernetes service that exposes two different ports for two different purposes such as a main application and a custom control or heath app, a name-based ingress with a path to each port will result in a single pool on the BigIP, named for the service, with an unpredictable port selection from the available service ports. This ends up with both paths in the ingress pointing to the same port and preventing access to one of the desired ports. For each deployment of the ingress, the port selected by the controller is persistent. The workaround is to instruct our devs to expose and ingress only one port per service. 

#### Kubernetes Version
1.10

#### Controller Version
1.5.0

#### BIG-IP Version
12.1.3 build 0.0.378

**Comment by mhermsdorfer** [comment]
I'm also running into this issue with OpenShift Routes.

When you deploy a new route pointing to a service on a different port, all previously configured routes that use that same service will end up also pointing to the new port.  This is happening for the same reason @nconnor mentioned.  Currently only a single pool is created for a service.  There should at least be one pool created per service per port.  More likely, because health monitors should only apply to a single route, pools should be created on a per-route basis.  Otherwise health monitors from different routes could conflict with each other if they make use of the same service & port.

**Comment by vincentmli** [comment]
the function getServicePort  returns single port for a service

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/appManager.go#L1176

<pre>

func (appMgr *Manager) syncRoutes(
	stats *vsSyncStats,
	sKey serviceQueueKey,
	rsMap ResourceMap,
	svcPortMap map[int32]bool,
	svc *v1.Service,
	appInf *appInformer,
	dgMap InternalDataGroupMap,
) error {

		pStructs := []portStruct{{protocol: "http", port: DEFAULT_HTTP_PORT},
			{protocol: "https", port: DEFAULT_HTTPS_PORT}}
		for _, ps := range pStructs {
			rsCfg, err, pool := appMgr.createRSConfigFromRoute(
				route, svcName, appMgr.resources, appMgr.routeConfig, ps,
				appInf.svcInformer.GetIndexer(), svcFwdRulesMap, appMgr.vsSnatPoolName)
			if err != nil {
				log.Warningf("%v", err)
				continue
			}

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/resourceConfig.go#L1756

func (appMgr *Manager) createRSConfigFromRoute(
	route *routeapi.Route,
	svcName string,
	resources *Resources,
	routeConfig RouteConfig,
	pStruct portStruct,
	svcIndexer cache.Indexer,
	svcFwdRulesMap ServiceFwdRuleMap,
	snatPoolName string,
) (*ResourceConfig, error, Pool) {
	var rsCfg ResourceConfig
	rsCfg.MetaData.RouteProfs = make(map[routeKey]string)
	var policyName, rsName string

	if pStruct.protocol == "http" {
		policyName = "openshift_insecure_routes"
		rsName = routeConfig.HttpVs
	} else {
		policyName = "openshift_secure_routes"
		rsName = routeConfig.HttpsVs
	}

	var backendPort int32
	var err error
	if route.Spec.Port != nil {
		strVal := route.Spec.Port.TargetPort.StrVal
		if strVal == "" {
			backendPort = route.Spec.Port.TargetPort.IntVal
		} else {
			backendPort, err = getServicePort(route, svcName, svcIndexer, strVal)
			if nil != err {
				return &rsCfg, err, Pool{}
			}
		}

</pre>

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/resourceConfig.go#L2940

<pre>

func getServicePort(
	route *routeapi.Route,
	svcName string,
	svcIndexer cache.Indexer,
	name string,
) (int32, error) {
	ns := route.ObjectMeta.Namespace
	key := ns + "/" + svcName

	obj, found, err := svcIndexer.GetByKey(key)
	if nil != err {
		return 0, fmt.Errorf("Error looking for service '%s': %v", key, err)
	}
	if found {
		svc := obj.(*v1.Service)
		if name != "" {
			for _, port := range svc.Spec.Ports {
				if port.Name == name {
					return port.Port, nil
				}
			}
			return 0,
				fmt.Errorf("Could not find service port '%s' on service '%s'", name, key)
		} else {
			return svc.Spec.Ports[0].Port, nil
		}
	}
	return 0, fmt.Errorf("Could not find service ports for service '%s'", key)
}
</pre>

**Comment by mdditt2000** [comment]
Internal Jira CONTCNTR-1651 for PM tracking

**Comment by prabhatkarki** [comment]
Hi Mark,
We are on CIS2.0 and continue to see this "unpredictable port assignment to pool" issue when more than one ports are exposed on k8s services. 
Issue #1341 is reported on this on CIS2.0

Thanks
Prabhat

**Comment by mdditt2000** [comment]
No plans to add support for Ingress/Routes. -- Closing issue

- Works for CRD in CIS 2.2
- Adding for AS3 configmap in CIS 2.2.1. Internal PM Jira - CONTCNTR-2181 

Please monitor Issue below for Configmap

- https://github.com/F5Networks/k8s-bigip-ctlr/issues/1464
