### ISSUE TITLE
How to used configmap deploy iapp to BIG-IP? Thanks

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/k8s-bigip-ctlr#786]
#### Description
Hello Everyone
I want use the k8s configmap deploy iApp to BIG-IP.
I used the below YAML deployed, But it didn't work.
I don't want to manually specify pool member address in "pool__addr", Can it is be automatically found pods address like ingress?
How to do?
Thanks

My yaml is below:
kind: ConfigMap
apiVersion: v1
metadata:
  name: iappv1
  namespace: f51-namespace
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.2.json"
  data: |
    {
     "virtualServer": {
       "backend": {
         "serviceName": "f51-namespace-svc",
         "servicePort": 80
       },
       "frontend": {
         "partition": "f51-namespace",
         "iapp": "/Common/f5.http",
         "iappPoolMemberTable": {
           "name": "pool__members",
           "columns": [
               {"name": "addr", "kind": "IPAddress"},
               {"name": "port", "kind": "Port"},
               {"name": "connection_limit", "value": "0"}
           ]
         },
         "iappOptions": {
           "description": "Example iApp"
         },
         "iappVariables": {
           "monitor__monitor": "/#create_new#",
           "monitor__response": "none",
           "monitor__uri": "/",
           "net__client_mode": "wan",
           "net__server_mode": "lan",
           "pool__addr": "10.244.1.144",
           "pool__pool_to_use": "/#create_new#",
           "pool__port": "80"
         }
       }
      }
    }

Thanks

#### Kubernetes Version
v1.9.0

#### Controller Version
1.6.1 

#### BIG-IP Version
BIG-IP 13.1.0.7 Build 0.0.1 Point Release 7

#### Diagnostic Information
2018/10/31 15:03:01 [INFO] [2018-10-31 15:03:01,167 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /f51-namespace/f51-namespace_iapp.v1
2018/10/31 15:03:01 [ERROR] [2018-10-31 15:03:01,859 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiApplicationService) /f51-namespace/f51-namespace_iapp.v1.
2018/10/31 15:03:01 [ERROR] [2018-10-31 15:03:01,860 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/sys/application/service/
2018/10/31 15:03:01 [INFO] Text: u'{"code":400,"message":"01020061:3: IP Address 127.0.0.2 is invalid, loopback not allowed.","errorStack":[],"apiError":3}'
2018/10/31 15:03:01 [ERROR] [2018-10-31 15:03:01,861 f5_cccl.service.manager ERROR] Resource /f51-namespace/f51-namespace_iapp.v1 creation error, requeuing task...
2018/10/31 15:03:01 [INFO] [2018-10-31 15:03:01,861 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /f51-namespace/f51-namespace_iappv1
2018/10/31 15:03:03 [ERROR] [2018-10-31 15:03:03,190 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(ApiApplicationService) /f51-namespace/f51-namespace_iappv1.
2018/10/31 15:03:03 [ERROR] [2018-10-31 15:03:03,191 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/sys/application/service/
2018/10/31 15:03:03 [INFO] Text: u'{"code":400,"message":"0107003a:3: Pool member node (/f51-namespace/10.244.1.143) and existing node (/f51-namespace/10.244.1.143%0) cannot use the same IP Address (10.244.1.143).","errorStack":[],"apiError":3}'
2018/10/31 15:03:03 [ERROR] [2018-10-31 15:03:03,191 f5_cccl.service.manager ERROR] Resource /f51-namespace/f51-namespace_iappv1 creation error, requeuing task...
2018/10/31 15:03:05 [INFO] [2018-10-31 15:03:05,090 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /f51-namespace/f51-namespace_iapp.v1

**Comment by dgarrisonf5** [comment]
Hi @lilongabc.  I would recommend reviewing the example configmap that invokes an iApp template in the documentation located here: 

https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-deploy-iapp.html?highlight=iapp#deploy-the-iapp

A few notes:

It's somewhat confusing, but In the F5 HTTP iApp example, the "pool__addr" is actually the IP address to assign to the virtual server and the "pool__port" is the port to assign to the virtual server.

As specified in the below release note, as of Container Connector v1.4.0, if you want to use the F5 HTTP iApp template, it has to be the f5.http.v1.3.0rc3 version of the iApp.  You can download the latest iApp bundle from the F5 download site.  You will find this version of the iApp within the "Release_Candidates" subdirectory of the "HTTP" directory.

https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.4/RELEASE-NOTES.html#limitations

In your example, the schema reference is to an older version of the schema.  Please use this schema reference:

schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"

Can you please apply the recommended changes and report back?

Thanks

**Comment by lilongabc** [comment]
@dgarrisonf5  

My pool member is  pod f51-namespace-endpoint*  is blow:
[root@kube-master ~]# kubectl get pod  -n f51-namespace -o wide
NAME                                      READY     STATUS    RESTARTS   AGE       IP             NODE
cc-f51-namespace-6b5b95c9c9-98pdv         1/1       Running   0          1h        10.244.2.23    kube-node-2
f51-namespace-endpoint-5ff8594899-57p2m   1/1       Running   0          13d       10.244.1.144   kube-node-1
f51-namespace-endpoint-5ff8594899-bnsgr   1/1       Running   0          13d       10.244.2.18    kube-node-2
f51-namespace-endpoint-5ff8594899-bqlsg   1/1       Running   0          13d       10.244.1.143   kube-node-1
f51-namespace-endpoint-5ff8594899-g6hdp   1/1       Running   0          13d       10.244.2.17    kube-node-2
[root@kube-master ~]# 

My Yaml is blow:
virtual server is 192.168.0.150:8012
kind: ConfigMap
apiVersion: v1
metadata:
  name: http.iapp
  namespace: f51-namespace
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "f51-namespace-svc",
          "servicePort": 80
        },
        "frontend": {
          "partition": "f51-namespace",
          "iapp": "/Common/f5.http",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "iapp.http"
          },
          "iappVariables": {
            "net__client_mode": "wan",
            "net__server_mode": "lan",
            "pool__addr": "192.168.0.150",
            "pool__port": "8012"
          }
        }
      }
    }

CC log is below:
[root@kube-master ~]# kubectl logs -f cc-f51-namespace-6b5b95c9c9-98pdv   -n f51-namespace
2018/11/05 08:54:27 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2018/11/05 08:54:28 [INFO] [2018-11-05 08:54:28,330 f5_cccl.resource.resource INFO] Creating ApiApplicationService: /f51-namespace/f51-namespace_http.iapp
2018/11/05 08:54:30 [INFO] [2018-11-05 08:54:30,036 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.1.143
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,158 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.1.143.
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,159 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.1.143/
2018/11/05 08:54:30 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.1.143\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,159 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.1.143 delete error, requeuing task...
2018/11/05 08:54:30 [INFO] [2018-11-05 08:54:30,159 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.2.17
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,294 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.2.17.
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,295 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.2.17/
2018/11/05 08:54:30 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.2.17\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,295 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.2.17 delete error, requeuing task...
2018/11/05 08:54:30 [INFO] [2018-11-05 08:54:30,295 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.1.144
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,429 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.1.144.
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,429 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.1.144/
2018/11/05 08:54:30 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.1.144\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,429 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.1.144 delete error, requeuing task...
2018/11/05 08:54:30 [INFO] [2018-11-05 08:54:30,430 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.2.18
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,557 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.2.18.
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,558 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.2.18/
2018/11/05 08:54:30 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.2.18\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,558 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.2.18 delete error, requeuing task...
2018/11/05 08:54:30 [INFO] [2018-11-05 08:54:30,558 f5_cccl.resource.resource INFO] Deleting IcrVirtualAddress: /f51-namespace/192.168.0.150
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,736 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrVirtualAddress) /f51-namespace/192.168.0.150.
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,736 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/virtual-address/~f51-namespace~192.168.0.150/
2018/11/05 08:54:30 [INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /f51-namespace/192.168.0.150.","errorStack":[],"apiError":3}'
2018/11/05 08:54:30 [ERROR] [2018-11-05 08:54:30,736 f5_cccl.service.manager ERROR] Resource /f51-namespace/192.168.0.150 delete error, requeuing task...
2018/11/05 08:54:32 [INFO] [2018-11-05 08:54:32,016 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.1.143
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,120 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.1.143.
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,120 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.1.143/
2018/11/05 08:54:32 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.1.143\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,120 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.1.143 delete error, requeuing task...
2018/11/05 08:54:32 [INFO] [2018-11-05 08:54:32,121 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.2.17
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,256 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.2.17.
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,257 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.2.17/
2018/11/05 08:54:32 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.2.17\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,257 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.2.17 delete error, requeuing task...
2018/11/05 08:54:32 [INFO] [2018-11-05 08:54:32,257 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.1.144
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,372 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.1.144.
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,373 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.1.144/
2018/11/05 08:54:32 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.1.144\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,373 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.1.144 delete error, requeuing task...
2018/11/05 08:54:32 [INFO] [2018-11-05 08:54:32,373 f5_cccl.resource.resource INFO] Deleting IcrNode: /f51-namespace/10.244.2.18
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,503 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrNode) /f51-namespace/10.244.2.18.
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,504 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/node/~f51-namespace~10.244.2.18/
2018/11/05 08:54:32 [INFO] Text: u'{"code":400,"message":"01070110:3: Node address \'/f51-namespace/10.244.2.18\' is referenced by a member of pool \'/f51-namespace/f51-namespace_http.iapp.app/f51-namespace_http.iapp_pool\'.","errorStack":[],"apiError":3}'
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,504 f5_cccl.service.manager ERROR] Resource /f51-namespace/10.244.2.18 delete error, requeuing task...
2018/11/05 08:54:32 [INFO] [2018-11-05 08:54:32,505 f5_cccl.resource.resource INFO] Deleting IcrVirtualAddress: /f51-namespace/192.168.0.150
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,626 f5_cccl.resource.resource ERROR] HTTP error(400): CCCL resource(IcrVirtualAddress) /f51-namespace/192.168.0.150.
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,627 f5_cccl.service.manager ERROR] F5CcclResourceRequestError - 400 Unexpected Error: Bad Request for uri: https://192.168.0.134:443/mgmt/tm/ltm/virtual-address/~f51-namespace~192.168.0.150/
2018/11/05 08:54:32 [INFO] Text: u'{"code":400,"message":"01070344:3: Cannot delete referenced virtual address /f51-namespace/192.168.0.150.","errorStack":[],"apiError":3}'
2018/11/05 08:54:32 [ERROR] [2018-11-05 08:54:32,627 f5_cccl.service.manager ERROR] Resource /f51-namespace/192.168.0.150 delete error, requeuing task...
2018/11/05 08:54:33 [WARNING] Overwriting existing entry for backend {ServiceName:f51-namespace-svc ServicePort:80 Namespace:f51-namespace}
2018/11/05 08:54:33 [INFO] Wrote 0 Virtual Server and 1 IApp configs
2018/11/05 08:54:33 [WARNING] Overwriting existing entry for backend {ServiceName:f51-namespace-svc ServicePort:80 Namespace:f51-namespace}
2018/11/05 08:54:34 [INFO] Wrote 0 Virtual Server and 1 IApp configs

**Comment by mdditt2000** [comment]
@lilongabc are you still having issues. We have mad alot of progress moving away from iApps to AS3 JSON in a configmap. Let me know if i can demo this

**Comment by mdditt2000** [comment]
Closing this issue out. No response.
