### ISSUE TITLE
Please enable configmap to add custom irule

### ISSUE THREAD

**Issue by alarmdev** [F5Networks/k8s-bigip-ctlr#787]
#### Description
Currently the configmap does not support adding custom iRules and so can't add resources.
Please update the code to add iRules in the array.

configMapFrontend struct {
        Name     string `json:"name"`
        PoolName string `json:"pool,omitempty"`
        // Mutual parameter, partition
        Partition string `json:"partition,omitempty"`

        // VirtualServer parameters
        Balance               string                `json:"balance,omitempty"`
        Mode                  string                `json:"mode,omitempty"`
        VirtualAddress        *virtualAddress       `json:"virtualAddress,omitempty"`
        Destination           string                `json:"destination,omitempty"`
        Enabled               bool                  `json:"enabled,omitempty"`
        IpProtocol            string                `json:"ipProtocol,omitempty"`
        SourceAddrTranslation SourceAddrTranslation `json:"sourceAddressTranslation,omitempty"`
        SslProfile            *sslProfile           `json:"sslProfile,omitempty"`
        Policies              []nameRef             `json:"policies,omitempty"`
        IRules                []string              `json:"rules,omitempty"`
        Profiles              ProfileRefs           `json:"profiles,omitempty"`

#### Kubernetes Version
1.11

#### Controller Version
latest

#### BIG-IP Version
1.12

**Comment by orchmaster** [comment]
New enhancement request for configmap

**Comment by vincentmli** [comment]
I have a non-working patch which I think is getting close, there is something still missing, any input would be helpful.

<pre>
diff --git a/pkg/appmanager/resourceConfig.go b/pkg/appmanager/resourceConfig.go
index 43a5f44..d3306f5 100644
--- a/pkg/appmanager/resourceConfig.go
+++ b/pkg/appmanager/resourceConfig.go
@@ -1376,6 +1376,12 @@ func copyConfigMap(virtualName, ns, snatPoolName string, cfg *ResourceConfig, cf
                                }
                        }
                }
+               if len(cfgMap.VirtualServer.Frontend.IRules) > 0 {
+                       for _, iruleName := range cfgMap.VirtualServer.Frontend.IRules {
+                               log.Infof("iruleName: %s ", iruleName)
+                               cfg.Virtual.AddIRule(iruleName)
+                       }
+               }
        } else {
                // Handle IApp specific config.
                cfg.MetaData.ResourceType = "iapp"
diff --git a/schemas/bigip-virtual-server_v0.1.7.json b/schemas/bigip-virtual-server_v0.1.7.json
index 3ded0d0..51dbb02 100644
--- a/schemas/bigip-virtual-server_v0.1.7.json
+++ b/schemas/bigip-virtual-server_v0.1.7.json
@@ -74,6 +74,7 @@
         "partition": { "type": "string", "minLength": 1 },
         "mode": { "type": "string", "enum": [ "http", "tcp", "udp" ] },
         "sslProfile": { "$ref": "#/definitions/sslProfileType" },
+       "IRules": { "type": "array", "items": { "type": "string", "minLength": 1 } },
         "virtualAddress": { "$ref": "#/definitions/virtualAddressType" }
       },
       "additionalProperties": false,
</pre>

and the configmap yaml as:

<pre>
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
     virtual-server.f5.com/serverssl: "Common/serverssl"
  name: configmap-https-0
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "nginxservice",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /\r\n",
            "recv": "200|OK",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 443,
            "bindAddr": "10.169.72.160"
          },
          "partition": "test",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileName": "Common/clientssl"
          },
          "IRules": ["Common/http_responder"]
        }
      }
    }
</pre>

the configmap seems to be deployed in k8s ok

<pre>
[root@centos-k8s-master kubernetes]# cluster/kubectl.sh get configmap configmap-https-0 -o yaml
apiVersion: v1
data:
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "nginxservice",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /\r\n",
            "recv": "200|OK",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 443,
            "bindAddr": "10.169.72.160"
          },
          "partition": "test",
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileName": "Common/clientssl"
          },
          "IRules": ["Common/http_responder"]
        }
      }
    }
  schema: f5schemadb://bigip-virtual-server_v0.1.7.json
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"data":"{\n  \"virtualServer\": {\n    \"backend\": {\n      \"servicePort\": 80,\n      \"serviceName\": \"nginxservice\",\n      \"healthMonitors\": [{\n        \"interval\": 30,\n        \"protocol\": \"http\",\n        \"send\": \"GET /\\r\\n\",\n        \"recv\": \"200|OK\",\n        \"timeout\": 120\n      }]\n    },\n    \"frontend\": {\n      \"virtualAddress\": {\n        \"port\": 443,\n        \"bindAddr\": \"10.169.72.160\"\n      },\n      \"partition\": \"test\",\n      \"balance\": \"round-robin\",\n      \"mode\": \"http\",\n      \"sslProfile\": {\n      \"f5ProfileName\": \"Common/clientssl\"\n      },\n      \"IRules\": [\"Common/http_responder\"]\n    }\n  }\n}\n","schema":"f5schemadb://bigip-virtual-server_v0.1.7.json"},"kind":"ConfigMap","metadata":{"annotations":{"virtual-server.f5.com/serverssl":"Common/serverssl"},"labels":{"f5type":"virtual-server"},"name":"configmap-https-0","namespace":"default"}}
    status.virtual-server.f5.com/ip: 10.169.72.160
    virtual-server.f5.com/serverssl: Common/serverssl
  creationTimestamp: 2018-11-07T01:43:03Z
  labels:
    f5type: virtual-server
  name: configmap-https-0
  namespace: default
  resourceVersion: "12261"
  selfLink: /api/v1/namespaces/default/configmaps/configmap-https-0
  uid: 77368858-e22e-11e8-8e40-005056862f17
</pre>

but the if condition below is not true for something I am still missing, thus the virtual in config.json is not populated with the irule

<pre>
+               if len(cfgMap.VirtualServer.Frontend.IRules) > 0 {
+                       for _, iruleName := range cfgMap.VirtualServer.Frontend.IRules {
+                               log.Infof("iruleName: %s ", iruleName)
+                               cfg.Virtual.AddIRule(iruleName)
+                       }
+               }
</pre>

still digging, any clue?

**Comment by IliaGershenzon** [comment]
Joining the feature request :0

**Comment by opsmail** [comment]
+1

**Comment by Hamdan-Atypon** [comment]
+1

**Comment by umomany** [comment]
+1

**Comment by mdditt2000** [comment]
@vincentmli did your commit get approved?

**Comment by mdditt2000** [comment]
Please note you can add a  custom irule using CIS 1.9.1 and AS3 in the configmap. Here is the documentation. 

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/examples.html

Example 4: Calling resources from a URL source¶
In this example, we show how AS3 can fetch an external resource value from a URL using HTTP or HTTPS. This is useful if you have a bulky configuration resource (such as an F5 WAF security policy (see WAF Policy) or an iRule); you can store the resource on a webserver under your control, then include a URL reference to it in the declaration. In this example, our declaration includes an “under maintenance” iRule from a URL source. In this example, we also set the historyLimit, which sets the number of previously-deployed declarations AS3 saves for review using GET (for example using ?age=list) and for use with POST action redeploy and redeployAge=N.

Partition (tenant) named Sample_04.
A HTTP virtual server named serviceMain, which includes the iRule pulled from an external location.

**Comment by mdditt2000** [comment]
PM Jira CONTCNTR-910 - request PD to approve @vincentmli commit

**Comment by trinaths** [comment]
use override AS3 with custom irule.

https://github.com/mdditt2000/openshift-3-11/blob/master/examples/as3-override/f5-override-as3-declaration.yaml
