### ISSUE TITLE
Documentation inconsistent on TLS re-encrypt support with OpenShift Routes

### ISSUE THREAD

**Issue by mhermsdorfer** [F5Networks/k8s-bigip-ctlr#792]
#### Description
The documentation is inconsistent if TLS re-encrypt supports path/URI routing or not.

In the [Supported Route Configurations](https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.7/#supported-route-configurations) table, the table shows "Yes" for "Path Support" with "Re-encrypt Terminated".  However, above the table, there is a message box stating: "The k8s-bigip-ctlr does not support path-based routes for TLS re-encryption."

Additionally, if you look at the sample yaml files for "TLS re-encryption" found [here](https://clouddocs.f5.com/containers/v2/openshift/kctlr-openshift-routes.html#re-encryption-termination), you see a similar inconsistency.  There is a text box with the message: "The BIG-IP Controller does not support path-based Routes for TLS re-encryption."  Right above an example YAML file that contains a path, exactly the item claimed to be unsupported:
```
spec:
  host: mysite.example.com
  path: "/myApp"
```

Finally, if you do create TLS re-encrypt routes in OpenShift with PATH/URI based route statements, they  appear to be configured correctly by k8s-bigip-ctlr.  In testing, the host & URI are added to the secure_routes LTM Policy, and the iRule data-groups get updated such that a server-ssl profile is added for any host header with re-encrypted routes.

It's not clear why there are claims for lack of support.  By all appearances, k8s-bigip-ctrl supports path based routes with re-encrypt.

#### OpenShift Version
3.11

#### Controller Version
1.7

#### BIG-IP Version
13.1.1.0.8

#### Diagnostic Information

N/A, doc issue.

**Comment by mdditt2000** [comment]
https://jira.pdsea.f5net.com/browse/CONTCNTR-310

**Comment by mdditt2000** [comment]
Supports a single path-based route for TLS re-encryption. Multiple path-based routes are not currently supported.
