### ISSUE TITLE
iRule used to select server-ssl profile does not take into account URI path routing.

### ISSUE THREAD

**Issue by mhermsdorfer** [F5Networks/k8s-bigip-ctlr#793]
#### Description
In OpenShift, routes can have different TLS termination configurations within a single host-name.

For example, consider the following routes:
```
oc get routes
NAME                   HOST/PORT          PATH          SERVICES        PORT          TERMINATION          WILDCARD
example.com-static     example.com        /             crs-app-anf     https         reencrypt            None
example.com            example.com        /static       crs-app-anf     http-static   edge                 None
```

Everything for example.com should be re-encrypt with a server-ssl profile, EXCEPT /static, which should be edgeTerminated and be sent to the container in cleartext.

Right now, the decision to re-encrypt and apply a server-profile happens in the iRule at the ClientSSL handshake.  This is too early to support the fact that that some paths may need re-encrypted while others may not.

Currently, k8s-bigip-ctlr will apply a server-ssl profile for any request to example.com, re-encrypting all paths.  Ideally, this decision would be made later in the process at HTTP_REQUEST so that the URI could be taken into account before applying a server-ssl profile.

#### OpenShift Version
3.11

#### Controller Version
1.7

#### BIG-IP Version
13.1.1.0.8

#### Diagnostic Information

In general this issue is due to the fact that the decision to enable server-ssl profile, and which server-ssl profile to apply, should happen after the HTTP request is received on the client-side, and before it being sent to the server-side.  Currently, it happens either too early in the process, and/or does not take into account the HTTP::path of the request from the client.

Currently, the decision to enable server-ssl is made in the openshift_passthrough_irule, at line 126 though 131:
```
elseif { [class exists $reencrypt_class] } {
	set dflt_pool [class match -value $servername_lower equals $reencrypt_class]
	if { not ($dflt_pool equals "") } {
		SSL::enable serverside
	}
}
```
There are two issues here:
1) The data-group only has host-name data, no URI data for an iRule to make a decision.
2) This happens in the CLIENT_DATA, event, and we only get into this logic block if the packet received is a clientssl handshake.

A similar issue occurs when the iRule selects which server-ssl profile should be used.  Currently, this happens in SERVER_CONNECTED which is fine, however it does not take the HTTP::path from the client-side of the reuqest into account when making the decision.  The data-groups need to contain both server name & path, then the logic should be modified to inspect the path and select a server-ssl profile that is appropriate.
```
when SERVER_CONNECTED {
	set svrssl_class "/openshift-ocpd-dmz/ssl_reencrypt_serverssl_dg"
	if { [class exists $svrssl_class] } {
		set profile [class match -value $servername_lower equals $svrssl_class]
		if { not ($profile equals "") } {
			SSL::profile $profile
		}
	}
}
```

**Comment by veeramalla-f5** [comment]
This is fixed in 1.14. please migrate to the latest version.
