### ISSUE TITLE
About set up partition value in Yaml file.

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/k8s-bigip-ctlr#803]
#### Description
Hi 
I found install  f5-bigip-ctlr is yaml have bigip-partition parameter and it is required in the article.
But then I found out "partition" again in the data "Frontend" field location.
How to set partition value？Which partition configuration has the highest priority?
Article link: https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.7/#installation
Thanks
Happy NewYear Everyone

#### Kubernetes Version
v1.9.0

#### Controller Version
1.6.1

#### BIG-IP Version
BIG-IP 13.1.0.7 Build 0.0.1 Point Release 7

#### Diagnostic Information

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=admin",
            "--bigip-password=admin",
            "--bigip-url=192.168.0.134",
            "--bigip-partition=k8s",    《-----------------------------------------------------Here
            "--pool-member-type=nodeport"
            ]
      imagePullSecrets:
        # Secret that gives access to a private docker registry
        - name: f5-docker-images
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login

kind: ConfigMap
apiVersion: v1
metadata:
  name: my-vs-https
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "myService",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /",
            "recv": "Frontend",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 8443,
            "bindAddr": "192.168.0.134"
          },
          "partition": "k8s", <---------------------------------------------Here
          "balance": "round-robin",
          "mode": "http",
          "sslProfile": {
          "f5ProfileName": "Common/clientssl"
          }
        }
      }
    }

**Comment by myf5** [comment]
They are must be same, no priority for someone. This help to make sure the correct cc find the correct configmap for the correct partition.

if they are different, you can find the similar error:
```
2018/12/29 14:55:14 [WARNING] Could not get config for ConfigMap: nginx-deploy-svc.vs - The partition 'cka' in the ConfigMap does not match 'k8s' that the controller watches for
2018/12/29 14:55:23 [WARNING] Could not get config for ConfigMap: nginx-deploy-svc.vs - The partition 'cka' in the ConfigMap does not match 'k8s' that the controller watches for
2018/12/29 14:55:23 [ERROR] Error parsing ConfigMap default_nginx-deploy-svc.vs

```

**Comment by mdditt2000** [comment]
They are must be same. Please make sure the "partition": "k8s" is configured on the big-ip

**Comment by RainyBow** [comment]
I meet this error:

> 2019-01-24T06:28:30.619877752Z 2019/01/24 06:28:30 [WARNING] Could not get config for ConfigMap: f5-vs-nginx-ds - The partition '' in the ConfigMap does not match 'kubernetes' that the controller watches fo

I has created the partition kubernetes on bigip:

>admin@(localhost)(cfg-sync Standalone)(Active)(/kubernetes)(tmos)#  
the cc and configmap below:
[root@kube-node1 ~]# kubectl get ConfigMap f5-vs-nginx-ds -o yaml

> apiVersion: v1
> data:
>   data: |
>     {
>       "virtualServer": {
>         "backend": {
>           "servicePort": 80,
>           "serviceName": "nginx-ds"
>           }
>         },
>         "frontend": {
>           "virtualAddress": {
>             "port": 80,
>             "bindAddr": "1.2.3.4"
>           },
>           "partition": "kubernetes",
>           "balance": "round-robin",
>           "mode": "tcp"
>         }
>       }
>   schema: f5schemadb://bigip-virtual-server_v0.1.7.json
> kind: ConfigMap
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"v1","data":{"data":"{\n  \"virtualServer\": {\n    \"backend\": {\n      \"servicePort\": 80,\n      \"serviceName\": \"nginx-ds\"\n      }\n    },\n    \"frontend\": {\n      \"virtualAddress\": {\n        \"port\": 80,\n        \"bindAddr\": \"1.2.3.4\"\n      },\n      \"partition\": \"kubernetes\",\n      \"balance\": \"round-robin\",\n      \"mode\": \"tcp\"\n    }\n  }\n","schema":"f5schemadb://bigip-virtual-server_v0.1.7.json"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"f5type":"virtual-server"},"name":"f5-vs-nginx-ds","namespace":"default"}}
>   creationTimestamp: 2019-01-24T06:20:17Z
>   labels:
>     f5type: virtual-server
>   name: f5-vs-nginx-ds
>   namespace: default
>   resourceVersion: "108910"
>   selfLink: /api/v1/namespaces/default/configmaps/f5-vs-nginx-ds
>   uid: 1e7a0f33-1fa0-11e9-ae78-005056ad7fdc

[root@kube-node1 ~]# kubectl get pod k8s-bigip-ctlr-deployment-6d579f4b97-gr7nt -n kube-system -o yaml

> apiVersion: v1
> kind: Pod
> metadata:
>   creationTimestamp: 2019-01-24T05:36:56Z
>   generateName: k8s-bigip-ctlr-deployment-6d579f4b97-
>   labels:
>     app: k8s-bigip-ctlr
>     pod-template-hash: "2813590653"
>   name: k8s-bigip-ctlr-deployment-6d579f4b97-gr7nt
>   namespace: kube-system
>   ownerReferences:
>   - apiVersion: extensions/v1beta1
>     blockOwnerDeletion: true
>     controller: true
>     kind: ReplicaSet
>     name: k8s-bigip-ctlr-deployment-6d579f4b97
>     uid: 0fd0d3cd-1f9a-11e9-ae78-005056ad7fdc
>   resourceVersion: "104589"
>   selfLink: /api/v1/namespaces/kube-system/pods/k8s-bigip-ctlr-deployment-6d579f4b97-gr7nt
>   uid: 0fd3d707-1f9a-11e9-ae78-005056ad7fdc
> spec:
>   containers:
>   - args:
>     - --bigip-username=$(BIGIP_USERNAME)
>     - --bigip-password=$(BIGIP_PASSWORD)
>     - --bigip-url=192.168.220.215
>     - --bigip-partition=kubernetes
>     - --pool-member-type=nodeport
>     command:
>     - /app/bin/k8s-bigip-ctlr
>     env:
>     - name: BIGIP_USERNAME
>       valueFrom:
>         secretKeyRef:
>           key: username
>           name: bigip-login
>     - name: BIGIP_PASSWORD
>       valueFrom:
>         secretKeyRef:
>           key: password
>           name: bigip-login
>     image: f5networks/k8s-bigip-ctlr
>     imagePullPolicy: Always
>     name: k8s-bigip-ctlr
>     resources: {}
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     volumeMounts:
>     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       name: bigip-ctlr-token-szkbt
>       readOnly: true
>   dnsPolicy: ClusterFirst
>   imagePullSecrets:
>   - name: f5-docker-images
>   - name: bigip-login
>   nodeName: kube-node3
>   restartPolicy: Always
>   schedulerName: default-scheduler
>   securityContext: {}
>   serviceAccount: bigip-ctlr
>   serviceAccountName: bigip-ctlr
>   terminationGracePeriodSeconds: 30
>   tolerations:
>   - effect: NoExecute
>     key: node.kubernetes.io/not-ready
>     operator: Exists
>     tolerationSeconds: 300
>   - effect: NoExecute
>     key: node.kubernetes.io/unreachable
>     operator: Exists
>     tolerationSeconds: 300
>   volumes:
>   - name: bigip-ctlr-token-szkbt
>     secret:
>       defaultMode: 420
>       secretName: bigip-ctlr-token-szkbt
> status:
>   conditions:
>   - lastProbeTime: null
>     lastTransitionTime: 2019-01-24T05:36:56Z
>     status: "True"
>     type: Initialized
>   - lastProbeTime: null
>     lastTransitionTime: 2019-01-24T05:39:31Z
>     status: "True"
>     type: Ready
>   - lastProbeTime: null
>     lastTransitionTime: 2019-01-24T05:36:56Z
>     status: "True"
>     type: PodScheduled
>   containerStatuses:
>   - containerID: docker://2f1e54d02983960bdf79be3733b3a91dc8ceb73bdab5d22992e3f891d81009db
>     image: f5networks/k8s-bigip-ctlr:latest
>     imageID: docker-pullable://f5networks/k8s-bigip-ctlr@sha256:32e391b85b1cd100fd4d0e471e8fda0c02397089710db1bba8140337ed3ddbda
>     lastState: {}
>     name: k8s-bigip-ctlr
>     ready: true
>     restartCount: 0
>     state:
>       running:
>         startedAt: 2019-01-24T05:39:30Z
>   hostIP: 192.168.208.53
>   phase: Running
>   podIP: 172.30.77.4
>   qosClass: BestEffort
>   startTime: 2019-01-24T05:36:56Z

**Comment by RainyBow** [comment]
> I meet this error:
> 
> > 2019-01-24T06:28:30.619877752Z 2019/01/24 06:28:30 [WARNING] Could not get config for ConfigMap: f5-vs-nginx-ds - The partition '' in the ConfigMap does not match 'kubernetes' that the controller watches fo
> 
> I has created the partition kubernetes on bigip:
> 
> > admin@(localhost)(cfg-sync Standalone)(Active)(/kubernetes)(tmos)#
> > the cc and configmap below:
> > [root@kube-node1 ~]# kubectl get ConfigMap f5-vs-nginx-ds -o yaml
> 
> > apiVersion: v1
> > data:
> > data: |
> > {
> > "virtualServer": {
> > "backend": {
> > "servicePort": 80,
> > "serviceName": "nginx-ds"
> > }
> > },
> > "frontend": {
> > "virtualAddress": {
> > "port": 80,
> > "bindAddr": "1.2.3.4"
> > },
> > "partition": "kubernetes",
> > "balance": "round-robin",
> > "mode": "tcp"
> > }
> > }
> > schema: f5schemadb://bigip-virtual-server_v0.1.7.json
> > kind: ConfigMap
> > metadata:
> > annotations:
> > kubectl.kubernetes.io/last-applied-configuration: |
> > {"apiVersion":"v1","data":{"data":"{\n  "virtualServer": {\n    "backend": {\n      "servicePort": 80,\n      "serviceName": "nginx-ds"\n      }\n    },\n    "frontend": {\n      "virtualAddress": {\n        "port": 80,\n        "bindAddr": "1.2.3.4"\n      },\n      "partition": "kubernetes",\n      "balance": "round-robin",\n      "mode": "tcp"\n    }\n  }\n","schema":"f5schemadb://bigip-virtual-server_v0.1.7.json"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"f5type":"virtual-server"},"name":"f5-vs-nginx-ds","namespace":"default"}}
> > creationTimestamp: 2019-01-24T06:20:17Z
> > labels:
> > f5type: virtual-server
> > name: f5-vs-nginx-ds
> > namespace: default
> > resourceVersion: "108910"
> > selfLink: /api/v1/namespaces/default/configmaps/f5-vs-nginx-ds
> > uid: 1e7a0f33-1fa0-11e9-ae78-005056ad7fdc
> 
> [root@kube-node1 ~]# kubectl get pod k8s-bigip-ctlr-deployment-6d579f4b97-gr7nt -n kube-system -o yaml
> 
> > apiVersion: v1
> > kind: Pod
> > metadata:
> > creationTimestamp: 2019-01-24T05:36:56Z
> > generateName: k8s-bigip-ctlr-deployment-6d579f4b97-
> > labels:
> > app: k8s-bigip-ctlr
> > pod-template-hash: "2813590653"
> > name: k8s-bigip-ctlr-deployment-6d579f4b97-gr7nt
> > namespace: kube-system
> > ownerReferences:
> > 
> > * apiVersion: extensions/v1beta1
> >   blockOwnerDeletion: true
> >   controller: true
> >   kind: ReplicaSet
> >   name: k8s-bigip-ctlr-deployment-6d579f4b97
> >   uid: 0fd0d3cd-1f9a-11e9-ae78-005056ad7fdc
> >   resourceVersion: "104589"
> >   selfLink: /api/v1/namespaces/kube-system/pods/k8s-bigip-ctlr-deployment-6d579f4b97-gr7nt
> >   uid: 0fd3d707-1f9a-11e9-ae78-005056ad7fdc
> >   spec:
> >   containers:
> > * args:
> >   
> >   * --bigip-username=$(BIGIP_USERNAME)
> >   * --bigip-password=$(BIGIP_PASSWORD)
> >   * --bigip-url=192.168.220.215
> >   * --bigip-partition=kubernetes
> >   * --pool-member-type=nodeport
> >     command:
> >   * /app/bin/k8s-bigip-ctlr
> >     env:
> >   * name: BIGIP_USERNAME
> >     valueFrom:
> >     secretKeyRef:
> >     key: username
> >     name: bigip-login
> >   * name: BIGIP_PASSWORD
> >     valueFrom:
> >     secretKeyRef:
> >     key: password
> >     name: bigip-login
> >     image: f5networks/k8s-bigip-ctlr
> >     imagePullPolicy: Always
> >     name: k8s-bigip-ctlr
> >     resources: {}
> >     terminationMessagePath: /dev/termination-log
> >     terminationMessagePolicy: File
> >     volumeMounts:
> >   * mountPath: /var/run/secrets/kubernetes.io/serviceaccount
> >     name: bigip-ctlr-token-szkbt
> >     readOnly: true
> >     dnsPolicy: ClusterFirst
> >     imagePullSecrets:
> > * name: f5-docker-images
> > * name: bigip-login
> >   nodeName: kube-node3
> >   restartPolicy: Always
> >   schedulerName: default-scheduler
> >   securityContext: {}
> >   serviceAccount: bigip-ctlr
> >   serviceAccountName: bigip-ctlr
> >   terminationGracePeriodSeconds: 30
> >   tolerations:
> > * effect: NoExecute
> >   key: node.kubernetes.io/not-ready
> >   operator: Exists
> >   tolerationSeconds: 300
> > * effect: NoExecute
> >   key: node.kubernetes.io/unreachable
> >   operator: Exists
> >   tolerationSeconds: 300
> >   volumes:
> > * name: bigip-ctlr-token-szkbt
> >   secret:
> >   defaultMode: 420
> >   secretName: bigip-ctlr-token-szkbt
> >   status:
> >   conditions:
> > * lastProbeTime: null
> >   lastTransitionTime: 2019-01-24T05:36:56Z
> >   status: "True"
> >   type: Initialized
> > * lastProbeTime: null
> >   lastTransitionTime: 2019-01-24T05:39:31Z
> >   status: "True"
> >   type: Ready
> > * lastProbeTime: null
> >   lastTransitionTime: 2019-01-24T05:36:56Z
> >   status: "True"
> >   type: PodScheduled
> >   containerStatuses:
> > * containerID: docker://2f1e54d02983960bdf79be3733b3a91dc8ceb73bdab5d22992e3f891d81009db
> >   image: f5networks/k8s-bigip-ctlr:latest
> >   imageID: docker-pullable://f5networks/k8s-bigip-ctlr@sha256:32e391b85b1cd100fd4d0e471e8fda0c02397089710db1bba8140337ed3ddbda
> >   lastState: {}
> >   name: k8s-bigip-ctlr
> >   ready: true
> >   restartCount: 0
> >   state:
> >   running:
> >   startedAt: 2019-01-24T05:39:30Z
> >   hostIP: 192.168.208.53
> >   phase: Running
> >   podIP: 172.30.77.4
> >   qosClass: BestEffort
> >   startTime: 2019-01-24T05:36:56Z

and the kubernetes version:
[root@kube-node1 ~]# kubectl version

> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

BIGIP：BIG-IP 13.1.0.8 Build 0.0.3 Point Release 8    
    BIG-IP Virtual Edition 
Licensed Version    13.1.0

**Comment by mdditt2000** [comment]
Item is resolved and can be closed out
