### ISSUE TITLE
Create Multi-arch docker image 'f5devcentral/attributions-generator:latest'  for IBM ppc64le platform

### ISSUE THREAD

**Issue by Basavaraju013** [F5Networks/k8s-bigip-ctlr#806]
#### Description
`Make docs` is  internally using docker image `f5devcentral/attributions-generator:latest`, which is only available on x86 platform. for other archs, like IBM ppc64le, its failed with exec error. this issue created to enable Multi-arch  "f5devcentral/attributions-generator:latest" docker image.

```
+ATTR_GEN_IMG=f5devcentral/attributions-generator:latest
+docker pull f5devcentral/attributions-generator:latest
latest: Pulling from f5devcentral/attributions-generator
Digest: sha256:8ed14ab8d1166ab1c60b500177570edccc5558818a7c6846c32f2d030a86d770
Status: Downloaded newer image for f5devcentral/attributions-generator:latest
+RUN_ARGS=(--rm -v $PWD:$PWD -e LOCAL_USER_ID=$(id -u))
++id -u
+docker run --rm -v /home/travis/gopath/src/github.com/Basavaraju013/k8s-bigip-ctlr:/home/travis/gopath/src/github.com/Basavaraju013/k8s-bigip-ctlr -e LOCAL_USER_ID=1001 f5devcentral/attributions-generator:latest /usr/local/bin/flatfile-backend.py --project-path=/home/travis/gopath/src/github.com/Basavaraju013/k8s-bigip-ctlr
standard_init_linux.go:195: exec user process caused "exec format error"
Makefile:139: recipe for target 'flatfile_attributions.json' failed
make: *** [flatfile_attributions.json] Error 1
```
its will fails on ppc64le architecture.

**Comment by mkumatag** [comment]
@sjberman @amudukutore @bmarshall13 @ssurenr Any idea from where is this docker image `f5devcentral/attributions-generator:latest` is built?

**Comment by amudukutore** [comment]
The source is on an F5 internal repo. I'm not sure I understand why you need to change this given that the github travis CI pipelines should be able to use the existing container running on their x86 runners. If its for your own fork of the k8s-bigip-ctlr repo, perhaps you can disable building the docs (which is where this container is used).

**Comment by mkumatag** [comment]
> The source is on an F5 internal repo. I'm not sure I understand why you need to change this given that the github travis CI pipelines should be able to use the existing container running on their x86 runners. If its for your own fork of the k8s-bigip-ctlr repo, perhaps you can disable building the docs (which is where this container is used).

We are planning to push build and publish k8s-bigip-ctlr for ppc64le architecture, so part of that we were thinking of adding ppc arch to .travis.yaml to build. I think in this case, if it is not mandatory we can skip building doc on ppc64le arch.

**Comment by Basavaraju013** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/issues/807 issue is opened for creating multi-arch docker image.

**Comment by Basavaraju013** [comment]
@amudukutore i have commented #make docs for ppc64le platform. here is the PR for this.
https://github.com/F5Networks/k8s-bigip-ctlr/pull/808

**Comment by nokace** [comment]
We do not have validated support for a Power PC integration at this time. Closing issue at this is community supported. Thank you!
