### ISSUE TITLE
k8s-bigip-ctlr-deployment pod restart | fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by digambar01** [F5Networks/k8s-bigip-ctlr#842]
#### Description
Observing k8s-bigip-ctlr-deployment-xxx pod restart at random hours,
CPU or memory usage is normal. 
Error:  fatal error: concurrent map read and map write

#### Kubernetes Version
1.10

#### Controller Version
1.5.0

#### BIG-IP Version
13.1

#### Diagnostic Information
All logs for pod previous restart, 

```sh
oroutine 146 [running]:
runtime.throw(0x1cc259a, 0x21)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420d49be8 sp=0xc420d49bc8
runtime.mapaccess2_faststr(0x1abb520, 0xc420366240, 0xc420aa4420, 0x25, 0x0, 0xc4209efd40)
        /usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc420d49c48 sp=0xc420d49be8
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).checkValidConfigMap(0xc420192380, 0x1c73200, 0xc42026a108, 0xc420d49f38, 0x2, 0x2, 0x1)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:51 +0x1ca fp=0xc420d49cf8 sp=0xc420d49c48
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).enqueueConfigMap(0xc420192380, 0x1c73200, 0xc42026a108)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:571 +0x46 fp=0xc420d49d68 sp=0xc420d49cf8
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).newAppInformer.func2(0x1c73200, 0xc42026a108, 0x1c73200, 0xc42026a108)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:496 +0x3e fp=0xc420d49d90 sp=0xc420d49d68
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(0xc4204729e0, 0xc4204729f0, 0xc420472a00, 0x1c73200, 0xc42026a108, 0x1c73200, 0xc42026a108)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/controller.go:199 +0x5d fp=0xc420d49dc0 sp=0xc420d49d90
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate(0xc420180520, 0x1c73200, 0xc42026a108, 0x1c73200, 0xc42026a108)
        <autogenerated>:55 +0x8c fp=0xc420d49e08 sp=0xc420d49dc0
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc420738160, 0xc420126b40)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x2d1 fp=0xc420d49f50 sp=0xc420d49e08
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420d49f58 sp=0xc420d49f50
created by github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:402 +0xb1

goroutine 1 [chan receive, 4436 minutes]:
main.main()
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/cmd/k8s-bigip-ctlr/main.go:635 +0xe06
.
.
.
.
.
.
.
```

**Comment by vincentmli** [comment]
have you tried newer controller version like 1.7.1 or 1.8.1 that is just released?

**Comment by vincentmli** [comment]
this could be some kind of race condition, I would recommend to build the CC with race detector:

<pre>

diff --git a/build-tools/_build-lib.sh b/build-tools/_build-lib.sh
index 22cb69a..cc8f291 100755
--- a/build-tools/_build-lib.sh
+++ b/build-tools/_build-lib.sh
@@ -70,7 +70,7 @@ go_install () {
  # Declare seperate from assign, so failures aren't maked by local
  local BUILDDIR
  BUILDDIR=$(get_builddir)
-  local GO_BUILD_FLAGS=( -v -ldflags "-extldflags \"-static\" -X main.version=${BUILD_VERSION} -X main.buildInfo=${BUILD_INFO}" )
+  local GO_BUILD_FLAGS=( -v -race -ldflags "-extldflags \"-static\" -X main.version=${BUILD_VERSION} -X main.buildInfo=${BUILD_INFO}" )

  mkdir -p "$BUILDDIR"
  (

</pre>

**Comment by mdditt2000** [comment]
@digambar01 did you upgrade to the newer controller version 1.8.1?

**Comment by digambar01** [comment]
I will update and update you after upgrade, currently it's in production
and can not be changed for now.

**Comment by digambar01** [comment]
Hi , sorry for late respond, we tried directly with v 1.12.0  "f5networks/k8s-bigip-ctlr:1.12.0" and didn't observed this issue repeating. Also found it's really smoother than earlier for VIP creation operation.

**Comment by mdditt2000** [comment]
@digambar01 thank you for your feedback. The team is working diligently to improve quality. Let us know if you have any questions.
