### ISSUE TITLE
Use of Common Partition

### ISSUE THREAD

**Issue by spirrello** [F5Networks/k8s-bigip-ctlr#879]
#### Description
It would be nice to use the Common partition for existing K8s deployments that are already using F5 to expose services so that users won't need to rearchitect their existing deployments.

Is this a hard requirement to use the k8s partition and if so can you explain why?

#### Kubernetes Version
1.13.x

#### Controller Version
Haven't implemented it yet

#### BIG-IP Version
13.1.0.7

**Comment by mdditt2000** [comment]
@spirrello with CIS 1.9 you can use as AS3 declaration to reference profiles/certs/policies from the common partition. CIS 1.9 allows the user to create a partition of the big-ip for the tenant/app or multiple apps. Please read more about AS3 https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html

CIS/CC cannot write to common unless it is GSLB.

**Comment by spirrello** [comment]
I feel writing to the Common partition should be explored after all what is the difference between k8s-bigip-ctlr creating VIPs on an F5 vs an Ansible Playbook or Terraform script.  These use cases are all analogous and k8s-bigip-ctlr should provide the user an option to which partition to create VIPs – in my scenario we’d prefer to use the Common partition for everything.

k8s-bigip-ctlr is just another automation “tool” for creating VIPs the only difference is that it’s a controller that watches the K8s API on when to take action.

**Comment by mdditt2000** [comment]
Sure i understand what you are saying but why not create a tenant "partition" that can reference say your app-owner or repo? This is more devops like. Treat the common partition more like a admin partition or cert/asm management etc. Use AS3 to simply reference the objects. Its very clean and easy to migrate/manage configurations across clouds etc.

**Comment by spirrello** [comment]
Because we have F5 available in all data centers using the Common partition with all of our approved/existing VLANs and would be a major architectural shift to force our practices to begin using a new partition.

**Comment by mdditt2000** [comment]
All networking/vlans/tunnels etc are defined in common. Only application deployment "vip etc" is defined in a non-common partitions say "K8S"

**Comment by spirrello** [comment]
That’s the biggest problem I have with this.  We have our VLANs for our VIPs in the Common Partition.

**Comment by mdditt2000** [comment]
@spirrello can we chat. Please ping me so we can setup a meeting to discuss common partitions etc.

**Comment by mdditt2000** [comment]
Closing issues. Spoke with @spirrello on the phone

**Comment by kunalpuriii** [comment]
@mdditt2000 can you cross reference the VIP in different partition through CIS AS3 integration.
e.g. Pool and pool members are in AS3 partition, however VIP in common or different partition. Does it works ? if yes can you provide reference AS3 code.

Thanks
Kunal

**Comment by mdditt2000** [comment]
@kunalpuriii soon, currently AS3 does not allow you to share VIP from a different partition. Please watch the following AS3 githib issue https://github.com/F5Networks/f5-appsvcs-extension/issues/219

**Comment by kunalpuriii** [comment]
thankyou @mdditt2000
