### ISSUE TITLE
Add liveness for the bigip-ctlr

### ISSUE THREAD

**Issue by liorfranko** [F5Networks/k8s-bigip-ctlr#932]
#### Description
Please add liveness for the bigip-ctlr

#### Kubernetes Version
1.11.6

#### Controller Version
1.8.1

#### BIG-IP Version
12.1.2

**Comment by mdditt2000** [comment]
https://jira.pdsea.f5net.com/browse/CONTCNTR-178

**Comment by ssurenr** [comment]
Docs updated to use liveness probe on BIG-IP Controller.
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html#run-health-checks
