### ISSUE TITLE
[DOC] Applying sample f5-k8s-sample-rbac.yaml errors with Unsupported value: “rbac.authorization.k8s.io”

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#938]
#### Description

Using the file

```
https://clouddocs.f5.com/containers/v2/_downloads/d96ccbe17a36bb37e1693532669a795c/f5-k8s-sample-rbac.yaml
```

errors with the following message

```
clusterrole.rbac.authorization.k8s.io/bigip-ctlr-clusterrole created
The ClusterRoleBinding "bigip-ctlr-clusterrole-binding" is invalid: subjects[0].apiGroup: Unsupported value: "rbac.authorization.k8s.io": supported values: ""
```

This error is described in https://stackoverflow.com/questions/53050611/unsupported-value-rbac-authorization-k8s-io and the solution proposed fixes it

#### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

#### Controller Version
NA

#### BIG-IP Version

NA

**Comment by ssurenr** [comment]
@kkinch at file `f5-k8s-sample-rbac.yaml`, line 31 the value should be `""` instead of `rbac.authorization.k8s.io`

**Comment by kkinch** [comment]
@ssurenr This is completed. Thanks!

subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: <controller_namespace>

https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html

**Comment by ssurenr** [comment]
@alonsocamaro Thanks for letting us know.
