### ISSUE TITLE
Ingress Resource: Http to Https redirect not working

### ISSUE THREAD

**Issue by amarshaw** [F5Networks/k8s-bigip-ctlr#947]
#### Description
we are using k8s-bigip-ctlr as a LB for our k8 environment, we are facing issue with http to https redirect, its not working, in pod we are defining below Annotations.

```
Annotations:
  ingress.kubernetes.io/allow-http:    false
  ingress.kubernetes.io/ssl-redirect:  true

```
But still our http url is not getting redirect to https url.

#### Kubernetes Version
1.14.1

#### Controller Version
1.9.1

#### BIG-IP Version
BIG-IP 13.1.1.4 Build 0.0.4 Point Release 4
#### Diagnostic Information
Our Ingress file :
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    virtual-server.f5.com/health: '[{"path": "mydns.com/",
      "send": "GET / HTTP/1.1\r\n", "interval": 5, "timeout": 10 }]'
    virtual-server.f5.com/ip: x.x.x.x
    virtual-server.f5.com/partition: k8stest
  creationTimestamp: "2019-06-17T05:11:34Z"
  generation: 2
  labels:
    app: gocd-template
  name: gocd-template
  namespace: k8stest-gocdtemplates
  resourceVersion: "17924672"
  selfLink: /apis/extensions/v1beta1/namespaces/k8stest-gocdtemplates/ingresses/gocd-template
  uid: xxxxxxxxxxxxxxxxxx
spec:
  rules:
  - host: mydns.com
    http:
      paths:
      - backend:
          serviceName: gocd-template
          servicePort: 80
        path: /
  tls:
  - hosts:
    - mydns.com
    secretName: /Common/ssl-intranet
status:
  loadBalancer:
    ingress:
    - ip: x.x.x.x

```

**Comment by vincentmli** [comment]
can you try CC/CIS with AS3 ? I know AS3 1.9.1 does not support ingress yet. I have a patch to fix the http to https redirect in CC/CIS itself, but it is not merged in CC/CIS, would you like to try that?

**Comment by amarshaw** [comment]
Does ingress support on 1.9.0, we are facing the same issue with 1.9.0 as well.

**Comment by amarshaw** [comment]
We have  created AS3 for you app as bellow.

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  template: |-
    {
          "class":"AS3",
          "action":"deploy",
          "persist":true,
          "declaration":{
            "class":"ADC",
            "schemaVersion":"3.10.0",
            "id":"1847a369-5a25-4d1b-8cad-5740988d4423",
            "label":"Sample AS3 Template",
            "remark":"HTTP application",
            "stark":{
              "class":"Tenant",
              "blog":{
                "class":"Application",
                "template":"https",
                "serviceMain":{
                  "class":"Service_HTTPS",
                  "virtualAddresses":[
                    "10.191.118.27"
                  ],
                  "virtualPort":443,
                  "pool":"web_pool"
                },
                "web_pool":{
                  "class":"Pool",
                  "monitors":[
                    "https"
                  ],
                  "members":[
                  {
                    "servicePort":443,
                    "serverAddresses":[
                      "10.191.118.27"
                    ]
                  }
                  ]
                }
              }
            }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-06-28T10:17:29Z"
  labels:
    as3: "true"
    f5type: virtual-server
  name: as3-template-https
  namespace: k8sdev-gocdtemplates-dev
  resourceVersion: "98489980"
  selfLink: /api/v1/namespaces/k8sdev-gocdtemplates-dev/configmaps/as3-template-https
  uid: ef774c41-998d-11e9-9f62-0050569aee46

```
We have certificate install in LB it self and in ingress we define it like this.

```
  tls:
  - hosts:
    - gocd-templates-k8stest.intranet.mckinsey.com
    secretName: /Common/ssl-intranet
status:
  loadBalancer:
    ingress:
    - ip: x.x.x.x
```
Can you tell me how we defile certificate in AS3 config map as mention above.

**Comment by mdditt2000** [comment]
thank you @amarshaw for creating the AS3 configmap. Folks we need to leverage AS3 instead of a irule for ingress. This issue will be resolved in CIS 1.11 when we go from ingress to AS3. The ingress.kubernetes.io/ssl-redirect: "true" annotation is not needed since AS3 creates the redirect by default.

**Comment by mdditt2000** [comment]
@amarshaw please refer to the certs in common as shown in the AS3 example. https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#referencing-an-existing-ssl-certificate-and-key-in-the-common-partition

"tlsserver_local_cert": {
          "class": "Certificate",
          "certificate": {"bigip":"/Common/default.crt"},
          "privateKey": {"bigip":"/Common/default.key"}

Please let me know if you need additional help.

**Comment by mdditt2000** [comment]
@amarshaw yes CIS 1.9.1 doesn't make any changes to ingress. CIS 1.9 only adds AS3 support which will be the new API for BIG-IP. We are going to add functionality in CIS 1.11 where we will create a AS3 declaration from an ingress statement. However timeline is around September/October

**Comment by amarshaw** [comment]
Do we need to make any changes in our Big-IP to enabling AS3, or f5-bigip-ctlr 1.9 will take care it automatically.

**Comment by trinaths** [comment]
@amarshaw - In BIGIP you need install AS3 RPM. Please refer https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/installation.html

**Comment by amarshaw** [comment]
So first we need to install AS3 RPM in BIGIP, then we need to configure AS3 configmap in our app, then only it work and AS3 is available with CIS 1.11, which will release on September/October.

Correct me if i am wrong.

**Comment by trinaths** [comment]
AS3 ConfigMap support exists with 1.9 version. Support for Ingress or OpenShift Routes will be included in upcoming releases.

**Comment by amarshaw** [comment]
yes and we use  Ingress, so we need to wait till 1.11 ?

**Comment by mdditt2000** [comment]
@amarshaw CIS 1.9.1 with a AS3 configmap will give you Http to Https redirect by default. 

CIS 1.11 we plan to take a K8S ingress + annotation and create a AS3 declaration for you. However that work hasn't started.

**Comment by mdditt2000** [comment]
CONTCNTR-862

**Comment by mdditt2000** [comment]
PM Jira CONTCNTR-381 - tracking fix for CIS 1.10 Mid August.

**Comment by mdditt2000** [comment]
Fix is coming in CIS release 1.9.2 schedule for July 26th.

**Comment by linecolumn** [comment]
Can http to https fix be incorporated to non-AS3 version?

While here, we want to use our f5s as frontend/ingress to our k8s clusters, the question is should we, will future work be only AS3 based?

**Comment by trinaths** [comment]
The fix is incorporated in 1.9.2 version, yet to be released.

**Comment by mdditt2000** [comment]
@linecolumn yes. We are going to re-factor the ingress resource in the next release of CIS 1.12. We are replacing the old python based schema/API with AS3. AS3 will be behind the scenes. You will just use ingress resources etc.

**Comment by mdditt2000** [comment]
Filed Jira for PM tracking CONTCNTR-1121

**Comment by veeramalla-f5** [comment]
We have fixed the issues related to http to https redirect as part of pull requests
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1126 
https://github.com/F5Networks/k8s-bigip-ctlr/pull/1124

This will be subjected to release 1.13 which will be released in mid of Jan.
