### ISSUE TITLE
[RFE] AS3 functionality should support POST method's action "patch"

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#951]
#### Description

[Unsure if this should be considered a bug or enhancement.]

AS3's POST method allows the action "patch". My intention was to use this feature to add L7 routes into an existing AS3 declaration. This simplifies the CI/CD pipeline by not requiring the customer of building a full AS3 declaration with all the routes each time a new route is added.

This action "patch" can be used for other useful use cases as well.

This approach is described in 

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/as3-api.html#post-actions

and an example can be found here:

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/big-iq.html

#### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```
#### Controller Version

1.9.0

#### BIG-IP Version

NA

#### Diagnostic Information

Sending the patch request through Postman is just fine (see the attached file)

[POST-patch-action.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/3335022/POST-patch-action.txt)

and when submitting the same declaration throught k8-bigip-ctrl it complains with the following message:

```
2019/06/27 13:39:38 [ERROR] No ADC class declaration found.
2019/06/27 13:39:38 [ERROR] [as3] Error processing template

```

I wonder if by removing this check of ADC class declaration, then k8s-bigip-ctlr would support this.

See in the next files the configuration use for k8s-bigip-ctrl.

[f5-as3-routing-waf-ssl.deploy.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/3335051/f5-as3-routing-waf-ssl.deploy.yaml.txt)
[f5-as3-routing-waf-ssl.add-route.yaml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/3335052/f5-as3-routing-waf-ssl.add-route.yaml.txt)

Note: I find that when implementing this feature the ConfigMap should actually be updated with the resulting AS3 declaration to support persistence of the final configuration.

**Comment by ssurenr** [comment]
This can be achieved at the operator end using command line utilities as `jsonpatch` to stitch individual routes from their repository to the main declaration and send as a single declaration to CIS.
Marked this issue as an enhancement.

**Comment by mdditt2000** [comment]
@alonsocamaro who is requesting support for jasonpatch? We are going to be leveraging a new template framework in the future that could illuminating you having to POST the entire declaration. Just update the declaration and apply the configmap. Its alot simpler than jasonpatch.

**Comment by mdditt2000** [comment]
Closing this issue out. At this time there are no plans to support JSONPATCH with AS3.
