### ISSUE TITLE
Better documentation around AS3 and Service Labels

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/k8s-bigip-ctlr#982]
#### Description
Documentation for AS3 integration seems to overstep the need for the "app:" label on the Service.

All working examples require the "app:" label to work, however, the documentation doesn't highlight this. However, the picture on the page does have it as ``app: f5-example-web``, but there is no example of a Deployment this matches up too.

Documentation Page: https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html#container-ingress-services-and-as3-extension-integration

#### Kubernetes Version
N/A

#### Controller Version
3.10+

#### BIG-IP Version
N/A

#### Request

It would be better if there was some more information around the whole label section, something like:

```
app: [string] - This is a label used to match the deployment > spec > selector > matchLabels peer, must start with app, must meet DNS naming scheme
cis.f5.com/as3-tenant: [string] - This is the AS3 Partition Name in your AS3 declaration, must not include ``-`` (hyphens)
cis.f5.com/as3-app: [string] - This is the AS3 Application "Class" name in your AS3 declaration
cis.f5.com/as3-pool: [string] - This is the Pool in the AS3 Declaration you wish to manipulate, paired with the AS3 Tenant and App
```

**Comment by mdditt2000** [comment]
PM Jira CONTCNTR-977 for tracking. Assigned to tech writter

**Comment by mdditt2000** [comment]
@jmcalalang please can you review and provide feedback on the improvements 

1. Replaced existing graphic with new. 
2. Replaced existing Example Service and Example Deployment with examples based on HTTP use case.

https://clouddocs.f5networks.net/containers/latest/kubernetes/kctlr-k8s-as3.html

**Comment by mdditt2000** [comment]
@jmcalalang please can you review the changes from Kevin. I would like to close this issue out this sprint. TY

**Comment by mdditt2000** [comment]
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html - improvement mad. Closing issue out

**Comment by jmcalalang** [comment]
I looked this over, its wayyyy better, thank you!!
