### ISSUE TITLE
Can AS3 can support two and more pools in the future ? 

### ISSUE THREAD

**Issue by luruiqiang** [F5Networks/k8s-bigip-ctlr#997]
#### Description
I find some limit about as3. one of the limits is "AS3 pool class declarations support only one load balancing pool." (https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html)

Now the ingress of kubernetes can use many services . Can AS3 can support two and more pools in the future ? 

#### Kubernetes Version
1.13

#### Controller Version
1.9.1

#### BIG-IP Version
12.1

**Comment by mdditt2000** [comment]
Thanks you for your valuable feedback. Created Jira CONTCNTR-1005 for PM tracking. Checking to see if this something we can add to the next release.

**Comment by luruiqiang** [comment]
thanks. I look forward to getting it in the next release.

**Comment by mdditt2000** [comment]
Testing in progress for one of the created template to validate the traffic among multiple pools.

**Comment by mdditt2000** [comment]
@luruiqiang dev work is complete and regression will begin soon. Would you like a early build to begin some testing?

**Comment by luruiqiang** [comment]
I found that 1.11 had been released last week. Would you like to give me an example to use it?

**Comment by srivastavnitin24** [comment]
@luruiqiang Please find the attached document for the implementation.

[AS3 to use two or more pools.docx](https://github.com/F5Networks/k8s-bigip-ctlr/files/3727503/AS3.to.use.two.or.more.pools.docx)

**Comment by mdditt2000** [comment]
@mdditt2000 to add example to https://github.com/mdditt2000/kubernetes/tree/dev/cis-1-10
