### ISSUE TITLE
 Can CIS supports only two or more AS3 ConfigMap instances ?

### ISSUE THREAD

**Issue by luruiqiang** [F5Networks/k8s-bigip-ctlr#998]
#### Description
Now, CIS supports only one AS3 ConfigMap instance(https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html).  In our business environment, we have to config all vs in one configmap file. There are some risk when we config one VS with some error information.  We hope that CIS can support two or more AS3 ConfigMap instance( we can config every VS in one ConfigMap).

#### Kubernetes Version
1.13

#### Controller Version
1.9.1

#### BIG-IP Version
12.1

**Comment by mdditt2000** [comment]
Today its only possible to have one configmap per AS3 tenant. You can have multiple tenants allowing for multiple configmap file. Let me know if you need more details

Example 

AS3-HR - configmap - Virtual
AS3-SAP - configmap - Virtual

Etc

**Comment by luruiqiang** [comment]
If all VSs are created in one configmap and we want to modify one VS, we have to modify the configmap file. If we have a lot of VS in one configmap file, there are some risk when we modify multiple VSs.
So it is better that I can create/modify/delete one VS in one configmap file.

**Comment by mdditt2000** [comment]
@luruiqiang you have the flexibility to create as many virtual servers per tenant as you want. They just need to be different. Look at https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-9/A6/f5-as3-configmap.yaml

Apps A1 to A6, You can add another partition and additional. I can demo this if you have time.

**Comment by luruiqiang** [comment]
sorry, I can't get the yaml file (https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-9/A6/f5-as3-configmap.yaml). 
It's better that you can show me a video.

**Comment by luruiqiang** [comment]
I found that 1.11 had released last week. but I can't get the yaml file (https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-9/A6/f5-as3-configmap.yaml). I don't know how to use it. please give me some examples. Thanks.

**Comment by luruiqiang** [comment]
I hope that we can have a multi-configmap per AS3 tenant. Do you have some plans?

**Comment by veeramalla-f5** [comment]
@luruiqiang CIS supports this feature as part of 2.1 release. Please switch to the latest version(2.1)

Must:
Every ConfigMap should have unique tenants, else CIS will override the tenant configuration from one configmap with another.
