### ISSUE TITLE
Can we not label service when I use AS3 ?

### ISSUE THREAD

**Issue by luruiqiang** [F5Networks/k8s-bigip-ctlr#999]
#### Description
Now, When I use AS3, I must label my service:   
  "cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: f5-hello-world
    cis.f5.com/as3-pool: web_pool "

I must modify service( It is managed other department. I only config F5 CIS). Sometime, it can't be controlled by me. 

Can I not use label to service ?  I remember that we can use service name in iApp, Can I use the name in AS3 directly ?

#### Kubernetes Version
1.13

#### Controller Version
1.9.1

#### BIG-IP Version
12.1

**Comment by mdditt2000** [comment]
thanks for the feedback. Creating a story for tracking

**Comment by mdditt2000** [comment]
Jira CONTCNTR-1004 - PM tracking

**Comment by luruiqiang** [comment]
Thanks.

**Comment by luruiqiang** [comment]
I found that 1.11 had been released last week. Whether the issue is resolved?  If not, when the issue will be resolved?

**Comment by ssurenr** [comment]
@luruiqiang AS3 Configmap feature specifically developed considering this scenario. As a BIG-IP administrator, you create the AS3 declaration and pass the tenant, application and pool names to the development team who deploy the application. As part of the application deployment, they add these values as annotations in the service they create.
